### ISSUE TITLE
feat: nav 配置省略时支持自动使用 group 配置

### ISSUE THREAD

**Issue by xiexingen** [umijs/dumi#100]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
![image](https://user-images.githubusercontent.com/7939085/75984669-c9a9d280-5f25-11ea-86c1-dd1c7d1b7e1f.png)
如图，感觉有点多余，doc跟site只是模式不同 其实读取的标题、排序这些应该还是一致的

**Comment by PeachScript** [comment]
不是的，group 始终对应左侧 menu，nav 对应导航头，两者在 site 模式下会同时存在，在 doc 模式下只会有前者存在

**Comment by xiexingen** [comment]
> 不是的，group 始终对应左侧 menu，nav 对应导航头，两者在 site 模式下会同时存在，在 doc 模式下只会有前者存在

OK 明白了

**Comment by PeachScript** [comment]
这里其实也是个 enhancement，nav.title 支持 fallback 到 group.title，group.title 支持 fallback 到 h1，这样用户就能少配点东西

**Comment by xiexingen** [comment]
> enhancement

是的，感觉可以默认用group 如果配置了nav才用nav

**Comment by xiexingen** [comment]
还有个问题，如果同时配置了group和nav当模式切换到doc时，这种的左侧菜单都不会出来

**Comment by PeachScript** [comment]
v1.1.19 优化 3 点：
1. goup 和 nav 优先兜底成文件夹目录名
2. group 增加兜底为 nav.title
3. 路由 title 优先兜底成 group or nav 名

优化点正好覆盖该场景，后续配置了 nav 可以不配置 group，issue 关闭
