### ISSUE TITLE
feat: 增加对bitbucket 平台  subgroups 的支持

### ISSUE THREAD

**Issue by iolh** [umijs/dumi#1000]
### Description
 当前设置为 gitlab 时，若 url 涉及 subgroups 会对其进行特殊处理。
 请求增加对 bitbucket 的支持
### Solution
![image](https://user-images.githubusercontent.com/42227330/149745297-1d41a6b7-dfbd-46b7-8f30-5b4c1da7420f.png)

**Comment by iolh** [comment]
![image](https://user-images.githubusercontent.com/42227330/149745633-528cffca-1630-4c74-92b3-12d009bf925b.png)
文档地址在这里

**Comment by PeachScript** [comment]
v1.1.40 已支持
