### ISSUE TITLE
左侧菜单栏是怎么配置折叠的？

### ISSUE THREAD

**Issue by qq756585379** [umijs/dumi#1002]
![image](https://user-images.githubusercontent.com/14193713/150466859-484915ce-4175-47f3-abc8-5fee0b8ab282.png)

**Comment by PeachScript** [comment]
默认主题不支持折叠，官网折叠的是正文中的 toc，参考：https://d.umijs.org/zh-CN/config/frontmatter#toc

**Comment by florencemu** [comment]
https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠

**Comment by ChenYCL** [comment]
> https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠

仓库没看到源码额
