### ISSUE TITLE
请问为什么我左侧菜单会新增属性锚点

### ISSUE THREAD

**Issue by Wuuuu** [umijs/dumi#1004]
### Sample Code
![image](https://user-images.githubusercontent.com/15084300/150791493-9f969d1a-df0a-482d-b5f0-455d4a908757.png)

**Comment by PeachScript** [comment]
为了节省横向空间，移动端模式下 toc 默认展示在 Menu 里，不需要可以设置为 false：https://d.umijs.org/zh-CN/config/frontmatter#toc

**Comment by lbyupup** [comment]
> [为了横向空间，移动端模式下c默认展示在Menu节约里，不需要设置为false： https](https://d.umijs.org/zh-CN/config/frontmatter#toc) ://d.umijs.org/zh-CN/config/frontmatter#toc[](https://d.umijs.org/zh-CN/config/frontmatter#toc)

请问需要在哪里设置false呢，pc端也出现这个问题。
