### ISSUE TITLE
在site模式下如果要把组件文档归到一个nav下有什么快捷配置吗？

### ISSUE THREAD

**Issue by orangeyyy** [umijs/dumi#1005]
### Question
配置将组件文档全部放到“组件”目录下，如果组件的文档中不配置路由信息，则点击组件查看文档菜单显示会有问题，但是每个组件的文档配置路由信息又是一样的，有办法设置不用配置nav：path 就能够正常路由到组件文档吗？

如下面的例子所示：有办法不用每次都配置nav:path吗？

### Sample Code
我的dumi配置：
```js
{
navs: [
    {
      {
        title: '组件',
        path: '/comp'
      },
      {
        title: 'Utils函数库',
        path: 'https://yc-utils.alibaba-inc.com',
      }
  ],
  menus: {
    /comp':[
      {
        title: '常规展示',
        children: ['Foo', 'Button'],
      }
    ]
  }
}
```
组件文档书写:
```markdown
---
nav:
  path: '/comp'
---
## 按钮
<code src="./demos/demo1.tsx"></code>

<API ></API>
```

**Comment by PeachScript** [comment]
用文件夹组织是最快的，不在同一个祖先文件夹内的 md 只能 `nav.path` 归类，规则参考：http://localhost:8001/zh-CN/guide/basic#%E7%BA%A6%E5%AE%9A%E5%BC%8F%E8%B7%AF%E7%94%B1
