### ISSUE TITLE
bug: Missing class properties transform.

### ISSUE THREAD

**Issue by loopbless** [umijs/dumi#1006]
### Versions

- dumi: 1.1.29
- node: v12.22.9
- npm: 6.14.15
- OS: Mac
- Browser: Chrome

### Steps to reproduce

```
Syntax Error: SyntaxError: /.../node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/icon-button.js: Missing class properties transform.
  69 | export default function createIconButtonComponent(Icon) {
  70 |   return class IconButton extends PureComponent {
> 71 |     static defaultProps = {
     |     ^
  72 |       backgroundColor: IOS7_BLUE,
  73 |       borderRadius: 5,
  74 |       color: 'white',

```

**Comment by loopbless** [comment]
> 你好@loopbless。为了便于定位和故障排除，我们需要您提供一个真实的例子。您可以点击[这里](https://github.com/umijs/dumi-template/generate)创建一个dumi项目，并提供GitHub仓库地址并复现示例。
> 
> 你好@loopbless为了方便和排排，我们需要你提供一个[新](https://github.com/umijs/dumi-template/generate)的实例问题。

https://github.com/loopbless/dumi-example

**Comment by PeachScript** [comment]
为了编译性能默认是不对依赖做完整的 babel 编译的，正常情况下依赖的产物都应该是编译后的产物，如果要做额外的编译可以配置 `extraBabelIncludes`：https://d.umijs.org/config#extrababelincludes

但加上配置后使用你提供的仓库试了一下仍然会挂，原因是 `@expo/vector-icons` 的产物中有 js 文件内写 jsx 的不规范写法，例如：https://unpkg.com/browse/@expo/vector-icons@12.0.5/build/vendor/react-native-vector-icons/lib/tab-bar-item-ios.js ，修改所有相关 js 文件为 jsx 后可以编译成功

非标依赖不在 dumi 的处理范围内，如果无法控制依赖的质量，可以自行通过 chainWebpack 修改 rule 实现将 node_modules 下的 js 文件当做 jsx 编译
