### ISSUE TITLE
bug: 文档中DEMO的预览和二维码的预览效果不一致

### ISSUE THREAD

**Issue by hqwlkj** [umijs/dumi#1008]
### Versions

- dumi: ^1.1.26
- node: v16.9.1
- npm: 7.21.1
- OS: MacOS
- Browser: Google Chrome 版本 98.0.4758.80（正式版本） (x86_64)

### What is Expected?
![image](https://user-images.githubusercontent.com/12181423/152716474-2d368fe1-2d3c-44cf-a51e-60c75f81a3ee.png)
希望手机预览和我二维码预览的效果一致。目前二维码和新窗口打开的效果和实际的效果不一致；原因是 `<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=0.5,maximum-scale=0.5,minimum-scale=0.5,viewport-fit=cover">`
这里的 `initial-scale、maximum-scale、minimum-scale` 的值设置成了 0.5

### What is actually happening?

![image](https://user-images.githubusercontent.com/12181423/152716790-5cec9f24-9506-4cc9-a951-9e8357c23012.png)

**Comment by PeachScript** [comment]
高清方案可以通过配置 umi-hd 来修改，参考：https://d.umijs.org/zh-CN/theme#dumi-theme-mobile
<img width="1149" alt="图片" src="https://user-images.githubusercontent.com/5035925/152717413-08177c26-7252-4990-b963-49c1f4d94958.png">

**Comment by hqwlkj** [comment]
已经配置处理了， @PeachScript  感谢
