### ISSUE TITLE
bug: Missing header margins if you use headers below code blocks

### ISSUE THREAD

**Issue by 1247748612** [umijs/dumi#1009]
代码块下方如果使用标题没有外边距
![image](https://user-images.githubusercontent.com/29533304/152756121-b45bc060-39d9-4956-b049-e2d2e1299315.png)

### Steps to reproduce

https://procomponents.ant.design/components/group#%E5%A4%8D%E6%9D%82%E8%81%94%E5%8A%A8

#### Examples
```markdown
<code src="./demos/dependencies.tsx" height="500px" title="schema dependencies" />
### Not Margin
```

### What is Expected?

有外边距

**Comment by cnyballk** [comment]
> 这是个 bug，需要修复

怎么说？

**Comment by PeachScript** [comment]
看错了 👀
