### ISSUE TITLE
feat: 期望mode=doc的文档模式支持展示nav导航栏配置. 

### ISSUE THREAD

**Issue by guiyu1230** [umijs/dumi#1012]
### Description
期望mode=doc的文档模式支持展示nav导航栏配置. 
### Solution
![image](https://user-images.githubusercontent.com/33077436/153379368-896bf96b-a379-4819-a345-52dbc798e6a9.png)

**Comment by PeachScript** [comment]
doc 模式的特点就是没有导航，参考：https://d.umijs.org/zh-CN/config#mode
