### ISSUE TITLE
dumi 启动慢，是否有方法可以看启动的详细信息

### ISSUE THREAD

**Issue by zww-v5** [umijs/dumi#1014]
1、dumi 目前在本地启动的速度有点慢，有时是2分钟，有时是4分钟。我本地的 md 文件有 90个，md 中的示例代码都采用 iframe 的方式展示，示例代码的文件有 200 个左右。
<img width="695" alt="image" src="https://user-images.githubusercontent.com/9295948/153579162-dc6349d3-50b1-4746-b1fe-bd6974e554d8.png">

2、目前我采用 DEBUG=* 的方式想分析运行时的情况，但会提示如下信息无法正常启动，想问下有没有其他的方法可以查看下启动的详细信息，我想看下具体耗时的地方在哪？
<img width="610" alt="image" src="https://user-images.githubusercontent.com/9295948/153578200-e5764be2-6a61-4267-9c4d-ec150a38d5c7.png">

**Comment by PeachScript** [comment]
可能 log 太多挂了，`DEBUG=dumi:*` 试下

**Comment by PeachScript** [comment]
2min 的冷启动其实不算慢，可以开 MFSU 二次启动会变快很多

**Comment by zww-v5** [comment]
> 

恩，好的，谢谢，我这尝试下
