### ISSUE TITLE
bug: 组件API只展示自己封装的属性，不展示node_modules中的

### ISSUE THREAD

**Issue by Jarryxin** [umijs/dumi#1015]
### Versions

- dumi:1.1.38
- node:12.22.5
- npm:6.14.14
- OS:mac os
- Browser: 谷歌

### Steps to reproduce
> 参考：https://d.umijs.org/zh-CN/config#apiparser

配置
```js
apiParser: {
    propFilter: {
      skipNodeModules: true,
    },
},
```

组件
```ts
export interface IButton {
  /**
   * @default ''
   * @description 设置按钮颜色
   */
  color?: string;
}
const DButton: React.FC<IButton & ButtonProps> = (props) => (
  <Button
    style={{
      color: props.color,
    }}
    {...props}
  >
    {props.children}
  </Button>
);
```

### What is Expected?
期望使用  <API></API> 展示自定义属性 color

### What is actually happening?

<API></API>未展示 color 属性
![image](https://user-images.githubusercontent.com/21277570/153792922-1d9c3ff6-813d-47d7-be1d-7b9a3f4bf99e.png)

**Comment by PeachScript** [comment]
v1.1.39 已修复
