### ISSUE TITLE
bug: 构建成功之后卡死

### ISSUE THREAD

**Issue by kagawagao** [umijs/dumi#102]
### Versions

- dumi: `v1.0.2`
- node: `v13.8.0`
- npm: `v6.13.7`
- OS: `MacOS 10.15.4 Beta (19E250c)`
- Browser: `82.0.4078.0`

### Steps to reproduce
执行 `dumi build`

### What is Expected?

构建完成之后进程结束

### What is actually happening?

进程卡死

![image](https://user-images.githubusercontent.com/6930280/76057522-c0b41200-5fb4-11ea-8596-3cd59b5deaa2.png)

**Comment by fanxin0503** [comment]
我也遇到了这个BUG，当markdown里面引入了code之后，build的时候就会卡死
dumi版本:1.0.2

**Comment by PeachScript** [comment]
请帮忙确认下 1.0.1 是否正常，感谢

**Comment by PeachScript** [comment]
发了 1.0.3，可以再试试看
