### ISSUE TITLE
外部demo文件中引用自身，ts报错如何解决

### ISSUE THREAD

**Issue by bitsu567** [umijs/dumi#1021]
### Question
外部demo文件中引用自身，ts报错如何解决
### Sample Code
// 拉了ahook库下来 执行yarn；第三句从外部引用自身，ts会报错，但是执行yarn start没问题
import { Table } from 'antd';
import React from 'react';
import { useAntdTable } from 'ahooks'; // Cannot find module 'ahooks' or its corresponding type declarations.ts(2307)

**Comment by PeachScript** [comment]
先 build 一遍生成产物，否则 package.json 中指向的模块是不存在的
