### ISSUE TITLE
api 的 hideTitle 无效，而且换肤插件中也无法自定义这个标题

### ISSUE THREAD

**Issue by zww-v5** [umijs/dumi#1022]
1、这个文档下说明的 hideTitle 属性实测无效：https://d.umijs.org/zh-CN/guide/advanced#api
<img width="597" alt="image" src="https://user-images.githubusercontent.com/9295948/154218014-ea978016-6c11-445c-9dae-601cbb8b2347.png">

2、在 api 这个组件的源码中也没有找到跟这个标题有关的处理：https://github.com/umijs/dumi/blob/master/packages/theme-default/src/builtins/API.tsx

**Comment by PeachScript** [comment]
`hideTitle` 是编译时行为，逻辑在这里：https://github.com/umijs/dumi/blob/804af48209184d017e248f0d9d89465ebc8b15b2/packages/preset-dumi/src/transformer/remark/api.ts#L42

**Comment by zww-v5** [comment]
经再次测试后，发现升级 dumi 后就可以生效了
