### ISSUE TITLE
bug: dumi 中引入 antd Select 组件无法使用

### ISSUE THREAD

**Issue by hang1017** [umijs/dumi#1023]
![image](https://user-images.githubusercontent.com/48704410/154285774-0a080e7a-535c-4b22-891f-c5e53b0dd335.png)

下拉选择项无法选中。
demo 如下：

[pros.zip](https://github.com/umijs/dumi/files/8080633/pros.zip)

**Comment by PeachScript** [comment]
应该是组件内部实现导致的，浮层上有 `pointer-events: none` 的行内样式：
<img width="1058" alt="图片" src="https://user-images.githubusercontent.com/5035925/154617970-f9771e69-ec8e-4257-a25a-6fec3a89f821.png">

**Comment by hang1017** [comment]
首先这个行内样式，是 antd 组件自带了。应该是和 dumi 内的某些样式起冲突导致的失效。
其次，我有试着修改 pointer-events：all 或者 pointer-events：auto 的效果。但是 antd Select 的整体效果还是失效的。

**Comment by hang1017** [comment]
@PeachScript

**Comment by hang1017** [comment]
@PeachScript 麻烦在帮忙看下哈，想了很久找不到解决办法。

**Comment by PeachScript** [comment]
> 应该是和 dumi 内的某些样式起冲突导致的失效

可以提供下排查定位的步骤，我这边看起来和 dumi 是无关的

我的步骤如下：
1. 背景：dumi 本身不带任何全局样式，如果冲突只可能是容器继承的样式出现冲突，先测试根节点渲染
2. 排查：自定义 `.dumi/theme/layout.tsx`，只在整个页面的 root 节点渲染这个组件
3. 结果：问题依然存在，所以推测问题还是出在组件实现上，以及直接引用 antd 的 Select 组件没有发现这个问题

**Comment by hang1017** [comment]
好的谢谢
