### ISSUE TITLE
bug:使用dumi-theme-mobile时，code 的 defaultShowCode设置成false无效

### ISSUE THREAD

**Issue by z448401921** [umijs/dumi#1024]
### Versions

- dumi:1.1.38
- dumi-theme-mobile:1.1.21

期望效果希望在显示手机的时候代码默认收缩，实际是展开的

### 使用代码
```
<code src='@src/pages/button.tsx' defaultShowCode="false" ></code>

```

**Comment by PeachScript** [comment]
有意为之，移动端主题下 demo 区域是没有的，考虑到展示效果会强制展开源代码，相关代码：https://github.com/umijs/dumi/blob/master/packages/theme-mobile/src/builtins/Previewer.tsx#L80

有特殊需求的话可以自定义 Previewer.tsx：https://d.umijs.org/zh-CN/theme/development
