### ISSUE TITLE
项目设置less生成组件不生效

### ISSUE THREAD

**Issue by majiang666** [umijs/dumi#1027]
### Question
项目设置less生成组件后不生效，改为.css就好了，是哪里设置的不对吗
### Sample Code
`.umirc.ts
defineConfig({
  lessLoader: {
    rules: [
      {
        test: /\.less$/i,
        use: [
          // compiles Less to CSS
          "style-loader",
          "css-loader",
          "less-loader",
        ],
      },
    ],
  }
})；`

**Comment by majiang666** [comment]
> Hello @majiang666. In order to facilitate location and troubleshooting, we need you to provide a realistic example. You can create a dumi project by clicking [here](https://github.com/umijs/dumi-template/generate) and provide the GitHub warehouse address and reproduce examples.
> 
> 你好 @majiang666, 为了方便定位和排查问题，我们需要你提供一个重现实例。你可以通过点击 [此处](https://github.com/umijs/dumi-template/generate) 创建一个 dumi 项目并提供 GitHub 仓库地址和重现实例。

您好，项目暂时未开源，还不能提供源码，本地配置：defineConfig({ lessLoader: { rules: [ { test: /\.less$/i, use: ["style-loader", "css-loader", "less-loader", ], }, ], } })；

生成组件库后，上传npm，检查了生成文件，less样式文件都在，但是样式未生效，改成css，重新安装就好了，是不是配置方式有误，复现方式有点麻烦，需要上传npm

**Comment by PeachScript** [comment]
没明白你的具体问题，从描述内容来看可能是配置文件错了

umirc.ts 只是文档打包配置，而且自带 less-loader；组件打包如果是用的 father-build，可以参考 father 的文档或 issue：https://github.com/umijs/father
