### ISSUE TITLE
bug: 引用发布后的主题，报错依赖找不到

### ISSUE THREAD

**Issue by qubaomingg** [umijs/dumi#1030]
### Versions

- dumi: 1.0.13
- node: v14.18.0
- npm: 6.14.15
- OS:11.5.2
- Browser: 90.0.4430.212

### Steps to reproduce
> 最基本、正常运行的 dumi 静态网站根目录
- tnpm i -g dumi-theme-didoc 
- tnpm start 

### What is Expected?
报错 
![image](https://user-images.githubusercontent.com/3271828/155694797-bf2ddda0-da6a-471b-844f-9e2463b04206.png)

### What is actually happening?
正常运行

**Comment by PeachScript** [comment]
缓存失效判定有点问题，重装下依赖或者 rm -rf src/.umi 后重新启动

**Comment by qubaomingg** [comment]
> 缓存失效判定有点问题，重装下依赖或者 `rm -rf src/.umi` 后重新启动

一样的，还是报错这个，对比了 `node_modules/dumi-theme-default` 和 `node_modules/dumi-theme-didoc` 我的主题没有 `es` 文件夹，是不是主题开发没对，需要编译下呢？

**Comment by qubaomingg** [comment]
安装别人开发的主题，也是报这个错，尴尬了
