### ISSUE TITLE
FR: Markdown img 标签不支持 blob:http://

### ISSUE THREAD

**Issue by mengfei0053** [umijs/dumi#1033]
### Description
需要在项目中使用  

```
 ![图片](blob:https://xxxx.xxxx)
```

![image](https://user-images.githubusercontent.com/20025631/155934760-89f10f68-ba27-466d-b079-4b31fffe8998.png)

console.log(isRelativeUrl('./sdf')); // true
console.log(isRelativeUrl('sdf')); // true
console.log(isRelativeUrl('https://')); // false
console.log(isRelativeUrl('http://')); // false
console.log(isRelativeUrl('a://')); // false
console.log(isRelativeUrl('blob:http://')); // true

### Solution

再优化下这个判断吧

**Comment by mengfei0053** [comment]
另外如果开启了MFSU 则会显示
![image](https://user-images.githubusercontent.com/20025631/155935134-36b45902-4558-42cd-bdb1-40cafe4862a2.png)。

**Comment by PeachScript** [comment]
v1.1.39 已修复
