### ISSUE TITLE
feat: modifyAssetsMeta 生成缩略图服务

### ISSUE THREAD

**Issue by kkaaddff** [umijs/dumi#1036]
dumi.modifyAssetsMeta
----比如内部有个自动生成 demo 缩略图的服务

请问这个内部的服务有开源的计划么，或者有设计思路相关的资料可以放出来参考一下么

**Comment by PeachScript** [comment]
内部实现会耦合内部的其他服务，目前没有开源的计划，也很难实施

原理是无头浏览器截图，每个 demo 都可以通过 `/~demos/:id` 的方式访问到，供参考

**Comment by kkaaddff** [comment]
白嫖不成，只能……
