### ISSUE TITLE
theme 更改不实时生效

### ISSUE THREAD

**Issue by aisaJerry** [umijs/dumi#1037]
### Question
.umirc.ts theme 增加@primary-color, 修改颜色值，不能实时生效

**Comment by aisaJerry** [comment]
接入了antd, 需要更改主题颜色
如果手动清除src/.umi, 重启，并手动清除chrome缓存可以生效
是否有快捷方式解掉这个问题

**Comment by PeachScript** [comment]
开了 MFSU？
