### ISSUE TITLE
features 的icon 的可否引入本地图片

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#1038]
features:
  - icon: 图标的 URL 地址，建议切图尺寸为 144 * 144（可选）
    title: 性能强大
    link: 可为标题配置超链接
    desc: 可以配置 `markdown` 文本

icon的url地址是否可以本地地址

**Comment by PeachScript** [comment]
放在 `public` 文件夹就行了吧，类似：https://d.umijs.org/config#favicon
