### ISSUE TITLE
Error: Cannot find module 'umi/bin/umi'

### ISSUE THREAD

**Issue by DreamPWJ** [umijs/dumi#1039]
![image](https://user-images.githubusercontent.com/16730031/156783222-e24125a8-06e3-464d-ad40-239a626336c7.png)

### Versions

- dumi: 1.1.39
- node: 14
- npm:
- OS:
- Browser:

**Comment by DreamPWJ** [comment]
还有dumi能否提供默认中文的选项，很多内部文档是不需要多语言国际化的

**Comment by PeachScript** [comment]
如何复现？看起来是没装依赖？

> dumi能否提供默认中文的选项

参考 https://d.umijs.org/zh-CN/config#locales 把中文配在第一项即可

**Comment by DreamPWJ** [comment]
> 如何复现？看起来是没装依赖？
> 
> > dumi能否提供默认中文的选项
> 
> 参考 https://d.umijs.org/zh-CN/config#locales 把中文配在第一项即可

vercel有缓存导致

**Comment by PeachScript** [comment]
dumi 官网就是 vercel 部署的，没遇到这个问题

**Comment by DreamPWJ** [comment]
难道是因为我的目录结果比较特殊  dumi没有在根目录下面  而是类似这种层级 https://github.com/DreamPWJ/jenkins-shared-library/tree/master/docs/dumi

**Comment by PeachScript** [comment]
只要 NPM 安装目录和构建执行目录都是 docs，和根目录的结构应该是一致的

**Comment by DreamPWJ** [comment]
> 只要 NPM 安装目录和构建执行目录都是 docs，和根目录的结构应该是一致的

这几次构建又突然自己好了，估计vercel的锅
