### ISSUE TITLE
dumi 二次封装antd 遇到很多份重复样式覆盖？

### ISSUE THREAD

**Issue by Mluocheng** [umijs/dumi#1040]
### Question
dumi 二次封装antd ，生成很多份link 样式表。
### Sample Code
![image](https://user-images.githubusercontent.com/31057183/156926177-9de4af9a-afa5-4405-8cfd-598ad66e31e9.png)

自定义的less:
![image](https://user-images.githubusercontent.com/31057183/156926213-e65ee973-3d3c-45d5-8ee3-a72b8c128353.png)
在组件中引入：
![image](https://user-images.githubusercontent.com/31057183/156926243-8f881058-8f9f-4487-b100-1498ca516c4d.png)

**Comment by ChenYCL** [comment]
这个问题我们也遇到了，目前只是采用强行global.css的变量抽取，引入一次做link😄，或者@import ~'' 希望找到更好的方式

**Comment by FloaJa** [comment]
遇到了同样的问题, 现在有好的解决方法吗

**Comment by cners** [comment]
同问，谁有解决办法？分享一下
