### ISSUE TITLE
如何在demo中引入 非 default 的其他内容

### ISSUE THREAD

**Issue by zhuyunhe** [umijs/dumi#1042]
### Question
rt , 在markdown的demo中，是不是不能引入非default的内容

### Sample Code
export default MyCom = () => <h1>Hello dumi!</h1>;
export enum MyEnum ={A, B}

import { DatePicker } from 'MyCom';
// question
import {MyEnum} from 'MyCom';

**Comment by PeachScript** [comment]
只要导出正确就可以引入，描述里的 enum 写法看起来有问题，`export enum MyEnum { A, B }`
