### ISSUE TITLE
how to open in stackblitz

### ISSUE THREAD

**Issue by aslkami** [umijs/dumi#1044]
### Question

how to run demo in stackblitz, not only sandbox ?
我想在 stackblitz 运行，demo，但是文档默认的是 sandbox 的，有没有办法像 antd 官网那样 支持多种在线允运行 demo 的方式

### Sample Code

无，任意 可运行 demo 即可

**Comment by PeachScript** [comment]
默认主题不支持，可以参考主题开发文档基于默认的 Previewer 自行增量扩展
