### ISSUE TITLE
与 antd pro 集成时无法获取到文档的路由元信息

### ISSUE THREAD

**Issue by xiaoyao5137** [umijs/dumi#1045]
### Question
antd pro与dumi结合后，/~docs目录下的md文件是否不支持site模式？site打开里的hero和features都乱掉了
![image](https://user-images.githubusercontent.com/9154242/157270542-12307c40-efe7-40ba-b9bd-a85fd71c2f9e.png)
![image](https://user-images.githubusercontent.com/9154242/157270562-d60cc1b5-49ab-4d26-88e0-42be12d2276e.png)

### Sample Code
https://github.com/xiaoyao5137/test
进去后，访问http://localhost:8000/~docs可以看到效果

**Comment by PeachScript** [comment]
应该是 bug，嵌套路由找文档根路由的逻辑有问题，始终用的顶层的 `routes`：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/theme/layout.tsx#L134

**Comment by PeachScript** [comment]
v1.1.40 已修复
