### ISSUE TITLE
关于seo，ssr，exportStatic

### ISSUE THREAD

**Issue by aslkami** [umijs/dumi#1050]
### Question

根据官方文档，开启 ssr 和 exportStatic，虽然生成了默认的 index.html, 但是无法访问

### Sample Code

例如我部署的 [站点](aslkami.github.io)  的文档页面， 其中一个页面 路径是 `src/base/prototype` , 但是当我访问 `/base/prototype/index.html` 的时候却是白屏 没有内容

对了 我是自定义导航 和 菜单

<img width="746" alt="截屏2022-03-12 上午12 28 10" src="https://user-images.githubusercontent.com/31195809/157908264-b934b74c-8aa6-427b-b8a1-ca6387c84dfc.png">

即使 我把它改成 `/base/prototype/index.html` 这个路由也不行

是我哪里理解错了吗？ 期待您的回复

**Comment by PeachScript** [comment]
生成的前端路由表是不会带 `index.html` 后缀的，路由表里是 `/base/prototype`，访问路径也得是 `/base/prototype`
