### ISSUE TITLE
工程左侧菜单具体tab在测试环境不能展开，但是发布到线上环境就有具体的.md文档中的明细了，怎么保持和测试的时候一样，关掉明细呢

### ISSUE THREAD

**Issue by weixiaopasta** [umijs/dumi#1052]
### Question
测试环境的效果：
<img width="487" alt="image" src="https://user-images.githubusercontent.com/11311858/158300982-45b3c4cb-57c6-4ca8-8871-0880b36e3563.png">
发布之后的效果：
https://optimus.58.com/mobile/components/common/button
https://optimus.58.com/mobile/components/common/button#button-%E6%8C%89%E9%92%AE
<img width="546" alt="image" src="https://user-images.githubusercontent.com/11311858/158300477-4e355a50-effb-4d8d-b671-9379c4485731.png">

期望不存在展开的效果

### Sample Code
.md 文档写法如下
`---
title: Button 按钮
order: 0
group:
  title: 基础组件
  order: 1
---

## Button 按钮
`
下面是我们的package.json 文件
`{
  "private": false,
  "name": "optimus-mobile",
  "version": "1.1.7",
  "scripts": {
    "start": "dumi dev",
    "docs:build": "dumi build",
    "docs:deploy": "gh-pages -d docs-dist",
    "build": "father-build",
    "deploy": "npm run docs:build && npm run docs:deploy",
    "release": "npm run build && npm publish",
    "prettier": "prettier --write \"**/*.{js,jsx,tsx,ts,less,md,json}\"",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },
  "main": "dist/index.js",
  "module": "dist/index.esm.js",
  "typings": "dist/index.d.ts",
  "dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@fang/optimus": "^1.0.37",
    "@react-spring/web": "^9.4.2",
    "@types/lodash": "^4.14.178",
    "@umijs/plugin-esbuild": "^1.4.1",
    "ahooks": "^3.1.10",
    "clsx": "^1.1.1",
    "dumi-theme-mobile": "^1.0.3",
    "lodash": "^4.17.21",
    "normalize.css": "^8.0.1",
    "postcss-px-to-viewport": "^1.1.1",
    "rc-banner-anim": "^2.4.5",
    "rc-progress": "^3.1.3",
    "rc-util": "^5.13.2",
    "react": "^16.12.0",
    "react-dom": "^17.0.1",
    "react-sticky": "^6.0.3",
    "react-transition-group": "^4.4.2",
    "rmc-steps": "^1.0.1",
    "rmc-tabs": "~1.2.0",
    "rollup-plugin-commonjs": "^10.1.0",
    "staged-components": "^1.1.2",
    "antd-mobile-icons": "^0.2.2"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.15.1",
    "@testing-library/react": "^12.1.2",
    "@types/react-transition-group": "^4.4.2",
    "@umijs/test": "^3.0.5",
    "dumi": "^1.0.13",
    "father-build": "^1.17.2",
    "gh-pages": "^3.0.0",
    "lint-staged": "^10.0.7",
    "lorem-ipsum": "^2.0.4",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0"
  },
  "peerDependencies": {
    "lodash": "^4.17.21"
  }
}`

**Comment by PeachScript** [comment]
mobile 主题下为了节省空间默认会把 toc 展示在 menu 里，可以修改或者关闭：https://d.umijs.org/zh-CN/config/frontmatter#toc
