### ISSUE TITLE
如何修改“编辑此页”的url拼接逻辑

### ISSUE THREAD

**Issue by Holy-Shine** [umijs/dumi#1062]
由于写的文档存放的位置是企业定制版的gitee仓库，因此编辑的url和下面配置生成的略有不同
```json
// package.json
{
  "repository": {
    "type": "git",
    "url": "git+https://github.com/umijs/dumi.git",
    "branch": "master",
    "platform": "gitee"
  }
}
```
如何修改这个“编辑此页”的link的生成逻辑呢。

PS. 修改了压缩的js文件：`my_dumi_app/docs-dist/umi.js` 中的拼接逻辑，仍然不work

**Comment by PeachScript** [comment]
目前不能自定义，gitee 的路径是怎样的

**Comment by Holy-Shine** [comment]
> 目前不能自定义，gitee 的路径是怎样的

我司的定制版比较复杂，所以有了自定义的想法。
我看了gitee个人版，其实是跟github路径是一致的:
`http://gitee.com/username/repo_name/edit/branch/xxxx.md`
