### ISSUE TITLE
feat: 对React(ReactDOM)18的支持

### ISSUE THREAD

**Issue by ArcherCube** [umijs/dumi#1067]
### Description
React升级18后，新特性需替换原本的ReactDOM.render方法才可以生效，据了解目前dumi内核React为16.*，希望可以提供相关更新支持。
或提供相关配置允许开发者修改根组件的挂载方式？

**Comment by rumengkai** [comment]
支持，不然会报：

**Comment by PeachScript** [comment]
可以先用 `^1.1.41-rc.0` 临时解了这个问题；下个正式版会正式解这个问题

**Comment by hzh11012** [comment]
^1.1.41-rc.0 好像不行呃，还是会报

**Comment by PeachScript** [comment]
> ^1.1.41-rc.0 好像不行呃，还是会报

`rm -rf src/.umi` 重启

**Comment by PeachScript** [comment]
v1.1.42 已正式支持，closed
