### ISSUE TITLE
bug: 组件不支持less

### ISSUE THREAD

**Issue by scfido** [umijs/dumi#1068]
### Versions

- dumi: 1.1.40
- node: v14.18.1
- npm: 8.5.1
- OS: macOS 11.6.4 
- Browser: Microsoft Edge 99.0.1150.52

### Steps to reproduce

1. 从 [](https://github.com/umijs/dumi-template) 创建项目
2. 在`Foo`组件中添加`style.less`并引用
3. `yarn start`启动

### What is Expected?

能正常编译less文件

### What is actually happening?

编译报错
 
项目请见：https://github.com/scfido/dumi-sample

> ✖ Webpack
  Compiled with some errors in 703.74ms
  ERROR  Failed to compile with 1 errors   
  This dependency was not found:
  style.less?modules in ./src/Foo/index.tsx
  To install it, you can run: npm install --save style.less?modules

![image](https://user-images.githubusercontent.com/5214402/162377864-2a4fc1b6-e6f6-4e79-aafe-2fd5872577bd.png)

**Comment by PeachScript** [comment]
本地模块用 `./` 开头做引入

**Comment by scfido** [comment]
确是忘记了，大意了，非常感谢。
