### ISSUE TITLE
bug: 修改.umirc.ts配置文件没有自动编译

### ISSUE THREAD

**Issue by LiuJinYang9527** [umijs/dumi#107]
如题

### Versions

- dumi:^1.0.5
- node:12.14.1
- npm:6.13.4
- OS:Windows
- Browser:Chrome

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/87025866-8336ee00-c20d-11ea-8c26-8f21a79d8b7b.png)
给一个重现 demo 吧
