### ISSUE TITLE
引入外部demo，start可以正常运行，build报错

### ISSUE THREAD

**Issue by alwaysli** [umijs/dumi#1074]
### Question
src/functions/unfoldTree/demo/demo.tsx(2,28): error TS2307: Cannot find module '@yx-tools/utils' or its corresponding type declarations.
![image](https://user-images.githubusercontent.com/16472610/164132818-637e1f2e-17b2-4639-bd6c-14d7940fed4d.png)

#### md文档

```mardown

---
title: unfoldTree
---

# unfoldTree

`unfoldTree` 用于将树结构的数据转为水平结构

Demo:

<code src="./demo/demo.tsx"></code>


```

#### demo文件

```jsx
import React from 'react';
import { unfoldTree } from '@yx-tools/utils';

const data = [
  {
    title: 'Node1',
    value: '0-0',
    children: [
      {
        title: 'Child Node1',
        value: '0-0-1',
      },
      {
        title: 'Child Node2',
        value: '0-0-2',
      },
    ],
  },
  {
    title: 'Node2',
    value: '0-1',
  },
];
const endData = unfoldTree(data, 'value', 'children');
console.log('endData: ', endData);

export default () => <div>unfoldTree</div>;
```

**Comment by PeachScript** [comment]
如报错信息所述，需要解决 `@yx-tools/utils` 的类型定义缺失问题

**Comment by alwaysli** [comment]
不太清楚，是什么类型定义缺失呢？

**Comment by leohxj** [comment]
> 不太清楚，是什么类型定义缺失呢？

需要自定义 tsconfig 的 paths 映射, 参考 `ahooks`: https://github.com/alibaba/hooks/blob/master/tsconfig.json

**Comment by alwaysli** [comment]
解决了，非常感谢
