### ISSUE TITLE
非根目录部署的路由跳转问题

### ISSUE THREAD

**Issue by foolish-boy** [umijs/dumi#1079]
### Question
dumi版本1.1.40

我的页面部署到 my.domain.com/aaa/ 下面
我配置
{
  base: '/aaa',
  publicPath: '/aaa/',
  exportStatic: {},
}
这样以后我本地访问是OK的，每次切换一个路由 /bbb. 都会打开 my.domain.com/aaa/bbb， 但是部署到机器后 点击bbb就会丢失/aaa变成my.domain.com/bbb，页面可以打开 但是刷新就404

于是我改成hash路由：
history: { type: 'hash' }

能解决问题，但是会带来新的问题，就是我的demo页面切换代码块 右侧模拟器不会渲染新的或者渲染的是首页的内容

**Comment by PeachScript** [comment]
已确认是托管平台的问题，closed
