### ISSUE TITLE
bug: 使用 lerna 时依赖找不到的问题

### ISSUE THREAD

**Issue by heynext** [umijs/dumi#108]
如果是 `lerna` 项目，而且有个包下面有 `src` 文件夹，就会报错：`This dependency was not found: xxx`。

### Versions

- dumi: 1.0.5
- node: 13.1.0
- npm: 6.12.1

**Comment by sorrycc** [comment]
如何复现？

**Comment by heynext** [comment]
@sorrycc https://github.com/heynext/dumi-lerna-with-src 这个哈，就是 `lerna create xx` 然后把 `packages/xx/lib` 改成了 `packages/xx/src`

**Comment by PeachScript** [comment]
原因知道了，dumi 只判定了 `src` 目录，就把 package alias 到 src 了，没判定是否有 `src/index`，下个版本修一下：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/plugins/core.ts#L138

**Comment by heynext** [comment]
@PeachScript 这个预计什么时候发布呢？

**Comment by PeachScript** [comment]
@heynext 1.0.6 可用了
