### ISSUE TITLE
测试用例通过，但测试覆盖率为0

### ISSUE THREAD

**Issue by zhangminggeek** [umijs/dumi#1083]
### 测试用例通过，但测试覆盖率为0
使用 dumi 创建项目后，src 目录下全部都是 function，并且在 index.ts 文件中导出。
执行 `npm run test`，单元测试全部通过
执行 `npm run test:coverage`，单元测试全部通过，但测试覆盖率为0 ，如下图所示

<img width="510" alt="image" src="https://user-images.githubusercontent.com/30174437/166939355-18563d33-410e-4bbb-b648-d64b5ee054d9.png">

**Comment by PeachScript** [comment]
非 dumi scope，jest 社区找答案，推测和 `collectCoverageFrom` 配置有关
