### ISSUE TITLE
想要实现demos两列排列布局，但是layout的children无法控制

### ISSUE THREAD

**Issue by 0820Jones** [umijs/dumi#1087]
### Question
想要实现antd文档这样demo两列布局的形式，但是layout的children无法控制区分markdown和demos。遍历children时始终只有一个子组件，请问如何做才能分别获取markdown和demo内容？
![image](https://user-images.githubusercontent.com/31086553/167354563-5f67a3d7-7ce3-4d49-b672-17247730d891.png)
![image](https://user-images.githubusercontent.com/31086553/167355520-39a614a8-bdac-46d8-9fb9-73161f619777.png)

**Comment by 0820Jones** [comment]
@[PeachScript](https://github.com/PeachScript)

**Comment by PeachScript** [comment]
目前不支持，dumi 2 会支持
