### ISSUE TITLE
bug: 二级导航菜单文字居中

### ISSUE THREAD

**Issue by Holy-Shine** [umijs/dumi#1088]
![image](https://user-images.githubusercontent.com/14997709/167362933-c09f788f-3519-4df8-8fad-fee51a797122.png)
![image](https://user-images.githubusercontent.com/14997709/167362958-079c9387-06ed-4c96-82b2-e307688f56d7.png)
如图所示，二级导航菜单默认显示靠左而不是居中，请问是哪里配置错了吗

**Comment by PeachScript** [comment]
默认是靠左的，需要居中可以用 styles 配置项覆写样式
