### ISSUE TITLE
feat: 期望左侧菜单可折叠，样式可配（或提供小号）

### ISSUE THREAD

**Issue by roc-an** [umijs/dumi#1090]
### Description

目前左侧菜单，宽度固定，在小尺寸浏览器窗口下，默认的网站体验很不友好。

### Solution

期望提供配置项，如折叠、小号尺寸，或暴露可配置样式的 api

**Comment by PeachScript** [comment]
可以控制 Less 变量实现，参考：https://d.umijs.org/zh-CN/config#theme

**Comment by roc-an** [comment]
> 可以控制 Less 变量实现，参考：https://d.umijs.org/zh-CN/config#theme

非常感谢！
