### ISSUE TITLE
在config里配置antd属性报Invalid config key: antd

### ISSUE THREAD

**Issue by zhanguangao** [umijs/dumi#1091]
### Question
在config里配置antd属性报如下错误
![image](https://user-images.githubusercontent.com/13374669/169497772-99cf9296-f7d6-4759-8ffb-ebb5e03fc55e.png)

dumi版本：1.1.37
node_modules下安装的umi版本：3.5.21

尝试在umi项目下配置antd属性是可以生效的，dumi也是将属性透传给umi，不理解为什么会报错

### Sample Code
```
export default defineConfig({
  antd: {
      config: {
        prefixCls: 'mcui',
      },
    },
})
```

**Comment by PeachScript** [comment]
要手动安装 [@umijs/plugin-antd](https://umijs.org/plugins/plugin-antd)
