### ISSUE TITLE
bug: Cannot find module 'lerna/package.json'

### ISSUE THREAD

**Issue by soeasyjx** [umijs/dumi#1092]
lerna 项目 启动命令 yarn run start 

编译报错  Cannot find module 'lerna/package.json'

lerna 是全局安装的，现在还不支持全局的 lerna 么。。。。。

### Versions

- dumi: 1.1.42
- node: 16.15.0
- npm:8.10.10
- OS:12.3.1
- Browser:chrome 101

### What is Expected?
<img width="832" alt="WX20220522-204146@2x" src="https://user-images.githubusercontent.com/17918538/169695725-6de7c5bd-e31c-4473-b342-4fb0df1b2297.png">

**Comment by PeachScript** [comment]
暂不支持，可以项目里装一个
