### ISSUE TITLE
请问 menu 如何自动收缩？

### ISSUE THREAD

**Issue by 18888628835** [umijs/dumi#1094]
### 配置
你好，我用 dumi 的 site模式，然后 navs 和 menus 我都直接写在配置里，menus 的配置项是这样的：
```
const docsMenu = {
  '/docs': [
    {
      title: '前端可视化',
      path: '/docs/前端可视化',
      children: ['/docs/前端可视化/svg大屏.md', '/docs/前端可视化/canvas.md'],
    },
    {
      title: '前端工程化',
      path: '/docs/前端工程化',
      children: ['/docs/前端工程化/代码规范.md'],
    },
  ],
};
```
出来的效果是这样的
![image](https://user-images.githubusercontent.com/53749772/169998742-18d0285a-dced-4867-ade6-edec44cecff7.png)
我想要咨询一下，如何才能让 menu 自动收起来，当我点到它的时候，它才展开？
比如，我希望实现点击 【前端工程化】这个 menu，里面才会出现【代码规范】这一节，否则【代码规范】就隐藏起来呢？

dumi 官网的[指南](https://d.umijs.org/zh-CN/guide)就是这个效果，我看了 dumi 的项目，好像是在每个 MD 文件里面写 FrontMatter。跟我目前情况不太一样，所以来咨询一下

**Comment by PeachScript** [comment]
menu 不支持收缩，需要可以自定义主题实现；官网只是在 menu 里展示了当前文档的 toc，并非展示该分类下的子文档
