### ISSUE TITLE
bug:  Element type is invalid: expected a string (for built-in components) or a class/function (for composite components)

### ISSUE THREAD

**Issue by RoyKwok94** [umijs/dumi#1096]
### Versions

- dumi:^1.1.0
- node:14.18.1
- npm:6.14.15
- OS:win11
- Browser: chrome

### What is actually happening?
安装后的demo 
×
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `_default`.
▶ 21 stack frames were collapsed.
initialValue
./src/.umi/umi.ts:30
  27 |         defaultTitle: `dumi`,
  28 |       },
  29 |     });
> 30 |     return renderClient(opts);
  31 |   },
  32 |   args,
  33 | });
View compiled
(anonymous function)
./node_modules/_@umijs_runtime@3.5.24@@umijs/runtime/dist/index.esm.js:804
./src/.umi/umi.ts
./src/.umi/umi.ts:36
  33 | });
  34 | 
  35 | const clientRender = getClientRender();
> 36 | export default clientRender();
  37 | 
  38 | 
  39 |     window.g_umi = {
View compiled
__webpack_require__
./webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
fn
./webpack/bootstrap:100
   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
      | ^  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {
View compiled
0
http://localhost:8000/umi.js:88971:18
__webpack_require__
./webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
View compiled
(anonymous function)
./webpack/bootstrap:856
  853 | 
  854 | 
  855 | // Load entry module and return exports
> 856 | return hotCreateRequire(0)(__webpack_require__.s = 0);
      | ^  857 | 
View compiled
(anonymous function)
http://localhost:8000/umi.js:860:10

**Comment by jackywq** [comment]
我的遇到这种情况，本地写demo用例运行没问题，使用umi打包markdown文档并发版后，就报当前这个错误。

**Comment by jackywq** [comment]
我的也遇到类似这种情况，本地在markdown写demo用例运行没问题，使用umi打包markdown文档并发版后，就报当前这个错误。

**Comment by jackywq** [comment]
我的也遇到类似这种情况，本地在markdown写demo用例运行没问题，使用umi打包markdown文档并发版后，就报当前这个错误，直接导致页面崩溃。

**Comment by wbr911** [comment]
遇到一样的问题 
npx @umijs/create-dumi-lib 构建的项目 一行代码没改，跑起来就报这个错

**Comment by qc-z** [comment]
解决了吗？我也遇到
