### ISSUE TITLE
bug: build了后没有dist 也没有 es

### ISSUE THREAD

**Issue by ghost** [umijs/dumi#1099]
### Versions

- dumi:^1.1.0
- node:14.18.1
- npm:6.14.15
- OS:win11
- Browser:chrome

### Steps to reproduce
    一 、npx @umijs/create-dumi-lib     我按照官网的建立一个demo , 文档 是这样子说，执行 npm run docs:build (组件开发脚手架) / npm run build（静态站点脚手架), 或 npx dumi build 即可对我们的文档站点做构建，构建产物默认会输出到 dist 目录下，我们可以将 dist 目录部署在 now.sh、GitHub Pages 等静态站点托管平台或者某台服务器上。我打包后没有dist,只有docs-dist.
   二、packjson上"module": "es/index.js",  打包出来后没有es的

**Comment by PeachScript** [comment]
dumi 是组件库文档工具，`docs-dist` 是文档产物，组件库源码编译用 `npm run build`（背后是 `father-build`）
