### ISSUE TITLE
md中的小标题没有出现在侧边栏中？

### ISSUE THREAD

**Issue by xingxinglieo** [umijs/dumi#1101]
### Question
我看了下官方文档的 md 和 配置，好像也没有这个选项，但是小标题是在侧边栏的，我这边就是一个主标题，是少配了什么吗？

**Comment by stygian-desolator** [comment]
直接使用
```
#### 小标题 1

<code ...> 

#### 小标题 2

<code ...> 
```
这样的方式就好了，写在 title 上有时候确实会有些问题。

**Comment by PeachScript** [comment]
参考：https://d.umijs.org/zh-CN/config/frontmatter#toc

**Comment by xingxinglieo** [comment]
> 参考：https://d.umijs.org/zh-CN/config/frontmatter#toc

感谢🙏
