### ISSUE TITLE
bug: Could not find dependency: '@ant-design/pro-components' relative to '/App.tsx' 

### ISSUE THREAD

**Issue by binyellow** [umijs/dumi#1105]
### Versions

- dumi: 1.1.42
- node: 16.13.0
- npm: 8.1.0
- OS: macOs big Sur 11.4
- Browser: 版本 102.0.5005.61（正式版本） (x86_64)

### Steps to reproduce
https://codesandbox.io/s/swsnsf?file=/App.tsx
[其他pro-components的在线demo都会报错](https://procomponents.ant.design/components/form)

### What is Expected?
不报错，正确预览

### What is actually happening?
Could not find dependency: '@ant-design/pro-components' relative to '/App.tsx' 

### 补充
我的场景也是lerna，然后子package的依赖路径会是`packages/xx/src`
但是稍微浏览了下源码，发现`packages/preset-dumi/src/transformer/demo/dependencies.ts`解析依赖对这部分逻辑有点问题

**Comment by binyellow** [comment]
> Hello @binyellow. In order to facilitate location and troubleshooting, we need you to provide a realistic example. You can create a dumi project by clicking [here](https://github.com/umijs/dumi-template/generate) and provide the GitHub warehouse address and reproduce examples.
> 
> 你好 @binyellow, 为了方便定位和排查问题，我们需要你提供一个重现实例。你可以通过点击 [此处](https://github.com/umijs/dumi-template/generate) 创建一个 dumi 项目并提供 GitHub 仓库地址和重现实例。

https://github.com/ant-design/pro-components

**Comment by binyellow** [comment]
老哥  下周有空发个版呗 @[PeachScript](https://github.com/PeachScript)

**Comment by PeachScript** [comment]
[v1.1.43](https://github.com/umijs/dumi/releases/tag/dumi%401.1.43) 已发布，感谢👍
