### ISSUE TITLE
feat: 希望可以在一个md里可以引用另一个md的内容

### ISSUE THREAD

**Issue by heiyexing** [umijs/dumi#1108]
主要考虑到多个md当中有重复内容，希望能够在一个md文件里统一维护。

使用上类似`<API src="./......"/>`标签引入React组件注释生成的文档内容。

**Comment by PeachScript** [comment]
参考：https://d.umijs.org/guide/basic#embed

**Comment by heiyexing** [comment]
> https://d.umijs.org/guide/basic#embed

3Q very much
