### ISSUE TITLE
有内置类似 docz 的 Props 组件的计划吗？

### ISSUE THREAD

**Issue by heynext** [umijs/dumi#111]
### Question

RT

---

PS: docz 的 Props 在 TypeScript 下是真的难用

**Comment by PeachScript** [comment]
有的，同时 PR Welcome~

**Comment by shui-yue** [comment]
期待~

**Comment by heynext** [comment]
@PeachScript 请问 dumi 现在有钩子函数可以用吗？我们可以通过现有的机制在 markdown 解析时做这个吗？

**Comment by PeachScript** [comment]
@heynext 还不行，目前 dumi 的 md 解析是完全的黑盒；如果能介入 md 解析，是打算手动推导 Props 然后追加到文档中？

**Comment by heynext** [comment]
> @heynext 还不行，目前 dumi 的 md 解析是完全的黑盒；如果能介入 md 解析，是打算手动推导 Props 然后追加到文档中？

@PeachScript 是的，我们这写了个推到  Props 的 demo，想通过扩展 markdown 解析的方式追加到文档中。markdown 这个解析以后会开放扩展么？

**Comment by PeachScript** [comment]
@heynext 肯定会的，不过 props 推导 dumi 也打算支持，应该会在解析开放之前

**Comment by zhaoyao91** [comment]
请问 Props 组件已经推出了吗？在哪里？

**Comment by PeachScript** [comment]
@zhaoyao91 还没有，支持后 issue 会关闭的

**Comment by zhaopeifei** [comment]
请问下，有个预期时间吗？非常期待~

**Comment by aizigao** [comment]
期待加一，没有这个写文档好累

**Comment by MyCupOfTeaOo** [comment]
Props 确实是个很好的组件,不过希望可以对 TypeScirpt 支持好一点 (๑•ᴗ•๑)

**Comment by PeachScript** [comment]
API 自动生成特性已在 beta 中开放，欢迎试用：https://d.umijs.org/zh-CN/lab 以及集中反馈：https://github.com/umijs/dumi/issues/358

**Comment by MyCupOfTeaOo** [comment]
> API 自动生成特性已在 beta 中开放，欢迎试用：https://d.umijs.org/zh-CN/lab 以及集中反馈：#358

:+1:
