### ISSUE TITLE
如何定义一级menu？

### ISSUE THREAD

**Issue by codepandy** [umijs/dumi#1111]
### 自定义menu只能用children吗？
我有的文章是分组的，可以放在一个menu的children中，但是有的文章是想直接放在一级，该如何配置啊？

### Sample Code
```
 menus: {
    '/guide': [
      {
        title: '优化',
        children: [
          '/guide/优化/1.md',
          '/guide/优化/2.md',
        ],
      },
      {
        title: '独立文章',
        path: '/guide/安全/aa.md',
      },
    ],
  },
```
“独立文章”这样配置找不到文件啊？指定文件路径使用什么属性？

**Comment by PeachScript** [comment]
文件路径是相对于 `resolve.includes` 目录识别的，ref: https://d.umijs.org/zh-CN/config#menus

**Comment by qiugu** [comment]
相对于includes目录，当includes下的是个多包结构packages，又相对哪个呢，文档没说清楚，歧义很大

**Comment by qiugu** [comment]
includes目录不止一个的话，文件路径是相对哪个呢

**Comment by qiugu** [comment]
如果是多包的架构，packages/pkg/src这种的，pkg下面有个readme.md，pkg/src/**/index.md文件这种，该怎么配置menus
