### ISSUE TITLE
如何设置不检测代码块中的语法？

### ISSUE THREAD

**Issue by codepandy** [umijs/dumi#1112]
### Question
代码块中的语法和关键字会被检查，带尖括号和编译后会报错。
### Sample Code
比如`Array<String | Object>`就会报错
还有
```
<div className={valid ? styles.left : styles.leftInvalid} />```
问号那报错。转义的时候报错了“ <div className="{valid" ?="" styles.left="" :="" styles.leftinvalid}="">”

**Comment by PeachScript** [comment]
ref: https://d.umijs.org/zh-CN/guide/basic#%E4%B8%8D%E6%B8%B2%E6%9F%93%E4%BB%A3%E7%A0%81%E5%9D%97
