### ISSUE TITLE
描述中有英文的冒号解析不出来

### ISSUE THREAD

**Issue by hchlq** [umijs/dumi#1114]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
/**
 * title: Use the option property to configure Cookie
 * desc: Available options: defaultValue、expires、path、domain、secure、sameSite etc.
 */
### What is Expected?
`desc: Available options: defaultValue ...` 中的第二个冒号应该也能解析出来
### What is actually happening?
如果是这样 `desc: Available options: defaultValue、expires、path、domain、secure、sameSite etc.`，文档解析不出来

<img width="575" alt="image" src="https://user-images.githubusercontent.com/60802048/174952429-71757242-3694-4e23-a2dd-757dc8c9ee1b.png">

换成英文版的冒号之后 `desc: Available options：defaultValue、expires、path、domain、secure、sameSite etc.`，就可以解析出来了

<img width="676" alt="image" src="https://user-images.githubusercontent.com/60802048/174952554-363be755-ddfa-4c04-9da5-92182cd5ab89.png">

**Comment by hchlq** [comment]
除了通过 `&#58; ` 可以绕过之外，还有什么比较好的办法吗

**Comment by PeachScript** [comment]
引号括起来，具体参考 YAML 语法规则
