### ISSUE TITLE
bug: 设置tsconfig编译上层文件不生效

### ISSUE THREAD

**Issue by clerkkent** [umijs/dumi#1115]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/23066769/175204597-50383061-9918-4418-a0f1-eb415c396565.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/23066769/175204607-f72cea51-ee0f-4669-9957-6f953ce9c0c7.png">

**Comment by kevinpursuing** [comment]
我也遇到这个问题了，你是怎么解决的呢

**Comment by PeachScript** [comment]
1. dumi 默认不会编译当前目录之外的文件，需要配置 `extraBabelIncludes`：https://d.umijs.org/config#extrababelincludes
2. monorepo 建议还是按推荐的结构、从根目录启动 dumi，可以避免这个问题而且有自动 alias、使得 demo 里可以直接从其他子包引入组件，参考：https://d.umijs.org/zh-CN/guide/basic#lerna-%E9%A1%B9%E7%9B%AE
