### ISSUE TITLE
feat: 什么时候支持umi4

### ISSUE THREAD

**Issue by Andyspace5** [umijs/dumi#1119]
希望可以支持umi4

**Comment by PeachScript** [comment]
还有段时间，dumi 2 会基于 Umi 4

**Comment by PeachScript** [comment]
> @PeachScript hi，有大概的时间节点么？

目前只能确定 Q3 内，下个月应该会有 roadmap

**Comment by zhouzyc** [comment]
插眼

**Comment by hasnum-stack** [comment]
插眼

**Comment by tolerance-go** [comment]
插眼

**Comment by liihuu** [comment]
插眼

**Comment by olivewind** [comment]
> 确定 Q3 内，下个月应该会有 roadmap

请问是否已有 roadmap？

**Comment by PeachScript** [comment]
Roadmap 已制定：https://github.com/umijs/dumi/issues/1151

**Comment by yuandalu** [comment]
> > @PeachScript hi，有大概的时间节点么？
> 
> 目前只能确定 Q3 内，下个月应该会有 roadmap

roadmap 针对集成没有给时间点，还有计划加吗
