### ISSUE TITLE
如何排除项目根目录下的 readme.md？

### ISSUE THREAD

**Issue by shengliangli** [umijs/dumi#112]
### Question
通常会在项目的根目录（不是 /src，是项目的根）下增加一个 readmne.md 文档来说明当前项目的一些情况，这个文档的目的是面对项目的开发人员，不需要把这个文档也包含到最终的输出文档中。
尝试在配置中使用
```
resolve: {
    includes: ['src']
  },
```
也不起作用。
### Sample Code
none

**Comment by PeachScript** [comment]
看下这个：https://d.umijs.org/guide/faq#%E4%B8%BA%E4%BB%80%E4%B9%88-readmemd-%E4%BC%9A%E5%87%BA%E7%8E%B0%E5%9C%A8%E6%96%87%E6%A1%A3%E7%9A%84%E9%A6%96%E9%A1%B5%EF%BC%9F

**Comment by shengliangli** [comment]
thx.
