### ISSUE TITLE
bug: dumi打包出来的文件umi4不兼容

### ISSUE THREAD

**Issue by yaodong5063** [umijs/dumi#1120]
![Uploading 企业微信截图_16569046742057.png…]()

styles.main，这种就会报错，因为styles为underfined

**Comment by yaodong5063** [comment]
![image](https://user-images.githubusercontent.com/37628562/177075898-52c4221a-d2a2-449c-bac3-51847ea504d8.png)

**Comment by PeachScript** [comment]
组件库打包由 father 负责，另外组件库不建议使用 CSSModules，用户很难覆写样式

强行要用需要在 Umi 4 里配 `extraBabelIncludes` 让自己的组件库走 babel 编译
