### ISSUE TITLE
bug: keep location.hash is camel case when clicking on the icon-link

### ISSUE THREAD

**Issue by GOWxx** [umijs/dumi#1124]
### Versions

- dumi: ^1.1.7
- node: v16.14.2
- pnpm: 7.1.9
- OS: apple m1 macos Monterey
- Browser: google chrome 103.0.5060.53 (arm64)

### Steps to reproduce
visit https://ahooks.js.org/zh-CN/hooks/use-why-did-you-update
click '#' before title 'useWhyDidYouUpdate'

href: https://ahooks.js.org/zh-CN/hooks/use-why-did-you-update/#usewhydidyouupdate

![image](https://user-images.githubusercontent.com/12870715/177269644-8931fdbb-f02d-4e05-99b0-66f5fae1fa31.png)

### What is Expected?

href: https://ahooks.js.org/zh-CN/hooks/use-why-did-you-update/#usewhydidyouUpdate

**Comment by PeachScript** [comment]
1. URL is case-insensitive
2. This behavior is same as GitHub: https://github.com/alibaba/hooks/blob/master/packages/hooks/src/useWhyDidYouUpdate/index.zh-CN.md
