### ISSUE TITLE
我在.umirc.ts配置了extraBabelPlugins，分别是antd样式的按需加载和我自己的按需加载，但是我写的样式被覆盖了

### ISSUE THREAD

**Issue by qc-z** [umijs/dumi#1128]
![image](https://user-images.githubusercontent.com/22362903/177482785-cc8db6b1-8d55-4c99-9abf-30897cf1094e.png)

![image](https://user-images.githubusercontent.com/22362903/177482955-df46ee0e-637b-4141-b92a-5a6373187881.png)

**Comment by PeachScript** [comment]
样式优先级问题请自行解决
