### ISSUE TITLE
在外部demo中引入图片报错

### ISSUE THREAD

**Issue by huangyiming9228** [umijs/dumi#1131]
### 怎么才能在外部demo中引入图片资源呢

![image](https://user-images.githubusercontent.com/34177347/177520684-bf89d4a6-d1b1-4a50-84b8-459eac7efd19.png)
![image](https://user-images.githubusercontent.com/34177347/177520820-b94d176f-df29-40c4-9694-89627834b869.png)

**Comment by PeachScript** [comment]
打包相关问题在 father 仓库找答案，https://github.com/umijs/father/issues/227#issuecomment-720928000
