### ISSUE TITLE
bug: pnpm init project installation error

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [umijs/dumi#1133]
### Versions

- dumi: -
- node: v16.13.1
- npm: v8.10.0
- pnpm: v7.5.0
- OS: Windows 11
- Browser: Chrome

### Steps to reproduce

1. `pnpm @umijs/create-dumi-lib` init project.
2. `pnpm i` to install modules.

### What is Expected?

Install dependencies correctly.

### What is actually happening?

`dumi` is the wrong version, install dependencies error.

![image](https://user-images.githubusercontent.com/54026110/177932466-07104920-4b5a-4021-8e1e-085ba8d02962.png)

![image](https://user-images.githubusercontent.com/54026110/177932396-9f5a9a0b-6281-4f11-9463-03e1b93a924b.png)

**Comment by PeachScript** [comment]
是 bug，先手动更正下版本号吧

**Comment by PeachScript** [comment]
+ @umijs/create-dumi-lib@1.2.1 已修复，感谢反馈
