### ISSUE TITLE
如何配置代码块不显示左下角的链接和codesandbox两个图标

### ISSUE THREAD

**Issue by Hitotsubashi** [umijs/dumi#1138]
### Question

![image](https://user-images.githubusercontent.com/48796418/178259014-c0f1b2a6-5057-4772-9531-dbd1e9fa2f2d.png)
如何配置代码块不显示左下角的链接和codesandbox两个图标

**Comment by PeachScript** [comment]
暂不支持配置；可以用 styles 配置项全局样式隐藏
