### ISSUE TITLE
bug:  文档不能渲染

### ISSUE THREAD

**Issue by eveningwater** [umijs/dumi#1139]
我配置的menus是这样的:

```ts
{
  '/guide': [
    {
      title: 'Accordion',
      path: '/guide/Accordion/Accordion',
    },
    {
      title: 'Alert',
      path: '/guide/Alert/Alert',
    },
    {
      title: 'AutoLink',
      path: '/guide/AutoLink/AutoLink',
    },
  ],
  '/zh-CN/guide': [
    {
      title: '手风琴',
      path: '/zh-CN/guide/Accordion/Accordion',
    },
    {
      title: '提示',
      path: '/zh-CN/guide/Alert/Alert',
    },
    {
      title: '自动文本链接',
      path: '/zh-CN/guide/AutoLink/AutoLink',
    },
  ],
}
```

但是AutoLink文档的内容没有渲染出来，一片空白。

文档内容在:

docs/guide/AutoLink/AutoLink.md
docs/guide/AutoLink/AutoLink.zh-CN.md

![1](https://user-images.githubusercontent.com/29032781/178262577-32eca44f-3dc3-411c-a317-e4be494e772b.png)

![2](https://user-images.githubusercontent.com/29032781/178262588-ed2cdab1-0dbd-4496-8f1e-1fe8b98581dc.png)

![3](https://user-images.githubusercontent.com/29032781/178263055-594d3144-32fc-40d9-bdd6-e3900f903136.png)

![4](https://user-images.githubusercontent.com/29032781/178263061-a1a4be3c-5b1c-4a18-95bd-5079bd77949a.png)

如上图所示，我的Alert都能渲染，而且我部署到线上去，Accordin.tsx也没有渲染，但是本地运行是可以渲染的。

[源码地址](https://github.com/eveningwater/code-segment-react)
[线上地址](https://eveningwater.github.io/code-segment-react/guide/Accordion/Accordion)

### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

**Comment by PeachScript** [comment]
驼峰命名的文件在生成 url 的时候会被转换成短横线，`AutoLink` -> `auto-link`，URL 是不区分大小写的所以其他路由能访问
