### ISSUE TITLE
bug: .umirc.ts 只要有方法引用就回报错

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#114]
```ts
import path from 'path';

export default {
    outputPath: path.join('./dist', PROJECT)
}
```
报错如下

![image](https://user-images.githubusercontent.com/2802841/76272007-19392700-62b5-11ea-8464-5817b60e96ee.png)

**Comment by sorrycc** [comment]
看报错，PROJECT 未定义吧。

**Comment by mizi-lin** [comment]
对的，刚花眼了，过来关 issue 了··
