### ISSUE TITLE
官方推荐的dumi-template仓库无法使用antd的Tab组件，ts报错，详情见描述

### ISSUE THREAD

**Issue by huangh69** [umijs/dumi#1143]
### Question
使用官方推荐的dumi-template 仓库进行初始化之后，想使用antd（V3），在原模板文件Foo的index.tsx中import进来之后，TS报错

![image](https://user-images.githubusercontent.com/15855274/179181317-ad98745e-380b-4fad-9acb-f513f591539e.png)
![image](https://user-images.githubusercontent.com/15855274/179203961-2ab8f9e5-c2b6-440d-962a-cf328bb82f49.png)

### Sample Code
import React from 'react';
import { Tabs } from 'antd';
const { TabPane } = Tabs;

function callback(key:string) {
    console.log(key);
  }
export default ({ title }: { title: string }) => {
    <Tabs defaultActiveKey="1" onChange={callback}>
    <TabPane tab="Tab 1" key="1">
      Content of Tab Pane 1
    </TabPane>
    <TabPane tab="Tab 2" key="2">
      Content of Tab Pane 2
    </TabPane>
    <TabPane tab="Tab 3" key="3">
      Content of Tab Pane 3
    </TabPane>
  </Tabs>
};

仓库的地址为：https://github.com/huangh69/dumi-template.git
重现步骤：
1.git clone https://github.com/huangh69/dumi-template.git or 直接下载压缩包
2.执行npm install --force or npm install  --legacy-peer-deps
3.执行 npm run build
4.查看控制台报错信息

**Comment by huangh69** [comment]
@

**Comment by PeachScript** [comment]
![图片](https://user-images.githubusercontent.com/5035925/179883539-19ab803b-0ee7-43ff-a5a2-caf8bdb095e9.png)
