### ISSUE TITLE
fastRefresh 的文档站点挂了吗？

### ISSUE THREAD

**Issue by bigbigDreamer** [umijs/dumi#1149]
### Question
[Fast Refresh](https://umijs.org/docs/fast-refresh) 挂了吗？还是移动到了别的站点。
### Sample Code

目前白屏

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/39019913/180613431-8712dfc0-4739-426f-a23f-7239a48e8203.png">

**Comment by PeachScript** [comment]
https://v3.umijs.org/docs/fast-refresh ，链接要更新了

**Comment by bigbigDreamer** [comment]
> https://v3.umijs.org/docs/fast-refresh ，链接要更新了

okk，umijs 站的地址还没更，emm，我先保存了
