### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by fengxinhhh** [umijs/dumi#1152]
### dumi lerna项目可以packages下pc+mobile两套主题在一个项目里切换吗

项目地址：
github:
https://github.com/fengxinhhh/Concis
文档:
http://react-view-ui.com:92

虑把pc/mobile两套组件库做一个项目里，期待解答，感谢。

**Comment by fengxinhhh** [comment]
![image](https://user-images.githubusercontent.com/78004597/181778510-9751381a-adc7-433b-bcab-dc2a22e93b85.png)
![image](https://user-images.githubusercontent.com/78004597/181778601-11c1b179-b206-4a84-b14b-4b17d9c0daf7.png)

**Comment by PeachScript** [comment]
参考：https://d.umijs.org/zh-CN/theme#dumi-theme-mobile
![图片](https://user-images.githubusercontent.com/5035925/182277780-221aa810-c603-44d1-b467-ac2af6249b6b.png)
