### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by singsad** [umijs/dumi#1155]
### Versions

- dumi: 1.1
- node: 16.14
- npm: 8.5
- OS: 
- Browser:

### Steps to reproduce
dumi组件API在别的模块中定义，在组件index.tsx import类型时，MD文档无法展示正确的API。

### What is Expected?
希望可以正常展示

### What is actually happening?
dumi组件API在别的模块中定义，在组件index.tsx import类型时，MD文档无法展示正确的API。
只有在组件index.tsx中定义类型才可以被md文档正确找到并展示。

**Comment by PeachScript** [comment]
底层解析库限制，dumi 2.0 会支持
