### ISSUE TITLE
有办法在配置项里更改babel配置吗

### ISSUE THREAD

**Issue by Fidelgithub** [umijs/dumi#1158]
在组件里引用了wangEditor做富文本编辑，启动时报了警告
[BABEL] Note: The code generator has deoptimised the styling of E:\desktop\pro\qimai-front-end-designpro\node_modules\@wangeditor\editor\dist\index.esm.js as it exceeds the max of 500KB.

![image](https://user-images.githubusercontent.com/17291450/183041250-7e0fb4d8-3848-482f-a7ce-3e8c234f013b.png)

我想要通过babel配置跳过这个500kb的限制
```javascript
{
  compact: false
}
```

**Comment by PeachScript** [comment]
只能 chainWebpack 改 babel-loader 的配置：https://d.umijs.org/config#chainwebpack
