### ISSUE TITLE
feat: 希望 logo 支持 require 本地文件或直接写相对路径

### ISSUE THREAD

**Issue by heynext** [umijs/dumi#116]
RT

**Comment by tsejx** [comment]
附议，现在好像是跳转到非根路径页面刷新后请求的 Logo 路径会带上对应页面路径，就失效了

**Comment by caperso** [comment]
log指的是tab上的icon还是主页logo

**Comment by heynext** [comment]
主页的 logo

**Comment by poyiding** [comment]
@heynext   https://github.com/umijs/dumi/pull/220

**Comment by PeachScript** [comment]
本地 logo 可以走 `public` 目录的方式配置，该 issue 关闭，https://d.umijs.org/config#logo

**Comment by hx-dl** [comment]
> 本地 logo 可以走 `public` 目录的方式配置，该 issue 关闭，https://d.umijs.org/config#logo

但是我是讲dumi集成到了我自己项目的docs目录下编写文档，我的不希望项目根目录下存在public文件夹而希望引入docs/public目录中的图标来做logo,请问有什么好的解决方案呢
