### ISSUE TITLE
dumi 使用 dumi-theme-mobile  demoUrl 外接demo， 如何不再渲染代码块中的内容，只做纯代码展示

### ISSUE THREAD

**Issue by soeasyjx** [umijs/dumi#1162]
## 代码演示
```tsx
/**
 * title: 基础使用
 * hideActions: ['CSB']
 * demoUrl: http://43.142.22.94:8899/bordergradient.html
 */
import { PageLoading } from "fastman3-component-base";
const Demo: FC<{}> = (props) => {
  return (
    <View>
      <PageLoading/>
    </View>
  );
};
```

下面这种写法可以展示demo 但是我的示例代码怎么展示呢
```tsx
/**
 * title: 基础使用
 * hideActions: ['CSB']
 * demoUrl: http://43.142.22.94:8899/bordergradient.html
 */
//
```
我想绿色区域内展示示例代码，但是不进行渲染，应该怎么操作
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/17918538/183244015-c5aa6b97-f6c8-4adf-88b8-9cec9f609057.png">

我的需求是使用 demoUrl 在虚拟手机模型中显示demo ,但是代码块中的代码，我只做纯展示使用，现在dumi 会去进行渲染
现在这样会报错，因为PageLoading 是使用taro 自的，而我又不是安装taro 相关依赖，导至报错

**Comment by cnyballk** [comment]
https://d.umijs.org/zh-CN/config#resolvepreviewlangs

**Comment by soeasyjx** [comment]
> https://d.umijs.org/zh-CN/config#resolvepreviewlangs

previewlangs 并不能满足我的需求，现在公司统一使用dumi来进行文档的编写，通过dumi-theme-mobile demoUrl 引入外部链接，进而在手机模型中进行效果的展示，但是还需要显示纯示例代码，previewlangs会关闭，默认的渲染，因为并不是所有的文档都需要关闭。。。望大神提供一下解决方案

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/17918538/183338775-8658fede-ef8d-4ef6-9ecd-eed116d350ed.png">
红框里需要展示代码，不做渲染
绿框是通过demoUrl 链接进来的外部demo

望大神提供一下解决方案望大神提供一下解决方案

**Comment by soeasyjx** [comment]
算了，我看2.0方案里有我想要的功能，希望能解决，静等2.0版本

**Comment by cnyballk** [comment]
![image](https://user-images.githubusercontent.com/25214319/183346544-8fa7c3d9-c00f-494e-97be-44280234a759.png)

**Comment by soeasyjx** [comment]
> ![image](https://user-images.githubusercontent.com/25214319/183346544-8fa7c3d9-c00f-494e-97be-44280234a759.png)

使用pure标记为纯文档是可以只展示代码，不进行渲染，但是我需要在虚拟手机模型里展示外链的demo ，我使用的主题是dumi-theme-mobile 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/17918538/183348713-9a089118-a253-4522-b8b3-550c87f04f65.png">

**Comment by PeachScript** [comment]
这种用法太特殊了…目前没有低成本的方式实现，只能用成本较高的自定义编译时解：https://d.umijs.org/zh-CN/plugin#dumiregistercompiletime

dumi 2 发布后自定义会简单一些，先关闭了

**Comment by soeasyjx** [comment]
> 这种用法太特殊了…目前没有低成本的方式实现，只能用成本较高的自定义编译时解：https://d.umijs.org/zh-CN/plugin#dumiregistercompiletime
> 
> dumi 2 发布后自定义会简单一些，先关闭了

好吧，期待version 2 ，其实这个需求也比较常见吧。。。。希望能在 第二个版本能很简单的接入
