### ISSUE TITLE
为什么 `dir` routes 里 会排除 `fixtures` 目录

### ISSUE THREAD

**Issue by bigbigDreamer** [umijs/dumi#1166]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/39019913/183664301-faf0ec94-f459-4166-aa03-0fb8967c84ea.png">

如图所示，我在真实使用场景下，正好触发了这个条件.....但是不是很理解为什么要把它排除掉～，我换了个名好了。

<img width="581" alt="image" src="https://user-images.githubusercontent.com/39019913/183664569-ba950108-bfec-48f3-b4e4-4233fb7113d2.png">

**Comment by PeachScript** [comment]
`fixtures` 通常用来放置测试相关文件，https://stackoverflow.com/a/14684400

**Comment by bigbigDreamer** [comment]
> `fixtures` 通常用来放置测试相关文件，https://stackoverflow.com/a/14684400

好的，了解，感谢大佬，这个内容是否有必要体现在文档中？ 其实我排查了好久才发现....

`fixtures` 是否是一种规范化的标准，还是公认的说法，当然我是比较认同的..

因为就 `docs` 工具而言，作为使用者我就认为我可以完全的自由去设置任意的目录作为我的文档文件夹。

**Comment by bigbigDreamer** [comment]
> 可能只是我们认为的开源项目默认规则，并非某个标准，可以帮忙给 dumi 的文档里加上说明：

#1167
