### ISSUE TITLE
静态站点模式样式丢失

### ISSUE THREAD

**Issue by Nealyang** [umijs/dumi#1170]
es 包+cssInModule 方案。
![image](https://user-images.githubusercontent.com/9313216/183826425-f9552d3e-f87e-4f81-831e-f45bab26fc2a.png)
查看相似 issue 都是解决 treeShaking 误删，修改打包增加 sideEffects 的方案。但是貌似并不能解决目前遇到的这个问题

最小 demo 也非常简单
`npx @umijs/create-dumi-app`
![image](https://user-images.githubusercontent.com/9313216/183826693-093760f5-5a09-405e-8834-9a7f5214d3f9.png)

docs下引入相应组件。

现象：
组件如期渲染，但是没有加载 css，以及丢失 class 字段
![image](https://user-images.githubusercontent.com/9313216/183827356-960fb4f0-97d0-4be4-a38d-d50876746672.png)

实际 react 中组件使用时候的渲染：
![image](https://user-images.githubusercontent.com/9313216/183827435-df3711ce-be11-4d7d-aec1-8b64f6a57e84.png)

期望引入外部 react 组件，样式能正常引入，class 不会丢失

**Comment by PeachScript** [comment]
依赖包的 CSS Modules 要走 babel 编译才能生效，需要把相应包名加到这个配置项里：https://d.umijs.org/config#extrababelincludes

组件库不建议使用  CSS Modules，有额外编译成本且使用方很难覆写样式
