### ISSUE TITLE
在构建时提示'isFragment' is not exported by xxx，请问如何解决呢

### ISSUE THREAD

**Issue by shanyijin** [umijs/dumi#1176]
Error: 'isFragment' is not exported by node_modules\react-is\index.js, imported by node_modules\rc-util\es\Children\toArray.js
 
 Code:
  "dependencies": {
    "@ant-design/icons": "~4.7.0",
    "@types/react": "17.x || 18.x",
    "ahooks": "^3.5.0",
    "react": "~18.2.0",
    "react-dom": "~18.2.0",
    "umi": "~3.5.20",
    "umi-plugin-keep-alive": "~0.0.1-beta.30",
    "@umijs/plugin-esbuild": "~1.4.1",
    "@umijs/plugin-qiankun": "~2.36.0",
    "@umijs/preset-react": "1.x"
  },
  "devDependencies": {
    "@baic/eslint-config-yolk": "~2.1.0-alpha.48",
    "@baic/stylelint-config-yolk": "~2.1.0-alpha.48",
    "dumi": "~1.1.47",
    "father-build": "^1.19.1",
    "gh-pages": "^3.0.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0"
  }

**Comment by PeachScript** [comment]
dumi 只负责组件库文档构建，组件库打包相关问题在 father 仓库里找，ref: https://github.com/umijs/father/issues/278#issuecomment-732636637
