### ISSUE TITLE
How do I expand Enum types

### ISSUE THREAD

**Issue by 15167** [umijs/dumi#1188]
` apiParser: {
      shouldExtractLiteralValuesFromEnum: true,
      savePropValueAsString: true,
      shouldRemoveUndefinedFromOptional: true,
        if (prop.parent) {
          return !prop.parent.fileName.includes('node_modules');
        }
        return true;
      },
    },`
在.umirc.ts中这样配置，但是API注解还是不能展开enum类型，看了文档也说把shouldExtractLiteralValuesFromEnum设置成true就行

**Comment by PeachScript** [comment]
1. `apiParser` 只支持传递 `propFilter` 配置项
2. dumi 内部调用时 `shouldExtractLiteralValuesFromEnum` 始终为 `true`，否则展示不了 enum 的值
3. 这个配置项不是用来展开具体类型，只是用来获取 Enum 的 `Literal`

**Comment by 15167** [comment]
那dumi如何展开enum类型呢，我定义了一个enum为比如ButtonType = 'primary'|'danger',然后Api注解显示的就是ButtonType，不会展开为 'primary'|'danger'，这种情况下该如何配置呢？
