### ISSUE TITLE
dumi引用lowcode包报错

### ISSUE THREAD

**Issue by oneQiu** [umijs/dumi#1194]
father配置信息
![image](https://user-images.githubusercontent.com/50658231/188784148-396e4f5a-c2c0-442d-8a4b-fcabdbb8744e.png)

报错信息
![image](https://user-images.githubusercontent.com/50658231/188784088-de0598e8-7f86-40f6-89f2-c39a29564cd3.png)

**Comment by PeachScript** [comment]
demo 代码报错自行解决
