### ISSUE TITLE
demo 中如何引入普通 markdown 文件的内容，而不是被解析成文档？

### ISSUE THREAD

**Issue by jianhao** [umijs/dumi#1197]
最近在实现一个关于 markdown 预览的组件，demos 中需要一些 markdown 文件，但是引入都被解析为函数了，而不是原有的字符串内容，请问该如何引入？

示例代码：
```
import { MSMdNav } from '@moresec/rc-md-toc'
import React from 'react'

import md1 from '../../../assets/demo1.md'

const source = typeof md1 === 'string' ? md1 : ''
console.log('文档md1', md1, source)

export default () => {
  return <MSMdNav source={source} />
}
```

markdown 文档引入的内容被解析如下：
> props => {
  // scroll to anchor after page component loaded
  React.useEffect(() => {
    var _props$location;
    if (props !== null && props !== void 0 && (_props$location = props.location) !== n… 
    
实际希望引入的 markdown 内容是原有 markdown 字符串, 如：
```
# 标题一
## 快速开始
```

**Comment by PeachScript** [comment]
纯文本要单独配 loader，可以用 dumi 内置的 `dumi-raw-code-loader`：

```
import content from '!!dumi-raw-code-loader!./xx.md';
```

或者用 Webpack 提供的 `raw-loader`，配置 `chainWebpack` 配置项把 loader 挂上去：https://v4.webpack.js.org/loaders/raw-loader/

**Comment by jianhao** [comment]
> 纯文本要单独配 loader，可以用 dumi 内置的 `dumi-raw-code-loader`：
> 
> ```
> import content from '!!dumi-raw-code-loader!./xx.md';
> ```
> 
> 或者用 Webpack 提供的 `raw-loader`，配置 `chainWebpack` 配置项把 loader 挂上去：https://v4.webpack.js.org/loaders/raw-loader/

请问使用内置的loader直接这样引入就可以么，不需要其他配置么，我这边是解析不到:
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/30502487/190550810-d63bb04c-9da4-48e5-95b3-040cc5f98b95.png">

dumi 版本：1.1.31

**Comment by PeachScript** [comment]
@jianhao 是有问题，那就是不支持在 demo 里这么写了；chainWebpack 新加一条 raw-loader rule 应该可以，要自己调试 include 和 内置 md-loader 的 exclude，确保其他 md 走 dumi 的 loader，你的 demo md 走新加的 loader

**Comment by jianhao** [comment]
> @jianhao 是有问题，那就是不支持在 demo 里这么写了；chainWebpack 新加一条 raw-loader rule 应该可以，要自己调试 include 和 内置 md-loader 的 exclude，确保其他 md 走 dumi 的 loader，你的 demo md 走新加的 loader

好的，感谢，我有时间再试一下。
另外官方这边能考虑支持一下 markdown 文件的文本解析么，因为对于涉及到 markdown 文件的一些组件，还是需要拿到 markdown 文件内容文本的。

**Comment by PeachScript** [comment]
dumi 1 不加 feature 了，dumi 2 会考虑这个场景

**Comment by jianhao** [comment]
> dumi 1 不加 feature 了，dumi 2 会考虑这个场景

👌🏻，谢谢
