### ISSUE TITLE
dumi是升级了么？配置项有变化么？

### ISSUE THREAD

**Issue by zhouxiny1** [umijs/dumi#1199]
![image](https://user-images.githubusercontent.com/111745349/190945464-ce5ae4c5-813e-41cf-940d-e38144eef94d.png)
![image](https://user-images.githubusercontent.com/111745349/190945516-95465d1b-950b-42b2-8a5d-470822baecb8.png)

启动dumi 结果导航都点击都不会进行跳转，只有刷新页面才会更新。路由已经变了但是导航选中及页面都没有变化。

**Comment by PeachScript** [comment]
最近没有更新，提交 issue 请提供最小可复现仓库
