### ISSUE TITLE
打包的时候 public目录下的静态资源没有打包

### ISSUE THREAD

**Issue by 18355166248** [umijs/dumi#1202]

**Comment by 18355166248** [comment]
我用的是cra 然后用的 cross-env APP_ROOT=dumi dumi build 命令去打包的

**Comment by 18355166248** [comment]
找到原因了 这个dellete 操作影响的 这个操作有必要执行么 `export default {
  chainWebpack(memo) {
    memo.plugins.delete('copy');
  },
};`

**Comment by PeachScript** [comment]
删完 copy 插件对应 copy 配置也会失效
