### ISSUE TITLE
 babel conflict

### ISSUE THREAD

**Issue by 18270219411** [umijs/dumi#1204]
当项目中有自己额外加的babel配置时，如何使dumi不读取此配置文件，依旧默认使用其内部的相关bebel。
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/47958012/191402248-836f2daa-6350-45e8-b030-5d711813ab21.png">

**Comment by PeachScript** [comment]
dumi 不会读这个文件，看报错是 babel 缓存过期，删除 src/.umi 再重跑，还有问题请提供最小可复现仓库
