### ISSUE TITLE
bug: 不能和create-react-app配套使用

### ISSUE THREAD

**Issue by builden** [umijs/dumi#121]
### Versions

- dumi: 0.1.0
- node: 12.13.1
- npm: 6.12.1
- OS: Win7
- Browser: 

### Steps to reproduce
1. 使用create-react-app创建一个全新的工程
2. yarn add dumi -D 安装dumi
3. yarn dumi dev 执行，打开页面
4. 出现错误提示：URIError: Failed to decode param '/%PUBLIC_URL%/favicon.ico'

**Comment by fi3ework** [comment]
Guess this related to https://github.com/umijs/umi/issues/1959

**Comment by builden** [comment]
怎么解决呢？文档中没看到有修改这个配置项的说明

**Comment by PeachScript** [comment]
@xiaohuoni 这个场景配置 document.ejs 是正解么

**Comment by PeachScript** [comment]
在 dumi (Umi) 的约定中，public 会作为默认拷贝到 dist 的文件夹，和 cra 的文件夹冲突了，我们只能二选一；如果选择保留 cra 的逻辑，可使用 `config.chainWebpack` 去掉 dumi 的逻辑：
```js
chainWebpack(memo) {
  memo.plugins.delete('copy');
}
```

如果 dumi 和 cra 的约定都希望保留，可以如法炮制把上述 dumi 的 copy 的规则修改成拷贝类似 `static` 目录。

**Comment by xiaohuoni** [comment]
@PeachScript 还用不惯github新的issues，如果有@我，可以直接钉钉找我下。

**Comment by builden** [comment]
@xiaohuoni 
使用PeachScript的方法，无效。试用过
meme.plugins.delete('copy')
memo.plugins.store.delete('copy')
都不行，会报另一种错误

```ts
// .umirc.ts
import { defineConfig } from 'dumi';

export default defineConfig({
  title: 'dumi',
  mode: 'site', // site | doc
  chainWebpack(memo) {
    memo.plugins.delete('copy');
    memo.plugins.store.delete('copy');
  },
});
```
![image](https://user-images.githubusercontent.com/9499016/80559382-e89d8000-8a0f-11ea-9840-542589da5c6a.png)

**Comment by xiaohuoni** [comment]
@builden 官网更新了说明，可以cc。https://d.umijs.org/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8cra%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F

**Comment by builden** [comment]
@xiaohuoni 使用这种方式，dumi/docs下的md文件，无法引用src目录下的jsx组件

Module parse failed: Unexpected token (4:9)

**Comment by xiaohuoni** [comment]
@builden https://github.com/umijs/dumi/issues/161 这里一起讨论
