### ISSUE TITLE
如何取消dumi黑暗主题仅保留默认主题

### ISSUE THREAD

**Issue by changlin0501** [umijs/dumi#1212]
如何取消dumi黑暗主题仅保留默认主题

**Comment by PeachScript** [comment]
```ts
// .umirc.ts
export default {
  styles: ['.__dumi-default-dark { display: none;  }']
}
```

**Comment by changlin0501** [comment]
收到，感谢解答疑惑，谢谢！
















At 2022-09-28 19:46:54, "Peach" ***@***.***> wrote:

// .umirc.tsexportdefault{styles: ['.__dumi-default-dark { display: none;  }']}
