### ISSUE TITLE
请问一下如何在 md 文件中引入 node_modules 中的样式文件？

### ISSUE THREAD

**Issue by moecasts** [umijs/dumi#1219]
### Question
如题。
### Sample Code
相应的文件都是有的。（不知道会不会是 monorepo 的问题，不过把子包的 `node_modules` 删掉之后还是会报这个错）
<img width="971" alt="image" src="https://user-images.githubusercontent.com/37169906/194037494-1c1c2478-e78f-411c-9550-fa6c93424fb5.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37169906/194037329-2e68111a-7408-4fc7-bcce-4be2f05e5a36.png">

```ts
// .umirc.ts
import { defineConfig } from 'dumi';
import { getPackageAlias, getPackageDocPaths } from './utils';
import * as path from 'path';

const isProd = process.env.NODE_ENV === 'production';

export default defineConfig({
  title: 'dumi',
  mode: 'site',
  sass: {
    sassOptions: {
      includePaths: [path.join(__dirname, 'node_modules')],
    },
  },
  resolve: {
    includes: [
      'docs',
      ...getPackageDocPaths('./packages'),
    ],
  },
  // more config: https://d.umijs.org/config
});
```

**Comment by moecasts** [comment]
在命令行 `node` 中 `required/import` 是可以找到的

**Comment by moecasts** [comment]
用以下路径也可以：
`import '@casts/typography/styles.scss';`

不过想要引入 `dist/umd/typography.css` 的话就没办法了？

**Comment by moecasts** [comment]
找到原因了。。。因为 `dumi` 默认会给子包创建别名，导致不是去 `dist` 下找，而是去了 `src` 目录找。

**Comment by shengwanlin** [comment]
> 找到原因了。。。因为 `dumi` 默认会给子包创建别名，导致不是去 `dist` 下找，而是去了 `src` 目录找。

请问最后怎么解决的？

**Comment by moecasts** [comment]
> 请问最后怎么解决的？

@shengwanlin 自己手动创建新的 alias 覆盖一下
