### ISSUE TITLE
bug: 在使用了第三方组件时，若其含有类似文件名为.module.scss的css module文件时，将无法显示样式

### ISSUE THREAD

**Issue by thisXY** [umijs/dumi#1220]
是因为在node_modules文件夹里的原因吗？还是需要怎么配置一下.umirc.ts文件吗？求解决啊！

**Comment by PeachScript** [comment]
文档编译的自动 css modules 依赖 babel，需要把第三方 NPM 包加到这个配置项里：https://d.umijs.org/config#extrababelincludes

**Comment by thisXY** [comment]
esModule的js文件还是无法生效。。

> 文档编译的自动 css modules 依赖 babel，需要把第三方 NPM 包加到这个配置项里：https://d.umijs.org/config#extrababelincludes

**Comment by thisXY** [comment]
还是自己配chainWebpack解决了 = =
