### ISSUE TITLE
希望添加本地图片识别的功能

### ISSUE THREAD

**Issue by zoeminghong** [umijs/dumi#123]
### Description

无法识别本地图片路径，例如：`./assert/001.jpg`

**Comment by PeachScript** [comment]
感谢提议，在计划中了，临时方案可以把图片放进 `/public` 文件夹下，例如 `/public/logo.png`，那么访问 `localhost:8000/logo.png`

**Comment by PeachScript** [comment]
v1.0.9 已支持

**Comment by ltchronus** [comment]
#849  
publicPath 在production部署不生效，gg
