### ISSUE TITLE
基于Antd的组件库打包后发布到npm，下载到Next项目中，使用组件库报错

### ISSUE THREAD

**Issue by li-yu-tfs** [umijs/dumi#1233]
### Question
打包后发布到npm，下载到Next项目中，使用组件库报错
![image](https://user-images.githubusercontent.com/108653248/196988262-e42b77a6-df0e-4473-a99c-5e1f48c49639.png)

### Sample Code
![image](https://user-images.githubusercontent.com/108653248/196988402-36bd7423-6429-43d1-bd2f-1773848d1a98.png)
![image](https://user-images.githubusercontent.com/108653248/196988426-8020ba50-cf62-414e-9bdc-3b55ac140132.png)

**Comment by li-yu-tfs** [comment]
我的Next项目中也使用了antd，是互相有什么冲突吗？

**Comment by li-yu-tfs** [comment]
@PeachScript  https://github.com/lxulxu555/dumi-bug-demo 你好，我换了个账号创建麻烦你看看

**Comment by PeachScript** [comment]
去掉 babel-plugin-root-import 试下，father 4 是支持配置 alias 的，不需要额外的插件来转换引入路径了

**Comment by li-yu-tfs** [comment]
不行，就是因为不行，所以才加上了这个，结果发现加上这个还是不行

**Comment by PeachScript** [comment]
> 打包后发布到npm，下载到Next项目中，使用组件库报错
> ![image](https://user-images.githubusercontent.com/108653248/196988262-e42b77a6-df0e-4473-a99c-5e1f48c49639.png)

是我看错了，错误截图的意思是，你需要配置 less loader 才能正常加载 less 文件，参考 Next.js 的文档进行配置即可

**Comment by li-yu-tfs** [comment]
我有个疑问，这就是我引入了组件库才会造成的问题，如果不使用组件库是没有任何问题的。如果说是less-loader的问题，那么为什么我next.js项目也引入了antd，antd也引入less。就不会有问题呢？

**Comment by PeachScript** [comment]
可能和 Next.js 的默认配置有关系，可以去它的文档或者 issue 里找找解法；我这里使用 Umi 的默认配置是可以正常编译的

**Comment by li-yu-tfs** [comment]
我尝试在create-react-app已经使用antd的情况，再用该代码提交的npm包，依旧会有问题。请问，可以方便使用此份代码打包一个npm库进行尝试吗？
