### ISSUE TITLE
feat: markdown import support 支持markdown导入

### ISSUE THREAD

**Issue by aak1247** [umijs/dumi#1234]
### Description

类似docusaurus，支持引入其他Markdown(mdx)文件来便于管理页面，参考 https://www.docusaurus.cn/docs/markdown-features/react

### Solution

可以考虑引入[mdx](https://www.mdxjs.cn/)

**Comment by PeachScript** [comment]
迁移其他 md 是支持的：https://d.umijs.org/zh-CN/guide/basic#embed

但 MDX 不支持、目前也不在计划之内，dumi 有别于 Docusaurus、重心是组件研发场景；早期 father doc 集成的 Docz 就是 MDX，但实际研发存在的问题不少，比如 MDX 编写的 demo 源代码用户是没法复制使用的，因为缺少 import 等信息、JSX 之外的逻辑代码也展示不了

**Comment by aak1247** [comment]
能否顺便问一下embed引入后渲染出来的目录位于API后是什么导致的？（embed位置在API之前）

**Comment by PeachScript** [comment]
应该是 bug，dumi 1.x 的 embed 实现有点反模式、修不动了，dumi 2 换了实现，如果是新项目可以试下
