### ISSUE TITLE
是否可以跟 umi 2.x 一起使用

### ISSUE THREAD

**Issue by L-Jovi** [umijs/dumi#124]
### Question

我用 umi 2.x 生成的 ant design pro 模板项目，安装了 dumi 后新增加了一个 scrips 命令到 package.json 中

```
"start:doc": "dumi dev",
```

然后运行 yarn start:doc 发现实际运行的是 umi 2 的 dev 命令。。dumi 自己好像都没调用起来

**Comment by PeachScript** [comment]
dumi 只支持 Umi 3，且 Umi 3 更快、更小、更强大，强烈建议升级；虽然 dumi 的前身 father-doc 支持 Umi 2，但已经不再维护了，如果执意要使用可以查看此项目的 `father-doc` 分支

**Comment by L-Jovi** [comment]
@PeachScript 我也想用 umi 3.x，但是我发现不提供初始项目的模板选择功能了，这边的需求是想用 ant design pro 作为初始模板，为何 umi 3.x 不支持了？

**Comment by PeachScript** [comment]
@chenshuai2144 pro 有提供 umi 3 的初始化模板吗
