### ISSUE TITLE
bug: dumi 编译less报错

### ISSUE THREAD

**Issue by EruditionTu** [umijs/dumi#1244]
### Versions
- dumi:1.1.47
- node:14.15.0
- OS:windows
- Browser:chrome

dumi编译组件的时候会报一个无法编译less的错误
 error  in ./components/button/style/index.less

Module build failed (from ./node_modules/@umijs/bundler-webpack/lib/webpack/plugins/mini-css-extract-plugin/src/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@umijs/deps/compiled/less-loader/cjs.js):

.btn-disabled {
  .disabled();
^
Variable @disable-color is undefined
      in D:\Opensource\RecycleUI\components\button\style\index.less (line 183, column 2)
    at D:\Opensource\RecycleUI\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109216:20
    at D:\Opensource\RecycleUI\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:61151:11
    at D:\Opensource\RecycleUI\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:61017:18
    at context.callback (D:\Opensource\RecycleUI\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:60895:13)

 @ ./components/button/style/index.tsx 1:0-22
 @ ./components/button/demo/basic.tsx
 @ ./.umi/dumi/demos/index.ts
 @ ./.umi/dumi/layout.tsx
 @ ./.umi/core/routes.ts
 @ ./.umi/umi.ts
 @ multi ./.umi/umi.ts

**Comment by PeachScript** [comment]
缺变量，请自行 debug
