### ISSUE TITLE
feat: 支持 组件 live editor

### ISSUE THREAD

**Issue by ytftianwen** [umijs/dumi#1249]
### Description
怎么自定义组件区块的渲染呢，想支持live editor功能，codesanbox的话无法加载内网npm包
### Solution
类似于smooth doc：https://smooth-doc.com/docs/getting-started/

**Comment by PeachScript** [comment]
可以替换内置的 Previewer 组件，就能自定义渲染了，但具体怎么自定义需要你自己实现，替换内置的渲染组件可以参考：https://d.umijs.org/zh-CN/theme/development#%E5%A2%9E%E9%87%8F%E8%87%AA%E5%AE%9A%E4%B9%89
