### ISSUE TITLE
bug: 运行build出来的文件无法正常显示

### ISSUE THREAD

**Issue by LLLLLamHo** [umijs/dumi#125]
![image](https://user-images.githubusercontent.com/19260349/77061932-ff66b500-6a15-11ea-89f9-a7580a15b7c3.png)
应该如何配置才能让md文件的访问路径进行自定义

**Comment by PeachScript** [comment]
build 的资源需托管在 server 下，直接双击 html 是不行的，本地可以全局装个 `anywhere`
