### ISSUE TITLE
bug: dumi 1.x  build之后的文档无法在unpkg查看

### ISSUE THREAD

**Issue by ytftianwen** [umijs/dumi#1256]
### Versions

- dumi: 1.1.49
- node: 16.16.0
- npm: 
- OS:
- Browser: chrome

### Steps to reproduce

1. 运行 dumi build
2. 将产物 docs-dist/* 上传到npm
3. 访问https://unpkg.com/[pkg]@[version]/index.html

### What is Expected?

期望能通过unpkg正常展示

### What is actually happening?

如图所示，组件内容区是空白的
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/13484089/200556811-43b9f83a-a829-4954-93b1-95b87914f408.png">
经查看，content区域是空的
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/13484089/200557058-867575e6-086d-4ec3-b5bb-9b57ac8c729a.png">

**Comment by ytftianwen** [comment]
补充： 如果是放到服务器上是正常展示的，但是通过unpkg/xxxx/index.html 访问有问题

**Comment by PeachScript** [comment]
该问题非 dumi 的 scope，并且 unpkg.com 也不是静态站点托管服务，请用 gh-pages 之类真正的站点托管服务替代

**Comment by ytftianwen** [comment]
> 该问题非 dumi 的 scope，并且 unpkg.com 也不是静态站点托管服务，请用 gh-pages 之类真正的站点托管服务替代

更新：启用```exportStatic```可正常通过xxx.html在unpkg.com访问

感谢回复~
