### ISSUE TITLE
dumi开发的组件在umi项目里可正常使用，在其他ssr项目报错

### ISSUE THREAD

**Issue by DBznhaung** [umijs/dumi#1259]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/21373880/200778363-0625bab6-bd05-4d03-885c-a04e22c93757.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/21373880/200779382-c691c9ea-2d11-4b47-9fcd-4608a96c4dad.png">

**Comment by PeachScript** [comment]
与组件具体实现有关问题请自行解决
