### ISSUE TITLE
feat: monorepo项目全局配置是否可以支持分包自动检测

### ISSUE THREAD

**Issue by GIScyw** [umijs/dumi#1264]
**Description：**
如下，设置别名时无法通过包名自动匹配到当前分包名，需要增加一条新的别名才可以
<img width="735" alt="image" src="https://user-images.githubusercontent.com/31304946/201324330-a9862a3e-b8ac-4871-90c6-36a582772266.png">

期望：
不同包名冲突时，不需要新增别名来避免，可以有一个变量匹配到当前包名
```
  alias: {
        '@utils': `${process.cwd()}/packages/${anypackage}/src/utils`,
    },
```

**Comment by PeachScript** [comment]
无法支持，alias 必须是静态值

monorepo 下不建议对源码子目录做 alias，不光要处理文档构建、还要处理源码构建、类型声明，问题会复杂化，建议只 alias 包名到 src
