### ISSUE TITLE
ts declare warning 问题

### ISSUE THREAD

**Issue by lsky-walt** [umijs/dumi#1268]
### ts declare warning 问题

1. 创建一个例子
```shell
yarn create @umijs/dumi-lib
```
2. 在 src/Foo 文件夹下创建 foo.tsx
3. foo.tsx 写入代码
```tsx
import React from 'react';

export interface FooProps {
  title?: string
}

const Foo: React.FC<FooProps> = ({title}) => {
  return <h1 className="test-css-style">{title}</h1>;
}

export default Foo
```
4. 修改 src/Foo/index.tsx
```tsx
import React from 'react';

export { FooProps } from "./foo"
import Foo from './foo'

export default Foo
```

5. 修改 src/index.ts
```tsx
export { default as Foo } from './Foo';
export type { FooProps } from './Foo';
```

最后文件夹结构：
![image](https://user-images.githubusercontent.com/20224722/201620563-a2221605-e530-4f4e-8d02-f3025e1b5817.png)

### 本地起服务之后，控制台会报warning问题
![image](https://user-images.githubusercontent.com/20224722/201619955-73d289fc-3265-4648-be70-6bf3d9cdad4c.png)

这个有没有解决方案？

**Comment by PeachScript** [comment]
Babel 是单文件编译的，处理不了不带 type 的类型 export，第 4 步用 export type { FooProps } from './Foo' 即可
