### ISSUE TITLE
dumi alias 当前项目的包后引入组件，无法加载我覆盖的 antd 样式

### ISSUE THREAD

**Issue by HiJackSherlock** [umijs/dumi#127]
### Question
dumi alias 当前项目的包，引入项目组件同时使用了babel-plugin-import，组件封装了antd，但无法加载我覆盖的 antd 样式，如下图：

### Sample Code
样式覆盖如下：
![image](https://user-images.githubusercontent.com/17284380/77078497-9ee57100-6a31-11ea-9288-22f4beab3502.png)
实际运行效果：
![image](https://user-images.githubusercontent.com/17284380/77078616-ca685b80-6a31-11ea-807e-4899119f73b0.png)
但 source 文件是有样式的，就是没有加载：
![image](https://user-images.githubusercontent.com/17284380/77078738-f683dc80-6a31-11ea-8c97-efe03caf62f6.png)
项目的 .umirc 配置如下：
```
import { defineConfig } from 'dumi';

// more config: https://d.umijs.org/config
export default defineConfig({
  title: 'CRM 组件库',
  logo: 'http://www.staticec.com/www/images/cs/logo.3.png',
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
      'antd'
    ],
    [
      'babel-plugin-import',
      {
        libraryName: '@workec/ec-crm-components/lib/extra',
        libraryDirectory: '',
        style: true,
        camel2DashComponentName: false,
      },
    ],
  ],
});
```
请问如何解决？

**Comment by PeachScript** [comment]
推测 `babel-plugin-import` 的配置有问题，提供个复现 repo 吧

**Comment by HiJackSherlock** [comment]
查看我组件库里的 antd 版本为 4.0.3，当时封装 antd 组件时引用的是 3.23.x 版本，由于是 breaking change，部分 antd 组件内部样式名改变，所以覆盖不上。

现还原版本，样式成功覆盖。

谢谢啦。
