### ISSUE TITLE
bug: tsx demo文件无法自动建立组件库 NPM 包

### ISSUE THREAD

**Issue by blockmood** [umijs/dumi#1279]
### Versions

- dumi:2.0.2
- node:14+
- npm:
- OS:
- Browser:

### Steps to reproduce
![1668765487572](https://user-images.githubusercontent.com/22879524/202675352-fed1ba8c-ee78-4c33-9205-58e8f02e7d4f.jpg)

但是md文件里 `dntd` 是可以的
![3333](https://user-images.githubusercontent.com/22879524/202675319-ccec1c8d-0860-4ef0-b233-5fbe790c74ab.jpg)

**Comment by PeachScript** [comment]
这是缺类型，确保脚手架生成的 tsconfig.json 里映射是正确的，正常来说初始化的时候只要输入正确的 NPM 包名就能获得正确的配置：https://github.com/umijs/dumi/blob/master/suites/boilerplate/templates/react/tsconfig.json.tpl#L11

**Comment by blockmood** [comment]
@PeachScript 
我确认了下 我的ts配置

```
{
  "compilerOptions": {
    "strict": true,
    "declaration": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "jsx": "react",
    "baseUrl": "./",
    "paths": {
      "@@/*": [".dumi/tmp/*"],
      "dntd/*": ["src/*", "*"]
    }
  }
}
```

感觉没有问题啊。

**Comment by PeachScript** [comment]
模板有点问题，dnd/* 要改成 dnd

**Comment by caijf** [comment]
> 模板有点问题，`"dntd/*": ["src/*", "*"]` 要改成 `"dntd": ["src"]`

v2.0.3 加了这个配置还是一样找不到这个包

**Comment by blockmood** [comment]
@PeachScript  感觉不是模板的问题 

![企业微信截图_1a9646c0-a9ef-4d7b-a20e-c7228b63a16e](https://user-images.githubusercontent.com/22879524/202947801-332dc562-6684-4bf1-ada0-b0e462e584e1.png)

**Comment by caijf** [comment]
> 模板有点问题，`"dntd/*": ["src/*", "*"]` 要改成 `"dntd": ["src"]`

v2.0.3 加了这个配置，类型是有了，但demo还是不显示

**Comment by PeachScript** [comment]
用 v2.0.3 重新初始化无法复现，提供下最小可复现仓库吧

**Comment by caijf** [comment]
> 用 v2.0.3 重新初始化无法复现，提供下最小可复现仓库吧

<img width="734" alt="image" src="https://user-images.githubusercontent.com/5070722/202953964-ea4564e5-755d-4d15-8a94-897d761fb51b.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/5070722/202953994-44fbea27-3ed9-4bcb-98d3-53481b5f9ee2.png">

<img width="672" alt="image" src="https://user-images.githubusercontent.com/5070722/202954090-4bc12731-07ec-4da7-898d-77371f10e6c2.png">

**Comment by PeachScript** [comment]
@caijf code 必须是双标签，单标签不是合法 HTML，dumi 2 不识别了

**Comment by caijf** [comment]
> @caijf code 必须是双标签，单标签不是合法 HTML，dumi 2 不识别了

改成双标签可以了！

v1 是可以单标签的，文档中貌似没有这个升级改动点说明。

**Comment by PeachScript** [comment]
@caijf 漏掉了，有兴趣可以来个 PR 帮忙完善文档
