### ISSUE TITLE
question: dumi2.0没有暗黑模式了吗？

### ISSUE THREAD

**Issue by fengxinhhh** [umijs/dumi#1288]
### Question
question: dumi2.0没有暗黑模式了吗？

**Comment by kakachake** [comment]
同问

**Comment by PeachScript** [comment]
暂时没有，后续版本会加上

**Comment by fanhualei** [comment]
深度dumi使用者，升级了一下，感觉功能挺好的。为了不给自己添麻烦，退回原先的版本。 准备等3个月后，再升级。

**Comment by fengxinhhh** [comment]
@fanhualei 同深度用户，原dumi1的情况基于组件库暗黑切换的`localStorage`做了两色主题，现在直接没了有点伤~考虑现阶段自己先临时封装个简易版的了~

**Comment by PeachScript** [comment]
v2.1.0 已支持暗色模式
