### ISSUE TITLE
符号转义失败

### ISSUE THREAD

**Issue by zoeminghong** [umijs/dumi#129]
在编译的时候，由于md文档示例代码中存在 `<krbPath>` 存在就出现报错

### Versions

- dumi: 1.0.9
- node: v13.8.0
- npm: 6.13.6
- OS: MacOS
- Browser: Chrome

### Steps to reproduce

npm run start

### What is Expected?

支持如上情况，正确通过，目前好像txt MarkDown 语法标注也不支持

### What is actually happening?

![image](https://user-images.githubusercontent.com/10401743/77221278-55a53680-6b83-11ea-9f52-317700c413ea.png)

![image](https://user-images.githubusercontent.com/10401743/77221314-a87eee00-6b83-11ea-828b-517fead5f524.png)

**Comment by PeachScript** [comment]
非标准 HTML 标签需自行处理自闭合以符合 JSX 语法

**Comment by PeachScript** [comment]
补充一下，如果是需要展示 HTML 标签而不做渲染，需要手动转义，比如 `&lt;krbPath&gt;`
