### ISSUE TITLE
支持按键盘 / 或 cmd + K 打开搜索弹框

### ISSUE THREAD

**Issue by afc163** [umijs/dumi#1290]
<img width="1026" alt="图片" src="https://user-images.githubusercontent.com/507615/202853994-bc692f79-5703-408d-baa6-4c9f6186b45d.png">

https://4x.ant.design/index-cn

**Comment by PeachScript** [comment]
现在 cmd+K 是支持聚焦到输入框的，是指弹出一个专门的搜索框吗

**Comment by afc163** [comment]
对 否则滚动到页面下面再按 体验就不太好
