### ISSUE TITLE
bug: Windows环境下自动生成的代码中，路径异常的问题

### ISSUE THREAD

**Issue by ZN1996** [umijs/dumi#1291]
### Versions

- dumi: v2.0.2
- node: v14.18.2
- npm: v6.14.5
- OS: Windows 10
- Browser: Microsoft Edge 107.0.1418.35

### Steps to reproduce
1.下载ant-design代码库并安装依赖。
2.npm start
![image](https://user-images.githubusercontent.com/15108453/202854919-e95ab774-c5aa-4a53-85e4-3ae9b52692f1.png)
3.访问本地网址，窗口与控制台均有错误输出。
![image](https://user-images.githubusercontent.com/15108453/202855000-12da5c91-5012-40ba-ab12-adb8c5b573f5.png)
![image](https://user-images.githubusercontent.com/15108453/202855016-4716619c-4cdc-4859-bf86-bf2885f99278.png)
4.经过对问题的排查与定位，发现是某个生成的文件中，在路径表示上使用了windows的表达方式。
![image](https://user-images.githubusercontent.com/15108453/202855274-35ecee60-177c-498a-98cd-e3e8c8e5ee84.png)
5.我对这个问题想到的解决方案（不知道考虑得周不周全，还望指教）：
修改 dumi/src/features/meta.ts 这个文件。
![image](https://user-images.githubusercontent.com/15108453/202855877-bf739075-9a5f-4346-b44a-8080d9700e76.png)
使用winPath方法对文件路径进行转换。

### What is Expected?
生成能正确识别的路径地址
![image](https://user-images.githubusercontent.com/15108453/202855641-cd94310d-f2e7-4297-bf3b-77cf5cae460a.png)
此处地址改成上图之后，刷新浏览器，页面能正常显示。
![image](https://user-images.githubusercontent.com/15108453/202855600-ed006bfc-04e4-454a-9e96-62a61e95d377.png)

### What is actually happening?
未生成能正确识别的路径地址
![image](https://user-images.githubusercontent.com/15108453/202855274-35ecee60-177c-498a-98cd-e3e8c8e5ee84.png)

**Comment by PeachScript** [comment]
感谢帮忙排查原因，思路没问题，欢迎直接提交 PR 修复
