### ISSUE TITLE
bug: 外部引入demo，frontmatter 配置不生效

### ISSUE THREAD

**Issue by caijf** [umijs/dumi#1299]
### Versions

- dumi: v2.0.3
- node: 16
- npm: 8
- OS: MacOS 12
- Browser: 

### Steps to reproduce

`markdown`  内编写 `frontmatter` 是正常的，但是外部引入 demo `frontmatter` 就不生效了。

<img width="379" alt="image" src="https://user-images.githubusercontent.com/5070722/202997184-a58d1e23-629f-421c-b3d6-86c62ebda634.png">

### What is actually happening?

<img width="641" alt="image" src="https://user-images.githubusercontent.com/5070722/202997337-59f571af-638a-4bc9-b603-b7e93b5e2b76.png">

**Comment by PeachScript** [comment]
v2.0.4 已修复
