### ISSUE TITLE
如果用github page部署

### ISSUE THREAD

**Issue by LLLLLamHo** [umijs/dumi#130]
### Question
如果用github page部署

**Comment by afc163** [comment]
虽然很简单，但是如果官网写个手把手的文档有助于推广。

@PeachScript

**Comment by afc163** [comment]
还可以做一个 GitHub action。

**Comment by LLLLLamHo** [comment]
我就想知道如果我使用dumi能不能编译成纯静态页面，直接部署到github page中进行使用

**Comment by afc163** [comment]
@LLLLLamHo dumi 就是做这个用的。

**Comment by chenshuai2144** [comment]
@PeachScript  看一下这个 action
https://github.com/ant-design/ant-design-pro-layout/blob/master/.github/workflows/deploy.yml

**Comment by LJJCherry** [comment]
关注

**Comment by shaodahong** [comment]
手摸手 Faq https://github.com/umijs/dumi/pull/137

**Comment by shaodahong** [comment]
@afc163 搞个 now 看看

**Comment by whistleyz** [comment]
1. 脚本 .deploy.sh
```shell
#!/usr/bin/env bash

# 确保脚本抛出遇到的错误
set -e

# 生成静态文件
npm run build

# 进入生成的文件夹
cd dist

# 如果是发布到自定义域名
# echo 'www.example.com' > CNAME

git init
git add -A
git commit -m 'deploy'

git push -f git@github.com:whistleyz/blog-doc.git master:gh-pages

cd -
```

2. 配置 .umirc.js 
```js
export default {
  history: {
    // history 方式肯定不支持
    type: 'hash'
  },
  // 路由基础路径
  base: '/<REPO>/',
  // 静态文件
  publicPath: '/<REPO>/'
}
```

**Comment by PeachScript** [comment]
@whistleyz 不建议用 hash 路由，锚点会不好用，开启 `exportStatic: {}` 就可以保证刷新页面也能访问了

**Comment by whistleyz** [comment]
> @whistleyz 不建议用 hash 路由，锚点会不好用，开启 `exportStatic: {}` 就可以保证刷新页面也能访问了

OK
