### ISSUE TITLE
bug: alias配置引入路径别名`'@': 'src'`不生效, Module not found: Error: Can't resolve...

### ISSUE THREAD

**Issue by birdmanmandbir** [umijs/dumi#1302]
### Versions

- dumi: 2.0.0-rc.0
- node: v16.17.0
- npm: 8.15.0
- OS: windows
- Browser: edge

### Steps to reproduce
[最小化复现仓库](https://github.com/birdmanmandbir/dumi2-template)
初始化dumi2工程, 编辑`tsconfig.json`及`.dumirc.ts`, 添加`'@': 'src'`对应的路径别名
```json
// tsconfig.json
    "baseUrl": "./",
    "paths": {
      "@/*": ["src/*"],
      "@@/*": [".dumi/tmp/*"],
      "dumi2-template": ["src"],
      "dumi2-template/*": ["src/*", "*"]
    }
```
```ts
// .dumirc.ts
export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    name: 'dumi2-template',
  },
  alias: {
    '@': 'src'
  }
});
```

Foo.tsx引入其他目录的文件, 例如
```ts
import { add } from '@/utils/common.util';
```

### What is Expected?
无报错, 正常引入
![image](https://user-images.githubusercontent.com/48193000/203073454-bf94a1a2-e9b8-41bf-a448-fe3b60e4c4c9.png)

### What is actually happening?
报错: <mark>Module not found: Error: Can't resolve '@/utils/common.util' in 'D:\codes\dumi2-template\src\Foo'</mark>

**Comment by PeachScript** [comment]
v2.0.4 已修复

**Comment by ArthurBoyle** [comment]
Versions
dumi: 2.0.5
node: v16.6.0
npm: 7.20.3
OS: windows
Browser: edge


必须同时设置 tsconfig 和 alias 才可以实现吗？
我只设置 tsconfig 会提示 Module not found: Error: Can't resolve...
如果按照上面的方式设置 alias，则 .dumi 文件夹会被编译在 src 文件夹中，同时报错：
Module not found: Error: Can't resolve 'src\.dumi\tmp\umi.ts' in 'xxxxxxxx'
Did you mean './src\.dumi\tmp\umi.ts'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

**Comment by birdmanmandbir** [comment]
> Versions dumi: 2.0.6 node: v16.6.2 npm: 7.20.3 OS: windows Browser: edge
> 
> 必须同时设置 tsconfig 和 alias 才可以实现吗？ 我只设置 tsconfig 会提示 Module not found: Error: Can't resolve... 如果按照上面的方式设置 alias，则 .dumi 文件夹会被编译在 src 文件夹中，同时报错： Module not found: Error: Can't resolve 'src.dumi\tmp\umi.ts' in 'xxxxxxxx' Did you mean './src.dumi\tmp\umi.ts'? Requests that should resolve in the current directory need to start with './'. Requests that start with a name are treated as module requests and resolve within module directories (node_modules). If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

要同时设, alias这样配保险一点:
```js
  alias: {
    '@': path.resolve(__dirname, 'src'),
  },
```

**Comment by ArthurBoyle** [comment]
> > Versions dumi: 2.0.6 node: v16.6.2 npm: 7.20.3 OS: windows Browser: edge
> > 必须同时设置 tsconfig 和 alias 才可以实现吗？ 我只设置 tsconfig 会提示 Module not found: Error: Can't resolve... 如果按照上面的方式设置 alias，则 .dumi 文件夹会被编译在 src 文件夹中，同时报错： Module not found: Error: Can't resolve 'src.dumi\tmp\umi.ts' in 'xxxxxxxx' Did you mean './src.dumi\tmp\umi.ts'? Requests that should resolve in the current directory need to start with './'. Requests that start with a name are treated as module requests and resolve within module directories (node_modules). If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
> 
> 要同时设, alias这样配保险一点:
> 
> ```js
>   alias: {
>     '@': path.resolve(__dirname, 'src'),
>   },
> ```

我看过您的最小化复现仓库，也按照这种方式尝试过，还是会出现我上面描述的问题

**Comment by birdmanmandbir** [comment]
dumi是否升级到了最新版? 我当时看是没问题的

**Comment by ArthurBoyle** [comment]
> dumi是否升级到了最新版? 我当时看是没问题的 @ArthurBoyle

版本为2.0.6

**Comment by birdmanmandbir** [comment]
> > dumi是否升级到了最新版? 我当时看是没问题的 @ArthurBoyle
> 
> 版本为2.0.6

这个issue已经关了， 建议新提一条， 附上你自己的最小化复现仓库

**Comment by ArthurBoyle** [comment]
> > > dumi是否升级到了最新版? 我当时看是没问题的 @ArthurBoyle
> > 
> > 
> > 版本为2.0.6
> 
> 这个issue已经关了， 建议新提一条， 附上你自己的最小化复现仓库

感谢！
