### ISSUE TITLE
bug: The RTL/LTL button cannot be found on the page

### ISSUE THREAD

**Issue by fengxinhhh** [umijs/dumi#1304]
### Versions

- dumi:2.0.2
- node:16.13.2
- npm:8.1.2
- OS:mac os
- Browser:chrome

### Steps to reproduce

页面header中无法看到RTL/LTL按钮，`localstroage` 中加入参数可以实现效果。

### What is Expected?

页面header中可以看到RTL/LTL按钮。

![image](https://user-images.githubusercontent.com/78004597/203088949-8807b124-6428-414b-8494-858f61d5bf0f.png)

**Comment by miracles1919** [comment]
要加配置

```js
themeConfig: {
  rtl: true,
}
```

**Comment by fengxinhhh** [comment]
收到~文档上貌似没找到，close~
