### ISSUE TITLE
feat: support to search full content of site

### ISSUE THREAD

**Issue by shebaoting** [umijs/dumi#131]
目前的搜索支持比较差，好像仅仅支持搜索标题

其他，文档内除了标题之外的所有内容都无法搜索。这对一个文档工具来说，问题极大。

文档写了一大堆，但是如果别人想精确找到某个问题的文档，却很难。只能在知道标题的情况下搜索。

这不合理。希望作者能改进。谢谢。

**Comment by PeachScript** [comment]
考虑到搜索性能和 bundle size，目前只做了标题搜索，后续可能会支持接入 algolia，如果有好的解法，欢迎 PR

**Comment by shebaoting** [comment]
好的。谢谢您。

**Comment by yesmeck** [comment]
algolia +1

**Comment by zhaoyao91** [comment]
真的可以搜标题吗，我这里标题都搜不了

**Comment by PeachScript** [comment]
v1.0.23 已支持 algolia (#173 by @yesmeck 👍)，issue 关闭
