### ISSUE TITLE
bug: code block 中使用 tsx 编译报错

### ISSUE THREAD

**Issue by kingback** [umijs/dumi#1311]
### Versions

- dumi: 2.0.3
- node:
- npm:
- OS:
- Browser:

### What is actually happening?

<img width="938" alt="image" src="https://user-images.githubusercontent.com/471003/203252863-a6b94bb0-6b28-479e-a518-0ff2c0f0721e.png">

**Comment by PeachScript** [comment]
v2.0.4 已修复
