### ISSUE TITLE
bug: 从 dumi 导入的 API 缺少类型定义。

### ISSUE THREAD

**Issue by Codennnn** [umijs/dumi#1313]
TS 会报告无导出成员，但实际上可以正常使用。

![image](https://user-images.githubusercontent.com/47730755/203253655-fca03665-5093-47be-8189-ac002801ece7.png)

### Versions

- dumi: 2.0.3

复现仓库：https://github.com/Codennnn/create-dumi

**Comment by Codennnn** [comment]
引发这个问题的原因是，在 `.dumi` 文件夹内部不能正确解析 `@@/*`。

在实际配置中， `@@/*` 指向 `.dumi/tmp/*`，而在 `.dumi` 内却没有此路径，导致找不到 `.dumi/tmp/exports.ts`。

**Comment by PeachScript** [comment]
感谢反馈，`.dumi/tsconfig.json` 的内容有问题导致解析失败

**Comment by PeachScript** [comment]
v2.0.6 已修复
