### ISSUE TITLE
bug: monorepo demo文件无法自动建立组件库 NPM 包

### ISSUE THREAD

**Issue by JaylanChen** [umijs/dumi#1314]
### Versions

- dumi: v2.0.4
- node: v16.18.0
- npm: v8.19.2
- pnpm: v7.17.0
- OS: win10
- Browser: Edge v107

### Steps to reproduce
[demo 仓库](https://github.com/JaylanChen/dumi-error)

使用dumi2 维护 monorepo；
1. 配置 .dumirc.ts
```
  resolve: {
    atomDirs: [{ type: 'component', dir: 'packages' }],
  },
```
2. tsconfig.json 配置别名
```
"@xyz/button": ["packages/button/src/index.tsx"]
```
3. npm start 
demo解析包出错；

### What is Expected?
能够正常解析

### What is actually happening?

![image](https://user-images.githubusercontent.com/7055008/203290257-46576f09-2040-41b9-a1e4-40061cfa1376.png)

**Comment by PeachScript** [comment]
monorepo 下的 alias 目前需要自行配置：https://d.umijs.org/config#alias
