### ISSUE TITLE
外部 demo 实现方法

### ISSUE THREAD

**Issue by stephenliu1944** [umijs/dumi#1316]
### Question
请问dumi是如何实现 markdown 中导入外部 demo 的?
### Sample Code
```
<code src="/path/to/complex-demo.tsx"></code>
```

**Comment by PeachScript** [comment]
相关源码：https://github.com/umijs/dumi/blob/master/src/loaders/markdown/transformer/rehypeDemo.ts#L108

后续非使用相关疑问请提 discussion，issue 是用来讨论问题的
