### ISSUE TITLE
dumi2.0 <API></API> 标签的使用示例

### ISSUE THREAD

**Issue by textqaz** [umijs/dumi#1317]
### Question
求文档中更新 <API></API> 标签的使用示例，之前1.0文档中的示例 在2.0好像并不能适用。

**Comment by PeachScript** [comment]
还在试验阶段，暂不提供文档

**Comment by yzw2017** [comment]
1.0都有，2.0没有，我还特意看1.0版本，试半天都搞不出来。 最基本的东西都没有麻烦你先别发布给人用好吗，要么你就官网说明暂不支持。浪费别人时间

**Comment by 18281033262** [comment]
那请问，现在dumi2没有自动生成文档，那应该怎么写组件对应得api文档呢

**Comment by Go7hic** [comment]
大概啥时候更新这功能？之前都是自动生成的API表格文档 现在升级之后总不能全部改成手写吧。

感觉我这两天升级白升级了 不能上线用😂

**Comment by Go7hic** [comment]
> 

你要是有时间，可以自己用 markdown 表格语法写 效果都是一样的 就是蠢了一点

**Comment by Go7hic** [comment]
> 那请问，现在dumi2没有自动生成文档，那应该怎么写组件对应得api文档呢

你要是有时间，可以自己用 markdown 表格语法写 效果都是一样的 就是蠢了一点

**Comment by PeachScript** [comment]
API 功能验证完毕，官网已新增使用文档：https://d.umijs.org/guide/auto-api-table

实验阶段还有不少限制，后续版本会继续优化

**Comment by superAo005** [comment]
<API id="Foo"></API> 这个id必须带吗

**Comment by PeachScript** [comment]
@superAo005 目前必须带，下个版本可以和 dumi 1 一样支持推导出的 atomId
