### ISSUE TITLE
bug: Global 配置了 antd5.x的主题，未生效

### ISSUE THREAD

**Issue by DerrickTel** [umijs/dumi#1322]
### Versions

- dumi: 2.0.0-rc.0
- node: 14.17.3
- npm: 8.19.2
- OS: MacOS 12.3.1
- Browser: Chrome 106.0.5249.119

### Steps to reproduce
`npm start`
### What is Expected?
主题色全局修改
### What is actually happening?
主题色未修改

复现仓库：
https://github.com/DerrickTel/dumi-antd-theme-global

**Comment by PeachScript** [comment]
放在 `.dumi/theme/layouts/GlobalLayout`，参考文档：https://d.umijs.org/theme
