### ISSUE TITLE
自定义页面Tab怎么配置第一个tab的文字 

### ISSUE THREAD

**Issue by eternallycyf** [umijs/dumi#1323]
<img width="632" alt="截屏2022-11-25 09 50 44" src="https://user-images.githubusercontent.com/63464198/203884522-07947bff-e1b8-4882-a915-5f8a35f74584.png">
<img width="684" alt="截屏2022-11-25 09 51 14" src="https://user-images.githubusercontent.com/63464198/203884526-a0064f5d-e898-40cf-a169-e39745aea813.png">
<img width="372" alt="截屏2022-11-25 09 52 46" src="https://user-images.githubusercontent.com/63464198/203884587-2fd702af-cc2a-4e27-a2d0-5cd96b950862.png">

**Comment by PeachScript** [comment]
创建 `.dumi/theme/locales/zh-CN.json` 覆盖默认的文案 key：https://d.umijs.org/theme#%E6%96%87%E6%A1%88%E5%8A%A0%E8%BD%BD
