### ISSUE TITLE
bug:  创建 dumi 完后，启动报错

### ISSUE THREAD

**Issue by Zhou-Bill** [umijs/dumi#1328]
```tsx
node 版本： v16.14.0
```

![image](https://user-images.githubusercontent.com/13554001/204120357-95346a58-e57e-4d2f-835b-e513da04d447.png)

尝试换版本也不行，貌似只在mac下复现， windows 没有问题。。。

**关闭mfsu, 编译成功**

**新建时使用yarn 失败， 用pnpm 正常**

**Comment by PeachScript** [comment]
是 bug，下个版本修复

**Comment by PeachScript** [comment]
v2.0.7 已修复
