### ISSUE TITLE
bug: htmlSuffix build failed

### ISSUE THREAD

**Issue by FengXianGuo** [umijs/dumi#133]
### Versions

- dumi:1.0.13
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
npm run docs:build
### What is actually happening?
![image](https://user-images.githubusercontent.com/19646853/77848521-f042ec80-71f7-11ea-918b-962d7d378945.png)

**Comment by PeachScript** [comment]
v1.0.19 已修复
