### ISSUE TITLE
feat: Header hash anchor style

### ISSUE THREAD

**Issue by afc163** [umijs/dumi#1330]
标题旁边的 # 和 🔗 。

<img width="434" alt="图片" src="https://user-images.githubusercontent.com/507615/204424507-b3447f9f-6993-481f-b674-478fca7ff38a.png">

<img width="342" alt="图片" src="https://user-images.githubusercontent.com/507615/204424582-1c873ab0-1075-45e0-9706-f819373bcfce.png">

**Comment by PeachScript** [comment]
anchor 的 DOM 是存在的但结构和 Bisheng 有差异，需要在 antd 的 theme 里调整样式把它展示出来 cc @zombieJ @MadCcc
![图片](https://user-images.githubusercontent.com/5035925/204428661-59961b3a-473d-4e3c-86c9-ac0921c9ba03.png)

**Comment by PeachScript** [comment]
ref: https://github.com/ant-design/ant-design/pull/39388
