### ISSUE TITLE
bug: 文章目录文本高度不足，显示不全。

### ISSUE THREAD

**Issue by Aureate-Sunshine** [umijs/dumi#1333]
### Versions

- dumi:2.0.5
- node:16.18.1
- npm:8.19.2
- OS: Widnows 10
- Browser: Edge 107

### Steps to reproduce
1.编写文章名称，使 active header 包含google

### What is Expected?
正常显示

### What is actually happening?
默认主题，文本高度不足，g字母显示不全。
Default theme, insufficient text height. Can't fully dispaly "g".

![image](https://user-images.githubusercontent.com/8013016/204453757-6f8f449b-5ac5-492b-b508-280d7a42df9f.png)

**Comment by PeachScript** [comment]
升级到最新版试下，应该 #1326 修复了

**Comment by Aureate-Sunshine** [comment]
上周发现的时候还没有发布新版本。现在已经修复了，thx。
