### ISSUE TITLE
使用npm的方式引入demo会报错是什么原因

### ISSUE THREAD

**Issue by 18281033262** [umijs/dumi#1335]
![Uploading image.png…]()

**Comment by PeachScript** [comment]
请提供最小可复现仓库

**Comment by 18281033262** [comment]
https://gitee.com/wang-lei19981020/wl-dumi.git

**Comment by 18281033262** [comment]
帮忙看看呢？

**Comment by PeachScript** [comment]
> https://gitee.com/wang-lei19981020/wl-dumi.git

链接 403

**Comment by 18281033262** [comment]
现在可以访问了，刚刚忘记开权限了

**Comment by PeachScript** [comment]
NPM 包没有导出，所以引入会报错，确保：
1. `src/index.ts` 存在且有导出对应组件
2. `package.json` 里的 `main`/`module` 字段正确声明
