### ISSUE TITLE
dumi2.0 nav配置如何配置多语言？

### ISSUE THREAD

**Issue by HandsomeFishYin** [umijs/dumi#1338]
### Question
![image](https://user-images.githubusercontent.com/15686508/204508905-b031191e-4cb1-4654-9845-6f2a62546a84.png)
如何配置多语言？

**Comment by PeachScript** [comment]
遗漏功能，后续版本提供

**Comment by PeachScript** [comment]
v2.0.11 已支持：https://d.umijs.org/theme/default#nav

**Comment by Go7hic** [comment]
> v2.0.11 已支持：https://d.umijs.org/theme/default#nav

你这改出一个 bug 来了，一更新发现报错了。提了新的 pr
