### ISSUE TITLE
dumi2.x demo中引用多个code标签渲染问题

### ISSUE THREAD

**Issue by xiazhiqiang** [umijs/dumi#1340]
在demo中，引入多个code标签，本地启动渲染全部为最后一个code标签对应的jsx文件内容了。
最简单的工程复现：https://github.com/xiazhiqiang/dumi-demo/blob/main/docs/index.md

**Comment by PeachScript** [comment]
v2.0.9 试下看

**Comment by xiazhiqiang** [comment]
> 

可以了，thanks~
