### ISSUE TITLE
bug: dumi官网全文检索代码内容，无法跳转到代码位置

### ISSUE THREAD

**Issue by jx2011** [umijs/dumi#1342]
### Versions

- dumi: 2.0.9
- node: 16.15.0
- npm: 8.5.5
- OS: windows 10
- Browser: chrome 107.0.5304.107

### Steps to reproduce
1、访问dumi官网  
2、全文检索 ‘loading’ 关键字  
3、点击检索结果  
![image](https://user-images.githubusercontent.com/8459338/204989681-d127363f-4616-48c6-980d-097d8ae42c7c.png)

### What is Expected?
希望代码检索能正常跳转到代码位置  
![image](https://user-images.githubusercontent.com/8459338/204990506-ac2fce67-0cb0-4fdf-b0ec-f8b738a305d1.png)

### What is actually happening?
无法正确跳转到API文档的代码位置，只能跳转到API文档位置。

**Comment by PeachScript** [comment]
v2.0.12 已修复
