### ISSUE TITLE
bug: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by hzyhbk** [umijs/dumi#1348]
### Versions

- dumi: 2.0.10
- node: 16.18.1
- npm: 9.1.1
- OS: macOS 13.0.1 (22A400)
- Browser: Microsoft Edge 版本 107.0.1418.62 (正式版本) (x86_64)

### Steps to reproduce
1. 拉取仓库 https://github.com/hzyhbk/dumi2-hooks-bug
2. 安装依赖
3. 执行  npm start

### What is Expected?
页面正常打开

### What is actually happening?
 `src/Foo/index.md` 下多加了一句 hooks，页面就报错了。关闭 mfsu 即可正常打开。

![image](https://user-images.githubusercontent.com/42671099/205240422-2a116b92-accc-4782-a8b3-72af2b622bd0.png)

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/42671099/205240144-9830afe7-fe38-45aa-94a4-522d1b22a346.png">

**Comment by Go7hic** [comment]
最快的解决办法是 把这个演示代码放到 demo 目录里面，不要直接在 index.md 里面写

**Comment by ifreeWorld** [comment]
新版本啥时候发呢

**Comment by PeachScript** [comment]
今天会发

**Comment by PeachScript** [comment]
v2.0.13 已修复

**Comment by iyanming** [comment]
还是不行啊  dumi@2.1.3

**Comment by tpc-ht** [comment]
解决了吗，还是dumi@2.1.1 和 dumi@2.0.13 都报错了 Cannot read properties of null (reading 'useState')

**Comment by hacker0limbo** [comment]
同样出现这个问题, 不过我是在打包后发到 npm 后报这个错误, 同时本地使用 npm link 和 npm pack 均也出现这个错误. 

我自己的 father 的配置为:

```ts
import { defineConfig } from 'father';

export default defineConfig({
  // more father config: https://github.com/umijs/father/blob/master/docs/config.md
  esm: { output: 'dist/esm' },
  umd: { output: 'dist/umd', extractCSS: false },
  sourcemap: true,
});
```

package.json 配置为: 
```json
"main": "dist/umd/xxx.min.js",
"module": "dist/umd/xxx.min.js",
"types": "dist/esm/index.d.ts",
"files": [
  "dist"
],
```

编写组件源码的时候声明 useState 的时候会报这个错

新手不是很确定是不是配置出现问题还是我使用方式不太正确

**Comment by MutelyMilo** [comment]
> 

请问问题解决了吗？我在编辑react组件库的时候link后出现同样问题，版本2.2.0

**Comment by MutelyMilo** [comment]
> > 
> 
> 请问问题解决了吗？我在编辑react组件库的时候link后出现同样问题，版本2.2.0

@PeachScript 同样问题，lib模式下导出的组件通过link方式引入会报错 Cannot read properties of null (reading 'useState')

**Comment by tpc-ht** [comment]
> > > 
> > 
> > 
> > 请问问题解决了吗？我在编辑react组件库的时候link后出现同样问题，版本2.2.0
> 
> @PeachScript 同样问题，lib模式下导出的组件通过link方式引入会报错 Cannot read properties of null (reading 'useState')
具体不知道什么原因，但创建一个新的项目就不报错了
