### ISSUE TITLE
dumi2.0如何在build时将.less文件转成css，并压缩

### ISSUE THREAD

**Issue by chenmeiling2016** [umijs/dumi#1350]
### 预期效果
![image](https://user-images.githubusercontent.com/51880353/205578239-7b21c004-6f4f-4247-939e-6acda624f9bc.png)

### .fatherrc.ts

import { defineConfig } from 'father';

export default defineConfig({
  esm: { output: 'es' },
});

**Comment by PeachScript** [comment]
打包相关问题参考 father 文档：https://github.com/umijs/father/blob/master/docs/guide/umd.md#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9
