### ISSUE TITLE
bug:  生成的 package.json的types字段错误

### ISSUE THREAD

**Issue by ldydxmj** [umijs/dumi#1351]
### Versions

- dumi:2.0.0-rc.0
- node:14.18.0
- npm:
- OS:windows
- Browser:chrome

### Steps to reproduce
执行 npx create-dumi 生成的package.json的types字段值为 dist/type.d.ts  而生成的文件则没有该文件。正确的文件为index.d.ts。

### What is Expected?
希望修改生成的package.json的types字段为index.d.ts
### What is actually happening?
在vscode中不能提示导出的组件、变量等

**Comment by PeachScript** [comment]
create-dumi@2.0.3 已修复
