### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by wangyangexpo** [umijs/dumi#1353]
### Versions

- dumi: 2.0.11
- node: 16
- npm: 7
- OS: macOS
- Browser: chrome

### Steps to reproduce

构建产物报错，启动白屏，切回2.0.9版本正常。
![image](https://user-images.githubusercontent.com/19430028/205824674-3d07f61f-115a-471b-8186-2337b6604cf0.png)

### What is Expected?
页面正常打开。

### What is actually happening?
白屏

**Comment by PeachScript** [comment]
> Steps to reproduce

是指其他人按照提供的步骤能复现一样的问题，截图没法排查

**Comment by wangyangexpo** [comment]
复现步骤：
1. 使用 npx create-dumi 初始化项目；
2. 修改.dumirc.ts配置文件
```js
import { defineConfig } from 'dumi';

export default defineConfig({
  themeConfig: {
    name: 'dumi',
    nav: [
      { title: '介绍', link: '/guide' },
      { title: '插件', link: '/preset/pc' },
      { title: '学习', link: '/study' },
    ],
  },
});
```

**Comment by wangyangexpo** [comment]
使用配置化的nav菜单就会有问题，只要一个配置一个就行。

**Comment by PeachScript** [comment]
v2.0.12 已修复
