### ISSUE TITLE
主题自定义的时候会有`模块“"dumi"”没有导出的成员“Link”`

### ISSUE THREAD

**Issue by mortalYoung** [umijs/dumi#1356]
### Question

用脚手架创建的 React Library 项目，在 `.dumi/themes/slots/NavBar.tsx` 文件中想要用到 `Link` 组件，会提示上述错误
`模块“"dumi"”没有导出的成员“Link”`

### Sample Code

![image](https://user-images.githubusercontent.com/18719701/205916968-47bf4aca-d53e-40a0-a980-b46c021396bd.png)

**Comment by PeachScript** [comment]
外面的 tsconfig.json 里加上 include？

**Comment by mortalYoung** [comment]
> 外面的 tsconfig.json 里加上 include？

也阔以哦～ 是不是要在主题的文档里说一下？

**Comment by PeachScript** [comment]
@mortalYoung 可以的，本地主题应该都需要用到这个，你来加吗 👀

**Comment by Codennnn** [comment]
这样子配置确实能够正确解析了：

```json
{
  "include": ["**/*", ".dumi/**/*"],
  "exclude": ["node_modules", "docs-dist", "typings", ".dumi/tmp*/**/*"]
}
```

或许应该在 `create-dumi` 的模板项目中添加他们，我可以帮忙添加，但我不知道 `create-dumi` 的项目地址在哪里。

**Comment by Codennnn** [comment]
我编辑了文档，加入了这些配置。
