### ISSUE TITLE
feat: 是否支持使用 Tailwind CSS 编写 dumi 主题样式？

### ISSUE THREAD

**Issue by Codennnn** [umijs/dumi#1358]
目前在 `.dumirc.ts` 中无法配置 `tailwindcss`，会报告：Invalid config keys: tailwindcss

如果支持的话，能否提供一个简单的示例？

**Comment by mortalYoung** [comment]
纯好奇，组件库如果引入 tailwindcss 的话，会不会不太好

**Comment by Codennnn** [comment]
我想的是在编辑本地自定义主题的时候使用 tailwind。

**Comment by Codennnn** [comment]
可以讲讲如何挂载 `@umijs/plugins/dist/tailwindcss` 吗？在 umi 项目中，我只需要安装 `@umijs/plugins`，并且在 `.umirc.ts` 中加入 `tailwindcss : {}` 即可使用，但在 dumi 中，这样的操作会报：Invalid config keys: tailwindcss

**Comment by Codennnn** [comment]
这里有一个尝试使用 `tailwindcss ` 最小示例库：

https://github.com/Codennnn/create-dumi

如果哪里的配置有误，请帮忙指出，感谢！

**Comment by PeachScript** [comment]
> 可以讲讲如何挂载 `@umijs/plugins/dist/tailwindcss` 吗？

用 plugins 配置项：https://d.umijs.org/config#plugins

**Comment by Codennnn** [comment]
可以正常使用了！对于想知道具体实现的人，可以参考以下步骤：

1. 安装：`yarn add -D @umijs/plugins tailwindcss`

2. 在 `.dumirc.ts` 中添加插件：`plugins: ['@umijs/plugins/dist/tailwindcss']`

3. 启用插件：同样在 `.dumirc.ts` 加入 `tailwindcss: {}`

**Comment by Codennnn** [comment]
首先确保已创建 `tailwind.config.js` 和 `tailwind.css`，我的使用例子如下图中的标注：

![image](https://user-images.githubusercontent.com/47730755/207474153-d7674e1f-603a-49dc-a774-2ce961cc1534.png)
