### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by shiduobin** [umijs/dumi#1360]
### Versions

- dumi: 2.0.12
- node: 14.16.1
- npm: 6.14.12
- OS: macOS
- Browser: Chorme

### Steps to reproduce

**.dumirc.ts**  文件 的 themeConfig.nav 添加如下配置

```ts
themeConfig: {
    name: 'dumi-bug-demo',
    nav: [
      null,
      { title: '指南', link: '/guide' },
    ],
}
```

### What is Expected?

* 想对菜单做增量配置，一部分在 nav 中配置，一部分按照保留约定式生成导航

按照之前的文档，添加 null 菜单配置可做增量配置
![image](https://user-images.githubusercontent.com/26728144/206174390-75278fc2-4ebc-4b0e-8906-1d7bed47975c.png)

### What is actually happening?

* 浏览器控制台报如下错误

![image](https://user-images.githubusercontent.com/26728144/206175387-3d9ea256-cccb-463a-a952-33dba06584b3.png)

**Comment by PeachScript** [comment]
dumi 2 不支持旧的配法了，只能全量配置，用法以新的文档为准

**Comment by shiduobin** [comment]
这个后续能支持吗，感觉这个配置还是有必要的

**Comment by PeachScript** [comment]
应该不会以配置项的形式支持了，这种配法比较诡异；后续可能会提供一个 NavbarExtra 的 slot，供开发者以 React 组件的形式追加导航内容

**Comment by shiduobin** [comment]
slot 的方式有预期在什么时候支持呢？期待

**Comment by PeachScript** [comment]
预计这周内

**Comment by PeachScript** [comment]
@shiduobin v2.0.14 已支持 `NavbarEtra` slot，可增量配置导航，https://github.com/umijs/dumi/releases/tag/v2.0.14

**Comment by shiduobin** [comment]
想问下，这个有使用示例吗？看了下源码是添加了一个<></>标签？

**Comment by PeachScript** [comment]
源码只是个 slot 坑位，新建 `.dumi/theme/slots/NavbarExtra.tsx`，返回一个 React 组件渲染 li a 即可
