### ISSUE TITLE
如何优雅修改 代码块 的主题

### ISSUE THREAD

**Issue by Kshao123** [umijs/dumi#1362]
### Question
在 .dumi 中好像也不能覆盖 theme-default/builtins/SourceCode，可不可以提供 Api 覆盖 SourceCode 的 Highlight 的 theme
<img width="1344" alt="截屏2022-12-06 14 34 41" src="https://user-images.githubusercontent.com/41893166/206342461-59be3d78-3544-4254-8302-9f71fc311fdc.png">

其他方案的话，在 .dumi/global.ts 中引入了对应的 css，需要写 css 覆盖 dumi 的 .dumi-default-source-code 的样式，背景色需要去主题包里 copy 出来 不是很直观~

<img width="1335" alt="截屏2022-12-08 10 44 00" src="https://user-images.githubusercontent.com/41893166/206343356-ab701af7-7792-4325-8a85-d1b497727652.png">

**Comment by innocces** [comment]
覆写 [`slots/PreviewerActions`](https://github.com/umijs/dumi/blob/master/src/client/theme-default/slots/PreviewerActions/index.tsx#L136)

**Comment by PeachScript** [comment]
> 在 .dumi 中好像也不能覆盖 theme-default/builtins/SourceCode

创建 `.dumi/theme/builtins/SourceCode.tsx` 即可覆盖内置的 `SourceCode`，关于加载逻辑可以阅读主题文档：https://d.umijs.org/theme#%E7%BB%84%E4%BB%B6%E5%8A%A0%E8%BD%BD

但如果只是希望替换 prism 的 css 文件引入，建议使用 alias 配置把 dumi 默认引入的 prism 主题指向你需要的主题文件，比如：

```ts
// .dumirc.ts
export default {
  alias: {
    'prism-themes/themes/prism-one-light.css': require.resolve('xxx.css'),
  }
}
```
