### ISSUE TITLE
编写组件的时候用到了svgr,但是打包时svgr并没有被编译，导致发包的时候报错

### ISSUE THREAD

**Issue by zx-zx22** [umijs/dumi#1363]
### Sample Code
![image](https://user-images.githubusercontent.com/62274094/206346667-c53f8633-25a3-48aa-85c5-324e28fc6b20.png)
![image](https://user-images.githubusercontent.com/62274094/206346694-ff52bfa4-c99a-4bf5-b4a7-8f2ee18be231.png)

**Comment by PeachScript** [comment]
这是 father doctor 命令报错，升级 father 到最新版即可

另外 bundless 模式下非 js 文件（包括 svg）都不会被编译，要使用 svgr 需要确保使用组件库的项目能编译 svgr
