### ISSUE TITLE
请问发布的包如何排除package.json里面的一些依赖呢，比如antd和react?

### ISSUE THREAD

**Issue by zx-zx22** [umijs/dumi#1364]
没有找到相关的配置

官网文档贴出来的交流群已经满了，可以再开一个吗？

**Comment by PeachScript** [comment]
交流群二维码已更新，感谢反馈

dumi 不负责源码打包，打包相关问题可参考 father 的文档：https://github.com/umijs/father/blob/master/docs/config.md#externals

**Comment by zx-zx22** [comment]
但是这个属性externals是UMD下面的配置项，我打包的是es

**Comment by PeachScript** [comment]
bundless 模式不会打包依赖：https://github.com/umijs/father/blob/master/docs/guide/build-mode.md
