### ISSUE TITLE
bug: lessLoader 添加 math: 'always' 配置后报错

### ISSUE THREAD

**Issue by ifreeWorld** [umijs/dumi#1365]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
![image](https://user-images.githubusercontent.com/31157002/206376520-b45723da-ffce-4bec-9fa9-aaa5fa22db6c.png)
![image](https://user-images.githubusercontent.com/31157002/206376631-c904df95-30c5-4bab-a4bb-3299472cec41.png)

### What is Expected?
不报错
### What is actually happening?
lessLoader 添加 math: 'always' 配置后报错

**Comment by PeachScript** [comment]
stylelint 自动处理成 morden 写法了：https://stylelint.io/user-guide/rules/color-function-notation/

下个版本改回来

**Comment by ifreeWorld** [comment]
> stylelint 自动处理成 morden 写法了：https://stylelint.io/user-guide/rules/color-function-notation/
> 
> 下个版本改回来

🐂🍺 👬🏻

**Comment by PeachScript** [comment]
v2.0.13 可以试下
