### ISSUE TITLE
bug: 添加新组件后无法运行

### ISSUE THREAD

**Issue by alindas** [umijs/dumi#1366]
### Versions

- dumi: 2.0.7
- node: 14.16.0

### What is actually happening?

增加新组件时，重新运行项目出现报错，报错原因位于 `.dumi`  文件夹下。

![image](https://user-images.githubusercontent.com/50586970/206407406-762e0c85-e24a-4b7f-898f-daa5f3f37d38.png)

当我删掉新组件的两个 `md` 文件，项目又能正常运行了。
![image](https://user-images.githubusercontent.com/50586970/206407702-ad87a6e5-5a52-466c-8cc4-0299d1a20777.png)

对于 dumi 编译出现的问题无法进行处理，所以只能在此求助。

**Comment by PeachScript** [comment]
检查报错的 config-provider 有哪些文件引用到了，推测和你添加的这两个 md 里有代码间接引用这个模块，且路径不正确

**Comment by alindas** [comment]
> 检查报错的 config-provider 有哪些文件引用到了，推测和你添加的这两个 md 里有代码间接引用这个模块，且路径不正确

经测试，当按照官网的写法，demo 中从 npm 包名引用组件时就会报上面的错。但是按照其说法，新增组件其映射是自动生成的，作为开发者无法解决该 bug
![image](https://user-images.githubusercontent.com/50586970/206651688-0ae92474-8165-4bb6-aabc-0840ef7e7ee7.png)

![image](https://user-images.githubusercontent.com/50586970/206651561-1373c566-09ff-441d-9b6e-ede4329170a4.png)

![image](https://user-images.githubusercontent.com/50586970/206651612-9445f3dd-ed6a-45ab-886b-8c51af5371e1.png)

**Comment by PeachScript** [comment]
用脚手架复现不了，有空提供下最小可复现仓库
