### ISSUE TITLE
bug: 非根目录部署文档路径问题

### ISSUE THREAD

**Issue by 0xYootou** [umijs/dumi#1368]
### Versions

- dumi: 2.0.13
- node: 16
- npm: 8
- OS: mac
- Browser: chrome

### Steps to reproduce

因为需要在 github pages 中部署，但是因为 pages 部署后的域名不是根目录，所以需要是相对路径。

在 .dumirc.ts 中加入：

```
publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
runtimePublicPath: {},
```

使用官方 repo 即可重现，加入以上配置后，yarn docs:build ，然后 http-server . 托管一下项目目录，访问 http://127.0.0.1:8081/docs-dist 即可发现，资源路径是错的。

后来我改成

```
publicPath: process.env.NODE_ENV === 'production' ? '/docs-dist/' : '/',
runtimePublicPath: {},
```
静态资源的路径对了，但是异步加载的资源路径依然是根目录

关于这个 runtimePublicPath 的用法，很困惑，官方文档没说清楚，和 umi 里的用法也不一致，请帮忙解惑。

### What is Expected?

相对路径也可以正常运行，异步加载的资源也可以正常运行

### What is actually happening?

都不正常。使用官方 repo 即可重现，加入以上配置后即可重现

**Comment by miracles1919** [comment]
试了下，按照[部署文档](https://d.umijs.org/guide/faq#%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3)来是可以的

仓库：https://github.com/miracles1919/dumi-exapmles
pages：https://miracles1919.github.io/dumi-exapmles

```
base: '/dumi-exapmles/',
publicPath: '/dumi-exapmles/',
```

**Comment by Snow233** [comment]
> 
你这个项目本地编译完打开会报错嘛，我下载了你的项目编译完本地打不开

**Comment by Snow233** [comment]
> 试了下，按照[部署文档](https://d.umijs.org/guide/faq#%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3)来是可以的
> 
> 仓库：https://github.com/miracles1919/dumi-exapmles pages：https://miracles1919.github.io/dumi-exapmles
> 
> ```
> base: '/dumi-exapmles/',
> publicPath: '/dumi-exapmles/',
> ```

https://github.com/Snow233/dumi-demo我这个和你的项目一样，但是https://snow233.github.io/dumi-demo部署完有个异步的文件路径不对

**Comment by Snow233** [comment]
> ### Versions
> * dumi: 2.0.13
> * node: 16
> * npm: 8
> * OS: mac
> * Browser: chrome
> 
> ### Steps to reproduce
> 因为需要在 github pages 中部署，但是因为 pages 部署后的域名不是根目录，所以需要是相对路径。
> 
> 在 .dumirc.ts 中加入：
> 
> ```
> publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
> runtimePublicPath: {},
> ```
> 
> 使用官方 repo 即可重现，加入以上配置后，yarn docs:build ，然后 http-server . 托管一下项目目录，访问 http://127.0.0.1:8081/docs-dist 即可发现，资源路径是错的。
> 
> 后来我改成
> 
> ```
> publicPath: process.env.NODE_ENV === 'production' ? '/docs-dist/' : '/',
> runtimePublicPath: {},
> ```
> 
> 静态资源的路径对了，但是异步加载的资源路径依然是根目录
> 
> 关于这个 runtimePublicPath 的用法，很困惑，官方文档没说清楚，和 umi 里的用法也不一致，请帮忙解惑。
> 
> ### What is Expected?
> 相对路径也可以正常运行，异步加载的资源也可以正常运行
> 
> ### What is actually happening?
> 都不正常。使用官方 repo 即可重现，加入以上配置后即可重现

import { defineConfig } from 'dumi';
export default defineConfig({
  mfsu: false,
  base: '/dumi-demo/',
  publicPath: '/dumi-demo/',
});这样的配置没问题，mfsu: false,得关掉

**Comment by PeachScript** [comment]
> mfsu: false,得关掉

部署和 mfsu 应该没关系，mfsu 是仅 dev 启用的

**Comment by samphay** [comment]
遇到同样的问题，没有得到解决方案，不明白为什么把bug关了？

**Comment by songleilei** [comment]
+ 1 为什么关掉了，楼主的问题并没有解决啊

publicPath: process.env.NODE_ENV === 'production' ? './' : '/',
runtimePublicPath: {},

异步加载资源的路径是错误的

**Comment by dqm07** [comment]
umi4的时候，需要在html手动配置window.publicPath，然后umirc中配置runtimePublicPath: {}即可
