### ISSUE TITLE
bug: rc-tabs 版本冲突问题

### ISSUE THREAD

**Issue by ifreeWorld** [umijs/dumi#1370]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
使用了 antd3，antd3 依赖 rc-tabs@~9.6.0，dumi依赖 rc-tabs@12.1.0-alpha.1，于是有冲突，因为 12.1.0-alpha.1 中找不到 rc-tabs/es/TabContent，~9.6.0 版本中是有的，然后就报错了

![image](https://user-images.githubusercontent.com/31157002/206997830-2340c7ca-e355-4c1e-8b60-a7e48d74ef1a.png)
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/31157002/206998029-05d0fceb-1e1e-4514-805b-46675416dd80.png">
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/31157002/206998099-3947098e-eeeb-4b88-a111-d8f38c85167f.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/31157002/206998793-88172e03-4635-4ac7-83dc-a18772d1d0a5.png">

**Comment by ifreeWorld** [comment]
关闭 mfsu 就好了，请问还有其他的方式解决吗？
<img width="231" alt="image" src="https://user-images.githubusercontent.com/31157002/206998978-c5ff9821-3af5-4d74-876f-e0d7d2250e2c.png">

**Comment by PeachScript** [comment]
先关 mfsu 解决吧，1.x 不太会迭代了，可以考虑升级到 2.0：https://d.umijs.org/guide/upgrading

**Comment by ifreeWorld** [comment]
> 先关 mfsu 解决吧，1.x 不太会迭代了，可以考虑升级到 2.0：https://d.umijs.org/guide/upgrading

我使用的就是dumi2，具体版本2.0.13

**Comment by ifreeWorld** [comment]
2.0.13 也一样依赖了 rc-tabs 呢。
 https://github.com/umijs/dumi/blob/master/package.json#L108

**Comment by PeachScript** [comment]
懂了，那还是只能关 mfsu 了…antd 3 有点久远，rc-tabs 已经有了 Breaking Change，dumi 也不能自己重写一遍 rc-tabs，维护成本太高

**Comment by PeachScript** [comment]
后续 MFSU 方案迭代可能可以规避该问题，现阶段 dumi 必须 alias rc-tabs 为 dumi 依赖的版本才能确保 MFSU 正常工作，带来的负面影响就是 rc-tabs 版本分裂的场景下会工作不正常
