### ISSUE TITLE
2.0.13开启mfsu之后就报错了

### ISSUE THREAD

**Issue by qc-z** [umijs/dumi#1371]
![image](https://user-images.githubusercontent.com/22362903/207249382-93e24c96-defb-4d41-9c3c-09c08b2106a3.png)

**Comment by PeachScript** [comment]
Windows 目前还不支持启用 MFSU，有兼容性问题，后来做过一些调整但手边没有 Windows 设备不便测试，如果有兴趣可以帮忙验证下

开启方法：不能手动开启 `mfsu` 配置项，这会覆盖 dumi 内部对 MFSU 配置的设置，需要改 node_modules 下的这部分逻辑：https://github.com/umijs/dumi/blob/master/src/features/derivative.ts#L65

`rm -rf node_modules/.cache` 后启动如果没问题就验证通过，dumi 下个版本把上面的判断去掉；如果有问题还得排查下原因

**Comment by qc-z** [comment]
> Windows 目前还不支持启用 MFSU，有兼容性问题，后来做过一些调整但手边没有 Windows 设备不便测试，如果有兴趣可以帮忙验证下
> 
> 开启方法：不能手动开启 `mfsu` 配置项，这会覆盖 dumi 内部对 MFSU 配置的设置，需要改 node_modules 下的这部分逻辑：https://github.com/umijs/dumi/blob/master/src/features/derivative.ts#L65
> 
> `rm -rf node_modules/.cache` 后启动如果没问题就验证通过，dumi 下个版本把上面的判断去掉；如果有问题还得排查下原因

安装以上方法验证，依然报一样的错误
