### ISSUE TITLE
bug: themeConfig.nav 如果配置了带 children 属性的子节点会报错

### ISSUE THREAD

**Issue by baxtergu** [umijs/dumi#1373]
### Versions

- dumi: 2.0.13
- node: 16.18.2
- npm: 8.19.2
- OS: macos
- Browser: chrome

### Steps to reproduce

通过 npx create-dumi 创建的项目，只修改 nav 部分配置。只要有任意配置包含 children 属性 即报错

- reproduce
https://stackblitz.com/edit/node-3zbwyu?file=.dumirc.ts

### What is Expected?

不会报错，正常展示下拉

### What is actually happening?

报错

**Comment by PeachScript** [comment]
二级导航还没做，后续版本会支持

**Comment by PeachScript** [comment]
2.2.0+ 已支持二级导航，issue 关闭
