### ISSUE TITLE
bug: 初始化项目，生成文档时，产生的文件有部分放到以本地路径命名的目录里

### ISSUE THREAD

**Issue by ZhiRongYuan** [umijs/dumi#1377]
Versions
dumi: 2.0.14
node: 16.13.0
yarn: 1.22.17
OS: window
Browser: chrome

Steps to reproduce
通过 npx create-dumi 创建的React Library项目

npm run docs:build 生成站点文档

What is Expected?
部署后能正常访问

What is actually happening?
站点无法正常访问，资源引用不到，部分文件生成的目录有问题
![image](https://user-images.githubusercontent.com/19885237/208032445-925663f6-1a9c-4d5c-8f43-7ea8297ad457.png)

**Comment by PeachScript** [comment]
请按 issue 模板提供完整复现信息，只有截图没法看问题

**Comment by ZhiRongYuan** [comment]
> 请按 issue 模板提供完整复现信息，只有截图没法看问题

已更新issue

**Comment by ZhiRongYuan** [comment]
Mac是正常的  window有问题

**Comment by PeachScript** [comment]
v2.1.5 已修复
