### ISSUE TITLE
bug: 分组展示

### ISSUE THREAD

**Issue by shaodahong** [umijs/dumi#138]
### Versions

- dumi: 1.0.13
- node: v10.19.0
- npm: 6.13.4
- OS: osx 10.15.4
- Browser: Chrome  80.0.3987.149

### Steps to reproduce

```bash
.
├── README.md
├── components
│   ├── async-button
│   ├── form
│   ├── hooks
│   ├── index.tsx
│   ├── modal-form
│   ├── modal-table
│   ├── table
│   └── utils
├── docs
│   └── FAQ.md
├── now.json
├── package.json
├── site
│   ├── index.html
│   ├── umi.css
│   └── umi.js
├── tsconfig.json
└── yarn.lock
```

组件目录 `compoents`，每个组件 `index.zh-CN.md` 包含

```yml
---
group:
  title: Components
---
```

但是展示出来每个都是一个独立的

仓库地址：https://github.com/shaodahong/ant-design-admin
演示地址：https://ant-design-admin.now.sh/

### What is Expected?

都包含在 `Components` 分组下

### What is actually happening?

每个都是一个独立的 `Components` 分组

**Comment by shaodahong** [comment]
配置文件中已经添加了

```ts
  resolve: {
    includes: ['components'],
  },
```

所以访问的都是一级 path，如果加上 `group.path` 为 `components`，那么是访问不到页面的

**Comment by PeachScript** [comment]
`includes` 的目录都会作为根目录再往下识别，这个场景把 `components` 放进 `src` 目录下即可；
如果不希望改动目录结构，那么设置所有 `.md` 的 `group.path` 为 `/components` 即可，可以参考 umijs/hooks 的目录结构：https://github.com/umijs/hooks/blob/master/packages/hooks/src/useCounter/index.en-US.md
