### ISSUE TITLE
bug: 本地 LOGO 不生效 

### ISSUE THREAD

**Issue by BesideWithYou** [umijs/dumi#1380]
### Versions

- dumi: 2.0.2
- node: 16.13.0
- npm: 8.6.0
- OS: Windows
- Browser: Chrome

**Comment by BesideWithYou** [comment]
配置信息如图所示，页面上没有图片渲染

![image](https://user-images.githubusercontent.com/63894579/208280769-7e4a047e-a6c3-436d-a0c7-5b6907bbf437.png)

![image](https://user-images.githubusercontent.com/63894579/208280775-1d7fb8bb-8ca9-4065-837a-474ade1ee351.png)

**Comment by PeachScript** [comment]
我试了下是 OK 的，浏览器 Network 里看下图片是否正常加载了

**Comment by lby1024** [comment]
我也没生效,浏览器 Network 图片404

**Comment by maquannene** [comment]
> 我试了下是 OK 的，浏览器 Network 里看下图片是否正常加载了

这个如果不是在根路径部署，这种写法会有问题，有什么好办法解决吗？
