### ISSUE TITLE
dumi v2.0.16 自动API生成，显示“未找到 Foo 组件的属性定义”

### ISSUE THREAD

**Issue by candy4290** [umijs/dumi#1382]
### Question
dumi v2.0.16 自动API生成，显示“未找到 Foo 组件的属性定义”
![image](https://user-images.githubusercontent.com/19907991/208639162-84925fec-adfb-4df1-b5e5-d61a8ad2449c.png)

### Sample Code
![image](https://user-images.githubusercontent.com/19907991/208638475-2fc5722b-16ce-4539-a6ae-f6e1aade56ce.png)
![image](https://user-images.githubusercontent.com/19907991/208638530-333330bd-1534-43e3-81c8-cfbc06a8d04b.png)

**Comment by owen1190** [comment]
根据[新的文档](https://d.umijs.org/guide/auto-api-table#%E4%BD%BF%E7%94%A8%E6%96%B9%E5%BC%8F)，需要在Api属性配置id

**Comment by owen1190** [comment]
src/index.ts有导出Foo组件吗

**Comment by CaptainJon** [comment]
我也碰到这个问题了，怎么处理的

**Comment by PeachScript** [comment]
确保配置项已经打开，参考文档：https://d.umijs.org/guide/auto-api-table

**Comment by hanxzi** [comment]
`// src/index.ts
export { default as Foo } from './Foo'; 

// .dumirc.ts
apiParser: {},
  resolve: {
    entryFile: './src/index.ts',
  },
  
// src/Foo/index.tsx
import React, { type FC } from 'react';

export const Foo: FC<{ title: string }> = (props) => <h4>{props.title}</h4>;

export default Foo;
  `
  结果显示未找到 Foo 组件的属性定义，同样遇到这个问题
