### ISSUE TITLE
bug: monorepo packages tsx文件修改没有热更新

### ISSUE THREAD

**Issue by skyunBoss** [umijs/dumi#1384]
### Versions

- dumi:1.1.50
- node:14.20.0
- npm:6.14.17
- OS:mac
- Browser:chrome

### Steps to reproduce
https://github.com/skyunBoss/repo
### What is Expected?
正常热更新
### What is actually happening?
修改packages > driipt-table > src > index.tsx文件没有热更新

**Comment by PeachScript** [comment]
项目手动把包名指向子包目录，最终会依据 package.json 的声明指向产物，源码自始至终不参与编译，所以改动源码不会触发热更新：https://github.com/skyunBoss/repo/blob/main/.umirc.ts#L26

解法：要么把 `alias` 指向 `src/index.ts`；要么删掉自己配置的 `alias`，dumi v1 会自动 alias 子包到各自的 `src/index.ts`
