### ISSUE TITLE
bug: 渲染demo，如果demo在不同文件夹下相同名字（如/demo1/index.tsx, /demo2/index.tsx），则只渲染一个demo

### ISSUE THREAD

**Issue by JaylanChen** [umijs/dumi#1386]
### Versions

- dumi: v2.0.16
- node: v16.18.0
- npm: v8.19.2
- OS: Win 10
- Browser: Edge 108

### Steps to reproduce

![image](https://user-images.githubusercontent.com/7055008/209269332-4fab8bed-96a9-46f6-a396-87bb5f7b8098.png)

#### Demo 的文件名一样，则无法正常渲染 demo

<code src="./demos/demo2/index.tsx" description="demo2">demo2</code>

<code src="./demos/demo3/index.tsx" description="demo3">demo3</code>

#### demo2 代码
```
import { useEffect } from 'react';

export default () => {
  useEffect(() => {
    console.log('demo2');
  }, []);

  return <div>demo2</div>;
};
```
#### demo3 代码
```
import { useEffect } from 'react';

export default () => {
  useEffect(() => {
    console.log('demo3');
  }, []);

  return <div>demo3</div>;
};
```

### What is Expected?

能正常渲染不同的demo

### What is actually happening?

![image](https://user-images.githubusercontent.com/7055008/209269260-55ddfdc0-a3f9-4461-b886-43f87fb6ffbb.png)

没有渲染demo2，渲染了 2 个demo3,

[reproduce](https://github.com/JaylanChen/dumi-error)

**Comment by PeachScript** [comment]
本地试了下复现不了，提供下最小复现仓库？

**Comment by JaylanChen** [comment]
[bug 复现代码](https://github.com/JaylanChen/dumi-error)

dumi V2.0.18 也能复现

![image](https://user-images.githubusercontent.com/7055008/210029007-de5f380f-a80a-4ea4-88be-a2ae76e4965f.png)

**Comment by PeachScript** [comment]
应该是 win 下的兼容性问题，v2.1.0 已尝试修复，有空可以帮忙验证下

**Comment by JaylanChen** [comment]
> 应该是 win 下的兼容性问题，v2.1.0 已尝试修复，有空可以帮忙验证下

谢谢你，可以了。
