### ISSUE TITLE
bug: defineConfig typing downgraded, cause autocomplete missing in .dumirc.ts file

### ISSUE THREAD

**Issue by tinymins** [umijs/dumi#1387]
### Versions

- dumi: 2.0.2
- node: 16
- npm: 6
- OS: Ubuntu 22.04
- Browser: Chrome

### Steps to reproduce

1. init dumi-sample project by `npx create-dumi`
2. with

    ✔ Pick template type › React Library
    ✔ Pick NPM client › yarn

3. edit `.dumirc.ts` file

### What is Expected?

Expect configure fields typing autocomplete.

### What is actually happening?

No autocomplete.

![image](https://user-images.githubusercontent.com/1808990/209276557-b4780236-8bb4-420b-a423-7d9fef9c9b19.png)

After tracing source codes, the problem is here:

https://github.com/umijs/dumi/blob/6fc5257df6e2bc77e50f86b53a88da5ebb860c97/src/types.ts#L13

https://github.com/umijs/dumi/blob/6fc5257df6e2bc77e50f86b53a88da5ebb860c97/src/types.ts#L36-L37

Interface `IDumiConfig` extends `IUmiConfig` which is `Record<string, any>` actually, then `IDumiUserConfig` extends omitted `IUmiConfig`. <- problem is here

Omit `IUmiConfig` which extends `Record<string, any>` will actually result to `Record<string, any>`, that means the interface typing is downgraded.

So in my local environment, I modified codes to this:

```typescript
interface IDumiCustomConfig {
  resolve: {
    docDirs: (string | { type?: string; dir: string })[];
    /**
     * @deprecated use `resolve.atomDirs` instead
     */
    entityDirs?: { type: string; dir: string }[];
    atomDirs: { type: string; dir: string }[];
    codeBlockMode: 'active' | 'passive';
    entryFile?: string;
  };
  locales: ILocalesConfig;
  themeConfig: IThemeConfig;
  autoAlias?: boolean;
  /**
   * extra unified plugins
   */
  // eslint-disable-next-line @typescript-eslint/ban-types
  extraRemarkPlugins?: (string | Function | [string | Function, object])[];
  // eslint-disable-next-line @typescript-eslint/ban-types
  extraRehypePlugins?: (string | Function | [string | Function, object])[];
}
export type IDumiConfig = IDumiCustomConfig & IUmiConfig;

export interface IDumiUserConfig
  extends Partial<Omit<IDumiCustomConfig, 'resolve' | 'locales'>>, IUmiConfig {
  resolve?: Partial<IDumiCustomConfig['resolve']>;
  locales?: (
    | IDumiCustomConfig['locales'][0]
    | Omit<IDumiCustomConfig['locales'][0], 'base'>
  )[];
}
```

The autocomplete works well now!

![image](https://user-images.githubusercontent.com/1808990/209277925-77d9dd39-aa43-4371-bb11-6ef55eb4c0ab.png)

**Comment by tinymins** [comment]
Also, the problem can be from this:

https://github.com/umijs/umi/blob/6c2eb1d56a4b405d1bbf0a6d29998fb44d9e97ef/packages/core/src/service/service.ts#L57

Union with `Record<string, any>` will lost autocomplete, due to:

https://github.com/microsoft/TypeScript/issues/29729

So, change that line of code into this can also fix this problem:

```typescript
    config: Record<string & {}, any>;
```

![image](https://user-images.githubusercontent.com/1808990/209279998-c27eb057-d81a-45fb-a784-4ae874f09c17.png)

**Comment by tinymins** [comment]
I find that `defineConfig` is an empty function, so I guess the only reason why this function exists must be for `typescript` check and its autocomplete. And now, it's broken. 😂 

https://github.com/umijs/dumi/blob/master/src/index.ts#L12

**Comment by PeachScript** [comment]
Thanks for your detailed explanation, it's a bug, I will try the solution from PR later ❤️

**Comment by PeachScript** [comment]
v2.0.17 已修复

**Comment by tinymins** [comment]
![image](https://user-images.githubusercontent.com/1808990/209935965-ee4019aa-eb2b-4abd-9d8e-66f927a3cbec.png)
![image](https://user-images.githubusercontent.com/1808990/209936120-4ec72c27-ed58-4ed4-84a4-a02fc0c3006c.png)

我就是 2.0.17 呀

**Comment by PeachScript** [comment]
@tinymins 岔了，这是 defineConfig 的 issue...

**Comment by tinymins** [comment]
… 我的，忘记关这个 issue 已经忘记了它的存在
