### ISSUE TITLE
Question: 怎么快速简单的全局禁用demo的 codesandbox 、stackblitz等按钮

### ISSUE THREAD

**Issue by JaylanChen** [umijs/dumi#1388]
### Question

![image](https://user-images.githubusercontent.com/7055008/209281839-4edf2fa5-49c3-4e2f-827c-56f42c948697.png)

[代码位置](https://github.com/umijs/dumi/blob/3976ed86b135a3e0abfe7753f493ee31ddbaa492/src/client/theme-default/slots/PreviewerActions/index.tsx#L56)

如题，如何快速简单禁用demo的打开 codesandbox 、stackblitz 等按钮

**Comment by moecasts** [comment]
用 css 隐藏一下就好了吧？

**Comment by PeachScript** [comment]
推荐方案：创建 `.dumi/theme/slots/PreviewerActions.tsx`，包裹默认的组件并传递需要的 `disabledActions` 参数，相当于做一次柯里化

**Comment by doupo** [comment]
`import DumiPreviewerActions from 'dumi/theme-default/slots/PreviewerActions';
import React from 'react';

const PreviewerActions = (props) => {
  const config = {
    ...props,
    disabledActions: ['CSB', 'CODEPEN', 'STACKBLITZ'],
  };
  return <DumiPreviewerActions {...config} />;
};

export default PreviewerActions;
`

今天遇到这个问题，贴一下代码

**Comment by rllxxx** [comment]
> `import DumiPreviewerActions from 'dumi/theme-default/slots/PreviewerActions'; import React from 'react';
> 
> const PreviewerActions = (props) => { const config = { ...props, disabledActions: ['CSB', 'CODEPEN', 'STACKBLITZ'], }; return <DumiPreviewerActions {...config} />; };
> 
> export default PreviewerActions; `
> 
> 今天遇到这个问题，贴一下代码
![image](https://github.com/umijs/dumi/assets/13895891/8ba4f3c9-c81a-4fd4-8b7e-6b314c5728a0)
求帮助： 在theme -> slots -> PreviewActions 做覆盖并未生效
