### ISSUE TITLE
bug: 内存泄漏

### ISSUE THREAD

**Issue by shaodahong** [umijs/dumi#139]
### Versions

- dumi: 1.0.13
- node: v10.19.0
- npm: 6.13.4
- OS: osx 10.15.4
- Browser: Chrome  80.0.3987.149

### Steps to reproduce
1. 使用 `yarn` 安装
2. yarn start
3. 修改 `.umirc.ts` 配置（多修改几次）
4. `ctrl + c` 退出

### What is Expected?
进程 node 退出

### What is actually happening?
观察进程 node 没有退出

**Comment by xiaohuoni** [comment]
感觉可以转到umi issues

**Comment by PeachScript** [comment]
@xiaohuoni 这个问题有更新吗

**Comment by xiaohuoni** [comment]
还有这个问题吗？
