### ISSUE TITLE
Question: 主题插件开发，能否对 pages 目录支持

### ISSUE THREAD

**Issue by KuangPF** [umijs/dumi#1391]
### Question
在开发主题插件，涉及到完全重写首页或者其他页面等操作，根据官网文档描述，只能在`.dumi/pages/xxx` 中编写 React 组件用以覆盖，但不能在对应的插件主题代码里面编写 pages react 组件，这样在插件包发布以后，实质是不存在 pages react 组件的，从而导致不能深度定制主题。

不确定目前有啥好的建议或者解决方法没。

**Comment by PeachScript** [comment]
- pages 是为项目设计的，不是为主题包，所以主题包无法使用该约定
- 主题包的首页通常通过 DocLayout 来定制，具体可以参考默认主题的实现
- 如果要通过路由实现也是可以的，主题包提供了插件能力，通过 `api.modifyRoutes` 等钩子能够添加路由，但 dumi 目前还没提供插件文档，可以先参考 Umi 官网：https://umijs.org/docs/guides/plugins
