### ISSUE TITLE
bug: 引入json文件会解析错误

### ISSUE THREAD

**Issue by overQ-N** [umijs/dumi#1392]
使用create-dumi生成的最简模板，在代码中引入了json文件会报错
<img width="561" alt="image" src="https://user-images.githubusercontent.com/47857170/209423519-a70bec2b-8541-4af8-80c3-e675f4a8959f.png">

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/47857170/209423585-5a61988c-5b60-49c0-900f-a66851228363.png">

### Versions

- dumi:2.0.2
- node: v18.4.0
- npm: 8.12.1
- OS: Apple M1
- Browser: Chrome 108.0.5359.124

### What is Expected?
dumi1.x可以正常引用json文件，2.x无法正常运行
### What is actually happening?
只要引用json文件就会解析错误，项目template用的是Static Site

**Comment by overQ-N** [comment]
添加了json-loader解析，正常跑起来了
```js
chainWebpack(memo, { env, webpack }) {
    memo.module
      .rule('compile')
      .type('javascript/auto')
      .test(/\.json$/)
      .use('babel')
      .loader('json-loader');
  }

// webpack比较菜，不清楚这样有无问题，还是希望dumi内置一下吧

**Comment by PeachScript** [comment]
v2.0.18 已修复
