### ISSUE TITLE
feat: api表格类型自动推断增强

### ISSUE THREAD

**Issue by overQ-N** [umijs/dumi#1395]
第一张图是1.x的，可以自动推断Type类型，包括自定义的类型
<img width="700" alt="image" src="https://user-images.githubusercontent.com/47857170/209628115-cc38dbd2-243b-4618-8adb-75dc37f4e239.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/47857170/209628309-75134a5f-1da8-44e9-b498-cc49bcc32e24.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/47857170/209628433-818dfded-6811-48fb-ad03-05d568719129.png">

图二是2.x的，不能准确推断ts类型

另外在增加props（复杂类型，如第一张图的 `ruless` `onConfirm`）定义时，会导致整个项目挂掉

**Comment by PeachScript** [comment]
v2.1.11 已优化细节类型呈现

**Comment by innocces** [comment]
类似` React.CSSProperties` 还有  `number[]` 还是会变成  `object` 和 `array`
