### ISSUE TITLE
bug: 文档文件以-index结尾的被错误识别路由

### ISSUE THREAD

**Issue by tinymins** [umijs/dumi#1397]
### Versions

- dumi:2.0.17
- node:14
- npm:6
- OS:Ubuntu
- Browser:Chrome

### Steps to reproduce

- npx create-dumi
- 创建 一个叫做 data-index.md 的接口说明文档。
- 编译文档。

### What is Expected?

生成 `docs-dist/data-index.html`

### What is actually happening?

生成 `docs-dist/data-/index.html`

![image](https://user-images.githubusercontent.com/1808990/209923724-5aec8fe3-27b8-466a-880f-365c98037018.png)

**Comment by AkaraChen** [comment]
umijs 的问题，已经有 pr 修复了，等那边合并

**Comment by AkaraChen** [comment]
> > 等那边合并
> 
> 
> 
> 有什么进展么，这边是不是可以 close 了🤔。

那边没合，已经一个月了，[相关PR](https://github.com/umijs/umi/pull/10333)

**Comment by PeachScript** [comment]
Umi 层 PR 已经合并发版了，可以再试试看
