### ISSUE TITLE
dumi2, 在 demo 中引入组件,  组件代码更新后需要重新build该组件, demo才能更新， 

### ISSUE THREAD

**Issue by cx91** [umijs/dumi#1399]
### Question

dumi2, 在 demo 中引入组件,  组件代码更新后需要重新build该组件, demo才能更新
我记得dumi1是不用重新build的
难道dumi1 引入的时候是组件的src入口，dumi2 的入口改为了组件的 package.json->main

**Comment by PeachScript** [comment]
dumi 2 也是指向 src 的，ref: https://d.umijs.org/config#autoalias

**Comment by cx91** [comment]
> dumi 2 也是指向 src 的，ref: https://d.umijs.org/config#autoalias

我配上这个配置也没用，如果我在demo文件那引用组件的时候加上‘/src’，这样是能自动更新的
以前dumi1的时候是能自动更新的，最近项目升级到了dumi2

**Comment by PeachScript** [comment]
这个配置是默认开启的；可以提供最小复现仓库看下

**Comment by lee-xs0** [comment]
我好像也有这种情况，dumi1的时候是yarn workspace，2我尝试使用了pnpm workspace。会有关系吗

**Comment by PeachScript** [comment]
> 我好像也有这种情况，dumi1的时候是yarn workspace，2我尝试使用了pnpm workspace。会有关系吗

monorepo 在 v2 版本里不会自动 alias，要手动配置才行
