### ISSUE TITLE
请问怎么引入自身？

### ISSUE THREAD

**Issue by Aledenn** [umijs/dumi#140]
### Question

本地开发的时候
![image](https://user-images.githubusercontent.com/19233912/78654941-e3a94d00-78f7-11ea-8278-59a331e21f13.png)

### Sample Code

```
// demo/demo1.tsx
import React from 'react';
import Loading from 'my-ui'; // 找不到这个库

const Demo1 = () => <Loading loading />;

export default Demo1;


// dumi
<code src="./demo/demo1.tsx" />
```

**Comment by PeachScript** [comment]
package.json 设置 name 为 my-ui 了吗

**Comment by Aledenn** [comment]
> package.json 设置 name 为 my-ui 了吗

原来是引入方式错了,`import {Loading}`就好了，谢谢大佬
请问dumi是会自动解析 src下的index文件吗？

**Comment by PeachScript** [comment]
是的，dumi 的理念是，开发者使用库的方式应该和用户一样
