### ISSUE TITLE
版本更新日志在哪里看？

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1400]
如题，如果现在要更新版本（本体已经是2.x了，更新更高的版本），直接更新dumi库的版本就可以了，还是怎么？新的版本更新了哪些内容在哪里看？

**Comment by PeachScript** [comment]
使用包管理工具来更新即可，比如 `pnpm update dumi` or `npm update dumi`；更新日志都在 Release Page 里：https://github.com/umijs/dumi/releases
