### ISSUE TITLE
bug: md文档中手动书写api文档，生成的预览表格，多出一列空白列

### ISSUE THREAD

**Issue by lee-xs0** [umijs/dumi#1403]
### Versions

- dumi:2.0.18
- node:16.13.1
- npm:8.13.2
- OS: macOS12.0
- Browser:Google Chrome latest

### Steps to reproduce

![1](https://user-images.githubusercontent.com/56626207/211040938-3b9f696f-1374-48df-9ccd-c041bc29b264.png)

### What is actually happening?
![2](https://user-images.githubusercontent.com/56626207/211041013-e3f5ba84-7fdb-43e0-ada3-e4e9a54ff408.png)

**Comment by PeachScript** [comment]
看截图不像是空白列，审查元素看下是不是样式冲突了；如果找不到原因可以提供下最小可复现仓库

**Comment by lee-xs0** [comment]
感谢
