### ISSUE TITLE
bug:  API apiParser 不识别部分组件以及不稳定。

### ISSUE THREAD

**Issue by Cool-Star** [umijs/dumi#1406]
dumi2 API文档

配置打开 apiParser与resolve.entryFile后

大部分从dumi1迁移过来的组件，API是无法显示的。

并且，如果入口文件发生保存后，进程会崩溃。

**Comment by PeachScript** [comment]
2.0 的 API 换了底层解析器，还在实验性阶段，后续会逐步完善

**Comment by PeachScript** [comment]
Duplicate of #1395
