### ISSUE TITLE
dumi-theme-mobile 版本异常

### ISSUE THREAD

**Issue by Snow233** [umijs/dumi#1408]
### Sample Code
![截屏2023-01-09 下午2 58 36](https://user-images.githubusercontent.com/36450211/211255646-c4335228-e93b-4be2-9f98-6dc2bd474a20.png)

**Comment by PeachScript** [comment]
NPM 上的版本是正确的：https://www.npmjs.com/package/dumi-theme-mobile

这个版本提示是编辑器展示的，应该给编辑器的对应项目提 issue
