### ISSUE TITLE
feat: Markdown文件frontmatter的hide属性什么时候可以支持捏

### ISSUE THREAD

**Issue by FriedRiceNoodles** [umijs/dumi#1410]
![image](https://user-images.githubusercontent.com/53017934/211259064-d904609f-2860-4071-9041-b2cab8dfbcc1.png)

**Comment by DroganC** [comment]
这个可以走自定义吧
你slots里面的siderbar可以自己写内容

**Comment by PeachScript** [comment]
v2.1.3 已支持，更名为 debug 了：https://d.umijs.org/config/markdown#debug
