### ISSUE TITLE
开发过程中经常报一个看不懂的错误

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1420]
![image](https://user-images.githubusercontent.com/51065061/211966497-d03dc84d-29da-4cd2-959b-02fc0223bcc7.png)

该报错并未说明任何具体报错原因，看着像是引用其他文件夹的tsx文件时，自动省略了tsx后缀导致的，由于错误信息太过笼统，无法定位。

**Comment by CaptainJon** [comment]
![image](https://user-images.githubusercontent.com/51065061/211966678-bd5f2d47-b433-4eaa-a94b-33095c6be02f.png)

**Comment by CaptainJon** [comment]
好像也不是，没有引用其他文本地文件的，也报这个类似错误

**Comment by PeachScript** [comment]
是 API 解析逻辑抛出来的，v2.1.3 做了优化，可以试下看

**Comment by CaptainJon** [comment]
> 是 API 解析逻辑抛出来的，v2.1.3 做了优化，可以试下看

尝试用npm install 安装新版本的dumi时依旧报错
![image](https://user-images.githubusercontent.com/51065061/212055426-e86cb2b9-5b65-479c-848e-6961e6ae0af9.png)
