### ISSUE TITLE
bug: 在 .md 文件 demo中引入 antd 会报错 , 如果单独写demo 用 code 外部引入就没问题

### ISSUE THREAD

**Issue by chenmeiling2016** [umijs/dumi#1422]
### Versions

- dumi:2.1.2
- node:16.14.2
- npm:8.5.0
- OS:
- Browser:

### ![image](https://user-images.githubusercontent.com/51880353/212217074-28a49ce9-1405-4643-a166-a2c5972bc5e8.png)
![image](https://user-images.githubusercontent.com/51880353/212217119-b66afa77-4c48-4ef7-b196-42289a9e2379.png)

**Comment by PeachScript** [comment]
请按 issue 模板提交最小可复现步骤及仓库

**Comment by chenmeiling2016** [comment]
![image](https://user-images.githubusercontent.com/51880353/212221696-bc26cff6-5167-4dbe-80e2-873c3b487fe0.png)

1. 直接用官方的初始化方式， npx create-dumi   构建模版  
2. 创建好之后 安装 npm i antd 
3. 修改src目录下，Foo 文件 下的 index.md

![image](https://user-images.githubusercontent.com/51880353/212222063-2b25ee66-ce47-4a4c-9367-0117b13fbdc1.png)

**Comment by chenmeiling2016** [comment]
![image](https://user-images.githubusercontent.com/51880353/212222201-60cd2885-f628-4fc0-8c31-b39d4ab30e52.png)

这是我刚刚构建的

dumi 2.1.13
antd 5.1.4
react 18.2.0

**Comment by jeryqwq** [comment]
@chenmeiling2016  删掉node_modules/.cash 下dumi mfsu mfsu-deps 这些相关的文件夹试试，应该没啥问题

**Comment by iyanming** [comment]
同样遇到了 @jeryqwq

**Comment by iyanming** [comment]
> @chenmeiling2016 删掉node_modules/.cache 下dumi mfsu mfsu-deps 这些相关的文件夹重启试试，应该没啥问题

不行

**Comment by PeachScript** [comment]
> ![image](https://user-images.githubusercontent.com/51880353/212221696-bc26cff6-5167-4dbe-80e2-873c3b487fe0.png)
> 
>     1. 直接用官方的初始化方式， npx create-dumi   构建模版
> 
>     2. 创建好之后 安装 npm i antd
> 
>     3. 修改src目录下，Foo 文件 下的 index.md
> 
> 
> ![image](https://user-images.githubusercontent.com/51880353/212222063-2b25ee66-ce47-4a4c-9367-0117b13fbdc1.png)

可以复现，原因还在排查，临时方案是在配置文件里加上 `mfsu: false` 关闭 MFSU 提速方案

**Comment by PeachScript** [comment]
v2.1.5 已修复

**Comment by autelai4** [comment]
2.3.0仍然有这个问题
