### ISSUE TITLE
bug: apiParser 设置为 {} 会导致文档构建卡住

### ISSUE THREAD

**Issue by huarse** [umijs/dumi#1424]
### Versions

- dumi: 最新版本
- node: 14
- npm: 6.x
- OS: mac

### Steps to reproduce

1. 通过官方文档的方式创建一个工程：`$ npx create-dumi`
2. 修改 .dumirc.ts 配置，增加 `apiParser` 和 `resolve.entryFile`(否则会报错)

```ts
import { defineConfig } from 'dumi';

export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    name: 'hello-dumi',
  },
  apiParser: {},
  resolve: {
    entryFile: './src/index.ts',
  },
});
```

3. `$ pnm docs:build`

会卡在构建这一步
<img width="194" alt="image" src="https://user-images.githubusercontent.com/3724927/212275650-591f606e-34d9-4d3d-bf00-37d22e554331.png">

**Comment by gong9** [comment]
估计现在api生成太慢了

**Comment by CaptainJon** [comment]
我都没有用原生提供的API组件，直接手撸的表格

**Comment by PeachScript** [comment]
v2.1.6 开始改成子线程解析，不会卡文档构建了，issue 关闭；但解析慢的问题还在优化中，目前用 NPM 或 Yarn 的项目解析会快不少，PNPM 则非常慢

**Comment by giscafer** [comment]
@PeachScript 还有卡住的情况

![image](https://user-images.githubusercontent.com/8676711/220579210-e382e318-95e3-4333-bca9-df2681a52d78.png)

**Comment by PeachScript** [comment]
@giscafer 这是解析真的慢，解析线程没结束文档构建也没法结束；原因是 monorepo 下依赖被提升，当前 `node_modules` 找不到的包按目前的逻辑会去 `unpkg.com` 找，暂时无解

**Comment by giscafer** [comment]
一直卡着，不会断开也不报错。隔了一夜了。

**Comment by Stoneleee** [comment]
想请问：monorepo  entryFile这个字段怎么配置呢

**Comment by lby1024** [comment]
天坑啊

**Comment by giscafer** [comment]
@Stoneleee 我也是API 不能自动解析
