### ISSUE TITLE
bug: 文档编译后的构建产物在windows环境下的路径错误

### ISSUE THREAD

**Issue by ppmmwozuiai** [umijs/dumi#1429]
### Versions

- dumi: 2.1.3
- node: 16.17.1
- yarn: 1.22.19 
- OS: windows 10
- Browser: chrome/edge

### Steps to reproduce

1. yarn create dumi
2. dumi build

### What is actually happening?
node_modules/dumi/dist/client/pages/*下的文件的构建产物被冠以绝对路径，
那么在windows环境下，文件路径就带了盘符+工程名，类似如下内容：
D:/__demo__node_modules__dumi__dist__client__pages__404.649cde31.async.js
D:/__demo__node_modules__dumi__dist__client__pages__404.d5b31768.chunk.css
D:/__demo__node_modules__dumi__dist__client__pages__Demo__index.72cfa70d.async.js
D:/__demo__node_modules__dumi__dist__client__pages__Demo__index.578aa5c0.chunk.css
而windows生成文件时会把D:/截去，只能生成：__demo__node_modules__dumi__dist__client__pages__404.649cde31.async.js这样文件名
这样部署后，加载页面时就抛出404错误
### What is Expected?
修改构建产物的路径，

相关代码：
https://github.com/umijs/dumi/blob/8a981697a76f6938373a08c584b0d68ec02880bb/src/features/routes.ts#L90
https://github.com/umijs/dumi/blob/8a981697a76f6938373a08c584b0d68ec02880bb/src/features/routes.ts#L274

**Comment by PeachScript** [comment]
感谢反馈，v2.1.5 已修复
