### ISSUE TITLE
bug: Demo 配置的 description，html 标记被转义了，无法正常显示

### ISSUE THREAD

**Issue by lecepin** [umijs/dumi#1432]
### Versions

- dumi: 2.1.3
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce

```
```jsx
/**
 * title: 基础用法
 * description: 这是介绍。<br /> 下一行
 */
```

![image](https://user-images.githubusercontent.com/11046969/213102224-692e46bd-5a5b-4f1a-9814-af2aa9e1f516.png)

### What is Expected?

https://github.com/umijs/dumi/blob/master/src/client/theme-default/builtins/Previewer/index.tsx#L51

![image](https://user-images.githubusercontent.com/11046969/213102548-8a45ae68-cdd7-4d34-acaa-3dec7e22acf5.png)

看此处的代码，应该是可以显示 HTML 的。不知转义 HTML 现象，是刻意设计的  还是 遗漏了。

**Comment by PeachScript** [comment]
v2.1.5 已修复
