### ISSUE TITLE
为什么去掉了中文路由支持？

### ISSUE THREAD

**Issue by GeraltX** [umijs/dumi#1433]
### Question
以前 dumi 1 支持中文文件夹和文件名的，为什么现在去掉了？
直接用 `encodeURI` 做判断？
是出于什么考虑吗？
以后会支持吗？

**Comment by PeachScript** [comment]
不会支持了，中文 URL 会有很多潜在问题，比如：
1. 路由静态化的时候会有中文文件名，但有些静态站点托管服务是不支持的，会部署失败
2. SEO 不友好，比如 sitemap.xml
3. 网站埋点统计不友好

dumi v1 其实是遗漏了校验，为了避免 Breaking Change 才一直保留的

**Comment by Hehejie1** [comment]
这个感觉对于写文档不太友好吧，路径不能含有中文可以理解，但是文件名不支持中文就有点不能理解了

**Comment by codepandy** [comment]
一升级，整个文档改一遍？无语啊
