### ISSUE TITLE
feat: rewrite menuSorter

### ISSUE THREAD

**Issue by kagawagao** [umijs/dumi#144]
### Description

在没有指定 order 的情况下，是否可以直接比较 `path` 的 `ASCII` 顺序，而不是 `path` 的长度，这样的话也能保证相同字符开始的文档能够连续排列，往往以相同字符开始的是文档是相关文档。

### Sulution

当前

https://github.com/umijs/dumi/blob/37c9784c437c36a85a53935bf2fd6a9b5f9739e0/packages/preset-dumi/src/routes/getMenuFromRoutes.ts#L103-L114

![image](https://user-images.githubusercontent.com/6930280/78885877-e474e700-7a8f-11ea-83cc-8bc72e645a16.png)

修改后

```ts
export function menuSorter(prev, next) {
  const prevOrder = typeof prev.meta?.order === 'number' ? prev.meta.order : Infinity;
  const nextOrder = typeof next.meta?.order === 'number' ? next.meta.order : Infinity;
  // compare order meta config first
  const metaOrder = prevOrder === nextOrder ? 0 : prevOrder - nextOrder;
  // last compare path ASCII
  const pathOrder = prev.path- next.path;

  // 因为 `path` 必然不同，所以无需再比较 `title`
  return metaOrder || pathOrder;
}
```

![image](https://user-images.githubusercontent.com/6930280/78885772-be4f4700-7a8f-11ea-8492-d77eb6ee2ba3.png)

**Comment by PeachScript** [comment]
可以来个 PR
