### ISSUE TITLE
单md文件引入多个demo 会被覆盖

### ISSUE THREAD

**Issue by DroganC** [umijs/dumi#1440]
在一个index.md里面引入如下
```
<code src="./ListScrollExample/index.jsx"></code>

<code src="./ChartsNumericalExample/index.jsx"></code>

<code src="./ChartsBarColorExample/index.jsx"></code>

<code src="./ChartsCyclicColorExample/index.jsx"></code>
```
会全部覆盖为最后一个，虽然filename不同但是因为后缀都是index导致asset.id是一样的，最后preview的效果都是一样的
能否在code里面增加一个id属性 来区别

**Comment by ellen2212** [comment]
同遇到+1，
版本信息：dumi 2.1.0 即使升级到 2.1.6 也一样
仓库https://stackblitz.com/github/ellen2212/dumi-demo
同一个md文件引入不同demo，demo名一样就被覆盖。
这个issue怎么就被close掉了 郁闷
@PeachScript

**Comment by PeachScript** [comment]
> 这个issue怎么就被close掉了 郁闷

因为没提供复现仓库和步骤，按照 issue 描述的路径无法复现

> 同一个md文件引入不同demo，demo名一样就被覆盖。

这个在目前的逻辑里是正常的，因为 demo 文件名会作为 demo id 的生成依据，按照正常的使用场景，组件下的 demo 文件名都应该是不一样的

**Comment by ellen2212** [comment]
那可以增加一个小优化吗？不以文件名做唯一id, 或者增加code的id属性，会适用更多场景

**Comment by PeachScript** [comment]
> 增加code的id属性

这个是支持的，但考虑到同名 demo 的场景本身比较奇怪，所以没有写进文档

**Comment by ellen2212** [comment]
非常感谢您的回复，我们是想做一些简单组件看板， 以同类型/功能的角度集合一些组件，给非开发人员看。方便比较和筛选组件。看了下源码好像是不支持，以文件名和md文档的atomId做唯一标识，不过这两个在我当前场景并不唯一，或者有没有其他方案？

**Comment by PeachScript** [comment]
看了下 id 的确不支持，临时方案：

<pre language="markdown">
```jsx
export { default } from '/path/to/demo';
```
</pre>

缺点是源码不对，但非开发人员可以用 inline 模式不展示源码

**Comment by ellen2212** [comment]
确实是不需要展示源码，原本是在theme里的previewer 控制布局和控制是否隐藏源码。我再想想。谢谢您，希望之后某个版本可以支持code的id属性
