### ISSUE TITLE
bug: qiankun has been not supported in dumi@2.0.2

### ISSUE THREAD

**Issue by fengsx** [umijs/dumi#1442]
### Versions

- dumi:2.0.2
- node:14.20.0
- npm:
- OS:
- Browser:Chrome

### Steps to reproduce

- Initialize the project according to the document
- 
``` bash
$ mkdir myapp && cd myapp
$ npx create-dumi
```
- modifiy `.dumirc.ts`，just add configiure:

```
qiankun: {
    master: {},
  },
```

- install dependencies and start
```
$ npm start
```

an error was reported:
![image](https://user-images.githubusercontent.com/7709602/215436270-fdab7beb-4c39-4a4a-90f0-523db0d46835.png)

### What is Expected?

 Microapp was supported by `qiankun`

### What is actually happening?

` Invalid config keys: qiankun` was reported

**Comment by PeachScript** [comment]
qiankun 不是内置能力：

- dumi v1 安装 `@umijs/plugin-qiankun` 后可用
- dumi v2 安装 `@umijs/plugins` 并配置 `plugins: ['@umijs/plugins/dist/qiankun']` 后可用
