### ISSUE TITLE
多级路由无法实现自动跳转的问题

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1445]
我注意到dumi的官网也有这个问题，比如配置项的页面，配置项的按钮实际设置的路由是/config，但是我点击配置项左侧的其他导航，比如demo配置，/config/demo，顶部配置项的高亮却没了，按理来说都属于config下的子路由，配置项应当也保持高亮的。正常应该来说有个默认的跳转路由，比如顶部导航到/config时，自动跳转到某个子路由，比如/config/test，现在是没法实现

**Comment by PeachScript** [comment]
> 点击配置项左侧的其他导航，比如demo配置，/config/demo，顶部配置项的高亮却没了

我用 Chrome 109、FireFox 109 访问 https://d.umijs.org/config/demo 均无法复现，效果：
![图片](https://user-images.githubusercontent.com/5035925/215965098-32e9d7a9-2744-4636-948f-770e6de5dc59.png)

> 比如顶部导航到/config时，自动跳转到某个子路由，比如/config/test

存在 `/config` 索引路由就不会跳子路由，不存在时才会跳子路由，比如只创建 `config/test.md` 而不创建 `config/index.md`

**Comment by CaptainJon** [comment]
> > 点击配置项左侧的其他导航，比如demo配置，/config/demo，顶部配置项的高亮却没了
> 
> 我用 Chrome 109、FireFox 109 访问 https://d.umijs.org/config/demo 均无法复现，效果： ![图片](https://user-images.githubusercontent.com/5035925/215965098-32e9d7a9-2744-4636-948f-770e6de5dc59.png)
> 
> > 比如顶部导航到/config时，自动跳转到某个子路由，比如/config/test
> 
> 存在 `/config` 索引路由就不会跳子路由，不存在时才会跳子路由，比如只创建 `config/test.md` 而不创建 `config/index.md`

我没有索引路由，顶部导航使用的是/components，组件（src/components目录下）都用文件夹（比如src/components/button）包裹了一层，作为二级路由，并设置了atomDirs定位到components。但是我点击顶部导航跳转到/components，并不会自动跳转到我第一个组件的介绍（上一个版本是可以的），而是界面中出现dumi内置的页面未找到的介绍，必须在左侧点击组件，才会出现界面。
当然，我可以把顶部导航的路由更改为/components/button，这样点击导航会访问第一个组件，但是点击其他组件，就无法和顶部一级导航产生高亮互动了，因为/components/button并不是其他组件的父级路由，只有设置/components才是，这样无论查看哪个组件，顶部导航都处于高亮状态。而且，这样也没有解决用户单独在浏览器访问/components会出现缺省界面的问题。

**Comment by PeachScript** [comment]
请提供一个最小复现仓库

**Comment by nmsn** [comment]
这问题怎么解决的
