### ISSUE TITLE
请问如何隐藏codesandbox按钮

### ISSUE THREAD

**Issue by FanHHHHH** [umijs/dumi#1453]
### 2. 请问如何修改全局默认字体大小
注意到，默认主题下，`.markdown` 下的 `font-size` 来自 `heiti.scss`，而这个文件是外部库提供的，如果想修改markdown文本字体大小、标题和表格大小，改如何操作？

**Comment by PeachScript** [comment]
> 1.请问如何隐藏codesandbox按钮

ref: https://github.com/umijs/dumi/issues/1388#issuecomment-1363912651

> 2. 请问如何修改全局默认字体大小

1. 局部改写，`.dumi/global.less`
2. 全局覆盖，`.dumi/theme/slots/Content.tsx`，覆盖内置的 `Content` 组件，自己重写全部的样式
