### ISSUE TITLE
文档打包部署后网页出错

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1456]
执行`npm run docs:build`然后部署到服务器的某个目录`test`下后，发现网页无法显示出来，通过`f12`查看，发现网页请求了一个绝对路径的文件，而这个文件是不存在的，windows也不允许这样格式的文件吧，不知道为什么会去请求这样的一个文件。其他的资源都请求成功。

![QQ图片20230206094435](https://user-images.githubusercontent.com/51065061/216863034-4aa80612-ae2e-4e6d-8d84-7212f2919aa7.png)
![企业微信截图_16756473505511](https://user-images.githubusercontent.com/51065061/216863060-3a5a06bd-43fe-4ace-a0f4-93957a882aa8.png)

**Comment by PeachScript** [comment]
升级到最新版试下，应该和这个是一个问题， #1291
