### ISSUE TITLE
feat: .dumirc need to support config devServer

### ISSUE THREAD

**Issue by suyue0731** [umijs/dumi#1457]

**Comment by PeachScript** [comment]
提需求请补充背景信息

**Comment by suyue0731** [comment]
基于一些安全问题，我们的后端项目只允许特定端口跨域，希望能在dumirc里边把devServer的配置放出来，另外我试过了chainWebpack修改devServer，似乎无法生效

**Comment by PeachScript** [comment]
dumi/Umi 不是基于 webpack-dev-server 的，暂时没有提供 `devServer` 配置项的计划；需要改监听端口可以用 `PORT` 环境变量

**Comment by suyue0731** [comment]
用环境变量可以解决，希望能把支持的环境变量补充到文档里，谢谢🙏

**Comment by kkxi22** [comment]
> 用环境变量可以解决，希望能把支持的环境变量补充到文档里，谢谢🙏

环境变量dumi里怎么使用呢
