### ISSUE TITLE
自动API表格  如何在JSDoc 下使用？文档没示例

### ISSUE THREAD

**Issue by H5er** [umijs/dumi#1465]
### Question
自动API表格  如何在JSDoc 下使用？文档没示例

我是在js中写的组件，然后根据JSDoc 在组件上方写的注释，表格没检测出来

**Comment by PeachScript** [comment]
仅支持从 ts 模块解析类型定义，JSDoc 指在 TypeScript 类型基础上用注解提供更多信息，比如 `@default`
