### ISSUE TITLE
monorepo 、yarn workspaces 下，解析 demo 时会遇到umi 版本错误的问题

### ISSUE THREAD

**Issue by cx91** [umijs/dumi#1467]
monorepo项目升级到 dumi2.x，采用yarn workspaces 拉取的包，有一个组件里面用到了umi 3.x 中的  useRouteMatch  方法(该方法在umi4 中已停用)，在解析demo时报
```
Attempted import error: 'useRouteMatch' is not exported from 'umi' (imported as 'useRouteMatch').
```
怀疑是用到dumi2.x中依赖的umi4.x了，没有用组件package.json 中所定义的umi3.x

```
npm ls umi
```

<img width="694" alt="dumi包依赖图" src="https://user-images.githubusercontent.com/34469827/218010846-ec637f09-5b6f-47d3-936e-aeab0ca9b641.png">

monorepo项目打包，发布组件是对的

**Comment by PeachScript** [comment]
1. Umi 是开发框架，组件库是独立的 NPM 包，组件源码不应该依赖 Umi，无论是 3 还是 4
2. dumi 2 只能与 Umi 4 一起用，所以 issue 里提到的情况无法支持

建议修正组件库对开发框架的依赖，就不会存在多个 Umi 版本的问题了

**Comment by cx91** [comment]
> 1. Umi 是开发框架，组件库是独立的 NPM 包，组件源码不应该依赖 Umi，无论是 3 还是 4
> 2. dumi 2 只能与 Umi 4 一起用，所以 issue 里提到的情况无法支持
> 
> 建议修正组件库对开发框架的依赖，就不会存在多个 Umi 版本的问题了

假设dumi2.x 依赖了A 包(npm 包)，那组件库的包还能使用A包的其他版本吗？
