### ISSUE TITLE
总是构建报错    dumi: not found

### ISSUE THREAD

**Issue by DaphnisLi** [umijs/dumi#1469]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/67792799/218060508-c87bec3b-fc5a-468d-bd4e-8e45e550a4c4.png">

**Comment by PeachScript** [comment]
依赖安装或环境问题需要自行排查，dumi 无法控制，比如依赖声明是否正确、npm 是否正常安装依赖、bin 文件权限是否正确之类的
