### ISSUE TITLE
如何自定义文件的加载顺序？

### ISSUE THREAD

**Issue by code-artisan** [umijs/dumi#1472]
### Question
我自己写了一套多端适配的组件，大概的结构如下：
![image](https://user-images.githubusercontent.com/5195218/218363638-aab5bf61-5f88-4238-b2a8-1d8f80366e42.png)

以上仅为其中某个组件的文件结构作为示例，其他组件的文件结构与此类似。

在构建文档时我想自定义文件的加载顺序，如：优先查找 `index.web.tsx` 这样的文件，如果找不到则查找 `index.tsx`，否则 index.tsx 可能会存在引用 react-native 文件的情况，最终会导致构建失败。在 dumi 2 中应该怎么配置？

dumi version: 2.1.9

### Sample Code
--

**Comment by PeachScript** [comment]
用 `chainWebpack` 配置项改 webpack 的 `resolve.extensions` 配置，把 `.web.tsx` 放前面即可：https://webpack.js.org/configuration/resolve/#resolveextensions
