### ISSUE TITLE
bug: Z.indexOf is not a function

### ISSUE THREAD

**Issue by Chang1ng** [umijs/dumi#1480]
### Versions

- dumi: "^2.0.2",     "dumi-theme-chakra": "^0.0.7"
- node: 16
- OS: mac10+
- Browser: chrome

![image](https://user-images.githubusercontent.com/6593784/218987442-bb7b1c93-ca49-4f7f-b4f1-fca0cad7c933.png)

**Comment by PeachScript** [comment]
主题包的报错应该提交到主题包的仓库

**Comment by Chang1ng** [comment]
FYI https://github.com/innocces/dumi-theme-chakra/issues/12#event-8535775951
