### ISSUE TITLE
dumi2.x 在demo目录下从包名引入会提示找不到模块或者相应的类型声明

### ISSUE THREAD

**Issue by qc-z** [umijs/dumi#1481]
![image](https://user-images.githubusercontent.com/22362903/219263601-5cb9782b-147a-4bd8-b714-932275f65c3a.png)

前提
1 组件库 package.json 里有指明类型文件，且该类型文件已构建出来
`"typings": "lib/index.d.ts"`
疑问
直接引用包名不是自动指向src下吗？

**Comment by PeachScript** [comment]
这是类型找不到，如果是官方 React 脚手架初始化的，确保 tsconfig.json 里的 paths 配置正确，ref: https://github.com/umijs/dumi/blob/8836776706019d1bea6335f2b98cd603c7765b8f/suites/boilerplate/templates/react/tsconfig.json.tpl#L11

**Comment by qc-z** [comment]
@PeachScript 完美解决，谢谢
