### ISSUE TITLE
bug: 文档名字是中文，路由解析错误。 Error: Invalid route path: a/b/中文, please rename it with only alphanumeric, dash and slash.

### ISSUE THREAD

**Issue by Hehejie1** [umijs/dumi#1485]
### Versions

- dumi: v2.1.10
- node: 14+
- npm:   6.8
- OS:
- Browser:

### Steps to reproduce
在docs下面3级目录创建中文文档

### What is Expected?
正常渲染

### What is actually happening?
报错please rename it with only alphanumeric, dash and slash.

**Comment by PeachScript** [comment]
请认真阅读错误提示，dumi 2 不支持中文路由

**Comment by Hehejie1** [comment]
这个有配置可以支持中文吗？

**Comment by PeachScript** [comment]
ref: https://github.com/umijs/dumi/issues/1433#issuecomment-1407257195
