### ISSUE TITLE
feat: no use filepath to name chunks

### ISSUE THREAD

**Issue by master1lan** [umijs/dumi#1487]
### Description
 我在使用pnpm，build后会生成大量的类似
`__code__project__xxx__xxx__node_modules__.pnpm__dumi_2.1.9_4a6x6pblykqee7ucamos27j3la__node_modules__dumi__dist__client__pages__404.6bcf71bf`名字的js文件，在本地预览没有问题但是部署到服务器上后这些文件虽然存在但是全是404，建议提供dumi自身chunkname的生成规则

**Comment by PeachScript** [comment]
v2.1.15 已优化
