### ISSUE TITLE
怎么写latex

### ISSUE THREAD

**Issue by shengzhaotong** [umijs/dumi#1488]
怎么才能在文档上显示latex公式，我在markdown里面写类似于$y=x^2$这种的显示的都是原文

**Comment by PeachScript** [comment]
dumi 的 Markdown 解析基于 Unified.js 生态，通过 [extraRemarkPlugins](https://d.umijs.org/config#extraremarkplugins) 和 [extraRehypePlugins](https://d.umijs.org/config#extrarehypeplugins) 配置项挂载额外的解析插件即可：https://www.npmjs.com/package/remark-math , https://www.npmjs.com/package/rehype-katex

**Comment by shengzhaotong** [comment]
Error: Cannot find module 'https://www.npmjs.com/package/remark-math'


import { defineConfig } from 'dumi';

export default defineConfig({
&nbsp; themeConfig: {
&nbsp; &nbsp; name: 'test',
&nbsp; },
&nbsp; extraRemarkPlugins: ["https://www.npmjs.com/package/remark-math"],
&nbsp; extraRehypePlugins: ["https://www.npmjs.com/package/rehype-katex"]
});





已经通过yarn安装了这两个依赖（yarn add remark-math; yarn add rehype-katex），然后报这个错
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/dumi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/dumi] 怎么写latex (Issue #1488)





 
dumi 的 Markdown 解析基于 Unified.js 生态，通过 extraRemarkPlugins 和 extraRehypePlugins 配置项挂载额外的解析插件即可：https://www.npmjs.com/package/remark-math , https://www.npmjs.com/package/rehype-katex

**Comment by PeachScript** [comment]
请阅读配置项文档，插件配置值不应是 NPM 网址

**Comment by shengzhaotong** [comment]
公式现在能渲染出来了，但是但是markdown里面写一个公式会被渲染出来两个，
例如写：$$y=x$$
会出现：
请问有什么配置可以让它在网页上只显示前半部分吗，求指点。


import { defineConfig } from 'dumi';

export default defineConfig({
&nbsp; themeConfig: {
&nbsp; &nbsp; name: 'hourglass',
&nbsp; },
&nbsp; extraRemarkPlugins: ['remark-math'],
&nbsp; extraRehypePlugins: ['rehype-katex']
});




&nbsp; "dependencies": {
&nbsp; &nbsp; "rehype-katex": "5.0.0",
&nbsp; &nbsp; "remark-math": "4.0.0"
&nbsp; }




------------------&nbsp;原始邮件&nbsp;------------------


发件人:                                                                                                                        "umijs/dumi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月20日(星期一) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [umijs/dumi] 怎么写latex (Issue #1488)





 
请阅读配置项文档，插件配置值不应是 NPM 网址
