### ISSUE TITLE
description的显示必须先设置title不合理

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1489]
背景：在编写FrontMatter属性时，想通过description插入一段描述的话，单独写description属性不生效，必须同时设置title才显示，这个是否不太合理？

期望：title和description都可以单独设置并显示

**Comment by PeachScript** [comment]
没有标题就没有 TOC，description 的内容也不可搜索跳转，只配 description 不是最佳用法，所以目前没有支持的计划
