### ISSUE TITLE
请教下有关lessloader配置modifyVars变量的文体

### ISSUE THREAD

**Issue by Superzzw1994** [umijs/dumi#1490]
![image](https://user-images.githubusercontent.com/20533727/220287066-6190b3f0-29ea-43e4-9828-69c53326a007.png)

![ZzlatAPqRV](https://user-images.githubusercontent.com/20533727/220287263-46eee886-a0ba-4854-a8d2-8220ca3f0b97.jpg)

@chaoswise/ui是公司根据antd封装的组件库，更改了antd的主题变量，当配置后会报上图这个错误，貌似是覆盖掉了dumi的主题变量？
当去掉后，就是找不到chaoswise的变量，如下图。
![4NhcWQzvQT](https://user-images.githubusercontent.com/20533727/220287313-8b42d4ae-421a-4218-956b-d46f101fd648.jpg)
请问，怎么配置我自己定义的变量呢？谢谢~

**Comment by PeachScript** [comment]
改用 theme 设置 less 变量应该就行了，和 modifyVars 等价：https://d.umijs.org/config#theme
