### ISSUE TITLE
Module not found: Error: Can't resolve 'xxx' in md file

### ISSUE THREAD

**Issue by pheart** [umijs/dumi#1493]
dumi version: 2.1.5
example: 
package name is @aaa/x,
but have a error,  Module not found: Error: Can't resolve '@aaa/x' 

in md file: 
```tsx
import {  }  from "@aaa/x";

....
```

**Comment by PeachScript** [comment]
按 issue 模板提供复现仓库及步骤

**Comment by pheart** [comment]
> 按 issue 模板提供复现仓库及步骤

仓库地址： https://github.com/pheart/dumi2.0-demo

步骤：
pnpm start

报错 Can't resolve 'demo1'，  在packages/demo1/src/foo/index.md 中使用import { } from 'demo1'

**Comment by PeachScript** [comment]
monorepo 需要自行配置包名到源码目录的 alias，例如 `alias: { demo1: path.join(__dirname, 'packages/demo1/src') }`，ref: https://d.umijs.org/config#alias

**Comment by pheart** [comment]
已生效
