### ISSUE TITLE
组件使用react-intl的错误<IntlProvider> needs to exist如何处理？

### ISSUE THREAD

**Issue by giscafer** [umijs/dumi#1494]
![image](https://user-images.githubusercontent.com/8676711/220512898-89a81ece-9074-48b5-82cd-9162c8df7ee7.png)

如图，组件源码用了` import { useIntl } from 'react-intl'; `

**Comment by PeachScript** [comment]
提示得很清楚了，组件父级必须存在 react-intl 的 provider 才能调用 hook，你可以选择在 demo 调用组件的代码外层套 provider

**Comment by giscafer** [comment]
嗯，我一直想找的是App级别的 provider 添加方式~

**Comment by PeachScript** [comment]
App 级别可以用 `.dumi/theme/layouts/GlobalLayout`，但由于 dumi 自己也用了 `react-intl`，不确定会不会有 ConfigProvider 干扰
