### ISSUE TITLE
如何取消页面左侧自动生成的菜单？

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1495]
有时候一个页面只需要展示一个模块的内容，程序却会默认取用当前路由来作为左侧的默认菜单，虽然可以通过设置title来更改名称，但毕竟页面只有一个模块，并不想展示这个左侧菜单，有什么办法能取消呢？

**Comment by PeachScript** [comment]
还不支持，计划和 dumi 1 一样新增 `sidebar: boolean` 的 frontmatter 配置项，欢迎 PR

**Comment by PeachScript** [comment]
v2.1.14 已支持

**Comment by FanSun521** [comment]
没有支持哇

**Comment by FanSun521** [comment]
我用的v2.3.0
