### ISSUE TITLE
bug: 2.1.11 版本 demo 分栏展示异常 

### ISSUE THREAD

**Issue by mainhanu** [umijs/dumi#1496]
### Versions

- dumi: 2.1.11

### Steps to reproduce
查看 https://d.umijs.org/guide/page-config 的官方展示。
![image](https://user-images.githubusercontent.com/48398913/220551457-7e014db8-30f4-4449-997b-0e6a7f4b1f63.png)

**Comment by PeachScript** [comment]
@shunyue1320 有时间看看这个问题么，可能和 code 逻辑的调整有关系

**Comment by shunyue1320** [comment]
> @shunyue1320 有时间看看这个问题么，可能和 code 逻辑的调整有关系
已经本谁修复了吧
![image](https://user-images.githubusercontent.com/47295879/220564627-0a477650-250b-462e-ae17-0321d678e732.png)

**Comment by PeachScript** [comment]
@shunyue1320 我本地测试问题还在的，会不会和操作系统有关系

**Comment by PeachScript** [comment]
v2.1.12 已修复
