### ISSUE TITLE
bug: 2.1.11版本 react组件库打包出来的umd文件无法使用，报错

### ISSUE THREAD

**Issue by zjz1993** [umijs/dumi#1497]
复现方式：https://github.com/zjz1993/dumiFix/blob/master/example/example.html
example里的fix.min.js是组件库打包umd格式的产物， 运行这个网页期望正常展示组件内容
实际情况：报错，白屏
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/17746534/220557161-d4f803fc-4729-4d9f-8645-dbaedcaf3600.png">

**Comment by PeachScript** [comment]
React-based 组件库要在 `.fatherrc.ts` 里把 react 和 react-dom external 掉，后续打包相关问题提交到 father 仓库

**Comment by zjz1993** [comment]
> 

<img width="531" alt="image" src="https://user-images.githubusercontent.com/17746534/220560237-42ce3d15-b617-4c0b-99ab-2caefb8cf4e8.png">
请问是这样external吗？

**Comment by PeachScript** [comment]
不是，值是什么取决于 umd 的挂载变量，react/react-dom 分别是 React/ReactDOM

**Comment by hacker0limbo** [comment]
father umd 配置了 externals 后还是报错, 配置如下:

```js
export default defineConfig({
  // more father config: https://github.com/umijs/father/blob/master/docs/config.md
  esm: { output: 'dist/esm' },
  umd: {
    output: 'dist/umd',
    extractCSS: false,
    externals: {
      react: 'React',
      'react-dom': 'ReactDOM',
    },
  },
  sourcemap: true,
});
```

打包后使用组件报错信息为: Cannot find module React

![image](https://user-images.githubusercontent.com/36297538/231636841-02938bbe-d662-4e05-9fa7-50f0ad252c2b.png)
