### ISSUE TITLE
Module not found: Error: Empty dependency (no request)

### ISSUE THREAD

**Issue by kakachake** [umijs/dumi#1500]
项目创建完成后运行项目报错

**Comment by PeachScript** [comment]
按 issue 模板提交足够的复现信息

**Comment by kakachake** [comment]
> 按 issue 模板提交足够的复现信息

- dumi: latest
- node: 16.15.0
- npm: 8.16.0
- OS: win111

npx create-dumi
pnpm run dev

报错：
Module not found: Error: Empty dependency (no request)

**Comment by PeachScript** [comment]
脚手架无法复现

**Comment by kakachake** [comment]
不好意思，npx默认用的旧版的create-dumi，问题解决了
