### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by shunyue1320** [umijs/dumi#1506]
### Versions
dumi: 2.1.7
node: v16.13.0
npm: 8.19.2
OS: 13.1
Browser: 版本 109.0.5414.119（正式版本） (arm64)

### Steps to reproduce
两个demo文件名一样时文档上会渲染同一个demo
![2E88 1R S{V2G{I8X5S9JTN](https://user-images.githubusercontent.com/47295879/221158277-afdfd289-3282-4684-9927-c94ce878a055.png)
![I78@OHX9BAY10_7YB4F{(}P](https://user-images.githubusercontent.com/47295879/221158310-98b57cc9-1466-4fa0-9582-caf6238a04db.png)

### What is actually happening?
原因是 https://github.com/umijs/dumi/blob/master/src/loaders/markdown/transformer/rehypeDemo.ts#L230 取的是文件name
最终编译后的md长这样：
```tsx
<DumiDemoGrid
  items={[
    {
      demo: { id: 'dot-loading-demos-demo1'' },
      previewerProps: { filename: '../dot-loading/demos/demo1.tsx' },
    },
    {
      demo: { id: 'spin-loading-demos-demo1' },
      previewerProps: { filename: '../spin-loading/demos/demo1.tsx' },
    },
  ]}
/>
```
可以看出 id 是一致的，导致渲染一致了

当我把 id 改成不一致时，渲染效果就正常了：
![image](https://user-images.githubusercontent.com/47295879/221164641-42f8db97-f59a-4299-a3a9-9d2d527a8bca.png)

![image](https://user-images.githubusercontent.com/47295879/221162634-f7bdf544-afa0-47c4-a83b-4b9a65d98308.png)

所以 https://github.com/umijs/dumi/blob/master/src/loaders/markdown/transformer/rehypeDemo.ts#L230 是不是不应该取文件name呢？

**Comment by PeachScript** [comment]
Duplicate of #1440

**Comment by PeachScript** [comment]
issue 需要补充标题

> 是不是不应该取文件name呢？

现在是取 `name.tsx` 或 `name/index.tsx` 中的 name 来生成 id，设计的场景中组件关联的所有 demo 都在自己的 `demos` 文件夹下，所以不会出现重名；不知道截图中的用法具体是什么场景，但相比于修改 id 生成规则我更倾向于输出警告 + 允许用户自己指定 id，这样不会有 Breaking Change，而且这类用法目前来看是极少数

**Comment by shunyue1320** [comment]
Ant Design Mobile 就是这么用的：
https://github.com/ant-design/ant-design-mobile/blob/master/src/components/loading/index.zh.md?plain=1#L11

**Comment by shunyue1320** [comment]
没事我只是好奇😁

**Comment by Wxh16144** [comment]
我提供了一个复现 https://github.com/Wxh16144/dumi-report-issue-1440;

计划在 https://github.com/Wxh16144/dumi-report-issue-1440 修复它，可以给我点思路么？
