### ISSUE TITLE
Markdown表格宽度是否可以优化

### ISSUE THREAD

**Issue by wizcheu** [umijs/dumi#1509]
### Question
dumi表格目前都是等宽的，有些列内容比较多，导致需要换行很多，而等宽的问题在于有些列内容很少但也占据了很宽的列宽，看着很难受。
### Sample Code

github效果：
|少|多|
|:-:|:-------:|
| x | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |

dumi效果：
<img width="949" alt="image" src="https://user-images.githubusercontent.com/28148028/221754486-e48704d4-9f3d-4a64-b086-1d217ce8ed10.png">

**Comment by Wxh16144** [comment]
Test:

| Title  | Description |
| --- | --- |
| x | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |
| xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx | x |
| xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx |

**Comment by PeachScript** [comment]
v2.1.15 已优化
