### ISSUE TITLE
如何在demo中引用一个外部的自己的组件

### ISSUE THREAD

**Issue by sdhr27** [umijs/dumi#151]
### Question
步骤：
1、在已有项目中新建了一个文件夹，使用脚手架构建了dumi文档系统
2、从项目本身中引用组件来写demo。
3、组件本身是用ts写的，code引用后出现报错，无法解析深层的ts文件：
```
error  in ../src/components/Antd/EditModal/EditModal.tsx

Module parse failed: Unexpected token (21:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // * 限制当前可取用的组件内部方法
> type editModalRef = {
|   triggerEdit: () => void;
| };

 @ ../src/components/Antd/EditModal/index.tsx 1:0-36 5:15-24
 @ ./src/Editmodal/index.tsx
 @ ./src/index.ts
 @ ./src/Foo/index.md
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts
```
疑问：
是因为我在一个项目里内嵌了文档项目，两套umi配置不兼容么？

### Sample Code
EditModal/index：
```
// 引用外部主项目中的组件
import EditModal from '../../../src/components/Antd/EditModal';
export default EditModal;
```
md文档：
```<code src="./demo/beforeEdit.tsx" title="可编辑" />```
beforeEdit demo：
```
import React from 'react';
import { EditModal } from 'dumi-lib';
class App extends React.Component {
   // code
}
export default App;
```

**Comment by PeachScript** [comment]
有文件夹分层，配置天然隔离开来了吧？是否有复现仓库可以看一下

**Comment by sdhr27** [comment]
目录层级截图可以么？site文件夹存放dumi，config是项目本身的umi配置，两套配置文件的层级关系：
![TIM图片20200420092222](https://user-images.githubusercontent.com/37827411/79705596-cce7fa80-82e8-11ea-87d3-d3ca99054ba1.png)
components的位置：
![TIM图片20200420092337](https://user-images.githubusercontent.com/37827411/79705708-408a0780-82e9-11ea-981b-c03986f374f4.png)

**Comment by PeachScript** [comment]
启动 dumi 的时候是在 site 目录下启动的还是仓库根目录？

**Comment by sdhr27** [comment]
是在site目录下启动的：yarn dumi dev

**Comment by sdhr27** [comment]
我创建了一个仓库：https://github.com/sdhr27/dumi_test
在site文件夹下运行yarn start，报错如下：
![image](https://user-images.githubusercontent.com/37827411/79711546-ab900a00-82fa-11ea-93bf-dba78c17555e.png)

**Comment by PeachScript** [comment]
Umi 的 babel-loader [默认只从当前目录开始处理](https://github.com/umijs/umi/blob/266e94ca76b07d052b31143eb41e5b6aeb1bf1a7/packages/bundler-webpack/src/getConfig/getConfig.ts#L175)，目前可以通过 [config.chainWebpack](https://umijs.org/zh-CN/config#chainwebpack) 配置项手动加个 include 解决。

这种场景需要一个更好的解法，后面看下结合 UMI_ENV 做个切换，把文档和项目结合。

**Comment by sdhr27** [comment]
请问可以更具体一些么？如何通过config.chainWebpack手动加个 include？

**Comment by sdhr27** [comment]
感谢，我知道怎么设置了

**Comment by sdhr27** [comment]
我遇到了另外一个问题：
![image](https://user-images.githubusercontent.com/37827411/79959564-dcb53980-84b6-11ea-91dc-729e5d7f7265.png)
如何处理less？我看代码里css相关的配置好像是封装起来的？

**Comment by PeachScript** [comment]
`~` 意味着去找模块，node_modules 下有 theme 这个模块吗？

**Comment by sdhr27** [comment]
在同事的帮助下解决了~的确是theme存在问题，设置了alias后就好了
![TIM图片20200423181026](https://user-images.githubusercontent.com/37827411/80087502-bc0be300-858d-11ea-9226-bd7468549134.png)

**Comment by sdhr27** [comment]
> 一些么？如何通过config.chainWebpack手动加个 include？
> 您好，请问这一步是怎么做的？求

![image](https://user-images.githubusercontent.com/37827411/120452646-eea92180-c3c4-11eb-80f3-6af086ae29bf.png)
more config: https://d.umijs.org/config

**Comment by qqjay2017** [comment]
> > 一些么？如何通过config.chainWebpack手动加个 include？
> > 您好，请问这一步是怎么做的？求
> 
> ![image](https://user-images.githubusercontent.com/37827411/120452646-eea92180-c3c4-11eb-80f3-6af086ae29bf.png) more config: https://d.umijs.org/config

非常感谢
