### ISSUE TITLE
bug: 打包输出组件的antd-v5与调用项目antd-v4样式冲突

### ISSUE THREAD

**Issue by GuanJdoJ** [umijs/dumi#1515]
- 描述：
1 使用dumi开发组件库，father打包，组件库用antd v5版本，用ConfigProvider配置prefixCls为mc
2 引用项目本身使用antd v4版本，导入1组件库中组件
3 引用项目中v4或v5某一个样式失效，有时是v5无样式，有时是v4无样式

- 展示：
下图铃铛来自组件库，按钮来自引用项目
<img width="595" alt="image" src="https://user-images.githubusercontent.com/30386473/222134136-8e563285-331f-4237-85e0-121e46feefac.png">

<img width="557" alt="image" src="https://user-images.githubusercontent.com/30386473/222132473-9d2b08ff-a7b3-4453-b95f-e75632289266.png">

- 组件库配置：
//.fatherrc
import { defineConfig } from 'father';
export default defineConfig({
  esm: { output: 'dist' },
});
//package.json
"dependencies": {
  "antd": "^5.2.2",
},
"devDependencies": {
    "dumi": "^2.1.10",
    "father": "^4.1.5",
}

- 引用项目配置：
//package.json
"dependencies": {
    "antd": "4.24.8",
}

- 期望：
组件库与调用项目样式互不影响

**Comment by PeachScript** [comment]
从描述来看该问题和组件库具体实现或实际项目编译有关，这不在 dumi 和 father 的答疑范畴，请自行排查解决
