### ISSUE TITLE
feat: 没有符号的list是没有灵魂的

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#152]
![image](https://user-images.githubusercontent.com/2802841/80168532-ab9f4b00-8615-11ea-939a-2b595cf76de2.png)

只是缩进的list, 没有缩进符号, 我只想说.......难看·~

**Comment by PeachScript** [comment]
这个问题如何复现，官网渲染示例中的列表是有符号的：https://d.umijs.org/examples#%E5%88%97%E8%A1%A8

**Comment by mizi-lin** [comment]
升级到 1.0.18，有显示

**Comment by mizi-lin** [comment]
时灵时不灵的··~

**Comment by PeachScript** [comment]
如何复现

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/80470991-5a74bb80-8975-11ea-8ad6-eb5c1ad2a793.png)

**Comment by PeachScript** [comment]
无法复现，建议禁用浏览器扩展试试看，issue 先关闭了，如果问题仍然存在，请提供复现步骤再 reopen
