### ISSUE TITLE
feat: Line Highlighting in Code Blocks

### ISSUE THREAD

**Issue by Wxh16144** [umijs/dumi#1520]
### Description

也许我们可以支持指定行代码块高亮配置

![image](https://user-images.githubusercontent.com/32004925/222694189-ceb2c0d0-76f7-4fde-94e6-88cc23152fa6.png)

借鉴：https://vitepress.vuejs.org/guide/markdown#line-highlighting-in-code-blocks

### Solution

自定义 remark plugin ?

**Comment by Wxh16144** [comment]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/32004925/222699132-28c1e09f-a975-4687-9279-f912f88373a1.png">

附上 @arvinxx 的建议：https://rehype-pretty-code.netlify.app/

**Comment by PeachScript** [comment]
> https://rehype-pretty-code.netlify.app/

这个太高级了，加上很多用法并非社区共识，有需要的用户可以自己配置在 dumi 的 `extraRehypePlugins` 里使用 👀 

---

我的想法是仅支持指定行高亮就能满足大部分场景了，用户用法上可以[类似 Vitepress](https://vitepress.vuejs.org/guide/markdown#line-highlighting-in-code-blocks)：

<pre>
```jsx {1,2-4,3,9-10}
balabala
```
</pre>

解析的时候需要先把数据解析成 `{ start: number; end?: number }[]` 的形式（可能在[这里处理](https://github.com/umijs/dumi/blob/482c28fcbc4cdb62d2c6b424f979a58386383d3f/src/loaders/markdown/transformer/rehypeRaw.ts#L45)），应该有以下几种场景消费：

- 纯代码块可以在 [`rehypeEnhancedTag`](https://github.com/umijs/dumi/blob/273680ea22877e5a6df2c00516ded5ded21a3844/src/loaders/markdown/transformer/rehypeEnhancedTag.ts#L29) 里通过 `JSXAttribute` 把参数传给 `SourceCode` 组件
- 代码块 demo 和上面类似，但需要借 `Previewer` 再传给 `SourceCode`
- 外部 demo 可以支持 `highlightLines` 的属性和 FrontMatter，再借 `Previewer` 传给 `SourceCode`

和 dumi 已经支持的 `jsx | pure` 修饰符怎么配合使用需要讨论下，可能这么用看着合理点 <code>```jsx {1} | pure</code>

**Comment by Wxh16144** [comment]
> 和 dumi 已经支持的 `jsx | pure` 修饰符怎么配合使用需要讨论下，可能这么用看着合理点 `` ```jsx {1} | pure ``

发表一个个人观点，如果配置了 `jsx {1,2-4}` 则表示默认 pure。 这样我们只实现对代码块进行高亮。 DemoBlock 不做任何高亮处理。

**Comment by PeachScript** [comment]
> 如果配置了 `jsx {1,2-4}` 则表示默认 pure

也可以的，这样框架复杂度更低一些，后面真有需求了再说

**Comment by Wxh16144** [comment]
@any1024 感兴趣来个 PR~ 么

**Comment by any1024** [comment]
好的，让我来试试

> @any1024 感兴趣来个 PR~ 么

**Comment by PeachScript** [comment]
v2.1.16 已支持
