### ISSUE TITLE
dumi2.0怎么启用dva

### ISSUE THREAD

**Issue by programmer-jiangtao** [umijs/dumi#1522]

**Comment by PeachScript** [comment]
dva 只能独立引入使用，具体参考 dva 文档，但由于 dva 已经不维护了，建议采用其他数据流方案

另外无论是 dumi 1 还是 dumi 2，都不应该借用框架集成 dva 来使用（比如挂载 @umijs/plugin-dva 插件），组件库不同于应用，不应借助任何由框架提供的能力，这会导致组件库发布后无法如预期工作

**Comment by programmer-jiangtao** [comment]
umi4不是有dva配置么，为什么dumi就没有了？
