### ISSUE TITLE
bug: dumi_v1.0.20 不能正常启动 

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#153]
- dumi: v1.0.20
- node: v13.13.0

## 编译出错，说 md 路径查找不到

![image](https://user-images.githubusercontent.com/2802841/80181739-05b10800-8638-11ea-8358-ded671c881c4.png)

## 回滚至 v1.0.18 正常启动

![image](https://user-images.githubusercontent.com/2802841/80181807-224d4000-8638-11ea-8822-f721680eafe2.png)

**Comment by PeachScript** [comment]
回到最新版，删除 .umi 文件夹重试看看

**Comment by mizi-lin** [comment]
删除了， 而且重装依赖，还是有老问题

**Comment by PeachScript** [comment]
是否有复现 repo

**Comment by jf3096** [comment]
同样有问题:
```
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports["default"] = _default2;

var _react = _interopRequireDefault(require("react"));

var _Alert = _interopRequireDefault(require("D:/Project/untitled291/node_modules/@umijs/preset-dumi/lib/themes/default/builtins/Alert.js"));
```

**Comment by PeachScript** [comment]
如果问题仍然存在，请两位提供下复现 repo

**Comment by mizi-lin** [comment]
v1.0.24 可以正常启动·~~

**Comment by halionn** [comment]
> 同样有问题:
> 
> ```
> InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('"use strict";
> 
> Object.defineProperty(exports, "__esModule", {
>   value: true
> });
> exports["default"] = _default2;
> 
> var _react = _interopRequireDefault(require("react"));
> 
> var _Alert = _interopRequireDefault(require("D:/Project/untitled291/node_modules/@umijs/preset-dumi/lib/themes/default/builtins/Alert.js"));
> ```

一样的问题

**Comment by PeachScript** [comment]
@halionn 最新版还有问题吗？有的话请提供下最小复现 repo
