### ISSUE TITLE
bug: .dumirc中mfsu配置项中配置exclude后编译出错

### ISSUE THREAD

**Issue by suyue0731** [umijs/dumi#1530]
### Versions

- dumi: 2.1.15
- node: 14.18.2
- npm: 6.14.15
- OS: Mac11.3.1
- Browser: Chrome

### Steps to reproduce
照着官网的文档创建一个新项目test-dumi

在组件库index.ts中随便写一个依赖，例如axios
```
import request from 'axios'

export function test() {
  console.log(request)
}
```

创建src/demos/Test.tsx组件，引用test函数
```
import React, { useEffect } from 'react'
import { test } from 'test-dumi'

export default function Test() {
  useEffect(() => {
    test()
  }, [])
  return (
    <div/>
  )
}
```

在脚手架初始化后的guide.md中添加demo
`<code src="../src/demos/Test.tsx"></code>`

在dumirc中更改mfsu的配置exclude掉axios

```
import { defineConfig } from 'dumi';

export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    name: 'test-dumi',
  },
  mfsu: {
    exclude: ['axios']
  }
});
```

### What is Expected?
启动项目可以正常编译
### What is actually happening?
启动项目，编译报下面的错，去掉mfsu配置后编译成功
<img width="675" alt="image" src="https://user-images.githubusercontent.com/18397351/223397722-fe145581-2de9-482d-9141-5a9adfb8e5eb.png">

**Comment by cwjTerrace** [comment]
mark

**Comment by suyue0731** [comment]
有人跟进一下吗？如果想要代码在https://github.com/umijs/dumi/issues/1538这个被关掉的issue里有

**Comment by PeachScript** [comment]
这周会处理，有兴趣的话也欢迎 PR

**Comment by PeachScript** [comment]
v2.1.6 已修复
