### ISSUE TITLE
使用dumi打包less文件报错，烦请帮忙看看

### ISSUE THREAD

**Issue by darren-duan** [umijs/dumi#1532]
#### 报错共16个错误，均为截图所示的错误类型：
`
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis？

`

### 报错截图：
![image](https://user-images.githubusercontent.com/47881187/223677266-2ccf765c-b645-4cdb-a6d1-a5406397bca7.png)

#### 在dumirc文件中配置了lessLoader兼容性设置，但是还是无用：
<img width="663" alt="image" src="https://user-images.githubusercontent.com/47881187/223677800-b85ab883-3425-40d9-b348-74679fc3d2d3.png">

**Comment by PeachScript** [comment]
打包基于 father，而 .dumirc.ts 仅用于 dumi；可以在 .fatherrc.ts 里通过 chainWebpack 修改 loader 配置：https://github.com/umijs/father/blob/master/docs/config.md#chainwebpack

**Comment by darren-duan** [comment]
在fatherc 中配置了，但还是一样的报错，找不到原因，麻烦帮忙看看是不是不支持？

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/47881187/223741008-78a89be8-2c42-4352-bdcd-d69cd7078a7a.png">

**Comment by darren-duan** [comment]
@PeachScript
