### ISSUE TITLE
2.0 的 API 为什么要换底层解析器？当前解析器很多1.0能够解析的，这边都不行了，请问替换的目的是啥？

### ISSUE THREAD

**Issue by programmer-jiangtao** [umijs/dumi#1533]

**Comment by programmer-jiangtao** [comment]
如果是实验性的功能，能不能提供方法使用1.0时期的解析器？

**Comment by PeachScript** [comment]
两个原因：
1. 旧解析器是 `react-docgen-typescript`，实质上已经不维护了，dumi 1 用的已经是 fork 后改造的版本，之前为了解不兼容 TypeScript 新版的问题
2. 新解析器数据结构符合 JSON Schema 的规范，解析出的数据更全，而且对 jsDoc 的支持更好

但新解析器还需要完善，所以目前是实验性功能。

> 如果是实验性的功能，能不能提供方法使用1.0时期的解析器？

dumi 自身不会提供，但你可以通过开放能力（rehype 插件 + 全局组件）自己实现一个类似 `OldAPI` 的组件
