### ISSUE TITLE
如果需要分析文档完善度，应该使用什么插件 API

### ISSUE THREAD

**Issue by mainhanu** [umijs/dumi#1536]
### Question
如题，需要在构建时按目录分析(如 componets/xx)每个目录下的文档完整度，使用哪个插件 API 合适？

比如：
1. 获取文档里的 demo 数目
2. 解析 markdown，获取文档的段落数目。

**Comment by PeachScript** [comment]
借助自定义的 rehype 插件可以处理 mdast，在 vFile.data 里能拿到 demo 数量（参考 dumi 仓库 rehypeDemo.ts 源码），再想办法聚合输出即可

你这个想法挺好的，可以考虑写个 RFC 直接在 dumi 里实现，把文档完善度的评分机制和数值都合并到资产元数据里，成为一个新字段：https://github.com/umijs/dumi/blob/431fbabfb94111f2168f3adc06d6cfc6df9a8ec1/assets-types/typings/atom/index.d.ts

**Comment by Wxh16144** [comment]
> 文档完善度的评分机制

好奇这个评分机制怎么计算 🤔

**Comment by mainhanu** [comment]
> 借助自定义的 rehype 插件可以处理 mdast，在 vFile.data 里能拿到 demo 数量（参考 dumi 仓库 rehypeDemo.ts 源码），再想办法聚合输出即可
> 
> 你这个想法挺好的，可以考虑写个 RFC 直接在 dumi 里实现，设计文档完善度的评分机制并计算成数值合并到资产元数据里，成为一个新字段：https://github.com/umijs/dumi/blob/431fbabfb94111f2168f3adc06d6cfc6df9a8ec1/assets-types/typings/atom/index.d.ts

感谢，我试试

我们内部文档是有模板的，完善度也是针对模板的分析，不算通用
