### ISSUE TITLE
Dumi dev时scss文件中引入相对路径font字体文件解析失败

### ISSUE THREAD

**Issue by xiazhiqiang** [umijs/dumi#1537]
### Question

Dumi dev时scss文件中引入相对路径font字体文件解析失败

### Sample Code
app.scss
@import "./styles/font";

styles/font
@font-face {
    font-family: 'Noto Sans SC';
    font-style: normal;
    font-weight: 500;
    src: local(''),
        url('../fonts/noto-sans-sc-v26-latin_chinese-simplified-500.woff2') format('woff2'), 
        url('../fonts/noto-sans-sc-v26-latin_chinese-simplified-500.woff') format('woff');
  }

![image](https://user-images.githubusercontent.com/8468916/224234670-ab4ffb17-2cbc-41e4-a4ce-25f82316206d.png)

如何支持修改？

**Comment by PeachScript** [comment]
提问需提供最小可复现仓库

**Comment by xiazhiqiang** [comment]
https://github.com/xiazhiqiang/dumi-demo/blob/main/src/index.ts

**Comment by xiazhiqiang** [comment]
可复现的最小Demo，npm start就可以看到报错

**Comment by PeachScript** [comment]
参考：https://github.com/webpack-contrib/sass-loader#problems-with-url

**Comment by Jerryqun** [comment]
解决了吗
