### ISSUE TITLE
建议：FrontMatter 是否可以添加一个key, 设定模式是否打开 code, 查看源代码

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#154]
RT

**Comment by PeachScript** [comment]
`inline` 模式？

**Comment by mizi-lin** [comment]
非inline模式，若能都支持就更好了；
目前是需要点击查看 source 的图标，方可查看源码；
建议 FrontMatter 添加属性，可以默认打开源码框
---
若工具条和可视区可以设置互换位置就更完美了
即 源码块 在 可视区域上方

@PeachScript

**Comment by PeachScript** [comment]
源代码默认打开后续可以支持，但换位置太过定制化了，不会作为内置参数，可以后面主题定制开放之后进行自定义

**Comment by PeachScript** [comment]
v1.0.25 已支持：https://d.umijs.org/config/frontmatter#defaultshowcode

**Comment by mizi-lin** [comment]
cool
