### ISSUE TITLE
cra项目启动成功后，突然退出进程

### ISSUE THREAD

**Issue by CalvinP-Cai** [umijs/dumi#1542]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
第一步：把图中标记代码放开，执行
` npx cross-env APP_ROOT=./ dumi dev `
![image](https://user-images.githubusercontent.com/37281618/224658272-53d3f8d7-f0fd-46dc-a147-d92e8706b897.png)
第二步：把第一步放开代码注释调，再启动，就可以正常启动
![image](https://user-images.githubusercontent.com/37281618/224658743-0443477e-4459-426b-a805-c10885c232d5.png)

[复现项目](https://github.com/CalvinP-Cai/dumi_test)

**Comment by PeachScript** [comment]
component 单词拼错了
