### ISSUE TITLE
问一下有啥办法可以修改 .dumi/tmp-production 里的文件？

### ISSUE THREAD

**Issue by Go7hic** [umijs/dumi#1547]
### Question
.dumi 目录下的  tmp-production  是 build 的时候自动生成的，但是我想改一下生成的/tmp-production/umi.ts 文件代码，不知道有啥可以修改的办法？

**Comment by PeachScript** [comment]
无法直接修改，这可能破坏 Umi 的构建流程，可以通过编译时插件或运行时插件来达成部分修改的效果，比如增加一些代码：https://d.umijs.org/plugin/api#addentrycode
