### ISSUE TITLE
使用create-dumi指令报错

### ISSUE THREAD

**Issue by Volume3** [umijs/dumi#1551]
### Question
使用脚手架创建项目，报'create-dumi' is not recognized as an internal or external command, operable program or batch file.
node版本是v18.15.0
### Sample Code
![image](https://user-images.githubusercontent.com/47254392/225715770-9fd95956-4b7a-4d14-bd25-0ac0399e89a1.png)

**Comment by PeachScript** [comment]
无法复现，应该和 npm 安装或执行环境有关系，请自行排查，[ref](https://stackoverflow.com/a/38989697)
