### ISSUE TITLE
bug: dumi2.x hash history 模式下，在独立页面中打开 demo，将跳转到 404

### ISSUE THREAD

**Issue by CJY0208** [umijs/dumi#1554]
hash history 模式下，在独立页面中打开 demo，将跳转到 404

原因为 demoLink 中未携带 # 号
![image](https://user-images.githubusercontent.com/18415774/225798368-17d01f0b-5399-4a34-8adb-78c177a212f4.png)

目前本地修复方式为复写 slots/PreviewerActions，手动处理 demoUrl，不过感觉可能最好是在生成 demoUrl 的地方处理最好

```jsx
// .dumi\theme\slots\PreviewerActions.tsx
import React, { useMemo } from 'react'
import PreviewerActions, { IPreviewerActionsProps } from 'dumi/theme-default/slots/PreviewerActions'

export default function OverridedPreviewerActions({ demoUrl, ...props }: IPreviewerActionsProps) {
  const fixedDemoUrl = useMemo(() => demoUrl.replace(/\/~demos\//, `${window.location.pathname}#/~demos/`), [demoUrl])

  return <PreviewerActions {...props} demoUrl={fixedDemoUrl} />
}
```

### Versions

- dumi: 2.1.5
- node: 14.18.3
- npm: 6.14.15
- OS: Win10
- Browser: Chrome 107.0.5304.63

**Comment by PeachScript** [comment]
dumi 2 目前是不支持 hash 模式的，hash 模式问题统一合并到一个 issue 讨论吧

**Comment by PeachScript** [comment]
Duplicate of #1553
