### ISSUE TITLE
bug: useSiteSearch下的searchWorker中的正则用法错误

### ISSUE THREAD

**Issue by paradox010** [umijs/dumi#1557]
### Versions

- dumi: latest
- node: >=16
- npm: >=8
- OS: macos
- Browser: chrome

### Steps to reproduce

```md
---
# index.md
---

## title1
浙江
## title2
1浙江
```
search words : `浙江`
title2中的浙江将不会被识别出来

### What is actually happening?

原因：[lastIndex/MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex)  
matchReg中的lastIndex没有重置为0

https://github.com/umijs/dumi/blob/9983d4a57effbd67634979168c744c4b00c32aee/src/client/theme-api/useSiteSearch/searchWorker.ts#L256-L262

可以修改为
```js
if (matchReg.test(sec.rawTitle)) {
        matchReg.lastIndex = 0;
```
同理其他使用到了matchReg.test方法的地方。

**Comment by PeachScript** [comment]
看了下没用它 match 或者 replace，也可以去掉 `g`？

**Comment by PeachScript** [comment]
v2.1.18 已修复
