### ISSUE TITLE
约定式路由 解析问题

### ISSUE THREAD

**Issue by JaylanChen** [umijs/dumi#1558]
### Question
目前约定式路由，src 只解析 子文件夹的一个文档，如：/path/to/src/hello/index.md，其他的都不识别，如：/path/to/src/hello/world.md

怎么才能让它识别，类似/path/to/src/hello/world.md 的文档呢？

**Comment by PeachScript** [comment]
这种目录结构不是推荐实践，`src` 下的资产应该以文件夹为单位放置文档和源码，参考[目录结构](https://d.umijs.org/guide/project-structure)文档，嵌套会降低可维护性；特殊需要的话可以自己修改 `resolve.atomDirs`/`resolve.docsDirs` 配置项实现
