### ISSUE TITLE
使用dumi2.x默认主题的时候，切换主题有什么办法能监听到，我希望在切换文档主题的时候同时切换自己组件库的主题

### ISSUE THREAD

**Issue by qc-z** [umijs/dumi#1561]
![image](https://user-images.githubusercontent.com/22362903/226255752-b08e8bd0-0a7c-4d45-9d73-e42be29a8c2f.png)

**Comment by PeachScript** [comment]
ref: https://d.umijs.org/theme/api#usepreferscolor

逻辑可以写在 `.dumi/theme/layouts/GlobalLayout` 里
