### ISSUE TITLE
bug: code block compiled failed when import type

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#1563]
### Versions

- dumi: 2.1.17
- node: 16.19.1
- npm: 8.19.3
- OS: macOS 13.1
- Browser: --

### Steps to reproduce

代码块里写 `import type a from 'xxx'`，然后启动编译

### What is Expected?

正常编译

### What is actually happening?

抛出类似错误：

```bash
error - ./path/to/index.md?type=meta
Module build failed (from ./node_modules/@umijs/bundler-webpack/compiled/babel-loader/index.js):
SyntaxError: /path/to/index.md?type=meta: 'import' and 'export' may only appear at the top level. (45:0)

  43 |         }))
  44 | };
> 45 | export { };
     | ^
  46 |
  47 | }),
  48 |     asset: {
```

原因是 SWC 在遇到 `import type` 时会输出 `export {}` 导致代码块后续编译报错，需要手动在 react.ts 里做移除

**Comment by PeachScript** [comment]
v2.1.18 已修复

**Comment by goldEli** [comment]
> v2.1.18 已修复

v2.2.1 有这个问题 需要回退吗
