### ISSUE TITLE
bug:dumi官网，中文的guide页面显示页面未找到

### ISSUE THREAD

**Issue by Robinliu123456** [umijs/dumi#1564]
### Versions

- dumi: dumi官网
- node:
- npm:
- OS: Mac
- Browser: Chrome、Safari等浏览器

### Steps to reproduce
1. 🔍搜索dumi官网
![image](https://user-images.githubusercontent.com/49096641/226515303-4d90de99-e067-455e-ab57-4bb573ea6f91.png)

2. 出现dumi的官网地址，点击进入，会重定向到: https://d.umijs.org/zh-CN/guide,显示页面未找到
![image](https://user-images.githubusercontent.com/49096641/226515427-3ac5bbbc-947a-49ff-a8a6-3d26f2538b98.png)

### What is Expected?
显示正常，正常显示中文guide页面
### What is actually happening?
显示页面未找到

**Comment by PeachScript** [comment]
百度索引过期了

**Comment by Robinliu123456** [comment]
> 

好像是的，其它搜索都没问题

**Comment by PeachScript** [comment]
已添加重定向，到 zh-CN 的路由都会重定向到首页
