### ISSUE TITLE
feat: resolve.atomDirs 文档路径可以支持自定义名称？

### ISSUE THREAD

**Issue by nuonuo534** [umijs/dumi#1565]
resolve: {
    atomDirs: [
      { type: 'component', dir: 'src' },
      {
        type: 'select',
        dir: '../src/components_form'
      }
    ],
  },

// README.md or {name.md}
### Description
组件有很多历史文档都是以README.md命名，希望dir属性可以传全路径

**Comment by PeachScript** [comment]
文件名 rename 一下很方便，即便量大写个脚本也能一劳永逸；支持自定义会增加框架复杂度并且留下历史包袱，所以目前没有支持的计划
