### ISSUE TITLE
bug: local icon does not work, type `LocalIconsKeys` does not generate correctly

### ISSUE THREAD

**Issue by WilkinWendy** [umijs/dumi#1568]
### Versions

- dumi: 2.1.15
- node:
- npm:
- OS:
- Browser:

### What is actually happening?
paths.absSrcPath  is errorly ended with '.dumi'

**Comment by PeachScript** [comment]
没看懂，按照模板提供完整复现信息

**Comment by kiiroOvO** [comment]
> 没看懂，按照模板提供完整复现信息

我似乎也遇到了同样的问题
`.dumirc.ts`
```ts
export default defineConfig({
  icons: {},
})
```
使用
```tsx
import {Icon} from "dumi"

<Icon icon="local:add" />
```

并没有按预期加载到 `src/icons/add.svg`

**Comment by kiiroOvO** [comment]
> 没看懂，按照模板提供完整复现信息

# Versions
dumi: 2.1.17
node:  16.19.1
npm: 8.19.3
OS: Mac OS 13.2.1 (22D68)
Browser: Chrome Version 110.0.5481.177 (Official Build) (arm64)

# Steps to reproduce

.dumirc.ts
```ts
export default defineConfig({
  icons: {},
})
```
use Icon:
```tsx
import {Icon} from "dumi"

<Icon icon="local:add" />
```

the svg filepath is  `src/icons/add.svg`
```html
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path
    d="M8.8 15.3C8.8 15.9627 9.33726 16.5 10 16.5C10.6627 16.5 11.2 15.9627 11.2 15.3V11.2H15.3C15.9627 11.2 16.5 10.6628 16.5 10C16.5 9.33731 15.9627 8.80005 15.3 8.80005H11.2V4.7C11.2 4.03726 10.6627 3.5 10 3.5C9.33726 3.5 8.8 4.03726 8.8 4.7V8.80005H4.7C4.03726 8.80005 3.5 9.33731 3.5 10C3.5 10.6628 4.03726 11.2 4.7 11.2H8.8V15.3Z"
    fill="#A9A9B5" />
</svg>

```
# What is Expected?
load the svg 
# What is actually happening?
nothing (no error),I can't get the svg in the browser

and the file `.dumi/tmp/plugin-icons/icons.tsx` is this :
```tsx
// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export const __no_icons = true;
```
and `.dumi/tmp/plugin-icons/index.tsx`
```tsx
import * as iconsMap from './icons';

export const Icon = React.forwardRef<HTMLSpanElement, IUmiIconProps>((props, ref) => {
  //...
  const Component = iconsMap[iconName];
  if (!Component) {
    // TODO: give a error icon when dev, to help developer find the error
    return null;
  }
  //...
}

```

**Comment by PeachScript** [comment]
@kiiroOvO 感谢提供完整信息。

这是文档的问题，`icons` 特性继承自 [Umi 框架](https://umijs.org/docs/api/config#icons)的能力，但仅适用于 Umi 前端应用研发的场景；而 dumi 作为组件研发场景的文档框架，不应提供任何需要依托框架才能在组件源码中使用的能力，这会导致 NPM 包发布后无法按预期工作，所以我会更新文档将这个配置项去掉。

对于组件中的 icon 引入问题，有两种建议：

1. 直接引入 svg 文件，发包后需要宿主项目的编译框架支持 `url-loader/file-loader` 或同等能力
2. 如果是 React 组件库，可以用 [svgr 网站](https://react-svgr.com/playground/)转换成 React 组件直接使用

**Comment by kiiroOvO** [comment]
> @kiiroOvO 感谢提供完整信息。
> 
> 这是文档的问题，`icons` 特性继承自 [Umi 框架](https://umijs.org/docs/api/config#icons)的能力，但仅适用于 Umi 前端应用研发的场景；而 dumi 作为组件研发场景的文档框架，不应提供任何需要依托框架才能在组件源码中使用的能力，这会导致 NPM 包发布后无法按预期工作，所以我会更新文档将这个配置项去掉。
> 
> 对于组件中的 icon 引入问题，有两种建议：
> 
> 1. 直接引入 svg 文件，发包后需要宿主项目的编译框架支持 `url-loader/file-loader` 或同等能力
> 2. 如果是 React 组件库，可以用 [svgr 网站](https://react-svgr.com/playground/)转换成 React 组件直接使用

@PeachScript  谢谢
