### ISSUE TITLE
bug: Demo's shown source  code does not match, when using `<code src="./demos/demo.tsx"></code>`

### ISSUE THREAD

**Issue by WilkinWendy** [umijs/dumi#1572]
### Versions

- dumi: 2.1.17
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
<img width="370" alt="image" src="https://user-images.githubusercontent.com/24538691/226933252-c74eed69-5d0e-4db1-911c-939736f31ad3.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/24538691/226933902-ad5ba218-c754-4e55-8078-362e12bdebed.png">

### What is actually happening?
<img width="915" alt="image" src="https://user-images.githubusercontent.com/24538691/226933153-21ec4d13-4a9c-497c-af8a-86227f4774a7.png">

**Comment by PeachScript** [comment]
提供最小可复现仓库看下

**Comment by WilkinWendy** [comment]
> 提供最小可复现仓库看下

问题大概定位到了，是因为，
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/24538691/227130812-7cc218b2-5e16-4b87-b255-a8f8882c885c.png">
这个dependencies 的值是按文件名为键的，直接依赖的文件被被默认为`index.tsx` 而 我使用`import {Icon} from '..'` 时
`..` 也指向的是 index.tsx, 键相同被覆盖掉了

**Comment by PeachScript** [comment]
`..` 引入组件不是正确用法，参考：https://d.umijs.org/guide/write-demo#%E5%9C%A8-demo-%E4%B8%AD%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6
