### ISSUE TITLE
feat: docs下的md文件会自动生成nav，但是不支持排序，希望支持

### ISSUE THREAD

**Issue by wendyzhaogogo** [umijs/dumi#1573]

**Comment by PeachScript** [comment]
导航也可以通过 FrontMatter 排序，参考：https://d.umijs.org/guide/conventional-routing#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E8%88%AA%E5%88%86%E7%BB%84%E5%92%8C%E6%A0%87%E9%A2%98
