### ISSUE TITLE
lerna + dumi 自动生成API表格问题

### ISSUE THREAD

**Issue by Yang-Xinping** [umijs/dumi#1576]
### Question
我的组件库是用lerna搭建的，项目有多个入口文件，在配置自动生成API 表格时，entryFile不能同时配置多个入口文件，这个怎么处理

**Comment by PeachScript** [comment]
Duplicate of #1372

**Comment by Yang-Xinping** [comment]
@PeachScript  monorepor模式下, 在.dumi/resolveEntry.ts导出子包之后，.dumirc.ts的entryFile该怎么写
