### ISSUE TITLE
官网的那种alert怎么调出来的？

### ISSUE THREAD

**Issue by lichnow** [umijs/dumi#158]
如图
<img width="858" alt="p" src="https://user-images.githubusercontent.com/1695900/80266477-ae11ab80-86ce-11ea-971a-0dc2b1235922.png">

**Comment by PeachScript** [comment]
可查看官网的文档代码：https://github.com/umijs/dumi/blame/master/docs/config/index.md#L9

这部分的文档会在内置组件完善后补充

**Comment by fikyair** [comment]
> 可查看官网的文档代码：https://github.com/umijs/dumi/blame/master/docs/config/index.md#L9
> 
> 这部分的文档会在内置组件完善后补充

没有找到 -.-

**Comment by xrkffgg** [comment]
https://d.umijs.org/guide/basic#alert
