### ISSUE TITLE
bug: internal/event_target by node error

### ISSUE THREAD

**Issue by xuya227939** [umijs/dumi#1585]
![image](https://user-images.githubusercontent.com/16217324/228470127-b519cac0-f4f9-49e6-bbd5-6ce622e64edf.png)

npm run dev 运行 dumi ，修改几下代码，热更新几次，node 就会报错

### Versions

- dumi: 2.0.2
- node: 16.19.1
- npm: 8.19.3
- OS: Win10
- Browser: Chrome

### Steps to reproduce
1. npm run dev
2. update code
3. hotReload

### What is Expected?

正常运行

**Comment by PeachScript** [comment]
`apiParser` 目前在 Windows 下工作不正常

**Comment by xuya227939** [comment]
@PeachScript 啥原因？

**Comment by xuya227939** [comment]
@PeachScript 可以了，谢谢

**Comment by LiFaNSuperMan** [comment]
我也遇到了同样的问题，如果我想使用apiParser应该怎么处理呢
