### ISSUE TITLE
css modules应该放开

### ISSUE THREAD

**Issue by ahongdepu** [umijs/dumi#1586]
### Question
我看dumi阻止了css modules的配置，但是导致组件前缀之类的共有变量无法导出使用，让人非常不爽。

我支持组件库不使用cssModules，但是dumi不应该强制不使用吧，建议默认关闭，允许配置开启
### Sample Code
@prefix: ~'ant-form';

:export {
  prefix: @prefix
}

**Comment by PeachScript** [comment]
NPM 包发布以后在 Umi 里使用时是不识别 CSSModules 的，即便你本地开发时能工作，发布后又会发现 import 进来的 prefix 是没有值的，所以强制关闭是为了开发所见即发布所得

关于你这个问题本身，给 JS 单独创建一个 `src/constants.ts` 来存放 `prefix` 也不会增加太多维护成本

**Comment by ahongdepu** [comment]
> NPM 包发布以后在 Umi 里使用时是不识别 CSSModules 的，即便你本地开发时能工作，发布后又会发现 import 进来的 prefix 是没有值的，所以强制关闭是为了开发所见即发布所得
> 
> 关于你这个问题本身，给 JS 单独创建一个 `src/constants.ts` 来存放 `prefix` 也不会增加太多维护成本

作为框架怎么能强制约束使用者呢，而且还是这种不影响使用的规范性问题。

单独创建文件不能实现less和js共用一个的效果啊。比如ant这个前缀就不能通过一个配置修改了，得维护两套
