### ISSUE TITLE
2.1.18版本执行docs:build命令自动中断打包，webpack大概完成 building (17%)

### ISSUE THREAD

**Issue by Wukongyang** [umijs/dumi#1594]
**Versions**
dumi：v2.1.18
umi：v4.0.46
node：v16.16.0
npm：v9.1.2

**Step**
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/54463146/229066634-561b3585-f596-40ff-b89e-0ec6e0442d41.png">
执行build命令可正常完成库打包，执行docs:build打包文档时，webpack大概完成 building (17%)，则会自动中断执行，直接退出命令执行

**Solve**
目前的解决方案是固定dumi版本为2.1.17，才能完成打包
望官方及时修复

**Comment by Wukongyang** [comment]
npm：v9.1.2

**Comment by PeachScript** [comment]
在部分设备上可以复现，先回退 latest tag 到 `v2.1.17` 了；不需要锁版本改用 `^2.1.17` 声明即可，这样修复版发布后可以及时生效

**Comment by PeachScript** [comment]
v2.1.19 已修复
