### ISSUE TITLE
新建的组件文档标题会替换原来的导航

### ISSUE THREAD

**Issue by xliez** [umijs/dumi#1596]
### Question

使用 create-dumi 创建的 demo ，默认会将 docs/guide.md 和 src/Foo/index.md 的标题 Foo 作为导航。当我在 src/ 下新建了一个组件 Bar 后， src/Bar/index.md 的标题 Bar 替换掉了导航 Foo。

不清楚这个导航的生成逻辑，如何固定住这边的导航呢

### Sample Code

目录是这样的，Bar 基本是 Foo 的 copy

```
./src
├── Bar
│   ├── index.md
│   └── index.tsx
├── Foo
│   ├── index.md
│   └── index.tsx
├── index.md
└── index.ts

```

**Comment by PeachScript** [comment]
页面名是导航的兜底值，可以通过 FrontMatter 自行控制导航标题：https://d.umijs.org/guide/conventional-routing#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E8%88%AA%E5%88%86%E7%BB%84%E5%92%8C%E6%A0%87%E9%A2%98
