### ISSUE TITLE
如何添加css样式改变dumi默认样式

### ISSUE THREAD

**Issue by danyun123** [umijs/dumi#1597]
![image](https://user-images.githubusercontent.com/100011153/230065076-7963b1f4-da5d-4cc6-ba93-9d320e7d9a46.png)
我在theme/index.css中编写了css代码希望修改首页logo的样式，如何才能成功呢
![image](https://user-images.githubusercontent.com/100011153/230065337-1dfa9b8e-6512-4619-b334-9d7094e4fa2a.png)

**Comment by Elieen-v** [comment]
> ![image](https://user-images.githubusercontent.com/100011153/230065076-7963b1f4-da5d-4cc6-ba93-9d320e7d9a46.png) 我在theme/index.css中编写了css代码希望修改首页logo的样式，如何才能成功呢 ![image](https://user-images.githubusercontent.com/100011153/230065337-1dfa9b8e-6512-4619-b334-9d7094e4fa2a.png)
你好  ，想问一下你是怎么解决的呀

**Comment by danyun123** [comment]
在 .dumi 文件夹下面创建 global.less 或者css 在里面编写的代码就会运用到全局，具体可参考
https://d.umijs.org/guide/faq 中的 “如何添加统计脚本和全局&nbsp;CSS&nbsp;样式？” 一栏





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/dumi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 下午2:41
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [umijs/dumi] 如何添加css样式改变dumi默认样式 (Issue #1597)





  
 我在theme/index.css中编写了css代码希望修改首页logo的样式，如何才能成功呢 
 你好  ，想问一下你是怎么解决的呀

**Comment by Elieen-v** [comment]
![image](https://user-images.githubusercontent.com/110799511/230559277-7abbbfea-2528-409c-91bc-0e8325604fb4.png)
像这样嘛？我的还是不行

**Comment by Elieen-v** [comment]
> 在 .dumi 文件夹下面创建 global.less 或者css 在里面编写的代码就会运用到全局，具体可参考 https://d.umijs.org/guide/faq 中的 “如何添加统计脚本和全局&nbsp;CSS&nbsp;样式？” 一栏
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "umijs/dumi" ***@***.***&gt;; 发送时间:&nbsp;2023年4月7日(星期五) 下午2:41 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [umijs/dumi] 如何添加css样式改变dumi默认样式 (Issue #1597) 我在theme/index.css中编写了css代码希望修改首页logo的样式，如何才能成功呢 你好 ，想问一下你是怎么解决的呀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
![image](https://user-images.githubusercontent.com/110799511/230559542-34a535b2-3193-402d-bdee-49eda97d136d.png)

像这样嘛？我的还是不行

**Comment by danyun123** [comment]
我也是这样设置的呢，你看看控制台有没有设置上，有可能是你设置的样式被覆盖了，就使用 ！important 覆盖试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/dumi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月7日(星期五) 下午3:05
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [umijs/dumi] 如何添加css样式改变dumi默认样式 (Issue #1597)





  
在 .dumi 文件夹下面创建 global.less 或者css 在里面编写的代码就会运用到全局，具体可参考 https://d.umijs.org/guide/faq 中的 “如何添加统计脚本和全局&nbsp;CSS&nbsp;样式？” 一栏
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "umijs/dumi" @.&gt;; 发送时间:&nbsp;2023年4月7日(星期五) 下午2:41 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [umijs/dumi] 如何添加css样式改变dumi默认样式 (Issue #1597) 我在theme/index.css中编写了css代码希望修改首页logo的样式，如何才能成功呢 你好 ，想问一下你是怎么解决的呀 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
 
  
像这样嘛？我的还是不行
