### ISSUE TITLE
bug: useOutlet 等来自 umijs 的 api 丢失类型

### ISSUE THREAD

**Issue by NoDocCat** [umijs/dumi#1598]
### Versions

- dumi: 2.1.19
- node: 18.14.2
- npm: 7.26.2
- OS: Windows 11
- Browser: Edge 111.0.1661.62

### Steps to reproduce

1. 使用官方 cli 创建一个 dumi 主题模板
2. 在代码中尝试 `import { useOutlet } from 'dumi'`
3. 此时 TS 会提示: (TS2305: Module '"dumi"' has no exported member 'useOutlet').

### What is Expected?

类型应该同时被导出

### What is actually happening?

似乎一部分类型被生成到了 `.dumi/tmp/exports.ts` 中:
![image](https://user-images.githubusercontent.com/20502666/230327617-8ce9a64a-f655-49ee-a6fa-d2031436faf3.png)

**Comment by NoDocCat** [comment]
目前的临时解决方法: 在 `tsconfig.json` 中配置 path,  将 `@@/*` 指向 `.dumi/tmp/*`

**Comment by PeachScript** [comment]
@NoDocCat 这个配置是必要的，theme 模板[只在 example 下加了](https://github.com/umijs/dumi/blob/969b83d98021dc65e894cd172468a2738eb26186/suites/boilerplate/templates/theme/example/tsconfig.json.tpl)，有空可以来个 PR 合并到外面
