### ISSUE TITLE
打包以后部署到服务器报错

### ISSUE THREAD

**Issue by danyun123** [umijs/dumi#1602]
![image](https://user-images.githubusercontent.com/100011153/230758661-0f2f756e-9a04-4e1f-bca7-0c90e5778c52.png)

在自己的IDE中运行 npm run dumi项目可以正常跑起来，
部署到服务器以后就报错

**Comment by PeachScript** [comment]
构建产物包含磁盘路径是有问题的，之前修过这个问题，可以安装 dumi 最新版试下，如果不行按照 bug issue 模板提供复现信息
