### ISSUE TITLE
bug: 创建umi4项目后出现的一些问题antd、config

### ISSUE THREAD

**Issue by rookiesBody** [umijs/dumi#1607]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### What is actually happening?
1. 下载umi4项目后，antd menu组件异常不能使用
2. 删除.umirc文件后，config/config.ts 异常不能使用，保留,umirc文件正常
3. 因为第一种情况的出现，所以我自己安装了antd@4 版本后，组件可以使用了但是antd默认样式引入失效
[demo.zip](https://github.com/umijs/dumi/files/11206883/demo.zip)

**Comment by PeachScript** [comment]
Duplicate of https://github.com/umijs/umi/issues/10949
