### ISSUE TITLE
请问有方法在已有项目中添加 dumi 嘛？

### ISSUE THREAD

**Issue by phyzess** [umijs/dumi#161]
### Question

看文档都是用脚手架新起一个项目，如果想要在一个已有项目中引入dumi 来进行项目文档的编写和生成应该怎么做？

项目未使用 umi

**Comment by xiaohuoni** [comment]
这里应该有手动初始化 https://d.umijs.org/guide/getting-started#%E6%89%8B%E5%8A%A8%E5%88%9D%E5%A7%8B%E5%8C%96

**Comment by phyzess** [comment]
我尝试过这个文档里面的 `npm i dumi -D`，packages.json 里配置了script， "dumi:dev: dumi dev"， 然后在根目录下新建了 docs/index.md
但是跑起来以后是一个空白页面

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/80470296-614efe80-8974-11ea-8858-954e4c1f5460.png)
![image](https://user-images.githubusercontent.com/11746742/80470334-7166de00-8974-11ea-9156-d01ddac0cdf8.png)
### package.json
```
{
  "name": "dumi-demo",
  "scripts": {
    "dev": "dumi dev"
  },
  "dependencies": {
    "dumi": "^1.0.20"
  }
}
```
### docs/index.md
```
# 这是什么？

<div style="font-size:50px">Dumi</div>

```

**Comment by xiaohuoni** [comment]
@phyzess cc

**Comment by phyzess** [comment]
@xiaohuoni 那可能是我项目里面有什么问题？
<img width="786" alt="1" src="https://user-images.githubusercontent.com/25143884/80474314-e557b500-8979-11ea-86aa-52b62b1d310f.png">
<img width="335" alt="2" src="https://user-images.githubusercontent.com/25143884/80474345-ec7ec300-8979-11ea-87fb-039f06f50ccc.png">
<img width="1680" alt="3" src="https://user-images.githubusercontent.com/25143884/80474359-f0124a00-8979-11ea-8029-04cb2555d1c1.png">

dev跑起来以后 .umi 下面的目录与脚手架在空目录下起的相比，缺少了一些文件夹
<img width="276" alt="4" src="https://user-images.githubusercontent.com/25143884/80474589-38316c80-897a-11ea-8441-bfc240fb0ce8.png">

**Comment by phyzess** [comment]
@xiaohuoni 那可能是我项目里面有什么问题？
<img width="786" alt="1" src="https://user-images.githubusercontent.com/25143884/80474721-62832a00-897a-11ea-9fd5-92eb70bbb377.png">
<img width="335" alt="2" src="https://user-images.githubusercontent.com/25143884/80474732-66af4780-897a-11ea-84ce-50cf35bb37eb.png">
<img width="1680" alt="3" src="https://user-images.githubusercontent.com/25143884/80474739-69aa3800-897a-11ea-804b-653f46ec960e.png">


dev跑起来以后 .umi 下面的目录与脚手架在空目录下起的相比，缺少了一些文件夹
<img width="276" alt="4" src="https://user-images.githubusercontent.com/25143884/80474589-38316c80-897a-11ea-8441-bfc240fb0ce8.png">

**Comment by xiaohuoni** [comment]
https://github.com/umijs/dumi/pull/163 可以参考这个
## 如何在cra等非 umi 项目中使用 dumi？

安装模块。

```bash
yarn add dumi cross-env -D
```

增加启动命令，修改 `package.json`。

```json
  "scripts": {
    "dumi": "cross-env APP_ROOT=dumi dumi dev",
    "dumi-build": "cross-env APP_ROOT=dumi dumi build"
  },
```

增加配置，新建 `config/config.js`。

```js
export default {
    chainWebpack(memo) {
        memo.plugins.delete('copy');
    },
}
```

新建文档目录 `dumi/docs/`，这里的 `dumi` 目录即第二步中配置的环境变量，你可以随意同步修改。

新建文档 `dumi/docs/index.md`。

```markdown
# 这是一个 Dumi 结合 create-react-app 的 Demo
```

将 dumi 的临时文件添加到 `.gitignore` 中。

```
.umi
```

**Comment by GloriaCHL** [comment]
> 需要等待PR合并，发新版本。#163 可以参考这个
> 
> ## 如何在cra等非 umi 项目中使用 dumi？
> 安装模块。
> 
> ```shell
> yarn add dumi cross-env -D
> ```
> 
> 增加启动命令，修改 `package.json`。
> 
> ```json
>   "scripts": {
>     "dumi": "cross-env APP_ROOT=dumi dumi dev",
>     "dumi-build": "cross-env APP_ROOT=dumi dumi build"
>   },
> ```
> 
> 增加配置，新建 `config/config.js`。
> 
> ```js
> export default {
>     chainWebpack(memo) {
>         memo.plugins.delete('copy');
>     },
> }
> ```
> 
> 新建文档目录 `dumi/docs/`，这里的 `dumi` 目录即第二步中配置的环境变量，你可以随意同步修改。
> 
> 新建文档 `dumi/docs/index.md`。
> 
> ```gfm
> # 这是一个 Dumi 结合 create-react-app 的 Demo
> ```
> 
> 将 dumi 的临时文件添加到 `.gitignore` 中。
> 
> ```
> .umi
> ```
> 
> 主要是 `cross-env APP_ROOT=dumi` 把 dumi 的默认目录和项目的 src 隔离开来。

请问用 antd pro 4 初始化的项目也需要这样配置吗？找了圈好像没有相关的使用说明

**Comment by zhaoyao91** [comment]
> 需要等待PR合并，发新版本。#163 可以参考这个
> 
> ## 如何在cra等非 umi 项目中使用 dumi？
> 安装模块。
> 
> ```shell
> yarn add dumi cross-env -D
> ```
> 
> 增加启动命令，修改 `package.json`。
> 
> ```json
>   "scripts": {
>     "dumi": "cross-env APP_ROOT=dumi dumi dev",
>     "dumi-build": "cross-env APP_ROOT=dumi dumi build"
>   },
> ```
> 
> 增加配置，新建 `config/config.js`。
> 
> ```js
> export default {
>     chainWebpack(memo) {
>         memo.plugins.delete('copy');
>     },
> }
> ```
> 
> 新建文档目录 `dumi/docs/`，这里的 `dumi` 目录即第二步中配置的环境变量，你可以随意同步修改。
> 
> 新建文档 `dumi/docs/index.md`。
> 
> ```gfm
> # 这是一个 Dumi 结合 create-react-app 的 Demo
> ```
> 
> 将 dumi 的临时文件添加到 `.gitignore` 中。
> 
> ```
> .umi
> ```
> 
> 主要是 `cross-env APP_ROOT=dumi` 把 dumi 的默认目录和项目的 src 隔离开来。

这样配置之后，无法引用 src 中的组件

**Comment by xiaohuoni** [comment]
@GloriaCHL umi的项目就不用了吧？这么做是为了规避public中有一个index.html文件，会覆盖产物。pro 初始化的项目，不太理解你的使用场景。

**Comment by xiaohuoni** [comment]
@zhaoyao91 是 @ 别名引用的方式应该不行，你可以在config里面配置一个别名。如果还不行，可以另开一个issues。需要再定位一下。可能是 umi 的问题了。

**Comment by GloriaCHL** [comment]
> @GloriaCHL umi的项目就不用了吧？这么做是为了规避public中有一个index.html文件，会覆盖产物。pro 初始化的项目，不太理解你的使用场景。

就是我的项目是从 ant design pro 开始的意思。想弄个组件管理平台，之前考虑storybook，不过发现生态不同太难了，然后就看到umi有对应的dumi，就想说在ant design pro 4的项目里加个dumi做组件管理。

可以给个在 ant design pro 使用的方案吗？按你上面那个方案是可以运行的，但有上面那位兄台@zhaoyao91 的问题，不能别名，只能绝对路径。所以觉得不是很优雅。

**Comment by xiaohuoni** [comment]
应该可以使用别名的吧？只是不能使用内置的 `@`,因为内置的 @ 对应的是src，使用 APP_ROOT=dumi 之后，可能就是 dumi/src，但是你期望的应该是 上一层的 src 。可以尝试一下添加一个别名 ，对应到 src 目录。不知道，重复定义 @ 会不会覆盖原来的。 https://umijs.org/zh-CN/config#alias

**Comment by GloriaCHL** [comment]
> 应该可以使用别名的吧？只是不能使用内置的 `@`,因为内置的 @ 对应的是src，使用 APP_ROOT=dumi 之后，可能就是 dumi/src，但是你期望的应该是 上一层的 src 。可以尝试一下添加一个别名 ，对应到 src 目录。不知道，重复定义 @ 会不会覆盖原来的。 https://umijs.org/zh-CN/config#alias

这个我试过的，别名指向dumi文件夹里的目录，为了回避'@'用的是'$$'，没成。

![image](https://user-images.githubusercontent.com/10557315/81249197-a9df7980-9050-11ea-9e12-a244f76b7bc8.png)

![image](https://user-images.githubusercontent.com/10557315/81249226-bebc0d00-9050-11ea-9782-ec280f9e82e2.png)

感觉最好的场景还是像项目里的 model 文件那样可以自己嗅探出来组织。不过如果目前还无法做到的话，也只能先写绝对路径了。

可以总结性地说下 ant design pro 里怎么使用 dumi 吗？上面说了那么多太零散了，容易迷糊。还是说依然是使用上面说的 cra 那种方法就可以了？

**Comment by GloriaCHL** [comment]
我按照上面所说的CRA方法在 ant design pro 里建了个 dumi 文件夹，在里面构建了个dumi服务。用绝对路径引用主项目的tsx文件没问题，但是tsx文件中的别名引用组件就识别不了，报了错。
![image](https://user-images.githubusercontent.com/10557315/81518350-5a5ebd80-9370-11ea-9c4b-3f527a401cfe.png)
这个有什么办法解决吗？

**Comment by PeachScript** [comment]
默认 `@` 是指向 `{cwd}/src` 的，如果嵌套到子文件夹下，需要手动配置 config.alias 为 `{ '@': path.join(__dirname, '../../src') }`

**Comment by GloriaCHL** [comment]
> 默认 `@` 是指向 `{cwd}/src` 的，如果嵌套到子文件夹下，需要手动配置 config.alias 为 `{ '@': path.join(__dirname, '../../src') }`

按你说的设置可以通过别名拿到dumi外部的组件了，但是又来了个新的错误╮(╯▽╰)╭

![image](https://user-images.githubusercontent.com/10557315/81534188-31532280-939a-11ea-8962-b2ab94645265.png)

如果把组件移到 dumi 文件夹内部是没问题的。

**Comment by hopperhuang** [comment]
借楼同问，我现在有一个umi项目(web项目,非组件库)，想通过dumi 为项目添加文档说明，请问我该如何配置，有相关的文档说明否？
@xiaohuoni

**Comment by PeachScript** [comment]
看起来成了个棘手的问题…这周试试看，可行的话出个 example

**Comment by ThinCats** [comment]
> 借楼同问，我现在有一个umi项目(web项目,非组件库)，想通过dumi 为项目添加文档说明，请问我该如何配置，有相关的文档说明否？
> @xiaohuoni

前面的步骤和上面一样，创建dumi文件夹，作为dumi的APP_ROOT
只不过要注意三点
  1. 如果需要在dumi内使用umi项目的组件，需要向webpack添加一些rule，参考 #151 
  2. 经过个人测试，要想在dumi中使用alias @，直接在config.alias里设置是失败的，最好手动在`chianWebpack`里设置，参考代码

in `dumi/.umirc.ts`
```ts
export default defineConfig({
    // other config entry
    chainWebpack(memo) {
      memo.module
        .rule('js')
        .include.add(resolve(__dirname, '..'))
        .end()
        .exclude.add(/node_modules/)

      memo.resolve
        .alias
        .set('@', resolve(__dirname, '../src'))
    }
})
```
  3. 如果失败，尝试修改主项目`.umirc.ts`中的`config.nodeModulesTransform.type = 'all'`，提高兼容性，可见 https://umijs.org/zh-CN/config#nodemodulestransform-31

分离有一个好处，主项目与dumi项目生成的`src/.umi`不会相互影响

**Comment by xjl271314** [comment]
现有项目中集成已经跑了起来了,但是再dumi下的components中引用原有项目的组件报错了。

import AppTipBanner from 'components/AppTipBanner';

![image](https://user-images.githubusercontent.com/20588030/91843472-5c82ba00-ec88-11ea-8813-58c6e342f957.png)

![image](https://user-images.githubusercontent.com/20588030/91843511-6efcf380-ec88-11ea-84da-5e1b4cd3b5f0.png)

想要加载原有项目中的组件 需要手动去配置loader么?

**Comment by xiaohuoni** [comment]
看起来这个配置会有用
```js
import { join } from 'path';
export default {
  chainWebpack: (config: any) => {
    config.module
      .rule('js')
      .test(/\.(js|mjs|jsx|ts|tsx)$/)
      .include.add(join(__dirname, '..', '..', 'src')).end()
      .exclude.add(/node_modules/).end()
      .use('babel-loader')
  },
  alias: {
    'xxx': join(__dirname, '..', '..', 'src')
  }
};
```

**Comment by xjl271314** [comment]
@xiaohuoni 是的昨天我加上这个配置 并单独抽离出来加载 可以使用了 感觉现有的文档还有有些简单 一些问题不太好查阅。

顺便问下 我在     extraBabelPlugins: []中配置的 ES11相关语法的plugin 实际并没有起作用 

![image](https://user-images.githubusercontent.com/20588030/91967467-dd53bb80-ed45-11ea-9772-c55f52cb10d1.png)

**Comment by NuoHui** [comment]
这里这么配置chainWebpack可以解析我项目中都ts、less类型文件呢。

**Comment by dream-approaching** [comment]
![](https://raw.githubusercontent.com//dream-approaching/pictureMaps/master/img/20201113093729.png)
按照配置配完，效果是可以的，只是为什么会自动生成`node_modules`并且好像死循环了，虽然只是快捷方式，但还是看着很别扭

还有一个疑问：这种方式我要怎么把组件放入dumi-lib中引用？

**Comment by xydegithub** [comment]
> ![](https://raw.githubusercontent.com//dream-approaching/pictureMaps/master/img/20201113093729.png)
> 按照配置配完，效果是可以的，只是为什么会自动生成`node_modules`并且好像死循环了，虽然只是快捷方式，但还是看着很别扭
> 
> 还有一个疑问：这种方式我要怎么把组件放入dumi-lib中引用？

真的是循环嵌套！

**Comment by xiaohuoni** [comment]
@dream-approaching 兄弟，你这给一个重现库，我看看，应该是bug。正确的表现不是这样子的

**Comment by xydegithub** [comment]
> @dream-approaching 兄弟，你这给一个重现库，我看看，应该是bug。正确的表现不是这样子的

直接用npx @umijs/create-dumi-lib生成的就有这个问题，node_modules里循环的展示了；还有demo写在md里，react好像引不了，导致createelement方法为空报错
![Uploading image.png…]()

**Comment by xiaohuoni** [comment]
别用demo文件夹试试。

**Comment by xydegithub** [comment]
不用demo也不行啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "umijs/dumi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 下午5:33
收件人:&nbsp;"umijs/dumi"<dumi@noreply.github.com&gt;;
抄送:&nbsp;"凌霄云"<895077746@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [umijs/dumi] 请问有方法在已有项目中添加 dumi 嘛？ (#161)





 
别用demo文件夹试试。

**Comment by xydegithub** [comment]
> 没复现出来，别用demo文件夹试试。

不用demo也不行啊

**Comment by xiaohuoni** [comment]
给个在线库吧？

**Comment by dream-approaching** [comment]
> 按照配置配完，效果是可以的，只是为什么会自动生成`node_modules`并且好像死循环了，虽然只是快捷方式，但还是看着很别扭
> 给个在线库吧？

我之前有问题这个项目分支废弃了，刚刚重新在cra项目中按照上面的文档添加dumi，发现问题可能出现在windows下，因为公司的电脑是windows的
- 用windows系统：执行`npm run dumi`后，**`node_modules`下循环嵌套了**
- 用windows下的linux子系统：执行`npm run dumi`后，`node_modules`正常

我把这个demo放github仓库了：https://github.com/dream-approaching/dumi-loop-demo

<br />
我有一些其他疑问可以帮忙看下吗 @xiaohuoni   

### 场景(在cra项目中使用dumi)
- 在cra项目中`package.json` 的 `script`中新增
  ```json
  "dumi": "cross-env APP_ROOT=dumi dumi dev",
  "dumi-build": "cross-env APP_ROOT=dumi dumi build",
  ```
- 在根目录新建`dumi`文件夹
- .......(参考上方的文档步骤，不一一列出了)

### 疑问
- 1、在其他issus中看到，[package.json需要添加`dumi-lib`](https://github.com/umijs/dumi/pull/257/commits/7d5a65e91a257859bb7862a611c51ef54032c5a1)，应该是添加到根目录的 `package.json` 中吗，还是要在 `dumi` 文件夹下新建 `package.json` 文件再安装 `dumi-lib` ？我暂时是放在根目录下了
- 2、在`dumi/components`新建了一个组件 `Com` ，然后在 `index.js` 中导出，最开始用`dumi`的时候，是可以通过 `import { Com } from 'dumi-lib';` 引用 `Com`组件 的，但是在当前项目下不行了，还会报错 `Can't resolve './locale' in '**/**/**/node_modules/dumi-lib/dist'` ，网上说要安装 `moment` ，但试了还是不行，可以帮忙解答下吗
![image](https://user-images.githubusercontent.com/22695534/109097235-ec964d80-7759-11eb-84bc-2f6703eb40bf.png)

**Comment by PeachScript** [comment]
循环软连接是正常情况，这是 dumi 为了确保 `import x from '组件库包名'` 能找到正确的 TS 类型定义做的处理

`dumi-lib` 只是个代称，并非需要安装的依赖，实际上是我们自己的组件库名称

其他问题请另开 issue 提出

**Comment by xiaohuoni** [comment]
我一直想重现这个图片中的情况，没成功。
![](https://raw.githubusercontent.com//dream-approaching/pictureMaps/master/img/20201113093729.png)

**Comment by xiaohuoni** [comment]
这个issues 太长了。还有问题的，提供在线仓库，重新提个新的issues吧。
