### ISSUE TITLE
bug: base 不为 / 时切换多语言浏览器地址错误

### ISSUE THREAD

**Issue by Wxh16144** [umijs/dumi#1614]
https://user-images.githubusercontent.com/32004925/231829090-946daf48-40f4-4be7-bba0-6153317f9770.mp4

### Versions

- dumi: 2.1.20
- node: 16.x
- npm: 8.x
- OS: OSX 13
- Browser: chrome 112

**Comment by PeachScript** [comment]
v2.1.21 已发布
