### ISSUE TITLE
dumi-theme-mobile@2.0.4 安装后启动后报错

### ISSUE THREAD

**Issue by sunweibin** [umijs/dumi#1620]
### Question
dumi-theme-mobile@2.0.4 安装后启动后报错

Variable @desktop is undefined

### Sample Code
dumi@2.0.2

**Comment by sunweibin** [comment]
这个我使用pnpm不行，使用yarn运行就可以

**Comment by PeachScript** [comment]
`pnpm up -L` 一下，pnpm v8 开始默认用声明的最低版本导致了这个问题
