### ISSUE TITLE
.dumirc.ts文件中defineConfig里面的配置项到底哪些用umi进行组件的编译

### ISSUE THREAD

**Issue by sunweibin** [umijs/dumi#1622]
### Question
使用【extraPostCSSPlugins】该配置项时，直接把文档给处理了

比如：我这边需要将组件的less编译时，经过【postcss-pxtorem】插件
将src下组件的less中px转成rem，没用

**Comment by PeachScript** [comment]
`.dumirc.ts` 的配置项同时作用与文档和组件 demo，无法拆分；建议不使用插件、写的时候通过 less var 去处理成 rem

**Comment by xiazanzhang** [comment]
可以忽略dumi的样式转换，比如：
