### ISSUE TITLE
自动API 总是提示  未找到 XXX 组件的属性定义

### ISSUE THREAD

**Issue by juntity** [umijs/dumi#1629]
### Question
也不清楚是配置问题还是写法问题， 自动 API 总是出不来

dumi v2.1.22
### Sample Code
组件
`import React, { FC } from "react";
import { createFromIconfontCN } from "@ant-design/icons";

export interface IconProps {
    type?: string,
    style?: React.CSSProperties,
    [key: string]: any
}

const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/c/font_3302712_zruvxur74tl.js',
});

const MSIcon:FC<IconProps> = (props: IconProps) => {
    const type = props.type || "";
    const style = props.style || {};
    return <IconFont type={type} style={style} {...props} />;
}
export default MSIcon;`

文档
`<API></API>` 
或
`<API id="MSIcon"></API>`
都出不来

**Comment by PeachScript** [comment]
Duplicate of #1476

**Comment by PeachScript** [comment]
如果不是 Windows 系统，在上面的 issue 里提供复现信息；如果是 Windows 系统，目前解析器存在系统兼容性问题，需要等后续支持后才能使用
