### ISSUE TITLE
静态部署后页面白屏

### ISSUE THREAD

**Issue by huyinglin** [umijs/dumi#1630]
### Question
使用 dumi 1.x 的相同配置升级为 dumi 2.x 后，静态资源部署后页面白屏，不是404。资源加载没有问题，资源除了下面的 `/127.0.0.1:64555/api/basic`接口报错，其他的资源都能加载出来，如首页的 index.html 和首页中需要的 js 和 css 资源都能加载出来，但页面就是白屏。这个报错的接口不是业务代码，在打包产物中也搜索不到。控制台除了接口加载报错，没有其他报错。
![image](https://user-images.githubusercontent.com/30167928/234457987-fcb54e9a-7a4b-4d85-becc-f84f74f429eb.png)

### Sample Code
.dumirc.ts 配置如下：
```
import { defineConfig } from 'dumi';

export default defineConfig({
  resolve: {
    entryFile: './src/index.ts',
  },
  outputPath: process.env.BUILD_DEST || 'docs-dist',
  // 引入 fusion 主题
  styles: [
    'https://gw.alipayobjects.com/os/lib/alife/theme-tgc-pro/2.0.1/dist/next-noreset.css',
    'https://gw.alipayobjects.com/os/lib/alife/theme-tgc-pro/2.0.1/dist/next-noreset.var.css',
  ],
  base: '/components/',
  publicPath:
    process.env.NODE_ENV === 'production'
      ? `https://dev.g.alicdn.com/c2m-goldrooster/jinji-materials/`
      : '/',
  manifest: {},
  exportStatic: {},
  sassLoader: {},
  themeConfig: {
    name: 'Jinji Design',
    hero: {
      title: 'Jinji Design',
      description: 'Extension Component Library Based on Fusion',
      actions: [{ text: '开始使用', link: '/guide' }],
    },
    features: [
      { title: '开箱即用' },
      { description: '接入简单，安装即使用，全面融入 Ant Design 5.0 风格。' },
    ],
  },
});

```

**Comment by PeachScript** [comment]
没有错误的白屏大概率是 base 配置不正确导致 react-router 无法正常处理路由导致的，参考 FAQ 检查下 base 配置：https://d.umijs.org/guide/faq#%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95%E9%83%A8%E7%BD%B2

**Comment by Js-Man-H5** [comment]
![image](https://github.com/umijs/dumi/assets/62057975/83259073-6a6e-4025-98c5-d360f0a2f697)
![image](https://github.com/umijs/dumi/assets/62057975/9e2c24eb-ed5c-46dc-a450-08c1a35cc604)
设置了base打包之后就是没有、就离谱
