### ISSUE TITLE
dumi2.0: resolve.excludes 不支持配置了吗？如何排除不想被解析的md文件？

### ISSUE THREAD

**Issue by jiaolongshenme** [umijs/dumi#1635]
### Question
resolve.excludes 不支持配置了吗？如何排除不想被解析的md文件？
### Sample Code
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/22339560/235094976-ab3454c7-ff93-4b7d-a250-3a33febbd8a4.png">

**Comment by PeachScript** [comment]
不支持，按标准目录结构来是用不到 `excludes` 的，不应该从项目根目录开始解析 Markdown
