### ISSUE TITLE
bug: API表格未能正确渲染ts中定义的null属性

### ISSUE THREAD

**Issue by leegsen7** [umijs/dumi#1638]
dumi@2.1.22

```ts
interface IProps {
  msg: string | null
}
```
![image](https://user-images.githubusercontent.com/15691486/236107777-456c1210-55d1-4a05-bdcd-c42d15f9caf8.png)

**Comment by PeachScript** [comment]
v2.1.23 已修复，感谢 @windyrain 提交 PR ❤️
