### ISSUE TITLE
在已有项目里手动初始化dumi后，引入antd的button后的效果和预期不符

### ISSUE THREAD

**Issue by AnnaSearl** [umijs/dumi#164]
### Question
在已有项目里手动初始化dumi后，引入antd的button后的效果和预期不符，发现是没有引入antd的样式导致的，文档里好像没有提到如何引入样式，请问怎么解决
具体显示情况请点击下面的图片链接查看
[点击此处查看截图](https://smebimage.fuliaoyi.com/Fi0vpAjBJNPOkvM0zgJ4rTSczi46)
### Sample Code
`import React from 'react';`
`import { Button } from 'antd';`
`export default () => <Button type="primary">aa</Button>;`

**Comment by PeachScript** [comment]
两个解法，手动引入样式表或者启用 babel-plugin-import，可参考 dumi 的 config/config.js 或者 `antd` 的文档：https://ant.design/docs/react/getting-started-cn#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
