### ISSUE TITLE
全局自动搜索报错，无法正常使用

### ISSUE THREAD

**Issue by fengbozhi** [umijs/dumi#1640]
全局自动搜索输入关键字，控制台报错，搜索面板无法正常弹出
![image](https://user-images.githubusercontent.com/19235574/236416375-e8738e44-0ea9-473a-ab26-c0b215aea3a1.png)

### Versions

- dumi: 2.0.2
- node: 16.16.0
- npm: 8.11
- OS: windows
- Browser: chrome  112.0.5615.138（正式版本） （64 位）
- react: 16.9.0
- react-dom: 16.9.0

### Steps to reproduce
搜索框输入关键字
### What is Expected?
正常弹出搜索结果
### What is actually happening?
无法显示搜索结果

**Comment by PeachScript** [comment]
官网搜索是没问题的，复现步骤是指『别人按照你的步骤能在自己的环境里复现』

**Comment by fengbozhi** [comment]
找到原因了，devDependencies中的react\react-dom版本不能低于17
