### ISSUE TITLE
bug: Module not found: Error: Can't resolve 'nprogress' in '\.dumi\tmp\dumi\theme'

### ISSUE THREAD

**Issue by Emily-0616** [umijs/dumi#1655]
### Versions

- dumi: 2.1.23
- node: 16.5.1
- npm: 8.11.0
- OS: win11
- Browser: chrome版本 113.0.5672.93（正式版本） （64 位）

### Steps to reproduce
 - npx create-dumi
 - Static Site
 - pnpm
 - /
 - /
 - /
 
安装完依赖以后 pnpm start 就出现这个错误了。
![image](https://github.com/umijs/dumi/assets/32790186/671b9880-9152-43d3-9b36-72b324806137)

**Comment by PeachScript** [comment]
上个版本幽灵依赖了，两个临时方案：
1. 禁用 `themeConfig.nprogress`
2. 暂时用 npm 安装依赖

**Comment by PeachScript** [comment]
v2.1.24 已修复
