### ISSUE TITLE
bug: 设置 themeConfig.name 无效，左上角标题设置不进去

### ISSUE THREAD

**Issue by liaoyongfu** [umijs/dumi#1658]
### Versions

- dumi: v2.1.23
- node: v16.20.0
- npm: 8.19.4
- OS:
- Browser:

### Steps to reproduce
在项目中手动引入了 dumi，配置文件如下：
```js
import { defineConfig } from 'dumi';

export default defineConfig({
    chainWebpack(memo) {
        memo.plugins.delete('copy');
    },
    resolve: {
        docDirs: ['docs', 'src', 'README.md']
    },
    themeConfig: {
        name: 'test-component',
    }
});
```
### What is Expected?
![image](https://github.com/umijs/dumi/assets/7555071/7871a6e8-2620-4bd5-91cc-e3d1d1d81a42)
期望标题能设置进去
### What is actually happening?
标题设置不上去

**Comment by PeachScript** [comment]
请提供最小可复现仓库

**Comment by liaoyongfu** [comment]
打扰了，一开始按文档：https://d.umijs.org/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi
的方法引入发现不行。

后面把 `.dumirc` 改成 `.dumirc.js` 就可以了，虽然不知道为啥

**Comment by PeachScript** [comment]
`.dumirc.js` 或 `.dumirc.ts` 才是有效配置文件，已更正文档，感谢反馈
