### ISSUE TITLE
能直接使用css Modules方式在组件中导入样式表吗？

### ISSUE THREAD

**Issue by Lands-1203** [umijs/dumi#1663]
### Question
我在组件中使用css Modules方式导入样式表出错，导入进来的对象没有内容
![image](https://github.com/umijs/dumi/assets/61341868/9d849729-99c1-47da-80e9-99ff510986c3)
![image](https://github.com/umijs/dumi/assets/61341868/3cac64e8-1b07-48f4-8d95-8549d5b8d87a)
 
请问dumi有没有配置lessloader？我查看文档好像是自动支持4版本，但是不能导入，并且自己配置了webpack也不行

**Comment by PeachScript** [comment]
不行，dumi 2 不再支持 CSS Modules，参考：https://d.umijs.org/guide/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%94%AF%E6%8C%81-css-modules
