### ISSUE TITLE
bug: Module does not exist in container

### ISSUE THREAD

**Issue by vaynevayne** [umijs/dumi#1668]
<img width="1092" alt="image" src="https://github.com/umijs/dumi/assets/124666577/c38e5a6d-7750-41ff-848c-3f46d7a29eb1">

**Comment by PeachScript** [comment]
请重新按模板提供完整复现步骤及复现仓库，这是 bug 类 issue 的必要内容，该 issue 关闭

**Comment by vaynevayne** [comment]
用着用着就这样了

**Comment by AttackXiaoJinJin** [comment]
@PeachScript  dumiV2.3.2 的确有这个bug，但是 V2.2.17 却没有，你可以本地跑下这个项目：https://github.com/react-component/virtual-list

https://github.com/react-component/virtual-list/blob/master/package.json#L54

里面标注的是`"dumi": "^2.2.17",`，根据 ^ 实际安装版本是 2.3.2，运行 pnpm start 报错：

![image](https://github.com/umijs/dumi/assets/26433572/46fa90f5-31e2-4399-a299-669f0efe43ec)

![image](https://github.com/umijs/dumi/assets/26433572/a551bb33-2c78-432d-8d56-6959d992ed32)


改称`"dumi":"2.2.17"`，pnpm i，再跑就没有错误了：

![image](https://github.com/umijs/dumi/assets/26433572/68d30823-1a19-4d67-afe5-6a6cb7170712)


![image](https://github.com/umijs/dumi/assets/26433572/6f2aafa4-f130-49f5-95ca-3fda62ea8b3a)

**Comment by jeffwcx** [comment]
@AttackXiaoJinJin  你这个问题和原问题应该不是一个问题，应该是 mfsu 没处理好引发的问题，我这边关掉mfsu就好了。建议你另外开一个issue，我们这边会处理
