### ISSUE TITLE
在demo中无法导入组件

### ISSUE THREAD

**Issue by AnnaSearl** [umijs/dumi#167]
### Question
在demo中无法导入组件，编译提示需要install组件，但是我明明已经install了,package.json的dependencies中也已经包含anna-remax-ui了，请问该如何解决这个问题
### Sample Code
编译错误提示：To install it, you can run: npm install --save anna-remax-ui

// button.md
Demo:
`<code src="./button/button.tsx" />`

//button.tsx
`import * as React from 'react';`
`import { Card } from 'anna-remax-ui';`
`export default () => <Card title="商品信息">内容</Card>`

**Comment by PeachScript** [comment]
`anna-remax-ui` 是你的组件库包名吧？确保 package.json 的 `name` 是 `anna-remax-ui` 然后重新启动 dumi 即可

**Comment by AnnaSearl** [comment]
> `anna-remax-ui` 是你的组件库包名吧？确保 package.json 的 `name` 是 `anna-remax-ui` 然后重新启动 dumi 即可

可是我的package.json 的 name 原本就是 anna-remax-ui
