### ISSUE TITLE
bug: Preprocessor dependency "less" not found. Did you install it

### ISSUE THREAD

**Issue by vaynevayne** [umijs/dumi#1670]
在执行 yarn run build 的时候 不会编译less吗?  
 
 使用它的项目报错了
 

<img width="621" alt="image" src="https://github.com/umijs/dumi/assets/124666577/9b338c57-3d70-42eb-9559-cb0b9d94357c">

<img width="969" alt="image" src="https://github.com/umijs/dumi/assets/124666577/23a58249-2c24-4e0f-aad8-207271b7cd89">

这个问题我应该怎么解决呢?

**Comment by PeachScript** [comment]
源码打包相关问题看 father 文档：https://github.com/umijs/father/blob/master/docs/guide/build-mode.md

相关 issue：https://github.com/umijs/father/issues/514#issuecomment-1333691752
