### ISSUE TITLE
目前是如何配置 Logo 和 footer 的内容

### ISSUE THREAD

**Issue by Alicehhhmm** [umijs/dumi#1675]
### Question
如何在 .dumirc.ts 中配置 Logo 和 footer 内容

### Sample Code
目前配置如下（无效）
```ts
import { defineConfig } from 'dumi';

export default defineConfig({

  themeConfig: {
      logo: '/public/logo.svg',
      footer:  'Copyright (c)'
  },

});
```

**Comment by PeachScript** [comment]
`logo` 路径可能不对，如果是要用本地文件，参考文档的说明：https://d.umijs.org/theme/default#logo
`footer` 配法没问题，如果不生效提供下复现仓库及复现步骤
