### ISSUE TITLE
生成移动端组件文档时px未转换，导致px为正常的两倍大

### ISSUE THREAD

**Issue by AnnaSearl** [umijs/dumi#168]
### Question
我尝试在umirc.ts文件中配置
`extraPostCSSPlugins: [
    require('postcss-px2units')({
      targetUnits: 'px',
      divisor: 2,
    })
  ],`
但是发现虽然移动端组件px转换成功了，但是整个网站的尺寸也被转换成原来的1/2了，如下图所示，请问这个有什么办法解决

[点击查看图片](https://smebimage.fuliaoyi.com/FsyUABkAnmbCoWiajFJUl30hTcNC)

**Comment by PeachScript** [comment]
目前对移动端组件开发确实不友好，属于 #63 中需要优化的点，可以试下这个能加 exclude 目录的插件，把 @umijs/preset-dumi 的包路径做忽略：https://github.com/jadepam/postcss-plugin-px2units

**Comment by AnnaSearl** [comment]
> 目前对移动端组件开发确实不友好，属于 #63 中需要优化的点，可以试下这个能加 exclude 目录的插件，把 @umijs/preset-dumi 的包路径做忽略：https://github.com/jadepam/postcss-plugin-px2units

这个插件的功能好像是高度还原设计稿的，没有根据比例缩放的功能。。。

**Comment by AnnaSearl** [comment]
用postcss-plugin-px2rem解决了，谢谢大佬解答

**Comment by ChenYCL** [comment]
> ### Question
> 我尝试在umirc.ts文件中配置
> `extraPostCSSPlugins: [ require('postcss-px2units')({ targetUnits: 'px', divisor: 2, }) ],`
> 但是发现虽然移动端组件px转换成功了，但是整个网站的尺寸也被转换成原来的1/2了，如下图所示，请问这个有什么办法解决
> 
> [点击查看图片](https://smebimage.fuliaoyi.com/FsyUABkAnmbCoWiajFJUl30hTcNC)

你好，同问题，请问你用postcss-plugin-px2rem 是只针对组件部分源码进行替换么，有开源配置么
