### ISSUE TITLE
bug: doc下文件重命名直接报错退出，让手动删除.dumi 

### ISSUE THREAD

**Issue by AliSnowaroma** [umijs/dumi#1680]
dumi 2.1.22 
使用脚手架创建的dumi项目，doc下文件重命名直接报错退出，让手动删除.dumi 
集成度太高，反而导致反感

### Versions

- dumi: 2.1.22
- node:
- npm:
- OS:
- Browser:

**Comment by PeachScript** [comment]
请按 issue 模板补充复现步骤及相关信息

**Comment by AliSnowaroma** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，谢谢
