### ISSUE TITLE
bug: html2sketch 需要node版本>=16.0.0

### ISSUE THREAD

**Issue by QDyanbing** [umijs/dumi#1681]
<img width="859" alt="image" src="https://github.com/umijs/dumi/assets/66234749/20a61bb8-21bc-402b-9775-308851c1c691">

### Versions

- dumi: 2.1.14
- node: 14.18.0
- npm:
- OS:
- Browser:

**Comment by PeachScript** [comment]
临时方案：升级 Node.js 或者安装的时候 `--ignore-engines`

**Comment by PeachScript** [comment]
@arvinxx html2sketch 能把 engines 依赖降到 14 和 dumi 2 保持一致吗，dumi 提供的 API 需要用到 html2sketch 导出的类型

**Comment by arvinxx** [comment]
> @arvinxx html2sketch 能把 engines 依赖降到 14 和 dumi 2 保持一致吗，dumi 提供的 API 需要用到 html2sketch 导出的类型

ok

**Comment by arvinxx** [comment]
@QDyanbing 试试重装依赖
