### ISSUE TITLE
怎么增加百度统计的代码？

### ISSUE THREAD

**Issue by tangtaoit** [umijs/dumi#1682]
### Question
感谢开源出这么好的文档系统，我现在遇到个问题，麻烦指点下，
发现2.0 没有index.html文件了 index.html是自动生成的，我现在需要加script到index.html里，应该怎么弄？

**Comment by tangtaoit** [comment]
找到了 headScripts可以配置。

**Comment by PeachScript** [comment]
可以直接用框架提供的配置：https://d.umijs.org/config#analytics
