### ISSUE TITLE
关于软换行处理的疑问

### ISSUE THREAD

**Issue by NoDocCat** [umijs/dumi#1683]
### Question

当前 dumi 在解析 markdown 时使用了 `remarkBreaks` 支持了软换行, 但是这种处理一般在较短的文本输入下才开启, 例如: issues, pull request 等.
而在编写开发文档时会经常有大段的文字出现, 强制要求写成一行不利于阅读. 且大部分开发场景下, 不会额外去为了 md 单独配置文本超长不换行.
这个行为是否应该增加一个配置项用来开关? 且默认应该被关闭

**Comment by PeachScript** [comment]
> 强制要求写成一行不利于阅读

我在 VSCode 里试了下文字超过一行时会自动换行展示的，也没有针对 .md 额外配置内容，是不是和你的配置有关系

> 这个行为是否应该增加一个配置项用来开关? 且默认应该被关闭

这是为了与 GitHub 的行为保持一致，否则同一份文档在网站中和 GitHub 上的换行效果是不一致的，我的看法是应该保持现状

**Comment by NoDocCat** [comment]
vscode 的换行应该只是显示上的, 在文件中并没有换行符. 但很多情况下会被要求一行不超过 80 / 120 个字符.
例如使用 `prettier` 的情况, 就得必须为 md 文件单独设置 `proseWrap: preserve`. 否则的话到达一定宽度的行会被插入换行符.

而且在 GitHub 中, 只有 issue 和 pull request 这种短文本会开启软换行, 在展示代码中的 markdown 时是不开启软换行的:

![image](https://github.com/umijs/dumi/assets/20502666/a676bfd6-c87f-4cd2-b22d-889b13783dd7)
![image](https://github.com/umijs/dumi/assets/20502666/1dc8df46-9d3d-4ca8-b05f-900cfe4bfa05)

**Comment by NoDocCat** [comment]
总结来说, GitHub 的策略是如果内容来自用户在页面上的输入, 则换行尽量保持与用户一致. 如果内容来自 md 文件, 则遵循标准的 md 换行规则.

**Comment by PeachScript** [comment]
我之前不清楚 GitHub 这个细节，感谢补充，目前看的确不处理软换行更合理，但考虑到对已有项目存在 Breaking Change，可能还是提供配置项禁用更稳妥？

> 必须为 md 文件单独设置 `proseWrap: preserve`

这个在 dumi 2 里其实是必要的，否则 demo 分栏语法在自动格式化的情况下就会失效，脚手架里的 prettier 配置也默认加上了这条

**Comment by PeachScript** [comment]
思考了一下，这其实是个脱离社区规范的行为，不太希望它继续存在 dumi 2 的整个版本周期，并且也不希望未来的增量应用继续使用这个行为，我的想法是做和[约定式二级导航向前兼容](https://github.com/umijs/dumi/pull/1679)类似的方案：
1. 不开设配置项，基于 `devDependencies` 里的 dumi 版本来判断，高于指定版本则默认去掉 `remark-breaks`（正好 dumi 2.2 刚刚发布，仍然可以以 `^2.2.0` 作为判断依据）
2. （非必须，如果可行的话）在 `remark-breaks` 插件之前对存量项目中的类似用法做检测，提示开发者版本声明高于 2.2.0 后就会去掉该行为，升级时可以选择更改用法 or 打开配置项（`resolve.transformSoftBreaks`）保留用法

这样脚手架新建的应用初始版本声明就是 `^2.2.0`，可以确保增量不继续使用该行为；另外存量应用在手动升级版本号声明之前也不会受影响，你看下这个方案是否合适？

**Comment by NoDocCat** [comment]
第二个需求很好实现, 因为 `remark-breaks` 的实现就是发现 `\n` 之后往 AST 里塞一个 break 节点, 完全可以自己写一个带弃用提醒的 `remark-breaks`. 在塞入 break 节点的同时输出弃用信息.
但是这个根据版本判断是否有必要呢? 因为只要他升级肯定就是新的行为, 不升级肯定就是老的行为. 我的想法是在 `2.2.x` 这个周期里保持现有行为但发出弃用警告, 等到 `2.3.0` 版本的时候再去掉这个自定义插件就 ok 了.
唯一麻烦的是弃用警告的出现时机, 不能太频繁, 但必须能让用户注意到这个问题.

**Comment by PeachScript** [comment]
> 我的想法是在 `2.2.x` 这个周期里保持现有行为但发出弃用警告, 等到 `2.3.0` 版本的时候再去掉这个自定义插件就 ok 了.

我们理解的版本周期可能不太一样，我是指基于 package.json 里声明的依赖版本作为判定依据而非 `node_modules` 下的安装版本，这样有两个作用：
1. 增量项目的声明默认是 `^2.2.0`，所以是新行为，不会继续增量旧行为的应用
2. 存量项目的声明默认是 `^2.0.0`，所以是旧行为，它只要不升级声明的版本号，都不会受影响，当然我们也可以告知在 2.3.0 发布时这个向前兼容的逻辑将会去掉，避免把这个逻辑一直拖着走

> 唯一麻烦的是弃用警告的出现时机, 不能太频繁, 但必须能让用户注意到这个问题.

这个应该可以借用持久缓存实现，把当前时间（例如月份或者周）作为 cacheKey 的一部分

**Comment by PeachScript** [comment]
> 发现 `\n` 之后往 AST 里塞一个 break 节点

这里我不确定能不能精准提示，比如我的确是用的两个换行，但这两个 `\n` 应该也会被它命中替换成 break，理想情况是只对段落之间一个换行的情况做检测，另外换行也有可能存在于列表项之间、代码块里，不知道会不会误伤

**Comment by NoDocCat** [comment]
我看了一下 #1679 , 明白你的设计了, 我认为可以按照这方法去做. 
至于 \n 匹配的方法是不是会误伤, 我在写的时候去实验一下, 如果不行的话那就得研究一下 remark 的 AST 了.

**Comment by PeachScript** [comment]
v2.2.1 已发布
