### ISSUE TITLE
支持配置 Demo 预览区域的按钮

### ISSUE THREAD

**Issue by guoyang007** [umijs/dumi#169]
如题

**Comment by PeachScript** [comment]
不会自动上传，只是展示了在 codesandbox 打开的入口

**Comment by guoyang007** [comment]
了解了，而且可以通过styles配置隐藏该入口。之前以为做内部组件库，该入口可能会带来风险。

**Comment by afc163** [comment]
@PeachScript 这些按钮都统一加个配置吧，给用户选择权。

**Comment by PeachScript** [comment]
v1.0.32 已支持配置：https://d.umijs.org/config/frontmatter#hideactions

**Comment by afc163** [comment]
有哪些可选项呢？

**Comment by PeachScript** [comment]
补上了👍

**Comment by afc163** [comment]
Riddle 呢？

**Comment by PeachScript** [comment]
@afc163 Riddle 实际上是[支持配置](https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/themes/default/builtins/Previewer.tsx#L69)的，但因为社区不可见，所以没有写入文档

**Comment by 271853754** [comment]
"react": "16.13.0",
"react-dom": "16.13.1",


devScripts.js:5836 Warning: React does not recognize the `hideActions` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hideactions` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Previewer)
    in Previewer (created by Context.Consumer)
    in Unknown (at confirm.md:31)
    in Unknown (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by component)
    in component (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by RouterComponent)
    in RouterComponent
    in Unknown
    in Unknown

**Comment by PeachScript** [comment]
@271853754 感谢反馈，这个是转 JSX 环节存在的问题，会在 v1.1 中解决，warning 确实有些难受但不影响生产环境，可放心使用

**Comment by zhaoyao91** [comment]
请问可以支持 hideActions 全局配置吗，这个是网站管理者的需求，希望内容创作者可以不关心这个配置，而不必在每个 demo 上都去写 fontmatter

**Comment by PeachScript** [comment]
目前还不行，未来会提供配置，可暂时使用 `config.styles` 做 CSS 层面的隐藏
