### ISSUE TITLE
bug: 无法使用锚点

### ISSUE THREAD

**Issue by yesmeck** [umijs/dumi#170]
### Versions

- dumi: 1.0.20
- node: 13.12.0
- npm:  6.14.4
- OS:  macOS 10.15.4
- Browser:  Chrome 81.0.4044.129 (Official Build) (64-bit)

### Steps to reproduce

访问 https://remaxjs.org/guide/v2-migration#css-%E4%B8%AD%E7%9A%84%E5%9B%BE%E7%89%87

### What is Expected?

能定位到「CSS 中的图片」

### What is actually happening?

没有定位

**Comment by PeachScript** [comment]
有些奇怪，本地以及其他项目的线上（https://umijs.org/zh-CN/plugins/api#registermethod-name-string-fn-function-exitserror-boolean- ）都无法复现，可能和 GitHub Pages 有关

**Comment by yesmeck** [comment]
发现有个 301

**Comment by yesmeck** [comment]
迁移到 now 可以了，不知道哪来的 301
