### ISSUE TITLE
如何不要现有首页,直接指定某个内页作为首页?

### ISSUE THREAD

**Issue by LiuRan89** [umijs/dumi#1702]
#### 我不需要首页,我希望直接把某个内页,比如指南页,作为首页,能不能做到?
谢谢!!!

**Comment by PeachScript** [comment]
参考 https://github.com/umijs/dumi/issues/1428#issuecomment-1506311914

**Comment by cangsnage** [comment]
> ### 问题:如何不要现有首页,直接指定某个内页作为首页?
> #### 我不需要首页,我希望直接把某个内页,比如指南页,作为首页,能不能做到?
> 谢谢!!!

请问解决了么

**Comment by LiuRan89** [comment]
> > ### 问题:如何不要现有首页,直接指定某个内页作为首页?
> > #### 我不需要首页,我希望直接把某个内页,比如指南页,作为首页,能不能做到?
> > 谢谢!!!
> 
> 请问解决了么

没有,我搞不定,就没搞了

**Comment by ruimax** [comment]
我用的dumi2，可以参考https://d.umijs.org/config/runtime#patchclientroutes配置路由重定向
`import { Navigate } from 'dumi';

export const patchClientRoutes = ({ routes }) => {
  routes.unshift({
    path: '/',
    element: <Navigate to="/teacher/1" replace />,
  });
};
`
