### ISSUE TITLE
dumi build的产物 模版引入的资源路径支不支持配置前缀

### ISSUE THREAD

**Issue by ibcLee** [umijs/dumi#1705]
### Question
构建文档后，html中引入的资源路径支持配置前缀么
### Sample Code
<script src="/demo/umi.724d274d.js"></script>

**Comment by PeachScript** [comment]
ref: https://d.umijs.org/guide/faq#%E9%9D%9E%E6%A0%B9%E7%9B%AE%E5%BD%95%E9%83%A8%E7%BD%B2
