### ISSUE TITLE
dumi build 非常慢

### ISSUE THREAD

**Issue by LemonYo** [umijs/dumi#1707]
dev 是很快的，但是到了 CI/CD 的时候，基本就卡死在哪里。本地执行build 也卡死在哪里，如何解决，cache ？

**Comment by PeachScript** [comment]
提供下最小可复现仓库

**Comment by LemonYo** [comment]
已经找到问题了，是因为开启了自动生成api表格 导致的，我目前只有一个组件，请问如何优化 ，我的配置如下：
apiParser: {}
resolve: {
// 配置入口文件路径，API 解析将从这里开始
	entryFile: '../packages/widget/src/index.ts',
},

**Comment by PeachScript** [comment]
v2.2.1 已优化 PNPM 及 monorepo 项目下的解析速度，ref: https://github.com/umijs/dumi/issues/1528#issuecomment-1573273914

**Comment by LemonYo** [comment]
@PeachScript 刚才升级dumi v.2.2.1 感觉并没有生效，或者说明显的提升。没有找到dumi-afx-deps@1.0.0-alpha.18这个依赖

**Comment by PeachScript** [comment]
@LemonYo 可以提供下最小可复现仓库，统一到上面的 issue 里讨论吧
