### ISSUE TITLE
🐞 bug:  关于md中 `-->` 中被意外的渲染成了 `*/}`

### ISSUE THREAD

**Issue by jhoneybee** [umijs/dumi#171]
### Versions

- dumi:  dumi@1.0.21
- node: v14.1.0
- npm: 6.14.4
- OS:  window 10
- Browser:  chrome 最新版本

### Steps to reproduce

1. 执行命令 `npx @umijs/create-dumi-lib --site`
2. 修改Foo.md文件，添加以下内容

\`\`\`
-->
\`\`\`

期待渲染出来的HTML标签为 

```
<pre><code> --&gt; <br></code></pre>
```

实际上他渲染出来为

```
<pre><code>*/}<br></code></pre>
```

导致 `-->` 被渲染为了 `*/}`

**Comment by PeachScript** [comment]
感谢反馈，v1.0.25 已修复
