### ISSUE TITLE
如何在顶部导航区域添加自定义下拉框，类似官网那样

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#1711]
比如有时候我们自己也要添加版本切换，或者自定义下拉事件改变组件的颜色主题展示等等

![image](https://github.com/umijs/dumi/assets/51065061/ee0cecef-19d7-4598-a2b5-7ebe04d089e2)

**Comment by PeachScript** [comment]
等下个 patch 发布参考官网代码仓库添加即可：https://github.com/umijs/dumi/blob/17e21bf3e7c612495d06cbbbd4babffdf5c91d92/.dumi/theme/slots/HeaderExtra/index.tsx

**Comment by CaptainJon** [comment]
> 等下个 patch 发布参考官网代码仓库添加即可：https://github.com/umijs/dumi/blob/17e21bf3e7c612495d06cbbbd4babffdf5c91d92/.dumi/theme/slots/HeaderExtra/index.tsx

ok，nice

**Comment by PeachScript** [comment]
v2.2.1 已发布
