### ISSUE TITLE
如何获取 .dumirc.ts 中所有值内容

### ISSUE THREAD

**Issue by KuangPF** [umijs/dumi#1714]
### Question
需求大致是这样：想要获取 .dumirc.ts 中 [theme](https://d.umijs.org/config#theme) 的值用于修改自定义主题包中的颜色主题，但目前能查到的 api `useSiteData` 只能获取到 `themeConfig` 中的值，对于之外的值并没有提供，想问题有没有办法获取 .dumirc.ts 中剩余的值，或者能否提供一种思路。

thanks.

**Comment by PeachScript** [comment]
建议主题包在 `themeConfig` 里提供一个配置项实现该功能，原因：
1. `themeConfig` 外的是框架的编译时配置，并非所有值都可以被序列化（比如函数），所以无法直接提供给运行时读取
2. 虽然主题包能通过插件 API 实现 `theme` 配置项的借壳传递，但 `theme` 配置项在 dumi 里的作用是配置 Less 变量，而主题包应该不是用 Less 在运行时做动态主题，语法上肯定有区别，混用一个配置项不太合适

**Comment by KuangPF** [comment]
好的，理解了。
