### ISSUE TITLE
dumi如何build生成静态资源包

### ISSUE THREAD

**Issue by waitInHope** [umijs/dumi#1724]
### dev模式都展示正常，但是打包之后直接访问入口文件index.html会报资源加载错误，使用storybook打包后就是一个纯净的静态资源包，有什么方式可以设置dumi的打包产物来单纯部署静态资源网站

<!DOCTYPE html><html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<link rel="stylesheet" href="/umi.6cab289a.css">
</head>
<body>
<div id="root"></div>
<script src="/umi.cd1e0a6b.js"></script>

</body></html>

解析"/umi.6cab289a.css"和"/umi.cd1e0a6b.js"的时候会报错

**Comment by PeachScript** [comment]
dumi 的产物必须由 http-server 或类似 GitHub Pages 的平台托管，不支持直接打开 index.html 访问
