### ISSUE TITLE
升级dumi2.0时原dumi1.0的主题API如何处理

### ISSUE THREAD

**Issue by yuanfeng1991** [umijs/dumi#1730]
在把项目从dumi1.0升级到dumi2.0（参照[https://d.umijs.org/guide/upgrading）过程中](https://d.umijs.org/guide/upgrading%EF%BC%89%E8%BF%87%E7%A8%8B%E4%B8%AD)，发现dumi1.0原有的主题API没有了，且在dumi2文档里面没有找到相应的部分，麻烦问下应该怎么处理。
未找到的主题API：
useDemoUrl、context、useMotions、useCopy、useLocaleProps等

**Comment by PeachScript** [comment]
主题包暂时没有升级文档，你提到的这几个：
1. `useDemoUrl`：已废弃，直接通过 Previewer 的 props 传递完成最终 demoUrl 了，自定义主题覆盖 Previewer 时可以直接消费
2. `context`：改用 [`useSiteData`](https://d.umijs.org/theme/api#usesitedata)
3. `useMotions`：已废弃，dumi 1 的实验性功能，dumi 2 暂时没有支持的计划
4. `useCopy`：已废弃，需要自己依赖 `react-copy-to-clipboard` 实现
5. `useLocaleProps`：已废弃，dumi 2 自身的主题包实现用不到该 hook 了，如果你的项目仍然需要，可以自己复制一份
