### ISSUE TITLE
bug: markdown文档中code标签编译错误

### ISSUE THREAD

**Issue by G-02** [umijs/dumi#1731]
相同的code标签渲染的内容不一致
<img width="561" alt="image" src="https://github.com/umijs/dumi/assets/70744950/8c61d6d4-a96a-4ed6-b5dc-b3ff9f47dee2">
<img width="1158" alt="image" src="https://github.com/umijs/dumi/assets/70744950/eacb8845-7b01-4abb-9b05-121ea0604221">
<img width="1100" alt="image" src="https://github.com/umijs/dumi/assets/70744950/13cf8718-7079-4130-8652-8a2ded761609">
3和4的渲染表现不一致

### Versions

- dumi:^2.2.0
- node:16.16.0
- npm:8.11.0
- OS:mac OS
- Browser:谷歌

**Comment by G-02** [comment]
> `1`
> `2`
> `3`
> `4`

**Comment by suiyun39** [comment]
试试在第四行之后添加一个空行

**Comment by Wxh16144** [comment]
你可以尝试在 `<code />` 标签上添加 id 来避免;

相关 PR: https://github.com/umijs/dumi/pull/1508/files#diff-c7797cd6cba66e547ee96e694d51de9a4413e4bb1b09bfb2ab5ccce67c994c4cL86-R89
