### ISSUE TITLE
无法启动 443 端口

### ISSUE THREAD

**Issue by gauseen** [umijs/dumi#1742]
### Versions

- dumi: "^2.2.0"
- node: v14.21.3
- npm: 6.14.18
- OS: macOS 13.2.1 (22D68)
- Browser: chrome

### Steps to reproduce

```sh
# .env file

PORT=443
```
.dumirc.ts

![image](https://github.com/umijs/dumi/assets/22701565/8d22a44a-d179-47f9-aa2d-a647d0648d73)

运行 sudo npm run dev 启动项目

### What is Expected?

正常启动 443 端口

### What is actually happening?

启动服务是 1024 端口
![image](https://github.com/umijs/dumi/assets/22701565/0416707d-bf49-4e2f-a5c6-ffd1be0c7b64)

**Comment by PeachScript** [comment]
443 和 80 一样，需要 sudo 权限才能启动

**Comment by gauseen** [comment]
> 443 和 80 一样，需要 sudo 权限才能启动

确实是的，在 package scripts 里面用 `sudo dumi dev` 才行
