### ISSUE TITLE
bug: demo没有展示依赖文件的源代码

### ISSUE THREAD

**Issue by wangminglmm** [umijs/dumi#1744]
示例文件太多，分了多个文件，发现demo引入的相对路径文件没有展示源代码
### Versions

- dumi: 1.1.49
- node:
- npm:
- OS:
- Browser:

**Comment by wangminglmm** [comment]
![image](https://github.com/umijs/dumi/assets/23519408/68d63893-4eb9-4cff-b789-648059238dd0)

**Comment by PeachScript** [comment]
dumi 1 不迭代了，有精力可升级到 dumi 2，或者排查下问题原因提交 PR 到 1.x 分支帮忙修复
