### ISSUE TITLE
body污染的 全局样式

### ISSUE THREAD

**Issue by chico-malo** [umijs/dumi#1745]
### Question
搜索过了，没有提过同样的问题。
问题1：
![image](https://github.com/umijs/dumi/assets/26463204/2ef28b04-6065-46d9-9585-8b802f3edb3b)
body全局样式会被一个叫 Common.tsx 覆盖掉。

问题2：
在某些场景，Common.tsx 的样式，再次被覆盖。
![image](https://github.com/umijs/dumi/assets/26463204/ada9d834-11df-4ef6-a3b1-88948f084c87)

### Sample Code
无
demo地址：https://assets-test.sto.cn/ux/cn-eone/0.0.1-alpha.5/guide/index.html

**Comment by PeachScript** [comment]
dumi 在实现默认主题的过程中有意规避了对组件库的样式污染，截图的样式来源都不是 dumi，大概率来源于组件库的实现或者组件库的三方依赖，这些全局样式污染只能自己想办法处理，要么利用 PostCSS 插件转换这些全局样式，要么组件库自己覆写回来

**Comment by chico-malo** [comment]
> dumi 在实现默认主题的过程中有意规避了对组件库的样式污染，截图的样式来源都不是 dumi，大概率来源于组件库的实现或者组件库的三方依赖，这些全局样式污染只能自己想办法处理，要么利用 PostCSS 插件转换这些全局样式，要么组件库自己覆写回来

经过测试，果然是第三方主题的问题，多谢~
