### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by haolipersonal** [umijs/dumi#1746]
### Versions

- dumi: 2.21

 docs -components-aaa-index.md
菜单不显示aaa菜单
docs-component-aaa.md
菜单显示aaa菜单

约定式路由-解析实例中说明是可以，我之前使用的2.1.2版本项目也是可以的，但是在2.2.1版本中无法实现

**Comment by PeachScript** [comment]
没看懂问题，请按照模板把复现信息补充完整
