### ISSUE TITLE
bug: 点击切换返回首页（自定义页面），nprogress 无法关闭

### ISSUE THREAD

**Issue by KuangPF** [umijs/dumi#1750]
### Versions

- dumi: 2.2.0+
- node: 18.12.0
- npm: 9.5.1
- OS: MacOS 13.2
- Browser: Chrome 112

### Steps to reproduce
使用官方提供的脚手架新建一个项目，自定义首页 `pages/index.tsx`，然后新建一些 nav，点击某一个 nav，然后点击左上角图标返回首页，nprogress 无法关闭
### What is Expected?
关闭 nprogress
### What is actually happening?
nprogress 无法关闭，一致 loading

大致定位了下，如果首页是通过 .md 的形式则不会出现问题，是否因为nprogress 没有适配自定义页面导致的。
antd 官网也可以复现，比如点击`组件`导航，再点击左上角图标返回首页，nprogress 一直存在。

thanks.

**Comment by PeachScript** [comment]
v2.2.2 已修复
