### ISSUE TITLE
能否通过配置关闭约定式二级导航

### ISSUE THREAD

**Issue by FriedRiceNoodles** [umijs/dumi#1751]
我升级到了最新版本的dumi，但我不想使用[约定式二级导航](https://d.umijs.org/guide/conventional-routing#%E7%BA%A6%E5%AE%9A%E5%BC%8F%E4%BA%8C%E7%BA%A7%E5%AF%BC%E8%88%AA)，请问我可以在不修改package.json的情况下将这个功能关闭吗？

**Comment by PeachScript** [comment]
关不了，但这只是一种约定，不想用二级导航有两种方案：
1. 约定式目录结构不包含二级嵌套就不会生成二级导航
2. 通过 `themeConfig.nav` 使用配置式导航

**Comment by tsejx** [comment]
倒退式更新，如果一个 nav 下有太多 md 文件需要用文件夹统一管理，所要达到的效果是在左侧侧边栏做分组即可，1.x 的版本就很好用

现在为了实现我的需求，就只能从文件名做区分
