### ISSUE TITLE
bug: 直接启动 ahooks 的本地，访问codesanbox，报ahooks依赖

### ISSUE THREAD

**Issue by 1587315093** [umijs/dumi#1752]
### Versions

- dumi: 1.1.48
- node: 16.14.0
- npm:  pnpm@7.3.0
- OS:
- Browser:

### Steps to reproduce
1. git  clone https://github.com/alibaba/hooks.git
2. pnpm i  然后 pnpm start
3. 随便点击某个demo 的沙盒链接
### What is Expected?

Could not find dependency: 'ahooks' relative to '/App.tsx'

### What is actually happening?
![image](https://github.com/umijs/dumi/assets/77056991/de30955b-75c9-49fd-a8e2-fe4fb73eb910)

**Comment by PeachScript** [comment]
dumi 1 不迭代了，请升级到 dumi 2
