### ISSUE TITLE
nginx隐藏端口号后 访问项目首页 无限自动刷新

### ISSUE THREAD

**Issue by zrs1996** [umijs/dumi#1755]
### Question
nginx隐藏端口号后 访问项目首页 无限自动刷新
如果加上端口号就不自动刷新了
项目换成vite 或者 webpack启动都不会自动刷新 这是因为什么
这个问题困扰了我几天了  找不到原因所在  

### Sample Code
项目地址
https://github.com/zrs1996/happy-bee.git
使用npm start启动

nginx配置

    server {
        listen       80;
        server_name  zhanrongshuai.com;
        location / {	
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host            $http_host;
            proxy_pass http://zhanrongshuai.com:9001;
        }
    }
### 复现步骤
浏览器访问
http://zhanrongshuai.com  自动刷新
http://zhanrongshuai.com:9001 正常

**Comment by PeachScript** [comment]
推测是反代后 HMR 连不上 socket server 导致的，如果是要部署建议直接用 nginx 托管产物而不是反代到 dumi 的 dev server

**Comment by zrs1996** [comment]
> 推测是反代后 HMR 连不上 socket server 导致的，如果是要部署建议直接用 nginx 托管产物而不是反代到 dumi 的 dev server

已经解决。

托管产物后就好了 https也生效了

之前代理的dev server 自动刷新 https的代理也不生效。
