### ISSUE TITLE
怎么实现载入ts,js,css,jsx等源代码文件到markdown代码块

### ISSUE THREAD

**Issue by mudssky** [umijs/dumi#1756]
### Question
怎么实现载入ts,js,css,jsx等源代码文件到markdown代码块
### Sample Code
文档里面有载入tsx组件编写demo的功能
```
<code src="./demos/foo.tsx"></code>
```
这个好像只能用来展示tsx组件相关的代码

我只展示代码，希望能直接通过路径导入到markdown，应该怎么实现。

**Comment by PeachScript** [comment]
Duplicate of #1864
