### ISSUE TITLE
feat: 多语言切换应该使用 a 标签

### ISSUE THREAD

**Issue by xcodebuild** [umijs/dumi#176]
![image](https://user-images.githubusercontent.com/5436704/81625831-96efef00-942c-11ea-8a53-3e82fcdb926e.png)

目前多语言标签渲染出来的是一个没有链接的 `span`，会导致搜索引擎爬虫完全看不见另外一个语种的链接。

可以用 https://chrome.google.com/webstore/detail/sitemap-generator/hcnjemngcihnhncobgdgkkfkhmleapah 测试发现爬虫基本只能找到当前语种的链接。

**Comment by afc163** [comment]
来个 PR

**Comment by PeachScript** [comment]
v1.1.0-beta.7 已优化
