### ISSUE TITLE
代码块初始化展示正常 刷新后一直loading

### ISSUE THREAD

**Issue by kaqiinono** [umijs/dumi#1760]
### Question
访问http://localhost:8002/components/button正常展示
访问http://localhost:8002/components/table正常展示
回到button页 代码块一直加载
回到table页 代码块一直加载

详见附件
### Sample Code
[components.zip](https://github.com/umijs/dumi/files/11880499/dp-components.zip)

**Comment by kaqiinono** [comment]
![image](https://github.com/umijs/dumi/assets/11257690/fbe0af72-ec42-450b-b604-916284f0faf7)

**Comment by kaqiinono** [comment]
# First Loading

![image](https://github.com/umijs/dumi/assets/11257690/33930447-6c32-47c2-8f76-9ee5f92826fd)

# After refresh

![image](https://github.com/umijs/dumi/assets/11257690/6814c755-8921-4aa7-b5dd-a303be5c4a0e)

**Comment by kaqiinono** [comment]
有时候一直加载不出来 有时候要等很久才能加载出来

**Comment by PeachScript** [comment]
dumi 官方提供的主题包是没有 demo loading 功能的，所以应该和主题包的实现有关系，请反馈给对应主题包的仓库
