### ISSUE TITLE
react router使用问题

### ISSUE THREAD

**Issue by Bierxiensi** [umijs/dumi#1762]
### Question
![image](https://github.com/umijs/dumi/assets/40264423/5b36ac1e-a420-441c-ad46-4390e4f5424b)
![image](https://github.com/umijs/dumi/assets/40264423/99d31e6d-b7f9-4296-ba02-3769a21d9738)

### Sample Code
 我在代码里使用了<router>，报错 You cannot render a <Router> inside another <Router>. You should never have more than one in your app

**Comment by PeachScript** [comment]
dumi 也是使用 react-router 的，react-router 不允许同一个 React 应用存在多个同类型 router 实例；建议解法：
1. 换 `HashRouter` 实现 demo 和 dumi 使用的 `Router` (BrowserRouter) 区分开来
2. demo 里用 ReactDOM 强行新建一个 React 应用，和微应用类似，但需要注意路由表和外层应用冲突的情况
