### ISSUE TITLE
还是不懂插件怎么写

### ISSUE THREAD

**Issue by Tziheng** [umijs/dumi#1763]
### Question

根据 [https://d.umijs.org/plugin#核心概念](https://d.umijs.org/plugin#%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5)的代码，我在 `D;/dumi/` 目录下创建了一个文件夹 `plugins`，文件夹中有唯一文件`index.ts`，文件里面就是[https://d.umijs.org/plugin#核心概念](https://d.umijs.org/plugin#%E6%A0%B8%E5%BF%83%E6%A6%82%E5%BF%B5)这段代码，然后在`.dumirc.ts` 配置了
```
export default defineConfig({
  plugins: ['./plugins'],
  changeFavicon: 'https://gitee.com/favicon.ico',
});
```
运行后好像没有看见图标Favicon改变，是不是插件写错了，应该怎么去写？

**Comment by Wxh16144** [comment]
我检查一下代码, 其实 dumi 文档中关于插件的概念是 sync umijs 那边的文档, 文档有些陈旧了..., 但是你只需要修改一行就能正常跑起来了:

```diff
import { IApi } from 'dumi';

export default (api: IApi) => {
  api.describe({
    key: 'changeFavicon',
    config: {
      schema(joi) {
        return joi.string();
      },
    },
    enableBy: api.EnableBy.config
  });
  api.modifyConfig((memo)=>{
-    memo.favicon = api.userConfig.changeFavicon;
+    memo.favicons = api.userConfig.changeFavicon;
    return memo;
  });
};

```
