### ISSUE TITLE
bug:'opera_mobile' is not a valid target. Did you mean 'opera'? (While processing: ... @umijs.babel-preset-umi/app.js$0$0$39"))

### ISSUE THREAD

**Issue by doojia** [umijs/dumi#1766]
tnpm start 之后报这个错 webpack进度卡到99%

将目标文件index.md删除后服务器可以启动但是webpack进度还是99%

![image](https://github.com/umijs/dumi/assets/122765107/ade33b78-2b04-48d1-a51c-1b86c12a0bcb)

![image](https://github.com/umijs/dumi/assets/122765107/8a9980a8-7162-41bc-9c74-f3e55d689394)

**Comment by aiyuekuang** [comment]
me too

**Comment by xierenyuan** [comment]
删除 package.json 里的 broserlist 并且关闭 mfsu 可以临时解决 看起来是 babel 插件升级了导致的

**Comment by PeachScript** [comment]
Umi 层已经升级了 babel，可以重装依赖再看看有没有该问题

**Comment by PeachScript** [comment]
dumi v1 的问题，v1.1.52 已修复
