### ISSUE TITLE
Error: Bindings not found

### ISSUE THREAD

**Issue by jeffreyzzzs** [umijs/dumi#1767]
![image](https://github.com/umijs/dumi/assets/52402138/8c1e5c04-1ab6-46d5-82d4-983e1559bf89)

**Comment by PeachScript** [comment]
只有截图无法排查问题，如果问题仍然存在，请按照 bug issue 模板补充完整复现信息和最小可复现仓库：https://github.com/umijs/dumi/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by hexf00** [comment]
please see https://github.com/umijs/dumi/issues/1701#issuecomment-1681800490
