### ISSUE TITLE
md 里面写 <code src="xxx.tsx"></code> 案例问题

### ISSUE THREAD

**Issue by muddyrain** [umijs/dumi#1769]
### Question
md 里面写 `<code>` 案例问题
## 代码演示
```
<code src="./demo/demo1.tsx"></code>  
```

<img width="1198" alt="image" src="https://github.com/umijs/dumi/assets/66107882/7bbdae23-1843-41cd-83b3-aea695c1aaf4">
然后 显示出来的文档 为什么是 我组件的源码 而不是 案例的源码。

**Comment by PeachScript** [comment]
不确定你的具体写法，我用 dumi 仓库测试是展示 demo 源码的，需要提供最小可复现仓库看看
