### ISSUE TITLE
bug: [plugin-locale]

### ISSUE THREAD

**Issue by GloriaCHL** [umijs/dumi#177]
### Versions

- dumi:1.0.21
- node:v13.5.0
- npm:6.14.4
- OS:ubuntu 18.04
- Browser:chrome

### Steps to reproduce

```
import { FormattedMessage, useIntl } from 'umi';
...
const intl = useIntl();
...
```

### What is Expected?

在组件中使用 intl

### What is actually happening?

![image](https://user-images.githubusercontent.com/10557315/81632465-ee965680-943c-11ea-8dda-765e646543d8.png)

**Comment by PeachScript** [comment]
plugin-locale 安装了吗

**Comment by GloriaCHL** [comment]
没有。项目是用 ant design pro 初始化的，在项目里建了个dumi文件夹，用 [issue](https://github.com/umijs/dumi/issues/161) 这里介绍的方法加入 dumi 项目。这个组件在主项目里是没问题的。移到 dumi 文件夹里，用 dumi 负责调用就会报上面的错。

**Comment by PeachScript** [comment]
`useIntl` 是 plugin-locale 提供的能力，需要安装后才能使用：https://umijs.org/zh-CN/plugins/plugin-locale#useintl

**Comment by PeachScript** [comment]
默认会装载 cwd 下 package.json 中的 umi plugin，如果想装载上层目录的，需要手动用 config.plugins 装载：https://umijs.org/zh-CN/config#plugins

**Comment by GloriaCHL** [comment]
没行通。按plugins介绍加了个主项目目录下的node_moudules里的plugin-locale，报错了：
![image](https://user-images.githubusercontent.com/10557315/81812038-23e39700-9558-11ea-81a5-b763a4fb25a7.png)

是因为dumi使用的package.json跟主目录使用的是同一个吗？

**Comment by PeachScript** [comment]
不清楚你的目录结构，提供个最小复现仓库吧

**Comment by GloriaCHL** [comment]
https://github.com/GloriaCHL/antd-pro-dumi-demo

**Comment by Vincent-X** [comment]
same question，在dumi的目录下创建了locales，并且在dumi的配置中加了locale字段开启国际化，在文档中引用带了国际化的组件，提示Missing Message for [messageid]

**Comment by xiaohuoni** [comment]
@GloriaCHL https://github.com/GloriaCHL/antd-pro-dumi-demo/pull/1
locale 要配置才生效
```
// https://umijs.org/config/
import { defineConfig } from 'umi';

export default defineConfig({
  locale: {
    // default zh-CN
    default: 'zh-CN',
    // default true, when it is true, will use `navigator.language` overwrite default
    antd: true,
    baseNavigator: true,
  },
});
```

**Comment by xiaohuoni** [comment]
有点别扭这么用。locale 配置和约定的文件路径都不对。

**Comment by PeachScript** [comment]
问题还存在吗

**Comment by xrkffgg** [comment]
先关闭了，有问题再说。
