### ISSUE TITLE
lessLoader实现全局变量注入遇到的问题

### ISSUE THREAD

**Issue by lh-js** [umijs/dumi#1770]
### Question
lessLoader实现全局变量注入，这个lessLoader应该怎么配置，官方文档上也没有说的很清楚
### Sample Code
![image](https://github.com/umijs/dumi/assets/88662883/b712711e-af8f-4932-b94d-b8581c87d16a)

**Comment by PeachScript** [comment]
直接配传给 less-loader 的 `options` 参数值，也就是上图红框部分

另外需要说明下，`lessLoader` 配置项仅作用于组件库文档构建，不会对组件库源码构建产生影响，所以建议单独在每个 less 文件里引入变量文件确保组件库发布后可以正常工作，且 less 中暂无法使用别名，需要用相对路径引入其他文件，ref：https://github.com/umijs/father/issues/679
