### ISSUE TITLE
dumi 2.x 还支持 显示上次更新时间吗？该怎么配置？

### ISSUE THREAD

**Issue by lh-js** [umijs/dumi#1773]
### Question
dumi 2.x 还支持 显示上次更新时间吗？该怎么配置？ 1.x是默认带的，但是更新到2之后就没了
### Sample Code
<img width="1144" alt="image" src="https://github.com/umijs/dumi/assets/88662883/8f7dfd84-7676-4bd3-9af4-5cf815652e5d">

**Comment by PeachScript** [comment]
v2.2.2 已支持：https://d.umijs.org/theme/default#lastupdated

**Comment by lh-js** [comment]
<img width="1162" alt="image" src="https://github.com/umijs/dumi/assets/88662883/9ec7f799-ffa4-41b0-93d3-59aadd17a233">
这个样式好像有点问题，我的环境是mac

**Comment by PeachScript** [comment]
Chrome 下有问题，我再发个修复版本

**Comment by lh-js** [comment]
> Chrome 下有问题，我再发个修复版本

好的谢谢

**Comment by PeachScript** [comment]
#1800 有空可以帮忙 Review 下，PR 评论里有 Vercel 预览链接

**Comment by lh-js** [comment]
> #1800 有空可以帮忙 Review 下，PR 评论里有 Vercel 预览链接

好的，review在Chrome下是正常的

**Comment by PeachScript** [comment]
v2.2.4 已修复，感谢反馈及验证

**Comment by lh-js** [comment]
> v2.2.4 已修复，感谢反馈及验证

好的
