### ISSUE TITLE
bug: pnpm install error

### ISSUE THREAD

**Issue by Lpbzzz** [umijs/dumi#1783]
### Versions

- dumi:2.2.1
- node:16.18.1
- npm:9.8.1
- OS:Macos 13.4.1
- Browser: chrome

### Steps to reproduce

执行 pnpm install 

### What is actually happening?

<img width="1660" alt="image" src="https://github.com/umijs/dumi/assets/28721487/182a4083-ab8d-430c-8000-14bd5f8f996d">

**Comment by Lpbzzz** [comment]
<img width="618" alt="image" src="https://github.com/umijs/dumi/assets/28721487/57f664c4-39e6-4165-89cb-6ffb28a52776">

**Comment by PeachScript** [comment]
target 加上以后也无法安装吗
