### ISSUE TITLE
feat: 可以支持使用linaria么

### ISSUE THREAD

**Issue by Pursue-LLL** [umijs/dumi#1784]
试了各种方法都不行，报错
Using the "styled" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.

**Comment by PeachScript** [comment]
没有使用过这个库，建议按照官方提供的[webpack 集成文档](https://github.com/callstack/linaria/blob/master/docs/BUNDLERS_INTEGRATION.md#webpack)结合 dumi 的 [chainWebpack](https://d.umijs.org/plugin/api#chainwebpack) 配置项给 js rule 追加配置试试看

**Comment by leedalei** [comment]
> 试了各种方法都不行，报错 Using the "styled" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.

请问你成功用上了吗？
