### ISSUE TITLE
npx create-dumi    提示  Unexpected token '?'

### ISSUE THREAD

**Issue by lsk222** [umijs/dumi#1788]
### Question
npx create-dumi    提示  Unexpected token '?' 初始化失败
### Sample Code
node：16.14.2
操作系统： window10

**Comment by PeachScript** [comment]
贴一下错误堆栈截图

**Comment by lsk222** [comment]
![image](https://github.com/umijs/dumi/assets/46222616/eef84698-3fa3-467b-b581-3779b7bc30dd)
