### ISSUE TITLE
自定义页面禁用侧边栏时不展示 Content 容器

### ISSUE THREAD

**Issue by envylover** [umijs/dumi#1789]
### Versions

- dumi:2.2.1
- node: 16
- npm: 16.20.0
- OS: mac os
- Browser: edge

### Steps to reproduce
目录结构：
- dumi
  - pages
      - test
        - 1
        - 2
        - index.tsx
        - utils.ts

### What is Expected?
/test 是应该渲染React页面

### What is actually happening?
实际效果会在页面内容还会创建dumi-default-content，且侧边栏中展示
 1
 2
 utils
<br/>当test为Test时不会出现此现象。
自定义页面应当不需要展示dumi侧边栏

**Comment by PeachScript** [comment]
> 当test为Test时不会出现此现象

我本地验证下来和大小写无关，都会展示侧边栏

> 自定义页面应当不需要展示dumi侧边栏

dumi 没有这个设定，自定义页面也是可以有侧边栏的，这样才能和普通 md 生成的内容结构融合在一起

如果不需要侧边栏，给自定义页面最顶部加上 FrontMatter 配置 sidebar: false 即可，配置项文档：https://d.umijs.org/theme/default#sidebar-1 ，代码示例：

```tsx
/**
 * sidebar: false
 */

// 自定义页面的具体代码实现
```

但这里应该有个优化点，手动禁用 sidebar 的时候应该和首页一致不展示 Content 容器，下个版本会调整下

**Comment by PeachScript** [comment]
> 但这里应该有个优化点，手动禁用 sidebar 的时候应该和首页一致不展示 Content 容器，下个版本会调整下

v2.2.2 已调整
