### ISSUE TITLE
bug: 直接在md文件中引用antd组件，babel-plugin-import不生效

### ISSUE THREAD

**Issue by builden** [umijs/dumi#179]
### Versions

- dumi: v.1.0.25
- node:  v12.13.1
- npm: v6.12.1
- OS: Win7
- Browser: Chrome 81

### Steps to reproduce
在md文件直接引入antd库，在.umirc.ts中配置了babel-plugin-import
```ts
{
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
      'antd',
    ],
  ]
}
```

### What is Expected?
执行打包，不会把整个antd库引入进来

### What is actually happening?
如果是在src目录下编写jsx文件引入antd库，然后在md中通过`<code src="xxx"/>`的方式引入
tree shaking功能正常
直接在md中引入antd库，tree shaking失效

**Comment by poyiding** [comment]
同样遇到md中引入antd无效问题 @PeachScript

**Comment by poyiding** [comment]
你的 antd 可以安装在peerDependencies 中

**Comment by shengbeiniao** [comment]
同样的问题，自己的组件库，如果用 alias 引入，也会导致 tree shaking 失效

**Comment by PeachScript** [comment]
v1.1.37 已修复
