### ISSUE TITLE
feat: 如何实现代码块的不同版本的切换？

### ISSUE THREAD

**Issue by wabi-habi** [umijs/dumi#1799]
如何实现 `antd` 的代码预览的这种 js 和 ts 不同版本的切换？

<img width="1737" alt="image" src="https://github.com/umijs/dumi/assets/99811051/44ce0030-e346-469b-a3d2-50adc9d45cdd">

**Comment by PeachScript** [comment]
由于 TypeScript 转 JavaScript 会增加编译耗时和产物尺寸，加上 TypeScript 已经成为主流选择，所以 dumi 默认不提供此功能，有需要可以自己参考 antd 的实现，需要覆盖内置的 [demo 编译技术栈](https://github.com/ant-design/ant-design/blob/6cc3c2cd4f3db5e0e0951a686d4a72ba2da56d34/.dumi/theme/plugin.ts#L31)及[自定义 Previewer 预览器](https://github.com/ant-design/ant-design/blob/6cc3c2cd4f3db5e0e0951a686d4a72ba2da56d34/.dumi/theme/builtins/Previewer/CodePreviewer.tsx#L133-L136)，分别用于转换和展示 JavaScript 源代码
