### ISSUE TITLE
feat: 生成 sitemap.xml

### ISSUE THREAD

**Issue by yesmeck** [umijs/dumi#180]
### Description

对搜索引擎更友好。

https://docsearch.algolia.com/docs/tips

**Comment by shebaoting** [comment]
同求。否则无法开通Algolia 的 DocSearch 服务？

**Comment by JohnApache** [comment]
希望后续可以实现该功能

**Comment by PeachScript** [comment]
[v1.1.0-beta.31](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-beta.31) 已支持：https://d.umijs.org/config#sitemap

**Comment by drdevelop** [comment]
@PeachScript 当前网站不是在根目录，生成的xml里的文件路径怎么指定在统一目录下

**Comment by TrumanDu** [comment]
@PeachScript 当前网站不是在根目录，生成的xml里的文件路径怎么指定在统一目录下
