### ISSUE TITLE
引入图片找不到路径

### ISSUE THREAD

**Issue by lsk222** [umijs/dumi#1804]
### Question
引入图片找不到路径
### Sample Code
![image](https://github.com/umijs/dumi/assets/46222616/462a9f1e-45e4-4c25-9aa2-7267311fe3f8)

在BBlock中引入图片找不到
![image](https://github.com/umijs/dumi/assets/46222616/ddc51323-df5b-44f5-bab9-89042817f06a)

**Comment by PeachScript** [comment]
和常规 webpack 项目一致，静态资源通过 import 获取引用路径，`import imgUrl from './static/back.png'`
