### ISSUE TITLE
antd二次封装的组件 样式不对

### ISSUE THREAD

**Issue by lsk222** [umijs/dumi#1807]
### Question
我们有一个 fsearchinput 的组件，单独运行没问题，上传到npm后，下载到dumi里面使用，但是样式不对，这个组件是用antd二次封装的，
cascader，date 组件也是一样，样式乱了
### Sample Code
正常的
![image](https://github.com/umijs/dumi/assets/46222616/b238be78-86cf-481b-b71f-774eee91ee5e)
放在dumi里面的
![image](https://github.com/umijs/dumi/assets/46222616/0a738942-eb09-4140-9c0b-9baf74676370)
代码：src/FSeachInput/index.tsx
![image](https://github.com/umijs/dumi/assets/46222616/9c5b62b9-54ad-4379-9cf0-f76d2519c7aa)

**Comment by Wxh16144** [comment]
描述信息太少了
1. antd 的版本是多少？
2. 二次封装的仓库是否上传了 css less 等文件

**Comment by PeachScript** [comment]
没有足够的复现信息，该 issue 将关闭，如果仍有问题请补充完整的复现步骤和最小可复现仓库再 reopen
