### ISSUE TITLE
.dumi文件夹

### ISSUE THREAD

**Issue by 97vack** [umijs/dumi#1808]
全局样式覆盖和全局脚本是写在.dumi文件夹下， 发现.dumi文件夹是可以删除的， 删除后在启动项目会重新生成一个新的.dumi文件夹， 假如将全局样式覆盖和全局脚本写在.dumi文件夹下， 那删除后又将如何应对

**Comment by PeachScript** [comment]
会重新生成的是 `.dumi/tmp`，用户的文件不会受影响，参考：https://d.umijs.org/guide/project-structure#%E4%B8%B4%E6%97%B6%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95

**Comment by 97vack** [comment]
欧克欧克， 是我文档没看仔细
