### ISSUE TITLE
想咨询下，内网使用codeSandbox的一些问题

### ISSUE THREAD

**Issue by Zex158** [umijs/dumi#1809]
### Question
内网使用dumi开发组件库（包含一些内网npm上的依赖，也不希望组件库代码和相关内网npm包代码泄露到外网），用到codeSandbox，要是内网开放codeSandbox访问权限，是否可在内网正常使用codeSandBox，代码是否会泄露到外网

**Comment by PeachScript** [comment]
代码会泄露而且内网 NPM 包也安装不了，建议禁用按钮或内网自己私有化部署一套
