### ISSUE TITLE
dumi2 是否支持文档多版本

### ISSUE THREAD

**Issue by nanianlisao** [umijs/dumi#1810]
### Question

dumi2 是否支持文档多版本呢
考虑维护问题，所以还是希望使用约定式路由，本计划是通过 onRouteChange 做路由重定向到对应版本，但是由于 dumi2仅支持二级导航，因此多嵌套一套version路由会导致sideBar异常， 请问有什么好的解决方案吗
### Sample Code
```
import { history } from 'dumi';
export function onRouteChange(router: any) {
  const {
    routes,
    location: { pathname },
  } = router;

  if (pathname.startsWith('/xxx')) {
    history.replace(pathname.replace('/xxx', `/v2/xxx`));
  }
}

```

**Comment by PeachScript** [comment]
Duplicate of https://github.com/umijs/dumi/issues/208#issuecomment-639560671
