### ISSUE TITLE
如何在dumi构建的项目中引入静态js文件

### ISSUE THREAD

**Issue by crazymad-apps** [umijs/dumi#1814]
### Question
如题，我需要构建一个仓库，其中有一个依赖无法以npm的形式安装，我必须使用静态js的形式引入，我找不到统一的index.html入口引入文件

**Comment by crazymad-apps** [comment]
除了index.html以外，还有静态css文件也要从静态入口引入

**Comment by PeachScript** [comment]
参考：https://d.umijs.org/config#headscripts 以及同文档中的 `links`、`scripts` 配置项
