### ISSUE TITLE
bug: `^2.2.4` nav 解析异常！

### ISSUE THREAD

**Issue by ayangweb** [umijs/dumi#1815]
### Versions

- dumi: ^2.2.4
- node: v18.16.0 
- npm: 9.5.1
- OS: MacOS 12.6 M1
- Browser: Chrome 版本 115.0.5790.114（正式版本） (arm64)

### Steps to reproduce
[https://github.com/ayangweb/dumi-test](https://github.com/ayangweb/dumi-test)
### What is Expected?
将上面项目的 `dumi` 版本改为 `^2.1.22`，解析出来的是正常的！

<img width="1737" alt="image" src="https://github.com/umijs/dumi/assets/75017711/9169215b-77c9-497a-a7d8-e2b9f7ea0485">

<img width="1728" alt="image" src="https://github.com/umijs/dumi/assets/75017711/6b4cb348-bef1-4bba-999c-5d4281ddc9fc">

### What is actually happening?
`^2.2.4` 中：

- 指南路由在英文下是解析正常，但是中文下折叠起来了！

- 英文下组件路由跑到指南路由下了，#1816 gif 图能看到效果！

<img width="1737" alt="image" src="https://github.com/umijs/dumi/assets/75017711/58a817d5-5855-423c-a65b-9db98a9a2546">

<img width="1735" alt="image" src="https://github.com/umijs/dumi/assets/75017711/736eeda1-73aa-4628-91d7-63fba33ef796">

<img width="1737" alt="image" src="https://github.com/umijs/dumi/assets/75017711/739c1291-ca73-44c3-8b07-3d63990f89e8">

<img width="1737" alt="image" src="https://github.com/umijs/dumi/assets/75017711/662caae8-db23-4037-9998-d240fcb33327">

**Comment by PeachScript** [comment]
这是符合期望的，因为 2.2.0 开始支持了约定式二级导航，具体可以参考文档说明：https://d.umijs.org/guide/conventional-routing#%E7%BA%A6%E5%AE%9A%E5%BC%8F%E4%BA%8C%E7%BA%A7%E5%AF%BC%E8%88%AA

对于你遇到的问题，如果想恢复到原来的结构，只需要把目录结构从 3 级嵌套调整为 2 级即可，也就是将 `docs/guide/install/index.md` 重命名为 `docs/guide/install.md`，英文也是同理

**Comment by ayangweb** [comment]
> 这是符合期望的，因为 2.2.0 开始支持了约定式二级导航，具体可以参考文档说明：https://d.umijs.org/guide/conventional-routing#%E7%BA%A6%E5%AE%9A%E5%BC%8F%E4%BA%8C%E7%BA%A7%E5%AF%BC%E8%88%AA
> 
> 对于你遇到的问题，如果想恢复到原来的结构，只需要把目录结构从 3 级嵌套调整为 2 级即可，也就是将 `docs/guide/install/index.md` 重命名为 `docs/guide/install.md`，英文也是同理

感谢，`docs` 目录是没有问题了！但是 `src` 目录如何调整呢？我调整为 `test.md` 并没有成功解析！

<img width="469" alt="image" src="https://github.com/umijs/dumi/assets/75017711/998b8e49-28c0-4f3e-841c-98be78154acf">

<img width="707" alt="image" src="https://github.com/umijs/dumi/assets/75017711/eb66b7f4-86b0-435d-98ea-2eaa850ecc6d">

**Comment by PeachScript** [comment]
src 默认是资产文档目录，不会解析嵌套结构，所以保持 `src/test/index.md` 即可，会生成 `/components/test` 的路由

**Comment by ayangweb** [comment]
> src 默认是资产文档目录，不会解析嵌套结构，所以保持 `src/test/index.md` 即可，会生成 `/components/test` 的路由，这部分逻辑也可以参考上面约定式路由的文档

对，我是这个结构，昨天提 issues 就是这个结构，英文下它生成到 guide 的二级菜单去了！

**Comment by kzxuan** [comment]
我也有遇到 TOC 丢失的问题，感觉是不符合期望的。
可以尝试直接打开 dumi 官网的这个 tab：https://d.umijs.org/config，我这边大概率 TOC 全空白。
Chrome：114
dumi：2.2.4

**Comment by ayangweb** [comment]
@PeachScript 大佬啊，新版本的 `toc` 问题解决了，我这个啥情况啊，再帮我看看呗，英文下组件路由确实跑到指南路由的二级菜单了！

**Comment by PeachScript** [comment]
关键位置：https://github.com/umijs/dumi/blob/f6a51c1cf20155dc9895a18e7843c8a1a02bbb57/src/client/theme-api/useNavData.ts#L67
原因：这里的 parentPath 应当取 locale 前缀后一级，比如 `/en-US/components`，目前是把 `/en-US` 当成一级路由了
解法：link 在做 match 之前先把 locale 前缀去掉，可以用这个 util：https://github.com/umijs/dumi/blob/f6a51c1cf20155dc9895a18e7843c8a1a02bbb57/src/client/theme-api/useSidebarData.ts#L18
