### ISSUE TITLE
bug: `^2.2.4` 中 `toc: content` 异常！

### ISSUE THREAD

**Issue by ayangweb** [umijs/dumi#1816]
### Versions

- dumi: ^2.2.4
- node: v18.16.0 
- npm: 9.5.1
- OS: MacOS 12.6 M1
- Browser: Chrome 版本 115.0.5790.114（正式版本） (arm64)

### Steps to reproduce
[https://github.com/ayangweb/dumi-test](https://github.com/ayangweb/dumi-test)
### What is Expected?
正常第一次进入路由会显示！

<img width="1427" alt="image" src="https://github.com/umijs/dumi/assets/75017711/134cb5fc-608d-4b72-b66d-1c419d9fea70">

### What is actually happening?
当刷新页面或者来回切换语言会丢失！

顺便演示一下 #1815 `src` 目录下的 nav 的解析异常！跑到指南路由下了！

![iShot_2023-08-02_22 42 59](https://github.com/umijs/dumi/assets/75017711/38084cb6-7310-4b12-9df9-901ba13db7b8)

**Comment by xiyangranhongyan** [comment]
我遇到的问题是 第一次进入 toc 未显示，刷新或者切换到其他页面再切换回来正常

**Comment by PeachScript** [comment]
v2.2.5 已修复

**Comment by ayangweb** [comment]
> v2.2.5 已修复

测试过了，没有问题
