### ISSUE TITLE
dumi 打包后部署在github，publicPath针对子文件加载异常，加载路径缺失publichPath

### ISSUE THREAD

**Issue by wangwenbin0035** [umijs/dumi#1822]
### dumi 打包后部署在github，publicPath针对子文件加载异常，加载路径缺失publichPath，还请指出问题所在
本地环境： 
node: 16.14
npm: 8.3.1
操作系统： mac m1
dumi版本：^2.2.0
正常初始化 npx cteate-dumi 创建项目，选择site 模式
本地 .dumirc配置如下
```
export default defineConfig({
  outputPath: 'docs-dist',
  base: process.env.NODE_ENV === 'production' ? "/dumi-demo" : "/",
  publicPath: process.env.NODE_ENV === 'production' ? "/dumi-demo/" : "/",
  runtimePublicPath: {},
});

```
本地正常打包：yarn docs:build
发布部署至github: yarn deploy
部署结果：umi.js、umi.css 正常加载，但是子文件加载缺失publicPath,导致加载异常
![image](https://github.com/umijs/dumi/assets/30583349/5ee8ac48-ace6-4270-9846-991abde9949b)

**Comment by jianghai** [comment]
dumi v2.2.4 修复了，但 publicPath 不支持相对路径

**Comment by RudyDen** [comment]
> dumi v2.2.4 修复了，但 publicPath 不支持相对路径

最新 v2.2.5 版本部署在非根目录还是会publicPath缺失的问题。

![image](https://github.com/umijs/dumi/assets/11977468/7812fa66-2ae2-415e-8214-c8d4b8650fd0)
![image](https://github.com/umijs/dumi/assets/11977468/1a85e3a4-ba48-4a61-9f89-e8f9d404099d)
![image](https://github.com/umijs/dumi/assets/11977468/283d4859-e471-446a-85a5-d2500f796eea)

**Comment by PeachScript** [comment]
去掉 `runtimePublicPath` 配置项即可，如果项目真的需要这个配置，参考配置项说明确保 `window.publicPath` 有值：https://d.umijs.org/config#runtimepublicpath

**Comment by wangwenbin0035** [comment]
dumi 升级到 ^2.25，配置项 去掉runtimePublicPath，重新发布后，正常了

**Comment by warmhug** [comment]
@PeachScript 有什么配置项或脚本能设置 window.publicPath 吗？
