### ISSUE TITLE
如何判断当前路由页面是否符合404条件

### ISSUE THREAD

**Issue by KuangPF** [umijs/dumi#1823]
### Question
如何判断当前路由页面是否符合404条件
当前思路，使用 useOutlet 以及 useRouteMeta 信息来判断
1. 如果直接以 `/`路由访问，且没有 docs/index.md 或者 pages/index.(tsx | jsx), useOutlet 返回为 null， 但在多语言情况下以 `/index-en` 访问， `useOutlet` 会返回 Loading 组件
2. 如果自定义页面是 .tsx || .jsx，即使组件中render了一些内容，`useRouteMeta().texts`始终返回空数组，如果是 .md 的形式，则不会，所以也不能完全依据`useRouteMeta().texts`来判断是否为404

综上两条描述，没有找到一个合适的方法来判断，当前页面是否 404 页面。（官方虽然提供了404page页面自定义，但想拿到是否为 404 的 boolean 值做一些业务逻辑处理）

**Comment by PeachScript** [comment]
建议在 404 页面组件的生命周期钩子里加业务逻辑处理，这是成本最低的方案；如果一定要用函数式的形式判断 404，目前能想到的只有用 react-router 提供的 `matchRoutes` 方法，把所有路由传进去看返回的是不是 404 页面

**Comment by KuangPF** [comment]
thks
