### ISSUE TITLE
bug:  markdown 侧边栏显示异常

### ISSUE THREAD

**Issue by shiduobin** [umijs/dumi#1827]
### 问题描述

dumi 2.2.4，toc 显示有问题，刷新页面侧边栏不显示，官网显示就有问题

![image](https://github.com/umijs/dumi/assets/26728144/29e39f6e-94f8-4d8d-84c3-d194f0344f1c)

### Versions

- dumi: 2.2.4

**Comment by PeachScript** [comment]
Duplicate of #1816
