### ISSUE TITLE
打包依赖react-icons包文件过大，是否有优化方案

### ISSUE THREAD

**Issue by huangjihua** [umijs/dumi#1831]
### Question

![image](https://github.com/umijs/dumi/assets/3156292/e3d2ed92-ea9a-4cc3-b348-6820102cdfa8)

**Comment by PeachScript** [comment]
这个 issue 应该提给 react-icons，看官方的打包优化方案；举个例子 antd 5 会在文档里说支持 tree-shaking，antd 4 会告诉用户用 babel-plugin-import 实现按需加载
