### ISSUE TITLE
使用本地 ip 地址访问，一直刷新页面

### ISSUE THREAD

**Issue by hoboy0313** [umijs/dumi#1833]
### Versions

- dumi: 2.2.0
- node: 18.5.0
- npm: 8.12.1
- OS: MacOS 10.15.7
- Browser: Chrome 115.0.5790.170
- Umi 4.0.71

### Steps to reproduce

1. 在含有 dumi 的项目中启动 dev
2. 使用谷歌浏览器通过本地 ip 访问，如：172.18.188.234:8000
3.  疯狂刷新页面

### What is Expected?
期望正常访问

### What is actually happening?
抓包发现一直有一个 umi_ping 的接口持续调用并触发页面刷新。

![image](https://github.com/umijs/dumi/assets/40572453/80c89736-6327-4a67-bcb0-dfd3989f4ee1)

**Comment by hoboy0313** [comment]
localhost 访问是没问题，但是只要是非 localhost 就不行。
需求场景是，charles 抓包不抓取 localhost 流量，ip 也可以，映射去 127.0.0.1 的域名也可以。
但是，不管是本地 ip 还是 映射域名，都会触发刷新。

**Comment by PeachScript** [comment]
非 localhost 时可以关闭 HMR or 修改 SOCKET_SERVER 的地址，参考：https://d.umijs.org/config/env#hmr
