### ISSUE TITLE
bug: 自动API一直显示正在解析中，请稍等片刻，dumi版本2.2.5

### ISSUE THREAD

**Issue by Promisezhangbo** [umijs/dumi#1839]
![image](https://github.com/umijs/dumi/assets/104294824/096aa2f3-a76d-41fc-bb85-334c3d6fa69f)

dumi版本 2.2.5
一直展示属性定义正在解析中，稍等片刻。。。   请问各位大佬，这个是什么原因导致的呀

**Comment by PeachScript** [comment]
按 issue 模板补充最小复现步骤及仓库
