### ISSUE TITLE
样式与组件单独管理里，在 demo 里引用组件，无法像antd一样引用样式文件

### ISSUE THREAD

**Issue by git-lt** [umijs/dumi#184]
### Question

当组件的样式与js分开管理时，像 antd 这种，在demo中引用时，无法加载其 样式文件

### Sample Code

index.md

```tsx
import { XDescription } from 'rui';
// 这行报错：路径无法识别
import 'rui/XDescription/style';
```

**Comment by git-lt** [comment]
另外能否配置某些目录不参与 build，如

```
src
 Button
    demo
    index.md
    index.tsx
```
demo 目录存放的是 index.md 中引用的 jsx 文件，但是在 build 的时候 是否可以忽略掉 demo， demo不参与打包

**Comment by PeachScript** [comment]
这个产物是否应该打到 lib 或者 es 下，这样 dumi 就能识别到了

**Comment by Mr-jiangzhiguo** [comment]
demo：https://github.com/jsany/lean
