### ISSUE TITLE
bug: 自动API一直显示正在解析中，请稍等片刻，dumi版本2.2.5

### ISSUE THREAD

**Issue by Promisezhangbo** [umijs/dumi#1841]
### Versions

- dumi: 2.2.5
- node: v16.17.0
- npm: 8.15.0
- OS: macos
- Browser: google

### Steps to reproduce
按照 dumi1.x 升级到 2.x 的文档时，导致现在的自动API文档解析不出来
升级文档参考：https://d.umijs.org/guide/upgrading

### What is Expected?
预期是可以正常解析API文档

### What is actually happening?
![image](https://github.com/umijs/dumi/assets/104294824/aaad4cec-7631-4b1f-89de-c2a899dda262)

**Comment by Promisezhangbo** [comment]
试了好多遍，删除node_modules再重新安装包才生效，现在已经解决

**Comment by lk19940215** [comment]
可以看下你的 .dumirc.ts配置吗？  是多包管理？

**Comment by Promisezhangbo** [comment]
> 可以看下你的 .dumirc.ts配置吗？ 是多包管理？
都是基本配置，看起来只是解析时间比较久，发布之后解析还是挺快的，只是在本地有时候比较慢

<img width="672" alt="image" src="https://github.com/umijs/dumi/assets/104294824/06f006cc-3302-4e7e-98ef-e661509c9ed4">
