### ISSUE TITLE
bug: `^2.2.6` 中 `toc: content` 异常！

### ISSUE THREAD

**Issue by ayangweb** [umijs/dumi#1842]
### Versions

- dumi: 2.2.6
- node: 18.16.0
- npm: 9.5.1
- OS: MacOS 12.6 M1 Pro
- Browser: Chrome 版本 116.0.5845.96（正式版本） (arm64)

### Steps to reproduce

[https://github.com/ayangweb/dumi-test](https://github.com/ayangweb/dumi-test)

### What is actually happening?

切换路由丢失！

![iShot_2023-08-21_13 08 48](https://github.com/umijs/dumi/assets/75017711/b365ea4a-b52a-4daf-9523-7adfc13e6c3c)

**Comment by PeachScript** [comment]
关键位置：https://github.com/umijs/dumi/blob/8c91a070de7c06658bf796d724e58286e546c247/src/client/theme-default/slots/Toc/index.tsx#L41
原因：获取 DOM 的时候内容区域还未渲染完毕
