### ISSUE TITLE
.dumirc.js编译问题

### ISSUE THREAD

**Issue by 97vack** [umijs/dumi#1847]
我在.dumirc里配置了copy选项和chainWebpack想从构建的产物或者项目中复制文件夹到新的目录，但是npm run build 的时候，好像不起作用
![image](https://github.com/umijs/dumi/assets/33567483/3562d2f3-ff53-4604-a5a2-2fd6b186bf57)

**Comment by 97vack** [comment]
如果是在.fatherrc.ts里配置，但是.fatherrc.ts里没看到相关的配置选项

**Comment by PeachScript** [comment]
.dumirc 仅对 dumi 文档构建生效，不作用于 father

.fatherrc 不支持 copy 配置项，看你截图是为了调整输出目录，建议原始目录就按照输出目录来，或者通过 father 的 overrides 特性对子目录配置项做覆写，参考：https://github.com/umijs/father/blob/master/docs/config.md#overrides
