### ISSUE TITLE
`<code>`显示依赖文件的问题

### ISSUE THREAD

**Issue by Iixianjie** [umijs/dumi#185]
### Question
升级新版后发现使用`<code>`组件外部引入会在示例下显示组件的所有依赖，能否配置依赖文件显示的范围或只指定某些文件作为依赖

![image](https://user-images.githubusercontent.com/34636376/82276597-4d694c00-99b8-11ea-8e43-2d7c6c0244a6.png)

**Comment by Iixianjie** [comment]
感觉是配置了alias的原因

**demo.md**
```js
<code src="./base.tsx" />
```

**config.js**
```js
alias: {
    '@': path.resolve(__dirname, '../src'),
    'mylib/lib': path.resolve(__dirname, '../src/components'),
},
```

**./base.tsx**
```js
import React from 'react';
import Form from 'mylib/lib/form';
import Input from 'mylib/lib/input';
import Button from 'mylib/lib/button';
```

**Comment by PeachScript** [comment]
1.0.27 改进了这个问题，alias 指向的只要是本地文件，都不会被解析出来
