### ISSUE TITLE
能否支持第二层级的其他文件名.md文件的识别，以支持 同一文件夹下有多个同类型组件导出的场景

### ISSUE THREAD

**Issue by xiyangranhongyan** [umijs/dumi#1850]
### Question
目前只能识别index.md / README.md，并且会识别为同一个路径。
![image](https://github.com/umijs/dumi/assets/31724313/e5c29242-82a5-4b0c-a8aa-f94d537d900a)

如果有如下场景，一个点击文本跳转 一个点击图片跳转，此时 这边认为都是跳转类型组件，因此 在Link文件夹下(名为一个组件，但是实际上)导出 LinkText / LinkImage 两个组件，那么此时需要两个文档（index.md / link-image.md）且分组 来进行说明。

![image](https://github.com/umijs/dumi/assets/31724313/bc76a5ff-608b-4284-ad09-15e7ee3ef0ab)

### 期望
![image](https://github.com/umijs/dumi/assets/31724313/1e29a368-9175-4787-a860-f527be99bc80)

**Comment by PeachScript** [comment]
没有这个计划，既然它们是独立的组件，应当作为第一类成员把它们放在 `atomDirs` 目录下，只要配置相同的 group 仍然是会归类到一起的

作为参考，antd 的 DataPicker 和 TimePicker 也是放在第一层级的：https://github.com/ant-design/ant-design/tree/master/components

**Comment by xiyangranhongyan** [comment]
> 没有这个计划，既然它们是独立的组件，应当作为第一类成员把它们放在 `atomDirs` 目录下，只要配置相同的 group 仍然是会归类到一起的
> 
> 作为参考，antd 的 DataPicker 和 TimePicker 也是放在第一层级的：https://github.com/ant-design/ant-design/tree/master/components

先不说组件如何划分。想知道为什么第二级只去识别index.md/README.md，是识别所有的md文档会增加渲染复杂度还是别的原因？按照我的理解这一个过滤似乎不会有什么明显的提升。

**Comment by PeachScript** [comment]
和性能无关，这是 dumi 对原子资产目录结构的约定，组件与组件之间用文件夹分隔，以及组件源码、文档应当是一一对应的关系，这样组织会使得源码仓库更干净、统一

**Comment by xiyangranhongyan** [comment]
> 和性能无关，这是 dumi 对原子资产目录结构的约定，组件与组件之间用文件夹分隔，以及组件源码、文档应当是一一对应的关系，这样组织会使得源码仓库更干净、统一
好的 感谢回复

**Comment by xiyangranhongyan** [comment]
> 和性能无关，这是 dumi 对原子资产目录结构的约定，组件与组件之间用文件夹分隔，以及组件源码、文档应当是一一对应的关系，这样组织会使得源码仓库更干净、统一

好的，感谢回复
