### ISSUE TITLE
dumi版本2.2.6，在ant-design-pro项目中使用dumi搭建文档，怎么配置locales文件目录？

### ISSUE THREAD

**Issue by penglittlebai** [umijs/dumi#1851]
### Question
ant-design-pro项目中组件用到了国际化，dumi搭建文档引用改组件时，提示 export 'useIntl' (imported as 'useIntl') was not found in 'umi' ，
于是在.dumirc.ts 添加了插件 和 添加 locale配置 ：
plugins: [
    '@umijs/plugins/dist/locale',
 ],
 locale: {
    default: 'zh-CN',
 },

此时页面可以正常打开了，但是由于匹配不到正确的locales国际化配置文件，导致组件显示的 国际化id名称，例如 “publicComponents.table.query”
![image](https://github.com/umijs/dumi/assets/87426994/8d6677cd-a3b9-4643-b8ef-a92095893dd0)

同时 dumi框架自身相关的文字也变成了 国际化id名称，例如顶部搜索的placeholder显示 “header.search.placeholder”
![image](https://github.com/umijs/dumi/assets/87426994/9c887b21-48b7-4e50-a4c7-0c5f4da7fef1)

**Comment by PeachScript** [comment]
这个组合应该是不被支持的，分两点说明下：
1. dumi 虽然同属 Umi 体系，但不是所有 Umi 体系的插件都可以在 dumi 中使用的，其中 locale 插件就是不能用的，因为 dumi 内部也有 react-intl，和插件内置的 react-intl 会冲突
2. dumi 2 目前只提供独立运行模式，无法像 [dumi 1 的应用集成模式](https://v1.d.umijs.org/zh-CN/guide/advanced#umi-%E9%A1%B9%E7%9B%AE%E9%9B%86%E6%88%90%E6%A8%A1%E5%BC%8F)一样与 Umi 应用一起使用

如果你的初衷是为了管理应用内的组件，那么目前没有最佳实践，加上 dumi 也不支持依赖 Umi 框架能力的组件研发（即源码里存在 `import xxx from 'umi'`），所以这个问题是没有解决方案的
