### ISSUE TITLE
部署后页面内容严重丢失

### ISSUE THREAD

**Issue by Leexiaop** [umijs/dumi#1856]
### Question
dumi 1.1.0版本 site模式  部署完成后页面展示不全
![image](https://github.com/umijs/dumi/assets/34081591/ee9fe13f-1007-4b3c-b6ba-8437055a8066)
**只留下了一段文字，而docs/index.md中title部分的内容并没有显示**
### Sample Code

name: badger-ui

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './dist'

**Comment by PeachScript** [comment]
截图的链接查看源代码可以看出这不是 dumi 的产物，请自行检查 GitHub Pages 部署环节是否有误，比如 CI 流水线执行是否完成、分支是否正确、仓库是否正确等等
