### ISSUE TITLE
dumi dev 如何开启 HTTPS？

### ISSUE THREAD

**Issue by whinc** [umijs/dumi#1857]
### Question

本地开发时 dumi dev 如何开启 HTTPS？我查看了配置项文档，但是没有找到类似 HTTPS 的启用标识，在 issue 中也未找到相关问题。

**Comment by PeachScript** [comment]
文档里有对应配置项：https://d.umijs.org/config#https

**Comment by whinc** [comment]
> 文档里有对应配置项：https://d.umijs.org/config#https

我之前只在【环境变量配置】章节查找，原来在【编译配置】，感谢告知！
