### ISSUE TITLE
通过 resolve.atomDirs 配置的文档结构可以改为目录的层级吗

### ISSUE THREAD

**Issue by Seauning** [umijs/dumi#1859]
### Question
<img width="510" alt="image" src="https://github.com/umijs/dumi/assets/77973591/2f07c225-6933-4e99-8f21-758508a90def">
上面的这种文档结构可以改为目录的形式吗，像 advanced/animate、advanced/sltf
或者有别的配置支持这种目录结构吗

### Sample Code
```ts
import { defineConfig } from 'dumi';

// 指南
const guides = [
  { type: 'guide', dir: './guide' },
  // { type: 'guide/start', dir: './guide/start' },
  // { type: 'guide/start/content', dir: './guide/basic' },
];

export default defineConfig({
  themeConfig: {
    nav: [
      { title: '指南', link: 'guides' },
    ],
  resolve: {
    atomDirs: [
      ...guides,
    ],
  },
});

```

**Comment by PeachScript** [comment]
如果要生成类似 `advanced/animate` 的路由，合适的配置项是 `resolve: { docDirs: ['guide'] }` + 目录结构嵌套，类似：

```bash
guide
└── advanced
    └── animate.md
```

`atomDirs` 语义上是原子资产路由，仅用于 `src/Foo/index.md` 这类组件文档的识别，也不会识别嵌套结构
