### ISSUE TITLE
未找到 Foo 组件的属性定义

### ISSUE THREAD

**Issue by hhhhhello** [umijs/dumi#1870]
### Question
配置`apiParser `和`entryFile `后没有自动生成API表格，是写法上有什么问题吗？
![image](https://github.com/umijs/dumi/assets/22576500/764bd486-a148-4523-87d5-7870c40dd4b6)

### Sample Code
[https://github.com/hhhhhello/dumi-api](https://github.com/hhhhhello/dumi-api)

**Comment by Wxh16144** [comment]
https://d.umijs.org/guide/auto-api-table#%E8%87%AA%E5%8A%A8-api-%E8%A1%A8%E6%A0%BC 实验性 API 不太稳定。
我试了一下你的提供的 repo。 macos 用 pnpm 安装依赖可以正常解析。能力有限，关于自动表格 API 我也没去深入。
