### ISSUE TITLE
code的src支持解析md文件么？

### ISSUE THREAD

**Issue by NickJiangDev** [umijs/dumi#1871]
### Question

根目录的changelog想要放在文档的一个路由上
![image](https://github.com/umijs/dumi/assets/45092189/12954f4b-170c-4481-910d-335b28a2c1e8)

### Sample Code

```jsx
<code src="../../CHANGELOG.md"></code>
```
但并没有解析成功，期望得到一个解决方案

**Comment by PeachScript** [comment]
ref: https://d.umijs.org/guide/markdown#embed
