### ISSUE TITLE
根据官网创建项目，然后进行打包。本地打开打包的文件是空白

### ISSUE THREAD

**Issue by cangsnage** [umijs/dumi#1877]
``### Question
本地打开打包的docs-dist文件，页面打开空白
### Sample Code
`import { defineConfig } from 'dumi';
export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    name: '文档',
  },

});
`

**Comment by PeachScript** [comment]
构建产物不支持用 file:// 形式直接访问 index.html，需要使用 http-server 或站点托管服务托管，比如 nginx 或 [GitHub Pages](https://d.umijs.org/guide/faq#%E9%83%A8%E7%BD%B2%E5%88%B0-github-pages)

**Comment by peterczg** [comment]
dumi配置文件设置`exportStatic: false`，然后重新打个包试试
