### ISSUE TITLE
本地插件应该怎么使用

### ISSUE THREAD

**Issue by cangsnage** [umijs/dumi#1879]
### Question
想问下本地自己单独写一个插件应该怎么写，怎么使用呢
### Sample Code
![image](https://github.com/umijs/dumi/assets/25116493/44e13793-aa5e-4de7-8207-7c6ea658cd42)
看文档上写直接再plugin的文件写还是文件下写呢。而且不需要再配置么？主要没看懂。有没有实例demo链接。
谢谢

**Comment by Wxh16144** [comment]
> 直接再plugin的文件写还是文件下写呢

都可以，`plugin.ts` 或者 `plugin/my-plugin.ts` 都会被加载。

> 有没有实例demo链接

可以参考我这个：https://github.com/Wxh16144/dumi-debug-app/blob/630ac176f56b9553772c906cbcf8562725419fd8/.dumi/theme/plugin.ts

**Comment by cangsnage** [comment]
> demo

问下md文件怎么使用这个插件呢

**Comment by PeachScript** [comment]
没看懂你的问题，需要写插件的具体场景是什么

**Comment by cangsnage** [comment]
> 没看懂你的问题，需要写插件的具体场景是什么

就是类似官方的tab切换插件，但是我又没找到这个插件的源码

**Comment by PeachScript** [comment]
Tab 是约定式的：https://d.umijs.org/guide/page-tab

除非你要注册一个纯 React 写的全局 Tab 才需要用本地插件，参考：https://github.com/umijs/dumi/blob/master/examples/normal/plugin.ts
