### ISSUE TITLE
左侧目录导航

### ISSUE THREAD

**Issue by cangsnage** [umijs/dumi#1884]
### Question
左侧目录导航的数据是怎么获取的，

### Sample Code
![image](https://github.com/umijs/dumi/assets/25116493/62f74175-852d-4298-8113-1d540da19062)
我看用的是这个组件，但是我想自定义目录导航的样式和布局问题，想自己写一个组件，想问下这个目录导航数据是怎么获取的呢，
![image](https://github.com/umijs/dumi/assets/25116493/e4220180-8f04-4c99-bb52-3d39b1fc5be6)

**Comment by PeachScript** [comment]
参考内置的 slot 实现即可：https://github.com/umijs/dumi/blob/72ece4cb622947bef82624111ca2ac62d98f6121/src/client/theme-default/slots/Sidebar/index.tsx#L9

**Comment by cangsnage** [comment]
> 参考内置的 slot 实现即可：
> 
> https://github.com/umijs/dumi/blob/72ece4cb622947bef82624111ca2ac62d98f6121/src/client/theme-default/slots/Sidebar/index.tsx#L9

![image](https://github.com/umijs/dumi/assets/25116493/d50f6729-4867-470d-87f8-191572c1ae7a)
获取只有头部导航栏的数据，我想获取markdown里面导航栏的数据
![image](https://github.com/umijs/dumi/assets/25116493/79360f58-b43d-4768-9faa-a0eb24849407)

**Comment by PeachScript** [comment]
这个是 TOC，对应的 slot：https://github.com/umijs/dumi/blob/77941aa6dac393145efc48550765985aa1bea98f/src/client/theme-default/slots/Toc/index.tsx#L55
