### ISSUE TITLE
sidebar 只对子路由有效么

### ISSUE THREAD

**Issue by cangsnage** [umijs/dumi#1887]
### Question
我想问下sidebar 如果只对子路由有效，没办法设置对首页有效的话，那有什么办法把首页重定向子路由呢？

### Sample Code
![image](https://github.com/umijs/dumi/assets/25116493/828278ed-4fa3-4c0c-b8f6-3d7b3978465c)
z怎么对首页生效呢

**Comment by PeachScript** [comment]
sidebar 展示的是同一导航下的其他兄弟页面，比如 `/a/a1` 和 `/a/a2`，首页的兄弟页面就是一级导航，所以没有 sidebar 的概念，也无法配置展示

> 有什么办法把首页重定向子路由呢？

dumi 的定位是静态站点框架，首页是基本要素，所以框架本身不会提供重定向首页的配置，如果有特殊需要可以自己写运行时插件改路由表：https://d.umijs.org/config/runtime#patchclientroutes
