### ISSUE TITLE
HTTPS会重定向到HTTP

### ISSUE THREAD

**Issue by frhandlee** [umijs/dumi#1896]
### Question
我将打包后的页面部署到通过IIS 提供的HTTPS域名下，会自动重定下到http，有谁遇到过吗
### Sample Code
配置文件如下

import { defineConfig } from 'dumi';

export default defineConfig({
  outputPath: 'doc',
  base: '/doc/',
  publicPath: process.env.NODE_ENV === "production" ? "/doc/" : "/",
  themeConfig: {
    name: 'emrn-ui组件库文档',
    logo: 'https://gw.alipayobjects.com/zos/bmw-prod/d3e3eb39-1cd7-4aa5-827c-877deced6b7e/lalxt4g3_w256_h256.png',
  },
  favicons: ['https://gw.alipayobjects.com/zos/bmw-prod/d3e3eb39-1cd7-4aa5-827c-877deced6b7e/lalxt4g3_w256_h256.png'],
  resolve:{
      codeBlockMode: 'passive'
  }

});

**Comment by PeachScript** [comment]
dumi 不会做协议重定向的操作，有可能和域名解析服务、IIS 配置有关，需要自行排查

**Comment by frhandlee** [comment]
> dumi 不会做协议重定向的操作，有可能和域名解析服务、IIS 配置有关，需要自行排查

谢谢 我也是这么觉得的，但是别的项目就不会，我自己再看看

**Comment by cx91** [comment]
> > dumi 不会做协议重定向的操作，有可能和域名解析服务、IIS 配置有关，需要自行排查
> 
> 谢谢 我也是这么觉得的，但是别的项目就不会，我自己再看看

你好，你解决这个问题没呢，我们这边也遇到这个问题了，部署用的nginx,  提供的HTTPS域名中途有次跳转到http地址导致在线demo加载不出来

**Comment by hanfei7788** [comment]
> > > dumi 不会做协议重定向的操作，有可能和域名解析服务、IIS 配置有关，需要自行排查
> > 
> > 
> > 谢谢 我也是这么觉得的，但是别的项目就不会，我自己再看看
> 
> 你好，你解决这个问题没呢，我们这边也遇到这个问题了，部署用的nginx, 提供的HTTPS域名中途有次跳转到http地址导致在线demo加载不出来
我也碰到相同的问题了，请问您解决了吗
