### ISSUE TITLE
umi1.0升级到umi2.0后, group取消了，url链接如何顺滑平移？

### ISSUE THREAD

**Issue by fanhualei** [umijs/dumi#1900]
### Question

umi1.0升级到umi2.0后, group取消了，url链接如何顺滑平移？

#### 当前的目录结构
```
pages
- umi
-- a.md 
-- b.md
-- c.md
```
#### umi1.0  通过group=base可以设置成的url

```
/umi/base/a
/umi/base/b
/umi/base/c
```

#### umi2.0  通过group取消了，url变成下面的样子，外网的链接都找不到了
```
/umi/a
/umi/b
/umi/c
```

## umi中有没有一种配置，可以将/umi/base/a 自动跳转到 /umi/a  ？

我现在想到的办法是通过nginx进行跳转。

**Comment by PeachScript** [comment]
建议 `umi/a.md` 移动为 `umi/base/a.md`，url 就正确了
