### ISSUE TITLE
bug: 打包 引入antd包报错

### ISSUE THREAD

**Issue by ReactLearningTrip** [umijs/dumi#191]
peerDependencies 同级依赖antd不起作用知道什么情况吗？
我的打包组件：
组件1：引用的react，指向了同级文件包
组件2：引入antd包，没有指向同级文件包
https://github.com/ReactLearningTrip/example

**Comment by ReactLearningTrip** [comment]
好像就是环境问题，要不就是包冲突，要不就是webpack配置有问题，我的主项目（umi）能用打包的组件，但是子项目是自己配置的

**Comment by Mr-jiangzhiguo** [comment]
demo： https://github.com/jsany/lean

**Comment by GKLL** [comment]
我也引入报错。解决了吗？

**Comment by PeachScript** [comment]
link 本质上是软连接，webpack 默认是从软连接的实际位置去 resolve 依赖的，参考：https://webpack.js.org/configuration/resolve/#resolvesymlinks

issue 关闭
