### ISSUE TITLE
load typescript lib fail! 

### ISSUE THREAD

**Issue by wohy** [umijs/dumi#1910]
### Question

执行 npm run docs:build 时，一直报一下错误，导致组件文档的api表格也加载不出来

load typescript lib fail! Error: 加载失败: (0)[https://unpkg.com/lib/lib.esnext.d.ts [".d.ts",".ts",".tsx","/index.d.ts","/index.ts","/index.tsx","",".js",".jsx","/index.js","/index.jsx"]]

**Comment by PeachScript** [comment]
如果是非 Windows 设备请提供最小复现仓库，如果是 Windows 设备请先手写 API 表格，该功能暂时不支持 Windows 系统

**Comment by wohy** [comment]
> 如果是非 Windows 设备请提供最小复现仓库，如果是 Windows 设备请先手写 API 表格，该功能暂时不支持 Windows 系统

好的谢谢，目前是windows系统，确实关了这个功能就正常了，请问知道啥时候可以支持吗？手写太费劲了哈哈

**Comment by PeachScript** [comment]
不确定，目前没有精力投入，如有进展会在这条 issue 里同步 #1476 ，该 issue 关闭
