### ISSUE TITLE
bug:  dumi 2.0使用npx create-dumi初始化项目失败

### ISSUE THREAD

**Issue by jiebaibai** [umijs/dumi#1916]
### Versions

- dumi: 2.0
- node: 14.19.1
- npm: 6.14.16
- OS: mac
- Browser: 

### Steps to reproduce
执行npx create-dumi和npm i都会报错：Error: Cannot find module 'umi/dist/cli/node'
<img width="744" alt="image" src="https://github.com/umijs/dumi/assets/10113095/5b9cf0fd-9cf4-40f2-bda2-ed31c0c0dc72">

**Comment by PeachScript** [comment]
v2.2.12 已修复

**Comment by hanyao426** [comment]
该问题还是存在
<img width="813" alt="image" src="https://github.com/umijs/dumi/assets/70302443/7fe8fd9c-c8b3-4c3f-b639-485e08264a00">

**Comment by PeachScript** [comment]
> 该问题还是存在

感谢反馈，验证的时候漏了 dev，v2.2.12 已修复

**Comment by jiebaibai** [comment]
2.2.12脚手架初始化的时候还是有问题
<img width="621" alt="image" src="https://github.com/umijs/dumi/assets/10113095/ab4c0e67-71ee-480a-98a4-af5c867a4a6c">

**Comment by PeachScript** [comment]
> 2.2.12脚手架初始化的时候还是有问题

重装下依赖试试，刚 Umi 4.0.84 的包影响了 dumi 的逻辑，我先回滚了

**Comment by elevensky** [comment]
好了么？

**Comment by hanyao426** [comment]
可以了，2.2.12跑起来了
<img width="547" alt="image" src="https://github.com/umijs/dumi/assets/70302443/db3d3996-41e8-47b5-98b2-2176ae4bd81d">

**Comment by jiebaibai** [comment]
执行npx create-dumi还是不行
Error: Cannot find module '../dumi__theme/ContextWrapper'

**Comment by jiebaibai** [comment]
> > 2.2.12脚手架初始化的时候还是有问题
> 
> 重装下依赖试试，刚 Umi 4.0.84 的包影响了 dumi 的逻辑，Umi 已经回滚了

重装依赖也不行呢，还是有这个问题

**Comment by PeachScript** [comment]
是不是有 lock 文件，我这里使用 create-umi 重新初始化是 OK 的

**Comment by jiebaibai** [comment]
> 是不是有 lock 文件，我这里使用 create-umi 重新初始化是 OK 的

不是呢~ 
操作步骤：
node:14.19.1
执行npx create-dumi
选择React Library
选择npm
<img width="316" alt="image" src="https://github.com/umijs/dumi/assets/10113095/0c140cae-39b9-492a-afe4-ae6c5d9a7e58">

报错：
<img width="494" alt="image" src="https://github.com/umijs/dumi/assets/10113095/474b7956-273a-464c-89d0-4fb00c0bff68">

**Comment by 121595113** [comment]
> > 是不是有 lock 文件，我这里使用 create-umi 重新初始化是 OK 的
> 
> 不是呢~ 操作步骤： node:14.19.1 执行npx create-dumi 选择React Library 选择npm <img alt="image" width="316" src="https://user-images.githubusercontent.com/10113095/270942532-0c140cae-39b9-492a-afe4-ae6c5d9a7e58.png">
> 
> 报错： <img alt="image" width="494" src="https://user-images.githubusercontent.com/10113095/270942822-474b7956-273a-464c-89d0-4fb00c0bff68.png">

+1

**Comment by yangyi7** [comment]
<img width="553" alt="image" src="https://github.com/umijs/dumi/assets/134352029/1d8a5975-4066-4360-9dfb-c3f943a8d514">
还是有这个问题呀

**Comment by PeachScript** [comment]
> <img alt="image" width="553" src="https://user-images.githubusercontent.com/134352029/273385071-1d8a5975-4066-4360-9dfb-c3f943a8d514.png">

如果遇到截图的问题，需要检查安装的 umi 版本是否为 4.0.83，这个问题是 4.0.84 带入的，现在 umi latest tag 已经回退到 4.0.83 了，dumi 没有锁 umi 版本，正常情况下不会安装到 umi 4.0.84，除非有私有源没有同步到 npm 源的 tag 或者项目有 lock 文件

**Comment by houchaowei** [comment]
解决方法；
模板创建完项目之后，把 node_modules 和 lock 文件全都删一下，然后，在 package.json中将 dumi 的版本号改为^2.2.12,并增加 umi:"4.0.83", 切记不要加 ^，重新 install 就 ok 了

**Comment by PeachScript** [comment]
> 把 node_modules 和 lock 文件全都删一下，然后，在 package.json中将 dumi 的版本号改为^2.2.12,并增加 umi:"4.0.83", 切记不要加 ^，重新 install 就 ok 了

原来如此，所以即便切了 latest tag 还会安装到 4.0.84 的原因是 create-dumi 时如果选择 pnpm client 会默认 `up -L` 安装到最大的版本号

这样的话临时方案应该 rm -rf pnpm-lock.yaml 后重新安装就行了，不需要在 package.json 里声明 umi？

最终的解法等 #1935 合并，预计明天下午发版

**Comment by houchaowei** [comment]
> > 把 node_modules 和 lock 文件全都删一下，然后，在 package.json中将 dumi 的版本号改为^2.2.12,并增加 umi:"4.0.83", 切记不要加 ^，重新 install 就 ok 了
> 
> 原来如此，所以即便切了 latest tag 还会安装到 4.0.84 的原因是 create-dumi 时如果选择 pnpm client 会默认 `up -L` 安装到最大的版本号
> 
> 这样的话临时方案应该 `rm -f pnpm-lock.yaml` 后重新安装就行了，不需要在 package.json 里声明 umi？
> 
> 最终的解法等 #1935 合并，预计明天下午发版

对

**Comment by Promisezhangbo** [comment]
> 解决方法； 模板创建完项目之后，把 node_modules 和 lock 文件全都删一下，然后，在 package.json中将 dumi 的版本号改为^2.2.12,并增加 umi:"4.0.83", 切记不要加 ^，重新 install 就 ok 了

这个也没有效果，dumi build 会卡住，请问下这种情况需要怎么操作
<img width="481" alt="image" src="https://github.com/umijs/dumi/assets/104294824/c2952f20-d124-4baf-9cf2-3615a00311f0">

**Comment by PeachScript** [comment]
> 最终的解法等 #1935 合并，预计明天下午发版

v2.2.13 已修复

**Comment by PeachScript** [comment]
> dumi build 会卡住

不是同一个问题，另开 issue 提供复现仓库

**Comment by ParseDark** [comment]
same issue when i try to run "npx create-dumi"

---

node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'umi/dist/cli/node'
Require stack:

**Comment by ParseDark** [comment]
> 解决方法； 模板创建完项目之后，把 node_modules 和 lock 文件全都删一下，然后，在 package.json中将 dumi 的版本号改为^2.2.12,并增加 umi:"4.0.83", 切记不要加 ^，重新 install 就 ok 了

This solution still work.
