### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by AaronWing** [umijs/dumi#1920]
<img width="774" alt="image" src="https://github.com/umijs/dumi/assets/22290329/e056e8ee-ec8f-4dae-8d98-842f7bc12133">

**Comment by 121595113** [comment]
抱错+1

**Comment by PeachScript** [comment]
提供下最小可复现仓库

**Comment by PeachScript** [comment]
v1.1.54 已修复

**Comment by sdjalft** [comment]
v1.1.54版本依然存在这个问题😭😭😭
![image](https://github.com/umijs/dumi/assets/52817273/a7b75aac-80d4-48c1-8993-5571d5d0fa70)
看起来依然存在多个版本的babel。

**Comment by sdjalft** [comment]
![image](https://github.com/umijs/dumi/assets/52817273/ca7c9da5-e369-4eef-a23b-8aa2408e5044)
编译后依然存在类似的语句，
![image](https://github.com/umijs/dumi/assets/52817273/ed418d35-baea-4f81-99e5-0a831643a6d7)

是不是这种写法导致的呢（因为我发现只有这种引入方法会生成错误语句）

**Comment by PeachScript** [comment]
> 是不是这种写法导致的呢

是的，现在只判断了函数和变量，欢迎来个 PR 修复

**Comment by sdjalft** [comment]
> > 是不是这种写法导致的呢
> 
> 是的，现在只判断了函数和变量，欢迎来个 PR 修复，可参考 #1926

![image](https://github.com/umijs/dumi/assets/52817273/b55a3d7e-2d07-4b14-844b-a6d473c7c6e2)
可以的，目前暂时先这样解决了
