### ISSUE TITLE
bug: 移动端的下拉菜单会闪退

### ISSUE THREAD

**Issue by Immortalsby** [umijs/dumi#1923]
打开官网-F12-切换成移动端-点击版本号

会发现版本号那边直接就闪退了，用手机看是一样的效果，这个是已知bug吗？

**Comment by jeffwcx** [comment]
看起来是点透了，我有空会修修

**Comment by Wxh16144** [comment]
应该是预期效果🤔

**Comment by jeffwcx** [comment]
> 应该是预期效果🤔

不是，事件冒泡上去了，没做捕获
