### ISSUE TITLE
bug: demo在独立页面打开 然后使用手机模式查看 字很小 

### ISSUE THREAD

**Issue by 18355166248** [umijs/dumi#1928]
### Version

2.2.10

### OS Version

macOS 12.6

### Node.js Version

v16.20.0

### Browser Version

Google Chrome  117.0.5938.132

### Link to minimal reproduction

http://localhost:8000

### Steps to reproduce

![image](https://github.com/umijs/dumi/assets/28000939/ab37e255-7e8b-4402-aeff-9f7965ec2379)

![image](https://github.com/umijs/dumi/assets/28000939/9491c92a-bffe-4109-a3cd-68bc592c9e31)

### What is expected?

期望 viewport 设置成1 不然字太小了 

这个是不开手机预览展示的效果
![image](https://github.com/umijs/dumi/assets/28000939/9d8036a8-fbff-4d4d-9580-8ca69a6d5076)

### What is actually happening?

字太小

**Comment by PeachScript** [comment]
非 bug，移动端主题默认启用 750 高清方案，如果你要用 px 作为单位，把高清方案禁用即可，参考：https://d.umijs.org/theme/mobile#hd
