### ISSUE TITLE
bug: 从1.x升级到2.x出现 "Cannot find module '../dumi__theme/ContextWrapper'"错误

### ISSUE THREAD

**Issue by ZhangDaZongWei** [umijs/dumi#1932]
### Version

2.2.12

### OS Version

macOS 13.5.1

### Node.js Version

v16.15.0

### Browser Version

Chrome 117.0.5938.132

### Link to minimal reproduction

无

### Steps to reproduce

1. 按照该指示进行操作：https://d.umijs.org/guide/upgrading#%E6%96%B9%E6%A1%88%E4%BA%8C%E6%89%8B%E5%8A%A8%E5%8D%87%E7%BA%A7
2. 执行 `npm run dev`

### What is expected?

正常运行

### What is actually happening?

出现错误：
Error: Cannot find module '../dumi__theme/ContextWrapper' from 'xxx/.dumi/pages'

**Comment by Wxh16144** [comment]
大概率是依赖了 dumi1.x 的主题包的问题， 可以提供更多的消息吗？

**Comment by ZhangDaZongWei** [comment]
> 大概率是依赖了 dumi1.x 的主题包的问题， 可以提供更多的消息吗？

更多的信息是指哪些呢？

**Comment by gaogaoinvincible** [comment]
same error

**Comment by Promisezhangbo** [comment]
这个降dumi版本有用嘛：如 2.1.x  ？？？

**Comment by PeachScript** [comment]
v2.2.13 已修复
