### ISSUE TITLE
feat: 有自动化部署的自有服务器的教程吗

### ISSUE THREAD

**Issue by GuanErShuiShou** [umijs/dumi#1934]
### What problem does this feature solve?

自动化部署到自有服务器

**Comment by PeachScript** [comment]
没有教程，可能可行的思路是使用代码托管平台的 webhook，在代码 push 的时候通知你的服务器，然后你的服务器自动拉最新代码最构建 + 放置到 http-server 的目录下

具体细节需要借助搜索引擎寻找可行的实现，以及后续使用类问题请使用 [Discussions](https://github.com/umijs/dumi/discussions) 而不是 issue
