### ISSUE TITLE
bug: 访问文档页面index.html会重定向到404页面

### ISSUE THREAD

**Issue by GuoYongfeng** [umijs/dumi#1945]
### Version

2.2.5

### OS Version

macOS

### Node.js Version

20.0

### Browser Version

Chrome latest

### Link to minimal reproduction

https://github.com/umijs/dumi/issues

### Steps to reproduce

`idumirc.ts` 配置如下：

```
  base: isProd ? '/docs/' : '/',
  outputPath: './dist',
  publicPath: isProd ? '/docs/' : '/',
```

### What is expected?

访问 /docs/index.html 的时候需要能正常访问。

### What is actually happening?

异常场景：

访问 `/docs/index.html` 的时候，会重定向到 404 页面。
但是点击路由页签访问 /`docs/` 正常。

访问 `/docs/introduce/introduce/index.html`，会重定向到 404 页面。
但是点击导航页签访问正常，浏览器地址栏显示的是 `/docs/introduce/introduce`

**Comment by GuoYongfeng** [comment]
你好，我查看之前关闭 issue 中提到的相关问题。

>  dumi 2 对 hash 路由的支持不完整，锚点之类的会跳转异常，建议用默认的 browser 路由.

所以特意去掉了 history 的配置，采用默认的 browser 模式。但是：
- 访问 ${host}/docs/introduce/design-rules 默认会重定向到 ${host}/docs/introduce/design-rules/index.html 并提示404
- 而通过点击导航的方式是访问正常，显示的路由是 ${host}/docs/introduce/design-rules 

所以如何能去掉这个重定向到 index.html 的配置。

**Comment by PeachScript** [comment]
dumi 的 dev server 没有重定向 `/abc` 到 `/abc/index.html` 的逻辑，也不支持通过 `/abc/index.html` 访问到 `/abc`，因为路由表里只有 `/abc`；如果是部署后出现的情况，大概率是你使用的站点托管服务做的重定向

**Comment by cangsnage** [comment]
> '/docs/

![image](https://github.com/umijs/dumi/assets/25116493/42c36fc5-51a7-4d4c-b6aa-36dffb873190)
设置这样配置为啥打包报错
![image](https://github.com/umijs/dumi/assets/25116493/9c2e1609-de95-4e62-94f8-44c215c82a22)
无效的呢
