### ISSUE TITLE
bug: dumi 和 umi 配合使用引用路径不正确而报错

### ISSUE THREAD

**Issue by MinJieLiu** [umijs/dumi#195]
dumi 和 umi 配合使用：

src/.umi/core/routes.ts 中引用路径不正确，少写了一层目录

![image](https://user-images.githubusercontent.com/6167727/82756914-a1888c00-9e0f-11ea-8b9b-6742986fecd7.png)

此处应该是 `'../../../node_modules` `'../../../README.md'`

从而报错

```
 ERROR  Failed to compile with 3 errors                                                                                                                                                                                            22:30:48

These relative modules were not found:

* ../../README.md in ./src/.umi/core/routes.ts
* ../../node_modules/@umijs/preset-dumi/lib/themes/default/layout.js in ./src/.umi/core/routes.ts

```

### Versions

- dumi:1.0.26
- node:12
- npm:
- OS:Windows 10
- Browser:chrome

### Steps to reproduce

umi 约定式路由项目中引入 dumi。存在 pages 目录。

`defineConfig` 中 routes 设置为 [] 就不报错了，但组件文档也没了

手动将临时目录路径改掉，能正常运行。

### What is Expected?

所处目录层级应多写一层

**Comment by MinJieLiu** [comment]
mac 下这个问题依然存在，配置了 `resolve` 也不行

**Comment by MinJieLiu** [comment]
https://github.com/umijs/dumi/blob/c8cfef9564e77ef7d0f148acafd0eb5fe6a8aaf9/packages/preset-dumi/src/routes/getRouteConfig.ts#L41

这里用的是`absPagesPath`。我感觉应该是`absSrcPath`

**Comment by MinJieLiu** [comment]
https://github.com/umijs/dumi/issues/160

**Comment by MinJieLiu** [comment]
现象：倘若 更名 pages 目录，则生成的路径为绝对路径

**Comment by MinJieLiu** [comment]
https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/routes/getRouteConfig.ts#L41

改为

```js
slash(path.join(__dirname, '../themes/default/layout.js')),
```

和具体的路由地方改成绝对路径，然后就能跑起来了

**Comment by MinJieLiu** [comment]
https://github.com/umijs/dumi/pull/196

**Comment by PeachScript** [comment]
v1.0.31 已修复该问题，感谢反馈
