### ISSUE TITLE
bug: md 的 table 格式里 TS 的泛型解析报错

### ISSUE THREAD

**Issue by RedJue** [umijs/dumi#1950]
### Version

2.2.13

### OS Version

macOS 14.0

### Node.js Version

16.14.0

### Browser Version

Chorme  118.0.5993.88

### Link to minimal reproduction

无

### Steps to reproduce

![image](https://github.com/umijs/dumi/assets/21119589/23d434eb-3a85-40ca-928c-b3887b67d920)
在 API 文档里添加泛型类型

### What is expected?

不报错，正常解析

### What is actually happening?

<img width="594" alt="image" src="https://github.com/umijs/dumi/assets/21119589/33de9381-640f-4176-b0c4-dc7858cb0137">
解析报错

### Any additional comments? (optional)

应该是 table 里 TS 的泛型没有处理解析，当成 html 元素了，加转义`FlattenOptionData\<BaseOptionType\>` 之后能正常解析。

**Comment by PeachScript** [comment]
`<>` 是需要手动转义成 `&lt;&gt;`的，否则会识别成自定义组件做渲染；GitHub 的 Markdown 转换也不会自动做转义，而是把它当做不识别的 HTML 标签过滤掉
