### ISSUE TITLE
feat:  渲染MarkDown的代码导出为一个React组件

### ISSUE THREAD

**Issue by consistent-k** [umijs/dumi#1966]
### What problem does this feature solve?

这样可以再任意React项目中使用dumi的渲染md的能力，也可以将这套规范推广给更多的开发者。

**Comment by PeachScript** [comment]
受限于投入精力及使用场景，暂无此计划，如果你有兴趣和精力，欢迎在 Discussion 里创建详细的 RFC 进行讨论
