### ISSUE TITLE
feat: 想问下这个页面滚动怎么给子菜单赋值active？

### ISSUE THREAD

**Issue by cangsnage** [umijs/dumi#1967]
### What problem does this feature solve?

feat: 想问下这个页面滚动怎么给子菜单赋值active？
![image](https://github.com/umijs/dumi/assets/25116493/29236efa-e119-4b5b-ae8e-20cec18802dc)

### Possible Solution (optional)

feat: 想问下这个页面滚动怎么给子菜单赋值active？

**Comment by PeachScript** [comment]
dumi 的锚点 active 是自动滚动高亮的，看截图不是 dumi 的项目
