### ISSUE TITLE
feat: bug: 问下打包部署项目使用hash为啥打开时空白页面？也没有任何报错的问题

### ISSUE THREAD

**Issue by cangsnage** [umijs/dumi#1968]
### What problem does this feature solve?

![image](https://github.com/umijs/dumi/assets/25116493/cf62fe00-7d1f-4ade-a85b-e99777d0e704)
这样配置的

**Comment by PeachScript** [comment]
feat issue 模板仅接受 feature request，反馈问题请使用 bug issue 模板并提供完整复现信息
