### ISSUE TITLE
feat: 如何配置支持 css inline 引入

### ISSUE THREAD

**Issue by rowthan** [umijs/dumi#1971]
### What problem does this feature solve?

如何配置可以支持 css inline 引入？
`import css from './style.scss?inline'
`

### Possible Solution (optional)

尝试通过修改 webpack ，但无效。
```chainWebpack(config) {
    config.module
      .rule('scss')
      .test(/\.scss$/)
      .oneOf('normal')
      .use('style-loader')
      .loader('style-loader')
      .end()
      .use('css-loader')
      .loader('css-loader')
      .end()
      .use('sass-loader')
      .loader('sass-loader')
      .end()
      .end()
      .oneOf('inline')
      .resourceQuery(/inline/)
      .use('raw-loader')
      .loader('raw-loader')
      .end()
      .use('sass-loader')
      .loader('sass-loader')
      .end();
  },```

**Comment by PeachScript** [comment]
应该是命中 dumi 内置的 loader 了，你要对已经存在的 scss rule 做修改，或者参考 Webpack 文档中 loader inline 的用法

另外 issue 仅接受 bug 和 feature request，使用咨询请使用 disussion

**Comment by mengxinssfd** [comment]
@rowthan 遇到了同一个问题，能说下你最后是如何处理的吗

**Comment by mengxinssfd** [comment]
找到了，`import css from '!!raw-loader!sass-loader!postcss-loader!./index.scss'` 有用！
