### ISSUE TITLE
bug: Markdown文件中引用本地图片链接，cssPublicPath 不生效

### ISSUE THREAD

**Issue by xuliuzhu1834** [umijs/dumi#1972]
### Version

2.2.14

### OS Version

macOs

### Node.js Version

18.12.1

### Browser Version

chrome

### Link to minimal reproduction

无

### Steps to reproduce

文件： docs/xxx/xx.md

图片位置： public/a/b.jpeg

md文件编写示例：
```
# 图片示例
![img](/a/b.jpeg)
```
---
defineConfig({
...
cssPublicPath: '/api/web/',
publicPath： '/api/web/'
})

### What is expected?

图片正常显示

### What is actually happening?

图片并没有显示， 查看html元素， 发现img标签中的地址 仍然是 "/a/b.jpeg", cssPublicPath和publicPath都无作用

### Any additional comments? (optional)

Markdown中引用本地文件地址怎么样才能让publicPath生效？

**Comment by PeachScript** [comment]
非 bug，`/` 开头的资源请求不会当做本地资源处理，因为不确定开发者的真实意图，它可能指向的是同域名下某个子路径中的资源

解法：明确使用相对路径引用本地图片，比如 `./assets/sample.jpg`

**Comment by xuliuzhu1834** [comment]
@PeachScript 感谢大佬回复， 对此我还是有疑问，对于部署到服务器中时，相对路径是无法满足publicPath的,
配置是这样的

````
defineConfig({
...
base: '/dumi/a/'
publicPath: '/api/web/{version}'
})
````

其中publicPath是在ci环境中生成的。 此时
1. 用户无法明确路径
2.相对路径会使得路径变成"/dumi/a/assets/sample.jpg",此时则是错误的。

markdown中是否有能力引入publicPath，支持用户配置，
比如在markdown引入本地文件时可以这么写
[sample.png]({{publicPath}}assets/sample.jpg)

**Comment by nanianlisao** [comment]
dumi推荐的将静态资源放到 public 文件夹下， 并可以直接使用 / 进行访问
看起来 似乎只是因为 umi的默认行为， 会将 public 进行 copy，这并不会受到 publicPath  和 base 影响。

这个逻辑导致非独立部署情况下，资源无法正确加载。

**Comment by PeachScript** [comment]
> 对此我还是有疑问，对于部署到服务器中时，相对路径是无法满足publicPath的

这里的相对路径不是产物的最终路径，而是指在文件系统中静态资源相对于 Markdown 文件的路径，webpack 编译后会变成最终资源路径，并在请求时带上 publicPath，可以将其等价于在 JS 文件中编写 `import url from './assets/logo.png'`

上面 cannot resolve 的错误需要看下相对路径是否正确
