### ISSUE TITLE
bug: code embed标签的cols不生效

### ISSUE THREAD

**Issue by bestRenekton** [umijs/dumi#1980]
### Version

2.2.13

### OS Version

win10

### Node.js Version

16.20.2

### Browser Version

chrome 116

### Link to minimal reproduction

no

### Steps to reproduce

# 1.在一个index.md中,配置分栏，代码如下：

```
---
title: Button 按钮
demo:
  cols: 2
---

<code src="./demos/1_btn_type.tsx">按钮类型</code>
<code src="./demos/2_btn_icon.tsx">图标按钮</code>
```
这样是可以的分栏的。

# 2.但是如果我想单独配置code分栏，这样代码不生效

```
<code src="./demos/1_btn_type.tsx" cols="2">按钮类型</code>
<code src="./demos/2_btn_icon.tsx" cols="2">图标按钮</code>
```

# 3.另外embed分栏这样设置，也不生效
```
<embed src="./demos/multiple.md" cols="2"></embed>
```

### What is expected?

`code`，`embed`标签的`cols`属性可以生效

### What is actually happening?

`code`，`embed`标签的`cols`属性没有生效

**Comment by PeachScript** [comment]
非 bug，`cols` 始终是页面级的配置，不支持你提到的用法，https://d.umijs.org/guide/page-config#demo-%E5%88%86%E6%A0%8F%E9%85%8D%E7%BD%AE

**Comment by bestRenekton** [comment]
> 非 bug，`cols` 始终是页面级的配置，不支持你提到的用法，https://d.umijs.org/guide/page-config#demo-%E5%88%86%E6%A0%8F%E9%85%8D%E7%BD%AE

行，但是我页面设置了cols，`code`的分栏生效了，`embed`却没有生效呢

**Comment by PeachScript** [comment]
`embed` 本身没有分栏的功能，只能对 `embed` 内容中的 demo 进行分栏，且分栏生效的前提是该组 demo 数量大于 1

**Comment by bestRenekton** [comment]
> `embed` 本身没有分栏的功能，只能对 `embed` 内容中的 demo 进行分栏，且分栏生效的前提是该组 demo 数量大于 1

我在test.md下写了2个demo，也没有分栏呢？是否只有code方式的demo才可以？
```jsx
/**
 * title: demo1
 * demo:
 *    cols:2
 */
import React from 'react';

export default () => <>1</>;
```

```jsx
/**
 * title: demo2
 * demo:
 *    cols:2
 */
import React from 'react';

export default () => <>2</>;
```

**Comment by PeachScript** [comment]
> 是否只有code方式的demo才可以？

对，用法以文档演示为准
