### ISSUE TITLE
feat: 是否可以考虑增加图片浏览器功能

### ISSUE THREAD

**Issue by 7kms** [umijs/dumi#199]
# Description
是否考虑增加图片浏览器功能. 比如点击图片全屏展示这种.

**Comment by crazyair** [comment]
https://github.com/frontend-collective/react-image-lightbox

**Comment by xiaohuoni** [comment]
什么时候需要这个功能？

**Comment by 7kms** [comment]
> 什么时候需要这个功能？

一篇文章上有图片的时候, 点击图片预览大图这种需求应该有呀

**Comment by xiaohuoni** [comment]
懂了。

**Comment by HeyiMaster** [comment]
这个需求我考虑在remark解析图片资源时，将图片资源收集存储为一个参数，渲染页面时将该参数传递给 `react-image-lightbox` 或者其他 `gallery` 组件实现

**Comment by crazyair** [comment]
> 这个需求我考虑在remark解析图片资源时，将图片资源收集存储为一个参数，渲染页面时将该参数传递给 `react-image-lightbox` 或者其他 `gallery` 组件实现

可以跟 <code 一样，做个包裹。可以传参数，解析那也好处理。

**Comment by xiaohuoni** [comment]
替换掉默认的 img 就好了吧。用户都不要写。默认可以预览大图。

**Comment by HeyiMaster** [comment]
> 替换掉默认的 img 就好了吧。用户都不要写。默认可以预览大图。

替换 img 不可取吧，后面换肤如果用户对于图片资源想做一些定制，就不太好实现了。我觉得最好是解析出来一个 img list 参数，可以提供给用户会好点儿。

**Comment by crazyair** [comment]
如果当个编辑器来看，解析 img 合理，如果当做可布局的，做成 jsx 组件比较好。

**Comment by xiaohuoni** [comment]
如果是需要jsx组件的话，现在就支持，感觉只是自己 import 和 dumi import 的差别。现在支持自定义的组件显示。

![2020-07-13 09 26 45](https://user-images.githubusercontent.com/11746742/87263166-df8c5d00-c4ee-11ea-98fe-b589418d6600.gif)

另外，换肤自定义，应该是全局管理的事情，不需要单独对 img 组件做讨论。

**Comment by xiaohuoni** [comment]
https://github.com/ant-design/ant-design/issues/13719
