### ISSUE TITLE
bug: 代码中的`title`被错误地渲染到侧边栏的目录中

### ISSUE THREAD

**Issue by zhangfisher** [umijs/dumi#1999]
### Version

2.2.16

### OS Version

windows 10

### Node.js Version

18

### Browser Version

chrome 120

### Link to minimal reproduction

https://github.com/zhangfisher/speed-form/docs

### Steps to reproduce

我的[文档工程](https://github.com/zhangfisher/speed-form/docs)

为代码声明了`title`和`description`，但是`title`被渲染到侧边栏的目录中了。

```tsx
/**
* title: 读取状态
* description: 通过`store.state.firstName`直接读取状态,不通过`useState`方法
*/
import { createStore } from 'helux-store';
const state = {
  firstName:"Zhang",
  lastName:"Fisher",
  age:18
}

const store = createStore<typeof state>({state})

export default () => {
  return <div>
      <div>Hello :{store.state.firstName}{' '}{store.state.lastName}</div>
      <div>Age :{store.state.age}</div>
      <button onClick={()=>setState(draft=>draft.age+=1)}>+Age</button>
    </div>
}

``` 

![image](https://github.com/umijs/dumi/assets/2050579/edbd321f-e90b-484f-a1ba-8a45ed879a88)

### What is expected?

代码中的`title`不应该作为目录出现

### What is actually happening?

代码中的`title`不应该作为目录出现

**Comment by PeachScript** [comment]
非 bug，侧边菜单子级展示的是当前页面的 TOC，demo 标题也是 TOC 的一部分

不想展示 demo 标题可以把 demo tocDepth 改深一级即可：https://d.umijs.org/config/markdown#tocdepth
