### ISSUE TITLE
feat: 支持插件系统

### ISSUE THREAD

**Issue by tolerance-go** [umijs/dumi#200]

**Comment by PeachScript** [comment]
@tolerance-go 可以详细描述一下对扩展能力的需求，看看插件这块怎么搞

**Comment by xjl271314** [comment]
插件这个是否可以实现下类似VuePress中的对md文件的扩展。

类似:::tip
xxxx
:::

会渲染为一个带有指定样式的组件。

**Comment by xrkffgg** [comment]
文档中有体现到，但没找到具体的文档详细说明这块。

我看是用一个 <Alert> 包着的，期待完善下这块 API 文档。

**Comment by NoDocCat** [comment]
> 插件这个是否可以实现下类似VuePress中的对md文件的扩展。
> 
> 类似:::tip
> xxxx
> :::
> 
> 会渲染为一个带有指定样式的组件。

我感觉应该没有这个必要，这些东西用 React 组件提供就可以了

**Comment by xrkffgg** [comment]
现有的已经有了，等 1.1 文档发布后，可详细看到。
