### ISSUE TITLE
bug: MFSU esbuild bundler is not supported yet!

### ISSUE THREAD

**Issue by DaphnisLi** [umijs/dumi#2000]
### Version

2.2.14

### OS Version

macOS 14.2.1 (23C71)

### Node.js Version

v16.20.1

### Browser Version

Google Chrome 版本 119.0.6045.159（正式版本） (x86_64)

### Link to minimal reproduction

无

### Steps to reproduce

![image](https://github.com/umijs/dumi/assets/67792799/1d50c822-2e68-44af-a323-876663548604)

### What is expected?

1

### What is actually happening?

1

### Any additional comments? (optional)

1

**Comment by PeachScript** [comment]
非 bug，日志的意思是暂不支持 esbuild bundler
