### ISSUE TITLE
bug: defineApp 未导出

### ISSUE THREAD

**Issue by DaphnisLi** [umijs/dumi#2003]
### Version

2.2.6

### OS Version

macOS 14.2.1 (23C71)

### Node.js Version

v16.20.1

### Browser Version

Google Chrome 版本 119.0.6045.159（正式版本） (x86_64)

### Link to minimal reproduction

无

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

### Any additional comments? (optional)

1

**Comment by PeachScript** [comment]
Duplicate of #2004
