### ISSUE TITLE
feat: Markdown里支持通过变量替换文本

### ISSUE THREAD

**Issue by alienzhangyw** [umijs/dumi#2008]
我想通过设置自定义环境变量的方式，在编译时全局替换多个md文件中的一些文本，这个要能否实现？
我在讨论里提出了一些思路。

_Originally posted by @alienzhangyw in https://github.com/umijs/dumi/discussions/1985_

**Comment by Wxh16144** [comment]
原始需求是啥🤔，或者可以写一个 remark 插件然后自己用 正则表达式去 replaceAll

**Comment by alienzhangyw** [comment]
> 原始需求是啥🤔，或者可以写一个 remark 插件然后自己用 正则表达式去 replaceAll

原始需求就是要做OEM产品，文档里的图片、文字、URL等可以快速替换而不用修改源代码。所以想通过编译时载入环境变量的方式替换md文件里的文本和URL等。

**Comment by Wxh16144** [comment]
> 可以写一个 remark 插件然后自己用 正则表达式去 replaceAll 

这个可以满足你的需求

**Comment by alienzhangyw** [comment]
> > 可以写一个 remark 插件然后自己用 正则表达式去 replaceAll
> 
> 这个可以满足你的需求

我已经改用Docusaurus了，参考这个https://github.com/facebook/docusaurus/issues/395
