### ISSUE TITLE
使用worker-loader，出现报错Module not found: Error: Can't resolve 'mf/worker-loader'

### ISSUE THREAD

**Issue by yc507** [umijs/dumi#2011]
### Version

2.2.7

### OS Version

macOS12.1

### Node.js Version

16.17.0

### Browser Version

chromeV120.0.6099.216

### Link to minimal reproduction

无

### Steps to reproduce

项目中使用worker-loader进行Worker加载, worker-loader版本3.0.8，
配置了 chainWebpack(memo, args) {
    memo.module
      .rule('worker')
      .test(/\.worker\.js$/)
      .use('worker-loader')
      .loader('worker-loader')
      .end();
  }

import Worker from 'worker-loader!./my.worker.js';
export default class App extends React.Component {
  componentDidMount(): void {
    this.myWorker = new Worker();
  }
  render() {
    return <div>测试</div>;
  }

### What is expected?

希望通过worker-loader正常加载worker.js

### What is actually happening?

出现报错 Module not found: Error: Can't resolve 'mf/worker-loader'

**Comment by PeachScript** [comment]
关闭 mfsu 试下：https://d.umijs.org/config#mfsu

**Comment by yc507** [comment]
配置mfsu: {
      exclude: [/worker-loader/],
    },
 出现TypeError: Cannot read properties of undefined (reading 'startsWith')
 经排查发现worker-loader内部使用了以下语句导致上述报错
` const useWebpack5 = require("webpack/package.json").version.startsWith("5.");`

然后将worker-loader降低版本至"3.0.1"报错消失，但项目运行后会一直停留在50%,页面一直请求http://localhost:8000/__umi/api/bundle-status 感觉是mfsuBundleStatus状态没有通过
![image](https://github.com/umijs/dumi/assets/9586156/78acbd81-f55a-4d6c-9421-1326667de692)

最终修改配置 mfsu: false
将mfsu关闭，并将worker-loader降低版本至"3.0.1"项目能正常启动了
@PeachScript 感谢提供解决方法
