### ISSUE TITLE
feat: dumi2 的 自动API表格 生成太慢了，热更新也很慢

### ISSUE THREAD

**Issue by wanqing19954** [umijs/dumi#2022]
### What problem does this feature solve?

dumi2 的 自动API表格 生成太慢了，热更新也很慢，可能和我的组件数量有关系，但是dumi1的API生成就很快，这块能否优化下

**Comment by PeachScript** [comment]
Duplicate of #1582

**Comment by PeachScript** [comment]
短时间内没有精力投入 API 生成，可以先看是不是缺 @types 包或者 unpkg.com 访问不畅，参考：https://github.com/umijs/dumi/discussions/1676#discussioncomment-5947692

如果仍然不行建议先用 Markdown 手写 API
