### ISSUE TITLE
feat: Dumi 支不支持Taro ?

### ISSUE THREAD

**Issue by beMySun** [umijs/dumi#2034]
### What problem does this feature solve?

最近在使用 Dumi 搭建业务组件库， 有部分组件需要使用 Taro 实现， 但是没有发现相关特性。 

请问官方是否可以支持在 Dumi 中兼容 Taro 组件的开发？

### Possible Solution (optional)

可能的实现：
- 实现一个 babel 插件， 以便正确编译 Taro 组件。
-  Dumi 底层使用了 Umi，而 Umi 使用了 Webpack。可能需要在项目的配置文件中添加一些针对 Taro 的配置，比如添加 Taro 的 loader。

**Comment by PeachScript** [comment]
目前没有精力做技术栈的扩充，你有兴趣的话可以自定义技术栈实现 Taro 的接入，建议先搞个 RFC

自定义技术栈简单文档：https://d.umijs.org/plugin/api#registertechstack
Vue.js 技术栈支持：https://github.com/umijs/dumi/pull/1922
Vue.js 技术栈支持的讨论：https://github.com/umijs/dumi/discussions/1959

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!

**Comment by beMySun** [comment]
Hello!  Your E-mail has been recieved and I will respond you as soon as possible.Best wishes!
