### ISSUE TITLE
feat: dumi2集成umi4什么时候支持

### ISSUE THREAD

**Issue by gulangwh** [umijs/dumi#2040]
### What problem does this feature solve?

我看咱们有计划做集成umi4，但是目前还是没有支持。
想问下，2024年还有计划吗？大概是怎样的。

### Possible Solution (optional)

是否可以提供一个类似 @umijs/preset-dumi的插件

**Comment by PeachScript** [comment]
Duplicate of #1334

**Comment by PeachScript** [comment]
目前暂无计划和时间点，有进展会在上述 issue 中同步；你们如果有强诉求并且有兴趣提供方案，欢迎 Discussion 创建详细方案的 RFC 进行讨论
