### ISSUE TITLE
bug: 当开启apiParser的时候，修改组件代码会导致崩溃

### ISSUE THREAD

**Issue by windshowastore** [umijs/dumi#2047]
### Version

2.2.13

### OS Version

win11 21H2

### Node.js Version

20.11.0

### Browser Version

chrome 88

### Link to minimal reproduction

暂无

### Steps to reproduce

组件库设置开启apiparser

### What is expected?

正常显示并且不崩溃

### What is actually happening?

崩溃了，需要重启服务

**Comment by PeachScript** [comment]
Duplicate of https://github.com/umijs/dumi/issues/1476#issuecomment-1751908240
