### ISSUE TITLE
feat: 支持api文档站搭建吗？dumi更多是搭建前端组件库使用？

### ISSUE THREAD

**Issue by lys623** [umijs/dumi#2048]
### What problem does this feature solve?

类似下图的交互，左侧目录，中间是api使用说明，包括Request Parameters，Response Parameters，Request Example，Response Example等部分，右侧是导航。内容可以写死在前端仓库，全静态，可以是由json生成。
![image](https://github.com/umijs/dumi/assets/4364314/c47ef4d5-0d42-40c1-9a64-69c7f794502f)

**Comment by jeffwcx** [comment]
可以自行搞个OpenAPI的插件，理论上是能实现的

**Comment by lys623** [comment]
> 可以自行搞个OpenAPI的插件，理论上是能实现的

从零开始搞，那就复杂了，有现成的吗

**Comment by jeffwcx** [comment]
> > 可以自行搞个OpenAPI的插件，理论上是能实现的
> 
> 从零开始搞，那就复杂了，有现成的吗

https://github.com/scalar/scalar 用这个吧，dumi以后主要精力在 API Table，API reference这些
