### ISSUE TITLE
bug: SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by flyha** [umijs/dumi#2049]
### Version

^2.2.13

### OS Version

Windows

### Node.js Version

16.15.1

### Browser Version

Microsoft Edge 44.18362.449.0

### Link to minimal reproduction

http://localhost:8001/

### Steps to reproduce

after npm run start
![image](https://github.com/umijs/dumi/assets/69004145/8471326d-1aa3-42b2-911a-fbe24ae6ed51)
![image](https://github.com/umijs/dumi/assets/69004145/9a0e671e-30a2-43b4-ac4a-356e54adf2dd)

### What is expected?

希望正常显示

### What is actually happening?

对IE和Edge兼容性问题

**Comment by PeachScript** [comment]
ref: https://d.umijs.org/config#legacy
