### ISSUE TITLE
怎么隐藏footer中的last update

### ISSUE THREAD

**Issue by jinlily** [umijs/dumi#205]
怎么隐藏footer中的last update

**Comment by PeachScript** [comment]
单文件不需要可以配置 `updatedTime` 为 null 来禁用，全局目前还不支持关闭

**Comment by jinlily** [comment]
多谢，但这样只是时间不更新了,变成:Last Update:1970/1/1 上午8:00:00，没有把这一整行隐藏。

**Comment by PeachScript** [comment]
整行删掉的话 `filePath` 设置为 null，如果你的场景是希望完全自定义某个页面，可以使用 `gapless` 为 true

**Comment by dream-approaching** [comment]
> 整行删掉的话 `filePath` 设置为 null，如果你的场景是希望完全自定义某个页面，可以使用 `gapless` 为 true

@PeachScript 谢谢指导。设置了`filePath`为`null`可以隐藏更新时间。

还想请问下设置了`gapless`为`true`是可以完全自定义更新时间这一行吗，还需如何操作呢，没找到相关文档

**Comment by dream-approaching** [comment]
> 整行删掉的话 `filePath` 设置为 null，如果你的场景是希望完全自定义某个页面，可以使用 `gapless` 为 true

亲测可行，感谢大佬。还想请问下可以单独自定义页面的更新时间这一行吗？

**Comment by PeachScript** [comment]
在底部插入一个 inline 模式的  Demo，可以实现自定义

**Comment by wangz-code** [comment]
mark: 隐藏页面底部的编辑和更新时间  filePath: null   完全自定义当前页面 gapless: true
