### ISSUE TITLE
bug: dumi build --assets 报错

### ISSUE THREAD

**Issue by LesterWeng** [umijs/dumi#2057]
### Version

2.2.14

### OS Version

macOS 12.6  Apple M1 Pro

### Node.js Version

16.20.1

### Browser Version

浏览器无关

### Link to minimal reproduction

https://github.com/umijs/dumi/tree/master/examples/normal

### Steps to reproduce

dumi build --assets

### What is expected?

正常

### What is actually happening?

异常，报错

fatal - AssertionError [ERR_ASSERTION]: key title is already registered by undefined, plugin from /usr/local/lib/node_modules/dumi/node_modules/@umijs/preset-dumi/lib/plugins/title.js register failed.

**Comment by PeachScript** [comment]
版本混用了吧，`@umijs/preset-dumi` 是 dumi 1.x 的包，2.x 是没有这个包的
