### ISSUE TITLE
bug: 配置demo的inline模式时，调用echarts.registerMap导致不渲染

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#2070]
### Version

2.2.1

### OS Version

Windows 11 latest

### Node.js Version

16.20.2

### Browser Version

Google latest

### Link to minimal reproduction

no

### Steps to reproduce

1. 在markdown文件中渲染多个demo，其中多个demo都会渲染echarts图表，并且为inline模式，当其中某个demo渲染地图时，调用echarts.registerMap后就导致其他echarts的demo不展示（只有当前demo能展示），只有一个空白。并出现告警（没有错误），只要不调用这个代码，其他demo就没事。
![image](https://github.com/umijs/dumi/assets/51065061/903578c1-9b97-4163-9667-460525082a05)

### What is expected?

echarts正常展示

### What is actually happening?

调用echarts.registerMap后就导致其他echarts的demo不展示，只有一个空白。

**Comment by PeachScript** [comment]
看 warning 和 dumi 无关，ECharts 要求挂载点的 DOM 必须有宽高，检查下是不是满足要求

**Comment by CaptainJon** [comment]
> 看 warning 和 dumi 无关，ECharts 要求挂载点的 DOM 必须有宽高，检查下是不是满足要求

并不是，因为我也说了，只要不调用那个方法，其他demo是正常展示的，也就是有宽高的，我代码也设置了宽高。调用后，即使用f12也可以看到画布是有宽高的，但是就是不渲染。

**Comment by PeachScript** [comment]
dumi 只负责执行 demo 代码，执行后出现的问题需要开发者自行排查，包括 demo 与 demo 之间的实例冲突，该 issue 关闭

如果你确认这个问题在别的项目里都不存在，是 dumi 的编译导致的，请提交最小可复现仓库再 reopen
