### ISSUE TITLE
feat: Tree组件支持设置目录的文件类型

### ISSUE THREAD

**Issue by CaptainJon** [umijs/dumi#2071]
### What problem does this feature solve?

目前Tree组件只能根据是否存在ul和li标签（且li标签必须有内容）才能识别当前节点为文件夹，但是有时候只需初步展示一下目录结构，并不想展示里面的子文件，目前还实现不了。

### Possible Solution (optional)

可以和small一样，比如通过“fold”来声明是否为文件夹，如果存在ul和li则不需要声明，自动识别为文件夹。

**Comment by PeachScript** [comment]
`fold` 不是标准 HTML 标签，可以改一下逻辑支持空 `ul` 也判定为文件夹

**Comment by andybuibui** [comment]
> `fold` 不是标准 HTML 标签，可以改一下逻辑支持空 `ul` 也判定为文件夹

![image](https://github.com/umijs/dumi/assets/23742065/10dffd4f-1f83-42cf-bcfe-e31faf5fb6e4)
这种样式么？ 可以的话我来改一下

**Comment by PeachScript** [comment]
> 这种样式么？ 可以的话我来改一下

感谢贡献，样式是这样：空目录不展示左侧 +/- 按钮，始终为关闭的文件夹图标，你看看是否合理

**Comment by zhangfisher** [comment]
推荐树组件[litetree](https://zhangfisher.github.io/lite-tree/)
