### ISSUE TITLE
feat: 能否支持文档版本切换功能？

### ISSUE THREAD

**Issue by easonzen** [umijs/dumi#208]
背景：目前使用技术方案lerna + dumi 开发组件库
需求：组件的迭代同时会伴随着组件文档的更新，但是有时希望看到以前某一个版本的组件文档。目前没有在dumi官网上找到解决这个问题的解决方案，期待回复，Thanks~

**Comment by PeachScript** [comment]
不涉及 major 的切换可参考 Umi 官网使用 Badge 标记新版本特性：https://github.com/umijs/umi/blame/master/docs/config/README.zh-CN.md#L207
涉及 major 的切换，由于组件库本身已经存在不兼容，所以无法在同一文档中共存，可参考 Ant Design 官网采用导航菜单切换版本的形式：https://ant.design/
