### ISSUE TITLE
bug: 开启msfu后导致Module does not exist in container

### ISSUE THREAD

**Issue by AttackXiaoJinJin** [umijs/dumi#2094]
### Version

2.3.2

### OS Version

12.2

### Node.js Version

20.11.1

### Browser Version

124.0.6367.61

### Link to minimal reproduction

https://github.com/umijs/dumi/issues/1668#issuecomment-2082079861

### Steps to reproduce

https://github.com/umijs/dumi/issues/1668#issuecomment-2082079861

### What is expected?

希望 mfsu 处理好引发的问题

### What is actually happening?

mfsu 没有找到模块

**Comment by jeffwcx** [comment]
> /assign @jeffwcx 老哥帮忙看下

这块得他们内部人员改了，我已经报告他们了，你先 mfsu关闭凑合用
