### ISSUE TITLE
npm's latest tag is not 2.3.x

### ISSUE THREAD

**Issue by onlyling** [umijs/dumi#2097]
### Version

2.3.2

### OS Version

macOS 14.4.1 

### Node.js Version

v18.19.0

### Browser Version

Chrome 124.0.6367.119

### Link to minimal reproduction

https://www.npmjs.com/package/dumi?activeTab=versions

### Steps to reproduce

```bash
npx npm-check-updates -u
```

dumi is `^2.2.17`.

### What is expected?

```bash
npx npm-check-updates -u
```

dumi is `^2.3.2`.

### What is actually happening?

<img width="761" alt="image" src="https://github.com/umijs/dumi/assets/9999765/625de5b1-a2c9-4094-b2d6-8f264b591ae0">

**Comment by PeachScript** [comment]
有意回滚了的，因为 pnpm 项目默认就会挂， #2094 修复后会发 2.3.3 重新指向 latest
