### ISSUE TITLE
win本地打包后，在centos7上配置nginx后无法正常加载

### ISSUE THREAD

**Issue by zhouzyc** [umijs/dumi#2108]
### Version

2.3.4

### Link to minimal reproduction

https://gitee.com/JS-VeryHappy/vh-admin.git

### Steps to reproduce

![image](https://github.com/umijs/dumi/assets/18420689/459fee35-75a3-4114-9561-b2dfc12098e7)
![image](https://github.com/umijs/dumi/assets/18420689/a0a6f061-6d42-415a-ac87-0267955a4553)
![image](https://github.com/umijs/dumi/assets/18420689/1faae67e-ec9b-4b31-b6db-9db57fb80afd)
win打包的，在本地 dumi preview 正常，打包文件放到服务器centos7.5 nginx 上就不行了

### What is expected?

只能正常运行

### What is actually happening?

无法加载

**Comment by zhouzyc** [comment]
dumi版本恢复到2.2.16 后没有出现meta_E 这个方式，是否是因为特殊字符串在centos环境不无被正确执行

**Comment by PeachScript** [comment]
Duplicate of #1990
