### ISSUE TITLE
错误：可能是某个间接的库造成了各种错误

### ISSUE THREAD

**Issue by GuoDapeng** [umijs/dumi#2112]
### Version

2.2.13

### OS Version

macOS 14.4.1

### Node.js Version

22.1.0

### Browser Version

Google Chrome 126.0.6452.3

### Link to minimal reproduction

https://github.com/GuoDapeng/dumi_test/blob/main/docs/index.md

### Steps to reproduce

新建一个项目，或者以前的项目删除 `pnpm-lock.yaml` 或者 `yarn.lock`。

在任意文档里面添加：

```jsx
/**
 * inline: true
 */
import React from 'react';

const App: React.FC = () => {
  return <>APP</>
}
export default App;
```

`pnpm install` 或者 `yarn install`

启动项目 ` pnpm start` 或者 `yarn start`

### What is expected?

希望顺利启动

### What is actually happening?

![截屏2024-05-11 19 34 11](https://github.com/umijs/dumi/assets/7477750/0fc14479-294a-435d-a910-edfcc924fa60)

**Comment by PeachScript** [comment]
报错是符合预期的，原因是在 jsx 代码块里使用了 TypeScript 语法

**Comment by GuoDapeng** [comment]
非常感谢，我一直存在一个实践错误。需要使用 `tsx` 包裹需要渲染的组件。

<img width="285" alt="截屏2024-05-14 10 27 50" src="https://github.com/umijs/dumi/assets/7477750/6a236439-e463-43d4-914e-f9c2fc74942b">
