### ISSUE TITLE
bug: dumi组件中使用dumi提供的api构建组件后在项目中引入报错

### ISSUE THREAD

**Issue by QDyanbing** [umijs/dumi#2114]
### Version

2.3.4

### OS Version

macOS 14.4.1 

### Node.js Version

v16.20.1

### Browser Version

chrome 124.0.6367.202

### Link to minimal reproduction

https://github.com/QDyanbing/bug-repro-dumi-missing-dependencies

### Steps to reproduce

<img width="472" alt="image" src="https://github.com/umijs/dumi/assets/66234749/b43797db-30bd-474e-a1b4-8485b34a7365">
组件中如果使用的dumi提供的方法构建出的组件在项目中使用时会报错

### What is expected?

能正常使用

### What is actually happening?

引入组件报错

**Comment by QDyanbing** [comment]
<img width="346" alt="image" src="https://github.com/umijs/dumi/assets/66234749/8e80c9ff-356e-4e8c-9657-a24cc4b4f40c">
这个是构建好的组件的源码，这个组件已上传到npm

**Comment by PeachScript** [comment]
组件库源码不应该依赖框架，API 文档已有提示：https://d.umijs.org/theme/api#api
