### ISSUE TITLE
您好，我这个运行项目提示

### ISSUE THREAD

**Issue by Verdant-Grassland** [umijs/dumi#2119]
### Version

2.3.4

### OS Version

Windows 11 版本 23H2 (OS 内部版本 22631.3593)

### Node.js Version

22.1.0

### Browser Version

Edge  125.0.2535.51 (正式版本)

### Link to minimal reproduction

找不到相关问题

### Steps to reproduce

![image](https://github.com/umijs/dumi/assets/107308136/2a45f3a9-14d6-4d2a-98ba-bcd3e4d71cc6)
![image](https://github.com/umijs/dumi/assets/107308136/17fab08f-5376-4b34-a11b-ddd464e53293)
![image](https://github.com/umijs/dumi/assets/107308136/f29cc3af-bbe2-406b-92ee-647a0370f2fd)
我不知道刚刚创建项目并且执行项目，还等报错

### What is expected?

您好，我这个想要解决问题

### What is actually happening?

我不知道的，刚刚创建项目并且执行项目，还等报错，不知道什么情况啊
怎样解决问题呢？

**Comment by GuoDapeng** [comment]
用 yarn 或者 npm 试试，我发现 pnpm 运行很多问题。我的项目换 pnpm 都失败了，需要做的事情太多。

**Comment by PeachScript** [comment]
看报错可能是自己项目的 `package.json` name 设置为 dumi 导致的，需要换成其他名字

**Comment by PeachScript** [comment]
另外提 issue 需要给最小可复现问题的仓库和步骤，怎么一步步操作能出现相同的问题，只贴截图是不够的

**Comment by Verdant-Grassland** [comment]
> 看报错可能是自己项目的 `package.json` name 设置为 dumi 导致的，需要换成其他名字

感谢，解决了，是name: "dumi"问题，改成name: "dumis"了，感谢大佬
