### ISSUE TITLE
请问为什么dumi build后发布到 Github Page，样式都丢失了呢？

### ISSUE THREAD

**Issue by AnnaSearl** [umijs/dumi#213]
请问为什么dumi build后发布到 Github Page，样式都丢失了呢？

组件是js和样式分离的，借助 babel-plugin-import 加载样式，dumi dev是没问题的，但是dumi build后发布到 Github Page就丢失样式了

// .umirc.ts
extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'anna-remax-ui',
        libraryDirectory: '/',
        style: true,
      },
    ],
  ],
  alias: {
    'anna-remax-ui': path.resolve(__dirname, 'components'),
  },

**Comment by Mr-jiangzhiguo** [comment]
提供个 miniRepo 啊

**Comment by git-lt** [comment]
我也遇到了，开发调试的时候有样式，buid之后，demo 中组件样式就丢了， @Mr-jiangzhiguo @PeachScript 
我提供了可复现的最小仓库 https://gitee.com/aitter/dumi-issues
按readme.md 可很快复现，麻烦有时间帮忙看看

**Comment by Mr-jiangzhiguo** [comment]
分离开发下，看样子是 doc 没有按需引入 css 的原因

**Comment by PeachScript** [comment]
和 #225 重复，集中到隔壁讨论，先关闭了
