### ISSUE TITLE
feat: `在 ${repoPlatform} 上编辑这篇文档`链接中的分支可自定义

### ISSUE THREAD

**Issue by ApsarasX** [umijs/dumi#214]
### Description
在仓库`packages/preset-dumi/src/themes/default/layout.tsx`有如下代码
![image](https://user-images.githubusercontent.com/24390069/84904478-ec7d8280-b0e1-11ea-9a1e-5ead23da2d65.png)
对应生成页面底部跳转github源码的链接，但是这个链接的分支写死为了master

### Sulution

希望该分支可自定义，默认情况下为master

**Comment by PeachScript** [comment]
有道理👍

**Comment by ApsarasX** [comment]
#229 中已修复
