### ISSUE TITLE
bug: npx create-dumi 选择 React Library - pnpm，报错

### ISSUE THREAD

**Issue by wy1009** [umijs/dumi#2144]
### Version

2.3.8

### OS Version

macOS 14.4.1

### Node.js Version

18.13.0

### Browser Version

与浏览器无关

### Link to minimal reproduction

不需要库，初始化即复现

### Steps to reproduce

mkdir myapp && cd myapp
npx create-dumi
选择 React Library - pnpm，即可复现。

### What is expected?

正常初始化项目。

### What is actually happening?

<img width="1440" alt="image" src="https://github.com/umijs/dumi/assets/18343973/9cac5d8d-8d71-480a-a98d-ca100314e759">

**Comment by wy1009** [comment]
忘记补充，选择 yarn 即正常。

**Comment by PeachScript** [comment]
非 bug，报错是安装的 dumi 版本太旧导致的，原因有两个：
1. 你的 create-dumi 应该装到全局了，所以一直是 `2.0.2` 的旧版本
2. 你的 pnpm 应该比较旧，所以遇到 `^2.0.2` 的安装策略还是最低匹配而不是装到最新版
