### ISSUE TITLE
bug: 全文搜索无法正常搜索，显示加载中，并且控制台报Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ArwenFang** [umijs/dumi#2156]
### Version

2.4.3

### OS Version

macOS 13.2.1

### Node.js Version

18.16.0

### Browser Version

125.0.6422.77

### Link to minimal reproduction

None

### Steps to reproduce

1. mkdir myapp && cd myapp
2. npx create-dumi
3. 选择pnpm
4. pnpm dev

### What is expected?

Can operate normally

### What is actually happening?

![image](https://github.com/umijs/dumi/assets/129349587/fc9f48dc-a06f-4f90-aaf4-f671a4379cd0)
![image](https://github.com/umijs/dumi/assets/129349587/34c57566-bf0b-494a-8b82-f4baa5eede72)

### Any additional comments? (optional)

None

**Comment by Achilles822** [comment]
Same problem here.

**Comment by PeachScript** [comment]
@Jinbao1001 有空确认看看

**Comment by Jinbao1001** [comment]
fixed #2161
