### ISSUE TITLE
bug: dumi 2.4.0 之后的版本会报错 require is not defined

### ISSUE THREAD

**Issue by huarse** [umijs/dumi#2160]
### Version

>= 2.4.0

### OS Version

macOS

### Node.js Version

18

### Browser Version

Chrome

### Steps to reproduce

直接运行，看控制台

### What is expected?

2.3.x 版本是不会报错的

### What is actually happening?

<img width="346" alt="image" src="https://github.com/umijs/dumi/assets/3724927/25325c85-60ff-4581-99d6-8131eaf3b2d3">

**Comment by PeachScript** [comment]
看是海兔代码块的问题，可以到海兔群里反馈，可能和 #2156 有关， @Jinbao1001 跟进下

另外内部域名不要贴在 issue 里，描述里我已经删掉了
