### ISSUE TITLE
bug: iframe 高度设置无效

### ISSUE THREAD

**Issue by fengsx** [umijs/dumi#2168]
### Version

2.4.3

### OS Version

macOS 14.3

### Node.js Version

16.20.2

### Browser Version

Chrome 126.0.6478.127

### Link to minimal reproduction

https://pro-components.antdigital.dev/components/page-container

### Steps to reproduce

iframe 高度设置无效
![image](https://github.com/user-attachments/assets/82507d26-71f4-4817-b257-14ac3404ca86)
![image](https://github.com/user-attachments/assets/bb292414-9331-44c0-99b4-80881b430fb6)
![image](https://github.com/user-attachments/assets/e811d813-61bf-4388-9c3d-f53fff69d7e8)

### What is expected?

iframe 采用设置的高度

### What is actually happening?

iframe 高度设置无效

**Comment by PeachScript** [comment]
带单位的数值是不支持的，https://d.umijs.org/config/demo#iframe
