### ISSUE TITLE
如何配置更多有利于SEO的选项

### ISSUE THREAD

**Issue by 7kms** [umijs/dumi#217]
### Question
现在能手动配置的有title
如果想手动配置keywords和description等, 
并且最后要输出到meta标签中,请问应该如何配置

**Comment by PeachScript** [comment]
站点级别的可使用 https://umijs.org/zh-CN/config#metas 配置，路由级别的还不支持

**Comment by TrumanDu** [comment]
期待seo更多的支持

**Comment by PeachScript** [comment]
dumi v2 已提供页面级的 tdk 配置支持：https://d.umijs.org/config/markdown#description
