### ISSUE TITLE
bug: 引入formily在生产环境打包报错

### ISSUE THREAD

**Issue by qiliangya** [umijs/dumi#218]
### Versions

- dumi: v1.0.6
- node: v10.16.3
- npm: v6.12.0
- OS: mac V10.15
- Browser: google

### Steps to reproduce
引入[formily](https://formilyjs.org/)后， 在开发环境下正常运行， 但是在生产环境打包会报错

![image](https://user-images.githubusercontent.com/31298600/85351313-ff56e380-b535-11ea-9f98-ab72edcfe9ac.png)

### What is Expected?
希望生产环境能和开发环境一致
### What is actually happening?
有将对应的依赖写入dependencies
![image](https://user-images.githubusercontent.com/31298600/85351347-1695d100-b536-11ea-94ff-8107880a4fe7.png)
但还是无效

**Comment by PeachScript** [comment]
npm ls [报错的包名]，检查下是否还有依赖没有写进 dependencies

**Comment by qiliangya** [comment]
已检查dependencies， 加入了所有该组件用到的formily依赖，结果还是报相同的错误
![image](https://user-images.githubusercontent.com/31298600/85358591-b0fe1080-b546-11ea-8ba5-73ba5888182f.png)

以下是使用npm ls 对报错的包名
![image](https://user-images.githubusercontent.com/31298600/85358760-223dc380-b547-11ea-9817-1637d0c52962.png)

**Comment by qiliangya** [comment]
@PeachScript 麻烦看下感谢！

**Comment by PeachScript** [comment]
请提供下最小复现 repo，以便重现问题

**Comment by xiaohuoni** [comment]
@qiliangya cc
