### ISSUE TITLE
bug: 2.4.7版本"```jsx  | pure " 配置导致 demoUrl 无法被编译

### ISSUE THREAD

**Issue by zhouzyc** [umijs/dumi#2182]
### Version

2.4.7

### OS Version

win11

### Node.js Version

20.0.0

### Browser Version

谷歌

### Link to minimal reproduction

https://gitee.com/JS-VeryHappy/vh-mobile

### Steps to reproduce

1.根据官方文档的配置
![image](https://github.com/user-attachments/assets/93be5505-633a-4e28-8569-da26fb7dcb36)
2.如果又使用了 demoUrl 的配置，
![image](https://github.com/user-attachments/assets/26b01492-b8a3-498f-a3a7-cbb0bd8c4ebf)
3.此时demoUrl的配置将不会生效
![image](https://github.com/user-attachments/assets/d14ee9a0-1645-48c7-a4b5-ebaf030492d7)
4.猜测是因为配置 ```jsx  | pure  里面的代码解析将不会运行
5.我的场景是，代码不需要编译，但是需要显示出demoUrl对应的手机端iframe
6.这个现象是我从2.2.16升级到2.4.7才有的，以前是可以正常显示

### What is expected?

希望正常显示

### What is actually happening?

不显示

**Comment by zhouzyc** [comment]
本地的主题不生效了，有人帮忙看下吗

**Comment by zhouzyc** [comment]
1.根据官方文档的配置
![image](https://github.com/user-attachments/assets/93be5505-633a-4e28-8569-da26fb7dcb36)
2.如果又使用了 demoUrl 的配置，
![image](https://github.com/user-attachments/assets/26b01492-b8a3-498f-a3a7-cbb0bd8c4ebf)
3.此时demoUrl的配置将不会生效
![image](https://github.com/user-attachments/assets/d14ee9a0-1645-48c7-a4b5-ebaf030492d7)
4.猜测是因为配置 ```jsx  | pure  里面的代码解析将不会运行
5.我的场景是，代码不需要编译，但是需要显示出demoUrl对应的手机端iframe

**Comment by Jinbao1001** [comment]
设计如此, 以前能跑是意外.
