### ISSUE TITLE
bug: 使用 axios 报错 util.TextEncoder is not a constructor

### ISSUE THREAD

**Issue by crazyair** [umijs/dumi#2183]
### Version

latest

### OS Version

mac

### Node.js Version

latest

### Browser Version

chrome

### Link to minimal reproduction

https://github.com/crazyair/dumi-test/tree/codesandbox

### Steps to reproduce

打开 http://localhost:8001/guide

### What is expected?

不报错

### What is actually happening?

TypeError: util.TextEncoder is not a constructor

**Comment by PeachScript** [comment]
@Jinbao1001 cc

**Comment by chaomingd** [comment]
遇到同样的问题

**Comment by Jinbao1001** [comment]
closed #2187
