### ISSUE TITLE
bug: dumi Markdown引入第三方包报错

### ISSUE THREAD

**Issue by parlay96** [umijs/dumi#2185]
### Version

2.3

### OS Version

win

### Node.js Version

18.16.1

### Browser Version

google 127.0

### Link to minimal reproduction

dumi Markdown引入第三方包报错

### Steps to reproduce

dumi Markdown引入第三方包:
```jsx
import React from "react";
// 这是因为dumi文档找不到module
import { Close as CloseIcon, Thumb } from "fish-icons";
export default () => (
  <>
    <CloseIcon size="20px" color="red" />
    <Thumb size={20} color="#000" style={{ marginLeft: "8px" }} />
  </>
);
报错ReferenceError: module is not defined

### What is expected?

dumi Markdown引入第三方包:
```jsx
import React from "react";
// 这是因为dumi文档找不到module
import { Close as CloseIcon, Thumb } from "fish-icons";
export default () => (
  <>
    <CloseIcon size="20px" color="red" />
    <Thumb size={20} color="#000" style={{ marginLeft: "8px" }} />
  </>
);
报错ReferenceError: module is not defined

### What is actually happening?

dumi Markdown引入第三方包:
```jsx
import React from "react";
// 这是因为dumi文档找不到module
import { Close as CloseIcon, Thumb } from "fish-icons";
export default () => (
  <>
    <CloseIcon size="20px" color="red" />
    <Thumb size={20} color="#000" style={{ marginLeft: "8px" }} />
  </>
);
报错ReferenceError: module is not defined

### Any additional comments? (optional)

_No response_

**Comment by parlay96** [comment]
其实我fish-icons 暴露了es模块入口了的

**Comment by parlay96** [comment]
他默认去找了common.js模块

**Comment by parlay96** [comment]
![image](https://github.com/user-attachments/assets/6a6dc09f-e1ec-46f8-b0ba-57435ddcfbcd)
![image](https://github.com/user-attachments/assets/136fee4f-d0eb-4413-8412-953ecc430279)
dumi md文件 默认去找main

**Comment by Jinbao1001** [comment]
试试看 chainWebpack -> memo.resolve.byDependency.set('commonjs', {});

**Comment by parlay96** [comment]
@Jinbao1001 
![image](https://github.com/user-attachments/assets/7e187343-8492-41fc-b6f3-e88adbc11e99)
好像不行

**Comment by parlay96** [comment]
@Jinbao1001 谢谢你

**Comment by Jinbao1001** [comment]
> @Jinbao1001 ![image](https://private-user-images.githubusercontent.com/32978177/357365192-7e187343-8492-41fc-b6f3-e88adbc11e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTgyNTksIm5iZiI6MTcyMzU1Nzk1OSwicGF0aCI6Ii8zMjk3ODE3Ny8zNTczNjUxOTItN2UxODczNDMtODQ5Mi00MWZjLWI2ZjMtZTg4YWRiYzExZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE0MDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzk3ZDE0YjgyYTI3MDFlNjVjM2JjOWQ1MmFlZDEzNzQwNmZmYTIwOTg4OTJmMzZlYzM5MjUxMWU0MWQ2Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIePa7fjjlGJ-hzEA0Hh_93MdTbN933ZSg4qKZR-zeI) ![image](https://private-user-images.githubusercontent.com/32978177/357365759-54d9c288-9b68-4f6f-a411-820779d4ccc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTgyNTksIm5iZiI6MTcyMzU1Nzk1OSwicGF0aCI6Ii8zMjk3ODE3Ny8zNTczNjU3NTktNTRkOWMyODgtOWI2OC00ZjZmLWE0MTEtODIwNzc5ZDRjY2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE0MDU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhYmY5MzhmZWQyZWJmNWI0NTM5N2ZiMTUwM2U0ZGM3ZjZhNjNhODQyYzMyZDVlNDQ2ZDI5MTRjOTNiMmEwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A9rqKXzcu9RshUdhSdU84VpsGICKfgS2U-NJVVzeMpA)
> 
> 好像不行

好的, 已知问题, 编译cjs导致的, 这两天我会发版修复掉

**Comment by parlay96** [comment]
@Jinbao1001 幸苦了 发了告诉我下

**Comment by Jinbao1001** [comment]
@parlay96 方便使用 `beta` 版本测试一下么, 影响面有点广 [2.4.8-beta.1](https://www.npmjs.com/package/dumi/v/2.4.8-beta.1)

**Comment by Jinbao1001** [comment]
@parlay96 方便测试一下么? 看看有没有引发别的问题 [beta](https://www.npmjs.com/package/dumi/v/2.4.8-beta.3)

**Comment by parlay96** [comment]
@Jinbao1001 我明天试试看，不过你就该这个bug 应该发版也没啥吧

**Comment by Jinbao1001** [comment]
> @Jinbao1001 我明天试试看，不过你就该这个bug 应该发版也没啥吧

影响蛮大的. `demo`的`deps`引入规则都改掉了.

**Comment by Jinbao1001** [comment]
@parlay96 有测试一下吗?

**Comment by parlay96** [comment]
> @parlay96 有测试一下吗?

![image](https://github.com/user-attachments/assets/a6b3dc7f-a729-4e2f-a7c1-72903187a0d5)
![image](https://github.com/user-attachments/assets/3809d866-b686-406b-b524-9c5913521335)

感觉没啥问题

**Comment by Jinbao1001** [comment]
close #2187
