### ISSUE TITLE
bug: 引入vue 报错

### ISSUE THREAD

**Issue by ethan897** [umijs/dumi#2188]
### Version

2.3.0

### OS Version

window 11

### Node.js Version

14

### Browser Version

chrome

### Link to minimal reproduction

11

### Steps to reproduce

1

### What is expected?

1

### What is actually happening?

1

### Any additional comments? (optional)

![1](https://github.com/user-attachments/assets/d41e6af3-d028-4a9a-8b91-4fce9aca40aa)
你们给的官方demo报错

**Comment by Jinbao1001** [comment]
@jeffwcx cc, 非法字符, 是不是 `windows` 系统的问题.

**Comment by ethan897** [comment]
> @jeffwcx cc, 非法字符, 是不是 `windows` 系统的问题.

这个插件有问题，不支持window运行，mac可以跑起来
