### ISSUE TITLE
bug: markdown解析依赖报未定义的错误

### ISSUE THREAD

**Issue by anyuxuan** [umijs/dumi#2193]
### Version

2.4.9

### OS Version

macOS 14.6.1

### Node.js Version

18.16.0

### Browser Version

128.0.6613.85

### Link to minimal reproduction

无

### Steps to reproduce

1. 创建一个demos/Test.tsx demo组件，代码如下：
```tsx
import { Button } from '@alifd/next';

export default () => {
  return <Button>按钮</Button>
}
```
2. 在index.md中引入`<code src="./demos/Test.tsx"></code>`

### What is expected?

期望：正常渲染demo

### What is actually happening?

报错：Uncaught ReferenceError: detail_demo_test_deps_1 is not defined

### Any additional comments? (optional)

我临时将版本降到2.4.7能正常使用

**Comment by Jinbao1001** [comment]
@anyuxuan 可以帮忙给个最小复现仓库么, 我在 `example/normal` 中尝试后, 没有复现.

**Comment by Jinbao1001** [comment]
closed #2195
