### ISSUE TITLE
ts文件预览有错误

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/dumi#22]
使用 code 标签引入
```
<code src="./demo.tsx" />
```
代码中是
```tsx
const dataList: Item[] = new Array(10).fill(0).map((i, index) => ({ text: `第${index}个`, id: `${index}` }));
```
预览中是
```tsx
const dataList: Item[] = [10].map(i => ({ text: `第${i}个`, id: `${i}` }));
```
这两者逻辑并不一致。
![image](https://user-images.githubusercontent.com/11746742/70032243-03e29b80-15e8-11ea-8afb-a25d543e894c.png)

**Comment by PeachScript** [comment]
尝试复现了一下这个问题，没能成功，是不是还有什么特殊触发条件？
<img width="714" src="https://user-images.githubusercontent.com/5035925/70392578-5d016380-1a1c-11ea-988b-9af3feea0cb7.png">

**Comment by xiaohuoni** [comment]
高级，我重试一把。
