### ISSUE TITLE
bug: 开启mako后部分js请求会报错

### ISSUE THREAD

**Issue by Promisezhangbo** [umijs/dumi#2206]
### Version

2.4.11

### OS Version

macos 14.6.1

### Node.js Version

20.12.2

### Browser Version

google: 128.0.6613.138

### Link to minimal reproduction

无

### Steps to reproduce

<img width="457" alt="image" src="https://github.com/user-attachments/assets/6a062b9d-9b05-400c-88fb-18213243c11d">

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/0281a5e8-ba8b-4d32-89fd-4e9147d12519">

![image](https://github.com/user-attachments/assets/54379d72-348d-4277-9e4a-be6999065660)

![image](https://github.com/user-attachments/assets/865a0391-d2e6-4e5f-ac10-29f5e2fd15d6)

### What is expected?

期望js不会报错

### What is actually happening?

开启mako之后运行 dumi dev --watch 部分组件会报错

**Comment by PeachScript** [comment]
ref: https://github.com/umijs/mako/issues/1609

Mako 今天应该会发修复版本

**Comment by Jinbao1001** [comment]
mako 已修复
