### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by huang1234567** [umijs/dumi#2214]
### Version

1.1.0

### OS Version

window11

### Node.js Version

14.18.0

### Browser Version

谷歌127.0.6533.100

### Link to minimal reproduction

https://github.com/huang1234567/dfyhui

### Steps to reproduce

组件在https://codesandbox.io中打开，预览视图一直在Transpiling Modules...，组件包已发送至npm中，不知该怎么解决，求帮助!!
![image](https://github.com/user-attachments/assets/69ef24fd-cac1-480a-9722-09752a43e13a)

### What is expected?

codesandbox.io能正常显示视图

### What is actually happening?

使用dumi开发个人组件库（组件已发布至npm中），本地及github pages页打开codesandbox.io都无法预览视图

**Comment by Jinbao1001** [comment]
请使用`dumi2`
