### ISSUE TITLE
bug: 设置base后，demo设置成iframe无法访问

### ISSUE THREAD

**Issue by w514986768** [umijs/dumi#2224]
### Version

2.4.12

### OS Version

macos 13.1

### Node.js Version

16.14.2

### Browser Version

chrome 130.0.6723.117

### Link to minimal reproduction

*

### Steps to reproduce

设置base，然后用code方式引入代码并设置为iframe模式

### What is expected?

正常显示

### What is actually happening?

无法正常显示

### Any additional comments? (optional)

![image](https://github.com/user-attachments/assets/85fd5aff-b245-40ef-82f1-1eb173d308a5)

**Comment by PeachScript** [comment]
base 结尾必须带上 `/`，ref: https://d.umijs.org/config#base
