### ISSUE TITLE
bug:在文档上方配置debug: true，将页面标记为调试型文档，但在线上还是会展示

### ISSUE THREAD

**Issue by Naturalvolume** [umijs/dumi#2231]
### Version

2.4.14

### OS Version

macbook pro 13

### Node.js Version

18.18.0

### Browser Version

110.0.5481.177

### Link to minimal reproduction

no

### Steps to reproduce

![image](https://github.com/user-attachments/assets/781a02f4-974d-4c27-9895-a4322adafdec)

![image](https://github.com/user-attachments/assets/32250905-415b-4c2b-ac82-693b650fffb6)

### What is expected?

希望能隐藏一些文档

### What is actually happening?

配置了debug:true之后，在线上还是展示了

**Comment by Jinbao1001** [comment]
sorry, 才看到, #2239, 等下之后的发版

**Comment by Jinbao1001** [comment]
已发布.
