### ISSUE TITLE
bug: 当 history 为 hash 时，base 字段不生效，页面白屏无报错

### ISSUE THREAD

**Issue by mainhanu** [umijs/dumi#2233]
### Version

2.4.14

### OS Version

macOS 14

### Node.js Version

20

### Browser Version

chrome 131

### Steps to reproduce

配置

```
import { defineConfig } from 'dumi';

export default defineConfig({
  outputPath: 'docs-dist',
  themeConfig: {
    name: 'test',
  },
  base: '/docs-dist/',
  publicPath: '/docs-dist/',
  history: {
    type: "hash"
  },
  exportStatic: false,
});
```

将 history 注释后，工作正常，history 设为 hash 后，页面访问白屏且无报错

### What is expected?

在 hash 场景下，如果页面部署在非根目录下，该如何正确配置 `base` 字段？

### What is actually happening?

页面访问白屏且无报错

**Comment by mainhanu** [comment]
试出来了，hash 时不要设置 base 即可；建议文档里补充下

**Comment by ppYoung** [comment]
这也太坑了吧，浪费我一天的时间排查
