### ISSUE TITLE
bug: srcTranspiler设置为esbuild后报错

### ISSUE THREAD

**Issue by jayjliang** [umijs/dumi#2240]
### Version

2.4.15

### OS Version

macos14

### Node.js Version

20.18.0

### Browser Version

chrome120

### Link to minimal reproduction

https://d.umijs.org/guide/initialize

### Steps to reproduce

按照文档中的px create-dumi创建项目后，配置srcTranspiler为esbuild后打开页面报错

### What is expected?

页面正常

### What is actually happening?

页面报错

**Comment by Jinbao1001** [comment]
暂不支持, 之后会 ban 掉此配置. 构建提速请使用 `mako`
