### ISSUE TITLE
几个开发 Bug；

### ISSUE THREAD

**Issue by block-sexy** [umijs/dumi#227]
## 几个 bug
1、当本地开发时候，遇到致命错误，实时编译报错，到这里都 ok；但是修改完错误，不会再实时编译了，永远都不会了，除非重启；
2、.MD 内容的 tsx 代码，调用 其他 ts 文件，当遇到 函数中 使用 美元符开头的变量，比如：$tmp =1; 会报错：
Syntax Error: SyntaxError: xx.tsx: Unexpected token, expected "}" ；
 

- **Umi 版本**："dumi": "^1.0.31",
- **Node 版本**：12
- **操作系统**：mac

**Comment by PeachScript** [comment]
两个问题试了下都无法复现，能否提供可复现 repo？

**Comment by PeachScript** [comment]
已线下对焦，系 TypeScript 的类型断言写法 `<any>[]` 被识别为 JSX 导致的，改为 `[] as any` 可以 work
