### ISSUE TITLE
feat: 希望支持自定义 demo 单独访问的路由

### ISSUE THREAD

**Issue by heynext** [umijs/dumi#231]
现在 demo 单独访问的路由是 `/_demos/demo` `/_demos/demo-1` 这样的，希望可以自定义生成的路径。我们想要在构建之后拿到这个路径并且和具体的 `demo` 对应起来，现在是比较困难的。

**Comment by PeachScript** [comment]
v1.1.0-beta.7 开始修改了路径生成规则，会根据上两级目录追加前缀；另外也支持通过 `identifier` 字段自定义 demo 的路径，比如：
```js
/**
 * identifier: a-component-demo-1
 */

// demo 内容
```

将会生成 `~/demos/a-component-demo-1`，可以试试看
