### ISSUE TITLE
codesandbox上的代码无法正确运行

### ISSUE THREAD

**Issue by icerainzz** [umijs/dumi#232]
### Question
![image](https://user-images.githubusercontent.com/33819323/86892157-74c7d400-c132-11ea-944d-e670c51a2272.png)
找不到自己的包，是需要将包发布后codesandbox才可以正常运行吗？

**Comment by mortalYoung** [comment]
Yes, you should run demo after publishing your package, or codesandbox cannot find your package dependence

**Comment by PeachScript** [comment]
是的，通常来讲流程是：1. 本地开发组件库 -> 2. 发布组件库 -> 3. 发布组件库文档。

其中，第 1 步本地开发阶段是开发者自行调试，不需要 CodeSandbox，即便之前发过包了也没办法在 CodeSandbox 上加载本地最新的组件库代码；而第 3 步的文档是给用户看的，用户需要 CodeSandbox 来辅助查看 Demo，所以开发者需要完成第 2 步的发布流程。
