### ISSUE TITLE
bug: 在 extraBabelPlugins 使用  babel-plugin-import import 本地模块时, alias 未正确生效，依旧尝试从 node_modules 导入

### ISSUE THREAD

**Issue by imzue** [umijs/dumi#234]
### Versions

- dumi: 1.0.33
- @umijs/preset-dumi: 1.0.33
- node: v12.16.0
- npm: 6.4.15
- OS: Windows 10
- Browser: Firefox

### Steps to reproduce

```javascript
import { defineConfig } from 'dumi';

export default defineConfig({
  title: 'custom-package-name',
  favicon:
    'https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png',
  logo:
    'https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png',
  outputPath: 'docs-dist',
  mode: 'site',
  // more config: https://d.umijs.org/config
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'custom-package-name', // same as `title`
        libraryDirectory: 'src',
        style: true,
        camel2DashComponentName: false,
      },
    ],
  ],
});
```
### What is Expected?
通过 babel-plugin-import 导入 src 目录下的组件样式。

### What is actually happening?
通过 node_modules 导入了 custom-package-name，node_modules 也没有 custom-package-name 时，运行结果为：`These dependencies were not found`

复现 repo: https://github.com/imzue/dumi-issue-234

**Comment by PeachScript** [comment]
custom-package-name 是组件库名吗，package.json 的 name 是否设置正确？

**Comment by imzue** [comment]
> 
> 
> custom-package-name 是组件库名吗，package.json 的 name 是否设置正确？

是的，和 package.json 中 name 一致。

**Comment by imzue** [comment]
突然发现 [FAQ: 开发阶段，如何配置 md 文件中的样式按需引入？](https://d.umijs.org/guide/faq#%E5%BC%80%E5%8F%91%E9%98%B6%E6%AE%B5%EF%BC%8C%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-md-%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84%E6%A0%B7%E5%BC%8F%E6%8C%89%E9%9C%80%E5%BC%95%E5%85%A5%EF%BC%9F) ，但参照此 FAQ 的之后，依旧报错 cannot resolve module lean/lib/Button。

**Comment by imzue** [comment]
使用 [FAQ: 开发阶段，如何配置 md 文件中的样式按需引入？](https://d.umijs.org/guide/faq#%E5%BC%80%E5%8F%91%E9%98%B6%E6%AE%B5%EF%BC%8C%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-md-%E6%96%87%E4%BB%B6%E4%B8%AD%E7%9A%84%E6%A0%B7%E5%BC%8F%E6%8C%89%E9%9C%80%E5%BC%95%E5%85%A5%EF%BC%9F) 的配置方式后，在 preset-dumi => transformer/demo/dependencies 中 tranverse all require statement 时加入 `if (requireStr.includes("lean")) return; `判断，cannot resolve module 的报错不会出现。（注：此处 `lean` 为 FAQ 中的配置，等同此 issue 中的 `custom-package-name`）

**Comment by PeachScript** [comment]
package.name 配置生效的情况下，dumi dev 时会自动在 node_modules 下 symlink 到组件库目录，如果这步没有生效，说明自动 alias 出现异常了，需要提供下复现 repo

**Comment by imzue** [comment]
> 
> 
> package.name 配置生效的情况下，dumi dev 时会自动在 node_modules 下 symlink 到组件库目录，如果这步没有生效，说明自动 alias 出现异常了，需要提供下复现 repo

复现 repo: [https://github.com/imzue/dumi-issue-234](https://github.com/imzue/dumi-issue-234)

**Comment by PeachScript** [comment]
@imzue 应该和 #351 是一个原因导致的，请试下最新的 beta 版是否还存在此问题

**Comment by PeachScript** [comment]
issue 先关闭了，如果问题仍然存在请重新打开

**Comment by dream-approaching** [comment]
![](https://raw.githubusercontent.com//dream-approaching/pictureMaps/master/img/20201112181457.png)

按照配置配完，效果是可以的，只是为什么会自动生成`node_modules`并且好像死循环了，虽然只是快捷方式，但还是看着很别扭

**Comment by PeachScript** [comment]
是的，创建 symlink 到当前项目以确保 VSCode 的 module 类型检查不会出错
