### ISSUE TITLE
bug: lerna 结构项目下，resolve.includes 默认值并不是文档所示

### ISSUE THREAD

**Issue by tolerance-go** [umijs/dumi#240]
### Versions

- dumi: 1.0.33
- node: 12.18
- npm: 6.14.4 
- OS: macOS Mojave 10.14.6
- Browser: Chrome: 83.0.4103.116

### Steps to reproduce

项目下存在 lerna.json，配置相关字段

### What is Expected?

修改文档，当存在 lerna 环境下为 ['packages/pkg/src'] 否则 ['docs', 'src']  

### What is actually happening?

![image](https://user-images.githubusercontent.com/37258382/87413735-47c96480-c5fd-11ea-935b-fae6f21d223a.png)

**Comment by PeachScript** [comment]
你的意思是 lerna 下不包含 `docs` 目录，文档描述有问题？在逻辑中 `docs` 目录是始终包含的，可以查看 [源代码](https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/plugins/core.ts#L63)

**Comment by tolerance-go** [comment]
我没有测试 docs，那为我觉得文档应该表述为 ['packages/pkg/src', 'docs'] 或 ['docs', 'src']

**Comment by PeachScript** [comment]
有道理，可以来个 PR 帮 dumi 优化下 :D
