### ISSUE TITLE
bug: 相同 group.title sidemenu 没有自动合并

### ISSUE THREAD

**Issue by tolerance-go** [umijs/dumi#242]
### Versions

dumi: 1.0.33
node: 12.18
npm: 6.14.4
OS: macOS Mojave 10.14.6
Browser: Chrome: 83.0.4103.116

### Steps to reproduce

src/components/form-pro/__features__/index.md

```json
---
group:
  title: components
  path: components/form-pro
---
```

src/components/exports-button/__features__/index.md

```json
---
group:
  title: components
  path: components/exports-button
---
```

.umirc

```js
import { defineConfig } from "dumi";
import babelModuleConfig from "./babel.module.config.js";
import glob from "glob";

const matches = glob.sync("src/**/__features__");

export default defineConfig({
  resolve: {
    includes: [...matches, "docs"],
  },
  title: "bct-modules",
  outputPath: "docs-dist",
  extraBabelPlugins: babelModuleConfig.plugins,
});
```

![image](https://user-images.githubusercontent.com/37258382/87435838-d6021280-c61e-11ea-9da8-8fcc6dfb5b8c.png)

### What is Expected?

合并展示同一级 group

### What is actually happening?

分开展示了 group

**Comment by tolerance-go** [comment]
都提到了 docs 下

**Comment by monkindey** [comment]
请问下这个问题的解法是？只能把文档提到 docs 上吗？

**Comment by suedar** [comment]
同遇到该问题，md放在不同组件下，同一个group没有自动合并

**Comment by PeachScript** [comment]
group.path 一样会自动合并
