### ISSUE TITLE
bug: slugs 点击跳转有问题

### ISSUE THREAD

**Issue by mortalYoung** [umijs/dumi#245]
### Versions

- dumi:  v1.0.33
- OS: windows
- Browser: Chrome

### Steps to reproduce
官网文档就可以复现 
1. 打开官网文档 [控制菜单生成](https://d.umijs.org/guide/control-menu-generate)
2. 点击右侧 **配置式侧边菜单**

### What is Expected?
- 应该是直接路由跳转到 **配置式侧边菜单**

### What is actually happening?

- 路由跳转到了 **控制分组排序** 而不是 **配置式侧边菜单**
- 再次点击 **配置式侧边菜单** 才会跳转到 **配置式侧边菜单**

**Comment by PeachScript** [comment]
没能复现，贴个 gif？

**Comment by mortalYoung** [comment]
![dumi](https://user-images.githubusercontent.com/18719701/87849502-c125c780-c91b-11ea-84a9-1913d537626b.gif)

**Comment by mortalYoung** [comment]
应该是 `Layout.tsx` 里面 [Layout.tsx#L263](https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/themes/default/layout.tsx#L263) 去取了符合要求的最小的一个了 而不是去精准匹配当前的

**Comment by PeachScript** [comment]
#277 中把 hash 跳转的逻辑改掉了，该问题在 master 分支已修复
