### ISSUE TITLE
How I can I linter react syntax in md use eslint

### ISSUE THREAD

**Issue by aizigao** [umijs/dumi#246]
### Question
How I can I linter react syntax in md use, when I write in md, eslint don't working for react syntax, I can't find my errors

**Comment by PeachScript** [comment]
Maybe some VSCode extensions can do that but I cannot found :(

However, you can try external demo via `<code src="/path/to/YourDemo.tsx" />`, then you can get ESLint、Autocomplete、Code Snippets & etc. in the real TSX/JSX file: https://github.com/umijs/dumi/blame/master/docs/examples.md#L27
