### ISSUE TITLE
menus和routes配置混乱

### ISSUE THREAD

**Issue by haoyinag** [umijs/dumi#251]
用了site模式
如题，我配置了menus和routes，没有得到文档一样的结果
不知道问题出在哪
想在左边出现  结果要点击 右上角才会出现，而且我想右上角的也是中午也设置不了
下面看代码
```ts
  menus: {
    '/basic': [
      {
        title: '基础',
      },
      {
        title: '基础',
        children: ['Basic/basic'],
      },
    ],
  },
```
看图
![](https://upload-images.jianshu.io/upload_images/5644085-c98df00c2bdae01c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![](https://upload-images.jianshu.io/upload_images/5644085-2b62c567fbeb1915.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 读的一直是之前的内容   不清不楚
![](https://upload-images.jianshu.io/upload_images/5644085-0ead12bdd3385b8f.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### Versions
```bash
 "devDependencies": {
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.0.5",
    "dumi": "^1.0.9",
    "father-build": "^1.17.2",
    "gh-pages": "^3.0.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0"
  }
```

**Comment by PeachScript** [comment]
routes 配置贴一下看

**Comment by haoyinag** [comment]
> 算了，就写个文档而已  随便用吧  
约定式虽然能带来方便，可以少写配置，但相对也会对新人可能没那么友好，不一定能理解对应的约定规范的；
相反如果不是约定式，起码依葫芦画瓢也能用不是
就要跟预想结果不一样   起码 小白的我**整半天最后只能放弃**
提个建议：
1、如果是约定式，希望可以尽量把demo详细一点 ，起码复制粘贴后能跟预想结果一致；
2、如果不是约定式，更要详细说明吧

**Comment by zhaoyao91** [comment]
现在的约定式体系存在很大的问题
- 各自的配置分散没问题，但统一的配置，例如 order，分散管理很麻烦
- 如果向对 group 进行配置，但是不想要 `group/index.md`，则只能配置到某个页面上，这个页面没啥特殊性，但只能如此，很不合理

**Comment by PeachScript** [comment]
> 各自的配置分散没问题，但统一的配置，例如 order，分散管理很麻烦
如果是指 file order，分散管理应该才更方便吧；如果是 nav order，同一组 nav 只需要配置一个 md 就可以了

> 如果向对 group 进行配置，但是不想要 `group/index.md`，则只能配置到某个页面上，这个页面没啥特殊性，但只能如此，很不合理
文档的路由结构和文件系统的目录结构对应是更利于管理和维护的，也是约定式的意义

如果对路由生成规则或者配置方式有更好的方案，欢迎提出

**Comment by zhaoyao91** [comment]
> 如果是指 file order，分散管理应该才更方便吧；如果是 nav order，同一组 nav 只需要配置一个 md 就可以了
> 
> >

我举个例子说明。比如前面已经拍好了1，2，3，4，5，6，7，8，9，现在要新插入一个到位置5、6 中间，我就需要找到所有的后置文档并且进行修改，而且这种查找还不能一目了然

**Comment by zhaoyao91** [comment]
我的看法是，绑定在单个对象上的配置，和他放在一起很好，但是统筹一组对象的配置，应该放在统筹者那里，而不是各自拥有一个碎片，然后拼起来形成一个逻辑

**Comment by PeachScript** [comment]
你的看法我认同，但我理解 group 下排位第一的文档，就是统筹者，它可以是 `index.md` 也可以是任何其他的；

另外 order 跟随文档配置的确无法看到排序的全貌，所以可以考虑给 order 之间留一些步长，或者使用小数的 order 值，如果顺序变更非常频繁，可以用配置式手动管控；未来也许会做两全的方案：支持 GUI 拖拽排序。

**Comment by zhaoyao91** [comment]
> 但我理解 group 下排位第一的文档，就是统筹者，它可以是 `index.md` 也可以是任何其他的；

这个很难说，比如组件在动态增长，自然排序第一位的文档不总是那一个

**Comment by ChenYCL** [comment]
我也觉得是的路由和菜单,多级这块不好调控

**Comment by miaolin1993** [comment]
遇到了同样的问题，这个问题要怎么解决呢？有具体解决办法吗，是改配置还是升版本或是怎么样的
