### ISSUE TITLE
bug: demo jsx 使用 react hooks 报错

### ISSUE THREAD

**Issue by ILiuDongHui** [umijs/dumi#254]
### Versions

- dumi: 1.0.33
- node: 12.16.2
- npm: 6.14.5
- OS: windows 10 1909
- Browser: chorme latest

### Steps to reproduce
useState<boolean>(false) 

### What is Expected?
可以正常使用 React HOOK

### What is actually happening?
useState<boolean>(false) 报错

**Comment by PeachScript** [comment]
错误内容是什么
