### ISSUE TITLE
bug: 修改`.md文件`的内容开发服务不会更新

### ISSUE THREAD

**Issue by xianjie-li** [umijs/dumi#256]
### Versions

- dumi: ^1.0.27
- node: 10.15.0
- npm: 6.4.1
- OS: windows10
- Browser: chrome80

### Steps to reproduce
```
// config.js
export default {
  alias: {
    '@': path.resolve(__dirname, '../src'),
    'mylib': path.resolve(__dirname, '../src/components'),
  },
  title: 'xx',
  description: 'xxxxx',
  logo: 'xxxx',
  locales: [['zh-CN', '中文']],
  outputPath: 'docs',
}
```

### What is Expected?
修改`.md文件`或其中通过code引入的tsx时，开发服务器内容未更新，刷新后也不更新，需要重启后服务后修改才会生效

**Comment by PeachScript** [comment]
无法复线，检查一下是不是开了全局代理

**Comment by Iixianjie** [comment]
> 无法复现，检查一下是不是开了全局代理

你好，我创建了一个复现仓库<https://gitee.com/llixianjie/dumi0727.git>

图里面的docs文件夹内的内容修改后无更新, 其他地方都是正常的

![D7)%V660P@@@VX3K6M2L0ZV](https://user-images.githubusercontent.com/34636376/88502807-3a9b7500-d002-11ea-9e0e-92914f422b57.png)

**Comment by PeachScript** [comment]
现在问题还存在吗
