### ISSUE TITLE
怎么配置类似dumi的菜单

### ISSUE THREAD

**Issue by DerrickTel** [umijs/dumi#258]
### Question
![image](https://user-images.githubusercontent.com/24643779/88998510-cd028800-d324-11ea-8a66-c149fa90be29.png)

**Comment by mortalYoung** [comment]
Markdown 文件支持在文件顶端添加注释的方式来配置该页面的标题、分组等
```markdown
---
title: 标题内容
---
```

具体支持项如下：[frontmatter](https://d.umijs.org/config/frontmatter)
具体 demo 如下：[dumi 介绍](https://github.com/umijs/dumi/blob/master/docs/guide/index.md)

**Comment by PeachScript** [comment]
可以查看 dumi 的文档配置：https://github.com/umijs/dumi/blob/master/config/config.js#L7

**Comment by DerrickTel** [comment]
我的意思是。。这种黑体加粗的类型

**Comment by PeachScript** [comment]
配置式菜单且不设置 path，就是黑体加粗的
