### ISSUE TITLE
为什么dumi在dev环境ant组件样式全部丢失呢？如何恢复

### ISSUE THREAD

**Issue by lio-mengxiang** [umijs/dumi#261]
### Question
为什么dumi在dev环境ant组件样式全部丢失呢？代码如下
### Sample Code
```jsx
import React from 'react';
import { Button } from 'antd';

export default () => <Button type="primary">我是 antd 的按钮</Button>;
```
如何让样式显示出来呢？

**Comment by lio-mengxiang** [comment]
知道答案了，需要在config里配置

**Comment by YJKZHUZHU** [comment]
具体怎么配置呢

**Comment by Pszz** [comment]
具体怎么配置呢??? @lio-mengxiang

**Comment by luoheix** [comment]
.umirc.ts 文件中添加以下配置 @Pszz
`  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ],`
