### ISSUE TITLE
怎么在dumi中自定义antd主题

### ISSUE THREAD

**Issue by huhaha24** [umijs/dumi#263]
### umi文档中说是可以在theme中设置，但是我在dumi的theme中设置没有作用，并且如果用文件路径的话，会报theme只能是Object类型

加上这个的话，antd样式是可以加载成功的
![image](https://user-images.githubusercontent.com/37647607/89508659-d0a07e00-d800-11ea-8d47-2e9b15ca5d7f.png)
单独加下面这个的时候，自定义样式是可以的
![image](https://user-images.githubusercontent.com/37647607/89508753-eada5c00-d800-11ea-8d62-989eba5f50a0.png)

但是两个一起用就不行就只有antd的样式，自定义样式不起作用
![image](https://user-images.githubusercontent.com/37647607/89508823-047ba380-d801-11ea-9b7f-992ba142350c.png)

想问问各位大佬怎么做？万分感谢～

**Comment by PeachScript** [comment]
`babel-plugin-import` + `theme` 都是需要的：https://umijs.org/config#theme

**Comment by huhaha24** [comment]
我设置了但是没有用诶～
![image](https://user-images.githubusercontent.com/37647607/89599908-5240ec00-d893-11ea-9302-315eaa4265a5.png)
![image](https://user-images.githubusercontent.com/37647607/89599947-684eac80-d893-11ea-8b1a-d8d5b0331287.png)

**Comment by PeachScript** [comment]
style: true

**Comment by huhaha24** [comment]
可以了，非常感谢🙏

**Comment by lbyupup** [comment]
> `style: true`

请问配置后，可以在less文件里面@primary-color引用这个变量嘛，我用了之后样式生效，可是build会报错说找不到变量
