### ISSUE TITLE
代码块出现空格

### ISSUE THREAD

**Issue by Too-Tao** [umijs/dumi#264]
![image](https://user-images.githubusercontent.com/40811570/89516013-74425c00-d80a-11ea-80cd-dbb130dc6af9.png)
这是为什么...

**Comment by PeachScript** [comment]
请提供版本号和复现步骤

**Comment by Too-Tao** [comment]
版本号：
![image](https://user-images.githubusercontent.com/40811570/89535597-36086500-d829-11ea-87cd-078fbe14fff7.png)
依赖：
![image](https://user-images.githubusercontent.com/40811570/89535884-a31bfa80-d829-11ea-9971-6625629d8e5d.png)

复现步骤：
当在md文件中引入样式包文件后，页面中的代码部分会出现如上图空格样式，是不是编写代码块时，不能引入样式包。
![image](https://user-images.githubusercontent.com/40811570/89535551-24bf5880-d829-11ea-9990-675de72ebea2.png)

**Comment by Too-Tao** [comment]
> 请提供版本号和复现步骤

版本号：
![image](https://user-images.githubusercontent.com/40811570/89536076-e9715980-d829-11ea-85c3-013613b3a909.png)

依赖：
![image](https://user-images.githubusercontent.com/40811570/89536096-f1c99480-d829-11ea-9d7e-abe1ba3e57a8.png)

复现步骤：
当在md文件中编写代码块时，引入样式包文件后，页面中的代码部分会出现如上图空格样式，是不是编写代码块时，不能引入样式包。
![image](https://user-images.githubusercontent.com/40811570/89536208-23426000-d82a-11ea-88fc-1b90a04c1309.png)

**Comment by Too-Tao** [comment]
> 请提供版本号和复现步骤

在 .umirc.ts配置styles是不是不支持引入node_modules包中或者项目中的css文件

**Comment by PeachScript** [comment]
看起来可能是组件库的样式影响了文档源代码的样式，可以审查元素确认下，如果是的话只能组件库样式做规避

`styles` 配置项只能是远端 CSS 地址或者 CSS 文本内容，如果要引本地文件可以在 `src/app.ts` 中引入

**Comment by PeachScript** [comment]
另外，版本号不是提供 package.json 中的版本，而是要提供 node_modules 中实际安装好的版本
