### ISSUE TITLE
bug: 对Modal、Table等带有多语言信息的antd组件进行二次封装后，无法识别框架（pro/umi）的语言信息

### ISSUE THREAD

**Issue by ppmmwozuiai** [umijs/dumi#265]
### Versions

- dumi: 1.0.31
- node: latest
- npm: latest
- OS: widnows10 
- Browser: chrome/edge

### Steps to reproduce

[复现库（以Modal为例）](https://github.com/ppmmwozuiai/lean)

对Modal、Table等组件进行二次封装打包后，组件无法识别框架（ant design pro / umi）的语言配置，而只显示英文
必须在组件外套ConfigProvider才能设定语言

**Comment by PeachScript** [comment]
复现库应该只是组件库源码，有『无法识别框架（ant design pro / umi）的语言配置』这个问题的复现么？

**Comment by lbyupup** [comment]
我也遇到了这个问题，在dumi文档中基于table组件封装的组件，分页器显示的是英文的，请问在umi项目内使用该组件会恢复成中文的吗
