### ISSUE TITLE
how to import subModule

### ISSUE THREAD

**Issue by Vincent-X** [umijs/dumi#266]
### Questions
structure

|src/
|----/Component
|----index.ts
|--------/ComponentA
|----------index.tsx
|----------index.md

the doc is writing on index.md 

in `index.ts`
```
export { default as ComponentA } from 'dumi-lib/Component'
```

in `index.md`
```
import React from 'react'
import { ComponentA } from 'dumi-lib/Component'

export default () => <ComponentA />
```

it will cause
`ERROR [dumi]: cannot resolve module 'dumi-lib/Component' in '[pwd]/src/Component/ComponentA'`

**Comment by PeachScript** [comment]
Circle dependency? It would be better if there has a reproduce repository.

By the way, why import from `dumi-lib/Component` rather than `./Component` in `src/index.ts`? And your directory structure looks like incorrect, what is the relationship between `Component` and `ComponentA`?

**Comment by FrendEr** [comment]
> Circle dependency? It would be better if there has a reproduce repository.
> 
> By the way, why import from `dumi-lib/Component` rather than `./Component` in `src/index.ts`? And your directory structure looks like incorrect, what is the relationship between `Component` and `ComponentA`?

人家这个是指 demo 里面需要说明如何引用子组件，在 demo 里面总不可能写相对路径吧
