### ISSUE TITLE
请问如何阻止dumi渲染jsx代码块的内容呢？

### ISSUE THREAD

**Issue by wood3n** [umijs/dumi#268]
### Question
如题，markdown的代码块用jsx标识的话，就给我当成组件来渲染了，报错，请问有没有相关配置阻止渲染当前代码块为组件实例呢？
### Sample Code
![image](https://user-images.githubusercontent.com/31716713/89727579-d7c1c900-da58-11ea-8311-a526dc0259d0.png)
![image](https://user-images.githubusercontent.com/31716713/89727584-e0b29a80-da58-11ea-84d7-42826081ad3b.png)

**Comment by wood3n** [comment]
我现在的解决方法是改代码块的标识，不用`jsx`，用`javascript`了。

**Comment by PeachScript** [comment]
可参考文档配置：https://d.umijs.org/config#previewlangs

**Comment by wood3n** [comment]
> 可参考文档配置：https://d.umijs.org/config#previewlangs

但是我只想不转换当前页面的这个代码块😂 😂 ，previewLangs把所有的标识为jsx的代码块都干掉了。

**Comment by PeachScript** [comment]
@wood3n 可以使用
<pre>
```jsx | pure
```
</pre>

**Comment by wood3n** [comment]
> @wood3n 可以使用
> 
> ```jsx | pure
> ```

好的好的，多谢！
