### ISSUE TITLE
bug: code block的样式入侵到了md文档

### ISSUE THREAD

**Issue by FateRiddle** [umijs/dumi#270]
### Versions

- dumi: 1.0.33
- node: 11.15.0
- npm: 6.7.0
- OS: mac
- Browser: chrome

### Steps to reproduce
1. 接入一个 @alifd/next 的ui组件的demo https://fusion.design/pc/component/doc/102
2. 接入demo的文档的li、p等标签都被污染了，字变小，list-style也变成了none
![](https://img.alicdn.com/tfs/TB1Y.iZQVT7gK0jSZFpXXaTkpXa-680-170.png)

### What is Expected?

希望能够避免样式被入侵

**Comment by PeachScript** [comment]
目前没找到可靠的样式隔离方案，只能开发者自己规避，也欢迎 PR

**Comment by jhoneybee** [comment]
@PeachScript  我看似乎有 `shadow DOM` 可以隔离样式， 这个我还没有用过，但是看介绍似乎可以。

- https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

**Comment by PeachScript** [comment]
@jhoneybee ShadowDOM 坑比较多，DOM 事件传递也会有问题，如果有兴趣可以试试看，refer #7
