### ISSUE TITLE
code demo的全屏链接的地址刷新后会404，且code的demo的链接在有baseurl的时候会不对。

### ISSUE THREAD

**Issue by FateRiddle** [umijs/dumi#273]
### Versions

- dumi: 1.0.33
- node: 11.15.0
- npm: 6.7.0
- OS: mac
- Browser: chrome

### Steps to reproduce

1. 例如这个demo，跳转的链接不对 https://alibaba.github.io/form-render/playground
2. 又例如这个网址https://form-render.github.io/schema-generator/，点击“formily”按钮进入全屏的demo，刷新，变成404

**Comment by PeachScript** [comment]
第 1 个链接可以正常打开；第 2 个和 #275 是重复问题？

**Comment by FateRiddle** [comment]
@PeachScript 
1. 第一个的全屏链接我看还是404 https://alibaba.github.io/_demos/index
2. 第二个是 https://form-render.github.io/schema-generator      试着点击“formily”按钮，可以正常跳到demo，也正常显示。但是刷新一下就404了。应该就是你说的 _ 开头的文件被git page忽视的问题吧。和 #275 应该是两个问题， #275 是a标签跳的路径就错了

**Comment by PeachScript** [comment]
v1.1.0-beta.7 已修复
