### ISSUE TITLE
feat: 希望页面按需加载后，loading的默认展示能够美一点，现在就是个小字的“loading...”

### ISSUE THREAD

**Issue by FateRiddle** [umijs/dumi#274]
![image](https://user-images.githubusercontent.com/12005259/89855386-ecbd6a00-dbc8-11ea-9784-32d0f260fae3.png)
看着感觉会很山寨

**Comment by PeachScript** [comment]
走配置自定义组件即可：https://umijs.org/zh-CN/config#dynamicimport
