### ISSUE TITLE
bug: 当网站的base不是“/”时，<a> 标签相对链接跳转不对（没有考虑到base）

### ISSUE THREAD

**Issue by FateRiddle** [umijs/dumi#275]
### Versions

- dumi: 1.0.33
- node: 11.15.0
- npm: 6.7.0
- OS: mac
- Browser: chrome

### Steps to reproduce
例如网站部署在 https://alibaba.github.io/form-render/

`<a href="/playground" target="_blank">Playground</a>` 会跳到https://alibaba.github.io/playground/
而不是正确的 https://alibaba.github.io/form-render/playground/

### What is Expected?
和` [Playground](/playground)` 一致，都考虑到base，会跳到https://alibaba.github.io/form-render/playground/

**Comment by Yezzle** [comment]
上面说解决了 ，那为啥 站点模式时，我 nav上的 a标签还是没有加上bashurl啊

**Comment by PeachScript** [comment]
1.1.0.beta-27 已支持
