### ISSUE TITLE
bug: 自定义模板导致编译失败

### ISSUE THREAD

**Issue by JohnApache** [umijs/dumi#276]
### Question
我想给 html 标签 添加 `lang='zh-CN'` 属性该如何添加，文档里没有找到相关配置
### Sample Code
`<html lang="zh-CN">`

**Comment by PeachScript** [comment]
可参考这个：https://umijs.org/zh-CN/docs/html-template#%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E6%A8%A1%E6%9D%BF

**Comment by JohnApache** [comment]
@PeachScript  添加不了模版文件， 我直接创建在 `/doc/document.ejs`  `/document.ejs` ，目录下是没有任何效果的， 而创建在 `/pages/document.ejs` 和 `/src/pages/document.ejs` 这两个位置都会导致 dumi 编译失败，无法正常启动， 错误日志如下
```
✖ Webpack
  Compiled with some errors in 3.05s

 ERROR  Failed to compile with 38 errors                                                                                                                                    10:56:46

These relative modules were not found:

* ../docs/blog/algorithm/LRU.md in ./.umi/core/routes.ts
* ../docs/blog/algorithm/permutation-and-combination.md in ./.umi/core/routes.ts
* ../docs/blog/algorithm/sort.md in ./.umi/core/routes.ts
* ../docs/blog/backend/redis.md in ./.umi/core/routes.ts
* ../docs/blog/data-structure/ linked-list.md in ./.umi/core/routes.ts
* ../docs/blog/data-structure/avl.md in ./.umi/core/routes.ts
* ../docs/blog/data-structure/bst.md in ./.umi/core/routes.ts
```

求正确添加模版文件的姿势

**Comment by PeachScript** [comment]
这可能是 dumi 的 bug，我看下

**Comment by mortalYoung** [comment]
我用 `npx @umijs/create-dumi-lib ` 命令创建了一个 `dumi` 项目并在 `/src/pages` 文件夹下新增了 `document.ejs` 文件，但是我并不会导致文件编译失败，并且模板文件是生效了的

## 环境
- Platform: windows
- Version: dumi@1.0.34，umi@3.2.18

**Comment by PeachScript** [comment]
@JohnApache 请提供下版本信息

**Comment by JohnApache** [comment]
@PeachScript  @mortalYoung 
#环境
- Platform: Mac
- Version: dumi@1.0.26, umi@3.2.2

**Comment by PeachScript** [comment]
@JohnApache 尝试过最新版吗，正式版是 dumi@1.0.34

**Comment by JohnApache** [comment]
@PeachScript  本地`dumi`更新到 `1.0.34`版本没有报错了，在dumi 项目根目录下创建 `/pages/document.ejs`  模版，可以修改 html 的 `lang` 属性， 感谢
