### ISSUE TITLE
手机端 左侧菜单栏收起问题

### ISSUE THREAD

**Issue by dream-approaching** [umijs/dumi#294]
### Question
现状：手机端点击空白处无法收起菜单栏，点了某个菜单会跳转，但是也没有收起菜单栏
预期：点击空白处可以收起菜单栏，点了某个菜单在页面跳转之后也收起菜单栏

### Sample Code
无

### Others
dumi版本：`1.0.34`
我试了[dumi文档](https://d.umijs.org/config)的官网手机端模式，是符合我预期的，不过没找到相关配置
然后试了下[umi文档](https://umijs.org/guide/boost-compile-speed)的官网手机端模式，发现和我的项目一样，手机端菜单栏不能正常收起

**Comment by PeachScript** [comment]
v1.0.35 正式版也处理了
