### ISSUE TITLE
Previewer 的 external 功能未适配 base 配置？

### ISSUE THREAD

**Issue by noyobo** [umijs/dumi#301]
https://github.com/umijs/dumi/blob/adcdd665a9527ee2b087c6b372ddd82019f0f9f5/packages/theme-default/src/builtins/Previewer.tsx#L123

当配置了 `.umirc` 的 base 路径后链接未适配

**Comment by PeachScript** [comment]
请提供相关版本号

**Comment by noyobo** [comment]
> 请提供相关版本号

- dumi: 1.0.34
- @umijs/preset-dumi: 1.0.34

@PeachScript

**Comment by PeachScript** [comment]
1.1 beta 版本修复了，master 的代码现在是 1.1 beta 版本的代码，可以尝试切换到 beta 版
