### ISSUE TITLE
如何在已经项目中集成dumi的情况下,在dumi中的md文档中引用原有项目下的组件和方法

### ISSUE THREAD

**Issue by xjl271314** [umijs/dumi#302]
### Question

目前在已有的项目中按照FAQ中的方式集成了dumi,可以正常的显示相关的文档界面,但是想要写几个组件demo的时候,需要使用到原有项目中暴露在window上的对象或者其他的组件。

在config.js中配置了模块别名,是现在引用报错了。

### Sample Code

![image](https://user-images.githubusercontent.com/20588030/91703356-a0a08c80-ebac-11ea-8ce6-84cc2e3987da.png)

![image](https://user-images.githubusercontent.com/20588030/91703632-13aa0300-ebad-11ea-9a9d-7879284ca412.png)

**Comment by PeachScript** [comment]
别名要给文件系统中的绝对路径

**Comment by xjl271314** [comment]
![image](https://user-images.githubusercontent.com/20588030/91805112-1dd80a00-ec5e-11ea-9e4e-d7021315da03.png)

使用绝对路径会报错安装包找不到

**Comment by PeachScript** [comment]
这说明别名配置生效了，需要确保 src 需要的依赖安装正确且依赖的别名也配置正确

**Comment by xjl271314** [comment]
嗯嗯  是的 现在在解决一些 原有项目中别名某些报错的问题 我觉得这个点可以在FAQ下加一下  

同步下 需要解决原有项目的模块别名问题(需要使用绝对路径)

感谢。
