### ISSUE TITLE
feat: 支持通过 FrontMatter 设置隐藏文档

### ISSUE THREAD

**Issue by yesmeck** [umijs/dumi#303]
### Description

有时候某篇文档不想展示，但又不想把文件删掉（可能需要进一步调整再展示）。

### Solution

通过 FrontMatter 提供一个 hide 配置。

```
---
title: 看不见我
order: 3
hide: true
---
```

**Comment by fangzhengjin** [comment]
还有一种情况也会用到这个, 通过文件夹嵌套来自动生成group时, 如果要调整group的排序就需要在文件夹下新建一个index.md来设置, 设置后如果能通过hide隐藏就不会显示在列表上了

**Comment by PeachScript** [comment]
[v1.1.0-beta.31](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-beta.31) 已支持
