### ISSUE TITLE
md文件中的code示例使用

### ISSUE THREAD

**Issue by xjl271314** [umijs/dumi#307]
### Question

在md文件中引入了code并且指向了同级的tsx文件。

现象: 组件渲染不出来

是否跟路径相关或者其他原因？

环境： "dumi": "^1.0.34"

### Sample Code

![image](https://user-images.githubusercontent.com/20588030/92002752-caa3ab80-ed72-11ea-876a-b7a1b804c4c4.png)
![image](https://user-images.githubusercontent.com/20588030/92002803-d8f1c780-ed72-11ea-9e3f-185636b37af9.png)

**Comment by xjl271314** [comment]
> ### Question
> 在md文件中引入了code并且指向了同级的tsx文件。
> 
> 现象: 组件渲染不出来
> 
> 是否跟路径相关或者其他原因？
> 
> 环境： "dumi": "^1.0.34"
> 
> ### Sample Code
> ![image](https://user-images.githubusercontent.com/20588030/92002752-caa3ab80-ed72-11ea-876a-b7a1b804c4c4.png)
> ![image](https://user-images.githubusercontent.com/20588030/92002803-d8f1c780-ed72-11ea-9e3f-185636b37af9.png)

已解决:

直接在md文件中使用

<code src="/path/index.tsx />"

注意引用原有文件的地址需要使用相对路径

**Comment by Echosjj** [comment]
> > ### Question
> > 在md文件中引入了code并且指向了同级的tsx文件。
> > 现象: 组件渲染不出来
> > 是否跟路径相关或者其他原因？
> > 环境： "dumi": "^1.0.34"
> > ### Sample Code
> > ![image](https://user-images.githubusercontent.com/20588030/92002752-caa3ab80-ed72-11ea-876a-b7a1b804c4c4.png)
> > ![image](https://user-images.githubusercontent.com/20588030/92002803-d8f1c780-ed72-11ea-9e3f-185636b37af9.png)
> 
> 已解决:
> 
> 直接在md文件中使用
> 
> <code src="/path/index.tsx />"
> 
> 注意引用原有文件的地址需要使用相对路径
我引用了相对路径，demo 还是解析不出，节点是空的
