### ISSUE TITLE
通过Code引入外部Demo的时候是否支持ts,js结尾的文件?

### ISSUE THREAD

**Issue by xjl271314** [umijs/dumi#308]
### Question

通过Code引入外部Demo的时候是否支持ts,js结尾的文件?

尝试在config.js中添加previewLangs:['js']并不起作用。

### Sample Code

![image](https://user-images.githubusercontent.com/20588030/92061670-711a9b80-edc9-11ea-8aa3-8ddf95c23f8f.png)

**Comment by PeachScript** [comment]
js/ts 结尾的文件通常不是 React Component 吧

**Comment by xjl271314** [comment]
目前我们项目内部的组件导出是以js为结尾的jsx文件

**Comment by qiaodaima** [comment]
我觉得还是有必要支持一下 `js` `json`结尾的文件，
比方说当展示的代码特别长的时候，这个时候不是需要 ` React Component`
仅仅是为了展示代码

**Comment by qiaodaima** [comment]
#29 这个小哥也有同样的问题，
比方说我只是想演示一段js代码块，仅仅是展示作用，但是他并不是一个react组件，
直接把演示的js代码块写在md文件显得不那么优雅，想外部导入

**Comment by qiaodaima** [comment]
@PeachScript

**Comment by PeachScript** [comment]
这是两个问题吧，

从 demo 渲染来看，js/ts 文件是不合规的 JSX，`previewLangs` 设计的本意是应对不需要解析 JSX 为 demo 的场景，在这里确实产生误导了，目前没有支持的计划，建议 rename 为 .jsx 以获得编辑器正常的 lint 及高亮；

从源代码展示来看，目前没有碰到巨量源代码的展示需求，如果量太大直接放文档是否合适，以及是不是放 GitHub 的链接更合适；不过近期会计划支持 md 中内嵌 md，源代码这个场景应该也能够被满足。

这个 issue 先 close 了

**Comment by fjc0k** [comment]
单纯嵌入代码还是有需要的，特别源代码有点长，又是 Typescript 时，写在 md 里太难受了，根本不知道对不对。。。
