### ISSUE TITLE
feat: hideActions参数支持隐藏 复制功能 和 源代码功能

### ISSUE THREAD

**Issue by xjl271314** [umijs/dumi#311]
### Description

现有一些场景下需要显示某些组件的展示效果,但是又不想展示复制功能和显示源代码的功能。

是否可以通过配置hideActions参数支持隐藏。

目前仅支持了<'CSB' | 'EXTERNAL'>

**Comment by PeachScript** [comment]
这种情况更适合 inline 模式吧

**Comment by ChenYCL** [comment]
请问现在支持了么 隐藏源码

**Comment by xrkffgg** [comment]
@PeachScript 这个功能 搞么？

**Comment by PeachScript** [comment]
> 请问现在支持了么 隐藏源码

具体场景是啥，inline 模式能否满足需要
