### ISSUE TITLE
feat: 提供类似docz menu 的 FrontMatter 

### ISSUE THREAD

**Issue by MyCupOfTeaOo** [umijs/dumi#312]
### Description

是否可以提供类似于 docz menu 的 FrontMatter 
这样的话就可以把子菜单写到其他文件夹下

我是这样的场景,因为我的每个组件都是一个文件夹,我想在组件内部建个docs的文件夹里面写文档和用例,但是目前这样除了指定并手动配置routes,不然会出现如图的菜单结构
![image](https://user-images.githubusercontent.com/29906873/92209460-a1dcfc80-eebf-11ea-8f76-f04ea6263644.png)
![image](https://user-images.githubusercontent.com/29906873/92209675-fbddc200-eebf-11ea-83c3-41b6ed20c183.png)
docz可以通过这样的一个配置指定当前页面是哪个具体的菜单下的
![image](https://user-images.githubusercontent.com/29906873/92209812-37788c00-eec0-11ea-81be-0d5bdfef97e0.png)
希望可以提供这样的配置

**Comment by MyCupOfTeaOo** [comment]
经测试目前可是这样实现
![image](https://user-images.githubusercontent.com/29906873/92210393-36942a00-eec1-11ea-9efd-a872db095da5.png)
![image](https://user-images.githubusercontent.com/29906873/92210428-47dd3680-eec1-11ea-8715-8cfb7084e79b.png)

但我不知道zhe这个是否是正确的实现方法

**Comment by PeachScript** [comment]
文件层级不一样的 md 想归类到同一 group 下，只需要保证 group.path 一致即可，可以参考 ahooks 的项目：https://ahooks.js.org/hooks/async

**Comment by MyCupOfTeaOo** [comment]
> 文件层级不一样的 md 想归类到同一 group 下，只需要保证 `group.path` 一致即可，可以参考 ahooks 的项目：https://ahooks.js.org/hooks/async

好的谢谢
