### ISSUE TITLE
bug: md文件引入外部jsx文件时，如果jsx文件是以n开头，生成的routes.ts会把\n识别为换行

### ISSUE THREAD

**Issue by shuqiyige** [umijs/dumi#315]
### Versions

- dumi:1.0.34
- node:v12.11.1
- npm:6.11.3
- OS:windows 10
- Browser:chrome 85

### Steps to reproduce
bug: md文件引入外部jsx文件时，如果jsx文件是以n开头，
### What is Expected?
期望不要换行
### What is actually happening?
生成的routes.ts会把\n识别为换行

**Comment by PeachScript** [comment]
没理解问题是什么，请提供截图、错误日志、复现仓库之类有助于描述问题的信息

**Comment by shuqiyige** [comment]
# 外部jsx文件，文件名是n开头
![外部jsx文件，文件名是n开头](http://chuantu.xyz/t6/740/1599701692x992248267.png)


# 在md文件中引用文件
![在md文件中引用文件](http://chuantu.xyz/t6/740/1599701751x992249049.png)

# 生成的routes.ts会把\\n识别为换行
![生成的routes.ts](http://chuantu.xyz/t6/740/1599701843x992248267.png)

**Comment by shuqiyige** [comment]
> 没理解问题是什么，请提供截图、错误日志、复现仓库之类有助于描述问题的信息

我已经把问题图片上传

**Comment by PeachScript** [comment]
@shuqiyige 看到了，感谢反馈

**Comment by daodaoker** [comment]
我也遇到了，目前只有修改文件名才行

**Comment by PeachScript** [comment]
似乎 beta 版已经不存在这个问题了， @shuqiyige @daodaoker 两位是否方便用 dumi@next 在 windows 中测试下？

**Comment by daodaoker** [comment]
[Error: EINVAL: invalid argument, mkdir 'D:\work\doc-dumi\docs-dist\~demos\:uuid'] {
&nbsp; errno: -4071,
&nbsp; code: 'EINVAL',
&nbsp; syscall: 'mkdir',
&nbsp; path: 'D:\\work\\doc-dumi\\docs-dist\\~demos\\:uuid'
}



升级dumi版本后，目录里面的文件没有n开头的，都编译不过啦。无法验证问题是否解决了描述的问题。

**Comment by PeachScript** [comment]
> [Error: EINVAL: invalid argument, mkdir 'D:\work\doc-dumi\docs-dist\~demos\:uuid'] {
> &nbsp; errno: -4071,
> &nbsp; code: 'EINVAL',
> &nbsp; syscall: 'mkdir',
> &nbsp; path: 'D:\\work\\doc-dumi\\docs-dist\\~demos\\:uuid'
> }
> 
> 
> 
> 升级dumi版本后，目录里面的文件没有n开头的，都编译不过啦。无法验证问题是否解决了描述的问题。

感谢尝试，这是在执行什么命令的时候出现的？有 windows 的 CI 按理说不会挂掉才是

**Comment by PeachScript** [comment]
实测 beta 版本已经不存在此问题，请尝试切换到 beta，近期会发布 1.1 正式版了
