### ISSUE TITLE
设置了peerDependencies后通过codesandbox访问会缺省peerDependencies的包

### ISSUE THREAD

**Issue by xiexingen** [umijs/dumi#316]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
1.比如基于antd的自定义组件库，安装了antd并且设置了package.json中的peerDependency 包含antd
2.本地跑是正常的，发布后的静态页面也是正常的，但是访问静态页面中的codesandbox 后那边打开后不会安装peerDependency中的包，不知道是不是我用法问题
![image](https://user-images.githubusercontent.com/7939085/93157813-8bdfff00-f73d-11ea-9fc2-3b42f7a541a7.png)

![image](https://user-images.githubusercontent.com/7939085/93157780-77036b80-f73d-11ea-92b9-295284d27437.png)

发布后的文档地址：
https://wetrial.github.io/wetrials/component/common/scroll-bar#%E6%A1%88%E4%BE%8B
codesandbox预览地址：
https://codesandbox.io/s/laughing-tdd-v2l35?file=/demo.tsx

不知道是不是我自己使用的问题

**Comment by PeachScript** [comment]
这是有意设计的 feature，如果这个 feature 造成了某个 bug，请先完善 issue 模板中需要的信息再讨论

cc @xiaohuoni

**Comment by xiaohuoni** [comment]
@xiexingen 补充一下问题，thk！

**Comment by xiexingen** [comment]
好的  我完善下

**Comment by PeachScript** [comment]
理解了，`peerDependencies` 的识别在 beta 版中已经支持了，可以安装 dumi@next 试试

提 issue 版本号、描述和复现是必要的，否则很难理解

**Comment by xiexingen** [comment]
ok，谢谢

**Comment by PeachScript** [comment]
[v1.0.35](https://github.com/umijs/dumi/releases/tag/dumi%401.0.35) 正式版也支持 `peerDependencies` 合并了
