### ISSUE TITLE
优化本地主题的目录结构描述，避免歧义

### ISSUE THREAD

**Issue by varzhonglei** [umijs/dumi#318]
### Question
用yarn create @umijs/dumi-lib --site 初始化项目
升级dumi版本： "dumi": "1.1.0-beta.16"
创建对应文件夹 .dumi/theme
目录如下
![image](https://user-images.githubusercontent.com/23551811/92767878-1e913e80-f3ca-11ea-9470-eb60cf734f6e.png)

但是为何还是默认主题？

**Comment by varzhonglei** [comment]
我找到原因了
![image](https://user-images.githubusercontent.com/23551811/92776581-fb6a8d00-f3d1-11ea-949b-bb6640f05c41.png)
方法二， 目录结构是这样才生效的， 麻烦核对一下哦

**Comment by PeachScript** [comment]
> 方式二，在本地项目中创建 .dumi/theme 的文件夹，**目录结构和上方 src 目录一致**

文档中有说明的，看起来需要描述得更清楚些
