### ISSUE TITLE
code 引入外部代码解析错误

### ISSUE THREAD

**Issue by qiaodaima** [umijs/dumi#320]
### Question
用相对路径引入了一个文件
但是解析没生效

### Sample Code
![image](https://user-images.githubusercontent.com/30823413/93046038-6a263f80-f68b-11ea-96e7-5f0d867ae875.png)

**Comment by PeachScript** [comment]
无法复现，用 dumi@next 试试看

**Comment by qiaodaima** [comment]
@PeachScript 用了dumi@next  删除node_modules重新yarn可以了
