### ISSUE TITLE
Github Action 自动发布会丢失CNAME

### ISSUE THREAD

**Issue by qiaodaima** [umijs/dumi#321]
### Question
GitHub不是有静态托管功能么，
就是github pages，然后可以自定义域名，
其实就是生成一个CNAME文件

然后像是有一些自动发布，比如 Github Action
然后我发现有一个问题，自动发布是每次直接覆盖上次的文件，
也就是说，每次发布，CNAME都没有了

这个问题怎么解决

**Comment by PeachScript** [comment]
CNAME 放入 `/public` 文件夹下，参考：https://umijs.org/zh-CN/docs/directory-structure#public-%E7%9B%AE%E5%BD%95
