### ISSUE TITLE
我引入less-loader 就会报错No loader specified，帮忙看一下> @xiaohuoni 是的昨天我加上这个配置 并单独抽离出来加载 可以使用了 感觉现有的文档还有有些简单 一些问题不太好查阅。

### ISSUE THREAD

**Issue by Echosjj** [umijs/dumi#322]
> @xiaohuoni 是的昨天我加上这个配置 并单独抽离出来加载 可以使用了 感觉现有的文档还有有些简单 一些问题不太好查阅。
> 
> 顺便问下 我在 extraBabelPlugins: []中配置的 ES11相关语法的plugin 实际并没有起作用
> 
> ![image](https://user-images.githubusercontent.com/20588030/91970011-9c5da600-ed49-11ea-8b4e-3321046b8513.png)
> 
> 是否需要在类似上述的情况在memo运行环境时添加对应的options参数??
> 
> ```js
>     config.module
>     .rule('js')
>     .test(/\.(js|mjs|jsx|ts|tsx)$/)
>     .include.add(path.join(__dirname, '..', '..', 'src')).end()
>     .exclude.add(/node_modules/).end()
>     .use('babel-loader')
>     .options({
>         presets: [
>             ['@babel/preset-env', { targets: { browsers: ['safari >= 7', 'ie >= 9'] } }],
>             '@babel/preset-react',
>         ],
>         plugins: [
>             '@babel/plugin-proposal-optional-chaining',
>         ]
>     });
> ```
> 
> 原有项目中的一些组件使用了可选链语法在导入到md文件jsx渲染中报错。

已解决 之前的配置只解决了src目录下的loader问题 没有包含原有的整个项目的解析。

_Originally posted by @xjl271314 in https://github.com/umijs/dumi/issues/161#issuecomment-686235021_

**Comment by PeachScript** [comment]
实在没看明白说的是什么问题，如果是类似问题请在 #161 中准确描述；如果是新的问题请按照 issue 模板提供准确描述、复现步骤或复现仓库

这个 issue 先关闭了
