### ISSUE TITLE
Can't resolve 'xxxx', 引用本地项目报错

### ISSUE THREAD

**Issue by OctupleSakura** [umijs/dumi#323]
#### 错误描述
按照在umi项目以外的项目使用dumi配置后([戳这](https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F))，在md文件的jsx模块里面引用了当前项目，然后得到了如下的报错
已经尝试过删除缓存及lock文件后重新安装，均得到了同样的报错
#### 具体报错
![image](https://user-images.githubusercontent.com/26614477/93337483-c475fa80-f85b-11ea-963e-40a258ab0e71.png)

### Sample Code
![image](https://user-images.githubusercontent.com/26614477/93337610-eff8e500-f85b-11ea-8b8f-ca1ff550a1d2.png)

**Comment by PeachScript** [comment]
请提供复现 repo

**Comment by OctupleSakura** [comment]
@PeachScript 这里是复现repo，麻烦了
https://github.com/OctupleSakura/dumi-test-demo

**Comment by PeachScript** [comment]
`@weike/weike-ui` 是主项目的 package name 吗？dumi 是在 `APP_ROOT` 下寻找 `package.json` 做[自动 alias](https://d.umijs.org/zh-CN/guide/demo-principle#%E5%8E%9F%E5%88%99%E4%B8%80%EF%BC%9A%E8%83%BD%E7%9C%8B%E8%83%BD%E7%94%A8)，需要手动配置 alias 从 `@weike/weike-ui` 到 `src`

**Comment by PeachScript** [comment]
既然主项目自身是一个组件库，为什么需要用到 `APP_ROOT`？

**Comment by OctupleSakura** [comment]
可以了，脑子短路了hhh，昨天没有弄清楚自动alias的的规则，刚刚试了一下把`docs`和`umirc`移到根目录下面，移除了`APP_ROOT`的环境变量之后解决了，十分感谢！
