### ISSUE TITLE
页面内容`不足一屏`的时候，页面会有滚动条

### ISSUE THREAD

**Issue by qiaodaima** [umijs/dumi#324]
### Question

因为是 `100vh`，没有扣除顶部占据的高度，
所以在页面内容`不足一屏`的时候，页面是超过一屏幕的高度，
这样会产生滚动条，体验上不太友好。

https://github.com/umijs/dumi/blob/9e0a88fa46c58894af9d8ae0f579c2f8a84c78ae/packages/theme-default/src/style/layout.less#L16

### Sample Code
解决方案2种：
1. 添加属性：`box-sizing: border-box;`
2. 扣除顶部产生的高度

**Comment by PeachScript** [comment]
PR Welcome

**Comment by qiaodaima** [comment]
还不睡呀，老哥哥 ，哈哈

**Comment by zhaoyao91** [comment]
亲，我使用 dumi 1.0.35 新起的应用，怎么没有这个 feature 呢？

**Comment by PeachScript** [comment]
这是个已修复的 bug 不是 feature

**Comment by zhaoyao91** [comment]
安装 @next 之后解决了，多谢。
