### ISSUE TITLE
全局的CSS选择覆盖代码的问题

### ISSUE THREAD

**Issue by Tsutomu-miku** [umijs/dumi#330]
### Question
我这边开发了一个table的组件，css样式使用类选择器进行调整，然而dumi本身的全局属性，使用
```css
 .markdown table th {}
```
等选择器，会覆盖我的组件的样式。目前我写了两份样式代码保持组件库的样式一致性，比较痛苦，希望能够改进，比如组件展示不放在
```html
<div class='.markdown'>
```
下面的选项，或者直接使用类选择器。

**Comment by Tsutomu-miku** [comment]
用法有问题，<code>标签上不应有说明文字

**Comment by winterZhao** [comment]
碰到同样的问题了。能否详细说明一下解决方案。  标签上不应有说明文字。这个是什么意思。

**Comment by Tsutomu-miku** [comment]
> 碰到同样的问题了。能否详细说明一下解决方案。 标签上不应有说明文字。这个是什么意思。

他这个 markdown 文件的编译器有些问题，就是遇到 ``` 这种标签时，需要空一行再写。

**Comment by winterZhao** [comment]
好像没有解决问题。我是想在文档里实现左右布局的效果，所以我的.md里写了html标签 div + 行内样式，我发现一写了html标签就不行了。
