### ISSUE TITLE
bug: 使用svg图标，本地运行正常，打包提示svg图标虽然被引入了但无法打入包内。

### ISSUE THREAD

**Issue by blueju** [umijs/dumi#331]
![image](https://user-images.githubusercontent.com/49681036/93763556-4a22ed00-fc44-11ea-99bb-7d0e885f431a.png)

### Versions

- dumi: 1.0.10
- node: 12.18.3
- npm: 6.14.6
- OS: Windows
- Browser: Chrome 86

**Comment by PeachScript** [comment]
打包相关问题在 father 仓库讨论，参考：https://github.com/umijs/father/issues/164#issuecomment-574267556
