### ISSUE TITLE
sticky 手机模拟容器 + iframe 预览 demo

### ISSUE THREAD

**Issue by effortComeOn** [umijs/dumi#332]
### Question
怎么才能出现手机模拟容器，我按照文档上的要求，安装了对应版本的dumi@1.1.0-beta.18+ & dumi-theme-mobile，但是页面渲染并没有模拟器，是需要逼的什么配置吗？烦请解答，谢谢

**Comment by xiaohuoni** [comment]
不需要配置，页面上有写 demo 就行

**Comment by xiaohuoni** [comment]
出不来可能是使用了 hash 路由

**Comment by effortComeOn** [comment]
按照文档写了demo，run的时候，dumi-theme-mobile报错了 安装的版本
"dumi": "^1.1.0-beta.18",
"dumi-theme-mobile": "^1.0.0-beta.2",

![image](https://user-images.githubusercontent.com/32182458/93842332-15a54480-fcc9-11ea-9619-21722fd6100d.png)

是安装的版本不正确吗？还是我本地配置的原因？

**Comment by effortComeOn** [comment]
我升级到"dumi": "^1.1.0-beta.20"，可以正常展示了。谢谢了~
