### ISSUE TITLE
移动端组件研发

### ISSUE THREAD

**Issue by effortComeOn** [umijs/dumi#333]
### Question
移动端组件研发打包后，iframe里面的请求url为404
### Sample Code
![image](https://user-images.githubusercontent.com/32182458/93977013-6e99d900-fdac-11ea-8b50-236b8ed78ff4.png)

使用的默认模版，没有其他配置

**Comment by effortComeOn** [comment]
在配置文件中配置了
exportStatic: {
    dynamicRoot: true,
  },

iframe获取还是404

**Comment by xiaohuoni** [comment]
提供可复现的demo吧，这个功能都是正常的。

**Comment by effortComeOn** [comment]
我刚刚在钉钉群里面问了一哈，说可能和我们公司的发布系统有关吧，我后续再试试，有问题在钉钉群沟通吧，谢谢

**Comment by xiaohuoni** [comment]
好的

**Comment by effortComeOn** [comment]
这个问题解决了，在对应的node项目里面需要配置 window.routerBase为对应的项目路由就可以了，谢谢~

**Comment by effortComeOn** [comment]
在node项目的模版文件里设置 routerBase 为对应的根目录，如果有base，和base设置的值保持一致即可
<script>
      window.routerBase = "/"
    </script>

我这边遇到的问题是，我们的发布系统会把所有的文件都放在根目录下面，看起来应该就是路由的问题，，查看了打包后的html文件，有设置routerBase，就对应的更改到自己的那个文件存在的目录，路由就匹配ok了
