### ISSUE TITLE
dumi 如何在现有项目使用？

### ISSUE THREAD

**Issue by PiccoloYu** [umijs/dumi#334]
我想用dumi来做自己博客，但是dumi的样式都是固定的。想用umi来写博客，但是文档文章用dumi 来展示。 
我看了其他 Issues dumi 并没有考虑和umi 融合使用的情况。我更希望dumi 能在大多数项目中引入，然后直接使用。
不知道有没有这方面已经实现的Dome或者教程呢？

**Comment by PeachScript** [comment]
> 想用umi来写博客，但是文档文章用dumi 来展示。

这个是要实现什么效果。
