### ISSUE TITLE
是否约定了组件源码只能放在根目录src下呢

### ISSUE THREAD

**Issue by Z1hgq** [umijs/dumi#336]
### Question
是否约定了组件源码只能放在根目录src下呢
### Sample Code
将组件代码放在src目录下dumi dev正常运行
![image](https://user-images.githubusercontent.com/26574371/94362335-26045780-00ed-11eb-8a1c-8c7fd3a50df3.png)
但是将组件代码放在根目录components目录下dumi dev会报找不到包的错误
![image](https://user-images.githubusercontent.com/26574371/94362379-5f3cc780-00ed-11eb-99ac-2f153909de0f.png)
package.json配置和.umirc.js配置单为
![image](https://user-images.githubusercontent.com/26574371/94362403-9d39eb80-00ed-11eb-8b41-cdcf1a548684.png)
![image](https://user-images.githubusercontent.com/26574371/94362406-a75bea00-00ed-11eb-8f42-48fbed5c5574.png)

**Comment by Z1hgq** [comment]
"dumi": "^1.0.6"

**Comment by PeachScript** [comment]
是的，father-build 只会处理 src 下的源代码，如果改了目录会导致组件库无法打包

**Comment by Z1hgq** [comment]
> 是的，father-build 只会处理 src 下的源代码，如果改了目录会导致组件库无法打包

能否开放此源码路径配置呢，我觉得这个需求很合理

**Comment by xiaohuoni** [comment]
> 是的，father-build 只会处理 src 下的源代码，如果改了目录会导致组件库无法打包

那include的配置作用就模糊了？

**Comment by PeachScript** [comment]
@xiaohuoni include 是文档 md 的识别目录，和组件库源码不一样

**Comment by Z1hgq** [comment]
> @xiaohuoni include 是文档 md 的识别目录，和组件库源码不一样

@PeachScript 应该为组件库源码做一个配置

**Comment by PeachScript** [comment]
> > 是的，father-build 只会处理 src 下的源代码，如果改了目录会导致组件库无法打包
> 
> 能否开放此源码路径配置呢，我觉得这个需求很合理

目前没有计划，还有很多功能没做，相比之下自定义目录结构的优先级就变低了；如果你的工作中有很强的自定义需求，欢迎参与到 father 项目中一起共建

**Comment by Z1hgq** [comment]
> 目前没有计划，还有很多功能没做，相比之下自定义目录结构的优先级就变低了；如果你的工作中有很强的自定义需求，欢迎参与到 father 项目中一起共建

@PeachScript OK，多谢

**Comment by Z1hgq** [comment]
not support yet
