### ISSUE TITLE
如何开启和使用dva

### ISSUE THREAD

**Issue by likepearl** [umijs/dumi#337]
dumi中怎么使用dva
我在src目录下引用
import {getDvaApp} from 'umi'
获取不到getDvaApp 方法

报错信息"export 'getDvaApp' was not found in 'umi'

**Comment by PeachScript** [comment]
umi 插件要装到 devDependencies 里：https://umijs.org/zh-CN/plugins/plugin-dva
不过，组件库不应该依赖 dva

**Comment by likepearl** [comment]
> umi 插件要装到 devDependencies 里：https://umijs.org/zh-CN/plugins/plugin-dva
> 不过，组件库不应该依赖 dva

可以用dva了，谢谢。我们项目需求比较特殊 (#^.^#)
