### ISSUE TITLE
bug: loop函数会产生无限循环

### ISSUE THREAD

**Issue by yehuozhili** [umijs/dumi#338]
### Versions

- dumi:1.0.34
- node:12.12
- npm:6.13
- OS:win10
- Browser:chrome

### Steps to reproduce

位置应该在这：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/utils/watcher.ts#L25

如果一个a.md引用了aa.tsx  aa.tsx 引用了 bb.tsx的一个函数，bb.tsx中引入了aa.tsx中另一个函数 ，b.md中引入了bb.tsx ，此时不会有什么问题，然后新建c.md，c.md引入bb.tsx，引入b.md初次启动无问题，只要在c.md上进行修改，则出现loop无限循环，需要人为修改，将a.md中引入的aa.tsx移入bb.tsx中，aa.tsx中无引入bb.tsx内容，才可以避免

**Comment by PeachScript** [comment]
这部分的用例确实没覆盖到所有边界，有时间来个 PR？

**Comment by PeachScript** [comment]
v1.1.0-beta.25 已修复
