### ISSUE TITLE
Hope to write demo code in x.js or x.ts file, not x.md

### ISSUE THREAD

**Issue by 951565664** [umijs/dumi#341]
### Description
Currently writing ts or js code in md, there is no way to automatically check, and there is no way to use snipshots
### Solution

The demo code is under demo/demo.tsx. The code of demo.tsx is displayed in demo.md. The code of demo.tsx for running the webpage

such as

```md
//demo.md

##demo

``import './demo.tsx'``

```
```ts
//demo.tsx'

export default ()=>{
   return 'this is demo'
}

```

**Comment by PeachScript** [comment]
You can already do this with the external demo way: https://d.umijs.org/guide/demo-types#external-import
