### ISSUE TITLE
如何修改.md文件的嗅探目录？resolve.includes无效

### ISSUE THREAD

**Issue by vortesnail** [umijs/dumi#342]
### 问题描述
我在非`umi`项目中使用`dumi`，根据[官方FAQ](https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F)完全相同的操作，的确能成功显示文档，但是有一个问题，在`dumi`目录下会生成无限嵌套的`node_modules` 文件，这是什么原理？
![image](https://user-images.githubusercontent.com/18679842/95644116-cc395f80-0ae6-11eb-9953-f9e880f4e854.png)

根据官方的介绍，我可通过修改 `APP_ROOT` 改变目录，于是我想在项目根目录下新建一个`docs`文件目录，里面存放我所有的`.md` 文件，比如下图：
![image](https://user-images.githubusercontent.com/18679842/95644126-e6733d80-0ae6-11eb-9533-0ce66afebb99.png)

接着我修改了`package.json` 中的命令为：
```bash
"dumi": "cross-env APP_ROOT=./ dumi dev",
"dumi-build": "cross-env APP_ROOT=./ dumi build",
```

但是会出现以下报错：
![image](https://user-images.githubusercontent.com/18679842/95644157-39e58b80-0ae7-11eb-89a5-698443dc5457.png)

看起来是读了`src`目录，于是我尝试修改`.umirc.js` 配置如下：
```js
export default {
  chainWebpack(memo) {
    memo.plugins.delete('copy')
  },
  resolve: {
    includes: ['docs']
  },
}
```
最终报错也是一致！
我到底该怎么做才能自定义嗅探目录呢？
麻烦官方回答下，感激不尽～折腾太久了

**Comment by vortesnail** [comment]
发现了问题所在，src 下不能有名字为 app.{tsx | js} 的文件。。

**Comment by vortesnail** [comment]
> 是的，`src/app.ts` 是 umi 运行时插件的约定；如果这个路径不能规避的话，只能通过 APP_ROOT=docs 来切换文档应用的启动路径了

建议将这个写进 FAQ 或 约定式路由规则 中说明下，不然会不小心困惑到一些开发者。

**Comment by PeachScript** [comment]
FAQ 已增加：https://d.umijs.org/guide/faq#use-dumi-in-non-umi-project-then-got-error-register-failed-invalid-key-xx-from-plugin-srcappts
