### ISSUE TITLE
bug: 使用dumi二次封装antd时Button组件报错

### ISSUE THREAD

**Issue by jiachaosun** [umijs/dumi#345]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/jiachaosun/dumi-antd](https://gitee.com/jiachaosun/dumi-antd)

### Steps to reproduce
- build出dist
- 本地建了一个cra
- yarn link dumi组件库
- cra 使用上述link过的组件库（本地调试）
- cra中App.js，import { Button } from 'my-antd'

### What is expected?
Button组件正常渲染

### What is actually happening?
定位到antd中 InternalButton

node_modules/antd/es/button/button.js:124

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome 85 |

<img width="997" alt="图片" src="https://user-images.githubusercontent.com/859382/95764297-d88a0c00-0ce2-11eb-839e-dc26bb5337b5.png">

**Comment by PeachScript** [comment]
怀疑是应用安装的 React 版本和 link 过去的组件库安装的 React 版本不一致导致的，可以检查下看

**Comment by xrkffgg** [comment]
https://ant-design-colorful.github.io/ant-design-colorful/

我这用了 antd 的 Button ，你可以来参考下

**Comment by Arvin-zhu** [comment]
yarn link dumi组件库
yarn link react
yarn link react-dom

**Comment by JoeWrights** [comment]
@jiachaosun 请问问题解决了吗，同样遇到这种问题，用umi脚手架搭的项目里使用没这个问题，但是自行用webpack搭的react项目使用就有这个问题

**Comment by NancysMom** [comment]
@jiachaosun 请问问题解决了吗？我也是使用dumi封装了个antd的button 报同样的错
