### ISSUE TITLE
bug: 当设置 base 和 publicPath 后，favicon 路径问题

### ISSUE THREAD

**Issue by xrkffgg** [umijs/dumi#347]
### Versions

- dumi: 1.0.10
- node: 13

### Steps to reproduce

- 当图片路径设置本地 public 地址后，例如 实际路径为/public/images/icon.png，config  设置 `/images/icon.png`
- 同时设置了 base 和 publicPath
- 打包后，index.html 中的 umi.js 和 umi.css 加上了 publicPath 路径，但 link 的 icon 并没有加，还是 /images/icon.png
- 这样导致获取 icon 出错
- 不得不使用网络地址

### What is Expected?

- 打包后 link icon 的地址 加上 publicPath

### What is actually happening?

- 打包后 link icon 的地址 没加上 publicPath

**Comment by PeachScript** [comment]
favicon 是在 config 中配置的，需自行处理 `publicPath`
