### ISSUE TITLE
[Question] 打包 umi.js 怎么加随机戳 & 单页面页脚如何配置

### ISSUE THREAD

**Issue by xrkffgg** [umijs/dumi#348]
###  打包问题

1. 打包后的 umi.js 和 umi.css 如何加随机戳，我打包后直接是 umi.js 和 umi.css，但我看官网打包后有一个随机戳。

### 页脚配置

![image](https://user-images.githubusercontent.com/29775873/96202774-a8689480-0f92-11eb-9d91-90ee34d10ccd.png)

1. GitHub 编辑，这个要怎么显示出来呢？

2. 我默认显示的是英文，怎么设置成中文呢？文档中没找到

**Comment by PeachScript** [comment]
`config.hash: true` 开启哈希戳；配置 package.json 中的 repository 字段自动展示编辑地址；这两处可以看下 dumi 仓库的配置。

升级到 beta 版页脚会自动展示为中文，正式版目前默认英文。

**Comment by xrkffgg** [comment]
我设了 repository 后，默认编辑是 master 分支，但现在我用的是 main 分支的。
repository 的 url 加上 #main 也不好使
@PeachScript

**Comment by PeachScript** [comment]
@xrkffgg #214
