### ISSUE TITLE
umi项目中、结合dumi生成业务文档说明

### ISSUE THREAD

**Issue by zhouzyc** [umijs/dumi#349]
### Question
请问下我想实现一种场景。
1.公司项目组件非常的多、组件复杂度很高、对于新人来说上手难、并且也没有一个直观的demo来快速学习。
2.想利用dumi文档功能、为每一个umi项目中的组件生产对应文档说明。
3.当然如果能对每个业务页面也有一个说明就更好了

**Comment by PeachScript** [comment]
之后会有专门的模式支持这种场景，当前可参考临时解法、在项目子文件夹中单独维护一套文档来实现：https://github.com/umijs/dumi/issues/161#issuecomment-640098689

**Comment by PeachScript** [comment]
Umi 项目集成模式已发布，v1.1.0-beta.29 可用，欢迎尝试 https://d.umijs.org/lab#umi-inregrated-mode
