### ISSUE TITLE
bug: beta.25报cannot resolve module的错误

### ISSUE THREAD

**Issue by zhangyu1818** [umijs/dumi#351]
### Versions

- dumi: 1.1.0-beta.25
- node: 12.18.1
- npm: 6.14.5
- OS: macos 10.15.7
- Browser:

### Steps to reproduce
https://github.com/zhangyu1818/piatto
### What is actually happening?

在demo的markdown文件里引入组件报错

`Can't resolve 'piatto/button' in '/Users/zhangyu/Desktop/piatto/docs/button'`

注释掉umirc里的一段配置就好了，但是在beta.24是能正常使用的
```
  extraBabelPlugins: [
    [
      'import',
      {
        libraryName: 'piatto',
        libraryDirectory: '',
        customStyleName: name => path.resolve(__dirname, `src/${name}/index.less`),
      },
    ],
  ],
```

**Comment by PeachScript** [comment]
`libraryDirectory` 需要配置成 `src`，之前不配置也能工作是因为手动配置包名的 alias 会引发依赖查找的 bug、但同时也使得上面的 case 能『工作』，beta.25 正好修复了该问题：https://github.com/umijs/dumi/commit/22fe5aa6710079ba0d241ace942062d3760c4e4a#diff-3b674eb8d73e36235b46cb85e4854cfef77b403c7f50db255c7ce5b328c7b822R25

**Comment by zhangyu1818** [comment]
还需要手动配置alias吗，不配置alias，把libraryDirectory改为了src出现了新的错误
```
These dependencies were not found:

* piatto/src/input in ./docs/demo/space/default.tsx
* piatto/src/space in ./docs/demo/space/default.tsx
```

如果我配置了alias没有报错了，但是出来的页面里所有组件的demo文件都变成了同一个
```
 alias: {
   piatto: __dirname,
 }
```

**Comment by PeachScript** [comment]
@zhangyu1818 确认是 dumi 的 bug，上一个版本没考虑到 babel-plugin-import 的情况，搜集依赖阶段和文档构建阶段的 alias 行为不一致了，v1.1.0-beta.26 已修复可以试下，保持 `libraryDirectory` 为空即可

**Comment by zhangyu1818** [comment]
好了，已解决😄
