### ISSUE TITLE
feat: 支持自定义文档编辑链接

### ISSUE THREAD

**Issue by lin-123** [umijs/dumi#353]
### Versions

- dumi: 1.0.34
- node: 11.15.0
- npm: 6.7.0
- OS: macos
- Browser: chrome

### Steps to reproduce
1. package.json 中配置内网搭建的 gitlab 地址， 域名没有gitlab 关键字，导致没有通过 dumi 里面的规则校验；
```tsx
// dumi/package/theme-default/src/layout.tsx  60 行
// 这里约定 repoUrl 必须包含 github|gitlab 关键字
const repoPlatform = { github: 'GitHub', gitlab: 'GitLab' }[
    (repoUrl || '').match(/(github|gitlab)/)?.[1] || 'nothing'
  ];
```

### What is Expected?
1. 建议兼容内网搭建的 gitlab 地址，不对 repo 地址做约束， 由使用者指定即可

```tsx
      // dumi/package/theme-default/src/layout.tsx 96行 建议改成如下描述
       {repoUrl && (
              <Link to={`${repoUrl}/edit/${branch}/${meta.filePath}`}>
                {isCN ? `在线编辑这篇文档` : `Edit this doc online`}
              </Link>
            )}
```

### What is actually happening?
页脚编辑当前页面的超链接消失了

**Comment by PeachScript** [comment]
域名是目前判断 Git 平台类型的唯一依据，直接放开会导致使用其他托管平台的项目出现异常；

目前建议私有化部署也携带 gitlab 或者使用 beta 版的自定义主题控制编辑链接的渲染；后续版本会考虑开放配置、由用户自行渲染编辑链接。

**Comment by PeachScript** [comment]
已支持通过 `package.json` 中的 `repository.platform` 手动指定 Git 平台类型，详见 #461
