### ISSUE TITLE
bug: 在monorepo中使用生成的路由有问题

### ISSUE THREAD

**Issue by otakustay** [umijs/dumi#355]
### Versions

- dumi: `1.0.34` & `umi@3.2.24`
- node: `v14.14.0`
- npm: `6.14.8`
- OS: macOS Catalina
- Browser: Chrome 86.0.4240.111

### Steps to reproduce

我的目标是把一个monorepo下所有包的README整合在一起形成一份完整的文档

1. 有一个monorepo
2. 有2个包，分别是`packages/foo`和`packages/bar`
3. 2个包下面分别有一个`README.md`，内容不同
4. 在`.dumirc.js`中`resolve.alias: ['packages/foo', 'packages/bar']` <== 不确定为什么，不这么写dumi自己是找不到这些包的
5. `dumi dev`

复现用仓库：https://github.com/otakustay/issues/tree/monorepo-nav-issue （`monorepo-nav-issue`分支）

### What is Expected?

会在导航中生成`foo`和`bar`两个导航，点击后分别看各自的文档

### What is actually happening?

只有一个叫`bar`的导航（数组里顺序最后的），但内容是`foo`的（数组里顺序最前的）

![image](https://user-images.githubusercontent.com/639549/97164975-e8631f00-17bd-11eb-98fd-9974940b3349.png)

看起来，`findChildRoutes`这个函数在生成路由的时候，是不考虑monorepo的层级结构的，所以全部包的路由都成了`/`，相互覆盖了，不确定是by design的还是我的配置有问题

**Comment by PeachScript** [comment]
dumi 只有 `resolve.includes` 的配置项。

路由解析是从 includes 值开始的，所以 `README.md` 会相互覆盖 `/` 路由，想分开站点体现在导航上，把 `resolve.includes` 配置成 `packages` 即可。

**Comment by otakustay** [comment]
非常感谢。配置成`packages`可以使用，不过因为没有`excludes`可能需要调整包的结构让一部分包可以离开dumi的管理

**Comment by PeachScript** [comment]
好的，后续版本增加 exclude 的配置项以满足这种场景
