### ISSUE TITLE
执行yarn watch不会自动结束

### ISSUE THREAD

**Issue by FrontEndZhang** [umijs/dumi#356]
版本
v1.1.0-beta.26

执行yarn watch，会一直卡死在这里
theme-mobile: Start watching D:/VScode_project/seeyon/template-dumi/packages/theme-mobile/src directory...

**Comment by PeachScript** [comment]
watch 是用来监听 src 下的文件变更、实时 build 到 lib 的，『不会自动结束』是期望结果，<kbd>Ctrl</kbd> + <kbd>C</kbd> 手动结束即可
