### ISSUE TITLE
lerna 和 dumi 组合使用时，packages 下的包互相引用时的路径解析问题

### ISSUE THREAD

**Issue by xiaoYuanDun** [umijs/dumi#357]
### Question
dumi version: 1.0.34
当前工程是 dumi 和 lerna 组合的，结构如下：
packages
├── hook
├── ui-components
├── pro-components
├── icon-font
一共管理了4个库，但是遇到一个问题，就是在 pro-component 中 引用 ui-component 的 es 文件夹下的组件时，路径解析会报错，如下图：
![image](https://user-images.githubusercontent.com/22720420/97379387-aa6e1400-18ff-11eb-8b5f-76416d7e84cd.png)
![image](https://user-images.githubusercontent.com/22720420/97379439-c5408880-18ff-11eb-8f03-0bd8cf26d250.png)
dumi dev 时，会把 ui-components/es/time-picker 解析为一个单独的包，而不是从 ui-components 下寻找文件，我有试过配置 package.json 的 module，设置 webpack 的 resolve.alias 都不管用，所以想请教下，有人遇到这种问题吗
补充：在使用其他第三方库，如antd，会正确解析路径，如
![image](https://user-images.githubusercontent.com/22720420/97379627-2b2d1000-1900-11eb-8ef3-eaffb15c9220.png)
只有当前 lerna 下的包互相引用时会存在这种问题

**Comment by xiaoYuanDun** [comment]
补充一点，build 之后的产物可以正常使用，上面说的这种引用方式也可以正常识别，只有 dumi dev 的时候会有这个问题

**Comment by xiaoYuanDun** [comment]
找到问题了，模板文件里没有配置 es 文件夹对应的 alias 导致的

**Comment by netty0911** [comment]
> 找到问题了，模板文件里没有配置 es 文件夹对应的 alias 导致的

老大你是怎么解决的，我搞了半天也没弄明白
