### ISSUE TITLE
bug: 路径以n开头时，不能正确导入

### ISSUE THREAD

**Issue by Iixianjie** [umijs/dumi#361]
### Versions

- dumi: 1.0.34
- node: 12.18.1
- npm:
- OS: 
- Browser:

### Steps to reproduce
见下图:
![image](https://user-images.githubusercontent.com/34636376/97794609-38673900-1c37-11eb-9d79-3eb365db36f1.png)

错误如下：
```
This dependency was not found:

* ..\..\docs\utilso-ssr\demo.tsx in ./src/.umi/core/routes.ts

To install it, you can run: npm install --save ..\..\docs\utilso-ssr\demo.tsx
```

**Comment by xiaohuoni** [comment]
@PeachScript  印象中我修过这个问题，是因为` \n `被识别成换行符号？

**Comment by PeachScript** [comment]
是这个问题，1.0 的 demo 单独路由没处理，确实还存在这个 bug；但 1.1 中避开了， @Iixianjie  请使用 dumi 的 beta 版本

关联 issue: #315

**Comment by PeachScript** [comment]
[v1.0.35](https://github.com/umijs/dumi/releases/tag/dumi%401.0.35) 正式版也已修复
