### ISSUE TITLE
bug: sync bugfix to stable version from beta

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#362]
有些 bug 修复仅在 beta 版本做了，导致正式版还存在很多问题，很不合理，需要将这些修复都同步回正式版。

### bug 列表
- https://github.com/umijs/dumi/issues/273
- https://github.com/umijs/dumi/issues/294
- https://github.com/umijs/dumi/issues/301
- https://github.com/umijs/dumi/issues/316
- https://github.com/umijs/dumi/issues/361
- https://github.com/umijs/dumi/issues/338

**Comment by poyiding** [comment]
感谢及时答复解决，review了一下，目前暂时就这些，后续fix bug和feature 应分开发布。

**Comment by poyiding** [comment]
感谢及时答复解决，review了一下，目前暂时就这些。

**Comment by PeachScript** [comment]
同步 bugfix 过程中发现的问题：
1. #273 和 #301 应该是同一个问题
2. #273 中提到的 gh-pages 部署 + demo 单独打开刷新的问题，由于功能设计问题 1.0 不好修复，可通过 `_config.yaml` 配置 gh-pages 行为来规避：https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site

除此之外，其他问题已在 [v1.0.35](https://github.com/umijs/dumi/releases/tag/dumi%401.0.35) 中修复，后续 dumi 会避免出现『正式版不修复但 beta 版修复』的情况，感谢指正 ❤
