### ISSUE TITLE
Cannot find module 'umi/bin/umi'

### ISSUE THREAD

**Issue by paradox010** [umijs/dumi#364]
### Question

不是稳定的bug：
线上构建的时候，执行完npm install再打包的石化，会提示Cannot find module 'umi/bin/umi'。
这个bug很难稳定复现出来，开发环境的时候偶尔也会出现，

### Sample Code
我的依赖项
"dependencies": {
    "dumi": "1.1.0-beta.30",
    "rc-image": "^4.1.0",
    "react": "^16.12.0"
  },
  "devDependencies": {
    "@ant-design/tools": "^10.0.1",
    "@types/enzyme": "^3.10.5",
    "@types/classnames": "^2.2.10",
    "@umijs/preset-react": "1.x",
    "@umijs/test": "^3.0.5",
    "father-build": "^1.17.2",
    "gh-pages": "^3.0.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-to-json": "^3.3.5",
    "xhr-mock": "^2.4.1",
    "xhr2": "^0.2.0",
    "mockdate": "^3.0.0",
    "cz-conventional-changelog": "^3.3.0",
    "rc-queue-anim": "^1.4.0",
    "rc-scroll-anim": "^2.0.2",
    "rc-texty": "^0.2.0",
    "rc-tween-one": "^2.6.5"
  },

**Comment by PeachScript** [comment]
没有复现 repo 也没有复现步骤，这怎么玩…

**Comment by PeachScript** [comment]
另外 dumi 不要写死版本号以及应该写进 `devDependencies`

**Comment by paradox010** [comment]
> 另外 dumi 不要写死版本号以及应该写进 `devDependencies`

因为之前eslint有个版本bug，只有在dumi的beta版中解决了，所以我固定了dumi的版本号

**Comment by paradox010** [comment]
啊我好像找到问题了，对比两次的构建日志
+ npm -v
6.14.6
+ node -v
v12.18.3
+ npm install

> yorkie@2.0.0 uninstall /var/lib/jenkins/workspace/front_lzdesign_fix_web/node_modules/yorkie
> node bin/uninstall.js

husky
uninstalling Git hooks
done

我搜索了一下 husky的老issue中有提到这个问题 https://github.com/typicode/husky/issues/426
但是回复也只说在新版本解决了这个问题。所以我把yorkie换成了husky^4.0.3。这样线上通过webhook触发构建是ok的。(之前线上手动触发构建是可行的，可以触发yorkie的install.js)

**Comment by PeachScript** [comment]
> 因为之前eslint有个版本bug，只有在dumi的beta版中解决了，所以我固定了dumi的版本号

可以用 `next` tag，beta 版发版会很频繁，锁死版本会导致 bugfix 无法及时获取到

**Comment by paradox010** [comment]
> > 因为之前eslint有个版本bug，只有在dumi的beta版中解决了，所以我固定了dumi的版本号
> 
> 可以用 `next` tag，beta 版发版会很频繁，锁死版本会导致 bugfix 无法及时获取到

了解了谢谢！我之前的回答是错的，是node的版本导致了我这个问题。我已经修正了，希望后面有同样问题的人可以参考～
