### ISSUE TITLE
Question: i18n title

### ISSUE THREAD

**Issue by zhaoyao91** [umijs/dumi#367]
### Question

The title field in config is only a string, how to support i18n?

**Comment by PeachScript** [comment]
`config.title` 一般是组件库的名称，暂时没有支持国际化的计划

**Comment by zhaoyao91** [comment]
这很受限啊

**Comment by PeachScript** [comment]
受限具体指？首页不应该展示组件库名称吗

**Comment by zhaoyao91** [comment]
@PeachScript 就是说，组件库的**展示名称**，没有说一定全是英文的，比如 antd prop，中文展示名称未尝不可能是『antd 豪华版』
