### ISSUE TITLE
bug: 修改组件源码时 API 表格不热更新

### ISSUE THREAD

**Issue by effortComeOn** [umijs/dumi#370]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
dumi API 编辑注释之后保存页面API不更新，必须要重启，才会更新API，不知道和自定义主题有没有关系。

### What is Expected?
dumi API 编辑注释之后保存页面API可实时更新

### What is actually happening?
dumi API 编辑注释之后保存页面API不更新

**Comment by effortComeOn** [comment]
一版情况下，含有interface的都会默认生成API，继承某个接口生成的时候，有时候希望只生成自己新增的api，有时候希望所有的api都展示，能不能加个参数什么的，实现可配置的。

**Comment by PeachScript** [comment]
@effortComeOn 复现仓库能提供吗

**Comment by PeachScript** [comment]
确认下是不是直接用的 `<API></API>`，并未指定 `src`

**Comment by effortComeOn** [comment]
是的，没有指定 src

**Comment by PeachScript** [comment]
[v1.1.0-rc.2](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-rc.2) 已修复

**Comment by yangjinjun3** [comment]
dumi版本1.1.32；为<API>指定了src，源码中添加props，表格不更新

**Comment by yangjinjun3** [comment]
dumi版本1.1.32；未指定了src，源码中添加props，表格不更新

**Comment by yangjinjun3** [comment]
dumi版本1.1.32；为<API>指定了src，源码中添加props，表格不更新
