### ISSUE TITLE
feat: 通过 <code /> 标签向引用的 react 组件传递参数

### ISSUE THREAD

**Issue by zhaoyao91** [umijs/dumi#371]
### Description

这样我们就可以制作适用于多语言的组件，在不同的文档中进行复用

**Comment by PeachScript** [comment]
这违背了『开发者应该像用户一样写 demo』的原则，传递的 props 对用户来说是黑盒，如果组件库和 antd 一样走 `ConfigProvider` 提供国际化，那开发者也应该使用 `ConfigProvider` 来编写文档
