### ISSUE TITLE
feat: doc 模式支持搜索

### ISSUE THREAD

**Issue by CaanDoll** [umijs/dumi#373]
### Question
内容还是比较多，确实很需要搜索栏，但是又没必要切到site模式。且无意中也发现了doc模式的手机访问是有搜索栏的。希望能通过配置开启

**Comment by PeachScript** [comment]
目前不支持，移动端模式下有其实应该是 bug…后续版本支持掉

**Comment by zhaoyao91** [comment]
![image](https://user-images.githubusercontent.com/3808838/98711778-64fe1c00-23c0-11eb-870b-6484617ac0b3.png)
site 模式移动端的搜索栏的图标不居中，这个是 bug 吗？还是故意这样设计？

**Comment by PeachScript** [comment]
是兼容性 bug，[v1.1.0-rc.0](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-rc.0) 已修复

**Comment by CaanDoll** [comment]
希望能在doc模式下支持搜索。如果左侧菜单能支持三级就好了，现在就是gitbook想迁移过来发现有很多不同的地方

**Comment by PeachScript** [comment]
dumi v1 不再更新，欢迎升级到 v2（注：v2 没有 doc 模式了），issue 关闭
