### ISSUE TITLE
bug: ftp 等超链接被识别为站内链接，无法正常跳转

### ISSUE THREAD

**Issue by leotian** [umijs/dumi#375]
### Question
类似下面写的，如果我配置了base，这种（非http链接）都会给我加上base，导致跳转错误

### Sample Code
md：[ftp] (ftp://0.0.0.123/)
页面：/base/ftp://0.0.0.123/

**Comment by PeachScript** [comment]
是个 bug，感谢反馈

**Comment by PeachScript** [comment]
[v1.0.36](https://github.com/umijs/dumi/releases/tag/dumi%401.0.36) 及 [v1.1.0-rc.2](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-rc.2) 已修复
