### ISSUE TITLE
bug: locales 配置有只有一项 zh-CN 时展示的却是英文的

### ISSUE THREAD

**Issue by zhaoyao91** [umijs/dumi#379]
### Versions

- dumi: ^1.1.0-rc.0
- node: v14.15.0
- npm: 6.14.8
- OS: macOS 10.15.7
- Browser: chrom 86.0.4240.183

### Steps to reproduce

- 创建 `index.zh-CN.md` 和 `index.en-US.md` 两个文档，分别写中文和英文的内容
- `.umirc.ts` 中 的 `locales` 配置设置为 `[['zh-CN', '中文']]`

### What is Expected?

- 导航上没有语言切换按钮
- 文档是中文版的

### What is actually happening?

- 文档是英文版的

**Comment by ExcitingFrog** [comment]
我也遇到过这个问题 蛮怪的  
首先是如果config/config.js有了 就尽量不要在.umirc.ts里配置  可能会冲突
中文变成首选项后  中文内容好像就等于index.md了 当然加上后缀也行   建议所有markdown文件都加上后缀
还有就是config里的/zh-CN/guide  也得改成/guide
![heli](https://i.loli.net/2020/12/12/SQHClw1FvY7tWTn.jpg)

**Comment by cat-walk** [comment]
遇到了同样的问题

**Comment by GpingFeng** [comment]
同样，将所有的英文文档都删了，并且 .umirc.ts 中 的 locales 配置设置为 [['zh-CN', '中文']]

**Comment by changlin0501** [comment]
> 我也遇到过这个问题 蛮怪的 首先是如果config/config.js有了 就尽量不要在.umirc.ts里配置 可能会冲突 中文变成首选项后 中文内容好像就等于index.md了 当然加上后缀也行 建议所有markdown文件都加上后缀 还有就是config里的/zh-CN/guide 也得改成/guide ![heli](https://camo.githubusercontent.com/f3f7628b695241f0587392dc7cec429a8de3fcce48b7c29bd57f13e93ad7256b/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f31322f535148436c7731467659377457546e2e6a7067)

请问后面问题解决没，我也遇到相同问题

**Comment by PeachScript** [comment]
dumi v2 已发布，locales 逻辑更加符合直觉，路由识别及多语言切换按钮始终以 `locales` 配置为准，欢迎升级：https://d.umijs.org/guide/upgrading

dumi v1 不再更新，issue 关闭
