### ISSUE TITLE
question: how to speed up debugging

### ISSUE THREAD

**Issue by RexYuan1114** [umijs/dumi#380]
### how to speed up debugging
when I try `npm run doc`, it always take more than 5 minutes time, are there any configure option could speed up this command?

**Comment by PeachScript** [comment]
I cannot reproduce it in dumi repo, please provide a reproduce repo

**Comment by vortesnail** [comment]
I have this problem too, here is my issue [382](https://github.com/umijs/dumi/issues/382)

**Comment by PeachScript** [comment]
Duplicate with #382 , closed
