### ISSUE TITLE
本地服务启动极其慢，能到5分钟以上，是什么原因呢？

### ISSUE THREAD

**Issue by vortesnail** [umijs/dumi#382]
### Question
dumi 的开发者你们好，我这里将 dumi 作为我们项目的文档工具，在进行一系列自定义配置后，此文档工具也能正常使用。

但是在使用过程中我出现了一个难以忍受的问题，就是我每次启动文档（也就是 npm run dumi），启动起来会极其地慢，每次都是在 4～5 分钟以。。

我不知道问题是出在了哪里，个人怀疑是 dumi 的缓存文件没有用，也就是 `.umi`  这个目录没用到，我该怎么去改良呢？

非常希望能有开发者能解决我的疑惑，吾将万分感谢！

### Sample Code

这是我的 npm 命令（我改变了运行时目录）：
```
  "doc": "cross-env APP_ROOT=./ dumi dev",
```

这是我的配置文件：
```js
const path = require('path')

export default {
  mode: 'site',
  title: 'xxx',
  resolve: {
    includes: ['docs']
  },
  alias: {
    '@': path.resolve(__dirname, './src'),
    '@Comp': path.resolve(__dirname, './src/components'),
    "Utils": path.resolve(__dirname, './src/utils'),
  },
  outputPath: 'doc-build',
  theme: {
    '@c-primary': '#4a90e2',
  },
  menus: {
    //...
  },
  navs: {
    //...
  },
  chainWebpack(memo) {
    memo.plugins.delete('copy')
  },
  links: [{
    rel: 'stylesheet',
    href: 'https://cdn.bootcss.com/antd/4.7.0/antd.min.css'
  }],
  sass: {
    implementation: require('node-sass'),
  },
}

```

这是更改运行时目录之后的`.umi`缓存目录：
![image](https://user-images.githubusercontent.com/18679842/99328327-cb9aa280-28b6-11eb-8126-9b693c04b00c.png)

**Comment by PeachScript** [comment]
dumi 的版本信息请提供下，另外尝试关闭 `nodeModulesTransform` 试试：https://umijs.org/config#nodemodulestransform-31

**Comment by vortesnail** [comment]
> dumi 的版本信息请提供下，另外尝试关闭 `nodeModulesTransform` 试试：https://umijs.org/config#nodemodulestransform-31

我的 dumi 版本信息是：
`"dumi": "^1.0.26",`

谢谢朋友解答

**Comment by vortesnail** [comment]
是不是在每次正式启动前都去读根目录的 node_modules 了呢？ 我升级到了 1.0.36 情况一致

**Comment by vortesnail** [comment]
经过版本升级，配置修改后，情况一致：
```js
nodeModulesTransform: {
  type: 'none'
},
```
版本：
```
"dumi": "^1.0.36",
```

**Comment by PeachScript** [comment]
有点难定位，最好能有可复现仓库

**Comment by vortesnail** [comment]
> 有点难定位，最好能有可复现仓库

好，我再重新起个项目看看能不能复现，先别关哈。

**Comment by vortesnail** [comment]
想问一下，在这个阶段 umi 到底是在做什么工作啊？完全没有任何log也不知道在干嘛，会一直在这里卡七八分钟，然后才开始 webpack 读条。
![image](https://user-images.githubusercontent.com/18679842/99374174-45ee1580-28fd-11eb-9f56-9d287d7d79de.png)

**Comment by PeachScript** [comment]
在 webpack 启动之前，dumi 有两个耗时点：
1. 约定式路由读取（遍历目录耗时）
2. md 文件预解析（需要把 frontmatter 拿出来，预解析的结果会复用到编译阶段用于提速）

**Comment by vortesnail** [comment]
> 在 webpack 启动之前，dumi 有两个耗时点：
> 
> 1. 约定式路由读取（遍历目录耗时）
> 2. md 文件预解析（需要把 frontmatter 拿出来，预解析的结果会复用到编译阶段用于提速）

嗯，但是比如就100个md文件会耗去大概七八分钟的时间吗？感觉还是有点夸张了。有什么办法可以优化吗，关于这个阶段？

**Comment by PeachScript** [comment]
正常情况下都是很快的，所以还是得有复现仓库才行

**Comment by vortesnail** [comment]
> 正常情况下都是很快的，所以还是得有复现仓库才行

你好，我精简了我们现在的组件库，并删除了与 dumi 打包无关的文件，现在该项目只有 2 个命令：
```
npm run doc           # 本地启动文档
npm run doc-build     # 打包文档
```

因为我将组件缩减到了原来的 1/4 左右，所以现在的打包时间，我本机测试大概在 4-5 分钟，还是很慢。

`.umirc.js` 的配置与原仓库无区别。

我再一次明确下我的疑问哈：

- 本地启动/打包文档的速度太慢了，有无优化手段？

额外的问题：

- logo 和 favicon 的配置到底怎么样配置才是正确的？ （我尝试了查找相关 issue 以及 官方文档的配置方式，都无法实现）

复现仓库地址：[dumi-debugging-speed-demo](https://github.com/vortesnail/dumi-debugging-speed-demo)

再一次感谢 dumi 及 umi 的开发者热心的解答，谢谢🙏！

**Comment by vortesnail** [comment]
通过 `DEBUG=* dumi build` 发现是一直会有 eslint 相关的校验？（如截图所示每次耗时大概3s），我把本地 eslint 的配置文件 `.eslintrc.js` 文件删除后同样会走这个过程。

那么这一块儿是否可以通过配置将 eslint 的校验过程去除呢？

![image](https://user-images.githubusercontent.com/18679842/100323992-89353c00-3001-11eb-99f0-6f66665333eb.png)

**Comment by PeachScript** [comment]
v1.0.37 已修复，感谢反馈
