### ISSUE TITLE
dumi 可以合并多个 md 文档到一个文档中吗

### ISSUE THREAD

**Issue by yuxiuj** [umijs/dumi#383]
### Question
dumi 可以合并多个 md 文档到一个文档中吗，比如将demo文件夹下的多个md文档合并到一个文档中

**Comment by PeachScript** [comment]
可以看下这个 https://d.umijs.org/zh-CN/lab#markdown-%E6%96%87%E4%BB%B6%E5%B5%8C%E5%85%A5
