### ISSUE TITLE
bug: 升级到 rc-2 后自定义主题 layout 在 production 构建后失效

### ISSUE THREAD

**Issue by zhaoyao91** [umijs/dumi#384]
### Versions

- dumi: ^1.1.0-rc.2
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3808838/99359705-6e204900-28ea-11eb-8fba-5e8ec2d00d42.png)

```
/** @jsx jsx */
import { css, jsx, Global } from '@emotion/react';
import DefaultLayout from 'dumi-theme-default/src/layout';
import { ComponentPropsWithoutRef, FC, Fragment } from 'react';

type DefaultLayoutProps = ComponentPropsWithoutRef<typeof DefaultLayout>;

const globalStyles = css``;

const styles = {
  root: css`
    .__dumi-default-previewer-actions button[role='codesandbox'] {
      // 隐藏 codesandbox，目前官方还没有推出相关全局配置
      display: none;
    }

    .__dumi-default-locale-select {
      // 暂时隐藏语言切换功能，等需要上线英文内容时再打开
      // bug：暂时不能在 .umirc.ts 中进行配置，关注 https://github.com/umijs/dumi/issues/379
      display: none;
    }
  `,
};

const Layout: FC<DefaultLayoutProps> = props => {
  return (
    <Fragment>
      <Global styles={globalStyles} />
      <div css={styles.root}>
        <DefaultLayout {...props} />
      </div>
    </Fragment>
  );
};

export default Layout;
```

### What is Expected?

右上角切换语言的按钮和 codesandbox 隐藏起来

### What is actually happening?

没有隐藏起来

### 其他

- dev 环境没问题，build 之后就不行了
- rc-0 没有这个问题

**Comment by PeachScript** [comment]
在 dumi 仓库试了下生产构建不会丢失自定义 layout，[rc.0 到 rc.2](https://github.com/umijs/dumi/compare/dumi@1.1.0-rc.0...@umijs/preset-dumi@1.1.0-rc.2) 没有修改主题相关的内容，建议看下是不是 CSS in JS 导致的问题，另外这两个问题可以不用自定义 layout 解：

1. 全局隐藏 codesandbox 可以通过 `config.styles` 配置全局样式来实现
2. 隐藏中英文切换只要确保本地没有多语言 md 文件即可

**Comment by zhaoyao91** [comment]
@PeachScript 感谢，我新构建的时候也没有复现，难道是缓存问题？

隐藏中英文切换按钮，主要是现在铺垫了一些英文文档，但是还没有准备好开放，所以需要隐藏起来。
