### ISSUE TITLE
请问如何编写普通的 jsx 代码块？

### ISSUE THREAD

**Issue by zhaoyao91** [umijs/dumi#385]
### Question

目前 jsx 代码块都转成 demo 了，但有些 jsx 代码块我真的只想表达代码而已，请问应当如何操作？

**Comment by xrkffgg** [comment]
**jsx

**

** -> ``` 

试试

**Comment by zhaoyao91** [comment]
@xrkffgg 没态看明白，是不是被转义了？

**Comment by xrkffgg** [comment]
md 的写法

![image](https://user-images.githubusercontent.com/29775873/99468679-09153380-297c-11eb-9087-45eaa4b5de45.png)

**Comment by zhaoyao91** [comment]
@xrkffgg 这样写，代码块都变成 demo 了

**Comment by xrkffgg** [comment]
是吗？我看看

**Comment by wood3n** [comment]
用这个：https://github.com/umijs/dumi/issues/268#issuecomment-671302209
![image](https://user-images.githubusercontent.com/31716713/99478629-b3e31d00-298f-11eb-81cc-3ce8d7694c48.png)

**Comment by zhaoyao91** [comment]
@wood3n 多谢，这个文档里貌似没有，也许应当补充

**Comment by PeachScript** [comment]
是的，文档一直漏了

**Comment by PeachScript** [comment]
文档已添加：https://d.umijs.org/zh-CN/guide/control-demo-render#渲染为代码块
