### ISSUE TITLE
bug: 在浏览依赖多个文件的组件代码的过程中，tab 在不同文件间切换时可能出现白屏（线上也有）

### ISSUE THREAD

**Issue by jsdchenye** [umijs/dumi#386]
### Versions

- dumi: ^1.1.0-beta.32
- node:
- npm:
- OS: MacOS 10.14.6 
- Browser: 86.0.4240.198（正式版本） (x86_64)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/10431804/99521831-dd239d80-29cf-11eb-9789-a4d96e0365fa.png)
![image](https://user-images.githubusercontent.com/10431804/99522026-1a882b00-29d0-11eb-8c26-bec5f5cdb890.png)

### What is Expected?
tab 来回切换的时候都是可以正常显示的
### What is actually happening?
看起来从 .jsx 切到 .less 文件之后，第一个tab的名称从 index.jsx 变成 index.less,导致再切回来的时候找不到这个文件，所以白屏。猜测可能跟切换的时候后缀名的处理有关系。

**Comment by PeachScript** [comment]
确实是个 bug，感谢反馈

**Comment by qiaodaima** [comment]
> 确实是个 bug，感谢反馈

我也遇到了

**Comment by PeachScript** [comment]
[v1.1.0-rc.3](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-rc.3) 已修复
