### ISSUE TITLE
feat: 使用<code src="xxx" /> [EXTERNAL 在新窗口打开]生成的demo路径地址, 不规则

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#387]
RT, 

现在地址：http://localhost:8000/_demos/index
route 地址: http://localhost:8000/abc
期待：http://localhost:8000/_demo/abc 
或可配置~

**Comment by PeachScript** [comment]
1.1 已经能规则生成了，可通过 identifier 配置项自定义
