### ISSUE TITLE
<API src="文件名相同就会覆盖，不管路径是否相同"></API>

### ISSUE THREAD

**Issue by leotian** [umijs/dumi#388]
### Question
API里的src，文件名相同就会覆盖？

### Sample Code
目录如下
![image](https://user-images.githubusercontent.com/10192886/99751958-4c0f0c80-2b1e-11eb-9887-6c2928b4a9ea.png)
路径如下，这两个居然会相互覆盖？
![image](https://user-images.githubusercontent.com/10192886/99751913-34378880-2b1e-11eb-9c1e-35b1647f38b1.png)
![image](https://user-images.githubusercontent.com/10192886/99751924-38fc3c80-2b1e-11eb-80b9-f7ff2c9d2b92.png)
导致页面的API table是相同的，本来是不同的
![image](https://user-images.githubusercontent.com/10192886/99752004-6b0d9e80-2b1e-11eb-9bde-f78e9a92e851.png)

**Comment by xrkffgg** [comment]
这么神奇的么，你这 2 个是在一个文件中引的吗？

**Comment by leotian** [comment]
> 这么神奇的么，你这 2 个是在一个文件中引的吗？

不是啊，看目录，两个目录下的 src 里的docs/markdown 里

**Comment by PeachScript** [comment]
这个目录结构确实会有问题，目前如果发现是 index.tsx，会取父级目录作为组件名的，因为通常是 `src/Button/index.tsx` 这种取法

**Comment by leotian** [comment]
> 这个目录结构确实会有问题，目前如果发现是 index.tsx，会取父级目录作为组件名的，组件名会作为唯一键值，因为通常是 `src/Button/index.tsx` 这种取法🤦‍♂️

我的目录结构是如图，要单个组件打包的，所以这算个bug吗还是feature😂，我自己hack了下，watch -p 'src/index.tsx' -c 'cp src/index.tsx src/docs/A.Api.tsx'，然后引入这个文件。

**Comment by PeachScript** [comment]
bug，唯一键值应该由组件 export name 决定

**Comment by xiaohuoni** [comment]
export name 也会有重复的情况

**Comment by PeachScript** [comment]
[v1.1.0-rc.3](https://github.com/umijs/dumi/releases/tag/dumi%401.1.0-rc.3) 已修复，组件名的探测逻辑兼容这几种结构：
1. `src/Button/index.tsx` => `Button`
2. `components/Button/src/index.tsx` => `Button`
3. `src/Button.tsx` => `Button`

**Comment by ishenli** [comment]
这个`@alipay/umi-preset-library` 是不是还没有生效？

**Comment by PeachScript** [comment]
> 这个`@alipay/umi-preset-library` 是不是还没有生效？

生效的，如果有问题可以 Bigfish 讨论区贴下

**Comment by helsonxiao** [comment]
### 问题
我的场景是 monorepos，在每个 package 的根目录下写 README.md，`guessComponentName` 这个函数会被如下配置影响。
```tsx
export default defineConfig({
  resolve: {
    includes: ['docs', '../packages'],
  },
});
```
目录结构
```
packages
└─ pkgA
       ├─ README.md（子包根目录的说明文档）
       ├─ example（CRA 测试项目）
       │    └─ src
       │         ├─ App.tsx
       │         ├─ demos（供 CRA & dumi 复用的 demo）
       │         └─ index.tsx
       ├─ package.json
       └─ src
            └─ index.tsx
```
之所以在子包根目录下放文档的原因有 2 个：
1. 在根目录下放 README.md 基本属于约定俗成的规范，不想为了 dumi 大改现有结构。
2. 子包有独立建 repo 发布的需求，不和其它组件强绑定（区别于 dumi 项目中 packages 的关系），所以也期望在根目录下有 README.md，否则进 repo 是一片空白。为了使用 dumi，我直接把带有 `.git` 记录的 repo 放在了 packages 下，运行良好，除了 README.md 的修改时间读取不准确。

当然配置完 `resolve` 之后就 OK 了，只不过 API 生成 apis.json 的过程中处理有些问题。
```tsx
function guessComponentName(fileAbsPath: string) {
  const parsed = path.parse(fileAbsPath);
  console.log(fileAbsPath)
  console.log(parsed)

  if (parsed.name === 'index') {
    // button/index.tsx => button
    // button/src/index.tsx => button
    return path.basename(parsed.dir.replace(/\/src$/, ''));
  }

  // components/button.tsx => button
  return parsed.name;
}
```
```
// pkgA README.md
<API src="./src/index.tsx"></API>
```
```
// pkgB README.md
<API src="./src/index.tsx"></API>
```
`guessComponentName` 解析 pkgA & pkgB 生成的 `parsed` 都一样，导致覆盖。
```
{
  root: '',
  dir: './src',
  base: 'index.tsx',
  ext: '.tsx',
  name: 'index'
}
```
### 临时方案
写成下面这样就好了，不过很尴尬，希望能搞个优雅一点的处理方案。
```
// pkgA README.md
<API src="../pkgA/src/index.tsx"></API>
```
```
// pkgB README.md
<API src="../pkgB/src/index.tsx"></API>
```

**Comment by PeachScript** [comment]
@helsonxiao 临时方案中的 ，identifier 确实是推荐解法，但看到你上面 ../ 的处理，似乎 guess 前先把相对路径 resolve 成绝对路径就能覆盖这个场景
欢迎提 PR，一起优化

**Comment by helsonxiao** [comment]
> @helsonxiao 临时方案中的 ，identifier 确实是推荐解法，但看到你上面 ../ 的处理，似乎 guess 前先把相对路径 resolve 成绝对路径就能覆盖这个场景
> 欢迎提 PR，一起优化

我有空试着搞一下。

**Comment by helsonxiao** [comment]
> @helsonxiao 临时方案中的 ，identifier 确实是推荐解法，但看到你上面 ../ 的处理，似乎 guess 前先把相对路径 resolve 成绝对路径就能覆盖这个场景
> 欢迎提 PR，一起优化

PR 来了。BTW，这个 issue 在 windows 上由于目录分隔符是 `\`，似乎依旧存在？我一起改掉了。
https://github.com/umijs/dumi/pull/605
