### ISSUE TITLE
feat: layout hero support img

### ISSUE THREAD

**Issue by xrkffgg** [umijs/dumi#393]
### Description

类似于 https://lightproxy.org/ 中 hero title 上的图片

![image](https://user-images.githubusercontent.com/29775873/100320590-5d638780-2ffc-11eb-9a6a-962f441013b6.png)

vuepress 中也有可配置 api

![image](https://user-images.githubusercontent.com/29775873/100320609-63f1ff00-2ffc-11eb-89d3-19fd1c621173.png)

### Solution

https://github.com/alibaba/lightproxy/blob/eaa506fad39d1b54068fc0053b84947d81bb01e3/docs/.umirc.ts#L45-L53

- dumi 是否有计划增加?

**Comment by PeachScript** [comment]
> https://github.com/alibaba/lightproxy/blob/eaa506fad39d1b54068fc0053b84947d81bb01e3/docs/.umirc.ts#L45-L53

这么黑的实现方式，看来是得在默认主题中支持个配置项了

**Comment by xrkffgg** [comment]
嗯，我在本地已经实现了，正准备 PR
