### ISSUE TITLE
bug: 用dumi开发基于antd的组件，使用项目因按需加载导致组件中的antd本身的组件样式没加载出来。

### ISSUE THREAD

**Issue by GloriaCHL** [umijs/dumi#397]
### Versions

- dumi:^1.0.10
- node:v14.15.0
- npm: 6.14.8
- OS: mac big sur
- Browser: chrome

### Steps to reproduce
1. 使用 `yarn create @umijs/dumi-lib` 初始化组件库。
2. 实现一个组件，里面引用了`import {Image} from 'antd'`。再加点自己的样式，放在 `style.less` 文件中。都是按照一般应用开发流程来操作。
3. umirc.ts 添加以下配置，不然组件里引用 antd 无效。

   ```
   extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
      'antd',
       ],
     ],
   ```

4. fatherrc.ts 中加入 cssModules 配置，以使自己的less文件生效。
5. `yarn build` 后 `yarn link`。
6. 初始化一个使用组件库的项目，我用了 `ant-design-pro` 初始化。使用 `yarn link XXX` 来调用组件库。

### What is actually happening?
在ant-design-pro项目中引用我写的组件，发现组件中的 Image 是没有对应的样式支持的。我再在页面中引入一个antd 的 Image 组件后，我写的组件中的 Image 就有了样式了。

请问这是一个dumi打包的bug吗？还是我应该在哪里配置一下可以解决这个问题？

提供例子：https://www.npmjs.com/package/@gloria.lee/antd-gz-libs

```
npm i @gloria.lee/antd-gz-libs
```

**Comment by GloriaCHL** [comment]
破案了。在 fatherrc.ts 里加个 antd 的配置：

```
extraBabelPlugins: [
    ['babel-plugin-import', {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: true,
    }],
  ],
```

**Comment by nbhaohao** [comment]
感谢，遇到了相同的问题。

**Comment by Mluocheng** [comment]
配置了 
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
      'antd',
       ],
     ],
之后 有遇到这个问题吗
![image](https://user-images.githubusercontent.com/31057183/157367383-38d1de59-d869-4dd9-a3ad-6c34b2dfd303.png)
我是这样写的：
![image](https://user-images.githubusercontent.com/31057183/157367402-b613b217-229f-47b2-80d5-9dba83d0e0f3.png)
