### ISSUE TITLE
bug: 引入相对路径时Codepan链接消失

### ISSUE THREAD

**Issue by RequiemSoul** [umijs/dumi#399]
![image](https://user-images.githubusercontent.com/21095553/100565337-4f647e00-32fe-11eb-9060-836c702e617d.png)

在basic.tsx中引用以下相对路径的文件会导致codepan 链接消失, 不引用则正常

 import Item from './item';
 import './basic.less';

 
![image](https://user-images.githubusercontent.com/21095553/100565056-9736d580-32fd-11eb-9380-8016b03bddb3.png)

### Versions

- dumi: 1.0.36
- node:v12.17.0
- npm:6.14.4

**Comment by PeachScript** [comment]
正式版不支持多文件 codesandbox 打开，可以尝试 1.1 rc 版
