### ISSUE TITLE
feat: add console.log tab

### ISSUE THREAD

**Issue by xrkffgg** [umijs/dumi#409]
### Description

有时候组件的展示需要显示 console.log 的内容，

storybook 可以可以展示出输出，对应 demo 的演示很方便。

![image](https://user-images.githubusercontent.com/29775873/101307248-f6f32a80-3881-11eb-8e88-7d5c40621657.png)

### Solution

期望 增加该功能，如在 展开代码 按钮旁边 增加一个 输出 console.log 的 tab

**Comment by PeachScript** [comment]
这感觉再做都没有浏览器的 console 好用…

storybook 劫持原生 console 也有一些潜在问题，比如会导致 log 的行号全部变成 storybook 劫持输出的那行

**Comment by xrkffgg** [comment]
嗯
