### ISSUE TITLE
.umirc.js中配置alias，tsx文件中使用import xx from '@util/xx'  dev运行有作用 build报错 我应该怎么配置才能build也生效

### ISSUE THREAD

**Issue by LiveJie** [umijs/dumi#410]
### Question
dumi项目配置中配置alias run dev 的时候生效 build的时候报错
报错信息如下
``` shell
Build cjs with rollup
'~/utils/constants' is imported by src/fields/search-input/index.jsx, but could not be resolved – treating it as an external dependency
Build esm with rollup
'~/utils/constants' is imported by src/fields/search-input/index.jsx, but could not be resolved – treating it as an external dependency
```
然后去查阅了rollup的文档
[rollup文档](https://www.kancloud.cn/yunye/rollup/327467)
但是不知道怎么应用到dumi的项目中，我自己尝试了好久也没尝试成功，特地来寻求帮助
### Sample Code
.umirc.js
```
alias: { '@': resolveFile('src') },
```
jsx
```
import { xxx } from '@/utils/xxx';
```

**Comment by PeachScript** [comment]
build 走的是 [father-build](https://github.com/umijs/father)，目前不支持配置 alilas

**Comment by LiveJie** [comment]
> build走的是[father-build](https://github.com/umijs/father)，目前不支持配置alilas

好的，谢谢回复。
