### ISSUE TITLE
内网文档生成

### ISSUE THREAD

**Issue by warryy** [umijs/dumi#412]
### Question
想用 dumi 为私有组件库生成文档, 公司内部也有相关的内网 sandbox, 请问有什么办法可以使用 dumi 的查看 sandbox 代码按钮跳转到内网的 sandbox 页面吗?

**Comment by PeachScript** [comment]
不同的代码演示平台 API 及数据结构是不同的，无法直接使用 dumi 内置的 codesandbox 能力；可以基于你们内部平台的接口设计，使用主题 API、扩展一个内部用的主题包、复写 dumi 内置的 `Previewer.tsx` 即可，参考：
- 主题 API 文档：https://d.umijs.org/zh-CN/lab#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98
- dumi 的移动端组件研发主题包中对 `Previewer.tsx` 的复写：https://github.com/umijs/dumi/blob/master/packages/theme-mobile/src/builtins/Previewer.tsx
