### ISSUE TITLE
feat: customize entry HTML in a better way

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#413]
### Description

Umi 的设定是 `src/pages/document.ejs` 可以自定义 HTML 模板，但对于大多数组件库而言，`pages` 是个多余的层级，所以最好能走 dumi 自己的路径来自定义 HTML 模板，比如 `src/document.ejs` 或者和主题包的 `.dumi/theme` 约定一脉相承 `.dumi/document.ejs`。

### Solution

应该可以通过 [`modifyProdHTMLContent`](https://github.com/umijs/umi/blob/b896f13bc2f2de57aa0d1ed24343613feab97d3f/packages/preset-built-in/src/plugins/commands/build/applyHtmlWebpackPlugin.ts#L44) 和 [`modifyDevHTMLContent`](https://github.com/umijs/umi/blob/da2ae777f66e2578fc0b9c64e0edc0e07216cb4c/packages/preset-built-in/src/plugins/commands/dev/createRouteMiddleware.ts#L33) 这两个钩子实现，需要自己实例化一个 `HtmlGenerator`

但可能会导致 SSR 的逻辑工作不正常：https://github.com/umijs/umi/blob/99c6e8c15d67060aec6c2ac6b696f0b1c1d81b1a/packages/preset-built-in/src/plugins/features/ssr/ssr.ts#L120

@ycjcl868 帮忙看看

**Comment by ycjcl868** [comment]
应该提供自定义 document.ejs 的路径 api，其它不变

![image](https://user-images.githubusercontent.com/13595509/103058667-b1a84b80-4557-11eb-816d-67ece807d00e.png)

**Comment by PeachScript** [comment]
能有专门的 API 更好，`modifyDocumentTplPath`？

**Comment by PeachScript** [comment]
dumi v1 不再更新，issue 关闭
