### ISSUE TITLE
bug: 导航条不会随着滚动条滑动高亮

### ISSUE THREAD

**Issue by chnliquan** [umijs/dumi#416]
### Versions

- dumi: 1.1.0-rc.5
- node: 12.8.0
- npm: 6.14.6
- OS: 11
- Browser: Chromse

文档左侧和右侧的导航栏不会随着滚动条的变化高亮，dumi 官网有同样的问题

![image](https://user-images.githubusercontent.com/34906299/101712042-acff8400-3acf-11eb-9e90-bc2205393ec9.png)

![image](https://user-images.githubusercontent.com/34906299/101708996-863e4f00-3ac9-11eb-89f3-67f428e9d907.png)

**Comment by chnliquan** [comment]
@PeachScript 老哥，麻烦修复下这个 bug 哈。比较影响使用体验

**Comment by PeachScript** [comment]
@chnliquan PR Welcome

**Comment by xrkffgg** [comment]
还有一个相关的现象是 https://d.umijs.org/zh-CN/config#base ，点击进入链接后，左侧菜单没有呈现激活状态

**Comment by conlearning** [comment]
可否加一个功能，比如用楼上的https://d.umijs.org/zh-CN/config#base 链接从其他网站跳过来，可否左侧菜单也跳转到对应的文章？目前新跳转过来仅会显示左侧菜单顶部。

**Comment by PeachScript** [comment]
@conlearning PR welcome~

**Comment by PeachScript** [comment]
v1.1.26 已支持
