### ISSUE TITLE
API 组件，能否显示父类的props

### ISSUE THREAD

**Issue by yinhunfeixue** [umijs/dumi#417]
### Question
API 组件，能否显示父类的props

**Comment by PeachScript** [comment]
extends 过来的会自动展示

**Comment by yinhunfeixue** [comment]
> extends 过来的会自动展示

似乎不会，步骤如下

1、定义子类Props
```tsx
export interface IPageHeaderProps extends IComponentProps {
  /**
   * 附加内容，显示在页头右侧
   */
  extra?: ReactNode;

  /**
   * 标题
   */
  title: string;

  /**
   * 点击返回触发的方法。默认为null，此时，不显示返回按钮
   */
  onBack?: () => void;

  /**
   * 返回按钮的图标
   */
  backIcon?: ReactNode;
}
```

2、定义父类props
```tsx
interface IPageViewProps extends IPageHeaderProps {
  /**
   * 页头样式名
   */
  headerClassName?: string;

  /**
   * 页头内联样式
   */
  headerStyle?: CSSProperties;
}
```
3、定义组件
```tsx
class PageView extends Component<IPageViewProps, IPageViewState>{}
```

4、编写文件 PageView.md
```
<API src="../../src/PageView.tsx" />
```

生成结果如下
![image](https://user-images.githubusercontent.com/29660825/101738194-be14b900-3b00-11eb-9dfe-b6837df9eab5.png)

**Comment by PeachScript** [comment]
entends 有对应测试用例的，可以对比看看、或者提供个复现：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/api-parser/fixtures/raw/extends.tsx

**Comment by yinhunfeixue** [comment]
> entends 有对应测试用例的，可以对比看看、或者提供个复现仓库：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/api-parser/fixtures/raw/extends.tsx

原因找到了

如果父props和子props在同一个文件中，文档正常

否则，文档中只有子props的属性

**Comment by PeachScript** [comment]
但用例里面 `IAProps` 也是从别的文件引入的？

**Comment by ChenYCL** [comment]
这里的API这个title可以自定义么,还有映射markdown关系,再开启toc: menu 情况下,API会变成左侧子菜单显示
![image](https://user-images.githubusercontent.com/25706676/101886990-3ea5e900-3bd7-11eb-9fbb-37268f4f7308.png)

**Comment by PeachScript** [comment]
@ChenYCL title 确实应该提供一个配置控制；toc 是预期结果，因为 API 的标题也是 toc 的一部分；另外后续 API 相关问题可以到制定的 issue 里提，以便汇总 #358

**Comment by yinhunfeixue** [comment]
> entends 有对应测试用例的，可以对比看看、或者提供个复现仓库：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/api-parser/fixtures/raw/extends.tsx

项目地址
https://github.com/yinhunfeixue/h5-webview

项目代码：v3分支  v3文件夹

现象
1. page-view--缺少父props的属性
2. page-wrap--一个props属性也没有

**Comment by yinhunfeixue** [comment]
今天更新node_module后可以了，请求关闭此issues
