### ISSUE TITLE
bug: "hideActions" not working correctly

### ISSUE THREAD

**Issue by zhangyu-foxfox** [umijs/dumi#422]
# "hideActions" not working correctly

### Versions

- dumi: 1.0.38
- node: 12.14.1
- npm: 6.13.4
- OS: 10.14.6
- Browser: Chrome 87.0.4280.88

### Steps to reproduce

`<code src="./index.jsx" hideActions='["EXTERNAL"]' />`

### What is Expected?

The share button should be hidden.

### What is actually happening?

The share button is still there, but codesandbox button disappear.

**Comment by PeachScript** [comment]
Please provide a reproduce repo

**Comment by zhangyu-foxfox** [comment]
> Please provide a reproduce repo

https://github.com/zhangyu-foxfox/dumi-repo

**Comment by zhangyu-foxfox** [comment]
> > Please provide a reproduce repo
> 
> https://github.com/zhangyu-foxfox/dumi-repo

Please see "src/Foo/index.md"

**Comment by PeachScript** [comment]
试下最新版 1.1.2，有问题再反馈
