### ISSUE TITLE
如何创建自定义标签,在markdown当中使用,官方文档仅提供部分兜底

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#424]
### 在md当中使用API,如何自行构建这块内容,在theme下创建了一个自定义的tsx,md无法识别

![image](https://user-images.githubusercontent.com/25706676/101893099-3a7dc980-3bdf-11eb-83d6-44fdc0b4f4fe.png)
![image](https://user-images.githubusercontent.com/25706676/101893198-67ca7780-3bdf-11eb-8316-8a2e83fb5b5a.png)

**Comment by PeachScript** [comment]
无法复现，有复现仓库吗

**Comment by PeachScript** [comment]
可以 `DEBUG=dumi:theme dumi dev` 看下输出的主题解析结果

**Comment by ChenYCL** [comment]
可以看看这个 https://github.com/lgoweb/pro-components/tree/test 主体应该是用的dumi吧

**Comment by PeachScript** [comment]
单字母组件目前无法正常工作，换成其他名字试试
