### ISSUE TITLE
移动端组件研发 bug:  dumi@1.1.0-beta.18 以上报错 Object(...) is not a function

### ISSUE THREAD

**Issue by flftfqwxf** [umijs/dumi#425]
在beta及移动端组件研发 版本下，报错

![image](https://user-images.githubusercontent.com/5468564/101893200-68fba480-3bdf-11eb-9756-0849bfce6a09.png)

使用
环境：

系统mac 
node:12.18.4

安装：
dumi@1.1.0-beta.18
dumi-theme-mobile

![image](https://user-images.githubusercontent.com/5468564/101893257-7749c080-3bdf-11eb-84e6-30f301ce1c7b.png)
启动：
![image](https://user-images.githubusercontent.com/5468564/101893293-8466af80-3bdf-11eb-9e6b-32378e49cc26.png)

目录结构如下
![image](https://user-images.githubusercontent.com/5468564/101897132-0a392980-3be5-11eb-9f58-197dad798fb5.png)

md如下：
```


---
title: 文档示例
legacy: /example
nav:
  order: 3
  title: 渲染示例
toc: menu
---

# 文档示例

此页面列举了 dumi 渲染各项 Markdown 样式以及 Demo 的效果。

## 渲染 Demo

### 代码块嵌入

```jsx
import React from 'react';
import { Button } from 'antd';

export default () => <Button type="primary">我是 antd 的按钮</Button>;
```

```

**Comment by PeachScript** [comment]
重装依赖试试，怀疑某个底层库做了改动但又修复了，我们也有碰到过几例

**Comment by flftfqwxf** [comment]
@PeachScript 谢谢，问题已解决，安装beta版本会有问题，安装@next版本 1.1.0-rc.7。就可以了
