### ISSUE TITLE
md在watch情况下,有几率变成乱码

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#430]
![image](https://user-images.githubusercontent.com/25706676/102054489-79509100-3e24-11eb-9de0-f4db969923d1.png)

![image](https://user-images.githubusercontent.com/25706676/102054533-8b323400-3e24-11eb-933e-b1db12e9240c.png)
尚不明确是vscode格式化还是,dumi触发的问题,如果有人相同情况

**Comment by xrkffgg** [comment]
这 你直接用 vscode 看就是乱码啊

**Comment by ChenYCL** [comment]
在编辑其它带头demo tsx的情况下,突然变这样了,webstorm 昨天也发生了,今天换到vscode 也出现了这个情况.

**Comment by xrkffgg** [comment]
感觉应该是编码的原因，选择 UTF-8

**Comment by PeachScript** [comment]
dumi 版本多少?

**Comment by ChenYCL** [comment]
@PeachScript dumi@1.1.0-beta.27+

**Comment by PeachScript** [comment]
@ChenYCL 使用最新的 rc 版看看问题还存不存在

**Comment by PeachScript** [comment]
先关了，还有遇到再 reopen
