### ISSUE TITLE
bug: 启用 dynamicImport，会导致每个 md 重复编译组件库，严重影响编译速度

### ISSUE THREAD

**Issue by shengbeiniao** [umijs/dumi#431]
复现 repo: https://github.com/shengbeiniao/dumi-test

![image](https://user-images.githubusercontent.com/3301995/102181666-ff80dc00-3ee5-11eb-9f2a-d2b4e9472907.png)

### Versions

- dumi: 1.0.37
- node: 12.16.3
- npm:
- OS: linux
- Browser:

**Comment by shengbeiniao** [comment]
找到原因了，禁用 dynamicImport 可 fix

![image](https://user-images.githubusercontent.com/3301995/102759099-a239ce80-43ae-11eb-91ee-6c98b50c792c.png)

测试命令：WEBPACK_PROFILE=verbose SPEED_MEASURE=CONSOLE COMPRESS=none dumi build

分析工具：http://webpack.github.io/analyse，上传 stats.json

COMPRESS=none 禁用 terserPlugin，这个比较耗时

**Comment by ycjcl868** [comment]
@PeachScript  一起看看

**Comment by ycjcl868** [comment]
> 找到原因了，禁用 dynamicImport 可 fix
> 
> ![image](https://user-images.githubusercontent.com/3301995/102759099-a239ce80-43ae-11eb-91ee-6c98b50c792c.png)
> 
> 测试命令：WEBPACK_PROFILE=verbose SPEED_MEASURE=CONSOLE COMPRESS=none dumi build
> 
> 分析工具：[http://webpack.github.io/analyse，上传](http://webpack.github.io/analyse%EF%BC%8C%E4%B8%8A%E4%BC%A0) stats.json
> 
> COMPRESS=none 禁用 terserPlugin，这个比较耗时

可以用 @umijs/plugin-esbuild 插件，这个压缩几乎不耗时

**Comment by PeachScript** [comment]
新版本中这个问题是否还存在
