### ISSUE TITLE
开启模拟移动端审查元素,预览消失 

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#432]
![image](https://user-images.githubusercontent.com/25706676/102196950-7f657100-3efb-11eb-8109-938c929cdf81.png)

### Versions

"dependencies": {
    "react": "^16.12.0"
  },
  "devDependencies": {
    "@umijs/test": "^3.0.5",
    "dumi": "^1.1.0-rc.7",
    "dumi-theme-mobile": "^1.0.0-rc.4",
    "father-build": "^1.17.2",
    "gh-pages": "^3.0.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1",
    "yorkie": "^2.0.0"
  }
os: mac
os version: big sur (11.0.1 (20B29)

**Comment by PeachScript** [comment]
这是响应式规则的预期结果，如果要用浏览器的模拟器审查元素，可以新窗口打开
