### ISSUE TITLE
feat: features 添加 link, 可以点击 icon 或 title 切换路由或跳转

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#436]
RT

**Comment by xrkffgg** [comment]
没太明白，不是现在都有跳转的吗？

**Comment by mizi-lin** [comment]
![image](https://user-images.githubusercontent.com/2802841/102458251-efe8cb00-407e-11eb-82e0-05fdbcff67a5.png)

点击可以跳转~

**Comment by xrkffgg** [comment]
意思是 这几个图片可以点击跳转？
