### ISSUE TITLE
feat: 支持打开一个demo

### ISSUE THREAD

**Issue by chenshuai2144** [umijs/dumi#44]
每个demo 在 router 中生成一个单独的 path。支持通过一个按钮单独一个页面打开demo。类似 stroybook，这样支持 iframe 也会很简单，我们开发组件库调试也很方便

**Comment by PeachScript** [comment]
目前的计划是会给外链 demo 增加一种 iframe 模式，启用了以后会生成单独的 route path，便于展示一些不方便内嵌的 demo，至于默认生成 iframe 可以再讨论看具体的场景

**Comment by PeachScript** [comment]
v1.0.4 已支持
