### ISSUE TITLE
bug: markdown无序列表中没有前面的黑点

### ISSUE THREAD

**Issue by AlbertXiaoPeng** [umijs/dumi#441]
### Versions

- dumi: 1.0.38
- node: 12.15.0
- npm: 6.13.4
- OS: Windows 10
- Browser: Chrome

### Steps to reproduce

默认样板使用

### What is Expected?

markdown 生成的无序列表没有前面的黑点

![image](https://user-images.githubusercontent.com/44151574/102568962-f1220280-4127-11eb-8469-44275b921d4e.png)

**Comment by xrkffgg** [comment]
试试 `1.1.0-rc.7`

**Comment by AlbertXiaoPeng** [comment]
> 试试 `1.1.0-rc.7`

我通过自定义css样式文件，改变了markdown渲染样式，但是引入了一个新的引用问题
#442
