### ISSUE TITLE
自定义样式文件无法引用本地文件，只能引用cdn或者直接代码形式

### ISSUE THREAD

**Issue by AlbertXiaoPeng** [umijs/dumi#442]
### Question

自定义样式文件无法引用本地文件，只能引用cdn或者直接代码形式

### Sample Code

```
// defineConfig 配置
styles: [`public/css/markdown.css`]
或者
styles: ["public/css/markdown.css"],
```
都会变成下面这种
![image](https://user-images.githubusercontent.com/44151574/102590263-a322f400-4153-11eb-8697-69fdcc2d7899.png)

**Comment by AlbertXiaoPeng** [comment]
我只能通过
```
styles: [`${host}/public/css/markdown.css`]
```
来引用我自己的本地静态文件

**Comment by PeachScript** [comment]
在 `src/app.ts` 里 import 自己的样式文件即可
