### ISSUE TITLE
@umijs/preset-dumi 未对空格路径进行处理

### ISSUE THREAD

**Issue by rccq17mj** [umijs/dumi#444]
### 问题描述

node_modules/@umijs/preset-dumi/lib/utils/getHostPkgAlias.js 
74 行：

```
      JSON.parse((0, _child_process().execSync)(`${_path().default.join(paths.cwd, 'node_modules/.bin/lerna')} ls --json --all`, {
        stdio: 'pipe'
      }).toString()).forEach(pkg => {
        pkgs.push([pkg.name, pkg.location]);
      });
```

直接使用 paths.cwd 导致有空格的路径报错：

Command failed: /Volumes/APP OSX/CloudStation/project/gcongo/pyramid-kit-v2/node_modules/.bin/lerna ls --json --all
/bin/sh: /Volumes/APP: No such file or directory

Error: Command failed: /Volumes/APP OSX/CloudStation/project/gcongo/pyramid-kit-v2/node_modules/.bin/lerna ls --json --all
/bin/sh: /Volumes/APP: No such file or directory
![image](https://user-images.githubusercontent.com/29419878/102737325-16aa4880-4382-11eb-94fe-de79635ff646.png)

### 正确的处理方式

```
`${_path().default.join(`'${paths.cwd}'`, 'node_modules/.bin/lerna')} ls --json --all`
```

### 版本信息
* @umijs/preset-dumi Version: 1.1.0-rc.7
* Node Version: 12.12.0

**Comment by rccq17mj** [comment]
> 这看起来是 lerna 的 bin 文件没找到？

我的磁盘路径中间有空格，paths.cwd 需要加引号，否则路径会变成下面的情况
'/Volumes/APP OSX/CloudStation/...'
识别为：
'/bin/sh: /Volumes/APP'
空格处被截断

**Comment by PeachScript** [comment]
明白了，直接加引号不行，macOS 允许单引号作为文件名

**Comment by Kpyu** [comment]
我这里也遇到问题，不过是处理windows环境的路径，\\ 这种双斜杠路径的时候就会报parse错误

**Comment by PeachScript** [comment]
@Kpyu 具体错误贴一下看？

**Comment by Kpyu** [comment]
@umijs/preset-dumi 1.0.38版本
![image](https://user-images.githubusercontent.com/5809621/103610617-8d873a00-4f5b-11eb-8ecc-3591f231388a.png)
这里toString会把转义符号给去掉了，导致parse的时候会把剩下的单杠识别未转义符号直接报错
![image](https://user-images.githubusercontent.com/5809621/103610695-b5769d80-4f5b-11eb-9d20-f8f5ed8be837.png)

**Comment by Kpyu** [comment]
getHostPkgAlias.ts

**Comment by Kpyu** [comment]
> 明白了，直接加引号不行，macOS 允许单引号作为文件名



> @Kpyu 具体错误贴一下看？
https://github.com/umijs/dumi/issues/444#issuecomment-754411054

**Comment by PeachScript** [comment]
dumi v2 已发布，欢迎升级体验：https://d.umijs.org/

dumi v1 不再更新，issue 关闭
