### ISSUE TITLE
Question: 是否有办法可以重新渲染Previewer中的代码块

### ISSUE THREAD

**Issue by hqxczjx** [umijs/dumi#447]
### Question

目前我需要能够查看代码块并在线编辑，由于其中依赖的npm包放在公司内部的npm源上，所以使用codesandbox打开应该是无法添加对应包的，所以希望在渲染完成之后获取到md中显示的代码源码，即Previewer的props.sources，然后修改其中的内容，重新渲染整个Previewer，不知道目前有没这样的方法

**Comment by PeachScript** [comment]
精力原因，在线编辑、实时渲染还没做，有兴趣可以一起建设❤

另外，props.sources 只是用来源代码展示，并不用作渲染，所以实时改 props.sources 的思路目前行不通；issue 关闭，和 #96 重复。
