### ISSUE TITLE
bug: 二级域名点开 第二类语言 首页

### ISSUE THREAD

**Issue by xrkffgg** [umijs/dumi#452]
### Versions

- dumi: 1.1-rc8

### Steps to reproduce

https://actions-cool.github.io/issues-helper/en-US

点开后会默认变成 

https://actions-cool.github.io/issues-helper/en-US/

该现象存在与 部署在非跟目录

**Comment by xrkffgg** [comment]
类似的问题有
https://actions-cool.github.io/issues-helper/base#welcome

打开后会变成 

https://actions-cool.github.io/issues-helper/base/#welcome

base 也加上了 /

**Comment by xrkffgg** [comment]
该现象只存在于 非根目录 部署

**Comment by PeachScript** [comment]
refer: https://stackoverflow.com/questions/33270605/github-pages-trailing-slashes

**Comment by chnliquan** [comment]
githubPages 会在路由后面默认在 /，这样二级菜单就不会显示了

![image](https://user-images.githubusercontent.com/34906299/103451134-3d11a180-4cfb-11eb-8ec2-72b00815ea44.png)
![image](https://user-images.githubusercontent.com/34906299/103451136-43078280-4cfb-11eb-9fa7-4659a3c5c664.png)

**Comment by PeachScript** [comment]
和 #564 一样的原因，v1.1.5 已修复，issue 关闭
