### ISSUE TITLE
bug: 切换语言时，未带 # 后标题

### ISSUE THREAD

**Issue by xrkffgg** [umijs/dumi#453]
### Versions

- dumi: 1.1-rc8

### Steps to reproduce

https://d.umijs.org/config#algolia

切换语言变成

https://d.umijs.org/zh-CN/config

### What is Expected?

https://d.umijs.org/zh-CN/config#algolia

**Comment by PeachScript** [comment]
这个不太好处理，因为不知道中文的标题 anchor 对应着英文的哪条标题；有个思路是按序号来，中英文虽然标题不相同，但通常顺序还是一致的，可以试试看

**Comment by xrkffgg** [comment]
对哦，忘记名称不一样了 😂
