### ISSUE TITLE
bug: The "Edit this doc on GitHub" not show 

### ISSUE THREAD

**Issue by tomee-oy** [umijs/dumi#457]
### Versions

- dumi: ^1.0.38
- node: 14.7.0
- npm: 6.14.7
- OS: macOS Mojave 10.14.6
- Browser: google 87.0.4280.88

### Steps to reproduce

I have set repository in package.json like this:
```json
 "repository": {
    "type": "git",
    "url": "http://10.12.3.198/bigdata/frontend/cmiot-basic.git"
 },
```

### What is Expected?

"Edit this doc on GitHub" will show out at the footer

### What is actually happening?

The "Edit this doc on GitHub" not show

**Comment by xrkffgg** [comment]
重新下

**Comment by xrkffgg** [comment]
url 一般是配置 GitHub 的地址

**Comment by tomee-oy** [comment]
> url 一般是配置 GitHub 的地址

配置带ip地址的gitlab地址不行吗

**Comment by xrkffgg** [comment]
没试过，你可以试下

**Comment by PeachScript** [comment]
不行，目前是通过域名来判定是哪种代码托管平台，IP 无法体现这一点

**Comment by tomee-oy** [comment]
> 不行，目前是通过域名来判定是哪种代码托管平台，IP 无法体现这一点

后续有可能支持内部gitlab平台么？
