### ISSUE TITLE
关于mermaid时序图、流程图的支持

### ISSUE THREAD

**Issue by monlor** [umijs/dumi#466]
### Question
目前已有办法支持或考虑支持mermaid时序图、流程图这个特性么？

**Comment by xrkffgg** [comment]
tsx 里使用 AntV

**Comment by monlor** [comment]
不能在md里直接用mermaid是吧？

**Comment by xrkffgg** [comment]
mermaid 啊，没看到 😂 ，这得需要额外处理才行啊

**Comment by monlor** [comment]
可以考虑考虑呢

**Comment by PeachScript** [comment]
remark 社区有类似 plugin，不过是 3 年前的了：https://github.com/temando/remark-mermaid

dumi 得允许用户自定义 remark 插件才行

**Comment by youngjuning** [comment]
现在支持自定义 remark 插件吗？

**Comment by PeachScript** [comment]
看了下 [自定义 Markdown 组件](https://d.umijs.org/zh-CN/theme/development)，再配合 https://github.com/mermaid-js/mermaid 应该可以玩了
