### ISSUE TITLE
feat: support react native component

### ISSUE THREAD

**Issue by youngjuning** [umijs/dumi#467]
### Description

support react native component

### Solution

add dumi-theme-react-native

**Comment by DreamPWJ** [comment]
是否支持android和ios组件文档？

**Comment by youngjuning** [comment]
@DreamPWJ  支持 RN 就可以的，原生的组件文档这个搞不了吧。我们现在用的 docz 来生成站点 https://panel-docs.tuyacn.com/components/BasicComponents_Button

但是使用体验和维护体验很差，我在调研能不能用 dumi 替代

**Comment by youngjuning** [comment]
我写了一个 umi-plugin-react-native 支持了
