### ISSUE TITLE
bug: 文档编辑链接指向问题

### ISSUE THREAD

**Issue by ipudu** [umijs/dumi#469]
### Versions

- dumi: 1.0.10

### Steps to reproduce

在 GitHub 上编辑这篇文档  <---   链接默认指向master branch，现在Github 新项目的默认是main branch。

**Comment by xrkffgg** [comment]
```json
// package.json
"repository": {
    "type": "git",
    "url": "xxx",
    "branch": "main"
  },
```

**Comment by xrkffgg** [comment]
需要升级下 dumi 版本，1.0 的不支持哦

**Comment by ipudu** [comment]
了解，已经work了。谢谢！
