### ISSUE TITLE
bug: Windows环境下getHostPkgAlias中未对windows路径做单独处理导致JSON.parse报错

### ISSUE THREAD

**Issue by Kpyu** [umijs/dumi#470]
@umijs/preset-dumi 包中的 getHostPkgAlias.ts 第20行
![image](https://user-images.githubusercontent.com/5809621/103749712-d369fe00-5040-11eb-8d06-94fed81eb8d3.png)
这里toString会把转义符号给去掉，导致parse的时候会把剩下的单杠识别为转义符号直接报错
![image](https://user-images.githubusercontent.com/5809621/103749771-e5e43780-5040-11eb-8fb6-76ce54cf441a.png)

**Comment by lbwa** [comment]
@Kpyu 你所阐述的点在 window platform 下并不会出现你所描述的 JSON parse error 场景。

1. 对于你浏览器的截图，在 **浏览器** 中 `D:\\workspace` 不用调用 toString() 方法，直接输出就是 `D:\workspace`，这是浏览器自身的处理行为。浏览器 js runtime 和 nodejs runtime 这里是不同的处理方式，二者 runtime **不能等价**。

    <img width="214" alt="1" src="https://user-images.githubusercontent.com/32980314/103780758-61111200-5070-11eb-8678-7a38f91fa562.png">

请你额外提供一个 reproduction repo 帮助我们找到问题？
