### ISSUE TITLE
feat: config sort

### ISSUE THREAD

**Issue by mortalYoung** [umijs/dumi#471]
### Description
- 希望 Config 页面可以按照首字母排序一下 不然找配置比较难找
### Solution

[Config](http://localhost:8000/zh-CN/config) 页面

**Comment by xrkffgg** [comment]
好像 dumi 的 config 是排序的了。后面从 umi 同步过来的 也是有顺序的。。。

看看要不要把这2 个分开下，一个叫本身 config 一个是 umi 的

**Comment by mortalYoung** [comment]
> 好像 dumi 的 config 是排序的了。后面从 umi 同步过来的 也是有顺序的。。。
> 
> 看看要不要把这2 个分开下，一个叫本身 config 一个是 umi 的

感觉可以分开来 一个叫 config 一个叫 external config 或者 @PeachScript 辟起考虑下叫啥

**Comment by PeachScript** [comment]
分开吧，主要 Umi 同步过来的内容不好合并排序，基础配置 & 更多配置？

**Comment by xiaohuoni** [comment]
我觉得只需要维护一份 dumi 的配置就好，不必同步 umi 的配置。有些 umi 配置，dumi 中根本不会用，假设 umi 出了新的配置，也是需要人工确认，在 dumi 中是否有可能使用，那些非常规的高级用法，可以让他们再去看 umi 官方配置。

**Comment by PeachScript** [comment]
有很多没有 Umi 使用经验的用户会觉得懵，所以文档中尽量不透出 Umi 了
