### ISSUE TITLE
bug: 构建提示EINVAL: invalid argument, mkdir 'D:\GoProject\docs\docs-dist\~demos\:uuid'] 

### ISSUE THREAD

**Issue by mhxw** [umijs/dumi#473]
![image](https://user-images.githubusercontent.com/32643286/103860866-62d1e880-50f7-11eb-8f6d-9293f3e67a70.png)

**Comment by PeachScript** [comment]
`exportStatic` 属性暂不兼容 Windows 系统

**Comment by mhxw** [comment]
这个之前一直加的（可以构建成功）。初步估计，应该是npm依赖包问题

**Comment by xrkffgg** [comment]
https://github.com/umijs/umi/issues/5921

**Comment by mhxw** [comment]
好的，谢谢。

**Comment by PeachScript** [comment]
@xrkffgg dumi 在构建的时候我们把路由铺开来？比如 dev 的时候是 `/~demos/:uuid`，但构建之后就变成 `/~demos/a`、`~demos/b` 之类的

**Comment by PeachScript** [comment]
> @xrkffgg dumi 在构建的时候我们把路由铺开来？比如 dev 的时候是 `/~demos/:uuid`，但构建之后就变成 `/~demos/a`、`~demos/b` 之类的

exportStatic 已兼容 Windows，构建可以成功但产出的动态路由是不能直接使用的，后续版本会优化成上面的方案，issue 关闭

**Comment by PeachScript** [comment]
#715 里 track

**Comment by xiyanma** [comment]
![869e697686a92c12c2562aa3cc41e5d](https://user-images.githubusercontent.com/37499101/173238660-bde1de07-8c4e-451a-a3a3-201332edbf49.png)
是同一种问题嘛
