### ISSUE TITLE
使用 <code src="../.demos/workflow/test/index.tsx"></code> 编译时报错

### ISSUE THREAD

**Issue by KellenHe** [umijs/dumi#474]
使用 `<code src="../.demos/workflow/test/index.jsx"></code>` 编译时报如下错误：
`Expected corresponding JSX closing tag for <p>`
![image](https://user-images.githubusercontent.com/9713892/103866355-99603100-5100-11eb-9fe1-7fd6e375321f.png)

index.jsx内容如下
`import React from 'react';
export default () => <h1>Hello dumi!</h1>;`

### Versions

- dumi: 1.0.10
- node:
- npm:
- OS: windows
- Browser:

**Comment by KellenHe** [comment]
发现用官网脚手架生成的demo也运行不起来，能否看下
`---
nav:
  title: Components
  path: /components
---

## Foo

Demo:

```tsx
import React from 'react';
import { Foo } from 'dumi';

export default () => <Foo title="First Demo" />;
```

More skills for writing demo: https://d.umijs.org/guide/demo-principle`

**Comment by xrkffgg** [comment]
脚手架？ yarn create @umijs/dumi-lib ?

**Comment by PeachScript** [comment]
版本太老了，升级到 1.1 试试，如果还有问题再反馈，issue 先关闭了
