### ISSUE TITLE
bug: ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by youngjuning** [umijs/dumi#476]
我把 dumi 部署到 youngjuning.github.io，然后我其他仓库的 github pages 打不开。

https://youngjuning.js.org

https://youngjuning.js.org/wx-promise-pro/

**Comment by xrkffgg** [comment]
```
base: `/wx-promise-pro/`,
publicPath: `/wx-promise-pro/`,
```

**Comment by xrkffgg** [comment]
可以看看这个 https://github.com/umijs/dumi-template

**Comment by youngjuning** [comment]
兄弟，你理解错了，我在youngjuning.github.io 这个仓库部署 dumi。导致我其他项目无法访问，原因是多次重定向 301

**Comment by youngjuning** [comment]
我觉的问题在于dumi对于404的处理有问题

**Comment by xrkffgg** [comment]
你的 wx-promise-pro 是怎么在 io 展示的？我没有在你这个工程看到有分支是对应部署的，那应该是在 io 中的文件夹吗？

那这样的话， io/xx 会和 dumi 的路由有冲突了

**Comment by youngjuning** [comment]
我是在 youngjuning.github.io 部署的 dumi。然后访问我其它项目。发现路由多次重定向。

这个路由多次重定向可以解决吗？确实有部署到 xxx.githib.io 这个需求的 因为我想拿来做博客用

**Comment by xrkffgg** [comment]
可以试试 history 配置其他的看看

**Comment by PeachScript** [comment]
现场还原了吗，访问这两个链接看不到反复重定向的问题了

**Comment by youngjuning** [comment]
卧槽，我复原了一下，竟然又能重新访问了，我先关了，不能访问的话我再来问
