### ISSUE TITLE
使用<code />引入外部demo时，打包时也会把demo代码打包进npm包

### ISSUE THREAD

**Issue by Minfee** [umijs/dumi#481]
### Question
当使用<Code />标签在md文件引入demo的时候，对组件库进行打包，生成的npm包中含有demo的代码及文件夹，请问这个如何在打包时排除出去

**Comment by PeachScript** [comment]
参考：https://docs.npmjs.com/cli/v6/configuring-npm/package-json#files

**Comment by Minfee** [comment]
可以给个案例吗，操作了一下 发现还是会打包

**Comment by PeachScript** [comment]
dumi 的子包可以参考：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/package.json#L6
