### ISSUE TITLE
打包完毕在引入的时候报错

### ISSUE THREAD

**Issue by Minfee** [umijs/dumi#485]
### Question
webstorm的提示import路径是:

import {DynamicList} from "halo-ui-components/dist/src";

使用 import {XXX} from 'halo-ui-components' 之后的报错：
TS7016: Could not find a declaration file for module 'halo-ui-components'. '/Users/minfee/SynologyDrive/Developer/halo-lite-ui/node_modules/halo-ui-components/dist/index.js' implicitly has an 'any' type.   Try `npm install @types/halo-ui-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'halo-ui-components';`

请问如果让提示路径变为正常的import {XXX} from 'halo-ui-components'，以及使用此路径报错该如何消除，谢谢。

**Comment by PeachScript** [comment]
只是类型缺失，tsconofig 加上 declaration 配置给自己的组件库生成类型

**Comment by Minfee** [comment]
已经解决十分感谢
