### ISSUE TITLE
bug: demo 注释不是 yaml 时会解析报错

### ISSUE THREAD

**Issue by mizi-lin** [umijs/dumi#486]
![image](https://user-images.githubusercontent.com/2802841/104278791-20881d00-54e4-11eb-9f48-6845e27f3a57.png)

`node.properties.meta = Object.assign(meta, node.properties.meta);`  其中 meta 是个数组·~~

**Comment by PeachScript** [comment]
meta 为什么会是数组，请提供复现

**Comment by mizi-lin** [comment]
@PeachScript 

找到bug所在，<code src="./abc.example/index.tsx"  />

abc.example/index.tsx 有meta信息，造成错误

![image](https://user-images.githubusercontent.com/2802841/104317167-8db5a580-5518-11eb-9ca9-8664342d7ca3.png)

https://github.com/mizi-lin/dumi-issues/tree/dumi-v1.1.0

**Comment by PeachScript** [comment]
好的，frontmatter 只支持键值对，需要加个异常值检测

**Comment by PeachScript** [comment]
v1.1.3 开始会忽略无效的 frontmatter，issue 关闭
