### ISSUE TITLE
使用dumi配合@umi/fabric进行代码检查，eslintrc.js文件报错

### ISSUE THREAD

**Issue by Minfee** [umijs/dumi#488]
### Question
使用dumi，并且安装@umi/fabric进行代码检查，提供eslint prettier 等配置，但是在eslint的配置文件.eslintrc.js文件中弹出报错，
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: .eslintrc.js.
The file must be included in at least one of the projects provided.
曾经尝试在tsconfig.json文件中加入 "include": ["./**/*", "./.**"]，来避免报错但是会影响打包出来的npm包没有根目录的index.d.ts文件

**Comment by PeachScript** [comment]
eslintignore 掉 `.eslintrc.js`

**Comment by Minfee** [comment]
OK了 非常感谢哈
