### ISSUE TITLE
build后样式类名没有加上

### ISSUE THREAD

**Issue by SmartWrh** [umijs/dumi#495]
.umirc 中配置了 
```
 cssLoader: {
    localsConvention: 'camelCase',
}
```
.fatherrc.ts中配置了
```
cssModules: true,
```

打包过后类似 `AAA-BBB-CCC` 这样得类名全部丢失，请问该如何配置

**Comment by PeachScript** [comment]
dumi 和 father 的配置不互通的，目前只能通过 styles['AAA-BBB-CCC'] 去访问
