### ISSUE TITLE
dumi支不支持Taro？

### ISSUE THREAD

**Issue by l2en** [umijs/dumi#497]
### Question
dumi是否支持类React的Taro编写的组件预览及文档处理？

**Comment by PeachScript** [comment]
目前仅支持 React

**Comment by xiaohuoni** [comment]
@l2en 你可以直接试下，我看 taro 有 react 的组件

**Comment by l2en** [comment]
> @l2en 你可以直接试下，我看 taro 有 react 的组件

现在有个棘手的问题，taro开发的项目都是由@tarojs/cli脚手架创建，也就意味着taro的语法需要通过taro编译，dumi也是通过dumi斌阿姨，目前尝试了确实没找到可以整合这两个的办法。好蛋疼... 大佬目前有没有想开发个插件，能整合一下的。 thx

**Comment by PeachScript** [comment]
目前没有精力和场景做这方面的尝试，如果有需要可以考虑帮 dumi 提供方案，issue 关闭了

**Comment by starWangx** [comment]
同问

**Comment by zengqingzhuang** [comment]
同问
