### ISSUE TITLE
移动端开发真机预览 样式没有响应式

### ISSUE THREAD

**Issue by xxf512** [umijs/dumi#498]
### Question
移动端开发真机预览 样式没有响应式 ，打开是在pc端的样式
![image](https://user-images.githubusercontent.com/26305321/104580970-e4e28400-5698-11eb-8f29-6d3f37dd7774.png)
请问这个问题改怎么解决

**Comment by xiaohuoni** [comment]
这应该就是你自己写的问题吧？比如使用antd mobile组件没有引入 antd mobile 的样式文件

**Comment by ChenYCL** [comment]
同样问题，在pc端预览 1px正常显示，在真机上预览会自动缩放，
![image](https://user-images.githubusercontent.com/25706676/128689047-07cb129f-7f8a-4754-bcd9-8651be3bce74.png)
通过的事yarn site打包之后线上的产物

**Comment by PeachScript** [comment]
响应式方案需要根据项目情况配置，如果不需要响应式也可以关闭，参考文档下半部分：https://d.umijs.org/theme#dumi-theme-mobile
