### ISSUE TITLE
一个大胆的想法，移动端模式下，是否能支持自定义模拟器的路径？

### ISSUE THREAD

**Issue by l2en** [umijs/dumi#500]
### Question
- 出发点：在dumi没完全支持解析各种移动端编码方案（如taro、mpvue...)的情况下，预留支持自定义移动端模拟器（iframe）访问路径的功能，能尽快的让这类场景用上dumi

- 使用：由开发人员自己维护一张模拟器展示路由和dumi路由的映射表

**Comment by xiaohuoni** [comment]
你是说 <Device src="../abc.html" />

**Comment by l2en** [comment]
> 你是说 `<Device src="../abc.html" />`
![iframe路径](https://s3.ax1x.com/2021/01/15/s0DnbR.png)

就是iframe展示引用的URL，因为还没看源码不知道是不是你说的`<Device src="../abc.html" />`。

**Comment by PeachScript** [comment]
下个版本会支持

**Comment by l2en** [comment]
> 下个版本会支持

期待。 请问下个版本什么时候回发布呢 thx

**Comment by PeachScript** [comment]
v1.1.1 已支持，https://d.umijs.org/config/frontmatter#demourl

**Comment by l2en** [comment]
> v1.1.1 已支持，https://d.umijs.org/config/frontmatter#demourl

salute

**Comment by xiaohuoni** [comment]
这不是还加上了吗？（笑脸）

**Comment by l2en** [comment]
> 这不是还是加上了吗？（笑脸）

简直不太太给力，我之前是把Device组件拉出来改造了一下，还是有不完美。 这下官方支持更优美，全面拥抱umi，respect！（致敬）
