### ISSUE TITLE
dumi升级到1.1.1之后 移动端模拟容器主题安装后无法显示

### ISSUE THREAD

**Issue by l2en** [umijs/dumi#502]
### Question
dumi升级到1.1.1之后 移动端模拟容器主题安装后无法显示，操作如下：
![image](https://user-images.githubusercontent.com/33387383/104864251-6bd27d80-5973-11eb-9460-79f59968d5cd.png)
![image](https://user-images.githubusercontent.com/33387383/104864275-7b51c680-5973-11eb-85b0-45a8fb112f69.png)

**Comment by l2en** [comment]
![image](https://user-images.githubusercontent.com/33387383/104865110-1055bf00-5976-11eb-8744-e6cdac85c795.png)
![image](https://user-images.githubusercontent.com/33387383/104865130-22376200-5976-11eb-995d-9a1c94c69d82.png)

**Comment by PeachScript** [comment]
`dumi-theme-mobile@1.0.2` 已修复
