### ISSUE TITLE
bug: 升级dumi1.1.1之后自定义demoUrl未正确显示

### ISSUE THREAD

**Issue by l2en** [umijs/dumi#504]
### Versions

- dumi:1.1.1
- node:14.15.1
- npm:6.14.8
- OS: macos 10.15.7
- Browser: chrome 版本 87.0.4280.141（正式版本） (x86_64)

### Steps to reproduce
升级dumi1.1.1 移动模式下未显示自定义的demoUrl；
![image](https://user-images.githubusercontent.com/33387383/104869207-67609180-5980-11eb-8cbb-770bfae47dea.png)
![image](https://user-images.githubusercontent.com/33387383/104869219-721b2680-5980-11eb-9269-a95b55263e79.png)
![image](https://user-images.githubusercontent.com/33387383/104869257-91b24f00-5980-11eb-8520-158625b2df07.png)

### What is Expected?
希望正确显示demoUrl地址
### What is actually happening?
实际为正确显示，还是按照dumi自动生成的地址展示

**Comment by PeachScript** [comment]
和 #502 重复
