### ISSUE TITLE
导航栏如何添加下拉，非使用nav配置

### ISSUE THREAD

**Issue by EOS1O** [umijs/dumi#506]
### Question
如何在导航栏添加一个带下拉子菜单的选项，下拉的选项不是link，而是可以变换theme的一些选项
### Sample Code
不使用以下配置
{
      title: '更换主题',
      // 可通过如下形式嵌套二级导航菜单，目前暂不支持更多层级嵌套：
      children: [
        { title: 'blueTheme', path: '/components/chart-area?blueTheme' },
        { title: 'vintage', path: '/components/chart-area?vintage' },
      ],
}

**Comment by PeachScript** [comment]
只能配 navs 或者写自定义主题
