### ISSUE TITLE
bug: 文档编辑链接不支持 gitlab subgroups

### ISSUE THREAD

**Issue by fikyair** [umijs/dumi#507]
RT

**Comment by xrkffgg** [comment]
https://github.com/umijs/dumi/blob/14770424efa3906fecaa3a5e4456fb685eceb1c1/packages/preset-dumi/src/utils/getRepoUrl.ts#L7

@PeachScript 转这个是为啥？

**Comment by PeachScript** [comment]
> https://github.com/umijs/dumi/blob/14770424efa3906fecaa3a5e4456fb685eceb1c1/packages/preset-dumi/src/utils/getRepoUrl.ts#L7
> 
> @PeachScript 转这个是为啥？

应该是因为 browse 方法返回的可能包含子路径：https://www.npmjs.com/package/hosted-git-info#methods

**Comment by xrkffgg** [comment]
搞个 priorityUrl ?

**Comment by PeachScript** [comment]
v1.1.4 已支持 subgroups
