### ISSUE TITLE
bug: code block desc failed

### ISSUE THREAD

**Issue by mortalYoung** [umijs/dumi#508]
代码块设置 `desc` 的时候，如果是以反引号开头会报错，看了一下应该是 `js-yaml` 的问题，先把 issue 提出来了，看是 `js-yaml` 解还是 `dumi` 解 :grin:

### Versions

- dumi: v1.1.0
- node: v12.16.2
- npm: v6.14.4
- OS: windows

### Steps to reproduce
1. 随便找一个 code block 片段
2. 设置 desc 为反引号开头，比如  \`I’m\` a profile, I can use \`Markdown\` to write

### What is Expected?

as usual

### What is actually happening?
```bash
end of the stream or a document separator is expected at line 3, column 8:
     desc: `I’m` a profile, I can use `Mark ... 
           ^
YAMLException: end of the stream or a document separator is expected at line 3, column 8:
     desc: `I’m` a profile, I can use `Mark ...
```

**Comment by PeachScript** [comment]
特殊字符要做转义的吧，用 '' 包裹后面的内容

**Comment by mortalYoung** [comment]
> 特殊字符要做包裹的吧，用 '' 包裹后面的内容

嚯，原来如此！那 Close 掉了~ ☺️
