### ISSUE TITLE
改名为 dumi

### ISSUE THREAD

**Issue by afc163** [umijs/dumi#51]
对应 docz，`doc + umi === docu`，本身也是 document 的前缀。

**Comment by chenshuai2144** [comment]
这个单词有点丑。。。
DocU ？

**Comment by afc163** [comment]
- documint 备选

**Comment by PeachScript** [comment]
看了下 docu 在 npm 上已被注册，但已经是 5 年不更新的骨灰包了：https://www.npmjs.com/package/docu

**Comment by afc163** [comment]
备选 `dumi` `fatherify`

**Comment by PeachScript** [comment]
`dumi` +1，读米

**Comment by sorrycc** [comment]
dumi + 1

**Comment by chenshuai2144** [comment]
dumi + 1
