### ISSUE TITLE
feat: 组件api prop 应该始终返回必选属性require

### ISSUE THREAD

**Issue by mini0609** [umijs/dumi#514]
### Description
useApiData 返回的数据在有default值的时候，就不会返回require值了

### Solution
prop如果是require必选属性，那么应该始终返回require属性且值为true

**Comment by mortalYoung** [comment]
貌似 required 值的返回和是否有 default 值之间没有必然的联系，required 值只和该属性是否可选有关。
比如该接口, `className` 不返回 `required` 而 `type` 返回 `required`， 不是很清楚你说的是啥情况 0.0 要不你再具体描述一下或提供一下能够说明问题的 `interface` 😄 
```ts
interface IHelloProps {
  className?: string;
  type: string;
}

```

**Comment by mini0609** [comment]
咦，我刚刚又测试了下，又没问题了😄
