### ISSUE TITLE
如何在 dumi 中使用多个 API TABLE

### ISSUE THREAD

**Issue by cjfff** [umijs/dumi#515]
### Question

如题，比如像 ant-table 一样，某些属性是一个对象的形式，那么此时就需要多个 API TABLE 去展示明细，现在来说，dumi 只会简单显示一个 type/interface 的名称，不太符合预期...

例子请见 https://ant.design/components/table-cn/#API

**Comment by PeachScript** [comment]
export 多个 interface/type，dumi 会依次展示每个 interface/type 的表格

**Comment by woliuCN** [comment]
> 
export 多个 interface/type，dumi 会依次展示每个 interface/type 的表格。试了不行
