### ISSUE TITLE
有没有办法让md不生成路由

### ISSUE THREAD

**Issue by kyo4311** [umijs/dumi#517]
### Question
比如有一个md特别长的，我想用embed引用多个md，但是dumi会给其他几个md也生成了路由。
`
<embed src="./md01/index.md"></embed>
`
`
<embed src="./md02/index.md"></embed>
`
`
<embed src="./md03/index.md"></embed>
`

有没有类似特殊的注解，可以让这个md文件不生成路由

**Comment by PeachScript** [comment]
放入 `.` 开头目录或者 md 文件名本身以 `.` 开头则不会生成路由

**Comment by kyo4311** [comment]
可以，不生成路由了，
但是用了<embed>发现控制台一堆报错。如下：
Warning: validateDOMNesting(...): <h3> cannot appear as a descendant of <p>.

**Comment by xrkffgg** [comment]
<p> 应该换一下

**Comment by xrkffgg** [comment]
因为是 markdown 解析的，会在外层当成一段话，加了 p 标签。

有一个办法可以避免的是 `<div><embed src="xxx"></embed></div>`

@PeachScript 有办法在解析的时候，把 embed 使用 div 么 😂😂

**Comment by PeachScript** [comment]
是需要处理的，在 #524 跟进吧
