### ISSUE TITLE
为什么浏览器装了react devtool调试工具，浏览器打开的时候就会报错

### ISSUE THREAD

**Issue by liyan0411** [umijs/dumi#518]
### Question
uncaught TypeError:Cannot read propertry "forEach" of undefined(react-refresh-runtime.development.js:461)
### Sample Code
``

**Comment by liyan0411** [comment]
> Hello @liyan0411. In order to facilitate location and troubleshooting, we need you to provide a realistic example. You can create a dumi project by clicking [here](https://github.com/umijs/dumi-template) and provide the GitHub warehouse address and reproduce examples.
> 
> 你好 @liyan0411, 为了方便定位和排查问题，我们需要你提供一个重现实例。你可以通过点击 [此处](https://github.com/umijs/dumi-template) 创建一个 dumi 项目并提供 GitHub 仓库地址和重现实例。
>
你好，我这边就是直接初始化的项目，只是我的谷歌浏览器安装了react-devtools 调试工具，其他浏览器可以正常运行，谷歌不能正常运行，卸载react-devtools  调试工具后，即可正常运行。

react-devtools 调试工具版本：v3.XXX

[react-devtools-3.zip](https://github.com/umijs/dumi/files/5878705/react-devtools-3.zip)

**Comment by PeachScript** [comment]
我这里看最新版的 devtools 扩展是 v4.10.1，且本地无法复现你的问题，请从 Chrome 商店下载最新版重试

**Comment by liyan0411** [comment]
> 我这里看最新版的 devtools 扩展是 v4.10.1，且本地无法复现你的问题，请从 Chrome 商店下载最新版重试

网络限制无法到谷歌商店，是否方便发一个安装包呢，谢谢

**Comment by PeachScript** [comment]
抱歉，不方便，可以自行从源码构建：https://github.com/facebook/react/tree/master/packages/react-devtools-extensions

issue 关闭了
