### ISSUE TITLE
dumi-theme-mobile gh-pages 部署后  demo 出不来

### ISSUE THREAD

**Issue by kokiy** [umijs/dumi#519]
### Sample Code

demo: https://kokiy.github.io/react-h5-calendar/calendar
![微信截图_20210127182605](https://user-images.githubusercontent.com/15773714/105978125-24639400-60cd-11eb-991c-7f496ae2b51e.png)

**Comment by kokiy** [comment]
```json
  publicPath: './',
  base: '/react-h5-calendar/',
```
已经配置

**Comment by PeachScript** [comment]
请按照文档配置 publicPath：https://d.umijs.org/guide/faq#deploy-on-github-pages
