### ISSUE TITLE
bug: Do not work with workspaces of yarn berry

### ISSUE THREAD

**Issue by beizhedenglong** [umijs/dumi#528]
### Versions

- dumi: 1.1.0
- node: 13.9.0
- npm:
- OS: macOS 11.0
- Browser:

### Steps to reproduce

clone  this repo(https://github.com/beizhedenglong/react-hooks-lib/commits/yarn2), checkout to yarn2 branch

### What is actually happening?
<img width="921" alt="image" src="https://user-images.githubusercontent.com/12963675/106186310-0ede8f00-61df-11eb-9506-36dadbe9b9ba.png">

**Comment by PeachScript** [comment]
请参考官网指南组织 lerna 项目的文档：https://d.umijs.org/guide/basic#lerna-project
