### ISSUE TITLE
web和mobile的主题能否自由切换？

### ISSUE THREAD

**Issue by zimo888** [umijs/dumi#531]
### Question
我有一个组件库的文档，既有移动端又有web端，想写在不同的nav里面，但是
没找到哪里能切换web和mobile 的主题设置，
好像是整站只能二选一？

希望能在组件预览设置里面，添加加一个可以选择是否展示移动预览框的设置。

**Comment by lbwa** [comment]
可以根据 [文档](https://d.umijs.org/zh-CN/theme/development#%E5%A2%9E%E9%87%8F%E8%87%AA%E5%AE%9A%E4%B9%89) 自定义渲染容器 Previewer，自定义容器中可以定义自己想要的切换逻辑

**Comment by zimo888** [comment]
谢谢，晓得了,我关了。

**Comment by PeachScript** [comment]
@zimo888 `dumi-theme-mobile@1.0.10` 开始支持通过设置 `mobile: false` 的 Markdown frontmatter 关闭当前页面的手机预览框、回到默认状态

但 demo 级别的切换会使得交互逻辑变得非常复杂，如果需要的是 demo 级的、短期内还是只能手动自定义
