### ISSUE TITLE
doc 模式下。组件的示例代码如何默认展开显示呢？

### ISSUE THREAD

**Issue by Turkyden** [umijs/dumi#537]
### Question

请问 doc 模式下，组件的示例代码如何默认展开显示呢？有地方设置的么？

### Sample Code

![image](https://user-images.githubusercontent.com/24560160/106686499-56ad4e00-6605-11eb-8d72-178593347eca.png)

@PeachScript 求助

**Comment by PeachScript** [comment]
https://d.umijs.org/config/frontmatter#defaultshowcode

**Comment by Turkyden** [comment]
感谢
