### ISSUE TITLE
.umi/dumi/demos/index.ts 这个文件会生成的体积非常大，控制台 babel 会发出警告

### ISSUE THREAD

**Issue by tolerance-go** [umijs/dumi#539]
.umi/dumi/demos/index.ts 这个文件会生成的体积非常大，控制台 babel 会发出警告 

```
[BABEL] Note: The code generator has deoptimised the styling of /project/.umi/dumi/demos/index.ts as it exceeds the max of 500KB.
```

_Originally posted by @tolerance-go in https://github.com/umijs/dumi/issues/525#issuecomment-772258161_

**Comment by PeachScript** [comment]
dumi 会将 demo 按组件维度拆分成单独的模块，如果 demos/index.ts 入口模块过大，检查两点：

1. 是不是 demo 引了太多本地文件。组件 demo 作为组件范例，理应尽量从 npm package 里导出内容，而非引用过多的本地文件
2. 适当拆出复杂 demo 为外部 demo。外部 demo 不需要 dumi 单独提取出来，可有效节省体积

**Comment by tolerance-go** [comment]
> dumi 会将 demo 按组件维度拆分成单独的模块，如果 demos/index.ts 入口模块过大，检查两点：
> 
> 1. 是不是 demo 引了太多本地文件。组件 demo 作为组件范例，理应尽量从 npm package 里导出内容，而非引用过多的本地文件
> 2. 适当拆出复杂 demo 为外部 demo。外部 demo 不需要 dumi 单独提取出来，可有效节省体积

我们是都用都 code，官网文档也是这样建议的呀，可以利用 IDE 提示，那只能是先写再移嘛

**Comment by PeachScript** [comment]
第 2 点就是指用 code 标签引入，检查下第 1 点；另外最好能提供复现，否则无法准确判断体积过大的原因

**Comment by tolerance-go** [comment]
> 第 2 点就是指用 code 标签引入，检查下第 1 点；另外最好能提供复现，否则无法准确判断体积过大的原因

理解了，就是这个问题，已经解决了，谢啦
