### ISSUE TITLE
docs: 主题开发 - 自定义正文区域 src/layout.tsx 存在歧义

### ISSUE THREAD

**Issue by MakerTED** [umijs/dumi#542]
发现的问题：[主题开发-自定义正文区域](https://d.umijs.org/zh-CN/theme/development#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%AD%A3%E6%96%87%E5%8C%BA%E5%9F%9F) 小节中描述的例子代码无效。

以下为 dumi 文档中的内容片段：

>自定义正文区域<br>
> 如果只希望控制正文区域的渲染，可以选择包裹默认主题的 layout、控制 layout 的 children 来实现。例如，给正文区域增加一个反馈按钮：
>```
>// src/layout.tsx
>import React from 'react';
>import Layout from 'dumi-theme-default/src/layout';
>export default ({ children, ...props }) => (
>  <Layout {...props}>
>    <>
>      <button>反馈</button>
>      {children}
>    </>
>  </Layout>
>);
>```

### Versions

- dumi:1.0.13
- node:v14.15.4
- npm:6.14.10
- OS:11.1 (20C69)
- Browser:Chrome 88.0.4324.146

### Steps to reproduce

1、使用脚手架初始化项目。
2、在 `src` 目录中创建 `layout.tsx` 文件，并复制例子代码到文件中。
3、启动开发模式，页面中并没有出现反馈按钮。

### What is Expected?

在 `src` 目录中创建 `layout.tsx` 后，在页面中应该出现相应的内容。

### Remark

同样的环境下，创建 `.dumi/theme` 目录的方法是有效的。

**Comment by PeachScript** [comment]
是文档有歧义、并非 bug，`src/layout.tsx` 是主题包的结构，本地主题走 `.dumi/theme`
