### ISSUE TITLE
可以将 README.md 的 nav 名称映射为 README 嘛？

### ISSUE THREAD

**Issue by ystarlongzi** [umijs/dumi#544]
如题，当前 README.md 的一级标题会被转换成 nav 名称

预期，希望可以自定义 README.md 导航的名称，比如改为「介绍」

有尝试在 README.md 配置以下内容，但是未生效

```
---
title: 介绍
nav:
    title: 介绍
---
```

**Comment by PeachScript** [comment]
应该和 README.md 的 fallback 逻辑有关，没走标准的 frontmatter 获取：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/routes/decorator/fallback.ts#L37

cc @xrkffgg

**Comment by xrkffgg** [comment]
这。。。 有人会在仓库的主 READM 里加 
```
---
title: 介绍
nav:
    title: 介绍
---
```
这样 在仓库里 看起来 就很奇怪的

**Comment by xrkffgg** [comment]
我的理解  仓库的 主 README 是对仓库而言的，加一些非标准的
```
---
title: 介绍
nav:
    title: 介绍
---
```

在仓库直接查看会显示 

---
title: 介绍
nav:
    title: 介绍
---

看起来就挺奇怪的。如果你需要在 网站中引用 README 内容，可以使用 embed

**Comment by ystarlongzi** [comment]
@xrkffgg 有道理。我关掉了
