### ISSUE TITLE
bug: 启用 dynamicImport:{} 后，访问带有锚点的 url 时，锚点跳转失效

### ISSUE THREAD

**Issue by MakerTED** [umijs/dumi#545]
问题：

当在配置文件中配置 `dynamicImport:{}` 后，将带有描点的 url 复制到浏览器的新窗口进行访问时，页面渲染完成后没有跳转到描点所在位置。

### Versions

- dumi:1.0.13
- node:v14.15.4
- npm:6.14.10
- OS:11.1 (20C69)
- Browser:Chrome 88.0.4324.146

### Steps to reproduce
1、使用脚手架初始化项目。
2、在 .umirc.ts 文件中添加 `dynamicImport: {}`。
3、创建一个带有标题、且内容较长的 `newfile.md` 文件。
4、运行 `yarn start`，在浏览器中预览 `newfile` 页面。
5、点击页面中的标题，从浏览器地址复制带有锚点的 `url` ，新建浏览器窗口。
6、通过带有锚点的 `url` 在新窗口中预览。
7、【问题复现】页面渲染完成后没有跳转到描点所在位置。

### What is Expected?

在启用了 `dynamicImport:{}` 后，通过带有锚点的 `url` 访问时，可以正常跳转到锚点位置。

### Remark

不设置 `dynamicImport:{}`，锚点跳转是正常的。

**Comment by PeachScript** [comment]
v1.1.15 已修复
