### ISSUE TITLE
feat: API 自动生成组件增加 title 标题 和  @ignore

### ISSUE THREAD

**Issue by jian263994241** [umijs/dumi#546]
目前  API组件会自动生产固定的标题,   这样一个页面里面 多个API的话, 很难看, 不知道谁是谁.   

1. 需要增加 title 自定义

2. API属性定义 希望 增加   @ignore  手动忽略一些定义 ... 

3. 最后 API 组件 或者 把 react-docgen-typescript 的options 放出来  主要需要用 propFilter  自己增加过滤.  或者 useAPIdata 增加相关参数

4.  <API props></API>   可否 透传 API 组件自定义一些 props , 用来扩展 组件逻辑 ?

**Comment by PeachScript** [comment]
v1.1.25 已支持 `apiParser.propFilter` 配置项，参考：https://d.umijs.org/zh-CN/config#apiparser

第 1 点在 #699 跟进，第 3 点可以通过自定义本地主题自行实现 API 组件，实现渲染行为的完全控制：https://d.umijs.org/zh-CN/theme/development
