### ISSUE TITLE
bug: generate .umi temp dir into src

### ISSUE THREAD

**Issue by hustcc** [umijs/dumi#553]
### Versions

"dumi": "^1.1.4",
"dumi-theme-default": "^1.0.4",

- node: 12.x
- npm:
- OS:
- Browser:

### Steps to reproduce

> dumi dev/build

![image](https://user-images.githubusercontent.com/7856674/108449140-ef96c700-729d-11eb-819c-8874aeea7c13.png)

### What is Expected?

do not generate .umi temp dir into src

### What is actually happening?

generate .umi temp dir into src, so before npm publish, I need to rm them, or ignore them in configure file.

**Comment by PeachScript** [comment]
v1.1.6 开始使用根目录的 .umi 作为临时文件夹，issue 关闭

**Comment by hustcc** [comment]
@PeachScript build 下用的 根目录，但是 dev 似乎还是 src 下。 1.1.6 版本，刚刚升级试用。

**Comment by PeachScript** [comment]
@hustcc 感谢反馈，不是空的，里面还有 babel cache，看来得 Umi 层改下了，https://github.com/umijs/umi/blob/master/packages/bundler-utils/src/getBabelOpts.ts#L23，cc @xiaohuoni

**Comment by PeachScript** [comment]
改临时目录会使得 Umi 生态其他工具无法工作，所以该问题暂时只能通过 `.npmignore` 解决，后续进展再同步，refer: https://github.com/umijs/umi/issues/6180
