### ISSUE TITLE
dumi 导入子包时无法启动

### ISSUE THREAD

**Issue by huangbinjie** [umijs/dumi#556]
### Question

当前版本导入 `rootPackage/subpackage` 无法启动

### Sample Code

https://github.com/huangbinjie/dumi-demo

麻烦大佬克隆这个仓库帮忙看看，步骤写在 About 里面了

**Comment by xrkffgg** [comment]
配置文件

**Comment by huangbinjie** [comment]
@xrkffgg 加上配置文件了仍然不行

**Comment by PeachScript** [comment]
src 下没有入口文件，dumi 会认为这不是有效的组件源码目录、放弃软连接和 alias，解法：

1. 创建 `src/index.ts` 入口文件
2. 手动配置 alias 使得子包能解析到

issue 关闭，有问题再反馈

**Comment by xrkffgg** [comment]
`.umirc.js` 这个空的起作用吗？

**Comment by PeachScript** [comment]
> `.umirc.js` 这个空的起作用吗？

不起作用

**Comment by huangbinjie** [comment]
> 创建 src/index.ts 入口文件
手动配置 alias 使得子包能解析到

这俩似乎都不行呀，能否克隆下我提供的仓库帮忙试试？

**Comment by PeachScript** [comment]
你的仓库把 `src/.umi` 临时文件传上来太大了

看了下和入口文件无关，这种情况只能 .umirc.ts 手动配 alias 解决，比如 `alias: { 'dumi-demo/icons': path.join(cwd, 'src/icons') }`；另外需要考虑到，发出去的包用户是否也能这样把 icons 引入进来

**Comment by huangbinjie** [comment]
@PeachScript 感谢大佬，可以了～

l另外，开仓库之前用的最新版 `1.1.0-rc.5` 是可以的，升级到现在的最新版本然后就不行了所有才有这个问题 = =。

这种 break change 应该在 release 或者其他地方体现出来我没注意？
