### ISSUE TITLE
API docs 渲染html层级不符合规范

### ISSUE THREAD

**Issue by wuzhihuafe** [umijs/dumi#557]
### Versions

- dumi: 1.0.13
- node: 12.19.0
- npm: 6.14.8
- OS:
- Browser:

### Steps to reproduce
![image](https://user-images.githubusercontent.com/79357881/108591648-c57bfc80-73a4-11eb-8c8a-47743b1d7a43.png)
![image](https://user-images.githubusercontent.com/79357881/108591664-d6c50900-73a4-11eb-92d2-4c2957672595.png)
![image](https://user-images.githubusercontent.com/79357881/108591686-ea706f80-73a4-11eb-89a4-f7c6f6083400.png)
正常添加一个API标签，渲染出来的html不符合层级规范，会有有警告，p标签下应该包含h标签
### What is Expected?
讲该警告解决

**Comment by wuzhihuafe** [comment]
p标签下不应该包含h标签

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/umijs/dumi/issues/524
