### ISSUE TITLE
markdown的dom标签样式问题

### ISSUE THREAD

**Issue by 93336406** [umijs/dumi#560]
markdown里的dom标签如
```js
<div class="classa classb">...</div>
```
构建到线上后变成了
```js
<div class="classa,classb">...</div>
```
 样式名多个了逗号。本地开发环境是正确的。
如图
![image](https://user-images.githubusercontent.com/23730744/108649883-33393d00-74f9-11eb-8842-a394242e4f4e.png)
![image](https://user-images.githubusercontent.com/23730744/108649895-3cc2a500-74f9-11eb-89cc-421a475599a0.png)

**Comment by PeachScript** [comment]
v1.1.6 已修复
