### ISSUE TITLE
bug: Umi 项目集成模式下，当 umirc.ts 文件中包含 routes 时，执行 umi build --dumi 时报错

### ISSUE THREAD

**Issue by MakerTED** [umijs/dumi#561]
报错内容如下：

```
ENOENT: no such file or directory, open '/Volumes/data/Users/user/umi-app/@/pages/index'
```

### Versions

- "umi": "^3.3.7",
- "@umijs/preset-dumi": "^1.1.4"
- node:v14.15.4
- npm:6.14.10
- OS:11.1 (20C69)
- Browser:Chrome 88.0.4324.146

### Steps to reproduce

1、使用 umi 脚手架初始化项目。
2、添加 @umijs/preset-dumi 到 devDependencies 中。
3、执行 yarn umi build --dumi 时报错。

### What is Expected?

当原有的 umi 项目中配置了 routes 信息时，也可以正常的使用 Umi 项目集成模式。

### Remark

当删除 umirc.ts 文件中 routes 节点后可正常打包。

**Comment by PeachScript** [comment]
v1.0.13 还没有集成模式吧

**Comment by MakerTED** [comment]
> v1.0.13 还没有集成模式吧

写错了，是使用的 "@umijs/preset-dumi": "^1.1.4"

**Comment by Turkyden** [comment]
同问？有没有集成模式的案例呢？

**Comment by cike8899** [comment]
`yarn umi build --dumi ` 我也遇到了同样的问题，有在解决吗？ @PeachScript

**Comment by PeachScript** [comment]
v1.1.17 已修复
