### ISSUE TITLE
feat: 文档编辑链接希望能够控制是否使用 https

### ISSUE THREAD

**Issue by eleven-net-cn** [umijs/dumi#562]
当前文档编辑链接只能跳往 https 的链接，但是企业的 gitlab 一般都会限制内网访问，运维也不愿意配置 https 访问，建议提供参数控制使用 http 链接访问。

**Comment by eleven-net-cn** [comment]
![image](https://user-images.githubusercontent.com/20358391/111723209-26143180-889e-11eb-8c5b-d9272df0e041.png)

**Comment by xrkffgg** [comment]
有些 gitlab 确实是 http 的。。。

**Comment by ppbl** [comment]
> 有些 gitlab 确实是 http 的。。。

在这个问题下我补充一个问题，能顺便优化下吗？😅

比如我们公司的 gitlab 链接是这样的：
http://domain/xxx/xxx/xxx-utils.git

可是目前出来的地址是
https://domain/xxx/xxx

少了一块，因为后面只匹配了 $1$2~

**Comment by PeachScript** [comment]
@ppbl 自定义域名要手动指定一下 `repository.platform`，参考这个 PR：https://github.com/umijs/dumi/pull/461/files#diff-f839470d0a0c1fe221f1488b4996ec127c17946add5c54e8b2a38d66c09687deR31

文档里这个配置的描述缺失了

**Comment by PeachScript** [comment]
v1.1.10 已包含 PR 的内容
