### ISSUE TITLE
dumi 文档中的 Tree 是怎样嵌入的？

### ISSUE THREAD

**Issue by eleven-net-cn** [umijs/dumi#563]
我注意到 dumi 的文档中嵌入了 Tree，效果很炫酷，但是查找一圈没发现是怎样生效的。当我在文档中嵌入时，会直接报错。请问我应该怎样使用它？

![image](https://user-images.githubusercontent.com/20358391/108824847-2c93ee00-75fd-11eb-8977-0b135dc54b3b.png)

![image](https://user-images.githubusercontent.com/20358391/108824887-3d446400-75fd-11eb-91ca-14e077d44ec4.png)

**Comment by xrkffgg** [comment]
https://github.com/umijs/dumi/tree/master/.dumi/theme/builtins

**Comment by eleven-net-cn** [comment]
> https://github.com/umijs/dumi/tree/master/.dumi/theme/builtins

我需要在根目录新建 .dumi 文件夹，将这些主题文件复制进去么？

**Comment by xrkffgg** [comment]
你是想在自己项目里用？

**Comment by eleven-net-cn** [comment]
> 你是想在自己项目里用？

是用 dumi 创建、编译的文档项目，想在里面使用 Tree

**Comment by xrkffgg** [comment]
你先直接复制.dumi 吧，然后使用和 md 一样写法。

@PeachScript Tree 移进去？

**Comment by eleven-net-cn** [comment]
直接复制放到根目录，可以生效了，3Q

**Comment by PeachScript** [comment]
> 你先直接复制.dumi 吧，然后使用和 md 一样写法。
> 
> @PeachScript Tree 移进去？

感觉语法有待优化，ul > li 写得我有点累，所以一直没挪进 theme 里…
