### ISSUE TITLE
bug: 当 url 以 / 结尾时，页面脚部无法显示

### ISSUE THREAD

**Issue by MakerTED** [umijs/dumi#564]
如访问 `https://umijs.org/zh-CN/guide/boost-compile-speed/` 时，页面脚部 `__dumi-default-layout-footer-meta` 就无法显示。

### Versions

- dumi: ^1.1.4

**Comment by PeachScript** [comment]
修复已提交，这周内发版

**Comment by PeachScript** [comment]
试试 v1.1.5，issue 先关了，有问题再反馈
