### ISSUE TITLE
docs下文件夹会自动生成导航栏

### ISSUE THREAD

**Issue by Erchoc** [umijs/dumi#565]
### Question
`mode` 为`site` 时，`docs` 目录下的文件夹会被渲染为 `navs` 导航栏，能否将这一约束去掉？

否则我在 `config.js` 中再定义一次 `navs`，就会出现重复导航栏问题，如图。

### Sample Code
![image](https://user-images.githubusercontent.com/19908809/108847583-d635a800-761a-11eb-82a5-dfe352e60b05.png)

**Comment by Erchoc** [comment]
![image](https://user-images.githubusercontent.com/19908809/108848578-1f3a2c00-761c-11eb-92ca-fa73af31720b.png)

此处为中英文切换时，控制台的报错

**Comment by Erchoc** [comment]
中英文 navs 字段不要设置 null 元素即可关闭约定的目录生成导航，文档描述不太清楚：
![image](https://user-images.githubusercontent.com/19908809/108849896-a50aa700-761d-11eb-8257-10d755b74592.png)

**Comment by PeachScript** [comment]
可以一起优化文档，issue 关闭
