### ISSUE TITLE
bug: IE无法打开生成的文档

### ISSUE THREAD

**Issue by xyx650** [umijs/dumi#566]
### Versions

- dumi: 1.0.13 and 1.1.4(lastest)
- node: 14.15.4
- npm: 6.14.10
- OS: Macos 11.2.1 and windows 10
- Browser: IE 11

### Steps to reproduce
- 根据 dumi 官方指南运行 yarn create @umijs/dumi-lib
- .umirc.ts 文件中添加 targets: { ie: 9 } （targets: { ie: 10 } 和targets: { ie: 11 }均有尝试），yarn start 启动开发环境

+ yarn doc:build 打包文档
+ 部署到服务器浏览打包后的文档

### What is Expected?

umi 官网表明 IE8 及以下浏览器无法使用，按理解是应该支持 IE9~11，希望可以给予支持

### What is actually happening?
- 访问 http://localhost:8000，现代浏览器一切正常（开发环境）
- 使用 win10 自带 IE11 打开，文档首页正常，切换至 Foo 后页面空白，控制台报错。把 src/Foo/index.md 文件中引入代码的部分(\`\`\`tsx    code here    \`\`\`)去掉后可以正常访问

```SCRIPT438: 对象不支持“remove”属性或方法```
```foo (20658,3)```
```The above error occurred in the <Previewer> component:```
    ```in Previewer (at Foo/index.md:20)```
    ```in Unknown (created by Context.Consumer)```
    ```in Route (created by Context.Consumer)```
    ```in Switch (created by Context.Consumer)```
    ```in component (created by Context.Consumer)```
    ```in div (at layout.tsx:94)```
    ```in div (at layout.tsx:70)```
    ```in Layout (created by Context.Consumer)```
    ```in OuterLayout (created by Context.Consumer)```
    ```in Route (created by RouterComponent)```
    ```in Switch (created by RouterComponent)```
    ```in Router (created by RouterComponent)```
    ```in RouterComponent```

```Consider adding an error boundary to your tree to customize error handling behavior.```
```Visit https://fb.me/react-error-boundaries to learn more about error boundaries.```
```SCRIPT438: 对象不支持“remove”属性或方法```
```react-dom.development.js (11102,1)```

+ 服务器预览报错基本一致

**Comment by xyx650** [comment]
@PeachScript 刚开始用dumi，还在了解阶段，现在就提 PR 勉强了😂😂

**Comment by PeachScript** [comment]
@xyx650 [`ChildNode.remove`](https://caniuse.com/childnode-remove) 是 DOM API，babel 不会处理 polyfill，可以手动处理下：https://stackoverflow.com/a/43756520

dumi 没有做过 IE 的兼容性测试，不确定是否存在其他问题；如果你手动处理后能够运行，欢迎给 dumi 文档提个 FAQ，可以帮助其他有需要的人

**Comment by xyx650** [comment]
@PeachScript element-remove 和 babel-polyfill 都试过了，没有效果

**Comment by xyx650** [comment]
经多方验证和@PeachScript 的指引，参考 https://stackoverflow.com/a/43756520 的方案，在 .umirc.ts 文件里面 加入
```javascript
polyfill: {
    imports: [
      'element-remove',
      'babel-polyfill'
    ]
  }
```
两个 polyfill 缺一不可，问题解决。
感谢@PeachScript

**Comment by PeachScript** [comment]
@xyx650 👍，有空可以提个 PR 帮 dumi 文档 FAQ 里加一条

**Comment by xyx650** [comment]
@PeachScript OK， 晚些时候提个 PR

**Comment by shike-me** [comment]
配置浏览器兼容版本，应该就可以了吧？


export default {
  targets: {
    ie: 11,
  },
};
