### ISSUE TITLE
请问下封装组件时，网络请求如何处理？

### ISSUE THREAD

**Issue by quicklearning123** [umijs/dumi#583]
我这边有一个ant design pro项目，想把一些页面放到内部私有的公共组件库里面，比如用户管理。这样其他项目直接用。所以需要包含网络请求，权限控制等逻辑。有几块不太清楚怎么处理，请教各位大佬们？

1. request
import from umi会使用主项目的app.tsx设置的拦截器吗？
npm run dev时，如何设置proxy

2. dva:
connect,model, service 三部分代码，在组件中如何处理？

3.<Access> 
似乎是根据plugin-access+access.ts处理的，有部分是dev依赖，组件中如何引入？

**Comment by PeachScript** [comment]
业务逻辑耦合过重不建议做组件库，组件库应该是相对独立、不依赖开发框架（比如 umi）、暴露接口供外部初始化的场景下使用的，你描述的场景拆不出来，如果想页面在多项目复用建议看下 git submodules，可能有所帮助

该 issue 不在组件库讨论范围，issue 关闭

**Comment by hellojqk** [comment]
@quicklearning123  同样的需求，请问您最后怎样处理的？我的项目增加里一些权限组件供业务团队使用，其中也使用了dva
