### ISSUE TITLE
bug: API的exports生成API文档报错

### ISSUE THREAD

**Issue by southorange1228** [umijs/dumi#585]
### Versions

- dumi:1.1.7
- node: v12.16.1
- npm: v6.13.4
- OS: macos big sur 11.0.1
- Browser: chrome 88.0.4324.192（正式版本） (x86_64)

### Steps to reproduce
1. npx @umijs/create-dumi-lib    新建一个项目
2. 修改 `Foo/index.tsx` 
```tsx
import React from 'react';

export interface A {
    a: string
}

export interface B {
    b: string
}

export default ({ title }: { title: string }) => <h1>{title}</h1>;

```
3. 修改 `Foo/index.md`

```txt
<!-- 有default 和删除default的情况相同 -->
<API exports='["default","A","B"]'></API> 
```

4. npm run start启动服务 选中Foo组件的页面。报错

![image](https://user-images.githubusercontent.com/32590310/110466963-6262c780-8111-11eb-9012-91edeb764341.png)

**Comment by uujx** [comment]
Same here.

**Comment by crecreek** [comment]
+1

**Comment by Risker-C** [comment]
+1

**Comment by hbxks18** [comment]
+1

**Comment by heuuLZP** [comment]
@crecreek @hbxks18 @southorange1228 @Risker-C @uujx 
不需要使用 exports, 像下面这样即可

```
interface A {
  /**
   * 属性描述
   * @description   描述
   * @default          -
   */
  a: string
}

export const A = (props:A) => {
  return null;
}
```

**Comment by southorange1228** [comment]
> @crecreek @hbxks18 @southorange1228 @Risker-C @uujx
> 不需要使用 exports, 像下面这样即可
> 
> ```
> interface A {
>   /**
>    * 属性描述
>    * @description   描述
>    * @default          -
>    */
>   a: string
> }
> 
> export const A = (props:A) => {
>   return null;
> }
> ```

你这种写法是针对Props不需要导出的情况，Props必须要导出的情况下没有意义

**Comment by jetzeng193** [comment]
本来我的组件库只有源码，都是copy使用的，来了新同事，还是规范下组件库，于是father-build打包，各种配置头都搞大，打包搞定了，文档又是个大问题，总不能手动编辑嘛，于是找到了dumi，又是各种配置，头再一次大。顺利实现了demo后，API部分同样问题，文档实在太糙完全搞不通，本想参考antd源码的，但是哈它居然是手写（不能完全肯定，但是在源码里确实像手写的痕迹）的，跟踪调试（具体参考useApiData）发现实现方式应该是这样的：

对于需要形成API文档的定义要以包含组件的方式导出（这个现在才发现文档其实说得还是很清楚的），这里我叫“API.tsx”嘛，内容如下

interface IBirthplace {
  province: string;
  city:string;
  country:string
}

/**
* 这里的注释不能导出 
* @description 这样也没有
*/
interface IProps<T> {
  /**注释 */
  name: string;
  /** 这里我希望能够导航到#ISomeProp，但是不得行，实现方法暂不知 */
  birthplace: IBirthplace;
  /** value */
  value: T;
}
// 以上定义是事先完成的，这里只该是import

// 接下来是导出定义的时候了

export const IProps = <T,>(props: IProps<T>) => <></>;

export const IBirthplace = (props: IBirthplace) => <></>;

//当然你也可以export default，这个文档中名称只能显示API
//export default (props:IProps)=><></>

在md中
## API
《API src='path/to/API.tsx' exports='["IProps","IBirthplace"]' /》

上图
![image](https://user-images.githubusercontent.com/12954172/114214475-e91bf600-9996-11eb-92e4-5e89fd3748bc.png)

到此流程总算是基本搞定，接下来就是要完成各种组件的demo和API，头实在大，想想真佩服阿里的前端工程师，而我是真不适合搞前端，没办法，没人搞啊
第一次github上评论给你了

**Comment by southorange1228** [comment]
> 第一次github上评论，认真点哈
> 
> 本来我的组件库只有源码，都是copy使用的，来了新同事，还是规范下组件库，于是father-build打包，各种配置头都搞大，打包搞定了，文档又是个大问题，总不能手动编辑嘛，于是找到了dumi，又是各种配置，头再一次大。顺利实现了demo后，API部分同样问题，文档实在太糙完全搞不通，本想参考antd源码的，但是哈它居然是手写（不能完全肯定，但是在源码里确实像手写的痕迹）的，跟踪调试（具体参考useApiData）发现实现方式应该是这样的：
> 
> 对于需要形成API文档的定义要以组件的方式导出（这点到现在才发现文档其实说得还是很清楚的），这里我叫“API.tsx”嘛，内容如下
> 
> interface IBirthplace {
> province: string;
> city:string;
> country:string
> }
> 
> /**
> 
> * 这里的注释不能导出
> * @description 这样也没有
>   */
>   interface IProps {
>   /__注释 _/
>   name: string;
>   /__ 这里我希望能够导航到#IBirthplace，但是不得行，实现方法暂不知 _/
>   birthplace: IBirthplace;
>   /__ value */
>   value: T;
>   }
>   // 以上定义是事先完成的，这里只该是import
> 
> // 接下来是导出定义的时候了
> 
> export const IProps = <T,>(props: IProps) => <></>;
> 
> export const IBirthplace = (props: IBirthplace) => <></>;
> 
> //当然你也可以export default，这个文档中名称只能显示API
> //export default (props:IProps)=><></>
> 
> 在md中
> 
> ## API
> 《API src='path/to/API.tsx' exports='["IProps","IBirthplace"]' /》
> 
> 上图
> ![image](https://user-images.githubusercontent.com/12954172/114214475-e91bf600-9996-11eb-92e4-5e89fd3748bc.png)
> 
> 到此流程总算是基本搞定，接下来就是要完成各种组件的demo和API，头实在大，想想真佩服阿里的前端工程师，而我是真不适合搞前端，没办法，没人搞啊

你这种取巧的办法确实可以实现。但是有个问题就是会引入很多无用代码，组件库代码量小的时候都觉得无所谓，体量一旦上升，就不是很合适了。不过大佬还是很厉害的，居然琢磨出了这种办法：）

而且从官方文档说明来看，应该是可以直接支持export出的属性，而不需要采用编写一些无用代码的，个人理解应该还是dumi本身的bug

**Comment by ChenYCL** [comment]
同无法控制输出API ，不仅导出了default 还有其它enum之类的

**Comment by ChenYCL** [comment]
有办法控制子标题么，zhi yao只要default h3标签全部都是多余的
![image](https://user-images.githubusercontent.com/25706676/114535902-1dd3ca00-9c83-11eb-8a00-408e2eee55e0.png)

源码解析内容
![image](https://user-images.githubusercontent.com/25706676/114535980-3643e480-9c83-11eb-98f1-0c711fbab0cf.png)

**Comment by ONEWateR** [comment]
+1

这个问题到现在还没解决

**Comment by tiyunchen** [comment]
+1 现在也是，感觉要沦为kpi项目了

**Comment by DevXiaolan** [comment]
关注

**Comment by ChenYCL** [comment]
我们自己写了个api生成器， 读的types.ts  单文件 自动生成，没用API了 太多二级标签乱的很

**Comment by southorange1228** [comment]
这个issue多半是不会管了，各位自行想办法解决吧。 - -

**Comment by BarrySong97** [comment]
。。。。。这过了多久了，不管了是吧

**Comment by tiyunchen** [comment]
> 。。。。。这过了多久了，不管了是吧

之前dumi的钉钉群里面有说是ts的版本问题，说是ts版本太新，我后来也没去试了

**Comment by southorange1228** [comment]
> > 。。。。。这过了多久了，不管了是吧
> 
> 之前dumi的钉钉群里面有说是ts的版本问题，说是ts版本太新，我后来也没去试了

简单看了下源码，不是TS版本的问题。读jsdoc有问题导致有些数据加载不进去。最后变成了undefined

**Comment by PeachScript** [comment]
底层 API 解析库只支持解析 React Component 的导出，也就是说：

```tsx
// 可以识别
export const A: React.FC = () => null;

// 不能识别
export const B = 1;
export interface C {};
export type D = boolean;
```

**Comment by PeachScript** [comment]
TypeScript 4.3+ 版本 v1.1.22 开始已经支持了，refer: https://github.com/umijs/dumi/issues/732#issuecomment-870200685
