### ISSUE TITLE
dumi通过father-build构建打包能修改打包文件夹名字吗

### ISSUE THREAD

**Issue by yansj2016** [umijs/dumi#587]

**Comment by xrkffgg** [comment]
https://github.com/umijs/father#config

**Comment by yansj2016** [comment]
npm run build默认使用father-build命令打包，完成之后输出文件夹一直是dist，package.json和.fatherrc.ts配置如下：
"scripts": {
    "start": "dumi dev",
    "docs:build": "dumi build",
    "docs:deploy": "gh-pages -d dist_production",
    "build": "father-build",
    "deploy": "npm run docs:build && npm run docs:deploy",
    "release": "npm run build && npm publish",
    "prettier": "prettier --write \"**/*.{js,jsx,tsx,ts,less,md,json}\"",
    "test": "umi-test",
    "test:coverage": "umi-test --coverage"
  },


export default {
  disableTypeCheck: true,
  cjs: 'babel',
  esm: 'babel',
  umd: {
    name: 'frontend',
    sourcemap: true,
    globals: {
      react: 'React',
      antd: 'antd',
    },
  },
  extraBabelPlugins: [
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }],
  ],
  entry: 'src/index.ts',
  doc: {
    themeConfig: { mode: 'dark' },
    base: '/dist_production'
  },
};

**Comment by xrkffgg** [comment]
father 配置里 试试指定输出文件夹

**Comment by yansj2016** [comment]
> father 配置里 试试指定输出文件夹
大佬，我在father配置文档上没看到输出文件夹相关的配置，源码里面dist是不是写死了
![image](https://user-images.githubusercontent.com/24471719/111100535-efc77100-8582-11eb-9327-5bd11bc7b527.png)

**Comment by xrkffgg** [comment]
这个是清除的，我看了下 rollup 的 output 没有对应的 dir，应该是不支持。

**Comment by yansj2016** [comment]
> 这个是清除的，我看了下 rollup 的 output 没有对应的 dir，应该是不支持。

哦，谢谢大佬，这个修改打包输出文件夹名字的配置后续有计划会加上吗？

**Comment by xrkffgg** [comment]
这要看后续 father 的计划

**Comment by PeachScript** [comment]
目前不支持定制，社区有朋友提了 PR 在跟进这个问题 https://github.com/umijs/father/pull/308
