### ISSUE TITLE
dumi 可以通过meuns 配置项配置出三级菜单吗？

### ISSUE THREAD

**Issue by quanzhiyuan** [umijs/dumi#588]
### Question
dumi 可以通过meuns 配置项配置出三级菜单吗？
### Sample Code
    '/菜单': [
      {
        title: '一级菜单',
        children: 
        [
          {
            title: '二级菜单',
            children: [
              'test.md',  // 自动生成三级菜单
            ]
          }
        ]
      }
    ]

**Comment by PeachScript** [comment]
目前没有支持三级的计划，有需求可以扩展自定义主题实现

**Comment by Estherjing** [comment]
请问自定义主题有没有相关demo，求指导
