### ISSUE TITLE
bug: 非 umi 项目中使用 dumi，修改 APP_ROOT 后仍然加载 src/app.tsx

### ISSUE THREAD

**Issue by onlyling** [umijs/dumi#591]
### Versions

- dumi:^1.1.9
- node:v12.14.1
- npm:7.6.0
- yarn:1.22.5
- OS:mac OS 10.15.7 (19H524)
- Browser:Chrome 89.0.4389.72

### Steps to reproduce
package.json
```json
{
  "scripts": {
    "dumi": "cross-env APP_ROOT=dumi dumi dev",
    "dumi-build": "cross-env APP_ROOT=dumi dumi build"
  },
  "devDependencies": {
    "core-js": "^3.9.1",
    "cross-env": "^7.0.3",
    "dumi": "^1.1.9",
    "umi-plugin-react-native": "^0.4.0"
  }
}
```

参考仓库[onlyling/xant](https://github.com/onlyling/xant)

```
|-- config
|--|-- config.ts
|-- dumi
|--|-- docs
|--|--|-- index.md
|-- src
|--|-- app.tsx

## yarn dumi 
## 控制台没有任何报错

## 打开浏览器
## ReferenceError: require is not defined
```

ReferenceError: require is not defined
Module../node_modules/unstated-next/dist/unstated-next.mjs
./src/unstated-next.tsx:13
  10 | 	useContainer: () => Value
  11 | }
  12 | 
  13 | export function createContainer<Value, State = void>(
  14 | 	useHook: (initialState?: State) => Value,
  15 | ): Container<Value, State> {
  16 | 	let Context = React.createContext<Value | null>(null)

结合 [非 umi 项目启动 dumi 后提示 Error: register failed, invalid key xx from plugin src/app.ts](https://d.umijs.org/zh-CN/guide/faq#%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E5%90%AF%E5%8A%A8-dumi-%E5%90%8E%E6%8F%90%E7%A4%BA-error-register-failed-invalid-key-xx-from-plugin-srcappts) 的 FQ，不像是配置、使用方式的问题。

使用参考：
- [如何在 cra 等非 umi 项目中使用 dumi？](https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F)
- [xiaohuoni/dumi-demo-cra](https://github.com/xiaohuoni/dumi-demo-cra)

### What is Expected?

正常的渲染出 `dumi/docs/index.md` 文档

### What is actually happening?

修改了 `APP_ROOT ` 的路径，实际还是去加载了 `src/app.tsx` 文件。

`dumi` 文件夹下的 `node_modules` 无限嵌套？

<img width="255" alt="WX20210318-144657@2x" src="https://user-images.githubusercontent.com/9999765/111584440-d3cd0500-87f8-11eb-909e-6758af6cb379.png">

**Comment by xiaohuoni** [comment]
为什么不给一个可以直接复现的 demo！！

**Comment by xiaohuoni** [comment]
[umi-test.zip](https://github.com/umijs/dumi/files/6162710/umi-test.zip)
在最简 demo 中， APP_ROOT 表现正常。

**Comment by onlyling** [comment]
> 为什么不给一个可以直接复现的 demo！！

[demo](https://github.com/onlyling/xant/tree/doc)

[变更](https://github.com/onlyling/xant/commit/0d8f924992b71d0710024c3558a271157cae86f2)

**Comment by xiaohuoni** [comment]
> > 为什么不给一个可以直接复现的 demo！！
> 
> [demo](https://github.com/onlyling/xant/tree/doc)
> 
> [变更](https://github.com/onlyling/xant/commit/0d8f924992b71d0710024c3558a271157cae86f2)

我看看

**Comment by onlyling** [comment]
> > > 为什么不给一个可以直接复现的 demo！！
> > 
> > 
> > [demo](https://github.com/onlyling/xant/tree/doc)
> > [变更](https://github.com/onlyling/xant/commit/0d8f924992b71d0710024c3558a271157cae86f2)
> 
> 我看看
> ![image](https://user-images.githubusercontent.com/11746742/111741999-5d94d500-88c2-11eb-8943-e9548a94e2d6.png)
> 
> @onlyling 你给的 demo 可以运行

有点奇怪，我运行后就是这样的。

打开 `http://localhost:8000` 就报错。 

<img width="464" alt="WX20210320-230703@2x" src="https://user-images.githubusercontent.com/9999765/111874628-05002d80-89d1-11eb-95db-568b82904b0f.png">

![FireShot Capture 012 -  - localhost](https://user-images.githubusercontent.com/9999765/111874651-1d704800-89d1-11eb-9f36-29bc9d3f33e2.png)

**Comment by onlyling** [comment]
大概、可能找到问题了。

目前猜测是动态生成的依赖错误，莫名其妙就找到项目根目里面的 `index.js` 文件。重命名后，控制台出现错误。

```
Failed to compile with 1 errors 

This relative module was not found:

* ../../../../../.. in ./node_modules/@umijs/preset-dumi/lib/theme/hooks/useSearch.js
```

清除 `dumi/.umi` 文件夹，重新开始，浏览器能访问。

把项目根目录 `index.js` 文件重命名回来，重新开始，浏览器能访问。
@xiaohuoni
