### ISSUE TITLE
bug: raw-code-loader 加载 JSON 文件会报错

### ISSUE THREAD

**Issue by EWL0829** [umijs/dumi#592]
### Question
dumi-raw-code-loader 不能识别JSON文件吗？

### Sample Code
我的demo中引用的一个组件，使用了一个json格式的颜色配置，大致如下
```
{
  "white": "#fff",
  "black": "#000"
}
```

执行  ```yarn start```  之后会报错，内容如下：

![image](https://user-images.githubusercontent.com/28865408/111603766-a2136880-880f-11eb-8cc8-d026923ba470.png)

**Comment by PeachScript** [comment]
v1.1.10 已修复
