### ISSUE TITLE
请问项目里的Tree是怎么支持的 markdown

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#594]
![image](https://user-images.githubusercontent.com/25706676/111614747-eb1cea00-881a-11eb-96e7-500dd7738a1c.png)

**Comment by lbwa** [comment]
直接在 markdown 里面写jsx，参考原始记录即可 https://raw.githubusercontent.com/umijs/dumi/master/docs/guide/basic.zh-CN.md

**Comment by PeachScript** [comment]
dumi 官网自定义了一个组件，后面会放入默认主题里：https://github.com/umijs/dumi/blob/master/.dumi/theme/builtins/Tree.tsx

**Comment by ChenYCL** [comment]
原来如此,我是抽离这个项目的模版,主题是dumi搭建吧,多了多包 一键发包操作https://github.com/ant-design/pro-components

dumi啥时候能做一个这样的模版库就好了
