### ISSUE TITLE
feat: 新增 Tree 内置组件

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#599]
### Description

dumi 官网自定义的 `Tree` 组件比较受用户欢迎、且能在 GitHub 上降级渲染为无序列表，在用户群以及 #563 #594 都有提到，是时候迁移为 dumi 默认主题的内置组件了

### Solution

1. 目前 dumi 官网的 `Tree` 是基于 antd 实现的，如果直接内置、在未基于 antd 的组件库中使用 dumi 时，会被 antd 的全局样式污染，故需要从 antd 的 `Tree` 组件迁移到 [rc-tree](https://github.com/react-component/tree) 实现
2. 补充测试用例

**Comment by arleyGuoLei** [comment]
N个文件夹的项目 一层一层的 ul > li 写的我有点头大，官方有提供啥工具生成代码吗

**Comment by PeachScript** [comment]
没有…你有兴趣的话可以写个 CodeSandbox 然后放 dumi 文档里 👀

ul > li 的设计是为了使得在 GitHub 上能够降级阅读
