### ISSUE TITLE
bug: 渲染Tex公式

### ISSUE THREAD

**Issue by HerbertHe** [umijs/dumi#600]
### Versions

- dumi: 1.0.13
- node: v12.19.0
- npm: 6.14.8
- OS: Windows 10
- Browser: Edge chromium

### Steps to reproduce

- 根号渲染问题

示例如下

```latex
$$
I = I_1 + I_2 + 2\sqrt{I_1I_2}\cos\delta
$$
```

KaTex官方渲染结果

![image](https://user-images.githubusercontent.com/30955264/112082966-16fddf80-8b3b-11eb-8a6b-cd31912ab156.png)

但是在dumi中无根号

![image](https://user-images.githubusercontent.com/30955264/112083016-309f2700-8b3b-11eb-9d39-a8ac0a29486a.png)

- 公式块输入无法热更新

> 公式块输入之后, 会导致整个文档渲染失败, 可能是路由的问题?

```latex
$$
balabala here!
$$
```
这个bug不是很好复现, 偶尔会出现这个情况, 并没有找到具体原因在哪

### What is Expected?

渲染正常

**Comment by HerbertHe** [comment]
实例地址: [visible-physics](https://github.com/HerbertHe/visible-physics)

问题部分: [光的干涉](https://github.com/HerbertHe/visible-physics/blob/main/src/interference-of-light/index.md#%E6%B3%A2%E7%9A%84%E5%8F%A0%E5%8A%A0%E5%8E%9F%E7%90%86)

复现步骤:

```bash
yarn

yarn start
```

**Comment by xrkffgg** [comment]
### Mark

![87B6BF51-4B66-4859-B275-9C3D85EF7E6F](https://user-images.githubusercontent.com/29775873/112784660-d0513d80-9084-11eb-90a3-82d7675b428d.png)
