### ISSUE TITLE
bug: 非根部署无效的base配置项

### ISSUE THREAD

**Issue by HerbertHe** [umijs/dumi#603]
### Versions

- dumi: 1.0.13
- node: v12.19.0
- npm: 6.14.8
- OS: Win10
- Browser: Edge chromium

### Steps to reproduce

- 直接dumi命令行工具生成模板

- 修改`.umirc.ts`

```js
base: '/aaaa'
```

- 执行`npm run docs:build`

- 本地启动静态服务器访问`localhost:端口/aaaa`，就会发现白屏的现象！

### What is Expected?

经过对产物的研究，发现问题在默认的`index.html`生成

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"
    />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png"
    />
    <link rel="stylesheet" href="/umi.css" />
    <script>
      window.routerBase = "/visible-physics";
    </script>
    <script>
      //! umi version: 3.4.3
    </script>
    <script>
      !(function () {
        var e = localStorage.getItem("dumi:prefers-color"),
          t = window.matchMedia("(prefers-color-scheme: dark)").matches,
          r = ["light", "dark", "auto"];
        document.documentElement.setAttribute(
          "data-prefers-color",
          e === r[2] ? (t ? r[1] : r[0]) : r.includes(e) ? e : r[0]
        );
      })();
    </script>
  </head>
  <body>
    <div id="root"></div>

    <script src="/umi.js"></script>
  </body>
</html>
```

上面引入`umi.css`和`umi.js`的地址有问题，首次加载是访问根目录的，对于非根部署并不成立。在部署GitHub pages的子文档上有很大的影响。

调试截图：

![image](https://user-images.githubusercontent.com/30955264/112151547-32e29f00-8b96-11eb-84f9-26494cfe843c.png)

### What is actually happening?

正常在非根路径部署。

**Comment by PeachScript** [comment]
除了 `base` 还要配置 `publicPath`，详见文档：https://d.umijs.org/zh-CN/guide/faq#%E9%83%A8%E7%BD%B2%E5%88%B0-github-pages

**Comment by HerbertHe** [comment]
> 除了 `base` 还要配置 `publicPath`，详见文档：https://d.umijs.org/zh-CN/guide/faq#%E9%83%A8%E7%BD%B2%E5%88%B0-github-pages

文档是不是可以优化一下非根部署和GitHub Pages这两个问题为一个？上面的非根部署配置base，可能也会造成非GitHub Pages场景下无必要的issue。
