### ISSUE TITLE
umi加入dumi可以渲染md，但是build之后识别不了md

### ISSUE THREAD

**Issue by acsamson** [umijs/dumi#606]
build之后打开站点出现
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ...
请问怎么解决呢

**Comment by acsamson** [comment]
这边是直接创建umi，引入@umijs/preset-dumi，在index文件直接引入md，可以展示，但是build之后就显示DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ...

```
import styles from './index.less';
import SUB_1_1 from './sub-1-1.md';

export default function IndexPage() {
  return (
    <div>
      <h1 className={styles.title}>Page index</h1>
      <SUB_1_1></SUB_1_1>
    </div>
  );
}
```
感谢

**Comment by PeachScript** [comment]
把 md 当模块用？这是要实现什么效果

**Comment by xrkffgg** [comment]
jsx 应该没办法直接解析 md 文件当做标签吧。

可以弄一个 react 的组件，用来解析 md ，然后这个 jsx 引组件。

**Comment by acsamson** [comment]
> jsx 应该没办法直接解析 md 文件当做标签吧。
> 
> 可以弄一个 react 的组件，用来解析 md ，然后这个 jsx 引组件。

umi引入dumi后的dev模式可以识别src下的md文件，可以当做模块直接引入。build之后就识别不了md了，dumi在build后是不是需要手动添加raw-loader呢

**Comment by acsamson** [comment]
这样引入比较直观，来展示本地的md文件

**Comment by PeachScript** [comment]
Umi 集成模式的思路是，dev 下载入 dumi + 生成文档用来管理业务组件，prod 下不会载入 dumi 以确保业务自己可以单独构建

至于上面的 js 里 import md 在 dev 下也可以工作是纯属巧合，也不是 dumi 设计集成模式的初衷，请使用 md 文件作为路由入口来使用 dumi，issue 关闭

Umi 集成模式文档参考：https://d.umijs.org/zh-CN/guide/advanced#umi-%E9%A1%B9%E7%9B%AE%E9%9B%86%E6%88%90%E6%A8%A1%E5%BC%8F
