### ISSUE TITLE
mobile主题里预览的元素单位怎么转为vw

### ISSUE THREAD

**Issue by mushan0x0** [umijs/dumi#607]
### Question
![image](https://user-images.githubusercontent.com/29084441/112794615-bcfc9d00-9099-11eb-9637-34dd4111e2a6.png)

themeConfig 不管怎么设置都没有变化

**Comment by mushan0x0** [comment]
或者rem也可以，反正以750宽度窗口展示demo就行了

**Comment by xiaohuoni** [comment]
怎么写的，给demo吧。或者看例子。https://github.com/alitajs/antd-mobile-plus/blob/master/config/config.ts#L10

**Comment by xiaohuoni** [comment]
了解了一下，是适配方案不一致。需要自己自定义主题处理了。
“需要注意的是，如果使用 rem 的响应式方案，在样式源代码中也要采用 rem 单位，建议参考 antd-mobile 的方案，设置 Less 变量作为基础单位，再根据需要在编译时配置高清变量控制最终渲染值。”
