### ISSUE TITLE
 father-build failure

### ISSUE THREAD

**Issue by zhjgh** [umijs/dumi#609]
### Question

 father-build failure

### Sample Code

yarn run v1.22.10                                                                                                             $ father-build                                                                                                                Clean dist directory                                                                                                          Build cjs with rollup                                                                                                         The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten                      ×  error     Error: 'parse' is not exported by node_modules\qs\lib\index.js, imported by node_modules\umi-request\dist\index. es.js                                                                                                                             at error (D:\dp-npm\dumi\node_modules\rollup\dist\shared\rollup.js:5253:30)                                                   at Module.error (D:\dp-npm\dumi\node_modules\rollup\dist\shared\rollup.js:9821:16)                                            at handleMissingExport (D:\dp-
--

**Comment by PeachScript** [comment]
用到的依赖要写进 dependencies，比如上面的 `umi-request`；后续提问请按照格式提供复现步骤，issue 关闭
