### ISSUE TITLE
bug: 左侧栏与顶部导航栏点击默认跳转有问题，不是第一个。

### ISSUE THREAD

**Issue by answershuto** [umijs/dumi#610]
复现地址：

https://github.com/openkraken/website

### Versions

- dumi:1.1.19
- node:10.15.3
- npm:7.6.3
- OS:macOS 10.15.5 
- Browser:chrome 81.0.4044.138

### Steps to reproduce

点击左侧栏或者顶部导航栏，如点击顶部 “API”

![image](https://user-images.githubusercontent.com/17812136/112833009-b0dc0400-90c8-11eb-8a7e-f05776199bbf.png)

会跳转到“文档”

![image](https://user-images.githubusercontent.com/17812136/112833061-c0f3e380-90c8-11eb-94ce-6d41e5899f49.png)

除了顶部栏，左侧栏也一样的问题，如下，点击“样式”，会默认到“颜色与背景”。

![image](https://user-images.githubusercontent.com/17812136/112833312-234ce400-90c9-11eb-8cc2-456d92be2499.png)

### What is Expected?

跳转到第一个选项。

### What is actually happening?

实际上会跳转到单词按照 a-z 排序的最前面的文件路由。

**Comment by PeachScript** [comment]
v1.1.11 已修复
