### ISSUE TITLE
使用dumi-theme-default主题时，怎么关闭/不显示 CodeSandbox按钮

### ISSUE THREAD

**Issue by realwugang** [umijs/dumi#616]

**Comment by xrkffgg** [comment]
这个没有选项呢  ，不过可以通过 css 强行 display none

**Comment by realwugang** [comment]
> 这个没有选项呢 ，不过可以通过 css 强行 display none

可以通过参数配置吗？我看Previewer组件有个hideAcitons参数

**Comment by xrkffgg** [comment]
哦哦，那可以

**Comment by youngjuning** [comment]
`hideActions` 建议可以全局配置，因为我这边 预览 react-native，codesandbox 不支持
