### ISSUE TITLE
发布npm后发现src源码文件夹

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#620]
![image](https://user-images.githubusercontent.com/25706676/113249888-1ced8080-92f2-11eb-9dc3-05c4bd9a57ff.png)

这个怎么去掉呢,打包之后源码文件也同时存在

**Comment by ChenYCL** [comment]
通过创建 .npmignore 屏蔽 src/ node_modules/ 解决了

**Comment by xiaohuoni** [comment]
package.json 里面配置 files
