### ISSUE TITLE
feat: dumi 中使用的 `react-docgen-typescript` 是否可以开放 `propFilter` 选项

### ISSUE THREAD

**Issue by jiechud** [umijs/dumi#622]
### Description
我们在做组件库的时候， 继承 `node_modules`里面的类型不想在`API`组件中展示出来，希望在 `react-docgen-typescript`中加`propFilter` 配置

### Solution
`propFilter`  代码

```
  propFilter: (prop, component) => {
        if (prop.declarations !== undefined && prop.declarations.length > 0) {
          const hasPropAdditionalDescription = prop.declarations.find((declaration) => {
            return !declaration.fileName.includes("node_modules");
          });
    
          return Boolean(hasPropAdditionalDescription);
        }
    
        return true;
      },
```

**Comment by PeachScript** [comment]
有计划支持，还在进行中，和 #513 重复，issue 关闭

**Comment by ChenYCL** [comment]
如何引入react-docgen-typescript ,dumi集成了么,发现单独装有些问题,目前准备重写API

**Comment by PeachScript** [comment]
集成了，但没开放配置

**Comment by adagiomin** [comment]
> 
请问这个配置可以开放下吗， 碰到了单独用react-docgen-typescript解析不出来，但是dumi上可以的组件

**Comment by PeachScript** [comment]
已经开放了：https://d.umijs.org/config#apiparser

**Comment by adagiomin** [comment]
> 已经开放了：https://d.umijs.org/config#apiparser

那我理解错了，我是想问dumi自身在使用react-docgen-typescript的时候，内部options配置了什么呢
