### ISSUE TITLE
feat: 文档可以支持组件示例实时编辑吗，类似docz

### ISSUE THREAD

**Issue by zhangguimei** [umijs/dumi#623]
### Description
feat: 文档可以支持组件示例实时编辑吗，类似docz

**Comment by PeachScript** [comment]
暂不支持，docz 只渲染 JSX 标签，但 dumi 要处理组件逻辑和依赖，复杂度会高许多，有相关经验的话可以帮 dumi 增加这个功能。

与 #96 重复，issue 关闭

**Comment by shaoqiwang-fe** [comment]
这个有规划吗

**Comment by wenbin-im** [comment]
> 暂不支持，docz 只渲染 JSX 标签，但 dumi 要处理组件逻辑和依赖，复杂度会高许多，有相关经验的话可以帮 dumi 增加这个功能。
> 
> 与 #96 重复，issue 关闭

@PeachScript 可以先用react-live来支持单文件组件的Live Code吗？CodeBlock内有多个文件依赖的先不支持。

**Comment by PeachScript** [comment]
@wenbin-im react-live 应该只支持纯组件、处理不了三方依赖；在无法提供良好体验的 Playground 之前，跳 codesandbox.io 是更好的选择

**Comment by nieyao** [comment]
这块需求还是挺大的，我这边包是放在私有npm 上的，跳 codesandbox 下不了依赖，使用者没办法快速调试 demo

**Comment by huangchen1031** [comment]
因为使用私有源npm，最新也想给组件库加个这功能。看了下真是不好搞，docz和docusaurus都是基于react-live，所有第三方依赖的引入都是通过scope方式传给Playground，示例代码不是复制即可用。umi是通过预编译成文件，再通过import导入实现，这个实时编译的部分卡点很大。。。

**Comment by PeachScript** [comment]
@huangchen1031 有兴趣可以调研下 [sandpack](https://sandpack.codesandbox.io/)？这个讨论是一年多以前的，有些结论在今天不一定成立，也许 sandpack 之类的新方案能帮助 dumi 实现真正的 demo 实时编译预览，如果可行也欢迎给 dumi 提交 PR

**Comment by huangchen1031** [comment]
> @huangchen1031 有兴趣可以调研下 [sandpack](https://sandpack.codesandbox.io/)？这个讨论是一年多以前的，有些结论在今天不一定成立，也许 sandpack 之类的新方案能帮助 dumi 实现真正的 demo 实时编译预览，如果可行也欢迎给 dumi 提交 PR

这个也看了下，react新文档就是用的这个依赖实现的。有点在意的是sandpack官方示例都是iframe用src通过一个在线服务更新示例，这种也不支持私有npm源的第三方依赖。而react的文档iframe则没有src内容页纯粹很多，看源码似乎是用patch-package对@codesandbox/sandpack-react进行了一些魔改。这个我再研究研究，有进展在这里同步~

**Comment by huangchen1031** [comment]
@PeachScript sandpack的依赖只支持发布到npm的公共包，或者通过cdn引入的静态资源，又凉了。准备去看看[code-kitchen](https://github.com/freewheel/code-kitchen) :)

**Comment by PeachScript** [comment]
@huangchen1031 看 sandbox 文档是有方案的，在内网部一个 Node.js 服务即可，https://sandpack.codesandbox.io/docs/guides/private-packages

**Comment by huangchen1031** [comment]
> @huangchen1031 看 sandbox 文档是有方案的，在内网部一个 Node.js 服务即可，https://sandpack.codesandbox.io/docs/guides/private-packages

尝试了下这个方案，因为依赖溯源导致一个playground就让浏览器发了上千个请求，救命233
要不还是用react-live全局注入下scope算了
