### ISSUE TITLE
bug: demo渲染错误

### ISSUE THREAD

**Issue by realwugang** [umijs/dumi#626]
通过配置code标签指向demo的jsx文件地址，在demo中配置了demoUrl，为什么还会触发当前demo的jsx渲染？我希望配置了demoUrl，示例文件里的内容仅作为展示，绕开dumi不支持我的示例渲染，请问需要如何解决？

### Versions

- dumi:1.0.13
- node:v14.15.4
- npm:6.14.10
- OS:macOS 10.15.7
- Browser:Chrome 89

**Comment by xrkffgg** [comment]
https://d.umijs.org/zh-CN/guide/basic#%E5%86%99%E7%BB%84%E4%BB%B6-demo

**Comment by realwugang** [comment]
> https://d.umijs.org/zh-CN/guide/basic#%E5%86%99%E7%BB%84%E4%BB%B6-demo

我现在用的是dumi-theme-mobile主题，我把这个改成null了，就不会以我的demo文件去渲染了
![image](https://user-images.githubusercontent.com/26088619/113647605-ba173300-96bd-11eb-8c93-0eb4a4956fbf.png)

**Comment by xrkffgg** [comment]
你目前的 dumi 版本多少，demoUrl 需要 <kbd>1.1.1+</kbd>

**Comment by realwugang** [comment]
> 你目前的 dumi 版本多少，demoUrl 需要 1.1.1+

用的是1.0.13，手机主题下能正确预览并展示demoUrl地址，只是不想要这个demo文件被require作为一个component

**Comment by xrkffgg** [comment]
升级下看看

**Comment by realwugang** [comment]
> 升级下看看

还是不行的，因为我的demo是依赖taro环境，dumi不支持，所以用demoUrl来绕过去，没想到demo文件还会被require渲染

**Comment by xrkffgg** [comment]
`jsx | pure` 这种可以吗？

**Comment by soeasyjx** [comment]
> demo是依赖taro



> 



> > 升级下看看
> 
> 还是不行的，因为我的demo是依赖taro环境，dumi不支持，所以用demoUrl来绕过去，没想到demo文件还会被require渲染

兄弟我也遇到 这个问题了，我demo 是放到服务器上的，通过demoUrl 链接进来，但是我又需要展示示例代码。。。。我demo 也是taro 写的
