### ISSUE TITLE
为什么组件文件夹不支持小写命名

### ISSUE THREAD

**Issue by Hipotecas** [umijs/dumi#627]
### Question
![image](https://user-images.githubusercontent.com/80826665/113591504-8957df00-9666-11eb-888a-fec675867913.png)

### Sample Code
![image](https://user-images.githubusercontent.com/80826665/113591540-95dc3780-9666-11eb-9f89-d05ddb3333b6.png)

这种有没有配置更改成小写的形式

**Comment by PeachScript** [comment]
和文件系统有关，babel-loader 提示得很清楚了
