### ISSUE TITLE
lerna 项目下 别名 @ 解析问题如何解决

### ISSUE THREAD

**Issue by alvin0216** [umijs/dumi#628]
### Question
![image](https://user-images.githubusercontent.com/34113677/113669918-032fad00-96e7-11eb-8a2a-e2c04ae7dc85.png)

如图，lerna 子项目中使用了别名，导致 `dumi start` 时报错了 这个问题怎么解决呢？

**Comment by lbwa** [comment]
换一个别名，@ 和 @@ 已经被使用。

https://github.com/umijs/dumi/blob/7d1fe1702130642e27573d27c5615ff9e183e9cf/packages/preset-dumi/src/plugins/features/init.ts#L40-L41

**Comment by alvin0216** [comment]
> **最佳方案** 是换一个别名，@ 和 @@ 已经被内部使用，@ 为项目根目录或 src/（取决于 dumi 的使用方式），@@ 为 umi 缓存目录
> 
> 以上因为没有具体 demo 只能给出一个大致推断。另外说句题外话，在默认情况下 ts alias 与 dumi alias（webpack alias） 是不相关的，lerna 包中的 alias 需要额外同步到 .umirc.ts 中的 alias 配置

不清楚您的意思，这是我的文件目录

```bash
├── docs # dumi 根 docs
├── project
│   ├── drag # 子项目，umi 起的项目 用到 @ 别名
│   ├── render # 子项目，uni-app  起的项目 用到 @ 别名
│  
│   # 根 使用 lerna
```
如果在子项目中的 mdx 引入的 tsx 文件有引用了 `@` 则会报错，换一个别名，子项目的别名可能会有多个，多个项目中也会用到内部的 @ 别名，这里需要做什么配置呢

**Comment by lbwa** [comment]
> > **最佳方案** 是换一个别名，@ 和 @@ 已经被内部使用，@ 为项目根目录或 src/（取决于 dumi 的使用方式），@@ 为 umi 缓存目录
> > 以上因为没有具体 demo 只能给出一个大致推断。另外说句题外话，在默认情况下 ts alias 与 dumi alias（webpack alias） 是不相关的，lerna 包中的 alias 需要额外同步到 .umirc.ts 中的 alias 配置
> 
> 不清楚您的意思，这是我的文件目录
> 
> ```shell
> ├── docs # dumi 根 docs
> ├── project
> │   ├── drag # 子项目，umi 起的项目 用到 @ 别名
> │   ├── render # 子项目，uni-app  起的项目 用到 @ 别名
> │  
> │   # 根 使用 lerna
> ```
> 
> 如果在子项目中的 mdx 引入的 tsx 文件有引用了 `@` 则会报错，换一个别名，子项目的别名可能会有多个，多个项目中也会用到内部的 @ 别名，这里需要做什么配置呢

这里提供一种可行的思路是 **以你 lerna 包的 package.json 的 name 来作为别名**。可以参考 https://github.com/ant-design/pro-components/blob/master/.umirc.js#L12 进行配置，该项目就是 lerna 项目。

**Comment by PeachScript** [comment]
文档迁移的时候内容漏了，可以理解为不支持也不推荐在 demo 里使用 @；请使用 npm 包名作为组件引入的入口，用 dumi 写组件 demo 有一个大原则是**用户如何使用我们的组件，我们自己就怎么写 demo**，比如：
```
import { Button } from '@group/child'; // lerna 子包 package.json 的 name
```

**Comment by alvin0216** [comment]
> 文档迁移的时候内容漏了，可以理解为不支持也不推荐在 demo 里使用 @；请使用 npm 包名作为组件引入的入口，用 dumi 写组件 demo 有一个大原则是**用户如何使用我们的组件，我们自己就怎么写 demo**，比如：
> 
> ```
> import { Button } from '@group/child'; // lerna 子包 package.json 的 name
> ```

可以理解为 dumi 适用于单独的组件库文档，不适用于项目里面的组件文档么？

**Comment by PeachScript** [comment]
@alvin0216 项目内的组件可通过 dumi 的 alias 配置项单独建立别名映射

**Comment by alvin0216** [comment]
> @alvin0216 项目内的组件可通过 dumi 的 alias 配置项单独建立别名映射

![image](https://user-images.githubusercontent.com/34113677/114959786-4d0f5480-9e98-11eb-9cc7-55b47c757cbf.png)

并不生效？

**Comment by PeachScript** [comment]
看 script 是 cd 到子目录去执行命令的，确认 `.umirc.ts` 是在子目录下

**Comment by ldwonday** [comment]
@PeachScript 项目内如何配置alias？比如我在packages/core下如何配置core子仓的内部的短路径？

**Comment by Liu-0114** [comment]
就是希望在packages的内部包里面使用@，如何在components下的包里面直接使用@/utils，在tsconfig.json和.fatherrc.ts中配置了，都不起作用
目录如下：
<img width="350" alt="image" src="https://github.com/umijs/dumi/assets/59878300/20926f35-a797-4129-9be8-708b2f032eef">
