### ISSUE TITLE
feat: demo支持自定义第三方包css导入

### ISSUE THREAD

**Issue by janryWang** [umijs/dumi#630]
### Description

目前demo导入第三方包css的逻辑有点太固定，可以考虑支持一下自定义吧。

https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/transformer/demo/dependencies.ts#L236

### Solution

.umirc.js文件里支持一个配置白名单映射？

**Comment by PeachScript** [comment]
Duplicated with #479
