### ISSUE TITLE
bug: Cannot find module 'slash'

### ISSUE THREAD

**Issue by sylingd** [umijs/dumi#634]
### Versions

- dumi:1.1.12
- node:14.6.0
- npm:6.14.8
- OS:Mac
- Browser:-

### Steps to reproduce
* Create a new project: `yarn create @umijs/dumi-app`
* Create a jsx file in docs, such as `docs/a.jsx`:
```jsx
import * as React from 'react';

export default () => {
  return <div>hahaha</div>
};
```
* Add a inline demo in getting-started.md
```markdown

# Getting Started

Balabala...


```jsx | inline
import * as React from 'react';
import A from './a';

export default () => {
  return <A />;
};

// remove this comment flag
// ```
```
* run: `npm run build`

### What is Expected?
build docs

### What is actually happening?
![image](https://user-images.githubusercontent.com/5326684/114000346-7ffc8b80-988d-11eb-8025-04119f4947fa.png)

May because: import slash, but slash not in package.json
* https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/transformer/demo/dependencies.ts#L2

**Comment by xiaohuoni** [comment]
```
import slash from 'slash2';
```

**Comment by PeachScript** [comment]
v1.1.13 已修复
