### ISSUE TITLE
feat: <API>支持 alias

### ISSUE THREAD

**Issue by mini0609** [umijs/dumi#635]
### Description

希望支持` <API src="@/example/xxx" /> `这样可以配 alias 的写法，这样在找 example 的时候就方面很多了

**Comment by ltaoo** [comment]
能否在 `packages/preset-dumi/src/transformer/remark/api.ts` 文件 145 这里，判断下 `src` 里面是否存在别名，如果存在，就取 `ctx.umi.config.alias` 上进行替换，再用替换后的去拼接 `absPath`？
或者应该直接用 `enhanced-resolve` 去做依赖查找，更保险。

**Comment by PeachScript** [comment]
@ltaoo 可以用 utils 里的 `moduleResolver`，基于 `enhanced-resolve`，会自动处理 alias

**Comment by PeachScript** [comment]
v1.1.26 已支持
