### ISSUE TITLE
mobile模式下使用rem iframe的html设置了font-size导致样式失调  如何去掉iframe的fontsize

### ISSUE THREAD

**Issue by GzxNydia** [umijs/dumi#636]
### Sample Code
mobile模式下使用rem iframe的html设置了font-size导致样式失调  如何去掉iframe的内html fontsize

**Comment by PeachScript** [comment]
<img width="630" alt="图片" src="https://user-images.githubusercontent.com/5035925/114118890-2c854e80-991c-11eb-8375-184b65b78a3d.png">

refer: https://d.umijs.org/zh-CN/theme#dumi-theme-mobile
