### ISSUE TITLE
feat: tsx/jsx 代码块渲染为组件demo 希望支持 '| demo ' 修饰

### ISSUE THREAD

**Issue by whistleyz** [umijs/dumi#637]
### Description

md 中很普通的一个 React 代码片段：

<pre>
```tsx
import React from 'react';

const Header = &lt;div&gt;Header&lt;/div&gt;
```
</pre>

使用 dumi 会自动渲染为空代码块：
![image](https://user-images.githubusercontent.com/16064175/114124792-cb637800-9927-11eb-8700-5ec1d399553e.png)

如果需要解决这个问题，目前有两种方法：

1. 修改 tsx -> ts，不推荐（相当于代码块使用的语言发生变化，且 tsx 语法高亮在某些md编辑器会消失）
2. 修改 resolve. previewLangs 为 [] ，这意味着，你无法再使 tsx/jsx 代码块渲染为 demo 组件
3. 使用 | pure 修饰，意味着每个 tsx/jsx 代码块都需要使用 | pure 来标记一下

### Solution

期望更好的解决方法：能通过配置的修改，支持 modifier 控制 jsx/tsx 代码块，例如：

<pre>
```tsx | demo
import React from 'react';

const Header = &lt;div&gt;Header&lt;/div&gt;

export default Header;
```
</pre>

**Comment by PeachScript** [comment]
参考：https://d.umijs.org/zh-CN/guide/basic#%E4%B8%8D%E6%B8%B2%E6%9F%93%E4%BB%A3%E7%A0%81%E5%9D%97

**Comment by whistleyz** [comment]
@PeachScript 说的就是，我迁移过来的每个md，都需要加上 | pure

**Comment by PeachScript** [comment]
抱歉看错了…目前确实只能用方法 3 迁移，但这个迁移成本是一次性的；如果确实迁移成本很高，欢迎提交 PR 支持

**Comment by xrkffgg** [comment]
配置如何修改？

**Comment by PeachScript** [comment]
v1.1.14 已发布
