### ISSUE TITLE
useApiData仅在API中可以使用?

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#639]
### Question
![image](https://user-images.githubusercontent.com/25706676/114164864-5fe8cd00-995e-11eb-8d7e-6c288314dc37.png)
直接复制API源码 放入Mark中失效

### Sample Code
如果在自定义标签中使用,获取component/index.tsx中解析到的数据

### 期望
![image](https://user-images.githubusercontent.com/25706676/114165081-a3dbd200-995e-11eb-8e36-9bbc7954d576.png)

**Comment by PeachScript** [comment]
触发不了，useApiData 只是 runtime 的方法，用于获取生成好的 API 数据，不对 compiletime 产生影响，设计的初衷是用于开发者自定义 API.tsx 的
