### ISSUE TITLE
webpack5 下.dumi下获取fs模块

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#643]
### Question
![image](https://user-images.githubusercontent.com/25706676/114383091-ba349880-9bbf-11eb-8010-da48957b948f.png)

请问.dumi模块下怎么获取fs，模块呢

**Comment by PeachScript** [comment]
主题是运行在浏览器环境的模块，无法访问文件系统

**Comment by ChenYCL** [comment]
希望早日暴露API 注释的api

**Comment by PeachScript** [comment]
> 希望早日暴露API 注释的api

注释的 api 怎么理解

**Comment by ChenYCL** [comment]
目前发现export exports都会循环查找props 会自动插入以h3标签的title内容 希望有个可控输出的点 useApidata渲染多次 无法重写API.tsx控制

发自我的iPhone
