### ISSUE TITLE
写一个React class 组件 里面的static 还是一个React 的class 组件，在md文件使用时报错

### ISSUE THREAD

**Issue by gavinkd** [umijs/dumi#644]
### Sample Code
![image](https://user-images.githubusercontent.com/31567995/114488958-df1f1f00-9c44-11eb-8d92-bd87081500a0.png)

![image](https://user-images.githubusercontent.com/31567995/114489004-ee9e6800-9c44-11eb-883b-6a5de580a022.png)

error：
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by PeachScript** [comment]
确保 View 有通过 `src/index.ts` 导出

**Comment by gavinkd** [comment]
有的 大佬 
![image](https://user-images.githubusercontent.com/31567995/114799590-8bd6d900-9dca-11eb-897b-6ee64ea7727b.png)

**Comment by PeachScript** [comment]
请提供复现仓库

**Comment by 1617634** [comment]
这就关闭了吗
