### ISSUE TITLE
bug: doc 模式下当 md 文件放置在文件夹下时，会被认为是同个子路由

### ISSUE THREAD

**Issue by suedar** [umijs/dumi#645]
### Versions

- dumi: 1.1.7
- node: 14.16.0
- npm: 6.14.11
- OS: macos Catalina 
- Browser: 86.0.4240.80

### Steps to reproduce
如有组件A跟组件B, md文件分别放置于example文件夹下，会被认为是同一级路由

```
├── A
│   └── example
│       ├── index.md 
├── B
│   └── example
│       ├── index.md 

```

![image](https://user-images.githubusercontent.com/18492953/114696291-14179880-9d4f-11eb-8190-fd468b3b4dc7.png)

**Comment by PeachScript** [comment]
组件是 lerna 项目的子包？

**Comment by suedar** [comment]
@PeachScript 不是

**Comment by PeachScript** [comment]
根据 issue 模板把信息补全下吧，目前还看不到问题。期望结果、实际结果、复现步骤等等

**Comment by suedar** [comment]
Sorry. 前几天太忙了。@PeachScript 
GitHub 重现实例仓库地址：https://github.com/suedar/dumi-bad-case
`yarn start` 后的表现为：
![image](https://user-images.githubusercontent.com/18492953/115989206-e1438f00-a5ef-11eb-8cae-c517a0f9ff59.png)

**Comment by suedar** [comment]
需要补充个条件，配置了 group 的情况下

**Comment by PeachScript** [comment]
看起来是正常结果，index.md 自身意味着 `/`，给两个 index.md 设置不同的 `group.path` 即可

**Comment by suedar** [comment]
不是的 相同的 group.path 意味着同样的父级目录，所以这应该是个 bug

**Comment by PeachScript** [comment]
同样的父级目录下有两个 `/`，相互覆盖是预期结果
