### ISSUE TITLE
使用code引入外部demo,无法解析interface或者type 

### ISSUE THREAD

**Issue by Sundayuu** [umijs/dumi#648]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

![image](https://user-images.githubusercontent.com/44969151/115378824-8a127880-a203-11eb-91fb-37249a5beadc.png)

**Comment by yuweilan** [comment]
我这边也有这个问题，把interface export之后就可以用了

**Comment by PeachScript** [comment]
@yuweilan 应该不是同一个问题，这个看起来是引用了某些项目之外的文件，但内置的 loader 默认只会处理项目目录下的文件
