### ISSUE TITLE
外部导入demo上面必须有head标题🐛[BUG]

### ISSUE THREAD

**Issue by kakuyogy** [umijs/dumi#65]
### 🐛 bug 描述

如果没有标题展开代码异常
![image](https://user-images.githubusercontent.com/32446924/72430570-b0aa5e00-37cd-11ea-8de2-8d852124b30d.png)

**Comment by PeachScript** [comment]
有可复现 demo 吗，使用 father-doc 的文档无法复现此问题
<img width="835" alt="图片" src="https://user-images.githubusercontent.com/5035925/72674743-55ba8480-3ab5-11ea-8eb5-79eff4ac0b5f.png">
