### ISSUE TITLE
export type error

### ISSUE THREAD

**Issue by souse** [umijs/dumi#656]
##### 代码
```javascript
// rc/index.ts

export { default as Button } from './button';

export type { MenuProps, MenuTheme, SubMenuProps, MenuItemProps } from 'antd';
export { default as Menu } from './menu';
```
##### 操作
```
npm run prettier
```

##### 报错
```
[error] src/index.ts: SyntaxError: Declaration or statement expected. (3:1)
[error]   1 | export { default as Button } from './button';
[error]   2 |
[error] > 3 | export type { MenuProps, MenuTheme, SubMenuProps, MenuItemProps } from 'antd';
[error]     | ^
[error]   4 | export { default as Menu } from './menu';
src/menu/index.md 9ms
src/menu/index.tsx 5ms
tsconfig.json 7ms
typings.d.ts 7ms
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

**Comment by lbwa** [comment]
https://stackoverflow.com/questions/59833120/parsing-error-expected-in-import-type

https://github.com/ant-design/pro-table/issues/463

**Comment by souse** [comment]
@lbwa  并没有好哦，
```tsx
import type { ButtonProps } from 'antd';
// 同样报错  SyntaxError: '=' expected.
```

**Comment by lbwa** [comment]
> @lbwa 并没有好哦，
> 
> ```tsx
> import type { ButtonProps } from 'antd';
> // 同样报错  SyntaxError: '=' expected.
> ```

保证 prettier 2.0 以上。https://prettier.io/blog/2020/03/21/2.0.0.html#typescript-38-7631httpsgithubcomprettierprettierpull7631-by-thorn0httpsgithubcomthorn0-7764httpsgithubcomprettierprettierpull7764-by-sosukesuzukihttpsgithubcomsosukesuzuki-7804httpsgithubcomprettierprettierpull7804-by-sosukesuzukihttpsgithubcomsosukesuzuki

**Comment by souse** [comment]
@lbwa 好了
