### ISSUE TITLE
bug: mhchemParser报错

### ISSUE THREAD

**Issue by Hencky** [umijs/dumi#658]
### Versions

- dumi: v1.1.14
- node: v14.16.0
- npm: 7.7.5
- OS: macOS10.14.6
- Browser: chrome89

### Steps to reproduce

```
rm -rf node_modules
npm i 
npm start
```

### What is Expected?

正常启动dumi

### What is actually happening?

报错

![image](https://user-images.githubusercontent.com/40154205/115813745-4f3c5a80-a426-11eb-8145-8930ae74a0e2.png)

**Comment by lbwa** [comment]
fixed in [v1.1.16](https://github.com/umijs/dumi/releases/tag/dumi%401.1.16)
