### ISSUE TITLE
👑 [需求]支持识别 fatherrc 的可用配置

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/dumi#66]
如何与father-build联合使用啊
只能father-build用.fatherrc.js写打包配置，
用father-doc写UI配置么，就要写两份配置，比如babel-plugin-import就要写两份

**Comment by PeachScript** [comment]
是的，配置需要分开写。
不过你说的这个场景可以优化，father-doc 可以读一下 father-build 的配置然后帮用户 merge 有效的配置过来。

**Comment by PeachScript** [comment]
考虑到黑盒逻辑带来的风险，该 feature 暂时不作考虑，issue 关闭
