### ISSUE TITLE
feat: resolve 解析需要exclude配置

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#661]
### Description
某些单独md文件需要屏蔽，不屏蔽会出现在nav上

### Solution
![image](https://user-images.githubusercontent.com/25706676/115838841-a8b78000-a44c-11eb-934d-76ff627441f6.png)
exclude 排除大目录下某些局部文件夹

**Comment by PeachScript** [comment]
v1.1.25 已支持 `resolve.excludes` 配置项，参考：https://d.umijs.org/zh-CN/config#excludes
