### ISSUE TITLE
如何全局引入非umd格式的包

### ISSUE THREAD

**Issue by BovineBoy** [umijs/dumi#664]
### Question
目前知道可以通过headScripts引入umd格式的包，那么如何全局引入cjs或esm的包呢

**Comment by PeachScript** [comment]
`src/app.ts` 引入

**Comment by BovineBoy** [comment]
> `src/app.ts` 引入

dumi 采用的lerna架构，没有src目录吧

**Comment by BovineBoy** [comment]
如果在docs的index.md引入，如果进入其他路由并且刷新，引入的包就不会生效
