### ISSUE TITLE
bug: markdown table align left error

### ISSUE THREAD

**Issue by Turkyden** [umijs/dumi#669]
### Versions

- dumi: v1.1.16
- node: v10
- npm: v10
- OS: windows
- Browser: Chrome

### Steps to reproduce

dumi 里的 markdown 的表格语法，不支持左对齐，右对齐渲染？

```
| 居中 | 左对齐 | 右对齐 |
| :-------: | :------- | -------: |
| foo | bar | baz |
```

| 居中 | 左对齐 | 右对齐 |
| :-------: | :------- | -------: |
| foo | bar | baz |

### What is Expected?

![image](https://user-images.githubusercontent.com/24560160/117037305-e82d7880-ad38-11eb-8120-a1784bc4b1a5.png)

https://react-darkreader.vercel.app/#%F0%9F%A5%87-who-is-using

**Comment by lbwa** [comment]
经对 react-darkreader.vercel.app 的样式 debug，可见，默认的 markdown 产出的 table 居中属性被 antd 的全局样式覆盖，导致 markdown 的居中语法无法生效。

![image](https://user-images.githubusercontent.com/32980314/117165113-c9da8200-adf7-11eb-86ef-62ec92a0da56.png)

![image](https://user-images.githubusercontent.com/32980314/117165302-f2fb1280-adf7-11eb-9905-8c1c6db5f070.png)

![image](https://user-images.githubusercontent.com/32980314/117165472-1c1ba300-adf8-11eb-84ff-07c6a7b2b2e6.png)

已向 antd 提交相关 pr，https://github.com/ant-design/ant-design/issues/30398，待 antd 解决后，可进行再次尝试。

**Comment by PeachScript** [comment]
dumi 没有依赖 antd，可以看下项目中是否有依赖 antd，如果有用到可以考虑用不带样式的 antd 底层组件 rc-component 代替

**Comment by Turkyden** [comment]
OK，感谢，那我先自己排查一下哈，先 close 啦！
