### ISSUE TITLE
bug: 配置history为hash模式，切换路由，菜单不会定位到当前位置（整个根节点都重置了）

### ISSUE THREAD

**Issue by realwugang** [umijs/dumi#670]
![image](https://user-images.githubusercontent.com/26088619/117260330-8debff00-ae81-11eb-81ba-be64d61e9bcc.png)
![image](https://user-images.githubusercontent.com/26088619/117260455-af4ceb00-ae81-11eb-929d-900499921254.png)

**Comment by PeachScript** [comment]
暂时没有支持 hash 模式的计划，锚点会工作不正常

**Comment by foolish-boy** [comment]
> 暂时没有支持 hash 模式的计划，锚点会工作不正常

这个现在支持了吗？我这边用hash模式发现切换demo的代码块 模拟器不会重新渲染或者渲染的是首页

**Comment by Jerryqun** [comment]
目前有解决方案了吗
