### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by greenPeppers** [umijs/dumi#672]
本地文档构建没问题，但是jenkins构建不行

ERROR [dumi]: cannot resolve module antd/es/button/style from /var/jenkins_home/workspace/library_frontend_98/packages/rc/src/contentSwitch/index.md
Can't resolve 'antd/es/button/style' in '/var/jenkins_home/workspace/library_frontend_98/packages/rc/src/contentSwitch'
Error: Can't resolve 'antd/es/button/style' in '/var/jenkins_home/workspace/library_frontend_98/packages/rc/src/contentSwitch'
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/Resolver.js:209:21
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/var/jenkins_home/workspace/library_frontend_98/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/var/jenkins_home/workspace/library_frontend_98/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/var/jenkins_home/workspace/library_frontend_98/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
    at /var/jenkins_home/workspace/library_frontend_98/node_modules/enhanced-resolve/lib/Resolver.js:285:5

### Versions

- dumi: 1.1.16
- node: 14.15.1
- npm: 6.14.6
- OS: 11.3.1
- Browser: 90.0.4430.93

**Comment by PeachScript** [comment]
看起来是构建环境的问题，请先检查；如果确认和 dumi 有关系，请按照 issue 模板提交 bug 报告，该 issue 关闭
