### ISSUE TITLE
开发组件库使用图片但是打包的文件中无法使用图片

### ISSUE THREAD

**Issue by huabingtao** [umijs/dumi#675]
### 下方是我组件库的代码

![image](https://user-images.githubusercontent.com/19888505/117531088-64fb7380-b013-11eb-87e6-62cd37803257.png)
如图是引用了相对路径的图片，实现了当使用不同的类名就使用不同图片作为背景
 

### 这是实际使用组件库的代码
![image](https://user-images.githubusercontent.com/19888505/117531176-df2bf800-b013-11eb-8929-5a81d112c17c.png)
### 在浏览器中显示的实际效果
![image](https://user-images.githubusercontent.com/19888505/117531200-fc60c680-b013-11eb-9ac0-54cc700f21c9.png)
![image](https://user-images.githubusercontent.com/19888505/117533971-0db0cf80-b022-11eb-96ed-df8095190754.png)

组件和className可以正常渲染，但是样式却仍然是一个相对路径当前路径下image文件夹也不存在图片文件;
这可能是因为我开发方式不对导致的bug，请问我该如何解决这类问题呢？

**Comment by suedar** [comment]
哥们你是不问错地方了 
不过你可以试试直接在 `jsx/tsx` 文件里面引入图片
``` tsx
import image from '@/assets/search@2x.png';
export default {
 return {
     <Empty image={image}>
 }
}
```

**Comment by guixuefeng101** [comment]
这个我也遇到了，是什么原因？

**Comment by huabingtao** [comment]
就是不支持背景图片，如果非要用就转化为base64的方式
