### ISSUE TITLE
bug: 在dumi-theme-mobile主题下demo首次无法渲染刷新页面后才会渲染

### ISSUE THREAD

**Issue by huabingtao** [umijs/dumi#682]
### Versions

- dumi: 1.0.14
- node: 12
- npm: 7.7.6
- OS: 10
- Browser: chrome  90.0.4430.93

### Steps to reproduce
使用 dumi-theme-mobile的主题demo代码无法渲染就像这样
![image](https://user-images.githubusercontent.com/19888505/117787398-fddef880-b278-11eb-9207-ed4a28b2846e.png)
只要只用默认主题就完全没问题

当我手动刷新浏览器的时候demo就能正常显示了.

所以我怀疑是版本更新后引起的。但是由于我也没有更新版本只是重新安装了依赖，所以我怀疑是不是这次版本更新也改动了老版本的代码呢？

我猜测是在最新版本发布了dark主题切换的版本。

**Comment by xrkffgg** [comment]
@PeachScript 

第一次的时候是有点慢，dark 的 icon 也不是立马就出来，第二次就好了。

![image](https://user-images.githubusercontent.com/29775873/117949173-6c3cbd00-b344-11eb-8775-743a0f7d288b.png)

![image](https://user-images.githubusercontent.com/29775873/117949277-8a0a2200-b344-11eb-84de-4fc50ca83250.png)

感觉还是这个锅

https://github.com/umijs/dumi/blob/438206303e95386c5bebf2d4372b3526c40e0a5f/packages/preset-dumi/src/theme/hooks/usePrefersColor.ts#L115

**Comment by PeachScript** [comment]
和 dark 无关，v1.1.18 已修复
