### ISSUE TITLE
bug:  pro-components 在 codesandbox.io 上没有加载 style 样式

### ISSUE THREAD

**Issue by rdmclin2** [umijs/dumi#685]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce

随便在 ProComponents官网 找个 codebox 链接点进去。

![image](https://user-images.githubusercontent.com/4705237/117950567-e4f04900-b345-11eb-888a-d3660ef9995f.png)

**Comment by PeachScript** [comment]
问题已修复
