### ISSUE TITLE
MD讲解页面找不到

### ISSUE THREAD

**Issue by qiaodaima** [umijs/dumi#687]
### Question
我的记得官网以前是有这个页面的，现在怎么找不到了，是删除了么？
![image](https://user-images.githubusercontent.com/81732419/118241949-54de0b00-b4cf-11eb-9c5d-4177ed3e0d36.png)

**Comment by PeachScript** [comment]
1.1 拿掉了，详见 PR #419 
1.0 分支可以找到：https://github.com/umijs/dumi/blob/1.0/docs/examples.md
