### ISSUE TITLE
文档不是直接添加到项目目录里的，而是动态生成的，是否支持这种功能？

### ISSUE THREAD

**Issue by Feafortecsy** [umijs/dumi#688]
### Question

1. 如何在dumi中执行Node脚本生成动态文档

**Comment by PeachScript** [comment]
可以执行 dumi dev 之前跑一遍生成逻辑，可参考 dumi 仓库的上游文档同步逻辑：https://github.com/umijs/dumi/blob/master/scripts/sync-from-umi.js
