### ISSUE TITLE
feat:  希望内置组件中，添加一个类似【tyora的目录内容】

### ISSUE THREAD

**Issue by fanhualei** [umijs/dumi#690]
### feat:  希望内置组件中，添加一个类似【typora的目录内容】

因为现在的左右菜单， 现实的级别与长度受限制。

所以希望正文中，可以添加目录内容的功能，类似于typora 添加一个 [TOC] 标签

**Comment by PeachScript** [comment]
TOC 不是组件文档常规场景，暂时不会考虑支持，有需求可以通过自定义组件实现：https://d.umijs.org/zh-CN/theme/development
