### ISSUE TITLE
bug:  新版本安装时会报错

### ISSUE THREAD

**Issue by suedar** [umijs/dumi#691]
### Versions

- dumi: 1.1.17
- node:  v14.16.0
- npm: 6.14.11
- OS: mac 
- Browser: google

### Steps to reproduce

在旧项目中 `yarn add dumi`

### What is actually happening?

![截屏2021-05-17 下午6](https://user-images.githubusercontent.com/18492953/118477863-c45b3100-b741-11eb-969c-88029c82c2b7.jpg)

看了下对应文件 /node_modules/hast-util-to-text/index.js 

![image](https://user-images.githubusercontent.com/18492953/118478218-33388a00-b742-11eb-9581-548f81c22b40.png)

hast-util-is-element 这个包其实是有安装的  但是没有导出 convert

**Comment by xrkffgg** [comment]
@PeachScript mathjax 又搞事情啊

**Comment by xrkffgg** [comment]
@suedar 有个版本有问题，你移除下 lock node_modules 重新安装下 看看有问题吗？

**Comment by suedar** [comment]
找到方法了 需要更改 yarn.lock
hast-util-to-text 的 2.0.1 有问题 强制降级为 2.0.0 即可

**Comment by xrkffgg** [comment]
@PeachScript see see

**Comment by suedar** [comment]
![截屏2021-05-17 下午7 (1)](https://user-images.githubusercontent.com/18492953/118481072-ac85ac00-b745-11eb-94df-e87b1a3f3ea2.jpg)

@xrkffgg @PeachScript  麻烦空了修一下哈

**Comment by xrkffgg** [comment]
这玩意不行 就用你那个 temp 版本
