### ISSUE TITLE
bug: require 引入的图片无法加载

### ISSUE THREAD

**Issue by helsonxiao** [umijs/dumi#693]
### Versions

- dumi: 1.1.13
- node: 14
- npm:
- OS:
- Browser:

### Steps to reproduce

参考这个 demo 的代码
https://boyuai.github.io/antd-country-phone-input/demos/custom-flag

### What is Expected?

可以正常显示 require 引入的图片

### What is actually happening?

无法正常显示，但在业务项目中使用组件时是正常的
https://www.boyuai.com/login/

**Comment by ltaoo** [comment]
只能说明你的业务项目对静态资源的处理方式和 `dumi` 不一样，大部分项目中 `require` 返回的就是图片地址或者 `base64`，所以你的示例中，

```jsx
 require(`world_countries_lists/flags/24x24/${area.short.toLowerCase()}.png`).default
```

后面的 `.default` 去掉就行。可能你的项目中对静态资源会额外包装成一个对象，变成了 `{ default: '' }` 这种数据，所以你的项目中可以使用 `.default`。

或者抛开你的项目，你可以尝试在 `http://codesandbox.io/` 复现这个问题，大家也方便排查。

**Comment by helsonxiao** [comment]
感谢，`.default` 是 CRA 包装的，我做了下处理，已解决。

**Comment by xlei1123** [comment]
打包后 图片 引入的路径 不对是什么问题呢？
