### ISSUE TITLE
bug: 打包报错，尝试更新版本，还是无效

### ISSUE THREAD

**Issue by rggaoxin** [umijs/dumi#696]
Versions
umi:3.2.28
dumi:1.1.18
node:v12.20.2
npm:6.14.11
OS:mac 10.15.5
Browser:null

尝试更新了dumi、umi版本，无效。

log信息为：

plugin @umijs/plugin-locale is already registered by /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js, plugin from /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js register failed.
Error: plugin @umijs/plugin-locale is already registered by /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js, plugin from /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js register failed.
at Service.registerPlugin (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:457:13)
at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:436:14
at Generator.next ()
at asyncGeneratorStep (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:108:103)
at _next (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:194)
at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:364
at new Promise ()
at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:97
at Service.initPlugin (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:442:7)
at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:317:22

**Comment by rggaoxin** [comment]
> Hello @rggaoxin. In order to facilitate location and troubleshooting, we need you to provide a realistic example. You can create a dumi project by clicking [here](https://github.com/umijs/dumi-template) and provide the GitHub warehouse address and reproduce examples.
> 
> 你好 @rggaoxin, 为了方便定位和排查问题，我们需要你提供一个重现实例。你可以通过点击 [此处](https://github.com/umijs/dumi-template) 创建一个 dumi 项目并提供 GitHub 仓库地址和重现实例。

I'm sorry.The project is a company project and I can't share it.And other developers can build it on the mac.But I can't build it on the windows and linux.

**Comment by rggaoxin** [comment]
root@HON-AI:/var/lib/jenkins/workspace/RTM-QA-web# yarn run start
yarn run v1.22.5
warning package.json: "optionalDependencies" has dependency "puppeteer" with range "1.10.0" that collides with a dependency in "dependencies" of the same name with version "^1.10.0"
$ node changeFileNames && node copyThemeFile && cross-env UMI_ENV=debug umi dev
plugin @umijs/plugin-locale is already registered by /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js, plugin from /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js register failed.
Error: plugin @umijs/plugin-locale is already registered by /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js, plugin from /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/plugin-locale/lib/index.js register failed.
    at Service.registerPlugin (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:457:13)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:436:14
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:108:103)
    at _next (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:194)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:364
    at new Promise (<anonymous>)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:110:97
    at Service.initPlugin (/var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:442:7)
    at /var/lib/jenkins/workspace/RTM-QA-web/node_modules/@umijs/core/lib/Service/Service.js:317:22
Done in 2.68s.
root@HON-AI:/var/lib/jenkins/workspace/RTM-QA-web# vi 1.log 
root@HON-AI:/var/lib/jenkins/workspace/RTM-QA-web# npm -v
6.14.11
root@HON-AI:/var/lib/jenkins/workspace/RTM-QA-web# node -v
v12.20.2

**Comment by PeachScript** [comment]
请提供基于空白 dumi 项目的最小可复现仓库，不要包含内部业务逻辑；目前看错误日志仅提示 plugin-locale 重复注册，但 dumi 本身并不依赖该插件，无法排查定位
