### ISSUE TITLE
bug: 打包发布到GithubPage iframe报错404

### ISSUE THREAD

**Issue by huabingtao** [umijs/dumi#698]
### Steps to reproduce
[复现地址](https://huabingtao.github.io/test/)

### What is Expected?

1. 我期望点击logo后路径地址应该是https://huabingtao.github.io/test而不是https://huabingtao.github.io/
2. 右侧组件能正常展示
### What is actually happening?
使用dum脚手架创建的初始项目，本地预览是好的。打包发布到gitHubPage就这样了？
![image](https://user-images.githubusercontent.com/19888505/118946609-23f74d80-b989-11eb-8f5a-c475933eecf9.png)
这个渲染的地址貌似不对导致地址404
![image](https://user-images.githubusercontent.com/19888505/118947327-cca5ad00-b989-11eb-9209-92a14a11217a.png)

还有就是点击logo后url地址就变成https://huabingtao.github.io/ 不应该加上我配置的publicPath么？😌
希望能有个讨论群啥的问个问题是在太难了😌😌😌😌

**Comment by xiaohuoni** [comment]
https://github.com/umijs/dumi#discuss-group

**Comment by xiaohuoni** [comment]
你这个地址，我访问都正常耶？？

**Comment by xiaohuoni** [comment]
![2021-05-20 17-05-40 2021-05-20 17_08_45](https://user-images.githubusercontent.com/11746742/118952276-62dbd200-b98e-11eb-9ff9-4718cb8a3c63.gif)

**Comment by huabingtao** [comment]
> 你这个地址，我访问都正常耶？？
我也正常了刚刚不行？昨天也不行，算了不管了 关了
