### ISSUE TITLE
API 是否可以取消自动生成二级标题

### ISSUE THREAD

**Issue by alvin0216** [umijs/dumi#699]
`<API src="xxx" />` 会自动生成二级标题，会导致无法很好的控制文档的目录结构，建议可以通过配置取消。

**Comment by ltaoo** [comment]
在 `packages/preset-dumi/src/transformer/remark/api.ts` 这里，有两处插入标题，加个额外配置项如 `hiddenApiTitle` ，判断 `ctx.umi?.hiddenApiTitle` 才插入应该就可以了。

**Comment by PeachScript** [comment]
@ltaoo 可以的，`hideTitle` 即可？

**Comment by tiyunchen** [comment]
#546

**Comment by PeachScript** [comment]
v1.1.27 已支持，参考文档：https://d.umijs.org/zh-CN/guide/advanced#%E5%9C%A8%E6%96%87%E6%A1%A3%E4%B8%AD%E5%B1%95%E7%A4%BA-api
