### ISSUE TITLE
bug: readlinkSync和pkgPath比较不正确

### ISSUE THREAD

**Issue by LeoHuiyi** [umijs/dumi#700]
![image](https://user-images.githubusercontent.com/8001457/119308023-1b5f8980-bc9f-11eb-9fba-e95d48b54788.png)
fs.readlinkSync(linkPath) = 'path/'
pkgPath = 'path' 
一个有斜杠 一个没有

**Comment by LeoHuiyi** [comment]
![image](https://user-images.githubusercontent.com/8001457/119313181-d5f28a80-bca5-11eb-8bef-23048f1e7b79.png)
能否加个配置不要设置pkgName的alias，和别的打包工具一起用会有问题。

**Comment by PeachScript** [comment]
> 能否加个配置不要设置pkgName的alias，和别的打包工具一起用会有问题。

具体场景是？

**Comment by LeoHuiyi** [comment]
内部用的打包工具 ,使用rollup plugin添加了一些的注释语法，要用rollup编译后产物引入才行，

**Comment by PeachScript** [comment]
> 内部用的打包工具 ,使用rollup plugin添加了一些的注释语法，要用rollup编译后产物引入才行，

可以手动配置 alias 指向 cwd，这样自动 alias 就不会生效了；另外 issue 中提到的问题真实存在还是因为上面的原因导致的

**Comment by LeoHuiyi** [comment]
我是用lerna，比较麻烦。不太明白为什么要直接用src下的，而不用编译后的。 上面的斜杠路径那个问题，win10，node: 12.18.3
, 下路径打印是不一样的。别的系统我这边没有，可能你那边要测试下。

**Comment by PeachScript** [comment]
编译后意味着 dev 的同时要启动 build watch，研发体验和性能都会受影响

**Comment by LeoHuiyi** [comment]
> 编译后意味着 dev 的同时要启动 build watch，研发体验和性能都会受影响

会有点影响，但是正确更重要，我认为应该开个配置，让别的工具或者有定制需求的能使用。

**Comment by PeachScript** [comment]
原 issue 提及的问题已修复，symlink 相关问题可以新开 issue 讨论，也欢迎提 PR 支持

该 issue 关闭
