### ISSUE TITLE
【问题】定制化的首页时，页面链接跳转不正常

### ISSUE THREAD

**Issue by fanhualei** [umijs/dumi#701]
### Question

重现步骤：
1、访问：https://ant-learning.redhtc.com/
2、点击顶部页面导航，可以显示：https://ant-learning.redhtc.com/guide
错误的地方
3、将：https://ant-learning.redhtc.com/guide 复制到一个新打开的chrome浏览器地址栏中，显示空白页。

**Comment by xrkffgg** [comment]
https://d.umijs.org/config#exportstatic
