### ISSUE TITLE
bug: 初始化项目之后.fatherrc.ts 模式换成babel 打包报错

### ISSUE THREAD

**Issue by ChenYCL** [umijs/dumi#704]
## 重现步骤
```shell
mkdir demo && cd demo
yarn create @umijs/dumi-lib --site
yarn 
# 修改fatherrc.rs
#export default {
 # esm: 'babel',
 # cjs: 'babel',
#};
yarn build

```
![image](https://user-images.githubusercontent.com/25706676/119759934-b0e75d00-bedb-11eb-97f7-f5659c16bcf5.png)

**Comment by WaveStill** [comment]
遇到同样的问题：

**Comment by WaveStill** [comment]
遇到同样的问题：
yarn create @umijs/dumi-lib 和 yarn create @umijs/dumi-lib --site  
都不行，build的时候，都报这个错，有没有大佬来给点意见

**Comment by PeachScript** [comment]
日志没看到具体错误原因，tsconfig.json 里加下 `skipLibCheck: true` 试下
