### ISSUE TITLE
在react项目里引入dumi，按照官方配置出现如下问题

### ISSUE THREAD

**Issue by DXDZY** [umijs/dumi#705]
### Question
1. 使用yarn dumi后，可以正常编译，并启动端口，但是dumi目录下会出现node_modules 文件夹，并且无限嵌套
![image](https://user-images.githubusercontent.com/15250383/119775242-ed27b700-bef5-11eb-9706-4d5d12b809e0.png)
2. 本地打开http://localhost:8000  页面报错
![image](https://user-images.githubusercontent.com/15250383/119775301-016bb400-bef6-11eb-9c50-4e06d265af47.png)

**Comment by xrkffgg** [comment]
项目名称 换个~
