### ISSUE TITLE
定制化的首页时，页面链接跳转不正常，并且无法指定logo

### ISSUE THREAD

**Issue by fanhualei** [umijs/dumi#707]
### 问题1：无法访问URL：
1、访问：https://wukong-doc.redhtc.com/
2、点击顶部页面导航，可以显示：https://wukong-doc.redhtc.com/daily
3、将：https://wukong-doc.redhtc.com/daily 复制到一个新打开的chrome浏览器地址栏中，显示空白页。

看下的文档，反复实验了，还是不行。
https://d.umijs.org/config#exportstatic

### 问题二：logo无法指定本地文件
这么配置不行
logo: 'images/logo.svg',

代码在https://gitee.com/fanhualei/wukong-doc 。 

可以下载到本地，运行yarn start ，【问题一】在 本地调试无法重现，但是部署到nginx就可以重现了。 【问题二】在本地调试，nginx都能重现。

> 下面是配置信息

```
  title: 'wukong-doc',
  favicon: 'https://zos.alipayobjects.com/rmsportal/TOXWfHIUGHvZIyb.svg',
  // favicon: '/images/logo.svg',
  logo: 'https://zos.alipayobjects.com/rmsportal/TOXWfHIUGHvZIyb.svg',
  // logo: 'images/logo.svg',
  outputPath: 'docs-dist',
  mode: 'site',

  exportStatic: {
    dynamicRoot: true,
    // htmlSuffix: true,
  },

```

**Comment by PeachScript** [comment]
nginx 需要配置所有路径请求都解析到 index.html，参考：https://stackoverflow.com/a/44098311

**Comment by fanhualei** [comment]
> nginx 需要配置所有路径请求都解析到 index.html，参考：https://stackoverflow.com/a/44098311

问题二：logo无法指定本地文件。 这个怎么解决呢？

**Comment by fanhualei** [comment]
我的nginx就是按照这个来设置的，还是不行。没关系，凑合用也行

server {
    listen 80;
    server_name wukong-doc.redhtc.com;
    rewrite ^(.*)$ https://${server_name}$1 permanent;
}



server {
  listen 443 ssl;

  server_name wukong-doc.redhtc.com;
  server_tokens off;

  root /opt/wukong-doc/;
  index index.html index.htm;
  ssl_certificate   /etc/nginx/conf.d/ss-cert/5699472_wukong-doc.redhtc.com.pem;
  ssl_certificate_key  /etc/nginx/conf.d/ss-cert/5699472_wukong-doc.redhtc.com.key;
  ssl_session_timeout 5m;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers on;

#  location / {
#    # 用于配合 browserHistory使用
#    try_files $uri $uri/ /index.html;
#   }


}

**Comment by PeachScript** [comment]
> 问题二：logo无法指定本地文件。 这个怎么解决呢？

文档里有 https://d.umijs.org/zh-CN/config#logo
