### ISSUE TITLE
👑 [需求]umijs中配置的alias无效

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/dumi#71]
在umijs中配置alias，tsx文件中使用import xx from '@'，在father-doc dev中无作用，用umi dev运行有作用

**Comment by Iixianjie** [comment]
很需要能够配置alias

**Comment by PeachScript** [comment]
dumi 是否还有此问题？

**Comment by PeachScript** [comment]
先 close 了，如果确定问题仍然存在请再 reopen
