### ISSUE TITLE
bug: run yarn dev and exit immediately

### ISSUE THREAD

**Issue by wenbin-im** [umijs/dumi#710]
### Versions

- dumi: master latest
- node: v14.3.0
- npm: V6.14.5
- OS: macOS 10.15.5
- Browser: None

### Steps to reproduce
1. 根目录下运行 `lerna clean && rm -rf node_modules`
2.  yarn
3. yarn watch
4. yarn dev

### What is Expected?
 yarn dev后，终端退出，输出错误日志：
```
(tag.text || "").trim is not a function
TypeError: (tag.text || "").trim is not a function
```

### What is actually happening?

dev server 运行正常

**Comment by wenbin-im** [comment]
发现是dumi依赖的react-docgen-typescript，在TypeScript 4.3上有Break Change，相关链接：[issues/356]( https://github.com/styleguidist/react-docgen-typescript/issues/356)

**Comment by PeachScript** [comment]
dumi 仓库已锁定 typescript，计划 PR 上游仓库最最终修复，该 issue 关闭
