### ISSUE TITLE
bug: code 使用 inline 还会出现 copy 按钮

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/dumi#713]
![image](https://user-images.githubusercontent.com/11746742/120451508-16e45080-c3c4-11eb-8645-e9c0bea0a870.png)

### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
```
<code src="./demos/base.tsx" inline />
```

**Comment by PeachScript** [comment]
这感觉不像是 code 标签导致的，inline 是在编译时处理的，不是运行时隐藏 demo 壳的，dumi 官网的 inline 没有发现这个情况：https://d.umijs.org/zh-CN/guide/basic#%E7%9B%B4%E6%8E%A5%E5%B5%8C%E5%85%A5%E6%96%87%E6%A1%A3

**Comment by xiaohuoni** [comment]
我正在定位，我的错，上面还有一个空白代码段
