### ISSUE TITLE
feat: make dynamic route static when dumi build

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#715]
### Description
组件 demo 的单独访问路由是 `/~demos/:uuid`，但动态路由在很多部署平台/HTTP Server 上都需要手动处理，直接将产物进行部署会访问 404

### Solution
dumi build 的时候根据 demo id 列表把 `/~demos/:uuid` 下的路由都静态化

**Comment by Carnia** [comment]
+1，很需要这个方案：`dumi build 的时候根据 demo id 列表把 /~demos/:uuid 下的路由都静态化`
