### ISSUE TITLE
其它脚手架集成 dumi，logo 无法修改

### ISSUE THREAD

**Issue by FruitJ** [umijs/dumi#716]
### Question
您好，我是在 webpack 上面将 dumi 集成进来的，工作起来一切正常，但是当我打算修改页面的 logo 的时候发现怎么也无法修改成功，还请开发同学可以提供一个解决方案。

### Sample Code
/config/config.js
```js
import { defineConfig, } from 'dumi';

export default defineConfig({
    chainWebpack(memo) {
        memo.plugins.delete('copy');
    },
    title: 'AtheneUI',
    mode: 'site',
    logo: '/images/favicon.png',
    outputPath: 'site',
    theme: {
        '@primary-color': '#DDDDDD',
    },
    navs: [
        {
            title: '首页',
            path: '#',
        },
        {
            title: '组件',
        },
        {
            title: 'GitHub',
            path: 'https://github.com/AtheneUI/athene-ui',
        },
        {
            title: '更新日志',
            path: 'https://www.baidu.com',
        },
    ],
});
```
### 目录结构
![image](https://user-images.githubusercontent.com/35673570/120748651-b8d77a80-c535-11eb-8ff4-5fef879d8293.png)
### 页面 logo
![image](https://user-images.githubusercontent.com/35673570/120749007-5a5ecc00-c536-11eb-94d9-cc71b6a6c3bb.png)

**Comment by PeachScript** [comment]
> `memo.plugins.delete('copy');`

会取消托管 public 文件夹下的静态资源

**Comment by FruitJ** [comment]
> > `memo.plugins.delete('copy');`
> 
> 会取消公共一个下的资源

@PeachScript 谢谢您的解答，目前面临的问题已经解决。没注意过这项配置，但是我还有一个疑问就是 dumi 官网的是这样配置的，它为什么要这样配置呢 ? 
![image](https://user-images.githubusercontent.com/35673570/120749730-a9f1c780-c537-11eb-9640-46c92abea523.png)

**Comment by PeachScript** [comment]
<img width="541" alt="图片" src="https://user-images.githubusercontent.com/5035925/120756749-3bfecd80-c542-11eb-9248-728393d0181d.png">

**Comment by FruitJ** [comment]
谢谢
