### ISSUE TITLE
bug: 在次级"-"标签里面写代码块会导致下一个二级标题在toc里面消失

### ISSUE THREAD

**Issue by Carnia** [umijs/dumi#717]
### Versions

- dumi: ^1.0.26
- node: v12.10.0
- npm: 7.7.4
- OS: macOS 10.15.6 (19G2021)
- Browser: chrome 91.0.4472.77

### 如何复现及说明

一般在markdown里，使用"-" 标签可以生成小标题"·"，常用用法是：
- 小标签1
- 小标签1
  - 子级小标签1
  ```js
  some code
  ```
  - 子级小标签2
 
 但是在dumi在开发和生产时，在二级小标签（也就上述`子级小标签1`）后面，**使用和标签同级的代码块会导致下一个二级标题（##）在toc中消失**，详见demo中的描述：

**下面是demo开始：**
# some title

## sub-title1

- msg1
  - msg1-1
  - msg1-2
  ```js
  console.log("这里的二级代码块（任意语言）会导致"sub-title2"在toc里面无法显示，有时候也会影响到一级标题（##）");
  ```
  - msg1-2

## sub-title2

- msg2
  - msg2-1
  - msg2-2
  - msg2-2

```js
console.log("这里的一级代码块不会影响到相邻二级标签的toc显示");
```

## sub-title3
**demo结束**

### 补充说明
- 在开发模式时（yarn dumi），上述异常会100%必现，在不改变任何文件的同时进行一次文件保存（触发热更新），上述异常会被自动修复（toc展示完整）。
- build后的文件，部署后上述异常100%必现。
- 相关配置文件我放在评论里。

**Comment by Carnia** [comment]
package.json:
```json
{
  "name": "dumi",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dumi": "cross-env APP_ROOT=./ dumi dev",
    "dumi-build": "cross-env APP_ROOT=./ dumi build"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cross-env": "^6.0.3",
    "dumi": "^1.0.26",
    "typescript": "^3.7.4"
  }
}
```
.umirc.ts
```js
export default {
  chainWebpack(memo) {
    memo.plugins.delete("copy");
  },
  resolve: {
    passivePreview: false,
    previewLangs: [],
  },
};
```
error.md(下面内容中的"/```"去掉"/")
```markdown
# some title
## sub-title1
- msg1
  - msg1-1
  - msg1-2
  /```js
  console.log("这里的二级代码块（任意语言）会导致"sub-title2"在toc里面无法显示，有时候也会影响到一级标题（##）");
  /```
  -msg1-2
## sub-title2
- msg2
  - msg2-1
  - msg2-2
  - msg2-2
  /```js
  console.log("这里的一级代码块不会影响到相邻二级标签的toc显示");
  /```
## sub-title3
```

**Comment by PeachScript** [comment]
> 一个必现的例子(下面内容中的"/```"去掉"/")：
> error2.md
> 
> ```lisp
> # title
> 
> ## sub-title
> 
> 1. one
> 
>     /```tsx
>     <div>
>       ...
>     </div>
>     /```
> 1. two
> 
> ## sub-title2
> 
> msg
> ```

用这个无法复现，请确认安装到 node_modules 里的 dumi 版本是不是最新版

**Comment by Carnia** [comment]
新版本（1.1.0版本）已修复。
