### ISSUE TITLE
bug: 最新版dumi所有的有序无需列表前的序号和原点消失

### ISSUE THREAD

**Issue by innocces** [umijs/dumi#718]
### Versions

- dumi: 1.1.19
- node: 12.22.1
- npm: 6.14.12
- OS: macOS 11.4
- Browser: Chrome 91

### Steps to reproduce
无序/有序列表序号展示异常

### What is Expected?
序号展示正常

**Comment by PeachScript** [comment]
dumi 官网正常展示，检查是不是组件库有全局样式

**Comment by innocces** [comment]
> dumi 官网正常展示，检查是不是组件库有全局样式
当前编译结果：
![image](https://user-images.githubusercontent.com/38065966/121003742-74abda80-c7c0-11eb-9433-e64d79323386.png)

官网样式:
![image](https://user-images.githubusercontent.com/38065966/121003826-87261400-c7c0-11eb-8274-a8b62ac356b9.png)

=。-  感觉是编译的时候样式就丢掉了

**Comment by PeachScript** [comment]
都是浏览器默认样式，不存在编译时丢掉一说

**Comment by innocces** [comment]
> 都是浏览器默认样式，不存在编译时丢掉一说

确实~
