### ISSUE TITLE
lerna 下报错，是什么情况

### ISSUE THREAD

**Issue by chenguzhen87** [umijs/dumi#720]
![image](https://user-images.githubusercontent.com/28331609/121181466-9e363600-c894-11eb-81bf-01e5bf65a0e0.png)

**Comment by DivXPro** [comment]
我也有这个问题

**Comment by chenguzhen87** [comment]
@PeachScript demo地址
https://github.com/chenguzhen87/video-range-bar

**Comment by chenguzhen87** [comment]
已重现原因了,脚手架生成项目没有依赖lerna，我全局安装lerna,结果跑不起来。
解决办法：在工作空间目录下执行 yarn add lerna --D -W 来安装lerna
