### ISSUE TITLE
bug: React.createElement is undefined

### ISSUE THREAD

**Issue by imcuttle** [umijs/dumi#725]
### Versions

- dumi: 1.1.19
- node: 12.20.1
- npm: 6.14.10
- OS: Mac
- Browser:

### Steps to reproduce

1. dumi dev

![image](https://user-images.githubusercontent.com/13509258/122188518-9d1f8d00-cec2-11eb-912f-88a6bf78fc97.png)

发现 React is undefined, 由于 dumi 生成的 demos/index.ts 里面有 var React

**Comment by imcuttle** [comment]
https://github.com/umijs/dumi/blob/d5a02089f584eea294957b76ec21e19da97a973f/packages/preset-dumi/src/transformer/demo/index.ts#L135

**Comment by PeachScript** [comment]
有意为之，写 JSX 要把 React 引入进来，不能依赖 Umi 自动注入的顶层变量

**Comment by imcuttle** [comment]
> 有意为之，写 JSX 要把 React 引入进来，不能依赖 Umi 自动注入的顶层变量

@PeachScript 请问是需要在 Markdown 里面明确书写如下引入吗：
~~~~
```jsx
import React from 'react'
```
~~~~

**Comment by PeachScript** [comment]
参考 https://stackoverflow.com/a/51388776
