### ISSUE TITLE
lerna 下报错，是什么情况

### ISSUE THREAD

**Issue by DivXPro** [umijs/dumi#730]
### Question
运行 dumi dev 报错
Cannot find module 'lerna/package.json'

### Sample Code
这是出现这个问题的仓库地址 https://github.com/toy-box/toybox

**Comment by DivXPro** [comment]
应该是使用全局的leran的关系

**Comment by xuehebinglan** [comment]
所以是咋解决呀？

**Comment by soeasyjx** [comment]
怎么解决

**Comment by AllenMinD** [comment]
应该是因为在 package.json 中没有写上 lerna 的依赖 。

在 package.json 中加上 lerna 依赖，然后删掉 node_module 和 lock 文件，再执行 yarn 重新装一下依赖应该就好了。

![image](https://user-images.githubusercontent.com/15014595/176870289-20a0b31d-dcf9-45c0-97dc-75839d684274.png)
