### ISSUE TITLE
bug: nested list not working if indent by 2 spaces

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#733]
### Versions

- dumi: 1.1.20
- node: 15.6.0
- npm: 7.4.0
- OS: macOS 11.2.3 BigSur
- Browser: Firefox 89.0.1

### Steps to reproduce

Create list with Markdown syntax then `dumi dev`:
```md
1. xx
  1. xx
2. xx
```

### What is Expected?

Rendered 2-level list.

### What is actually happening?

Rendered single level list, but indent by **more than 2 spaces** will works properly.

**Comment by PeachScript** [comment]
refer: https://github.com/remarkjs/remark/issues/764

**Comment by ChristianMurphy** [comment]
This is by design, it's how markdown works, when markdown has  less than the minimum indent for nesting lists, a single level list is created.
This is documented in the commonmark specification at https://spec.commonmark.org/0.30/#example-310 and https://spec.commonmark.org/0.30/#example-311

To improve the developer experience, consider using https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-recommended#readme to highlight places where syntax may be confusing or misused.

**Comment by ChristianMurphy** [comment]
The behavior is also fairly consistent across markdown flavors beyond just commonmark.
gfm, pandoc, kramdown, python-markdown, marked, and most other markdown flavors handles list indent the same way https://babelmark.github.io/?text=1.+xx%0A++1.+xx%0A2.+xx

**Comment by PeachScript** [comment]
@ChristianMurphy thank you for reply this issue with the detailed explanation ❤️ 

For the commonmark specification, I have 2 questions about it:

1. why 2 spaces intent item will be treated as single-level item in the [most implementations](https://babelmark.github.io/?text=1.+xx%0A++1.+xx) but remark will treat it as nested list
2. GitHub also treat 2 spaces intent item as nested list, for example:

```md
- a
  - b
- c
```

will render:

- a
  - b
- c

And Visual Studio Code editor is the same:

<img width="356" alt="VS Code" src="https://user-images.githubusercontent.com/5035925/123908656-63fb1880-d9aa-11eb-8cc7-a3de4a7ae16e.png">


So is it means the most implementations not the common implementation?

**Comment by ChristianMurphy** [comment]
A point of clarification, ordered lists need three or more spaces indent to nest, unordered two or more to nest.

https://babelmark.github.io/?text=1.+A%0A++1.+A%0A%0A*+A%0A+*+A%0A%0A1.+A%0A+++1.+A%0A%0A*+A%0A++*+A

https://astexplorer.net/#/gist/81dd323bf800689e8e5479cfa7b0ee8d/ec430603d07531397796e126061a8f80b3cb198c

The behavior is consistent across implementations and on github itself:

****

1. A
  1. A

* A
 * A

1. A
   1. A

* A
  * A

****

> why 2 spaces intent item will be treated as single-level item in the most implementations but remark will treat it as nested list

> GitHub also treat 2 spaces intent item as nested list

Remark does the same as the other implementations, see the clarification and examples above.

**Comment by PeachScript** [comment]
@ChristianMurphy got it, I made a comparison between ordered list and unordered list by mistake, thank you very much!
