### ISSUE TITLE
bug: babel 模式下，dumi dev 找不到 css 文件

### ISSUE THREAD

**Issue by imyzf** [umijs/dumi#737]
### Versions

- dumi: v1.0.14
- node: v12.21.0
- npm: v6.14.11
- OS: 11.4 (20F71)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/8298849/123241113-73461600-d513-11eb-8cf8-aebd512693a6.png)

1.  git clone https://github.com/imyzf/dumi-test.git
2. npm i
3. npm start

### What is Expected?

成功启动 dev server，引入 css 文件

### What is actually happening?

![image](https://user-images.githubusercontent.com/8298849/123240957-56114780-d513-11eb-8234-1deca159a353.png)

使用`npm run build`，是有生成 index.css 文件的，说明 father-build 没问题

另外比较奇怪的一点，有时候跑过 `npm run build` 以后，这个报错会消失，页面正常展示，但不是 100% 稳定复现。

**Comment by PeachScript** [comment]
要 `npm run build -- --watch` 吧

**Comment by imyzf** [comment]
> 要 `npm run build -- --watch` 吧

试了还是不行额

**Comment by PeachScript** [comment]
需要手动配置下 lib 的 alias 到项目目录，默认是指向 src 目录的，但 CSS 的输出路径不是 src，refer: https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/plugins/features/symlink.ts#L52

**Comment by imyzf** [comment]
> 需要手动配置下 lib 的 alias 到项目目录，默认是指向 src 目录的，但 CSS 的输出路径不是 src，refer: https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/plugins/features/symlink.ts#L52

感谢，可以了。

-----

总结一下这里的场景，方便后面大家查阅。

首先我开启了 babel 模式编译，并把 less 转换成了 css。

```ts
// .fatherrc.ts
export default {
  esm: 'babel',
  cjs: 'babel',
  lessInBabelMode: true,
};
```

编译后的目录结构：

```
├── es
│   ├── index.css
│   ├── index.d.ts
│   └── index.js
├── lib
│   ├── index.css
│   ├── index.d.ts
│   └── index.js
├── src
│   ├── index.less
│   └── index.tsx
```

在 markdown 里引入 `import 'dumi-test/lib/index.css';`，dumi 内部做了目录映射`lib -> src`，会在 src 目录下查找 `index.css`，是不存在的，需要修改 alias，重新定位到 lib 目录下：

```ts
// .umirc.ts
import { defineConfig } from 'dumi';
import path from 'path'

import packageJson from './package.json'

export default defineConfig({
  chainWebpack(memo) {
    memo.resolve.alias.set(`${packageJson.name}/lib`, path.resolve(__dirname, 'lib'));
  },
});

```

然后需要在 dev 的时候，需要使用 `npm run build -- --watch`，不然文件不会更新。
