### ISSUE TITLE
设置了 resolve.includes 为 src 之后还是会将根目录下的 README.md 包含进来

### ISSUE THREAD

**Issue by jiyingzhi** [umijs/dumi#740]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

**Comment by PeachScript** [comment]
首页是必须的，resolve 目录下没有 index.md 就会 fallback 到 README

**Comment by ldwonday** [comment]
我的resolve配置如下
```
resolve: {
    includes: [
      'packages/thor-components',
      'packages/thor-schema',
      'packages/thor-datasource',
      'packages/thor-theme',
      'docs',
    ],
  },
```

docs下面有index.md，但是还是加载README，routes部分内容如下
![image](https://user-images.githubusercontent.com/4630157/146110901-eaeaff9f-d37c-445f-9a8f-06b75b729820.png)
，什么问题啊！
