### ISSUE TITLE
bug: 自动生成导航和分组错误

### ISSUE THREAD

**Issue by tazyong** [umijs/dumi#741]
### Versions

- dumi: 1.1.20
- node: 14.15.3
- npm: 6.14.9
- OS: Windows 10
- Browser: Google Chrome 91.0.4472.114

### Steps to reproduce

无。

### What is Expected?

与官方文档描述一致。

### What is actually happening?

site 模式下，在 `docs`、`src`、`packages/pkg/src` 目录中新建非 index 的 md 文件，会自动生成导航和分组，这与 [官方文档](https://d.umijs.org/zh-CN/guide/basic#约定式路由) 不符。

![image](https://user-images.githubusercontent.com/24738011/123532540-8be74380-d740-11eb-86b1-b8b958942243.png)

**Comment by PeachScript** [comment]
看 issue 描述和文档是相符的，期望结果是怎样的

**Comment by tazyong** [comment]
如之前的截图所示，`/path/to/src/hello.md` 这种文件

应当生成：
- 导航：无
- 分组：无
- 页面路由：/hello

实际生成：
- 导航：/hello
- 分组：/hello
- 页面路由：/hello

这使得首页的左侧菜单无法显示，而显示在右上角的导航上。

**Comment by tazyong** [comment]
这个是就是我期待的结果

代码地址：https://codesandbox.io/s/dumi-demo-js95o

![image](https://user-images.githubusercontent.com/24738011/123577915-49d50500-d807-11eb-834c-3836c967dbf9.png)

**Comment by PeachScript** [comment]
实际生成是对的，site 模式设计的初衷是首页不展示侧边菜单，以及首页是独立于其他导航条目的存在

**Comment by tazyong** [comment]
这与文档不符，这属于 BUG！不应急于关闭 issues，解决问题才是对的

![image](https://user-images.githubusercontent.com/24738011/123578631-d16f4380-d808-11eb-8903-84a91ab50732.png)

**Comment by PeachScript** [comment]
@tazyong 不好意思看漏了文档的错误，文档已修复，感谢反馈
