### ISSUE TITLE
dumi-theme-mobile 的预览区域可以展示所有的 demo？

### ISSUE THREAD

**Issue by jiyingzhi** [umijs/dumi#742]
如下图所示展示所有的 demo，而不是滚动到当前区域时才展示：
![image](https://user-images.githubusercontent.com/21698836/123582069-b9e78900-d80f-11eb-9870-15f7aedfefac.png)

**Comment by PeachScript** [comment]
暂不支持，上图这种建议写成一个 demo

**Comment by karmiy** [comment]
有实现了 dumi-theme-phone 解决这个问题
