### ISSUE TITLE
有Gatsby为啥还要dumi

### ISSUE THREAD

**Issue by DreamPWJ** [umijs/dumi#743]
### Question
dumi是针对组件场景的Gatsby？

**Comment by PeachScript** [comment]
两者除了『支持静态站点研发』的定位有重合以外没有其他关联，Gatsby 的定位是通用应用开发框架、更靠近 [Umi](https://umijs.org)

如果要类比的话，docz 是面向组件研发场景的 Gatsby，dumi 是面向组件研发场景的 Umi

**Comment by DreamPWJ** [comment]
明白了
