### ISSUE TITLE
怎么使用主题色呢？

### ISSUE THREAD

**Issue by hellojayjay** [umijs/dumi#747]
### Question

项目是umi的，在.umirc.ts中定义了primary-color。

用dumi创建了组件库，请问怎么在dumi组件库中使用primary-color呢？比如自定义了一个div，需要background-color: @primary-color

**Comment by hellojayjay** [comment]
自问自答。
在组件库的.umirc.ts中配置：
`
theme: {
  'primary-color': 'primary-color'
}
`

**Comment by PeachScript** [comment]
.umirc 是只用于文档站点的主题变量配置；组件库的变量可以参考 antd 创建 theme/default.less 维护变量，再由组件库其他 Less 文件引入

**Comment by hellojayjay** [comment]
> .umirc 是只用于文档站点的主题变量配置；组件库的变量可以参考 antd 创建 theme/default.less 维护变量，再由组件库其他 Less 文件引入

有没有可能组件库中的less变量是来自于 依赖这个组件库的umi项目的.umirc.ts中的primary-color呢？

**Comment by PeachScript** [comment]
目前不行，.umirc 是文档构建配置、.fatherrc 是组件打包配置，如果只配置 .umirc 那么组件打包是不生效的，走独立 theme 文件比两边都配置更好维护；未来文档构建和组件打包一体化之后可以实现上面的效果

**Comment by PeachScript** [comment]
并且独立 theme 文件也便于用户二次使用组件库的 theme，配置在 .umirc 里意味着用户在自己的项目里只能使用这个组件库的 CSS，想用 Less 会找不到变量

**Comment by hellojayjay** [comment]
> 并且独立 theme 文件也便于用户二次使用组件库的 theme，配置在 .umirc 里意味着用户在自己的项目里只能使用这个组件库的 CSS，想用 Less 会找不到变量

好的，感谢！
