### ISSUE TITLE
左侧菜单 最多只能生成二级吗？

### ISSUE THREAD

**Issue by 18583952605** [umijs/dumi#748]
site 模式下

文件目录结构大概是这样的
```
/docs
    /一级
        /二级
            /三级
                /index.md
```

预期也是类似上图的左侧菜单

实际不是

**Comment by PeachScript** [comment]
只支持两级，有特殊需求可以通过主题 API 做定制化：https://d.umijs.org/zh-CN/theme/development

**Comment by florencemu** [comment]
https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠
