### ISSUE TITLE
feat: full-mfsu support

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#749]
### Description

Known issues:
- [ ] local theme import default theme
- [ ] Ant Design Charts project `await import('@antv/util')` error

**Comment by chenshuai2144** [comment]
```
import React, { useContext, useEffect, useMemo, useState } from 'react';
import Layout from 'dumi-theme-default/src/layout';
import dumiContext from '@umijs/preset-dumi/lib/theme/context';
```

**Comment by sorrycc** [comment]
相关代码，https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/plugins/features/theme.ts#L50

**Comment by PeachScript** [comment]
umi 层已处理，dumi 项目可开启 mfsu 实现编译提速，issue 关闭
