### ISSUE TITLE
给内置组件传的参数，只能是字符串吗？

### ISSUE THREAD

**Issue by 18583952605** [umijs/dumi#752]
### Question
写了个内置组件，其中一个属性想传array，目前是转成json字符串后传的，因为直接传会报错

### Sample Code
```
<CardPro
  data='[{"a": 1}]'
/>
```

**Comment by xrkffgg** [comment]
`data={[]}`

**Comment by PeachScript** [comment]
Sample Code 的值不是有效 JSON 字符串，`data='[{ "a": 1 }]'`

**Comment by PeachScript** [comment]
> `data={[]}`

这个已经不支持了，是 1.0 版本的用法 👀

**Comment by 18583952605** [comment]
> Sample Code 的值不是有效 JSON 字符串，`data='[{ "a": 1 }]'`

嗯呐 已修改

**Comment by 18583952605** [comment]
@PeachScript   只能传字符串吗？

**Comment by PeachScript** [comment]
@18583952605 弄错了，自定义组件确实只支持字符串，JSON 字符串自动 parse 只适用于 `code` 和 `API`
