### ISSUE TITLE
bug: 多语言版本切换中文时候，会默认分成多个分组

### ISSUE THREAD

**Issue by zjjjavascript** [umijs/dumi#754]
### Versions

- dumi:1.0.16
- node:12.19.0
- npm:6.14.9
- OS:MacOS
- Browser:Chrome

### Steps to reproduce
1.目录结构
![image](https://user-images.githubusercontent.com/26682866/124459923-4d492d00-ddc1-11eb-9490-f42f5634a4f0.png)
2.中文md配置
![image](https://user-images.githubusercontent.com/26682866/124459951-56d29500-ddc1-11eb-8501-0d4202cd39cd.png)
![image](https://user-images.githubusercontent.com/26682866/124460048-736ecd00-ddc1-11eb-9be7-1b9d765dd6ce.png)
![image](https://user-images.githubusercontent.com/26682866/124460059-779aea80-ddc1-11eb-9914-e6f0ee4b1b47.png)
3.当前菜单展示
1）中文
![image](https://user-images.githubusercontent.com/26682866/124460114-88e3f700-ddc1-11eb-8c7e-d5c3113e8d7d.png)
2）英文
![image](https://user-images.githubusercontent.com/26682866/124460137-8ed9d800-ddc1-11eb-8fce-1b2ab5c51a83.png)

### What is Expected?
期望中文菜单和英文菜单保持一致

**Comment by PeachScript** [comment]
Duplicated with #755
