### ISSUE TITLE
创建中文md文件的时候，指定同一个Group，会变成两个分组，英文md不会有这个问题

### ISSUE THREAD

**Issue by zjjjavascript** [umijs/dumi#755]
文件结构：
![image](https://user-images.githubusercontent.com/26682866/124443328-2afae380-ddb0-11eb-8151-46603ee9e7c0.png)
中文md文件：
![image](https://user-images.githubusercontent.com/26682866/124443389-36e6a580-ddb0-11eb-804a-a22005e9cb6a.png)
![image](https://user-images.githubusercontent.com/26682866/124443404-3a7a2c80-ddb0-11eb-91a6-d648e1086508.png)
对应的菜单变成了：
![image](https://user-images.githubusercontent.com/26682866/124443435-4239d100-ddb0-11eb-96e7-b7704f0ee6a9.png)
![image](https://user-images.githubusercontent.com/26682866/124443483-4d8cfc80-ddb0-11eb-8d25-20d40d27fe71.png)

**Comment by zjjjavascript** [comment]
> Hello @zjjjavascript. In order to facilitate location and troubleshooting, we need you to provide a realistic example. You can create a dumi project by clicking [here](https://github.com/umijs/dumi-template/generate) and provide the GitHub warehouse address and reproduce examples.
> 
> 你好 @zjjjavascript, 为了方便定位和排查问题，我们需要你提供一个重现实例。你可以通过点击 [此处](https://github.com/umijs/dumi-template/generate) 创建一个 dumi 项目并提供 GitHub 仓库地址和重现实例。
仓库地址如下：
https://github.com/zjjjavascript/dumi-tempate
只是把Foo组件放在了components文件夹下，并且同级创建了Hello组件

**Comment by PeachScript** [comment]
group 的唯一键是 `path`，`path` 一致会被认定为同一个分组

**Comment by zjjjavascript** [comment]
> group 的唯一键是 `path`，`path` 一致会被认定为同一个分组

现在设置了同一个path就会变成中英文一起出现了，是我的目录结构不对嘛 
![image](https://user-images.githubusercontent.com/26682866/124538822-dd818380-de4e-11eb-9a17-576663b22a38.png)
![image](https://user-images.githubusercontent.com/26682866/124538841-e6725500-de4e-11eb-945d-ce9126954253.png)
![image](https://user-images.githubusercontent.com/26682866/124538861-ef632680-de4e-11eb-9969-393a20e91d13.png)

**Comment by zjjjavascript** [comment]
解决了，是我的命名有问题，同时用了component和components，导致路由和菜单才错乱
