### ISSUE TITLE
bug: docs/index.md中title或desc使用@符号导致站点模式失效

### ISSUE THREAD

**Issue by hellojqk** [umijs/dumi#757]
---
hero:
  title: @xxx/component
  desc: @xxx/component site example
  actions:
    - text: Getting Started
      link: /components
features:
  - icon: https://gw.alipayobjects.com/zos/bmw-prod/881dc458-f20b-407b-947a-95104b5ec82b/k79dm8ih_w144_h144.png
    title: Feature 1
    desc: Balabala
  - icon: https://gw.alipayobjects.com/zos/bmw-prod/d60657df-0822-4631-9d7c-e7a869c2f21c/k79dmz3q_w126_h126.png
    title: Feature 2
    desc: Balabala
  - icon: https://gw.alipayobjects.com/zos/bmw-prod/d1ee0c6f-5aed-4a45-a507-339a4bfe076c/k7bjsocq_w144_h144.png
    title: Feature 3
    desc: Balabala
footer: Open-source MIT Licensed | Copyright © 2020<br />Powered by [dumi](https://d.umijs.org)
---

## 介绍

使用 yarn create @umijs/dumi-lib --site 创建站点模式后正常打开站点模式。
修改了docs/index.md如上方配置，其中包含@符号，导致站点模式失效。

**Comment by PeachScript** [comment]
配置要遵循 YAML 语法，特殊值用引号包裹，可以在线测试能不能正常解析：https://yaml-online-parser.appspot.com/
