### ISSUE TITLE
bug: 使用过一次移动端的主题(dumi-theme-mobile)，原来的pc端组件项目也变成移动端主题了。

### ISSUE THREAD

**Issue by walljser** [umijs/dumi#765]
### Versions

- dumi: 1.1.23
- node: 12.10.0
- npm:  6.10.3
- OS: Windows
- Browser: Chrome

### Steps to reproduce
安装的主题：
![image](https://user-images.githubusercontent.com/38822081/125044021-22671d80-e0ce-11eb-8070-1f5e4e63bdff.png)

运行起来效果：
![image](https://user-images.githubusercontent.com/38822081/125044194-504c6200-e0ce-11eb-954d-87ab8278423b.png)

### What is Expected?
正常显示为PC端主题风格

### What is actually happening?
之前使用时正常的，有一个新项目尝试依赖dumi-theme-mobile之后出的问题

**Comment by PeachScript** [comment]
浏览器移动端模拟器打开了？

**Comment by PeachScript** [comment]
这个和移动端主题没关系，默认主题也有手机端适配

**Comment by walljser** [comment]
![image](https://user-images.githubusercontent.com/38822081/125045964-21cf8680-e0d0-11eb-9214-d53a66e97242.png)
@PeachScript 不是浏览器移动端模拟器的原因，关掉也是显示不正常

**Comment by walljser** [comment]
![image](https://user-images.githubusercontent.com/38822081/125046557-b3d78f00-e0d0-11eb-834b-c1f3093076a9.png)

**Comment by PeachScript** [comment]
请提供复现仓库
