### ISSUE TITLE
bug: 移动端样式展示问题

### ISSUE THREAD

**Issue by taomas** [umijs/dumi#766]
### Versions

- dumi:v1.0.13
- node:v14.15.5

### Steps to reproduce
移动端的文本复制功能，在chrome的模拟器上展示复制按钮图标正常，但是在手机上多了一个小尖角

### What is Expected?
点击代码展示区域时，只展示复制按钮图标，不要展示多余的尖角图标

### What is actually happening?
当通过手机微信或者safari浏览器访问以下页面时，点击代码展示框，出现复制按钮时，多出现了半个尖角图标

访问地址：https://d.umijs.org/zh-CN/config

展示图片：
![image](https://user-images.githubusercontent.com/17002702/125055418-c0acb080-e0d9-11eb-967c-853aecc06d42.png)

**Comment by PeachScript** [comment]
v1.1.25 已修复
