### ISSUE TITLE
开发模式没问题，构建打包后，部分代码丢失

### ISSUE THREAD

**Issue by NARUTOne** [umijs/dumi#768]
### Question
由于有些代码在源码中是直接引入执行的  例：`import './a.js'`，开发模式写demo时没问题，构建打包后出现这部分代码未打包进去
### Sample Code
![image](https://user-images.githubusercontent.com/18441915/125269209-103de700-e33b-11eb-850b-8142fd1ba2e4.png)

**Comment by NARUTOne** [comment]
dumi  V 1.1.0

**Comment by PeachScript** [comment]
检查 `sideEffects` 配置，文档构建是默认开 `tree-shaking` 的

**Comment by NARUTOne** [comment]
哦了，懂了，谢谢
