### ISSUE TITLE
bug: umi 创建 app 启动报错

### ISSUE THREAD

**Issue by crazyair** [umijs/dumi#77]
### Versions
- father-doc: latest
- node: 10
- npm:
- OS:
- Browser:

### Steps to reproduce

`yarn create umi` 选择 app
`father-doc dev`  报错

`Plugin apply failed: ENOENT: no such file or directory, open '/Users/xxx/test/f/src/layouts/index'`

**Comment by PeachScript** [comment]
请使用 dumi 的脚手架进行初始化：https://d.umijs.org/guide/getting-started#%E8%84%9A%E6%89%8B%E6%9E%B6%E5%88%9D%E5%A7%8B%E5%8C%96
