### ISSUE TITLE
dumi build 报错  [Error: ENOENT: no such file or directory, mkdir '\dist\~demos\:uuid'

### ISSUE THREAD

**Issue by YeWills** [umijs/dumi#771]
你好，windows 10 电脑下 dumi build 执行报错， dumi版本 1.1.19  ， node 12.8.0：
```
[Error: ENOENT: no such file or directory, mkdir 'D:\workplace\xxxx\dist\~demos\:uuid'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\workplace\\xxxx\\dist\\~demos\\:uuid'
}
build failed
Error: build failed
```

**Comment by PeachScript** [comment]
Duplicated with #473 , closed

**Comment by YeWills** [comment]
我看了#473 关联的解决方案：
1. exportStatic 已兼容 Windows，构建可以成功但产出的动态路由是不能直接使用的，后续版本会优化成上面的方案，issue 关闭
2. dumi 在构建的时候我们把路由铺开来？比如 dev 的时候是 /~demos/:uuid，但构建之后就变成 /~demos/a、~demos/b 之类的
3. windows 环境下开启 exportStatic 打包规避方案 #5921
目前有以上解决方案吗？上面方案中：
方案1 应该还没有发布版本吧；
方案2 这种我没有实践过，不知道如何把路由铺开来；
方案3 使用action的方案不好，因为安全问题，不能使用github
