### ISSUE TITLE
bug: dumi build 无法根据自定义的customStyleName 进行样式按需导入

### ISSUE THREAD

**Issue by yedegesong** [umijs/dumi#773]
### Versions

- dumi: 1.1.23
- node: v12.10.0
- npm: 6.10.3
- OS:
- Browser: chrome

### Steps to reproduce
.umirc.ts 配置开发按需加载：
   [
      "import",
      {
        libraryName: "waterx",
        //libraryDirectory: '../../components',
        "customName": (name: string, file: object) => {
          console.log(name)
          // 设置自定义导入路径
          return `${path.resolve('components')}/${name}`;
        },
        customStyleName: name => {
          // 设置自定义样式导入路径
          return `${path.resolve('components')}/${name}/style/index.ts`; // 注意：这里 ./ 不可省略
        }
      },
      "waterx",
    ],
### What is Expected?
开发环境下:dumi dev 组件样式正常按需加载，执行dumi build 构建出来的文档库组件样式应该也是按需加载打包出来的；
### What is actually happening?
执行dumi build 构建出来的文档库组件样式没有跟开发环境一样，无法根据自定义的customStyleName 进行样式按需导入；

**Comment by PeachScript** [comment]
检查是不是 `sideEffect` 配置的问题，refer: https://github.com/umijs/dumi/issues/225#issuecomment-655564649
