### ISSUE TITLE
bug: 与浏览器插件兼容问题

### ISSUE THREAD

**Issue by crazyair** [umijs/dumi#78]
### Versions
- father-doc:latest
- node:latest
- npm:latest
- OS:mac
- Browser:chrome

### Steps to reproduce

下载 father-doc 执行 `yarn dev` ；
浏览器插件安装 lastpass 或者 Console Importer 我这里是看到这2个会在控制台打印 error

![image](https://user-images.githubusercontent.com/7971419/74114143-4b3a6900-4be3-11ea-81df-98d0b68ca90b.png)

测试后发现是因为加了 

![image](https://user-images.githubusercontent.com/7971419/74114135-3cec4d00-4be3-11ea-9d73-4671d89cad14.png)

这个导致的

**Comment by crazyair** [comment]
刚才安装 Console Injector  控制台又多一个错误

![image](https://user-images.githubusercontent.com/7971419/74114227-b8e69500-4be3-11ea-92d2-57d71a2a5f3f.png)

**Comment by PeachScript** [comment]
插件抛出的错误应该由插件来处理吧，issue 先关闭了
