### ISSUE TITLE
dumi编译较慢，请问是否可以使用umi的MFSU方案

### ISSUE THREAD

**Issue by lzx-cloud** [umijs/dumi#782]
### 把antd组件源码使用dumi进行二次开发，编译的过程中，发现每次启动的时候会很卡，热更新的时候也会很慢

看umi里面有提供MFSU方案，但是发现dumi里面的umi版本较低，请问有什么办法可以减少dumi的编译的时间吗？

**Comment by lzx-cloud** [comment]
对了，我使用的是dumi-template

**Comment by PeachScript** [comment]
dumi 没限制 umi 版本，可以开启 MFSU 试试看

**Comment by lzx-cloud** [comment]
你好，使用了，但是启动的时候还是比较忙，大概要10分钟左右
另外MFSU容易卡在88 或者89就不动了，需要等很久才行，一旦有错误就启动不了，也不报错

**Comment by PeachScript** [comment]
MFSU 只打包项目依赖，如果项目源代码非常大是有可能会慢，但 10min 的启动耗时我们目前最大的项目即便不开 MFSU 也没有遇到过，需要提供更多信息才能排查问题原因
