### ISSUE TITLE
dumi 可以不提前编译 code block 中的代码吗

### ISSUE THREAD

**Issue by jiyingzhi** [umijs/dumi#786]
我的项目是跑在 Vite 中的，所以和 dumi 有不同的入口文件和打包配置，我的想法是自己拿到 code block 中的代码，跑在 Vite 中，然后把 dumi-theme-mobile 里 iframe 的 URL 替换为 Vite 对应的 URL。看了一下 dumi 也是把 code block 编译到 .umi 目录里的，但是提前编译的话 Vite 项目特有的代码就无法运行，所以可以不提前编译 code block 中的代码，或者可以说一下怎么通过插件实现？

**Comment by PeachScript** [comment]
提前编译是为了分析 demo 元信息（依赖、源代码等），无法跳过；但后续版本 dumi 会支持以 React Component 包裹的形式接入其他技术栈，参考 #804 ，API 还在测试阶段，有疑问可以 PR 里讨论
