### ISSUE TITLE
怎么控制只显示外部 demo 的源代码，而不展示其他依赖的源代码

### ISSUE THREAD

**Issue by wjkang** [umijs/dumi#787]
![image](https://user-images.githubusercontent.com/9456046/126495191-073d50e5-fb18-4f92-9495-7cfcf8d90ad9.png)

不想让依赖的源代码也展示出来，不知道能不能控制

**Comment by PeachScript** [comment]
无法控制，dumi 希望组件 demo 对用户来说是『能看能用』的，如果有特殊需要可以基于自定义主题定制 demo 渲染组件
