### ISSUE TITLE
bug: 与@ant-design/pro-layout不兼容，好急啊

### ISSUE THREAD

**Issue by ywy94ywy** [umijs/dumi#79]
这是复现地址：
https://codesandbox.io/s/romantic-cache-rq6wd

**Comment by PeachScript** [comment]
这个和 pro-layout 应该无关，.md 中所有的 tsx/jsx 代码块默认会被 render，如果希望显示纯代码块，后面加上 pure 修饰符即可：`jsx | pure`

**Comment by ywy94ywy** [comment]
不是的,比如我写成这样
```jsx
<input/>
```
我想它被render，如果不安装pro-layout，可以渲染。
但是npm install pro-layout，再father-doc dev，只要代码中包含```jsx就会报错

**Comment by PeachScript** [comment]
代码块必须 export React Component 才能渲染，单写一个 <input /> 是会报错的。

如果仍然无法工作且确定和安装 pro-layout 有关，把错误内容贴一下看，上面的复现 demo 由于 jsx 代码块中写的中文，无法作为参考。

**Comment by PeachScript** [comment]
先 close 了，如果确定问题仍然存在请再 reopen
