### ISSUE TITLE
bug: project running error, "These dependencies were not found..."

### ISSUE THREAD

**Issue by 0x219** [umijs/dumi#793]
### Versions

- dumi: v1.1.23
- node: v14.17.3
- npm: v7.19.1
- OS: MacOS v11.4
- Browser: Google Chrome v92.0.4515.107

### Steps to reproduce
Use pnpm package manager or npm v7 to install project dependencies and run development commands.

### What is Expected?
Start the development server of the document normally.
### What is actually happening?
```
These dependencies were not found:

* dumi-theme-default/es/builtins/API.js in ./docs/index.md, ./src/Foo/index.md
* dumi-theme-default/es/builtins/Alert.js in ./docs/index.md, ./src/Foo/index.md
* dumi-theme-default/es/builtins/Badge.js in ./docs/index.md, ./src/Foo/index.md
* dumi-theme-default/es/builtins/Example.js in ./docs/index.md, ./src/Foo/index.md
* dumi-theme-default/es/builtins/Previewer.js in ./docs/index.md, ./src/.umi/core/routes.ts and 1 other
* dumi-theme-default/es/builtins/SourceCode.js in ./docs/index.md, ./src/Foo/index.md

To install them, you can run: npm install --save dumi-theme-default/es/builtins/API.js dumi-theme-default/es/builtins/Alert.js dumi-theme-default/es/builtins/Badge.js dumi-theme-default/es/builtins/Example.js dumi-theme-default/es/builtins/Previewer.js dumi-theme-default/es/builtins/SourceCode.js
```

**Comment by zjsth92** [comment]
+1

**Comment by zjsth92** [comment]
`dumi-theme-default` cannot be installed with react 17

**Comment by PeachScript** [comment]
Cannot reproduce with `npm@7.4.0`

**Comment by 0x219** [comment]
只有yarn安装是没问题的

**Comment by 0x219** [comment]
实际上这个问题有很久了，貌似去年就已经存在了。🤔

**Comment by PeachScript** [comment]
pnpm 不会提升底层依赖、确实会出现，但其他包管理工具没有复现；pnpm 解法参考 https://github.com/umijs/dumi/issues/570#issuecomment-886474994

**Comment by PeachScript** [comment]
Duplicate of #570

**Comment by 0x219** [comment]
> pnpm 不会提升底层依赖、确实会出现，但其他包管理工具没有复现；pnpm 解法参考 [#570 (comment)](https://github.com/umijs/dumi/issues/570#issuecomment-886474994)

npmv7版本你那里没有复现么

**Comment by PeachScript** [comment]
> Cannot reproduce with `npm@7.4.0`

⏫

**Comment by 0x219** [comment]
> > Cannot reproduce with `npm@7.4.0`
> 
> ⏫

npm目前没解法么

**Comment by PeachScript** [comment]
v1.1.24 修复了 pnpm 安装找不到依赖的问题

@0x219 上面是说 npm@7.4.0 无法复现

**Comment by 0x219** [comment]
> v1.1.24 修复了 pnpm 安装找不到依赖的问题
> 
> @0x219 上面是说 npm@7.4.0 无法复现

试试我的npm版本

**Comment by 0x219** [comment]
npm v7没有复现了，我关闭了issue
