### ISSUE TITLE
dumi build iframe demo 404

### ISSUE THREAD

**Issue by SuperLuckyYU** [umijs/dumi#794]
### Question
Package after using dumi-theme-mobile theme, preview 404 in iframe, but you can preview it in local development

### Sample Code
The content of the .umirc.ts file is the initial file content
![Uploading 1627236673706.jpg…]()

**Comment by SuperLuckyYU** [comment]
solved

**Comment by beiyu98** [comment]
你好，解决方式可以分享下吗？
