### ISSUE TITLE
bug: 开启mfsu导致FrontMatter修改无法预览效果

### ISSUE THREAD

**Issue by blueju** [umijs/dumi#795]
开启 mfsu 后，修改 FrontMatter 配置不会触发页面改变，无法预览效果，需要删除 .umi 后重新编译才能看到效果，但关闭 mfsu 后恢复正常

### Versions

- dumi: "^1.1.23"
- node:  “12.16.3”
- npm: “6.14.4”
- OS: “windows”
- Browser: "edge 91.0.864.64"

**Comment by yutingzhao1991** [comment]
@xiefengnian

**Comment by PeachScript** [comment]
v1.1.33 已修复
