### ISSUE TITLE
能否优雅地全局隐藏 codesandbox 按钮？

### ISSUE THREAD

**Issue by Gavin-Gong** [umijs/dumi#799]
能否优雅地全局隐藏 codesandbox 按钮？因为像内部项目和 react-native 项目是不需要 codesandbox 的
![image](https://user-images.githubusercontent.com/9414378/127801931-42b8157c-5c69-4377-b8b7-5f8c440b6c86.png)

workaround
- `display: none` 样式覆盖
- 每个代码块注释写上 `hideActions: "CSB"`

**Comment by PeachScript** [comment]
本地自定义 Previewer，props 加上 hideActions 再传给 dumi 默认主题的 Previewer 渲染，参考：https://d.umijs.org/zh-CN/theme/development

**Comment by Gavin-Gong** [comment]
> 本地自定义 Previewer，props 加上 hideActions 再传给 dumi 默认主题的 Previewer 渲染，参考：https://d.umijs.org/zh-CN/theme/development

按照你说的方法解决了我的问题，thx。其实更加期望可以在 themeConfig 字段增加一个字段方便进行控制。在我看来不使用codesandbox 是比较常见的场景🙂。

```tsx
import Previewer from 'dumi-theme-default/src/builtins/Previewer';

export default (props) => {
  return <Previewer {...props} hideActions="CSB" />;
};
```

**Comment by PeachScript** [comment]
> 其实更加期望可以在 themeConfig 下增加一个字段方便进行控制。因为在我看来不使用codesandbox 是比较常见的场景🙂。

@Gavin-Gong 有空可以来个 PR 支持下~

**Comment by fariellany** [comment]
> Previewer

应该怎么写呢 ？ 我是用 <code src='./all'> 模式 不是直接用的 <Previewer /> 我应该怎么把 Previewer导入到我全局里面呢 

import React from 'react';
import Layout from 'dumi-theme-default/es/layout';

export default ({ children, ...props }) => (
  <Layout {...props}>
    <>
      {children}
    </>
  </Layout>
);

直接是写在这里面吗 ？

**Comment by BosenY** [comment]
我更新下最新版本的隐藏方法：
- 创建`.dumi/theme/builtins/Previewer.tsx`
- 添加代码
```tsx
// @ts-nocheck
import Previewer from 'dumi-theme-mobile/dist/builtins/Previewer';
export default (props) => {
    return <Previewer {...props} disabledActions={['CSB', 'STACKBLITZ']} />;
};
```

**Comment by PeachScript** [comment]
@BosenY 感谢补充，有两点建议：
1. 本地主题建议用 theme-original 别名，这样不需要关心当前是什么主题包：https://d.umijs.org/theme#dumitheme-originallayoutsbuiltinsslotsxx
2. 建议覆盖 `PreviewerActions` slot 而不是覆盖 `Previewer` builtin，符合最小变更
