### ISSUE TITLE
在<code /> 引入的演示文件中  vscode提示当前找不到 如何处理 

### ISSUE THREAD

**Issue by zlfgege** [umijs/dumi#801]
![image](https://user-images.githubusercontent.com/59908589/127810160-0073a3a6-5844-4b14-b3cc-d0ff079baed9.png)

**Comment by zlfgege** [comment]
这是开发的模块 按照官网的文档的来写示例 但是在vscode 中会提示找不到 而且也没有ts 相关的提示 开发体验并不好

**Comment by zlfgege** [comment]
在 demo 中引入组件 提示找不到当前开发组件的ts类型

**Comment by PeachScript** [comment]
确保组件库 package.json 里有指明类型文件，且该类型文件已构建出来

**Comment by zlfgege** [comment]
> 确保组件库 package.json 里有明确的类型文件，并且该类型的文件已构建出来

确认为未构建类型文件 ， 在哪配置构建类型文件，官网文档中没有找到相关配置，修改tsconfig.json 文件中的 "declaration": true,        无效
<img width="952" alt="WeChat2a9163f7ef6e3e027a1a05fe40588818" src="https://user-images.githubusercontent.com/59908589/127817394-d648b189-f9a5-4e82-8738-37b5ddc3ffe6.png">

**Comment by PeachScript** [comment]
配置 `declaration: true` 是对的，如果是 dumi 脚手架执行 `npm run build -- -w` 即可

**Comment by PeachScript** [comment]
issue 关闭，有疑问再反馈
