### ISSUE TITLE
移动端模式能不能增加个开关，可以打开收起模拟器

### ISSUE THREAD

**Issue by zhudaye** [umijs/dumi#810]

**Comment by zhudaye** [comment]
![image](https://user-images.githubusercontent.com/11675644/128174160-8cff6473-2f65-4685-a3f9-e3ae865f5425.png)

**Comment by PeachScript** [comment]
v1.1.36 做了两点优化：
1. 移动端主题右侧 toc 强制展示在 menu 里，节省横向空间
2. 超宽表格支持横向滚动，不会被模拟器遮挡了

issue 关闭
