### ISSUE TITLE
bug: theme.ts 用到了 IE 不支持的 includes 方法，并且插入了 <head> 标签中

### ISSUE THREAD

**Issue by lalalazero** [umijs/dumi#811]
### Versions

- dumi: 1.1.23
- node: 12.18
- npm:  --
- yarn: 1.22
- OS: windows 10
- Browser: ie 11

### Steps to reproduce
1. dumi build
2. 部署打好的包
3. 打开 ie11 访问
![image](https://user-images.githubusercontent.com/20458239/128294321-13825d6f-a1a1-4c0b-9aca-6a53f313bc37.png)

### What is Expected?
ie 11 正常访问不报错

### What is actually happening?

![image](https://user-images.githubusercontent.com/20458239/128294119-81ec91de-cbef-4dbe-9c17-9b4cc29ebacc.png)

参考这个 #566 ，ie 下做了 polyfill，但是这段代码是直接插入到 `<head>` 中，运行报错了。

我看这段代码是在这里插入的，https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/plugins/features/theme.ts#L64

可以把这段代码的插入挪到 `<body>` 中， umijs 后面去吗？

**Comment by xrkffgg** [comment]
其实就是个简单的判断，不行就换成最 简朴的 写法好了。
