### ISSUE TITLE
Will there be a plugin api named "dumi.modifyCodeBlock"?

### ISSUE THREAD

**Issue by Shwvi** [umijs/dumi#812]
### Question

There has been some situation where I need to process the markdown before they are converted to HTML.  I find the "dumi.detectCodeBlock" plugin API and I plan to do what I need to in the CodeBlock by identifying them with the frontmatter. But it's frustrating that I can only get the CodeBlock but not able to modify them. So, will there be a plugin api named "dumi.modifyCodeBlock" or any other methods to deal with my question? Thanks.

### Sample Code

```js
// /path/to/plugin.ts
import { IApi } from 'dumi';
import { ExampleBlockAsset } from 'dumi-assets-types';

export default (api: IApi) => {
  api.register({
    key: 'dumi.modifyCodeBlock',
    async fn(block: ExampleBlockAsset) {
      const newBlock = await changeBlock(block)
      return newBlock
    },
  });
};
```

**Comment by PeachScript** [comment]
You can try this experimental API: #804

**Comment by Shwvi** [comment]
> You can try this experimental API: #804

Okey, you're right:). Thank U！
