### ISSUE TITLE
请问如何忽略某些 markdown

### ISSUE THREAD

**Issue by karmiy** [umijs/dumi#814]
dumi 会把 resolve.includes 下的 markdown 文件都转为文档

如 packages/xxx/HELPER.md，也会生成一个叫 xxx 的 nav 名，并把 HELPER.md 作为 group 的文档 content

但 HELPER.md 只是用来记录某些事项的文件，不希望作为一个 docs 被识别，请问要如何忽略它？

是否可以在顶部加什么 frontMatter 属性来解决

**Comment by PeachScript** [comment]
下个版本会支持 `excludes` 配置项，refer: #792

**Comment by karmiy** [comment]
> 下个版本会支持 `excludes` 配置项，refer: #792

好的，非常感谢你的回复

**Comment by PeachScript** [comment]
v1.1.25 已支持 `resolve.excludes` 配置项，参考：https://d.umijs.org/zh-CN/config#excludes
