### ISSUE TITLE
如何引入 lerna 结构中组件库的样式

### ISSUE THREAD

**Issue by karmiy** [umijs/dumi#815]
最近在用 dumi 写文档，遇到了问题想请教下
项目结构如下：

- packages
    - react-components
        - src
            - index.ts
            - button
                - style
                    - index.css
                - index.tsx
                - README.md
        - package.json

在  README.md 中编写：

```tsx
import { Button } from 'react-components';
```

如何引入它的样式，试了下 dumi 官方常见问题的做法：

extraBabelPlugins: [
  [
    'import',
    {
      libraryName: 'react-components',
      camel2DashComponentName: false,
      customStyleName: name => {
        return `./style/index.css`;
      },
    },
    'react-components',
  ],
];

也不行，请问如何处理呢？

**Comment by PeachScript** [comment]
走 `style` 配置而非 `customStyleName`，参考 babel-plugin-import 的文档：https://github.com/ant-design/babel-plugin-import#style
