### ISSUE TITLE
使用最新的dumi构建资源异常，运行92%之后自动终止

### ISSUE THREAD

**Issue by luojinghui** [umijs/dumi#816]
### Question
使用dumi构建文档项目，在centos服务器自动化构建时，每次运行到92%就构建结束，没有任何错误，但是没有任何构建包产出。导致服务器访问dist目录失效。

构建信息：
Webpack █████████████████████████ chunk asset optimization (92%) TerserPlugin
✨  Done in 264.19s.

表现：
到92%任务自动结束，没有构建包输出，没有任何错误，执行 DEBUG 调试模式输出也没有任何错误；

观察：
1. 服务器内存飙升
2. 在运行到92%时，服务器cpu达到110%+（本地测试mac高配笔记本也有同样的问题，cpu达到110%+）

### Sample Code
经过初步的定位，可能是umi构建资源时，TerserPlugin或babel内部造成内存泄漏或者资源处理异常问题导致的服务爆栈问题。
详见文章：https://zhuanlan.zhihu.com/p/286491809

请问官方是否能出解决方案？

**Comment by PeachScript** [comment]
压缩器可以换成 esbuild：https://umijs.org/zh-CN/plugins/plugin-esbuild
