### ISSUE TITLE
bug: "dumi": "cross-env APP_ROOT=dumi dumi dev",  这个配置有问题

### ISSUE THREAD

**Issue by zww-v5** [umijs/dumi#818]
我这按照这个文档(https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F)在非 umi 的项目中使用 dumi，但却一直报这个错误。
![image](https://user-images.githubusercontent.com/9295948/128673990-03de3fe3-d469-4e33-ab06-b0879f491937.png)

经测试后，发现文档的指引有问题，得把本地创建的那个 dumi 文件夹改成其他的名字。
![image](https://user-images.githubusercontent.com/9295948/128674230-3a2f3e61-dbce-4f20-9b56-268e4ea22035.png)

我这把 dumi 文件夹改成 dumi-root 后就正常了。
![image](https://user-images.githubusercontent.com/9295948/128674380-fb407d1f-2340-4110-b14b-a27425bcdec3.png)

**Comment by PeachScript** [comment]
v1.1.25 已修复，可以使用 dumi 作为项目文档的文件夹了
