### ISSUE TITLE
以antd作为基础组件，进行组件的二次封装，如何让antd的less变量修改生效？

### ISSUE THREAD

**Issue by FJHou** [umijs/dumi#819]
### Question
目前通过引入antd，在antd基础上作自定义开发，umirc配置了babel-import-plugin，配置了lessLoader的modifyVars，按理来说应该可以修改antd的less变量，但是目前看是不生效。请问应该怎么做才能生效？

### Sample Code
umirc配置：
`extraBabelPlugins: [['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }]],
  lessLoader: {
    options: {
      modifyVars: {
        'primary-color:': 'red',
        'border-radius-base': '4px',
      },
      javascriptEnabled: true,
    },
  }`

**Comment by PeachScript** [comment]
文档配置：https://d.umijs.org/config#theme
组件打包配置：https://github.com/umijs/father#lessinrollupmode

**Comment by FJHou** [comment]
> 文档配置：https://d.umijs.org/config#theme
> 组件打包配置：https://github.com/umijs/father#lessinrollupmode

```
export default {
  entry: './src/index',
  esm: 'babel',
  lessInRollupMode: {
    modifyVars: {
      'primary-color': '#1DA57A',
      'link-color': '#1DA57A',
      'border-radius-base': '4px',
    },
  },
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ]
};

```
我在.fatherrc.ts里配置了，但是没生效。请问是我哪里配置有问题？

**Comment by FJHou** [comment]
> 文档配置：https://d.umijs.org/config#theme
> 组件打包配置：https://github.com/umijs/father#lessinrollupmode

配置theme发现确实是生效的，但是我能确定我组件库的主题色变量的修改也是生效的么？

**Comment by PeachScript** [comment]
babel 打包模式下 `lessInRollupMode` 要换成 `lessInBabelMode`

后续打包相关问题请到 father 仓库提问，issue 关闭
