### ISSUE TITLE
bug: docs-dist 中index.html引入的umi.js多了个“/”

### ISSUE THREAD

**Issue by abingye** [umijs/dumi#820]
`docs:build` 后生成的`docs-dist`下的`index.html`引用人`umi`路径是  `/umi.js`而不是 `umi.js`,如果直接打开index.html将无法正常引用`umi.js`和`umi.css`
![image](https://user-images.githubusercontent.com/20157897/128711229-036bcb48-3912-4a0d-bdd3-52af75205b7a.png)

**Comment by PeachScript** [comment]
并非 bug，文档产物默认是给 HTTP Server 托管、不是用来双击在浏览器里打开的，如有特殊需要配置静态资源托管路径，可参考：https://d.umijs.org/zh-CN/config#publicpath
