### ISSUE TITLE
bug:  引用本地静态资源失效

### ISSUE THREAD

**Issue by suedar** [umijs/dumi#824]
### Versions

- dumi: 1.1.24
- node: v14.16.0
- npm: 6.14.11
- OS: mac 11.5.1
- Browser: chrome 86.0.4240.80

### Steps to reproduce

例如组件库的资源为`antd`，组件库代码位于`根目录/src/components`，静态资源放在`根目录/es`下面。

设置 `alias`
``` ts

const path = require('path');

export default {
  chainWebpack: config => {
    config.resolve.alias
      .set("ssc-ui-react", path.resolve(__dirname, 'src', 'components'))
      .set("@root", path.resolve(__dirname));
  },
};
```

在编写示例代码时，引用静态资源的方式为 `@root/es/components/icon`

会报这个错误

![截屏2021-08-12 下午3 43 16](https://user-images.githubusercontent.com/18492953/129158090-1bec1220-fb7f-4515-860d-ffe8bd642d67.png)

看官方有关于根目录的内置别名
![image](https://user-images.githubusercontent.com/18492953/129158253-5e59d3a1-cc33-4d47-8f63-a44767102b43.png)

更改为  `umi/es/components/icon` 仍有问题

**Comment by PeachScript** [comment]
是文档的问题，内置别名目前均不可用，原因是 `father-build` 暂不支持别名配置，以避免开发者产生 dev 能跑但打包失败的疑惑

**Comment by PeachScript** [comment]
已从文档中移除默认 `alias` 的说明，等 father 支持别名后会再开启默认 `alias`；如果需要使用别名且 `.fatherrc` 里通过 rollup 插件处理了打包的别名配置，可以在配置里手动配一遍 `alias`
