### ISSUE TITLE
项目跑不起来，windows系统

### ISSUE THREAD

**Issue by lizhulee** [umijs/dumi#825]
### Question
依此运行下面三个命令，项目跑不起来。怎么解决？
### Sample Code
npx @umijs/create-dumi-lib --site
npm install
npx dumi dev

**Comment by lizhulee** [comment]
PS D:\wetool\wiki\dumi> npx @umijs/create-dumi-lib --site
Copy:  .editorconfig
Copy:  .fatherrc.ts
Write: .gitignore
Copy:  .prettierignore
Copy:  .prettierrc
Write: .umirc.ts
Write: docs\index.md
Write: package.json
Write: README.md
Write: src\Foo\index.md
Copy:  src/Foo/index.tsx
Copy:  src/index.ts
Copy:  tsconfig.json
Copy:  typings.d.ts
PS D:\wetool\wiki\dumi> npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@16.14.0
npm WARN node_modules/react
npm WARN   react@"^16.12.0" from the root project
npm WARN   6 more (umi, @umijs/runtime, dumi-theme-default, react-router, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-dom@17.0.2
npm WARN node_modules/react-dom
npm WARN   peer react-dom@">=16.9.0" from rc-tabs@11.10.1
npm WARN   node_modules/rc-tabs
npm WARN   1 more (@umijs/renderer-react)
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 1983 packages, and audited 1984 packages in 2m

189 packages are looking for funding
  run `npm fund` for details

13 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
PS D:\wetool\wiki\dumi> npx dumi dev                     
ERROR [dumi]: cannot start, detected this project is named 'dumi', please rename it in package.json file.

**Comment by PeachScript** [comment]
> ERROR [dumi]: cannot start, detected this project is named 'dumi', please rename it in package.json file.

请看错误提示
