### ISSUE TITLE
<code />如何引用当前文档项目外的demo组件？

### ISSUE THREAD

**Issue by JserShadow** [umijs/dumi#826]
### Question
code标签目前用下来貌似只能通过相对路径引用demo，我的场景是在monorepo中demo单独作为一个package，按照外部依赖或者相对路径引用都不行，文档里也没有针对code src路径的描述，问下这种情况要怎么做？
### Sample Code
目录结构
```
-- documents
    -- a-doc # 这里是dumi项目
-- examples # 这里是demo集合 
```

a-doc的package.json中有examples依赖，如果按如下方式引用会报resolve error

```
<code src="examples/xx/xx.tsx" />
```

**Comment by PeachScript** [comment]
在哪里安装和启动 dumi 的，以及『相对路径引用都不行』具体什么错误

**Comment by JserShadow** [comment]
好像是react引用的问题，先关掉了..
