### ISSUE TITLE
bug: demo 中的 jsx 初始会 render 2 次

### ISSUE THREAD

**Issue by karmiy** [umijs/dumi#827]
在 demo 中写 jsx 语法，最简单的示例如：

```tsx
import React, { useEffect } from 'react';

export default () => {
  useEffect (() => {
        console.log('mount success');
   }, []);
  return <div>123</div>;
};
```

会发现 log 会打印了 2 次，即整个 demo 是被 render 2 次的

这导致了：如果希望实现一个类似 componentDidMount 的 hooks，useDidMount

示例中 useDidMount 的回调将会执行 2 次，demo 示例就不能很好的给开发人员看到效果，会看到打了 2 次 log，与 useDidMount 只在组件初始化结束执行 1 次存在偏差

请问要如何解决呢？

**Comment by karmiy** [comment]
似乎与 dumi-theme-mobile 有关

**Comment by JessieZheng2015** [comment]
我也遇到这个问题，请问如何解决吗？

**Comment by PeachScript** [comment]
@JessieZheng2015 v1.1.33 存在初始渲染两次的 bug，等 v1.1.35 修复；这个 issue 比较早，应该不是同一个问题

**Comment by JessieZheng2015** [comment]
> @JessieZheng2015 v1.1.33 存在初始渲染两次的 bug，等 v1.1.35 修复；这个 issue 比较早，应该不是同一个问题
我升级1.1.35后就好了，感谢回复。
