### ISSUE TITLE
demo 里面的组件如何使用 babel-plugin-import 引入 style?

### ISSUE THREAD

**Issue by Unfantasy** [umijs/dumi#828]
### Question
想要做个组件类似 ant-design 可以使用 `babel-plugin-import` 按需引入 style, 所以把样式写在了 style 目录里面，使用的时候通过`babel-plugin-import` 可以引入样式，但是开发组件的时候 style 里面的样式不知道如何引入。
### Sample Code
![image](https://user-images.githubusercontent.com/16619996/129439471-02eea3e8-0f66-435d-a473-132ea1199e66.png)

**Comment by PeachScript** [comment]
假定按需引入的样式路径是 `pkg/es/button/style`，两个解法：
1. `babel-plugin-import` 配置和实际项目一致，开发时 `father-build -w` 实时编译出 `es` 目录
2. `babel-plugin-import` 配置和实际项目不一致，例如样式引入目录从 `pkg/es/button/style` 修改为 `pkg/button/style`

**Comment by Unfantasy** [comment]
@PeachScript  非常感谢，我使用 `father-build -w` 在开发的时候可以做到实时更新了。
想要再问一个问题，我使用 `father-build` 的 `babel` 模式后，`index.d.ts` 就不打包了，这样在使用的时候就点不进去，使用 `rollup` 模式的时候是有的，这个能在 `babel` 模式的时候也打包出 `index.d.ts` 吗？

**Comment by PeachScript** [comment]
@Unfantasy babel 模式的类型是输出到 `es/index.d.ts`，需要更新 `package.json` 里的 `typings` 路径

如果还有遇到其他问题可以新开 issue，这个 issue 先 close 了
