### ISSUE TITLE
请问如何使用 FrontMatter 将 md 文件置为 1级菜单项

### ISSUE THREAD

**Issue by karmiy** [umijs/dumi#829]
场景：
目前正在使用 dumi 塑造 hooks 文档，md 都使用 FrontMatter 定制对应的 Nav 与 Group
但像 “快速上手” “日志”  这类的 md 不需要隶属于某个 group，更期望作为独立的 1级菜单，而非 group 下的某一项

图文描述：
![XD OCUMW~X2$7GGPGT7_)KC](https://user-images.githubusercontent.com/46210915/129442643-9cb20da3-cb13-4803-919e-ce4c5c5fa7d9.png)

当前配置的 FrontMatter：
\---
mobile: false
nav:
  title: React Hooks
  path: /react-hooks
group:
  title: Store
  path: /store
  order: 0
\---

存在的问题：
- 路由变成是 /react-hooks/store/store，期望是：/react-hooks/store
- 此时是 md 内 h1 标题与 Group 重名时，才达到了期望的效果（如果 h1 的另一个名字或有配置 title，又会变成 group 下的项），但其实点击 Store 菜单时，它并不能被视为 “选中高亮”

参考：
参考了 ahooks 的代码，如 “快速上手” 是放在 docs 自动生成的，非 FrontMatter 实现，目前项目无法像 ahooks 那样有对应的目录结构自动生成

期望：
使用 FrontMatter 语法实现，Store 的这个 md 可以作为独立的 1级菜单，且选中后高亮

**Comment by PeachScript** [comment]
推荐通过目录结构来控制分组而不是 frontmatter：

```bash
.
└── docs
    └── react-hooks
        └── store.md
```

或

```bash
.
└── docs
    └── react-hooks
        └── store
            └── index.md
```

**Comment by karmiy** [comment]
> 推荐通过目录结构来控制分组而不是 frontmatter：
> 
> ```shell
> .
> └── docs
>     └── react-hooks
>         └── store.md
> ```
> 
> 或
> 
> ```shell
> .
> └── docs
>     └── react-hooks
>         └── store
>             └── index.md
> ```

你好，你说的这个是可以的，就想了解下是否使用 frontmatter 做不到这样呢？

**Comment by PeachScript** [comment]
理论上可以，但官方文档不会提供类似实践，有特殊需要可以根据文档尝试：https://d.umijs.org/zh-CN/guide/basic#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E8%88%AA%E3%80%81%E5%88%86%E7%BB%84%E5%92%8C%E6%A0%87%E9%A2%98
