### ISSUE TITLE
bug: links 选项未生效

### ISSUE THREAD

**Issue by zww-v5** [umijs/dumi#832]
我按照这个文档配置页面额外的样式，但并未生效。https://d.umijs.org/zh-CN/config#links

我的项目是非 umi 的项目，单独使用 dumi 的。

![image](https://user-images.githubusercontent.com/9295948/129534184-f997b2ea-5d0b-490d-a99c-e2da5b52a4be.png)

![image](https://user-images.githubusercontent.com/9295948/129534687-e8ad0c4f-cb18-4d48-865e-67e4dcb492a2.png)

### Versions

- dumi: 1.1.25
- node: v14.17.5
- npm: 6.14.14
- OS: macOS Big Sur

**Comment by PeachScript** [comment]
样式表用 `styles` 配置项引入：https://d.umijs.org/zh-CN/config#styles

**Comment by PeachScript** [comment]
另外上一版本修复后，可以使用 `dumi` 命名的文件夹了，`dumi-root` 有些奇怪

**Comment by zww-v5** [comment]
> 另外上一版本修复后，可以使用 `dumi` 命名的文件夹了，`dumi-root` 有些奇怪

好的，感谢
