### ISSUE TITLE
是否可以和antd文档一样做左右demo布局

### ISSUE THREAD

**Issue by yagang94** [umijs/dumi#834]
### Question
实际场景：公司基于antd组件进行二次封装，需要集成antd组件文档以及公司内部组件文档（包含业务，基础等）

**Comment by PeachScript** [comment]
不支持，有自定义需求可以定制主题：https://d.umijs.org/zh-CN/theme/development

**Comment by yagang94** [comment]
> 不支持，有自定义需求可以定制主题：[https](https://d.umijs.org/zh-CN/theme/development) : [//d.umijs.org/zh-CN/theme/development](https://d.umijs.org/zh-CN/theme/development)

那想请问下有没有人做过类似的场景呢，将antd的文档和内部文档做整合的

**Comment by PeachScript** [comment]
二次拓展很多，都是选择给个超链接跳转到 antd 文档，集成 antd 文档没有听说过
