### ISSUE TITLE
lerna 下 根路径有.umirc.ts，同时也有umi项目，dumi dev运行会不会冲突

### ISSUE THREAD

**Issue by caoxu331** [umijs/dumi#837]
### Sample Code
![image](https://user-images.githubusercontent.com/51979013/129842862-c036dd00-f463-4e6c-95c7-e0eedd508f49.png)

**Comment by caoxu331** [comment]
同时配置`resolve.excludes = ['app/*']`失效

**Comment by PeachScript** [comment]
会冲突，一般两种用法：
1. 如果 Umi 项目是主应用，要使用 dumi 管理该应用的组件，那么使用集成模式，配置冲突可以通过 `UMI_ENV` 区分多环境配置实现，参考：[集成模式](https://d.umijs.org/zh-CN/guide/advanced#umi-%E9%A1%B9%E7%9B%AE%E9%9B%86%E6%88%90%E6%A8%A1%E5%BC%8F)、[多环境配置](https://umijs.org/zh-CN/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE)
2. 如果 Umi 和 dumi 两个应用完全没关系，建议用不同目录存放，执行时通过 `APP_ROOT` 环境变量切换执行目录，参考：[APP_ROOT 范例](https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F)

**Comment by PeachScript** [comment]
> 同时配置`resolve.excludes = ['app/*']`失效

如果处理后还存在该问题，单独提 issue 并附上复现仓库

**Comment by caoxu331** [comment]
> 会冲突，一般两种用法：
> 
> 1. 如果 Umi 项目是主应用，要使用 dumi 管理该应用的组件，那么使用集成模式，配置冲突可以通过 `UMI_ENV` 区分多环境配置实现，参考：[集成模式](https://d.umijs.org/zh-CN/guide/advanced#umi-%E9%A1%B9%E7%9B%AE%E9%9B%86%E6%88%90%E6%A8%A1%E5%BC%8F)、[多环境配置](https://umijs.org/zh-CN/docs/config#%E5%A4%9A%E7%8E%AF%E5%A2%83%E5%A4%9A%E4%BB%BD%E9%85%8D%E7%BD%AE)
> 2. 如果 Umi 和 dumi 两个应用完全没关系，建议用不同目录存放，执行时通过 `APP_ROOT` 环境变量切换执行目录，参考：[APP_ROOT 范例](https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi%EF%BC%9F)
