### ISSUE TITLE
怎么关闭最新版切换屏幕模式组件

### ISSUE THREAD

**Issue by Jcanno** [umijs/dumi#839]
### Question
最新版的会生成切换暗黑屏幕的组件，如何关闭他？主要暗色不兼容，影响体验
![image](https://user-images.githubusercontent.com/34361691/130029587-45dcd7c1-5540-4d75-b701-6e202b933d49.png)

**Comment by xrkffgg** [comment]
https://github.com/umijs/dumi/pull/683

目前可以先通过 css 隐藏

**Comment by changlin0501** [comment]
> #683
> 
> 目前可以先通过 css 隐藏

你好，我想问问再哪个CSS中隐藏

**Comment by PeachScript** [comment]
Duplicate of #1212
