### ISSUE TITLE
Question:  切换英文时，组件代码块中的 title 、 desc 及代码中的文字，显示的是中文？

### ISSUE THREAD

**Issue by niexq** [umijs/dumi#840]
### Question
 切换英文时，组件文档，代码块中的 `title` 和 `desc` 显示的是中文
 
### Sample Code
复现仓库：https://github.com/niexq/react-auto-sizer
复现网址：https://niexq.github.io/react-auto-sizer

### Versions
- dumi: "^1.1.0"
- node: "v12.18.4"
- npm: 6.14.6
- OS: macOS Big Sur
- Browser: Google Chrome 版本 92.0.4515.131（正式版本） (x86_64)

### Steps to reproduce

步骤：切换英文时，组件代码块中的 `title` 、 `desc` 及`代码中的文字`，显示的是中文

![](https://raw.githubusercontent.com/niexq/picbed/main/picgo/react-auto-sizer-dumi.gif)

### What is Expected?
切换英文显示英文

### What is actually happening?
切换英文时，组件代码块中的 `title` 、 `desc` 及`代码中的文字`，显示的是中文

**Comment by PeachScript** [comment]
目前多语言配置要显式携带后缀，后续会支持自动识别

Duplicate of #777

**Comment by niexq** [comment]
> 目前多语言配置要显式携带后缀，后续会支持自动识别
> 
> Duplicate of #777

好的，谢谢
