### ISSUE TITLE
dumi.getRootRoute 的说明不清晰

### ISSUE THREAD

**Issue by zww-v5** [umijs/dumi#842]
按照文档去使用这个 api 时，其中的 routes 变量会报未定义的错误，文档中也未说明这个 routes 是从哪获取的。
![image](https://user-images.githubusercontent.com/9295948/130315486-a57318a5-6d2b-4817-bb84-90ed08059dbd.png)

**Comment by PeachScript** [comment]
感谢反馈，dumi 沿用 Umi 的插件体系，routes 可以通过 Umi 提供的基础 API 拿到，已优化文档：https://d.umijs.org/zh-CN/plugin#dumigetrootroute

**Comment by javaxiu** [comment]
按照这个文档里的 demo 写的，结果报错了

```tsx
// /path/to/plugin.ts
import { IApi } from 'dumi';

export default async (api: IApi) => {
  const rootRoute = await api.applyPlugins({
    key: 'dumi.getRootRoute',
    type: api.ApplyPluginsType.modify,
    initialValue: await api.getRoutes(),
  });
};
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Cannot read properties of null (reading 'routes')
TypeError: Cannot read properties of null (reading 'routes')
    at /Users/u/workspace/wec/node_modules/@umijs/core/lib/Route/Route.js:88:53
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/u/workspace/wec
```bash

```

**Comment by PeachScript** [comment]
@javaxiu 得有最小复现才能排查
