### ISSUE TITLE
使用dumi 写外部demo报错

### ISSUE THREAD

**Issue by RainManGO** [umijs/dumi#845]
### 问题
写了一个外部demo，写法按照文档上写的。引入之后报错。

![image](https://user-images.githubusercontent.com/9261077/130541293-9219ecef-c7d9-4ecd-8f04-4aac95d5ee72.png)

![image](https://user-images.githubusercontent.com/9261077/130541453-7f4eadcd-598c-404a-8e3a-1156c2e9f9bc.png)

### 报错信息

Cannot read property 'createElement' of undefined
TypeError: Cannot read property 'createElement' of undefined at _callee7$ (http://localhost:8000/docs__components__base-components__baseTable.md~docs__components__base-components__breadcrumbButton.~4e96ce5e.js:948:25) at tryCatch (http://localhost:8000/umi.js:53842:17) at Generator.invoke [as _invoke] (http://localhost:8000/umi.js:54062:22) at Generator.prototype.<computed> [as next] (http://localhost:8000/umi.js:53895:21) at asyncGeneratorStep (http://localhost:8000/umi.js:3054:24) at _next (http://localhost:8000/umi.js:3076:9) at http://localhost:8000/umi.js:3083:7 at new Promise (<anonymous>) at http://localhost:8000/umi.js:3072:12 at loader (http://localhost:8000/docs__components__base-components__baseTable.md~docs__components__base-components__breadcrumbButton.~4e96ce5e.js:961:27) at LoadableSubscription.load [as _loadFn] (http://localhost:8000/umi.js:51622:17) at LoadableSubscription.retry (http://localhost:8000/umi.js:51812:24) at new LoadableSubscription (http://localhost:8000/umi.js:51797:10) at init (http://localhost:8000/umi.js:51702:17) at LoadableComponent (http://localhost:8000/umi.js:51743:5) at renderWithHooks (http://localhost:8000/umi.js:35489:18) at updateForwardRef (http://localhost:8000/umi.js:37548:20) at beginWork (http://localhost:8000/umi.js:39602:16) at beginWork$1 (http://localhost:8000/umi.js:44439:14) at performUnitOfWork (http://localhost:8000/umi.js:43278:12) at workLoopSync (http://localhost:8000/umi.js:43206:5) at renderRootSync (http://localhost:8000/umi.js:43169:7) at performSyncWorkOnRoot (http://localhost:8000/umi.js:42792:18) at http://localhost:8000/umi.js:31831:26 at unstable_runWithPriority (http://localhost:8000/umi.js:50301:16) at runWithPriority$1 (http://localhost:8000/umi.js:31780:10) at flushSyncCallbackQueueImpl (http://localhost:8000/umi.js:31826:9) at flushSyncCallbackQueue (http://localhost:8000/umi.js:31813:3) at scheduleUpdateOnFiber (http://localhost:8000/umi.js:42392:9) at dispatchAction (http://localhost:8000/umi.js:36643:5) at checkForUpdates (http://localhost:8000/umi.js:52300:11) at http://localhost:8000/umi.js:51861:16 at Set.forEach (<anonymous>) at LoadableSubscription._update (http://localhost:8000/umi.js:51860:23) at http://localhost:8000/umi.js:51843:15

**Comment by PeachScript** [comment]
code 标签是直接使用的，不能放在代码块内部

**Comment by RainManGO** [comment]
好的，谢谢
