### ISSUE TITLE
bug: Throw errors when i import something from 'dumi/theme'...

### ISSUE THREAD

**Issue by vortesnail** [umijs/dumi#846]
Now i am tring to run code below:
```js
import { usePrefersColor, context } from 'dumi/theme'; 
```

and i get this error:
![3251629795039_ pic](https://user-images.githubusercontent.com/18679842/130588884-1f637613-03da-4844-ad73-4a3a99d6d20a.jpg)

But according to the documentation , what i am doing is allowed. How to avoid this kind of error?
![image](https://user-images.githubusercontent.com/18679842/130589065-d5b1beff-8e1a-4c9a-9efd-b182b41f5915.png)

In fact, there is a type hint when I move the mouse up:
![image](https://user-images.githubusercontent.com/18679842/130589199-e2ce91b6-5748-4958-91c0-4f3c0ea3f034.png)

Thanks!

**Comment by vortesnail** [comment]
Supplement: If I comment out this code first, and then open the comment after the startup is successful, there will be no error? Why?

**Comment by vortesnail** [comment]
Here is the repo url of realistic example: https://github.com/vortesnail/qier-player
```bash
cd website
```
and then install:
```bash
yarn
```

After npm installed:
```bash
yarn start
```

and you can see the errors.

**Comment by vortesnail** [comment]
Is there any solution, now I can’t `yarn build` and can't deploy because of this problem. I have tried to re install npm packages.

**Comment by PeachScript** [comment]
v1.1.26 已修复

**Comment by RootJian** [comment]
> v1.1.26 已修复
1.1.40 复现
![image](https://user-images.githubusercontent.com/41674118/167588962-d746cd57-d477-49c0-8f1e-a4e0d068a9ce.png)

**Comment by PeachScript** [comment]
> ![image](https://user-images.githubusercontent.com/58587791/172570275-3d4bd981-2def-47a1-9295-59cbaf587995.png) 这个问题的解决方案是什么呢，也遇到了 @PeachScript

看截图是依赖的代码有问题，组件库源码不能依赖框架提供的能力

**Comment by RootJian** [comment]
> > ![image](https://user-images.githubusercontent.com/58587791/172570275-3d4bd981-2def-47a1-9295-59cbaf587995.png) 这个问题的解决方案是什么呢，也遇到了 @PeachScript
> 
> 看截图是依赖的代码有问题，组件库源码不能依赖框架提供的能力

麻烦查看下我上面那条

**Comment by PeachScript** [comment]
@RootJian 看不出原因，提供一个最小可复现仓库

**Comment by LMLGM** [comment]
![image](https://user-images.githubusercontent.com/58587791/172750397-735acde0-a1ed-4c13-9cf2-113182d8b8d4.png)
是要固定版本吗？ @PeachScript

**Comment by RootJian** [comment]
> @RootJian 看不出原因，提供一个最小可复现仓库

https://github.com/RootJian/dumi-bug-report

**Comment by PeachScript** [comment]
> > @RootJian 看不出原因，提供一个最小可复现仓库
> 
> https://github.com/RootJian/dumi-bug-report

组件 demo 不能用 dumi 提供的 API，组件 demo 是给用户演示组件用法的，不能依赖开发框架的能力

**Comment by RootJian** [comment]
> > > @RootJian 看不出原因，提供一个最小可复现仓库
> > 
> > 
> > https://github.com/RootJian/dumi-bug-report
> 
> 组件 demo 不能用 dumi 提供的 API，组件 demo 是给用户演示组件用法的，不能依赖开发框架的能力

啊？那这个监听dumi的颜色变化还有啥场景能用😂

**Comment by PeachScript** [comment]
> 啊？那这个监听dumi的颜色变化还有啥场景能用😂

两个场景：
1. 自定义主题包
2. 支持多主题色的组件库（比如 antd）在外层 layout 注入 ConfigProvider，实现组件库主题色与文档随动

**Comment by LMLGM** [comment]
> > > @RootJian 看不出原因，提供一个最小可复现仓库
> > 
> > 
> > https://github.com/RootJian/dumi-bug-report
> 
> 组件 demo 不能用 dumi 提供的 API，组件 demo 是给用户演示组件用法的，不能依赖开发框架的能力

@PeachScript 你好，我这里是在应用中引入dumi编码的包时，启动报错，组件 demo的时候并没有报错

**Comment by LMLGM** [comment]
![image](https://user-images.githubusercontent.com/58587791/172774341-0fb3d4d4-91af-4556-b065-54b58aaef562.png)
@PeachScript 一个组件并不是在.md文件中使用

**Comment by PeachScript** [comment]
> > ![image](https://user-images.githubusercontent.com/58587791/172570275-3d4bd981-2def-47a1-9295-59cbaf587995.png) 这个问题的解决方案是什么呢，也遇到了 @PeachScript
> 
> 看截图是依赖的代码有问题，组件库源码不能依赖框架提供的能力

@LMLGM 上面回复你了，找 NPM 依赖的维护者改

**Comment by LMLGM** [comment]
>   
 



> > > ![image](https://user-images.githubusercontent.com/58587791/172570275-3d4bd981-2def-47a1-9295-59cbaf587995.png) 这个问题的解决方案是什么呢，也遇到了 @PeachScript
> > 
> > 
> > 看截图是依赖的代码有问题，组件库源码不能依赖框架提供的能力
> 
> @LMLGM 上面回复你了，找 NPM 依赖的维护者改

我就是写npm的，要怎么改呢，代码就是截图里那样，install这个包启动就报错 @PeachScript

**Comment by PeachScript** [comment]
@LMLGM 组件源码里不要引入 dumi 提供的 API，组件库如果要支持多色参考 antd、用 ConfigProvider 实现
