### ISSUE TITLE
bug: 同名 md 内的 demo 展示会冲突

### ISSUE THREAD

**Issue by Grewer** [umijs/dumi#847]
在开发时, 基于cra脚手架开发文档,但是在创建demo时出现了问题

初步判断是md的文件名 如果不是 index 就会出现demo被覆盖的问题

gif演示效果：

![FWlrGlETBD](https://user-images.githubusercontent.com/21995246/130713834-9a19db79-27ce-4e4c-9b65-33d57e2fc166.gif)

其中 Text 是一个div， 而不是button

### 最小实现仓库

https://github.com/Grewer/dumi-ques-demo

### Versions

- dumi: 1.1.25
- node: 12.18.3
- npm:6.14.6
- OS: window 10
- Browser: chrome 92.0.4515.159

### Steps to reproduce

运行dumi

### What is Expected?

对于名称限制能够修复

**Comment by PeachScript** [comment]
v1.1.27 已修复
