### ISSUE TITLE
bug: docs文件夹下，md引入脚本，脚本里面引入了dumi/theme，提示不能解析

### ISSUE THREAD

**Issue by lzx-cloud** [umijs/dumi#848]
发现一个bug，操作如下：
首先在docs里面新建一个md文件，然后引入jsx，是可以正常显示页面的，因为我需要自定义页面，就像antd官网的组件总览一样

但是我需要获取到所有的路由，所以我这样写
import { context,} from 'dumi/theme';
const { menu } = useContext(context);
但是当我改变了md的文件夹之后，就提示我dumi/theme不能解析，具体错误提示如下：
Module build failed (from ./node_modules/@umijs/preset-dumi/lib/loader/index.js):
Error: Can't resolve 'dumi/theme' in 'D:/mlamp/projects/mlt-design/docs/components/src/overview'

后来我发现一个规律，在运行npm start启动之前如果没有引入dumi/theme的情况下，是完全可以正常启动的，然后再打开这几句代码，也是正常的，也可以获取到menu的，这都是正常的

问题在于：当我改变了该md之后，就会提示我以上错误，不能解析dumi/theme,我必须重复上面的操作才可以，也就是说，我在启动之后必须先把该模块的引用先注释了，才可以

当然，如果我不改变md内容的话，就是正常的，一旦改变就要重复上面的操作

**Comment by vortesnail** [comment]
我也有同样的问题，已经提了 issue 了，官方没有回复，估计在排查（或者没时间😂）[#846](https://github.com/umijs/dumi/issues/846)，不过我查看了 dumi/theme 这个类型声明的地方，发现是从 `@umijs/preset-dumi/lib/theme` 这个包里导出的，我现在的暂时性解决方案是这样：

```js
import { usePrefersColor, context } from '@umijs/preset-dumi/lib/theme';
```

亲测可用，急的话先用下，后续还是等官方解决这个问题再换回去。

**Comment by PeachScript** [comment]
Duplicate of #846

**Comment by lzx-cloud** [comment]
好的，谢谢，我试试

**Comment by PeachScript** [comment]
v1.1.26 已修复
