### ISSUE TITLE
bug: 配置 publicPath 本地启动有效，打包后的静态资源没有加上 publicPath。

### ISSUE THREAD

**Issue by vortesnail** [umijs/dumi#849]
我根据 dumi 的文档，设置了 `base` 和 `publicPath` 属性为我的仓库名称：

```js
export default defineConfig({
  base: '/qier-player',
  publicPath: '/qier-player/',
})
```

`base` 起作用了，每个访问的 url 会加一个 `/qier-player`，也能正确拿到 `umi.js` 文件；
`publicPath` 没起作用，我所有访问的静态资源都没有加这个前缀。比如我在 `.md` 文件中引入一个图片：

```md
# demo

现在我引入一张本地的图片：

<img src="/img/screenshot-shadow.png" />
```

我执行 `yarn start` 并查看控制台 network，所有资源都加上了 `publicPath` 的值，比如
```
http://localhost:8000/qier-player/img/screenshot-shadow.png
```

但是当我执行 `yarn build` 打包之后，我做了以下工作以确定有没有加上 `publicPath`：

1. 查看 `dist` 目录下 `umi.js` ，找到这个引用的地方，发现没有加上：

![image](https://user-images.githubusercontent.com/18679842/130828309-d2042e8c-3b69-40c2-b5f2-806cf95f5551.png)

2. 我部署至 github pages 之后，同样查看 network，发现也没有加上前缀，导致所有静态资源图片全部 404。

总结：我所有用到静态图片的地方，无论是 `.md` 文件内还是自己写的 `.tsx` 文件内，又或是 dumi 自己生成的 html 文件内，本地启动是好的，请求路径加了 `publicPath`，也能正确请求到。但打包后部署查看请求，没有加 `publicPath` 导致资源请求 404。

希望能得到解答，谢谢了，不然使用 dumi 的开发者每个图片的请求都要手动再加前缀，有点呆儿～（可能是我姿势不对，望解答😂）

**Comment by Vision010** [comment]
有同样的问题，请问最后是如何解决的？

**Comment by zksJack** [comment]
> 



> 我根据 dumi 的文档，设置了 `base` 和 `publicPath` 属性为我的仓库名称：
> 
> ```js
> export default defineConfig({
>   base: '/qier-player',
>   publicPath: '/qier-player/',
> })
> ```
> 
> `base` 起作用了，每个访问的 url 会加一个 `/qier-player`，也能正确拿到 `umi.js` 文件； `publicPath` 没起作用，我所有访问的静态资源都没有加这个前缀。比如我在 `.md` 文件中引入一个图片：
> 
> ```lisp
> # demo
> 
> 现在我引入一张本地的图片：
> 
> <img src="/img/screenshot-shadow.png" />
> ```
> 
> 我执行 `yarn start` 并查看控制台 network，所有资源都加上了 `publicPath` 的值，比如
> 
> ```
> http://localhost:8000/qier-player/img/screenshot-shadow.png
> ```
> 
> 但是当我执行 `yarn build` 打包之后，我做了以下工作以确定有没有加上 `publicPath`：
> 
> 1. 查看 `dist` 目录下 `umi.js` ，找到这个引用的地方，发现没有加上：
> 
> ![image](https://user-images.githubusercontent.com/18679842/130828309-d2042e8c-3b69-40c2-b5f2-806cf95f5551.png)
> 
> 2. 我部署至 github pages 之后，同样查看 network，发现也没有加上前缀，导致所有静态资源图片全部 404。
> 
> 总结：我所有用到静态图片的地方，无论是 `.md` 文件内还是自己写的 `.tsx` 文件内，又或是 dumi 自己生成的 html 文件内，本地启动是好的，请求路径加了 `publicPath`，也能正确请求到。但打包后部署查看请求，没有加 `publicPath` 导致资源请求 404。
> 
> 希望能得到解答，谢谢了，不然使用 dumi 的开发者每个图片的请求都要手动再加前缀，有点呆儿～（可能是我姿势不对，望解答😂）

请问解决了么

**Comment by maohui66661** [comment]
请问你解决了么？我也遇到了同样的问题。

**Comment by ltchronus** [comment]
> 请问你解决了么？我也遇到了同样的问题。

加上runtimePublicPath好了

**Comment by ltchronus** [comment]
> 我根据 dumi 的文档，设置了 `base` 和 `publicPath` 属性为我的仓库名称：
> 
> ```js
> export default defineConfig({
>   base: '/qier-player',
>   publicPath: '/qier-player/',
> })
> ```
> 
> `base` 起作用了，每个访问的 url 会加一个 `/qier-player`，也能正确拿到 `umi.js` 文件； `publicPath` 没起作用，我所有访问的静态资源都没有加这个前缀。比如我在 `.md` 文件中引入一个图片：
> 
> ```lisp
> # demo
> 
> 现在我引入一张本地的图片：
> 
> <img src="/img/screenshot-shadow.png" />
> ```
> 
> 我执行 `yarn start` 并查看控制台 network，所有资源都加上了 `publicPath` 的值，比如
> 
> ```
> http://localhost:8000/qier-player/img/screenshot-shadow.png
> ```
> 
> 但是当我执行 `yarn build` 打包之后，我做了以下工作以确定有没有加上 `publicPath`：
> 
> 1. 查看 `dist` 目录下 `umi.js` ，找到这个引用的地方，发现没有加上：
> 
> ![image](https://user-images.githubusercontent.com/18679842/130828309-d2042e8c-3b69-40c2-b5f2-806cf95f5551.png)
> 
> 2. 我部署至 github pages 之后，同样查看 network，发现也没有加上前缀，导致所有静态资源图片全部 404。
> 
> 总结：我所有用到静态图片的地方，无论是 `.md` 文件内还是自己写的 `.tsx` 文件内，又或是 dumi 自己生成的 html 文件内，本地启动是好的，请求路径加了 `publicPath`，也能正确请求到。但打包后部署查看请求，没有加 `publicPath` 导致资源请求 404。
> 
> 希望能得到解答，谢谢了，不然使用 dumi 的开发者每个图片的请求都要手动再加前缀，有点呆儿～（可能是我姿势不对，望解答😂）

配置上加上runtimePublicPath: true， md里的img正常了

**Comment by dqm07** [comment]
umi4的时候，需要在html手动配置window.publicPath，然后umirc中配置runtimePublicPath: {}即可

**Comment by warmhug** [comment]
@dqm07 请问怎么手工设置 window.publicPath 呢？

**Comment by tpc-ht** [comment]
> umi4的时候，需要在html手动配置window.publicPath，然后umirc中配置runtimePublicPath: {}即可
我完成了你上面的操作，但运行和打包后并没在资源路径前面添加 window.publicPath的值。请问是需要在资源前面拼接 window.publicPath 吗？

**Comment by tpc-ht** [comment]
> umi4的时候，需要在html手动配置window.publicPath，然后umirc中配置runtimePublicPath: {}即可

我完成了你上面的操作，但运行和打包后并没在资源路径前面添加 window.publicPath的值。请问是需要在资源前面拼接 window.publicPath 吗？
