### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by xiexingen** [umijs/dumi#85]
### Versions

- dumi:^1.0.0-beta.5
- node:v10.16.3
- npm:6.13.7
- OS:window 10
- Browser:chrome 80.0.3987.122 x64

### Steps to reproduce
代码如截图所示
![image](https://user-images.githubusercontent.com/7939085/75304929-85606780-587f-11ea-963b-354045bbb4b1.png)

### What is Expected?
应该有less文件中定义的样式
### What is actually happening?
![image](https://user-images.githubusercontent.com/7939085/75305020-d83a1f00-587f-11ea-8749-4daef5695c4b.png)
组件上样样式名有，但是没有对应的样式值

**Comment by PeachScript** [comment]
看截图你似乎使用的是 father-doc 而不是改名之后的 dumi？

father-doc 是基于 Umi 2，默认启用了 CSS Modules，需要手动禁用；建议切换到 dumi，基于全新的 Umi 3，更智能的 CSS Modules 启用方式，无需手动开关便能符合预期
