### ISSUE TITLE
bug: 当设定APP_ROOT=dumi后，Edit this doc on GitHub 的链接指向有问题

### ISSUE THREAD

**Issue by MrSeaWave** [umijs/dumi#856]
### Versions

- dumi: 1.1.26
- node: v15.2.1
- npm: 7.0.8
- OS: Mac
- Browser: Chrome

### Steps to reproduce

复现仓库可查看[dumi-demo](https://github.com/MrSeaWave/dumi-demo)

```bash
$ yarn
$ npm run docs:start
```

打开 `http://localhost:3000/guide` 或者 `http://localhost:3000/components/basic/pkg-a` 

![2021-08-31 10 50 04](https://user-images.githubusercontent.com/21967852/131433859-6040ba45-2097-4403-b1c2-39bab4efa9a8.gif)

### What is Expected?

期望指向正常的链接位置

### What is actually happening?

实际指向链接如图所示

![image](https://user-images.githubusercontent.com/21967852/131433286-7d13c2f3-4b01-434c-ae9d-034dc2206bf0.png)

**Comment by PeachScript** [comment]
v1.1.27 已修复
