### ISSUE TITLE
bug: 文档刷新后就404了

### ISSUE THREAD

**Issue by sl1673495** [umijs/dumi#86]
### Steps to reproduce
打开文档中的任意子页面，然后刷新
### What is Expected?
能够正常展示页面
### What is actually happening?
页面直接404了

尤其是https://umijs.github.io/dumi/write-demo#/config 这个页面根本就没办法进去

**Comment by PeachScript** [comment]
感谢反馈，已修复

**Comment by hefeng6500** [comment]
为啥我的博客刷新后依然是 404 呢？ "dumi": "^1.1.10",  求指点 https://hefeng6500.github.io/blog/algorithm/algorithm-complexity

**Comment by PeachScript** [comment]
@hefeng6500 默认产物不支持非根目录的 GitHub Pages 部署方式，两个办法：
1. 产物不放入 blog 文件夹，通过域名根目录访问
2. 产物部署到 blog 仓库的 gh-pages 分支，可以通过 `域名/blog` 访问
