### ISSUE TITLE
请问如何设置三级菜单，以及如何实现侧边栏目录折叠？

### ISSUE THREAD

**Issue by GuardZhu** [umijs/dumi#861]
### Question
1，请问侧边栏如何设置三级菜单展示
2，请问如何实现侧边栏菜单目录折叠
### Sample Code
1，如侧边栏菜单结构如下
编程语言
    Java
        Java基础.md
        Java进阶.md
    Python
        Python基础.md
        Python进阶.md
2，如上所示
编程语言，Java，Python等菜单，怎样实现折叠？收起来，否则当前菜单下面如果文件过多，展示，查看就比较麻烦，相对来说不是那么友好

**Comment by GuardZhu** [comment]
![侧边栏](https://user-images.githubusercontent.com/32634812/132151435-17dacb4a-605d-4228-a767-2cc41ff313f8.png)

**Comment by PeachScript** [comment]
Duplicate of #748 

默认主题暂无支持这两项功能的计划，有需要可以自定义主题

**Comment by florencemu** [comment]
https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠

**Comment by swustzzh** [comment]
@florencemu 仓库删掉了？请问有新的仓库地址吗？

> https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠

**Comment by kuaimeizheng** [comment]
> https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠

仓库删掉显示为空，请问有新的仓库地址吗？

**Comment by swustzzh** [comment]
您的邮件已收到。----------------------张智慧----------------------

**Comment by kuaimeizheng** [comment]
@florencemu 仓库删掉显示为空，请问有新的仓库地址吗？

**Comment by kuaimeizheng** [comment]
> 仓库删掉显示为空，请问有新的仓库地址吗？

仓库删掉显示为空，请问有新的仓库地址吗？

**Comment by kuaimeizheng** [comment]
> https://www.npmjs.com/package/dumi-theme-rdpe 支持多级菜单+可折叠

仓库删掉显示为空，请问有新的仓库地址吗？
