### ISSUE TITLE
外部 demo 不支持引入其它 md 类型文档吗？

### ISSUE THREAD

**Issue by HaiYoungs** [umijs/dumi#864]
### Question
因为除了我们封装的组件之外，我们还想加一些antd原生组件的一些 demo 放在组件库文档里面发布，同时希望把已封装的组件维护在一起，于是把剩余 demo 放在了 doc 目录下，但这样好像又显得很分散。我想可不可以把组件库demo（已封装的和没封装的）都放在 docs 下，在 docs 下通过外部 demo 方式直接引入组件库源码中的 md 文档，但好像 dumi 不支持这样引入。请问这种情况怎么样解决比较好？

### Sample Code
![image](https://user-images.githubusercontent.com/44990400/132295210-e0e52bd7-493e-4d27-8810-d02c101942d0.png)

**Comment by PeachScript** [comment]
外部 demo 是用来引入 React Component 的，不能引入 md

**Comment by HaiYoungs** [comment]
> 外部 demo 是用来引入 React Component 的，不能引入 md
好的，那请问这种情况有没有更好的解决方案呢

**Comment by PeachScript** [comment]
参考 embed 用法：https://d.umijs.org/zh-CN/guide/basic#embed

**Comment by HaiYoungs** [comment]
> 参考 embed 用法：https://d.umijs.org/zh-CN/guide/basic#embed
试过了，可以的！
