### ISSUE TITLE
bug: markdown 图片为中文地址乱码 

### ISSUE THREAD

**Issue by czb128abc** [umijs/dumi#865]
![image](https://user-images.githubusercontent.com/339385/132438888-2ca636fc-0102-4fc2-838b-f171a2ececbe.png)
`./docs/css-demo/01/demo.md
Module not found: Can't resolve '../../assets/images/%E8%9C%BB%E8%9C%93%E5%B9%BF%E6%92%ADUI.jpg' in '/Users/mac/workspace/tt/code/dumi-blog/docs/css-demo/01'
 `
### Versions

- dumi:1.1.25
- node:v14.15.3
- npm:6.14.9
- OS: mac os
- Browser: chrome last

**Comment by PeachScript** [comment]
v1.1.27 已修复
