### ISSUE TITLE
bug: 启动报错 path没有判空处理，Cannot read property 'path' of undefined TypeError: Cannot read property 'path' of undefined     at /node_modules/@umijs/preset-dumi/lib/routes/decorator/redirect.js:133:196

### ISSUE THREAD

**Issue by wayofwade** [umijs/dumi#872]
### Versions

- dumi:  1.1.26
- node: v15.12.0
- npm: 7.6.3
- OS: mac
- Browser: 

### Steps to reproduce

yarn dev 项目启动的时候报错，项目不能正常启动。报错信息如下：
Cannot read property 'path' of undefined
TypeError: Cannot read property 'path' of undefined
    at /Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/redirect.js:133:196
    at Array.forEach (<anonymous>)
    at Object.redirect (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/redirect.js:87:10)
    at /Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:63:27
    at Array.reduce (<anonymous>)
    at RouteDecorator.process (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:62:28)
    at _default (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/decorator/index.js:82:20)
    at /Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/getRouteConfig.js:127:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/chencongcong/code/web/galaxy/node_modules/@umijs/preset-dumi/lib/routes/getRouteConfig.js:70:103)
✨  Done in 18.18s.

我的.umirc.js的配置如下
menus: {
'/docs': [
{
title: '通用',
children: ['../docs/docs/common/start.md', '../docs/docs/common/changelog.md'],
}
]
}

### What is Expected?

希望yarn dev 项目正常启动，而不是报错

### What is actually happening?

 可以说是必现，对path属性进行判空，就可以正常启动了

**Comment by PeachScript** [comment]
<img width="797" alt="图片" src="https://user-images.githubusercontent.com/5035925/133059689-6e2305a3-17c2-48b0-814f-393888ab4941.png">

menus 的 children 配置改成 `docs/common/start.md` 试下

**Comment by wayofwade** [comment]
> <img alt="图片" width="797" src="https://user-images.githubusercontent.com/5035925/133059689-6e2305a3-17c2-48b0-814f-393888ab4941.png">
> 
> menus 的 children 配置改成 `docs/common/start.md` 试下

我试了下  也不行

**Comment by PeachScript** [comment]
请更新复现仓库为你修改后的版本

**Comment by wayofwade** [comment]
> 请更新复现仓库为你修改后的版本

你好 已经更新仓库了

**Comment by PeachScript** [comment]
<img width="290" alt="图片" src="https://user-images.githubusercontent.com/5035925/133075781-a699aaa0-0c0a-41e6-809e-e52fc6593807.png">

仓库 clone 下来无法复现，步骤如下：
```bash
$ git clone https://github.com/wayofwade/dumi-fix-bug-demo.git
$ cd dumi-fix-bug-demo
$ npm i
$ npm start
```

**Comment by wayofwade** [comment]
> <img alt="图片" width="290" src="https://user-images.githubusercontent.com/5035925/133075781-a699aaa0-0c0a-41e6-809e-e52fc6593807.png">
> 
> 仓库 clone 下来无法复现，步骤如下：
> 
> ```shell
> $ git clone https://github.com/wayofwade/dumi-fix-bug-demo.git
> $ cd dumi-fix-bug-demo
> $ npm i
> $ npm start
> ```

你好，修改了配置之后我这边也可以了。感谢回复！！！

但是我觉得你们工具新老版本应该兼容的，我之前报错是因为老版本的配置，使用的是相对路径。
更新了新版本之后老代码就报错了，报错的原因就是我上面说的，把老的代码更新了就可以了。

我建议你们改一下这个判空处理的报错，因为有的用户和我一样，版本升级之后就报错了，用户体验不太好。

**Comment by PeachScript** [comment]
这个设定应该挺久了，老版本是指哪个版本？

**Comment by wayofwade** [comment]
> 这个设定应该挺久了，老版本是指哪个版本？

之前使用的是"dumi": "^1.0.35"

**Comment by PeachScript** [comment]
👌报错信息后续版本我们优化下，感谢反馈
