### ISSUE TITLE
father-build build的时候我在tsx里引入import style from "./index.less";  报模块找不到，请问这里是怎么配置，.fatherrc.ts

### ISSUE THREAD

**Issue by dongcer** [umijs/dumi#874]
### Question
$ father-build Clean dist directory Build cjs with babel Clean lib directory  src\commonFC\FWTable\index.tsx(3,19): error TS2307: Cannot find module './index.less' or its corresponding type declarations. src\Foo\index.tsx(2,19): error TS2307: Cannot find module './index.less' or its corresponding type declarations.
### Sample Code
export default {
  // esm: 'rollup',
  // cjs: 'rollup',
  cssModules: true,
  esm: 'babel',
  cjs: 'babel',
  // cssModules: true,
  // runtimeHelpers: true,
  lessInBabelMode: true,
  // extractCSS: true,

  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
    ],
  ],
  extraPostCSSPlugins: [],
};

**Comment by PeachScript** [comment]
参考：https://github.com/umijs/father/issues/227#issuecomment-720928000 ，后续 father-build 相关问题请到 father 仓库提交 issue
