### ISSUE TITLE
bug: markdown解析

### ISSUE THREAD

**Issue by lxw15337674** [umijs/dumi#875]
| **参数** | **说明**           | **类型**                               | **默认值** | 必填 |
| -------- | ------------------ | -------------------------------------- | ---------- | ---- |
| effect   | 可执行函数         | `() => (void |() => void| undefined))` | -          | 否   |
| deps     | 传入依赖变化的对象 | `array`                                | -          | 是   |

### Versions

- dumi: `1.0.16`
- node:`15.12.0`
- npm:`7.6.3`
- OS: `windows 10`
- Browser:`edge`

### What is Expected?
![image](https://user-images.githubusercontent.com/19898669/133062206-e44558eb-2285-41da-a906-a88f300bb9d9.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/19898669/133061690-42d1e54e-9832-41b6-ad3a-104463d3dc2e.png)

**Comment by PeachScript** [comment]
在 Markdown 语法中，表格里的 `|` 要转义成 `\|`
