### ISSUE TITLE
feat: 外部demo能否支持传参

### ISSUE THREAD

**Issue by scrapstation** [umijs/dumi#880]
### Description
文档中多处使用antd的image组件做预览图，代码如下
是否可以传递参数给code标签内的tsx
![image](https://user-images.githubusercontent.com/56467036/133230057-8c33cbc2-6610-4fe8-84d6-3ceb874c7f15.png)

### Solution
暂无

**Comment by PeachScript** [comment]
不支持，demo 要确保所有行为用户可见；这种场景应该用自定义本地组件，参考主题开发：https://d.umijs.org/zh-CN/theme/development
