### ISSUE TITLE
Q: 自定义主题builtins组件，使用Image组件src传参，编译后路径不对

### ISSUE THREAD

**Issue by scrapstation** [umijs/dumi#881]
### Question
#880 
### Sample Code
![image](https://user-images.githubusercontent.com/56467036/133360152-5ef9952e-1dd6-4549-9c72-9fac438f9453.png)
![image](https://user-images.githubusercontent.com/56467036/133361091-845eb197-9fe1-43aa-9604-af3edb019b96.png)
![image](https://user-images.githubusercontent.com/56467036/133361108-f8d4d617-2db3-494f-8b41-f1471249faea.png)

**Comment by PeachScript** [comment]
自定义组件的属性值不会经过编译器，应该把图片都仍在 `<project-root>/public/static` 文件夹下，然后用 `src="/static/xx.jpg"`

**Comment by scrapstation** [comment]
可以解决 多谢
