### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by 2362446788** [umijs/dumi#884]
### Question
使用官网npx @umijs/create-dumi-lib --site # 初始化一个站点模式的组件库开发脚手架报错
npm版本 15.12.0
![image](https://user-images.githubusercontent.com/45731115/133545279-4c29eb64-97b6-4eac-85ac-654eea534223.png)

**Comment by PeachScript** [comment]
package.json 里的 react 改成 `^17.0.0` 再重装试试

**Comment by 2362446788** [comment]
这么处理是可以的，但是出错的原因是什么呢。

**Comment by PeachScript** [comment]
你写的 issue 标题就是原因，需要更新下 dumi 脚手架

**Comment by 2362446788** [comment]
npx 这个不是默认最新的dumi脚手架吗

**Comment by PeachScript** [comment]
是脚手架模板的问题，已发布修复版本，重新初始化可以正常安装
