### ISSUE TITLE
如果文档权限不想被公开，除了内网，还有没有可能设置一套权限体系呢？

### ISSUE THREAD

**Issue by axinjs** [umijs/dumi#885]
如果文档权限不想被公开，除了内网，还有没有可能设置一套权限体系呢？必须让用户登录之内的才能访问。

**Comment by PeachScript** [comment]
可参考 Umi 的运行时配置：https://umijs.org/zh-CN/docs/runtime-config#renderoldrender-function

**Comment by biaoqiu** [comment]
有详细的例子吗

**Comment by zhangshichun** [comment]
~感觉挡不住用户直接请求js文件吧
