### ISSUE TITLE
dumi中如何开启mock？

### ISSUE THREAD

**Issue by ldwonday** [umijs/dumi#887]
按照umi的配置方式在项目根目录下的mock文件里配置了一些mock接口，使用dumi dev命令启动后无法mock，mock的接口返回首页地址了。
![image](https://user-images.githubusercontent.com/4630157/133585507-1caf83e3-62ce-4609-a0da-c8f0f3bd416b.png)
请问使用mock呢

**Comment by Hanjijiang** [comment]
你好，你这个问题解决了吗，我也遇到这个问题。

**Comment by weird94** [comment]
same

**Comment by aoxiang78** [comment]
@Hanjijiang @weird94 
把mock文件放到项目根上不下下是可以生效的，
my_project/mock/user.ts

有谁知道如何在非根目录下的mock文件加载的话可以回复下。
