### ISSUE TITLE
bug: dumi打包内容，没有生成index.d.ts类型声明文件，应如何生成呢？

### ISSUE THREAD

**Issue by fzz14hao** [umijs/dumi#890]
dumi打包内容在dist文件夹下面未找到index.d.ts文件。应该如何生成这个文件呢？

### Versions

- dumi:^1.0.16
- node: v12.18.3
- npm: 6.14.6
- OS: win10
- Browser: Chrome

**Comment by PeachScript** [comment]
打包相关问题到 father 项目里找答案：https://github.com/umijs/father/issues/219

**Comment by fzz14hao** [comment]
配置了declaration:true依然不会生成index.d.ts 文件 不知为何?
