### ISSUE TITLE
bug: umi integrated mode build issue 

### ISSUE THREAD

**Issue by neevany** [umijs/dumi#891]
In development mode `http://localhost:8500/~docs` works fine, but when I try to build for deployment using `umi build --dumi` getting this error

```
ERROR [dumi]: cannot resolve module @/components/Image from /src/components/Home/index.md
```

I've configured `resolve.includes` as needed and it's working in dev mode.

### Versions

- dumi: "umi": "^3.5.19", "@umijs/preset-dumi": "^1.1.29",
- node: 12.18.3
- npm: 6.14.6 / yarn 1.22.10
- OS: macOS Catalina 10.15.7 (19H2)
- Browser: Chrome

### What is Expected?
prod build should work fine in umi integrated mode

**Comment by PeachScript** [comment]
Thanks for your feedback, `v1.1.30` has been fixed it, you can upgrade dumi and retry
