### ISSUE TITLE
bug: 左侧菜单导航没有active

### ISSUE THREAD

**Issue by 798714773** [umijs/dumi#892]
官网的这个链接 https://d.umijs.org/zh-CN/guide#%E6%9E%84%E5%BB%BA%E5%8F%8A%E9%83%A8%E7%BD%B2

构建及部署左侧没有小圆点，左侧导航没有定位到对应，没有class active 。点击也没有效果。
官网有这个bug，我自己也遇到这个情况

**Comment by PeachScript** [comment]
这本质上是个交互逻辑取舍，一方面**页面滚动锚点高亮跟随**这个功能需要根据该锚点内容相对可视区域的内容来确定、逻辑判定优先；另一方面是当前可视区域的大部分内容仍然属于上一个锚点、如果高亮下一个锚点也会『文不对题』

可以访问其他具备 TOC 及锚点滚动跟随的网站，大部分所采用的逻辑都和 dumi 一致，是**可视区域内容优先**而非**URL hash 优先**

**Comment by 798714773** [comment]
https://www.midwayjs.org/doc/hooks/middleware#withcontroller

帮忙看一下midway的这个链接，它是实现了的。不清楚它是怎么做的。
可不可以做一个参数供用户选择 **可视区域内容优先** 或者 **URL hash 优先**

**Comment by PeachScript** [comment]
> 帮忙看一下midway的这个链接，它是实现了的

它用的旧版本 dumi，没有滚动锚点高亮跟随功能

> 可不可以做一个参数供用户选择

暂无计划，可视区域内容优先是通用做法，有特殊需要可以基于默认主题定制自己的主题

**Comment by 798714773** [comment]
我看了几个文档，vue也是，虽然 **可见区域内容优先** 但是点击后还是有className active，如果点击没有反应，我感觉会有点诡异
