### ISSUE TITLE
chanwebpack 没有 resolve.fallback 这一配置项

### ISSUE THREAD

**Issue by shuyuanzz** [umijs/dumi#896]
### Question
chanwebpack 没有 resolve.fallback 这一配置项
### Sample Code
 ```
  chainWebpack(memo) {
    memo.resolve.fallback    \\ undefined
  },
```

**Comment by PeachScript** [comment]
chainWebpack 相关问题可以到 webpack-chain 仓库看下：https://github.com/neutrinojs/webpack-chain
