### ISSUE TITLE
静态资源可以配置写出路径吗？目前使用的路径为 static

### ISSUE THREAD

**Issue by arleyGuoLei** [umijs/dumi#897]
### Question

如题，由于某些原因 static 路由在整个架构的 nginx 层都被拦截了，项目静态资源不能是 static 下的，导致文档静态图片加载失败

![image](https://user-images.githubusercontent.com/40717741/134843753-1b5d5039-90ab-4420-a065-4b06db9cbe94.png)

**Comment by PeachScript** [comment]
没有现成配置，只能 chainWebpack 改 url-loader 的参数：https://d.umijs.org/config#chainwebpack

**Comment by arleyGuoLei** [comment]
嗯嗯 通过 chainWebpack 已解决
