### ISSUE TITLE
本地start运行正常，build之后引用组件，antd的组件样式是有的，但是自定义样式丢失了

### ISSUE THREAD

**Issue by 156586197** [umijs/dumi#898]
### Question
嗯，我用dumi开发组件，本地start是正常的，打包发布之后，调用组件的时候，antd的样式是在的，但是，自己写的css和less样式都没了。下面是fatherrc.ts的配置，求大佬们帮我看看。
### Sample Code
export default {
  esm: 'babel',
  cjs: 'babel',
  extractCSS: true,
  cssModules: {
    generateScopedName: '[name][local]_[hash:base64:5]'
  },
  // lessInBabelMode: true,
  extraBabelPlugins: [
    [
      'babel-plugin-import',
      {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
      },
      'antd',
    ]
  ]
};

**Comment by dongcer** [comment]
> ### Question
> 嗯，我用dumi开发组件，本地start是正常的，打包发布之后，调用组件的时候，antd的样式是在的，但是，自己写的css和less样式都没了。下面是fatherrc.ts的配置，求大佬们帮我看看。
> 
> ### Sample Code
> export default { esm: 'babel', cjs: 'babel', extractCSS: true, cssModules: { generateScopedName: '[name][local]_[hash:base64:5]' }, // lessInBabelMode: true, extraBabelPlugins: [ [ 'babel-plugin-import', { libraryName: 'antd', libraryDirectory: 'es', style: true, }, 'antd', ] ] };

请问一下是怎么解决的嘛。我也遇到同样的问题

**Comment by Fidelgithub** [comment]
关注，遇到了同样问题

**Comment by maoyaru123** [comment]
同样的问题

**Comment by banchichen** [comment]
同样的问题
