### ISSUE TITLE
【Question】非umi项目接入dumi

### ISSUE THREAD

**Issue by TinsFox** [umijs/dumi#899]
### Question
请问怎么在非umi项目上接入dumi，比如create-react-app、 create-next-app
场景是给内部的项目中业务组件库写组件文档

**Comment by PeachScript** [comment]
参考：https://d.umijs.org/zh-CN/guide/faq#%E5%A6%82%E4%BD%95%E5%9C%A8-cra-%E7%AD%89%E9%9D%9E-umi-%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-dumi
