### ISSUE TITLE
bug: dumi 升级为最新版后，本地运行不起来

### ISSUE THREAD

**Issue by zww-v5** [umijs/dumi#901]
最近有个项目重新安装了 npm 包后，发现 dumi 运行不起来，最后降级后运行起来就正常了。具体情况如下：
一、升级后运行不起来的情况
dumi 版本：
![image](https://user-images.githubusercontent.com/9295948/136336880-7bea3a47-2a5c-4a0f-9700-da92acdcf64d.png)

运行时的错误提示：
![image](https://user-images.githubusercontent.com/9295948/136337254-203355f4-1825-4259-91f6-96fda3f7dcdf.png)

二、降级后正常，操作如下：
降级操作：
![image](https://user-images.githubusercontent.com/9295948/136337444-e7a1380e-728d-4e4f-9806-f05e224028d3.png)

运行正常：
![image](https://user-images.githubusercontent.com/9295948/136337695-beb81453-2d5c-4f68-a5db-750766533d25.png)

**Comment by PeachScript** [comment]
得看项目具体怎么配的，方便搞个最小复现仓库吗
