### ISSUE TITLE
使用pnpm运行npm run build之后ts报错

### ISSUE THREAD

**Issue by henryzp** [umijs/dumi#903]
### Versions

- dumi:最新版本
- node: v14
- npm: 
- OS: 最新
- Browser: chrome最新

### Steps to reproduce

使用pnpm来安装组件库的依赖，简单写一个组件，如下：

![image](https://user-images.githubusercontent.com/3849702/136487491-7549c5c6-b05c-4d58-b5a4-446c76a53a66.png)

这里的Input使用的是`antd`的Input组件。

然后运行`npm run build`，会报ts的错误，内容为图中的文字

如果删除node_modules，使用`yarn`来安装依赖，再运行`npm run build`，是正常的

### What is Expected?

能正常运行`npm run build`

**Comment by PeachScript** [comment]
可以复现，但这个问题应该与 father-build 无关，pnpm 和 yarn 安装的依赖结构有差异，yarn 之所以能成功大概率是因为[幽灵依赖](https://rushjs.io/pages/advanced/phantom_deps/)。

回到写法本身，不建议用重新声明相同类型的方式来扩展组件 Props，即便用 yarn、下层稍微做下改动构建还是会挂，建议走 class extends 或[提取原组件 Props 类型](https://stackoverflow.com/a/55005902) 等更标准的方式，也可以社区看下其他推荐做法，issue 关闭。
