### ISSUE TITLE
是否可以支持嗅探yarn workspace工程下其它子工程的md文件

### ISSUE THREAD

**Issue by liujiayii** [umijs/dumi#911]
### Question
是否可以支持嗅探yarn workspace工程下其它子工程的md文件
### Sample Code

 ```
 packages 
 --components
 --docs(dumi子工程)
 ----umirc.ts
```

比如在umirc中配置
```
resolve: {
    includes: ['docs', '../components']
 },
```
可以嗅探components子工程

**Comment by PeachScript** [comment]
可以在项目根目录使用 dumi，https://d.umijs.org/zh-CN/guide/basic#lerna-%E9%A1%B9%E7%9B%AE

**Comment by liujiayii** [comment]
> 可以在项目根目录使用 dumi，https://d.umijs.org/zh-CN/guide/basic#lerna-%E9%A1%B9%E7%9B%AE

放在根目录跟项目里的public/index.html和src/app.tsx 又有冲突了🤦🏻‍♀️

**Comment by PeachScript** [comment]
monorepo 下创建 src 确实比较奇怪，这个点后续优化掉
