### ISSUE TITLE
interface里有子类型时API组件如何写才能正确显示?

### ISSUE THREAD

**Issue by Shen-Shuyi** [umijs/dumi#913]
### Question

源文件如下:  
```tsx
export interface A {
  /** xxxx */
 name: string;
}

export interface B {
  /** xxxxx */
  aa: A;
  id: number;
}

const Comp =  ({aa, id}: B) => {
  return <div>{aa.name}{id}</div>
}

export default Comp;
```

然后md文件中写了<API />, 但是只显示B接口的信息  
按照文档写成 `<API exports='["default", "A"]'></API>` 却报错: TypeError: Cannot read properties of undefined (reading 'map')

**Comment by PeachScript** [comment]
只有被导出成 React 组件的 Props 定义才能被正常解析

**Comment by PeachScript** [comment]
在 #914 跟进，closed
