### ISSUE TITLE
bug: build Can't resolve '@@/dumi/apis' 

### ISSUE THREAD

**Issue by lxw15337674** [umijs/dumi#917]
开启mfsu后，编译报错，
```
 mfsu: {
    development: {
      output: '/.mfsu-dev',
    },
    production: {
      output: '/.mfsu-prod',
    },
  },
```

### Versions
项目链接：https://github.com/lxw15337674/ww-hooks/tree/report
- dumi: 1.1.31
- node:  v14.15.1
- npm:
- OS: windows
- Browser:

### Steps to reproduce
1. yarn
2. yarn run docs:build
### What is Expected?
build success
### What is actually happening?
build failed
![7dd6a80f53c038d9f1b14fcf1098a44](https://user-images.githubusercontent.com/19898669/138835366-5826e580-5a50-4a08-9ee9-464b44aa809e.png)

**Comment by PeachScript** [comment]
v1.1.33 已修复
