### ISSUE TITLE
bug: github action build failed

### ISSUE THREAD

**Issue by lxw15337674** [umijs/dumi#926]
### Versions

- dumi: 1.1.31
- node:
- npm:
- OS:
- Browser:

### What is Expected?

build success

### What is actually happening?
根据文档配置github actions自动部署
https://d.umijs.org/zh-CN/guide/faq#%E9%83%A8%E7%BD%B2%E5%88%B0github-pages
build报错如下：
https://github.com/lxw15337674/ww-hooks/runs/4063689933?check_suite_focus=true

**Comment by PeachScript** [comment]
报错没问题，`demo` 文件夹确实不存在，请自行修正；如果本地用的是 macOS 可能可以构建成功，因为 macOS 的文件系统默认大小写不敏感

**Comment by lxw15337674** [comment]
已解决，多谢
