### ISSUE TITLE
Logo的链接可以修改嘛

### ISSUE THREAD

**Issue by Echo-minn** [umijs/dumi#927]
### Question
1、点击logo跳转的链接可以修改嘛，现在是默认跳转到index页面
2、logo和title的配置支持写一个Element覆盖嘛
现在的配置文件是ts应该不支持直接给变量赋值Element，其他地方有暴露接口可以修改嘛

**Comment by PeachScript** [comment]
不支持，只能自定义 layout 替换默认的

**Comment by Echo-minn** [comment]
我已经写了layout，dumi的history跟umi好像不太一样，history.push("https://domain.com/")会报错

**Comment by Echo-minn** [comment]
我在查阅dumi文档的时候发现很多都跟umi相似，但又不完全一样，所以我经常在两个文档里面来回翻看，不知道可以不可以在dumi文档里面写一下有哪些设计是跟umi保持一致的，哪里又不一样

**Comment by Echo-minn** [comment]
> 不支持，只能自定义 layout 替换默认的

在umi里，我在根目录的app.tsx文件里自定义layout，大概是做了什么处理，这个layout自动就覆盖了默认的
但我在dumi里，同样的写法，并没有生效，请问有什么文档可以参考嘛

**Comment by PeachScript** [comment]
参考官网文档主题部分：https://d.umijs.org/zh-CN/theme/development
