### ISSUE TITLE
渲染自定义组件时，可以仅渲染，不对用户可见源码咩

### ISSUE THREAD

**Issue by Echo-minn** [umijs/dumi#929]
### Question
使用<code />渲染自定义组件的时候，源码也是对用户可见的，可以隐藏掉源码咩

**Comment by PeachScript** [comment]
主题中的自定义组件是不会展示源码的，具体怎么用的

**Comment by Echo-minn** [comment]
> 主题中的自定义组件是不会展示源码的，具体怎么用的
在MD文件里面直接使用<code src='../../component/xxx.tsx'></code>，这个component是我自己封装的

**Comment by Echo-minn** [comment]
> 主题中的自定义组件是不会展示源码的，具体怎么用的
在MD文件里面直接使用<code src='../../component/xxx.tsx'></code>，这个component是我自己封装的

**Comment by PeachScript** [comment]
refer: https://d.umijs.org/zh-CN/config/frontmatter#inline

也可以变成本地主题的自定义组件：https://d.umijs.org/zh-CN/theme/development#%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84
