### ISSUE TITLE
Dumi支持qiankun吗

### ISSUE THREAD

**Issue by LPink777** [umijs/dumi#931]

**Comment by PeachScript** [comment]
支持，安装 [@umijs/plugin-qiankun](https://umijs.org/plugins/plugin-qiankun) 即可

**Comment by LPink777** [comment]
> 支持，安装 [@umijs/plugin-qiankun](https://umijs.org/plugins/plugin-qiankun) 即可

启用了之后静态资源404，publicPath怎么设置呀？

**Comment by PeachScript** [comment]
qiankun 使用问题请在 qiankun 文档或 issue 中找答案，https://qiankun.umijs.org/zh/faq#%E4%B8%BA%E4%BB%80%E4%B9%88%E5%BE%AE%E5%BA%94%E7%94%A8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%B5%84%E6%BA%90%E4%BC%9A-404
