### ISSUE TITLE
dumi 如何自定义侧边菜单栏？

### ISSUE THREAD

**Issue by hexintao** [umijs/dumi#932]
### dumi 是否支持自定义侧边菜单栏？
现在业务需求，侧边的菜单栏需要有三级，并且有分组折叠的功能，但是经过各种尝试，发现最多只能有二级（markdown 的锚点无法切换右边的内容，所以不算）。尝试了 umi 的 layout 插件，但是不起作用。求指点。。

**Comment by PeachScript** [comment]
默认主题只支持两级，有需要可以自定义主题：https://d.umijs.org/zh-CN/theme/development
