### ISSUE TITLE
resolve.includes 相对路径抛出异常

### ISSUE THREAD

**Issue by dominicleo** [umijs/dumi#934]
```bash
RangeError: path should be a `path.relative()`d string, but got <filename>
```

repo: https://github.com/dominicleo/dumi-example

**Comment by PeachScript** [comment]
不支持解析项目根路径之外的目录，这种场景应该把配置放在 monorepo 的根目录启动

**Comment by dominicleo** [comment]
那么文档站点配置、主题、依赖文件都要放在根目录，我们是希望把文档站点收拢到 monorepo 子包里

**Comment by PeachScript** [comment]
不能既 收拢文档 又 耦合其他子包，正常来说 monorepo 的子包间只存在 NPM 的依赖关系
