### ISSUE TITLE
bug: tsx里必须得引react，不然会报错 

### ISSUE THREAD

**Issue by GitKou** [umijs/dumi#937]
### Versions

- dumi: dumi@1.1.31
- node: v16.9.1
- npm: 7.21.1
- OS:MacBook Pro  (13-inch, M1, 2020)
- Browser: Chrome 95.0.4638.69
-  react@17.0.2

### Steps to reproduce
在md的tsx写组件，必须要引入react，但是引入后eslint又会报错，不引入，就渲染失败
![image](https://user-images.githubusercontent.com/7437397/141077549-acc6fd37-72bc-4d4c-9485-feff83391723.png)

![image](https://user-images.githubusercontent.com/7437397/141077853-f125aa8a-bf86-4acd-b422-4c49504eecdf.png)

### What is Expected?
期待，无需在demo种无需引入react

**Comment by imwangming** [comment]
你升级到react 17不就行了

**Comment by GitKou** [comment]
> 你升级到react 17不就行了

react@17.0.2
。。。。

**Comment by PeachScript** [comment]
这是 ts 的警告，把 tsconfig.json 里的 `jsx` 选项改成 `react` 即可；dumi 强制 React 引入是有意为之，目的是让 demo 源代码可以在不同的 React 版本中正常运行，随着 React 17 的普及这个限制会在未来去掉

refer: https://d.umijs.org/zh-CN/guide/demo-principle#%E5%8E%9F%E5%88%99%E4%BA%8C%E4%BE%9D%E8%B5%96%E6%B8%85%E6%99%B0

**Comment by joriewong** [comment]
虽然遵循了[dumi Demo理念的原则二](https://d.umijs.org/zh-CN/guide/demo-principle#%E5%8E%9F%E5%88%99%E4%BA%8C%E4%BE%9D%E8%B5%96%E6%B8%85%E6%99%B0)，但从整个文档项目的角度看，每个.md里code block的`react`导入是冗余的且和外部demo导入的写法(React v17.x)不一致。
