### ISSUE TITLE
怎么在md里按需加载antd的组件样式

### ISSUE THREAD

**Issue by gouding** [umijs/dumi#938]
![image](https://user-images.githubusercontent.com/13016673/141112105-072736aa-340c-4783-8eab-43b1a667e056.png)
![image](https://user-images.githubusercontent.com/13016673/141112172-4d8600ea-2383-4787-b074-d0226af29d13.png)
现在是标签能出现，但antd的组件样式出不来

**Comment by gouding** [comment]
ok , i did
要先安装babel-plugin-import，根据官网的按需引有项目里的样式变了下

`yarn add babel-plugin-import `

然后.umirc.ts里添加相应配置
```extraBabelPlugins: [
    [
      'import',
      {
        "libraryName": "antd",`  
        "libraryDirectory": "es",
        "style": true
      }
    ],
  ]```

**Comment by Mluocheng** [comment]
[](https://user-images.githubusercontent.com/31057183/157367383-38d1de59-d869-4dd9-a3ad-6c34b2dfd303.png)[](https://user-images.githubusercontent.com/31057183/157367402-b613b217-229f-47b2-80d5-9dba83d0e0f3.png)配置了
extraBabelPlugins: [
[
'babel-plugin-import',
{
libraryName: 'antd',
libraryDirectory: 'es',
style: true,
},
'antd',
],
],
之后 有遇到这个问题吗
image
我是这样写的：
image
