### ISSUE TITLE
相同文件结构，Menu 渲染结构不同

### ISSUE THREAD

**Issue by boomsi** [umijs/dumi#939]
### Question

Button 和 Message 文件结构相同
![image](https://user-images.githubusercontent.com/39713960/141226452-f6aa55bb-8781-4aad-b150-779b3cad8fc4.png)

到 UI 上 message 却多出一个二级 Menu，message 组件只有一个 export default 
![image](https://user-images.githubusercontent.com/39713960/141226501-52b48541-6222-4bdd-af5d-414b81043148.png)

我尝试复制一个 Button 组件为 ButtonAnother，然后 ButtonAnother 也出现了二级 Menu

### Sample Code

`.umirc` 代码

```ts
export default defineConfig({
  title: 'boy-ui',
  favicon:
    'https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png',
  logo: 'https://user-images.githubusercontent.com/9554297/83762004-a0761b00-a6a9-11ea-83b4-9c8ff721d4b8.png',
  outputPath: 'docs-dist',
  // more config: https://d.umijs.org/config
  apiParser: {
    propFilter: {
      skipNodeModules: true,
      skipPropsWithName: [],
      skipPropsWithoutDoc: false,
    },
  },
});

```

**Comment by boomsi** [comment]
![image](https://user-images.githubusercontent.com/39713960/141227920-3f4c3f06-169e-4fcf-affa-70dc6fd9eaf4.png)
.umi 文件的 config.json

**Comment by PeachScript** [comment]
给个复现仓库，推测 `Message/index.md` 的 title 或者一级标题没有首字母大写

**Comment by boomsi** [comment]
> 给个复现仓库，推测 `Message/index.md` 的 title 或者一级标题没有首字母大写

确实是这样，感谢
