### ISSUE TITLE
希望能够支持多级文件夹

### ISSUE THREAD

**Issue by laoniu85** [umijs/dumi#944]
目前dumi支持的文件夹层数最多为2层，超过2层的仍然按照2层显示，是否能够考虑支持更多层的文件夹？

**Comment by PeachScript** [comment]
暂时没有计划，组件研发场景下两层完全足够，参考 Ant Design 等常见 UI 组件库的文档；建议优先考虑优化文档结构，有特殊需要一定要多层、可以自定义主题包实现
