### ISSUE TITLE
可以修改文档里面的代码demo样式吗？

### ISSUE THREAD

**Issue by lzx-cloud** [umijs/dumi#946]
### 可以修改文档里面的代码demo样式吗？

![image](https://user-images.githubusercontent.com/29159297/142344383-f3801231-6eee-47a1-8507-4c0362bd1eb9.png)

**Comment by PeachScript** [comment]
可以参考这个 FAQ 引入 prism 的其他主题的 CSS ：https://d.umijs.org/guide/faq#how-does-dumi-support-to-highlight-for-languages-such-as-swift-c-kotlin
