### ISSUE TITLE
bug: group的path设置成了一样变成一个分组后，order失效

### ISSUE THREAD

**Issue by yangjinjun3** [umijs/dumi#954]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
src/packages/CompA/index.md：
group:
  path: /
  title: balabala
  order: 2

src/packages/CompB/index.md：
group:
  path: /
  title: balabala
  order: 3

### What is Expected?
order正常排序，越小越靠前

### What is actually happening?
小的order没有靠前

**Comment by PeachScript** [comment]
感觉上目录结构并非支持的 monorepo 结构，可以先参考：https://d.umijs.org/guide/basic#lerna-project

**Comment by yangjinjun3** [comment]
我就是想实现截图效果，顶部有个导航叫组件，左侧导航里的每个分组里有多个组件！请问该参考那个结构，然后md该怎么写呢？

<img width="1230" alt="111" src="https://user-images.githubusercontent.com/44964193/142755660-310136b8-d458-4c91-9717-568fc9ed85ba.png">

**Comment by PeachScript** [comment]
非 monorepo 按照 `src/components/{ComponentName}/index.md` 的路径规则创建 md 即可，或者 `src/{ComponentName}/index.md` + `nav.path` 设置为 `/components`

monorepo 可参考 ahooks：https://github.com/alibaba/hooks
