### ISSUE TITLE
基于antd封装一个私有npm包，但打包后只有Button有样式，其他组件样式丢失

### ISSUE THREAD

**Issue by gouding** [umijs/dumi#956]
基于antd封装一个私有npm包，在其他项目里使用这个包时，只有Button有样式，其他组件样式丢失，怎么处理，升级了最新的dumi、father-build还是不行

**Comment by xiaohuoni** [comment]
import Button from 'antd/es/button'
import 'antd/es/button/styles/index.css'

**Comment by gouding** [comment]
我再描述清楚一些

以下两张图是基于dumi架子
![image](https://user-images.githubusercontent.com/13016673/142981549-e363a793-f368-410f-9534-58f4f492ff9e.png)
![image](https://user-images.githubusercontent.com/13016673/142981696-0fc2047c-9190-4718-9906-bcf535e31910.png)

以下是在第三方系统中使用我们封装的组件（father打包后的npm包）
![image](https://user-images.githubusercontent.com/13016673/142981881-63670802-ea21-40aa-af54-11f28ea1dfad.png)

**Comment by gouding** [comment]
![image](https://user-images.githubusercontent.com/13016673/142983541-463961ce-462b-49d3-80ef-af42880866cf.png)

在npm包里和第三方项目里都配置了按需加载，  但是antd的样式还是出不来

**Comment by PeachScript** [comment]
提供复现仓库

**Comment by banchichen** [comment]
我参考 #225 这个issue解决了，我使用的1.1.38版本
