### ISSUE TITLE
dumi是否支持修改antd前缀

### ISSUE THREAD

**Issue by XIAJIEXUWEI** [umijs/dumi#958]
场景：组件内自定义了antd前缀，使用dumi dev启动项目，antd前缀并未被修改，但是组件前缀已被修改，导致antd样式不生效

问题：dumi是否有一种方法可以在启动时修改antd样式前缀

![image](https://user-images.githubusercontent.com/24544138/142986446-ddabe6bc-7d70-425f-a25f-bb709de036d0.png)

**Comment by XIAJIEXUWEI** [comment]
图片是我在组件内的webpack打包配置，dumi dev启动时不生效

**Comment by xiaohuoni** [comment]
config - theme 配置

**Comment by XIAJIEXUWEI** [comment]
> config - theme 配置

![image](https://user-images.githubusercontent.com/24544138/143150559-5dea2747-2d45-40ae-82d1-ea41f36407fd.png)
配置了，并没有生效

**Comment by XIAJIEXUWEI** [comment]
问题已找到，使用了antd组件ConfigProvider处理前缀，完美解决

**Comment by ChenYCL** [comment]
有提供全局的配置么，每个组件都要抱一层的话

**Comment by bici-fed** [comment]
我现在也遇到了，每个组件包一层很麻烦啊

**Comment by PeachScript** [comment]
套一层 layout 即可，https://d.umijs.org/theme/development#custom-body-area

**Comment by crazyair** [comment]
> 套一层 layout 即可，https://d.umijs.org/theme/development#custom-body-area

链接失效了，现在要怎么配置

**Comment by PeachScript** [comment]
v1 文档：https://v1.d.umijs.org/theme/development#custom-body-area
v2 文档：https://d.umijs.org/theme 创建 GlobalLayout

**Comment by crazyair** [comment]
useOutlet 类型没有导出
![image](https://user-images.githubusercontent.com/7971419/223689494-355fec42-6b83-4455-a8fd-591dbb08947e.png)

useLocale 怎么不变，一直是中文
![image](https://user-images.githubusercontent.com/7971419/223689402-a52ff488-6bf1-4791-9103-1848dc1155e2.png)

**Comment by PeachScript** [comment]
@crazyair 其他问题可以单独提 issue + 提供复现

**Comment by XiaMin-sisi** [comment]
@PeachScript  只需要建一个GlobalLayout其他主题文件都可以不要吗

**Comment by XiaMin-sisi** [comment]
@PeachScript  修改好了前缀，但是antd的样式失效了？怎么解决呢
