### ISSUE TITLE
发布到公司服务器上刷新不正常

### ISSUE THREAD

**Issue by yangjinjun3** [umijs/dumi#960]
### Versions

- dumi:
- node:
- npm:
- OS:
- Browser:

### Steps to reproduce
打包后，将产物上传到公司内部服务器上（非github），比如点击alert组件，开始正常显示（见截图1），手动刷新后跳转到目录页（见截图2）

复现仓库：
https://github.com/worldzhao/react-ui-library-tutorial

### What is Expected?
刷新后还正常显示

### What is actually happening?
刷新后跳转到目录页
<img width="1564" alt="WechatIMG31" src="https://user-images.githubusercontent.com/44964193/143207352-a178dbdc-601b-4867-9266-670471375039.png">
<img width="941" alt="WechatIMG34" src="https://user-images.githubusercontent.com/44964193/143207365-7debd462-806e-4d80-a0ee-39605c4941e5.png">

**Comment by PeachScript** [comment]
既然 GitHub Pages 是可以渲染的，应该改服务器配置吧…

**Comment by yangjinjun3** [comment]
服务器配置指的是？

**Comment by PeachScript** [comment]
HTTP Server 的配置，取决于服务器具体用的什么方案，可以到对应方案的 issue 找一下
