### ISSUE TITLE
bug: <API /> src 指向错误

### ISSUE THREAD

**Issue by zoffyzhang** [umijs/dumi#961]
### Versions

- dumi: 1.1.33
- node: 14.17.0
- npm:
- OS: win10
- Browser: chrome 96

### Steps to reproduce

最小复现仓库 https://github.com/zoffyzhang/dumi-bug-report

我给每个组件都写了 \<API src="./API.tsx" /> ，但渲染出来 API 都是一样的。

![Snipaste_2021-11-25_18-46-10](https://user-images.githubusercontent.com/11470090/143427769-6720dc4e-4841-42c6-ad2b-701c15da062a.png)

![Snipaste_2021-11-25_18-46-35](https://user-images.githubusercontent.com/11470090/143427780-abf93886-6368-42ac-b726-2d1e790ad291.png)

**Comment by PeachScript** [comment]
组件名是 API 的唯一键，两个 API 的 default 导出都没有组件名，所以 API 元数据被覆盖了
