### ISSUE TITLE
bug: mobile: false not working when click demo

### ISSUE THREAD

**Issue by PeachScript** [umijs/dumi#962]
### Versions

- dumi: 1.1.33
- node: *
- npm: *
- OS: *
- Browser: *

### Steps to reproduce

1. Use `dumi-theme-mobile`
2. Configure `mobile: false` for a test page
3. Click demo in the test page

### What is Expected?

Nothing happened.

### What is actually happening?

The mobile demo previewer rendered.

**Comment by hangaoke1** [comment]
mark

**Comment by PeachScript** [comment]
Fixed in v1.1.34
