### ISSUE TITLE
组件含有图片资源，打包后引用不到，如何配置

### ISSUE THREAD

**Issue by ly01112020** [umijs/dumi#964]
###  code
cost test = require('@/assets/images/test.png')
...
<img src={test}> 

在编写md文档正常显示，打包后引入组件报错 找不到 @/assets/images/test.png

**Comment by linlinNB** [comment]
也遇到这个问题，看到有的答案说在chain-webpack里面去配置，但是不得起法。。。。。目前我的处理方式，把图片这些资源放在图床上

**Comment by scw1997** [comment]
同样问题+1
