### ISSUE TITLE
请问dumi支持下载Excel文档吗

### ISSUE THREAD

**Issue by changlin0501** [umijs/dumi#965]
### Question
请问dumi支持下载Excel文档吗

**Comment by PeachScript** [comment]
文档里加个超链接即可？下载的文件可以放 CDN，或者可以放入 [public](https://umijs.org/zh-CN/docs/directory-structure#public-%E7%9B%AE%E5%BD%95) 文件夹和文档一起作部署

**Comment by changlin0501** [comment]
解决了，谢谢！
