### ISSUE TITLE
Bug: 打包过程出错

### ISSUE THREAD

**Issue by a1ooha** [umijs/dumi#967]
### Versions

- dumi: 1.1.33
- node: 12.20.1
- npm: 7.20.2
- OS: macOS Monterey
- Browser: Chrome 94.0.4606.81

### Steps to reproduce

使用了 https://replit.com/@moudy/codemirror6-test 里的代码，但在 dumi 里 `npm start` 时会报错，但 `npm run build` 不会报错。

`.fatherrc.ts` 的配置是：

```ts
export default {
  esm: 'rollup',
  // cjs: 'rollup',
  runtimeHelpers: true,
};
```

可复现 repo：https://github.com/a1ooha/react-codemirror

### What is Expected?

在项目里直接 wepback 打包上面的代码是正常的，所以代码应该没问题。

### What is actually happening?

compile 过程报错：

![image](https://user-images.githubusercontent.com/13401668/144180204-5706c7d9-2806-4702-abe2-b4824b3eaaa2.png)

**Comment by PeachScript** [comment]
> 在项目里直接 wepback 打包上面的代码是正常的

找一下项目的 webpack 配置，大概率要额外挂某些 babel 插件，或者 babel-loader 的配置和 Umi 默认的不一样，可以 chainWebpack 修改

**Comment by a1ooha** [comment]
是 @babel/preset-env 里的 @babel/plugin-proposal-unicode-property-regex 的 bug， https://github.com/babel/babel/issues/13815

**Comment by a1ooha** [comment]
直接使用 umi 打包也是正常的

**Comment by jo0ger** [comment]
@a1ooha 怎么解决呢？我也遇到了这个问题
