### ISSUE TITLE
.eslintrc.js 配置无效

### ISSUE THREAD

**Issue by misty-zq** [umijs/dumi#969]
### Question

请问！为什么我配置的hooks规则不起作用？...

### Sample Code

![image](https://user-images.githubusercontent.com/49603449/144345236-253ef20c-7e91-4898-85ac-54be64724e4f.png)
![image](https://user-images.githubusercontent.com/49603449/144345263-cd76da0f-8147-4857-893d-60a6e6c6f30f.png)
![image](https://user-images.githubusercontent.com/49603449/144345316-a00a7a62-a58b-4d38-b76e-d15e51fee3b2.png)

**Comment by PeachScript** [comment]
不是 dumi 的功能范围，请在 ESLint 和相关 ESLint 插件项目里找解决方案
