### ISSUE TITLE
bug: can't resolve dependency when use resolve config

### ISSUE THREAD

**Issue by McDaddy** [umijs/dumi#970]
### Versions

- dumi: 1.1.33
- node: v14
- npm: v6
- OS: MacOS

### Steps to reproduce

checkout my reproduce repo branch https://github.com/McDaddy/erda-ui-components/tree/issue

run `npm start`, then I get below error

what I do next is rename `components` to `src` and remove `resolve` config.

finally everything goes well

So I guess the `resolve` config has bug inside

### What is actually happening?
![image](https://user-images.githubusercontent.com/5175455/144382827-b70098eb-e41b-46d2-a2fd-14e524d8fea4.png)

**Comment by PeachScript** [comment]
`components` is a non-standard source code directory, so you must configure alias from `erda-ui-components` to `components` directory manually: https://d.umijs.org/config#alias

**Comment by McDaddy** [comment]
> 



> `components` is a non-standard source code directory, so you must configure alias from `erda-ui-components` to `components` directory manually: https://d.umijs.org/config#alias

thx your quick help. I'm wondering is there any guide in official docs? I think it's a very common scenario that change src folder name, but I don't see hint in `resolve` config section

**Comment by PeachScript** [comment]
This behavior is nothing to do with `resolve` config, there has a simple explanation in the [guide](https://d.umijs.org/guide/basic#using-component-in-demo), any idea to improve it?

**Comment by McDaddy** [comment]
> This behavior is nothing to do with `resolve` config, there has a simple explanation in the [guide](https://d.umijs.org/guide/basic#using-component-in-demo), any idea to improve it?

@PeachScript  I did read this guide `Using component in demo` before developing, the information from this guide for me is dumi could automatically link the package to the folder I specified.

`dumi will create an alias for us between library NPM package and library source code` as a user, I was thinking this behavior should be `auto`. Please correct me if any misunderstanding
