### ISSUE TITLE
feature: 支持 typescript 4.5.2

### ISSUE THREAD

**Issue by bigbigDreamer** [umijs/dumi#971]
```ts
import React, { type FC } from 'react';
```

### Description

现在启动报错，大概率是内部解析的 `eslint`报出来的，希望提供支持。

### Solution

`eslint`、`@typescript-eslint/parser`

**Comment by bigbigDreamer** [comment]
Now report error @PeachScript 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/39019913/144801307-0f7026f2-cc03-48f0-a723-10a707a449c6.png">

**Comment by PeachScript** [comment]
Umi 层 babel 已升级至最新，closed
