### ISSUE TITLE
.dumi/theme/style下覆盖默认主题色没有生效

### ISSUE THREAD

**Issue by BoBoooooo** [umijs/dumi#972]
### Question
如题
### Sample Code
![image](https://user-images.githubusercontent.com/25972237/144994410-797b0e70-ca67-4ed2-ab3e-0de1ed787100.png)

如图所示，修改variables.less中的@c-primary没有反应，依旧为默认主题色。

**Comment by PeachScript** [comment]
使用 theme 配置项配置默认主题的 Less 变量：https://d.umijs.org/config#theme

**Comment by BoBoooooo** [comment]
> 使用 theme 配置项配置默认主题的 Less 变量：https://d.umijs.org/config#theme

![image](https://user-images.githubusercontent.com/25972237/145318182-4521b832-048c-4766-9241-f095fc9a20fc.png)

你好，使用theme是可以的，但是文档此处是否应该为更正为@c-primary，使用@primary-color是不生效的。

**Comment by PeachScript** [comment]
@BoBoooooo 感谢建议，文档已更正：https://d.umijs.org/config#theme
