### ISSUE TITLE
如何修改 src 目录？

### ISSUE THREAD

**Issue by WinmezzZ** [umijs/dumi#975]
### Question
默认组件目录在 src 下，可以设置为其他目录吗？（src命名目前被占用了）。

不修改现有 src 的命名 的情况，dumi能动态配置组件所在的根目录吗

**Comment by PeachScript** [comment]
> 默认组件目录在 src 下，可以设置为其他目录吗？

修改 [`resolve.includes`](https://d.umijs.org/zh-CN/config#resolve) 可以配置解析的目录；但 father-build 目前不支持定制源码目录，如果要做打包的话只能换其他工具，新的 father 3 出来后可以支持定制源码目录

> 不修改现有 src 的命名 的情况，dumi能动态配置组件所在的根目录吗

dumi 只是做了一次 alias，默认是把组件库 NPM 包名映射到 src，可以自行通过 [`alias`](https://d.umijs.org/zh-CN/config#alias) 配置包名映射目标目录
