### ISSUE TITLE
bug: mobile主题下，多个demo代码预览时，切换不生效

### ISSUE THREAD

**Issue by imgss** [umijs/dumi#976]
### Versions

- dumi: 1.1.35 
- dumi-theme-mobile: 1.1.18
- node: 14.16.1
- npm: 7.20.1
- OS: MacOs
- Browser: chrome 96

### Steps to reproduce
1. 在一个Md文件下写多个代码片段
2. 在生成的页面中，点击第二，第三个代码块，观察右侧的模拟器是否显示相应的内容

### What is Expected?

期望可以预览其他代码片段渲染出来的内容

### What is actually happening?
模拟器展示的依然是第一个代码片段渲染出的内容

**Comment by PeachScript** [comment]
v1.1.36 已修复

**Comment by houchaowei** [comment]
# Versions
dumi: 1.1.38
dumi-theme-mobile: 1.1.24
node: 16.20.2
npm: 8.19.4
OS: MacOs
Browser: chrome 125

# Steps to reproduce
在一个Md文件下写多个代码片段
在生成的页面中，点击第二，第三个代码块，观察右侧的模拟器是否显示相应的内容
# What is Expected?
期望可以预览其他代码片段渲染出来的内容

# What is actually happening?
模拟器展示的依然是第一个代码片段渲染出的内容


现在还有这个问题
