### ISSUE TITLE
为什么react依赖用的不是peerDependencies

### ISSUE THREAD

**Issue by wywppkd** [umijs/dumi#977]
### 为什么react依赖用的不是peerDependencies, 而是dependencies, 但是也能排除在打包之外

```js
// ...
  "dependencies": {
    "react": "^16.12.0 || ^17.0.0"
  },
// ...
```

我看 father-build 文档约定 peerDependencies 排除打包的

![image](https://user-images.githubusercontent.com/20620574/145742249-7334950f-010b-4073-993d-64a0ed293011.png)

**Comment by bigbigDreamer** [comment]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/39019913/145812702-12f90e6b-09be-455a-bad1-dde8e7939742.png">

可以看下 `father-build` 中 `rollup` 获取打包配置的源码，只要是排除打包在外的，一定跟`external`离不开关系～

[](https://github.com/umijs/father/blob/ce8b1c9a09557fec6538cf7b487a0af737e76d2f/packages/father-build/src/getRollupConfig.ts#L108)
