### ISSUE TITLE
export 多个 interface/type，dumi 会依次展示每个 interface/type 的表格

### ISSUE THREAD

**Issue by woliuCN** [umijs/dumi#979]
export 多个 interface/type，dumi 会依次展示每个 interface/type 的表格

_Originally posted by @PeachScript in https://github.com/umijs/dumi/issues/515#issuecomment-766922911_

**Comment by woliuCN** [comment]
有大佬试了么，我试了export多个并不会生成多个～

**Comment by PeachScript** [comment]
目前只能识别 React Component 的导出，普通 interface/type 不会处理
