### ISSUE TITLE
bug: 带有锚点和 Demo 的页面在滚动时会重复更新 Demo

### ISSUE THREAD

**Issue by kagawagao** [umijs/dumi#98]
### Versions

- dumi: `1.0.0`
- node: `3.7.0`
- npm: `6.13.7`
- OS: `MacOS 10.15.4 Beta(19E242d)`
- Browser: `82.0.4075.0`

### Steps to reproduce

创建一个有 Demo 的文档页面，同时页面有多个锚点

滚动页面

### What is Expected?

Demo 不重新渲染

### What is actually happening?

Demo 重复渲染

在线地址：https://g2plot-react.netlify.com/examples/line

**Comment by lijinke666** [comment]
+1 感觉是锚点改变时就会重新渲染

**Comment by kagawagao** [comment]
@lijinke666 确实是这样

**Comment by PeachScript** [comment]
问题修复了，试下 v.1.02
