### ISSUE TITLE
请问如何在不写 demo 的情况下，如何向 ～demo 插入新的一个路由

### ISSUE THREAD

**Issue by raohong** [umijs/dumi#981]
### Question
请问如何在不写 demo 的情况下，如何向 ～demo 插入新的一个路由
### Sample Code

现在要生成 demo 里的路由必须写一个 demo ， 但是手机demo上可能需要一个导航页。

现在我用 umi 的插件插入路由，但是不生效，正确食用方式？

```ts
import { IApi } from 'umi';
import path from 'path';

export default (api: IApi) => {
  api.modifyRoutes((routes) => {
    routes.push({
      component: path.join(__dirname, '.dumi/theme/DemoNav.tsx'),
      path: '/~demos',
      layout: false,
      wrappers: ['../dumi/layout'],
      exact: true,
    });

    return routes;
  });
};
```

或者：

现在在 ./.dumi/theme t添加 demo.tsx 可以自定义如何渲染 demo
可以做到 ./dumi/theme/demo 以目录的方式添加自定义 demo 路由， 比如

```./dumi/theme/demo/index.tsx```
```./dumi/theme/demo/other.tsx```

**Comment by PeachScript** [comment]
不建议魔改路由表，`~` 开头的是框架层的特殊路由，目前没有计划开放给用户定制，建议用 md 生成常规路由（比如 `/demos`）来罗列 demo

**Comment by xiaohuoni** [comment]
@raohong 参考这里 https://github.com/xiaohuoni/umi-plugin-mobile-dumi
