### ISSUE TITLE
如何配置文档全局的 Context？

### ISSUE THREAD

**Issue by WinmezzZ** [umijs/dumi#985]
### Question
如何配置文档全局的 Context？
### Sample Code
目前是这样的，我正在使用 dumi 的文档工具作为我组件库的文档，我的组件库同样支持配置暗黑模式，但是需要去在组件外层套一个 `ConfigProvider`。目前测试暗黑模式效果只能在 demo 代码中单独添加，调试起来很麻烦。

最重要的是，如果手动切换网站自带的主题切换，我无法检测到样式是否修改，黑配白的效果体验十分不好。

目前通过 `MutationObserver` 监听 html 标签上的 `data-prefers-color` 属性，能够获取实时的主题色，但是是否有办法支持我去配置网站的入口 jsx 去让我添加 `ConfigPovider` 呢？

**Comment by PeachScript** [comment]
用 `import { usePreferColor } from 'dumi/theme'` 去获取主题色：https://d.umijs.org/zh-CN/theme/api#usepreferscolor
用自定义的 `.dumi/theme/layout` 去初始化 Context：https://d.umijs.org/zh-CN/theme/development#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%AD%A3%E6%96%87%E5%8C%BA%E5%9F%9F

**Comment by swiftwind0405** [comment]
> * 用 `import { usePreferColor } from 'dumi/theme'` 去获取主题色：https://d.umijs.org/zh-CN/theme/api#usepreferscolor
> * 用自定义的 `.dumi/theme/layout` 去初始化 Context：https://d.umijs.org/zh-CN/theme/development#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%AD%A3%E6%96%87%E5%8C%BA%E5%9F%9F

大佬求解第二种方法详细用法，官网的案例没明白
