### ISSUE TITLE
bug: 单页面内的锚点目录，无法设置为右侧悬浮

### ISSUE THREAD

**Issue by eleven-net-cn** [umijs/dumi#986]
dumi: v1.1.37

过去版本，页面内锚点目录默认是 `content `，右侧悬浮效果。现在，即使显式设定 `toc: content` 也无效，无法设置为右侧悬浮。

**Comment by PeachScript** [comment]
官网正常的：https://d.umijs.org/lab
如果是移动端，toc 强制渲染到 sidemenu 里了，这是 1.1.37 的 feature 不是 bug：https://github.com/umijs/dumi/releases/tag/dumi%401.1.36
但似乎有个点可以优化，没有 demo、或者 `mobile: false` 的页面还是可以不强制渲染到 sidemenu 里

**Comment by zuosamu** [comment]
这个feature....

**Comment by eleven-net-cn** [comment]
> 官网正常的：https://d.umijs.org/lab 如果是移动端主题，toc 强制渲染到 sidemenu 里了，这是 1.1.37 的 feature 不是 bug：https://github.com/umijs/dumi/releases/tag/dumi%401.1.36 但似乎有个点可以优化，没有 demo、或者 `mobile: false` 的页面还是可以不强制渲染到 sidemenu 里

建议不做强制，而是默认 content 效果，把选择权留给使用者。
现在这种强制的效果，看上去更像是一个 bug，文档里没有介绍，比较费解。

**Comment by PeachScript** [comment]
v1.1.38 已做优化：
1. 如 @eleven-net-cn 建议所述，强制 `toc: menu` 修改为默认 `toc: menu`，开发者可以覆盖默认值
2. 如果页面没有 demo，不会触发规则 1
3. 如果页面级配置 `mobile: false` 不走移动端 demo 渲染，也不会触发规则 1
