### ISSUE TITLE
如何配置全局的ConfigProvider

### ISSUE THREAD

**Issue by McDaddy** [umijs/dumi#989]
### Question
当我们在基于antd开发组件库的时候，一般都会覆盖他的prefix，所以在写md的时候就必须在组件外面套一个ConfigProvider
比如如下的代码， 在dumi的配置我只找到可以修改less变量的theme配置，没有找到可以全局改ConfigProvider的方法。
否则就需要每个组件的md demo都要手动套一个ConfigProvider。 感觉很麻烦。
请问有解决的办法吗？

### Sample Code
```
import React from 'react';
import { Button, ConfigProvider } from 'xxx-ui-components';

export default () => (
  <ConfigProvider prefixCls="xxx">
    <Button type="primary">FUCK</Button>
  </ConfigProvider>
);
```

**Comment by McDaddy** [comment]
感觉只能自己设默认值。虽然有点麻烦

**Comment by PeachScript** [comment]
参考：https://github.com/umijs/dumi/issues/985
