### ISSUE TITLE
自定义标签如何不被渲染在.markdown里面

### ISSUE THREAD

**Issue by Linginnn** [umijs/dumi#993]
![image](https://user-images.githubusercontent.com/16818104/147865062-9f35d5a8-2a0b-4fa2-ac78-316d3078b6df.png)

红色是自定义的tabs标签，如何让他渲染和.markdown那个节点同级，而不是在他下面

**Comment by PeachScript** [comment]
确实不应该被 .markdown 容器包裹，会有样式污染，相关逻辑：https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/transformer/remark/isolation.ts#L11

**Comment by PeachScript** [comment]
v1.1.40 已修复，前后有空行、独立存在的自定义组件不会被 `.markdown` 容器包裹
