### ISSUE TITLE
dumi项目中引用了 plugin-model插件但是显示找不到是怎么回事

### ISSUE THREAD

**Issue by dongcer** [umijs/dumi#998]
### Question
![image](https://user-images.githubusercontent.com/35223950/148945797-9d80d0d3-c515-4a53-a1f6-9c9b75f6aacb.png)

### Sample Code

import React from 'react';
import { useModel } from 'umi';

interface SonProps {
  /** 是否禁用 */

}

const Auth: React.FC<SonProps> = (props: any) => {
  const masterProps = useModel('@@qiankunStateFromMaster');
  console.log(masterProps);
  
  return (
    <div></div>
  );
};
export default Auth;

**Comment by taojiangcb** [comment]
plugin-model 和 plugin-request 都不能用.

**Comment by susanred** [comment]
这个问题什么时候能解决？

**Comment by PeachScript** [comment]
plugin-model 是给应用研发用的，不能用于组件库研发

**Comment by Junior125306** [comment]
@dongcer 我现在有同样得需求，大哥你当时咋处理的
