### ISSUE TITLE
自定义菜单配置疑问

### ISSUE THREAD

**Issue by xoptimal** [umijs/dumi#999]
已知我的目录下是
src
------
|----a (index.md)
|----b (index.md)
|----c (index.md)

自定义 nav的时候, 我想创建一个 components , 然后把这 a,b,c 放进去, 但是dumi是按路径生成的,
访问/components/a 是无效的,
访问/a是正常的
我该如何访问components/a的时候, 是正常的 ???

```
menus: {
  '/components': [
    {
      title: 'A',
      path: '/components/a'
    },
    {
      title: 'B',
      path: '/components/b'
    },
    {
      title: 'C',
      path: '/components/c'
    }
  ]
},
navs: [
  {
    title: '文档',
    path: '/intro',
  },
  {
    title: '组件',
    path: '/components',
  },
  {
    title: 'GitHub',
    path: 'https://github.com/umijs/dumi',
  },
]
```

**Comment by xoptimal** [comment]
@xiaohuoni

**Comment by PeachScript** [comment]
menus 仅仅决定菜单生成，不会决定路由表的生成；所以确保 `{a,b,c}/index.md` 的 `nav.path` 都配置在 `/components` 下即可，配置参考：https://d.umijs.org/zh-CN/config/frontmatter#navpath
